export type DifficultyLevel = 1 | 2 | 3 | 4 | 5;

export const difficultyConfig: Record<DifficultyLevel, { label: string; color: string; bg: string }> = {
  1: { label: "Beginner", color: "text-emerald-700", bg: "bg-emerald-100" },
  2: { label: "Easy", color: "text-green-700", bg: "bg-green-100" },
  3: { label: "Moderate", color: "text-amber-700", bg: "bg-amber-100" },
  4: { label: "Hard", color: "text-orange-700", bg: "bg-orange-100" },
  5: { label: "Expert", color: "text-red-700", bg: "bg-red-100" },
};

export const lessonDifficulty: Record<string, DifficultyLevel> = {
  "heart-failure": 3,
  "hypertension": 2,
  "peds-cardiac-basics": 3,
  "cardiac-assessment-ecg": 2,
  "cardiac-cycle-hemodynamics": 3,
  "conduction-system": 3,
  "cardiac-monitoring": 2,
  "pad-claudication": 2,
  "cardioversion-defib": 3,
  "pacemaker-care": 3,
  "respiratory-assessment": 1,
  "lung-auscultation": 2,
  "oxygen-therapy-basics": 1,
  "inhaled-spacers": 1,
  "abg-basics": 3,
  "neuro-basics": 2,
  "stroke": 2,
  "delirium-dementia": 2,
  "parkinsons": 2,
  "peds-neuro": 3,
  "gerd-peptic": 2,
  "liver-cirrhosis": 3,
  "peds-gi-basics": 2,
  "bowel-obstruction": 2,
  "ostomy-care": 2,
  "appendicitis": 1,
  "cholecystitis": 2,
  "pancreatitis": 3,
  "celiac-disease": 2,
  "diabetes-basics": 2,
  "thyroid-basics": 2,
  "adrenal-basics": 2,
  "peds-endo": 3,
  "cushing-addison": 3,
  "diabetic-emergencies": 3,
  "uti-basics": 1,
  "aki-basics": 3,
  "kidney-stones": 2,
  "fluid-balance": 2,
  "peds-renal": 3,
  "skin-integrity": 1,
  "burns-basics": 2,
  "peds-skin": 2,
  "psoriasis-eczema": 2,
  "skin-cancer": 2,
  "contact-dermatitis": 1,
  "impetigo-cellulitis": 2,
  "decubitus-staging": 2,
  "labor-delivery": 2,
  "prenatal-care": 1,
  "postpartum-basics": 2,
  "newborn-assessment": 2,
  "breastfeeding": 1,
  "gestational-diabetes": 3,
  "preeclampsia-basics": 3,
  "newborn-jaundice": 2,
  "apgar-scoring": 1,
  "maternal-hemorrhage": 3,
  "newborn-thermoregulation": 2,
  "neonatal-respiratory": 3,
  "neonatal-hypoglycemia": 2,
  "neonatal-sepsis": 3,
  "neonatal-abstinence": 3,
  "kangaroo-care": 1,
  "developmental-milestones": 2,
  "immunization-schedule": 1,
  "growth-assessment": 1,
  "pediatric-fever": 1,
  "croup-epiglottitis": 2,
  "bronchiolitis-rsv": 2,
  "peds-asthma": 2,
  "pyloric-stenosis": 2,
  "intussusception": 3,
  "kawasaki-disease": 3,
  "sickle-cell-basics": 3,
  "leukemia-basics": 3,
  "nephrotic-syndrome": 3,
  "peds-diabetes": 3,
  "cerebral-palsy": 2,
  "cleft-lip-palate": 2,
  "downs-syndrome": 2,
  "failure-to-thrive": 2,
  "osteoporosis-basics": 2,
  "scoliosis-basics": 2,
  "hip-dysplasia": 2,
  "fracture-sprain-care": 2,
  "fracture-types": 2,
  "cast-care": 1,
  "rom-exercises": 1,
  "mobility-aids": 1,
  "joint-replacement-basics": 2,
  "mental-health-basics": 2,
  "anxiety-depression": 2,
  "bipolar-disorder": 3,
  "schizophrenia": 3,
  "substance-abuse": 2,
  "eating-disorders": 2,
  "therapeutic-communication": 1,
  "suicide-prevention": 2,
  "elder-abuse": 1,
  "vitals-assessment": 1,
  "wound-care-basics": 1,
  "vac-dressing": 3,
  "wound-irrigation": 1,
  "cleansing-enemas": 1,
  "meds-to-infants": 2,
  "safe-med-admin": 1,
  "injection-sites": 1,
  "iv-therapy-basics": 2,
  "blood-glucose-monitoring": 1,
  "specimen-collection": 1,
  "nasogastric-tube": 2,
  "catheter-care": 1,
  "fall-prevention": 1,
  "infection-control-basics": 1,
  "hand-hygiene": 1,
  "ppe-precautions": 1,
  "sterile-technique": 2,
  "isolation-precautions": 1,
  "chain-infection": 1,
  "concussion-assessment": 2,
  "cranial-nerve-assessment": 2,
  "icp-basics": 3,
  "gcs-assessment": 2,
  "seizure-precautions": 2,
  "aaa-rupture": 4,
  "cardiac-tamponade": 4,
  "acute-mi": 3,
  "chest-pain-assessment": 3,
  "atrial-fibrillation": 3,
  "heart-failure-rn": 3,
  "endocarditis": 4,
  "pericarditis": 3,
  "dvt-pe-rn": 3,
  "valve-disease": 4,
  "aortic-dissection": 5,
  "polycythemia": 4,
  "carotid-endarterectomy": 4,
  "dvt-management": 3,
  "cardiogenic-shock": 5,
  "ards-rn": 4,
  "pneumonia-rn": 3,
  "pneumothorax": 4,
  "pulmonary-embolism": 4,
  "resp-failure": 4,
  "mechanical-ventilation": 5,
  "copd-exacerbation": 3,
  "asthma-emergency": 3,
  "status-asthmaticus": 4,
  "pleural-effusion": 3,
  "increased-icp": 4,
  "status-epilepticus": 4,
  "spinal-cord-rn": 4,
  "brain-injury": 4,
  "meningitis-rn": 3,
  "stroke-advanced": 4,
  "autonomic-dysreflexia": 4,
  "meniere-disease": 3,
  "duchenne-md": 3,
  "spina-bifida": 3,
  "myasthenia-gravis": 4,
  "guillain-barre": 4,
  "neuritis-neuropathy": 3,
  "liver-failure": 4,
  "gi-bleed": 4,
  "crohn-uc": 3,
  "esophageal-varices": 4,
  "hepatic-encephalopathy": 4,
  "acute-pancreatitis-rn": 4,
  "aki-management": 4,
  "electrolyte-safety": 3,
  "ckd-management": 3,
  "rhabdomyolysis": 4,
  "av-fistula": 3,
  "dialysis-steal": 4,
  "hemodialysis-care": 4,
  "bph-management": 3,
  "dka-management": 4,
  "thyroid-storm": 5,
  "addisonian-crisis": 5,
  "pheochromocytoma": 5,
  "siadh-management": 4,
  "diabetes-insipidus": 4,
  "compartment-syndrome": 4,
  "burn-management": 4,
  "pressure-injury": 3,
  "knee-arthroplasty": 3,
  "osteomyelitis": 4,
  "rheumatoid-arthritis": 3,
  "osteoporosis-rn": 3,
  "amputation-care": 3,
  "hip-fracture-rn": 3,
  "preeclampsia-rn": 4,
  "hellp-syndrome": 5,
  "placenta-previa": 4,
  "placental-abruption": 4,
  "ruptured-ectopic": 4,
  "postpartum-endometritis": 3,
  "uterine-inversion": 5,
  "mastitis": 2,
  "postpartum-depression-care": 3,
  "postpartum-psychosis": 4,
  "neonatal-rds": 4,
  "neonatal-hie": 5,
  "neonatal-sepsis-rn": 4,
  "meconium-aspiration": 4,
  "neonatal-seizures": 4,
  "prematurity-complications": 4,
  "neonatal-cardiac": 5,
  "hydrops-fetalis": 5,
  "pediatric-seizures": 3,
  "cystic-fibrosis": 4,
  "pediatric-burns": 3,
  "child-abuse": 2,
  "elder-mistreatment": 2,
  "intimate-partner-violence": 2,
  "disaster-triage": 3,
  "airborne-precautions": 2,
  "droplet-precautions": 2,
  "contact-precautions": 2,
  "transmission-based-precautions": 2,
  "blood-transfusion": 3,
  "chest-tube-mgmt": 4,
  "trach-care": 4,
  "thoracentesis": 3,
  "postmortem-care": 2,
  "burn-care-advanced": 4,
  "comprehensive-health-assessment": 3,
  "primary-survey-rn": 3,
  "secondary-survey-rn": 3,
  "rapid-assessment-rn": 3,
  "focused-assessment-rn": 3,
  "ecg-interpretation-rn": 4,
  "cardiac-rhythm-rn": 4,
  "hemodynamic-assessment-rn": 5,
  "nih-stroke-scale": 3,
  "gcs-advanced-rn": 3,
  "neuro-checks-rn": 3,
  "cranial-nerve-exam-rn": 4,
  "icp-monitoring-rn": 5,
  "scat5-assessment-rn": 3,
  "respiratory-assessment-rn": 3,
  "abg-interpretation-rn": 4,
  "ventilator-assessment-rn": 5,
  "chest-assessment-rn": 3,
  "airway-assessment-rn": 3,
  "cardiac-auscultation-rn": 4,
  "jvd-assessment-rn": 3,
  "peripheral-vascular-rn": 3,
  "abdominal-assessment-rn": 3,
  "ascites-assessment-rn": 3,
  "hepatojugular-reflux-rn": 4,
  "trauma-assessment-rn": 4,
  "burn-assessment-rn": 3,
  "wound-classification-rn": 3,
  "pressure-injury-staging-rn": 3,
  "pain-assessment-rn": 2,
  "sedation-scale-rn": 3,
  "delirium-screening-rn": 3,
  "suicide-risk-assessment-rn": 3,
  "mental-status-exam-rn": 3,
  "psychiatric-assessment-rn": 3,
  "substance-screening-rn": 3,
  "fetal-monitoring-assessment-rn": 4,
  "bishop-score-rn": 3,
  "leopold-maneuvers-rn": 3,
  "postpartum-assessment-rn": 3,
  "ballard-score-rn": 4,
  "pediatric-triangle-rn": 3,
  "pediatric-early-warning-rn": 3,
  "developmental-milestones-rn": 2,
  "fluid-balance-rn": 3,
  "sepsis-screening-rn": 4,
  "postop-assessment-rn": 3,
  "discharge-readiness-rn": 2,
  "cultural-assessment-rn": 2,
  "family-assessment-rn": 2,
  "functional-assessment-rn": 2,
  "early-warning-score-rn": 3,
  "handoff-communication-rn": 2,
  "aaa-rupture-np": 5,
  "mi-management-np": 5,
  "hf-advanced-np": 5,
  "shock-syndromes-np": 5,
  "copd-exacerbation-np": 5,
  "asthma-emergency-np": 5,
  "pe-recognition-np": 5,
  "increased-icp-np": 5,
  "stroke-advanced-np": 5,
  "seizure-safety-np": 5,
  "dka-hhns-np": 5,
  "siadh-di-np": 5,
  "thyroid-storm-np": 5,
  "aki-management-np": 5,
  "electrolyte-safety-np": 5,
  "sepsis-mastery-np": 5,
  "dic-management-np": 5,
  "transfusion-reactions-np": 5,
  "tumor-lysis-np": 5,
  "hellp-syndrome-np": 5,
  "amniotic-fluid-embolism-np": 5,
  "eclampsia-np": 5,
  "obstetric-hemorrhage-np": 5,
  "neonatal-rds-np": 5,
  "neonatal-hie-np": 5,
  "persistent-pulm-htn-np": 5,
  "neonatal-abstinence-np": 5,
  "autoimmune-np": 5,
  "immunodeficiency-np": 5,
  "transplant-rejection-np": 5,
  "cytokine-cascade-np": 5,
  "pharmacokinetics-np": 5,
  "pharmacodynamics-np": 5,
  "drug-interactions-np": 5,
  "prescribing-np": 4,
  "pediatric-pharmacology-np": 5,
  "geriatric-pharmacology-np": 5,
  "psychopharmacology-np": 5,
  "antimicrobial-stewardship-np": 5,
  "opioid-management-np": 4,
  "anticoagulation-np": 5,
  "comprehensive-hpi-np": 4,
  "differential-diagnosis-np": 5,
  "clinical-reasoning-np": 5,
  "evidence-based-assessment-np": 4,
  "advanced-cardiac-auscultation-np": 5,
  "ecg-advanced-np": 5,
  "hemodynamic-monitoring-np": 5,
  "swan-ganz-np": 5,
  "cardiac-output-np": 5,
  "pft-interpretation-np": 5,
  "abg-advanced-np": 5,
  "vent-waveform-np": 5,
  "respiratory-mechanics-np": 5,
  "neuro-exam-advanced-np": 5,
  "cranial-nerve-advanced-np": 5,
  "cerebellar-exam-np": 5,
  "motor-sensory-exam-np": 4,
  "reflex-grading-np": 4,
  "brain-death-assessment-np": 5,
  "dermatological-exam-np": 4,
  "dermoscopy-np": 5,
  "msk-special-tests-np": 4,
  "joint-exam-np": 4,
  "spine-exam-np": 4,
  "gait-analysis-np": 4,
  "ophthalmoscopic-exam-np": 5,
  "otoscopic-exam-np": 4,
  "thyroid-exam-np": 4,
  "breast-exam-np": 3,
  "gynecological-exam-np": 4,
  "prenatal-assessment-np": 4,
  "fetal-surveillance-np": 5,
  "geriatric-assessment-np": 4,
  "frailty-assessment-np": 4,
  "cognitive-screening-np": 4,
  "developmental-screening-np": 4,
  "psychiatric-diagnostic-np": 5,
  "vascular-assessment-np": 4,
  "lymphedema-assessment-np": 4,
  "abdominal-exam-np": 4,
  "rectal-prostate-np": 4,
  "sofa-apache-np": 5,
  "wells-criteria-np": 5,
  "imaging-interpretation-np": 5,
  "lab-interpretation-np": 5,
  "point-of-care-us-np": 5,
  "nutritional-assessment-np": 4,
  "wound-specialist-np": 4,
  "capacity-assessment-np": 4,
  "palliative-assessment-np": 4,
  "fat-embolism-np": 5,
  "spinal-cord-injury-np": 5,
};

export function inferTierFromId(id: string): string {
  if (id.endsWith("-np")) return "np";
  if (id.endsWith("-rn")) return "rn";
  if (id.endsWith("-rpn")) return "rpn";

  const rnPatterns = [
    "aaa-rupture", "cardiac-tamponade", "acute-mi", "chest-pain-assessment",
    "atrial-fibrillation", "heart-failure-rn", "endocarditis", "pericarditis",
    "dvt-pe-rn", "valve-disease", "aortic-dissection", "polycythemia",
    "carotid-endarterectomy", "dvt-management", "cardiogenic-shock",
    "ards-rn", "pneumonia-rn", "pneumothorax", "pulmonary-embolism",
    "resp-failure", "mechanical-ventilation", "copd-exacerbation",
    "asthma-emergency", "status-asthmaticus", "pleural-effusion",
    "increased-icp", "status-epilepticus", "spinal-cord-rn", "brain-injury",
    "meningitis-rn", "stroke-advanced", "autonomic-dysreflexia",
    "meniere-disease", "duchenne-md", "spina-bifida", "myasthenia-gravis",
    "guillain-barre", "neuritis-neuropathy", "liver-failure", "gi-bleed",
    "crohn-uc", "esophageal-varices", "hepatic-encephalopathy",
    "acute-pancreatitis-rn", "aki-management", "electrolyte-safety",
    "ckd-management", "rhabdomyolysis", "av-fistula", "dialysis-steal",
    "hemodialysis-care", "bph-management", "dka-management", "thyroid-storm",
    "addisonian-crisis", "pheochromocytoma", "siadh-management",
    "diabetes-insipidus", "compartment-syndrome", "burn-management",
    "pressure-injury", "knee-arthroplasty", "osteomyelitis",
    "rheumatoid-arthritis", "osteoporosis-rn", "amputation-care",
    "hip-fracture-rn", "preeclampsia-rn", "hellp-syndrome",
    "placenta-previa", "placental-abruption", "ruptured-ectopic",
    "postpartum-endometritis", "uterine-inversion", "mastitis",
    "postpartum-depression-care", "postpartum-psychosis",
    "neonatal-rds", "neonatal-hie", "neonatal-sepsis-rn",
    "meconium-aspiration", "neonatal-seizures", "prematurity-complications",
    "neonatal-cardiac", "hydrops-fetalis", "pediatric-seizures",
    "cystic-fibrosis", "pediatric-burns", "child-abuse",
    "elder-mistreatment", "intimate-partner-violence", "disaster-triage",
    "airborne-precautions", "droplet-precautions", "contact-precautions",
    "transmission-based-precautions", "blood-transfusion", "chest-tube-mgmt",
    "trach-care", "thoracentesis", "postmortem-care", "burn-care-advanced",
  ];

  if (rnPatterns.includes(id)) return "rn";
  return "rpn";
}

export function getDifficulty(id: string, tier?: string): DifficultyLevel {
  if (lessonDifficulty[id]) return lessonDifficulty[id];
  const resolvedTier = tier || inferTierFromId(id);
  switch (resolvedTier) {
    case "rpn": return 2;
    case "rn": return 3;
    case "np": return 5;
    default: return 2;
  }
}
