const illustrationAltText: Record<string, string> = {
  "infective-endocarditis": "Hand-drawn medical illustration of infective endocarditis showing heart valve vegetation and bacterial colonies  -  NurseNest nursing education",
  "peripheral-artery-disease": "Clinical illustration of peripheral artery disease showing arterial plaque buildup and reduced blood flow  -  NurseNest nursing education",
  "pacemaker-care": "Detailed illustration of cardiac pacemaker placement and lead positioning in the heart  -  NurseNest nursing education",
  "dysrhythmias": "Medical illustration of cardiac dysrhythmias and cardioversion procedure  -  NurseNest nursing education",
  "mi-management": "Illustration of the cardiac cycle showing myocardial infarction pathophysiology  -  NurseNest nursing education",
  "mi-acute": "Clinical diagram of acute myocardial infarction with coronary artery occlusion  -  NurseNest nursing education",
  "cardiovascular-rpn": "Hand-drawn cardiovascular system overview for practical nursing education  -  NurseNest",
  "cardiovascular-rn": "Cardiovascular system anatomy and physiology illustration for registered nurses  -  NurseNest",
  "cardiovascular-np": "Advanced cardiovascular pathophysiology illustration for nurse practitioners  -  NurseNest",
  "chf-basics": "Illustration of congestive heart failure showing cardiac chamber dilation and fluid backup  -  NurseNest",
  "hf-advanced": "Advanced heart failure pathophysiology diagram with ejection fraction concepts  -  NurseNest",
  "copd-exacerbation": "Medical illustration of COPD showing airway obstruction and hyperinflated alveoli  -  NurseNest nursing education",
  "asthma-emergency": "Clinical illustration of acute asthma showing bronchospasm and airway inflammation  -  NurseNest nursing education",
  "asthma-copd": "Comparative illustration of asthma versus COPD airway pathology  -  NurseNest nursing education",
  "hand-hygiene": "Illustration of hand hygiene technique and bacterial transmission prevention  -  NurseNest nursing education",
  "ppe-basics": "Medical illustration of proper PPE donning and doffing with bacteria visualization  -  NurseNest nursing education",
  "isolation-precautions-rpn": "Illustration of virus particle structure and isolation precaution types  -  NurseNest nursing education",
  "airborne-precautions": "Clinical diagram of airborne virus transmission and respiratory protection  -  NurseNest nursing education",
  "droplet-precautions": "Illustration of droplet precaution measures with viral particle spread patterns  -  NurseNest nursing education",
  "neuritis-neuropathy": "Detailed nerve fiber illustration showing neuritis and neuropathy pathology  -  NurseNest nursing education",
  "tumor-classification": "Medical illustration of tumor classification types and staging system  -  NurseNest nursing education",
  "radiation-therapy": "Clinical illustration of radiation therapy targeting tumor cells  -  NurseNest nursing education",
  "treatment-of-cancer": "Comprehensive cancer treatment modalities illustration  -  NurseNest nursing education",
  "hodgkin-lymphoma": "Illustration of Hodgkin lymphoma showing Reed-Sternberg cells  -  NurseNest nursing education",
  "non-hodgkin-lymphoma": "Medical illustration of non-Hodgkin lymphoma cell types and lymph node involvement  -  NurseNest nursing education",
  "aki-management": "Hand-drawn kidney anatomy illustration showing acute kidney injury pathology  -  NurseNest nursing education",
  "ckd-management": "NurseNest-branded illustration of chronic kidney disease showing nephron damage, fibrosis, uremia, and fluid retention  -  NurseNest nursing education",
  "ckd": "NurseNest-branded illustration of chronic kidney disease showing shrunken kidney, reduced glomerular function, and waste buildup  -  NurseNest nursing education",
  "chronic-kidney-disease": "NurseNest-branded illustration of chronic kidney disease showing nephron damage and kidney fibrosis  -  NurseNest nursing education",
  "rhabdomyolysis": "Illustration of rhabdomyolysis showing muscle fiber breakdown and kidney impact  -  NurseNest nursing education",
  "av-fistula": "Detailed illustration of arteriovenous fistula for hemodialysis access  -  NurseNest nursing education",
  "dialysis-steal": "Medical illustration of dialysis steal syndrome and vascular access complications  -  NurseNest nursing education",
  "shock-syndromes": "Clinical illustration of shock pathophysiology showing circulatory collapse  -  NurseNest nursing education",
  "sepsis-mastery": "Illustration of sepsis cascade from infection to organ dysfunction  -  NurseNest nursing education",
  "burn-management": "Hand-drawn illustration of burn wound classification and tissue layers  -  NurseNest nursing education",
  "cellulitis": "Clinical illustration of cellulitis showing skin infection and inflammation layers  -  NurseNest nursing education",
  "cardiogenic-shock": "Medical illustration of cardiogenic shock with failing cardiac output  -  NurseNest nursing education",
  "aaa-rupture": "Illustration of abdominal aortic aneurysm with rupture risk anatomy  -  NurseNest nursing education",
  "pe-dvt": "Clinical diagram of pulmonary embolism and deep vein thrombosis pathology  -  NurseNest nursing education",
  "pe-recognition": "Medical illustration of pulmonary embolism lodged in pulmonary vasculature  -  NurseNest nursing education",
  "cardiac-monitoring": "Illustration of cardiac monitoring with ECG lead placement  -  NurseNest nursing education",
  "cardiac-rhythm-rn": "ECG rhythm interpretation illustration for registered nurses  -  NurseNest nursing education",
  "cardiac-auscultation-rn": "Heart auscultation landmarks and cardiac cycle sounds illustration  -  NurseNest nursing education",
  "hypertension-management": "Clinical illustration of hypertension effects on cardiac and vascular system  -  NurseNest nursing education",
  "aortic-dissection": "Medical illustration of aortic dissection showing intimal tear and false lumen  -  NurseNest nursing education",
  "carotid-endarterectomy": "Surgical illustration of carotid endarterectomy procedure  -  NurseNest nursing education",
  "pneumonia-basics": "Hand-drawn illustration of pneumonia showing alveolar consolidation  -  NurseNest nursing education",
  "pneumonia-management": "Clinical illustration of pneumonia treatment and lung pathology  -  NurseNest nursing education",
  "pneumonia-community": "Illustration of community-acquired pneumonia with bacterial invasion of alveoli  -  NurseNest nursing education",
  "pneumonia-hospital": "Medical illustration of hospital-acquired pneumonia and ventilator-associated infection  -  NurseNest nursing education",
  "pneumonia-aspiration": "Illustration of aspiration pneumonia showing gastric content entering airways  -  NurseNest nursing education",
  "active-tb": "Clinical illustration of active tuberculosis with lung cavitation and acid-fast bacilli  -  NurseNest nursing education",
  "tuberculosis": "Detailed tuberculosis pathology illustration showing granuloma formation  -  NurseNest nursing education",
  "latent-tb": "Illustration of latent tuberculosis infection with encapsulated granuloma  -  NurseNest nursing education",
  "tb-screening": "Medical illustration of tuberculosis screening methods and Mantoux test  -  NurseNest nursing education",
  "tracheostomy-care": "Hand-drawn illustration of tracheostomy tube placement and airway anatomy  -  NurseNest nursing education",
  "tracheostomy": "Detailed tracheostomy anatomy illustration showing tube components  -  NurseNest nursing education",
  "tracheostomy-suctioning": "Clinical illustration of tracheostomy suctioning technique  -  NurseNest nursing education",
  "laryngectomy": "Medical illustration of laryngectomy and permanent stoma  -  NurseNest nursing education",
  "parkinsons-disease": "Illustration of Parkinson disease showing dopaminergic neuron degeneration in substantia nigra  -  NurseNest nursing education",
  "parkinsons": "Clinical illustration of Parkinson disease motor symptoms and basal ganglia pathology  -  NurseNest nursing education",
  "multiple-sclerosis": "Medical illustration of multiple sclerosis showing demyelination of nerve fibers  -  NurseNest nursing education",
  "ms-management": "Illustration of multiple sclerosis nerve damage and myelin sheath destruction  -  NurseNest nursing education",
  "stroke": "Hand-drawn illustration of stroke showing ischemic and hemorrhagic brain pathology  -  NurseNest nursing education",
  "stroke-advanced": "Advanced stroke illustration with penumbra zone and cerebral circulation  -  NurseNest nursing education",
  "brain-abscess": "Clinical illustration of brain abscess with encapsulated infection  -  NurseNest nursing education",
  "delirium-vs-dementia": "NurseNest-branded illustration comparing delirium and dementia brain changes  -  NurseNest nursing education",
  "delirium": "NurseNest-branded medical illustration of delirium showing acute brain dysfunction and fluctuating consciousness  -  NurseNest nursing education",
  "dementia-care": "NurseNest-branded illustration of dementia showing progressive brain atrophy and cognitive decline  -  NurseNest nursing education",
  "dementia": "NurseNest-branded illustration of dementia showing progressive brain atrophy and cognitive decline  -  NurseNest nursing education",
  "cranial-nerve-assessment": "NurseNest-branded illustration of the twelve cranial nerves and their pathways for clinical assessment  -  NurseNest nursing education",
  "cranial-nerves": "NurseNest-branded cranial nerve anatomy diagram showing all twelve cranial nerves  -  NurseNest nursing education",
  "trigeminal-neuralgia": "Clinical illustration of trigeminal neuralgia showing affected nerve branches  -  NurseNest nursing education",
  "carpal-tunnel": "Medical illustration of carpal tunnel syndrome showing median nerve compression  -  NurseNest nursing education",
  "carpal-tunnel-syndrome": "Detailed illustration of carpal tunnel anatomy with nerve entrapment  -  NurseNest nursing education",
  "cerebral-edema": "Illustration of cerebral edema showing brain swelling and increased intracranial pressure  -  NurseNest nursing education",
  "myasthenia-gravis": "Clinical illustration of myasthenia gravis showing neuromuscular junction antibody attack  -  NurseNest nursing education",
  "concussion": "NurseNest-branded medical illustration of concussion showing brain impact, stretched axons, disrupted ion channels, and concussive pathophysiology  -  NurseNest nursing education",
  "concussion-management": "NurseNest-branded illustration of concussion management showing headache, confusion, dizziness, memory disturbance, and loss of consciousness  -  NurseNest nursing education",
  "tbi-management": "Traumatic brain injury management illustration with cerebral pathology  -  NurseNest nursing education",
  "bells-palsy": "Hand-drawn illustration of Bell palsy showing facial nerve inflammation  -  NurseNest nursing education",
  "cystic-fibrosis": "Clinical illustration of cystic fibrosis showing thick mucus in airways and CFTR defect  -  NurseNest nursing education",
  "cf-management": "Detailed cystic fibrosis pathophysiology illustration with chloride channel dysfunction  -  NurseNest nursing education",
  "pertussis-basics": "Medical illustration of pertussis (whooping cough) showing Bordetella pertussis bacteria  -  NurseNest nursing education",
  "whooping-cough": "Illustration of whooping cough airway inflammation and paroxysmal coughing mechanism  -  NurseNest nursing education",
  "bronchiectasis": "Clinical illustration of bronchiectasis showing permanently dilated bronchi  -  NurseNest nursing education",
  "bronchiectasis-management": "Detailed bronchiectasis pathology illustration with airway wall destruction  -  NurseNest nursing education",
  "pleurisy": "Medical illustration of pleurisy showing inflamed pleural membranes  -  NurseNest nursing education",
  "pleural-effusion": "Illustration of pleural effusion with fluid accumulation in pleural space  -  NurseNest nursing education",
  "chest-physiotherapy": "Hand-drawn illustration of chest physiotherapy techniques and postural drainage positions  -  NurseNest nursing education",
  "chest-physio": "Clinical chest physiotherapy illustration showing percussion and vibration techniques  -  NurseNest nursing education",
  "postural-drainage": "Illustration of postural drainage positions for respiratory secretion clearance  -  NurseNest nursing education",
  "rsv-management": "Medical illustration of respiratory syncytial virus (RSV) and bronchiolitis  -  NurseNest nursing education",
  "rsv-bronchiolitis": "Detailed RSV illustration showing viral infection of bronchioles  -  NurseNest nursing education",
  "hemoptysis": "Clinical illustration of hemoptysis showing blood in airway and potential causes  -  NurseNest nursing education",
  "hemoptysis-management": "Medical illustration of hemoptysis management and pulmonary bleeding sources  -  NurseNest nursing education",
  "abg-basics": "Illustration of arterial blood gas interpretation and electrolyte balance  -  NurseNest nursing education",
  "abg-interpretation-rn": "Detailed ABG interpretation illustration for registered nurses  -  NurseNest nursing education",
  "inflammatory-response": "Hand-drawn illustration of the inflammatory response cascade and immune cell activation  -  NurseNest nursing education",
  "inflammation": "Clinical illustration of inflammation pathways and tissue response  -  NurseNest nursing education",
  "retinal-detachment": "Medical illustration of retinal detachment showing separation of retinal layers  -  NurseNest nursing education",
  "pressure-injuries": "Illustration of pressure injury staging from Stage 1 to unstageable  -  NurseNest nursing education",
  "pressure-ulcers": "Detailed pressure ulcer illustration showing tissue damage layers  -  NurseNest nursing education",
  "pressure-injury-staging": "Clinical illustration of pressure injury staging classification system  -  NurseNest nursing education",
  "innate-immunity": "Hand-drawn illustration of the innate immune system with phagocytes and natural killer cells  -  NurseNest nursing education",
  "innate-immune-system": "Detailed innate immunity illustration showing first-line immune defenses  -  NurseNest nursing education",
  "adaptive-immunity": "Medical illustration of adaptive immune system with T-cells and B-cells  -  NurseNest nursing education",
  "adaptive-immune-system": "Detailed adaptive immunity illustration showing antibody production and memory cells  -  NurseNest nursing education",
  "immune-response": "Comprehensive immune response illustration with innate and adaptive pathways  -  NurseNest nursing education",
  "conjunctivitis": "Clinical illustration of conjunctivitis showing eye inflammation and discharge  -  NurseNest nursing education",
  "pink-eye": "Illustration of pink eye (conjunctivitis) with bacterial and viral causes  -  NurseNest nursing education",
  "aplastic-anemia": "Medical illustration of aplastic anemia showing bone marrow failure  -  NurseNest nursing education",
  "alopecia": "Hand-drawn illustration of alopecia showing hair follicle pathology  -  NurseNest nursing education",
  "alopecia-areata": "Clinical illustration of alopecia areata with autoimmune hair loss  -  NurseNest nursing education",
  "pemphigus": "Medical illustration of pemphigus vulgaris showing skin blistering and autoimmune attack  -  NurseNest nursing education",
  "pemphigus-vulgaris": "Detailed pemphigus vulgaris illustration with intraepidermal blister formation  -  NurseNest nursing education",
  "polycythemia": "Illustration of polycythemia vera showing excess red blood cell production  -  NurseNest nursing education",
  "polycythemia-vera": "Clinical illustration of polycythemia vera with bone marrow overproduction  -  NurseNest nursing education",
  "atopic-dermatitis": "Hand-drawn illustration of atopic dermatitis showing skin inflammation and eczema patterns  -  NurseNest nursing education",
  "eczema-atopic-dermatitis": "Medical illustration of eczema with skin barrier dysfunction  -  NurseNest nursing education",
  "eczema": "Clinical illustration of eczema showing inflammatory skin response  -  NurseNest nursing education",
  "otitis-media": "Illustration of otitis media showing middle ear infection and fluid buildup  -  NurseNest nursing education",
  "otitis-externa": "Clinical illustration of otitis externa (swimmer ear) with external ear canal infection  -  NurseNest nursing education",
  "ear-infection": "Medical illustration of ear infection anatomy and inflammatory response  -  NurseNest nursing education",
  "stevens-johnson-syndrome": "Hand-drawn illustration of Stevens-Johnson syndrome showing severe skin reaction  -  NurseNest nursing education",
  "toxic-epidermal-necrolysis": "Clinical illustration of toxic epidermal necrolysis with epidermal detachment  -  NurseNest nursing education",
  "herpes-simplex": "Medical illustration of herpes simplex virus showing vesicular skin lesions  -  NurseNest nursing education",
  "hsv": "Illustration of HSV infection with viral replication in epithelial cells  -  NurseNest nursing education",
  "cold-sores": "Clinical illustration of cold sores showing herpes labialis pathology  -  NurseNest nursing education",
  "herpes-zoster": "Hand-drawn illustration of herpes zoster (shingles) showing dermatomal distribution  -  NurseNest nursing education",
  "herpes-zoster-shingles": "Medical illustration of shingles with varicella-zoster virus reactivation  -  NurseNest nursing education",
  "shingles": "Clinical illustration of shingles showing nerve-distributed vesicular rash  -  NurseNest nursing education",
  "varicella-zoster": "Illustration of varicella-zoster virus lifecycle and reactivation  -  NurseNest nursing education",
  "glaucoma": "Detailed illustration of glaucoma showing increased intraocular pressure and optic nerve damage  -  NurseNest nursing education",
  "glaucoma-management": "Medical illustration of glaucoma management with aqueous humor drainage  -  NurseNest nursing education",
  "vitiligo": "Hand-drawn illustration of vitiligo showing melanocyte loss and depigmentation patterns  -  NurseNest nursing education",
  "cell-structure": "Detailed cell structure illustration showing organelles and membrane components  -  NurseNest nursing education",
  "cell-biology": "Clinical cell biology illustration with labeled cellular organelles  -  NurseNest nursing education",
  "homeostasis": "Illustration of homeostasis feedback loops showing negative and positive feedback mechanisms  -  NurseNest nursing education",
  "feedback-loops": "Medical illustration of physiological feedback loop regulation  -  NurseNest nursing education",
  "psoriasis": "Clinical illustration of psoriasis showing epidermal hyperproliferation and plaque formation  -  NurseNest nursing education",
  "contact-dermatitis": "Illustration of contact dermatitis showing allergic skin reaction  -  NurseNest nursing education",
  "melanoma": "Medical illustration of melanoma showing malignant melanocyte transformation  -  NurseNest nursing education",
  "urticaria": "Clinical illustration of urticaria (hives) showing mast cell histamine release  -  NurseNest nursing education",
  "scabies": "Medical illustration of scabies mite infestation in skin layers  -  NurseNest nursing education",
  "impetigo": "Illustration of impetigo showing superficial bacterial skin infection  -  NurseNest nursing education",
  "anaphylaxis": "Clinical illustration of anaphylaxis showing systemic allergic response  -  NurseNest nursing education",
  "compartment-syndrome": "NurseNest-branded illustration of compartment syndrome showing fascial compression, ischemia, blood flow obstruction, and fasciotomy  -  NurseNest nursing education",
  "malignant-hyperthermia": "Illustration of malignant hyperthermia showing uncontrolled muscle metabolism  -  NurseNest nursing education",
  "ards-management": "Clinical illustration of acute respiratory distress syndrome with alveolar damage  -  NurseNest nursing education",
  "oxygen-therapy": "Medical illustration of oxygen therapy delivery methods and respiratory support  -  NurseNest nursing education",
  "chest-tube-care": "Illustration of chest tube placement and pleural drainage system  -  NurseNest nursing education",
  "sterile-technique": "Hand-drawn illustration of sterile technique principles and aseptic field  -  NurseNest nursing education",
  "seizure-safety": "Clinical illustration of seizure pathophysiology and neuronal excitability  -  NurseNest nursing education",
  "increased-icp": "Medical illustration of increased intracranial pressure with brain herniation risk  -  NurseNest nursing education",
  "increased-icp-np": "Advanced ICP management illustration for nurse practitioners  -  NurseNest nursing education",
  "breast-cancer": "Illustration of breast cancer showing tumor growth and staging  -  NurseNest nursing education",
  "cervical-cancer": "Clinical illustration of cervical cancer with HPV-related cellular changes  -  NurseNest nursing education",
  "prostate-cancer": "Medical illustration of prostate cancer showing glandular involvement  -  NurseNest nursing education",
  "multiple-myeloma": "Illustration of multiple myeloma showing plasma cell proliferation in bone marrow  -  NurseNest nursing education",
  "basal-cell-carcinoma": "Clinical illustration of basal cell carcinoma skin cancer  -  NurseNest nursing education",
  "squamous-cell-carcinoma": "Medical illustration of squamous cell carcinoma  -  NurseNest nursing education",
  "potassium-imbalance-rpn": "Illustration of potassium imbalance showing hyperkalemia and hypokalemia electrolyte effects  -  NurseNest nursing education",
  "hyperkalemia-emergency-np": "Clinical illustration of hyperkalemia emergency with ECG changes and treatment  -  NurseNest nursing education",
  "clubfoot": "NurseNest-branded illustration of clubfoot (talipes equinovarus) showing forefoot adduction, hindfoot varus, and Ponseti casting correction  -  NurseNest nursing education",
  "talipes-equinovarus": "NurseNest-branded illustration of talipes equinovarus showing congenital foot deformity anatomy and casting treatment  -  NurseNest nursing education",
  "cmv": "NurseNest-branded illustration of cytomegalovirus showing congenital transmission, microcephaly, hearing loss, and antiviral management  -  NurseNest nursing education",
  "cytomegalovirus": "NurseNest-branded illustration of cytomegalovirus showing maternal-fetal transmission, cellular pathology, and organ involvement  -  NurseNest nursing education",
  "co-poisoning": "NurseNest-branded illustration of carbon monoxide poisoning showing CO binding to hemoglobin, hypoxia, and high-flow oxygen treatment  -  NurseNest nursing education",
  "carbon-monoxide": "NurseNest-branded illustration of carbon monoxide poisoning showing hemoglobin binding, brain hypoxia, and emergency oxygen therapy  -  NurseNest nursing education",
  "carbon-monoxide-poisoning": "NurseNest-branded illustration of carbon monoxide poisoning showing CO inhalation, carboxyhemoglobin formation, and treatment  -  NurseNest nursing education",
  "constipation": "NurseNest-branded illustration of constipation showing slow colonic transit, hard stool formation, and abdominal discomfort  -  NurseNest nursing education",
  "constipation-management": "NurseNest-branded illustration of constipation pathophysiology with colon anatomy and water absorption  -  NurseNest nursing education",
  "contracture": "NurseNest-branded illustration of joint contracture showing muscle fibrosis, tendon shortening, and splinting treatment  -  NurseNest nursing education",
  "contracture-management": "NurseNest-branded illustration of contracture showing flexion deformity, limited range of motion, and stretching prevention  -  NurseNest nursing education",
  "covid": "NurseNest-branded illustration of COVID-19 showing SARS-CoV-2 respiratory infection and transmission  -  NurseNest nursing education",
  "covid-19": "NurseNest-branded illustration of COVID-19 showing viral pathophysiology and clinical manifestations  -  NurseNest nursing education",
  "covid-basics-rpn": "NurseNest-branded illustration of COVID-19 fundamentals for practical nursing education  -  NurseNest nursing education",
  "crohns-disease": "NurseNest-branded illustration of Crohn's disease showing skip lesions, transmural inflammation, and bowel strictures  -  NurseNest nursing education",
  "crohns": "NurseNest-branded illustration of Crohn's disease showing inflammatory bowel disease pathology  -  NurseNest nursing education",
  "cushing-syndrome": "NurseNest-branded illustration of Cushing syndrome showing moon face, buffalo hump, central obesity, purple striae, and thin extremities  -  NurseNest nursing education",
  "cushings-syndrome": "NurseNest-branded illustration of Cushing syndrome showing cortisol excess manifestations  -  NurseNest nursing education",
  "dengue": "NurseNest-branded illustration of dengue fever showing mosquito-borne transmission, hemorrhagic complications, and clinical features  -  NurseNest nursing education",
  "dengue-fever": "NurseNest-branded illustration of dengue fever showing viral pathophysiology and hemorrhagic manifestations  -  NurseNest nursing education",
  "diabetes-insipidus": "NurseNest-branded illustration of diabetes insipidus showing ADH deficiency, dilute urine production, and dehydration  -  NurseNest nursing education",
  "diabetes-insipidus-management": "NurseNest-branded illustration of diabetes insipidus showing massive urine output and desmopressin treatment  -  NurseNest nursing education",
  "diabetic-nephropathy": "NurseNest-branded illustration of diabetic nephropathy showing glomerular damage, microalbuminuria, and progressive kidney disease  -  NurseNest nursing education",
  "diarrhea": "NurseNest-branded illustration of diarrhea showing intestinal pathophysiology, fluid loss, and dehydration risk  -  NurseNest nursing education",
  "diarrhea-management": "NurseNest-branded illustration of diarrhea causes, electrolyte imbalance, and fluid replacement therapy  -  NurseNest nursing education",
};

const systemAltText: Record<string, string> = {
  cardiovascular: "Cardiovascular system medical illustration  -  NurseNest nursing education",
  respiratory: "Respiratory system medical illustration  -  NurseNest nursing education",
  neurological: "Neurological system medical illustration  -  NurseNest nursing education",
  gastrointestinal: "Gastrointestinal system medical illustration  -  NurseNest nursing education",
  renal: "Renal and urinary system medical illustration  -  NurseNest nursing education",
  endocrine: "Endocrine system medical illustration  -  NurseNest nursing education",
  hematology: "Hematology and blood system medical illustration  -  NurseNest nursing education",
  musculoskeletal: "Musculoskeletal system medical illustration  -  NurseNest nursing education",
  immune: "Immune system medical illustration  -  NurseNest nursing education",
  maternity: "Maternity and obstetric nursing medical illustration  -  NurseNest nursing education",
  pediatrics: "Pediatric nursing medical illustration  -  NurseNest nursing education",
  "mental-health": "Mental health nursing medical illustration  -  NurseNest nursing education",
  oncology: "Oncology nursing medical illustration  -  NurseNest nursing education",
  pharmacology: "Pharmacology and medication medical illustration  -  NurseNest nursing education",
  fundamentals: "Nursing fundamentals medical illustration  -  NurseNest nursing education",
  emergency: "Emergency nursing medical illustration  -  NurseNest nursing education",
  sensory: "Sensory system (eye and ear) medical illustration  -  NurseNest nursing education",
  "wound-care": "Wound care nursing medical illustration  -  NurseNest nursing education",
  delegation: "Nursing delegation and prioritization illustration  -  NurseNest nursing education",
  "infection-control": "Infection control nursing medical illustration  -  NurseNest nursing education",
  pain: "Pain management nursing medical illustration  -  NurseNest nursing education",
  palliative: "Palliative and end-of-life care medical illustration  -  NurseNest nursing education",
  community: "Community health nursing illustration  -  NurseNest nursing education",
  cell: "Cell structure and biology medical illustration  -  NurseNest nursing education",
  homeostasis: "Homeostasis and feedback mechanisms medical illustration  -  NurseNest nursing education",
  reproductive: "Reproductive system medical illustration  -  NurseNest nursing education",
  assessment: "Health assessment nursing medical illustration  -  NurseNest nursing education",
};

export function getImageAltText(lessonId: string, fallbackTitle?: string): string {
  if (illustrationAltText[lessonId]) {
    return illustrationAltText[lessonId];
  }

  for (const [key, alt] of Object.entries(systemAltText)) {
    if (lessonId.includes(key)) {
      return alt;
    }
  }

  if (fallbackTitle) {
    return `Medical illustration for ${fallbackTitle}  -  NurseNest nursing education`;
  }

  return "NurseNest hand-drawn medical illustration for nursing education";
}

const illustrationCaption: Record<string, string> = {
  "mi-pathophysiology": "Cross-section showing coronary occlusion with ischemic zone, injury zone, and necrotic myocardial tissue",
  "hf-cell-pathology": "Hypertrophied cardiac myocytes with disorganized sarcomeres compared to normal organized muscle fibers",
  "heart-failure": "Heart failure pathophysiology showing ventricular dilation, mitral regurgitation, and peripheral edema",
  "copd-basics-rpn": "COPD pathophysiology showing air trapping, goblet cell hyperplasia, and inflammatory airway changes",
  "asthma-basics-rpn": "Comparison of normal versus asthmatic bronchiole showing smooth muscle contraction and mast cell degranulation",
  "dka-hhns": "DKA cascade: insulin deficiency leading to fat breakdown, ketone body production, and metabolic acidosis",
  "dka-management": "Diabetic ketoacidosis showing depleted beta cells, cellular glucose starvation, and Kussmaul breathing",
  "icp-basics": "Intracranial pressure pathophysiology with swollen brain, compressed ventricles, and tonsillar herniation",
  "preeclampsia": "Abnormal placental spiral artery remodeling causing systemic effects: cerebral edema, proteinuria, and hepatic congestion",
  "sickle-cell": "Sickle-shaped red blood cells blocking small vessels, causing tissue ischemia and splenic sequestration",
  "stevens-johnson-basics-rpn": "Severe skin reaction with concentric ring lesions and sheet-like skin peeling revealing raw dermis",
  "shingles-herpes-zoster-rpn": "Dermatomal distribution of herpes zoster rash with vesicles progressing to pustules and crusted lesions",
  "guillain-barre": "Peripheral nerve showing segmental demyelination by macrophages with ascending paralysis pattern",
  "pneumonia-basics-rpn": "Pneumonia cross-section showing infected alveoli with exudate alongside normal aerated alveoli",
  "dic-basics": "DIC paradox: simultaneous microthrombi in small vessels consuming clotting factors while causing diffuse bleeding",
  "coagulation-cascade": "Coagulation cascade with excessive factor consumption leading to fibrinolysis and D-dimer production",
  "cirrhosis-management": "Cirrhotic liver with portal hypertension causing esophageal varices, ascites, splenomegaly, and caput medusae",
  "acute-pancreatitis": "Pancreatitis showing autodigestion by activated enzymes, fat necrosis, and Grey Turner/Cullen signs",
  "thyroid-function": "Comparison of hypothyroid (goitrous, lymphocytic infiltration) versus hyperthyroid (diffuse enlargement, follicular hyperplasia)",
  "hypothyroidism-basics": "Hypothyroidism effects: weight gain, bradycardia, cold intolerance, dry skin, and periorbital edema",
  "hyperthyroidism-basics": "Hyperthyroidism effects: weight loss, tachycardia, heat intolerance, tremor, and exophthalmos",
  "thyroidectomy": "Thyroid gland disorders with cellular changes in Hashimoto versus Graves disease",
  "adrenal-insufficiency": "Addison disease showing atrophied adrenal cortex with cortisol and aldosterone deficiency effects",
  "adrenal-function": "Adrenal gland cross-section showing destroyed cortical zones with ACTH-driven hyperpigmentation",
  "electrolyte-safety": "Electrolyte effects on cardiac cells: hyperkalemia (peaked T waves, wide QRS) versus hypokalemia (flat T waves, U waves)",
  "gi-bleed": "GI bleeding sources: esophageal varices, Mallory-Weiss tear, gastric ulcer, diverticular bleed, and colorectal polyp",
  "gi-bleed-basics-rpn": "Upper and lower GI bleeding sources with ulcer penetrating through wall layers to blood vessel",
  "sle-autoimmune": "Lupus showing butterfly malar rash, joint synovitis, pericarditis, and glomerulonephritis from immune complex deposits",
  "tb-basics-rpn": "Tuberculosis pathophysiology showing granuloma structure and bacterial containment in latent versus active disease",
  "seizure-types-priorities-rpn": "Focal seizure origin in temporal lobe spreading to generalized bilateral hemisphere involvement",
  "status-epilepticus": "Sustained seizure activity showing abnormal spike-and-wave pattern spreading across brain hemispheres",
  "placenta-previa-abruption": "Placenta previa (implanted over cervical os) versus placental abruption (premature separation with retroplacental clot)",
  "meningitis": "Inflamed meninges with purulent exudate in subarachnoid space, cloudy CSF, and petechial rash of meningococcemia",
  "glaucoma-rpn": "Comparison of normal optic disc versus glaucomatous cupping with peripheral visual field loss pattern",
  "postpartum-hemorrhage": "PPH four T's: Tone (boggy uterus), Trauma (laceration), Tissue (retained placenta), Thrombin (coagulopathy)",
  "postpartum-hemorrhage-basics-rpn": "Postpartum hemorrhage showing atonic uterus versus well-contracted uterus with spiral artery hemostasis",
  "ulcerative-colitis": "Ulcerative colitis showing continuous mucosal inflammation from rectum proximally, with crypt abscesses and pseudopolyps",
  "peptic-ulcer": "Peptic ulcer disease: gastric ulcer crater with exposed blood vessel, H. pylori colonization, and disrupted mucosal barrier",
  "peptic-ulcer-basics-rpn": "Gastric and duodenal ulcers showing mucosa erosion with H. pylori bacteria and complications of perforation and bleeding",
  "bowel-obstruction": "Mechanical bowel obstruction with dilated proximal loops, collapsed distal bowel, and adhesion band causing obstruction",
  "acute-abdomen": "Bowel obstruction and volvulus showing twisted ischemic bowel with bacterial translocation and third-spacing",
  "cushing-syndrome": "Cushing syndrome features: moon face, buffalo hump, central obesity, purple striae, thin extremities, and easy bruising",
  "cushings-syndrome": "Cushing syndrome: cortisol excess causing moon face, buffalo hump, central obesity, and purple striae",
  "siadh-di": "SIADH (excess ADH, water retention, hyponatremia) versus Diabetes Insipidus (deficient ADH, water loss, hypernatremia)",
  "siadh-basics-rpn": "SIADH showing pituitary releasing excess ADH causing dilute blood and concentrated urine with cerebral edema risk",
  "diabetes-insipidus-basics-rpn": "Diabetes insipidus: kidneys unable to concentrate urine, producing massive dilute output with dehydration",
  "diabetes-insipidus": "Diabetes insipidus: ADH deficiency or resistance causing massive dilute urine output and dehydration risk",
  "diabetes-insipidus-management": "Diabetes insipidus management: desmopressin replacement, fluid balance monitoring, and electrolyte correction",
  "retinal-detachment-rpn": "Retina peeling away from pigment epithelium with subretinal fluid accumulation and photoreceptor ischemia",
  "dvt-management": "Deep vein thrombosis with Virchow triad: venous stasis, endothelial injury, and hypercoagulability forming layered thrombus",
  "pad-claudication": "Peripheral arterial disease with atherosclerotic narrowing causing intermittent claudication and tissue ischemia",
  "neonatal-jaundice-basics": "Neonatal jaundice: immature liver unable to conjugate bilirubin, with risk of kernicterus and phototherapy mechanism",
  "hyperbilirubinemia": "Bilirubin metabolism: RBC breakdown to unconjugated bilirubin, hepatic conjugation, and neonatal liver immaturity",
  "endocarditis-basics-rpn": "Endocarditis showing infected valve leaflets with septic emboli traveling to brain, kidney, and skin",
  "gestational-diabetes": "Placental hormones causing maternal insulin resistance with fetal macrosomia and neonatal hypoglycemia risk",
  "fetal-monitoring-rn": "Fetal heart rate patterns: early decelerations (head compression), late (uteroplacental insufficiency), variable (cord compression)",
  "fetal-monitoring-basics-rpn": "Fetal heart rate tracing showing baseline variability, accelerations, and deceleration types with uterine contractions",
  "shock-types-recognition-rpn": "Types of shock: cardiogenic, distributive, hypovolemic, and obstructive with hemodynamic differences",
  "tracheostomy-basics-rpn": "Tracheostomy tube components and correct positioning with thyroid gland and esophagus visible",
  "skin-integrity": "Wound healing phases: hemostasis (platelet plug), inflammation (immune cells), proliferation (granulation), and remodeling (collagen)",
  "blood-products": "Blood typing showing red blood cell surface antigens (A, B, AB, O) with corresponding plasma antibodies",
  "blood-transfusion-rpn": "Blood type compatibility: ABO system with antigens on RBC surface and antibodies in plasma",
  "insulin-safety": "Pancreatic islets of Langerhans with beta cells producing insulin and glucose uptake at cellular receptors",
  "dm-type1": "Type 1 diabetes: autoimmune destruction of pancreatic beta cells with absolute insulin deficiency",
  "dm-type2": "Type 2 diabetes: insulin resistance at cellular receptors with progressive beta cell dysfunction",
  "diabetes-lifespan": "Pancreatic function showing insulin regulation of blood glucose across the lifespan",
  "fracture-types": "Bone fracture classifications: transverse, oblique, spiral, comminuted, greenstick, and compound (open)",
  "fracture-sprain-care": "Various fracture patterns on long bone showing cortical disruption and displacement types",
  "cast-care": "Bone fracture immobilization with cast showing cortical and cancellous bone structure",
  "spinal-cord-injury": "Spinal cord cross-section showing gray matter, white matter, nerve roots, and meningeal layers",
  "atrial-fibrillation-rn": "ECG rhythm showing irregularly irregular pattern without distinct P waves characteristic of atrial fibrillation",
  "atrial-flutter-rn": "ECG tracing showing sawtooth flutter waves with regular atrial activity and ventricular response",
  "vtach-management": "Wide complex ventricular tachycardia rhythm on ECG monitor with rapid regular QRS complexes",
  "vfib-management": "Ventricular fibrillation showing chaotic electrical activity without organized QRS complexes",
  "heart-block-complete": "Complete heart block with independent atrial and ventricular rhythms showing AV dissociation",
  "ckd": "Chronic kidney disease: nephron damage, fibrosis, reduced filtration, uremia, and fluid retention with shrunken kidney",
  "chronic-kidney-disease": "CKD progression: glomerular damage leading to reduced kidney function, waste buildup, and systemic complications",
  "clubfoot": "Clubfoot (talipes equinovarus): forefoot adduction, hindfoot varus, equinus ankle, and Ponseti serial casting correction",
  "talipes-equinovarus": "Talipes equinovarus anatomy: calcaneus and talus bone malalignment with tendon involvement and casting treatment",
  "cmv": "Cytomegalovirus: congenital transmission via placenta, microcephaly, hearing loss, jaundice, and antiviral treatment",
  "cytomegalovirus": "CMV pathology: viral inclusion bodies in cells, organ involvement (brain, liver), and maternal-fetal transmission",
  "co-poisoning": "Carbon monoxide poisoning: CO displaces oxygen on hemoglobin, causing brain hypoxia, headache, dizziness, and requiring high-flow oxygen",
  "carbon-monoxide": "Carbon monoxide poisoning: CO binds hemoglobin displacing oxygen, causing headache, dizziness, and hypoxia requiring high-flow oxygen treatment",
  "carbon-monoxide-poisoning": "Carbon monoxide poisoning pathophysiology: carboxyhemoglobin formation, tissue hypoxia, and emergency 100% oxygen treatment",
  "compartment-syndrome-basics": "Compartment syndrome: increased fascial pressure causing ischemia, the 5 P's, and emergency fasciotomy",
  "concussion-basics": "Concussion: mild traumatic brain injury with stretched axons, disrupted ion channels, and excitotoxicity cascade",
  "constipation": "Constipation pathophysiology: slow colonic transit, excessive water absorption, hard stool formation, and straining",
  "constipation-management": "Constipation management: fiber intake, fluid hydration, activity, and bowel regimen interventions",
  "contracture": "Joint contracture: muscle fibrosis, tendon shortening, flexion deformity, and prevention with ROM exercises and splinting",
  "contracture-management": "Contracture prevention and management: stretching exercises, splinting, and range of motion maintenance",
  "covid": "COVID-19: SARS-CoV-2 respiratory infection, airborne transmission, and clinical manifestations",
  "covid-19": "COVID-19 pathophysiology: viral entry via ACE2 receptors, respiratory compromise, and systemic inflammation",
  "crohns-disease": "Crohn's disease: skip lesions, transmural inflammation, cobblestone appearance, fistulas, and stricture formation",
  "crohns": "Crohn's disease inflammatory bowel pathology: any GI tract segment, full-thickness wall involvement, and granuloma formation",
  "dengue": "Dengue fever: Aedes mosquito transmission, high fever, hemorrhagic complications, and thrombocytopenia",
  "dengue-fever": "Dengue hemorrhagic fever: viral pathophysiology, plasma leakage, and supportive fluid management",
  "diabetic-nephropathy": "Diabetic nephropathy: glomerular hyperfiltration, mesangial expansion, microalbuminuria progression, and ACE inhibitor protection",
  "diarrhea": "Diarrhea pathophysiology: increased intestinal motility, fluid and electrolyte loss, and dehydration risk",
  "diarrhea-management": "Diarrhea management: oral rehydration therapy, electrolyte replacement, and identification of underlying causes",
  "delirium-basics": "Delirium: acute onset brain dysfunction with fluctuating consciousness, reversible causes, and medical emergency",
  "delirium": "Delirium: sudden-onset confusion with fluctuating awareness, inattention, and disorganized thinking requiring urgent evaluation",
  "delirium-vs-dementia": "Comparison: delirium (acute, reversible) versus dementia (gradual, irreversible) with key differentiating features",
  "dementia-basics": "Dementia: progressive cognitive decline with memory loss, disorientation, and irreversible brain changes",
  "dementia-care": "Dementia care: progressive brain atrophy with memory loss, behavioral changes, and supportive nursing interventions",
  "dementia": "Dementia: progressive neurodegeneration with cortical atrophy, memory impairment, and functional decline",
  "concussion": "Concussion: brain impact causing stretched axons, disrupted ion channels, excitotoxicity, and inflammation cascade",
  "concussion-management": "Concussion management: headache, confusion, dizziness, nausea, memory disturbance, and graded return-to-activity protocol",
  "concussion-rpn": "Concussion nursing assessment: mental status changes, pupil reactivity, and neurological monitoring priorities",
  "cranial-nerves": "Twelve cranial nerves: olfactory, optic, oculomotor, trochlear, trigeminal, abducens, facial, vestibulocochlear, glossopharyngeal, vagus, accessory, hypoglossal",
  "cranial-nerve-assessment": "Cranial nerve clinical assessment: systematic testing of all twelve cranial nerve functions",
  "compartment-syndrome": "Compartment syndrome: elevated fascial pressure causing the 5 P's (pain, pressure, paralysis, paresthesia, pulselessness) requiring fasciotomy",
  "compartment-syndrome-management": "Compartment syndrome emergency: fasciotomy to release pressure, prevent ischemia, and restore neurovascular function",
  "ckd-management": "CKD management: dietary restrictions, fluid balance, electrolyte monitoring, and dialysis preparation based on GFR staging",
};

export function getImageCaption(lessonId: string): string | undefined {
  return illustrationCaption[lessonId];
}

export function getImageTitle(lessonId: string, lessonTitle?: string): string {
  if (lessonTitle) {
    return `${lessonTitle}  -  NurseNest Clinical Illustration`;
  }
  return "NurseNest Clinical Illustration";
}

export function getImageStructuredData(lessonId: string, src: string, lessonTitle?: string) {
  return {
    "@type": "ImageObject",
    name: getImageTitle(lessonId, lessonTitle),
    description: getImageAltText(lessonId, lessonTitle),
    contentUrl: src,
    creator: {
      "@type": "Organization",
      name: "NurseNest",
      url: "https://www.nursenest.ca",
    },
    copyrightHolder: {
      "@type": "Organization",
      name: "NurseNest",
    },
    copyrightNotice: `© ${new Date().getFullYear()} NurseNest. All rights reserved.`,
    license: "https://www.nursenest.ca/terms",
    acquireLicensePage: "https://www.nursenest.ca/terms",
  };
}
