const illustrationAltText: Record<string, string> = {
  "infective-endocarditis": "Hand-drawn medical illustration of infective endocarditis showing heart valve vegetation and bacterial colonies  -  NurseNest nursing education",
  "peripheral-artery-disease": "Clinical illustration of peripheral artery disease showing arterial plaque buildup and reduced blood flow  -  NurseNest nursing education",
  "pacemaker-care": "Detailed illustration of cardiac pacemaker placement and lead positioning in the heart  -  NurseNest nursing education",
  "dysrhythmias": "Medical illustration of cardiac dysrhythmias and cardioversion procedure  -  NurseNest nursing education",
  "mi-management": "Illustration of the cardiac cycle showing myocardial infarction pathophysiology  -  NurseNest nursing education",
  "mi-acute": "Clinical diagram of acute myocardial infarction with coronary artery occlusion  -  NurseNest nursing education",
  "cardiovascular-rpn": "Hand-drawn cardiovascular system overview for practical nursing education  -  NurseNest",
  "cardiovascular-rn": "Cardiovascular system anatomy and physiology illustration for registered nurses  -  NurseNest",
  "cardiovascular-np": "Advanced cardiovascular pathophysiology illustration for nurse practitioners  -  NurseNest",
  "chf-basics": "Illustration of congestive heart failure showing cardiac chamber dilation and fluid backup  -  NurseNest",
  "hf-advanced": "Advanced heart failure pathophysiology diagram with ejection fraction concepts  -  NurseNest",
  "copd-exacerbation": "Medical illustration of COPD showing airway obstruction and hyperinflated alveoli  -  NurseNest nursing education",
  "asthma-emergency": "Clinical illustration of acute asthma showing bronchospasm and airway inflammation  -  NurseNest nursing education",
  "asthma-copd": "Comparative illustration of asthma versus COPD airway pathology  -  NurseNest nursing education",
  "hand-hygiene": "Illustration of hand hygiene technique and bacterial transmission prevention  -  NurseNest nursing education",
  "ppe-basics": "Medical illustration of proper PPE donning and doffing with bacteria visualization  -  NurseNest nursing education",
  "isolation-precautions-rpn": "Illustration of virus particle structure and isolation precaution types  -  NurseNest nursing education",
  "airborne-precautions": "Clinical diagram of airborne virus transmission and respiratory protection  -  NurseNest nursing education",
  "droplet-precautions": "Illustration of droplet precaution measures with viral particle spread patterns  -  NurseNest nursing education",
  "neuritis-neuropathy": "Detailed nerve fiber illustration showing neuritis and neuropathy pathology  -  NurseNest nursing education",
  "tumor-classification": "Medical illustration of tumor classification types and staging system  -  NurseNest nursing education",
  "radiation-therapy": "Clinical illustration of radiation therapy targeting tumor cells  -  NurseNest nursing education",
  "treatment-of-cancer": "Comprehensive cancer treatment modalities illustration  -  NurseNest nursing education",
  "hodgkin-lymphoma": "Illustration of Hodgkin lymphoma showing Reed-Sternberg cells  -  NurseNest nursing education",
  "non-hodgkin-lymphoma": "Medical illustration of non-Hodgkin lymphoma cell types and lymph node involvement  -  NurseNest nursing education",
  "aki-management": "Hand-drawn kidney anatomy illustration showing acute kidney injury pathology  -  NurseNest nursing education",
  "ckd-management": "Clinical illustration of chronic kidney disease stages and nephron damage  -  NurseNest nursing education",
  "rhabdomyolysis": "Illustration of rhabdomyolysis showing muscle fiber breakdown and kidney impact  -  NurseNest nursing education",
  "av-fistula": "Detailed illustration of arteriovenous fistula for hemodialysis access  -  NurseNest nursing education",
  "dialysis-steal": "Medical illustration of dialysis steal syndrome and vascular access complications  -  NurseNest nursing education",
  "shock-syndromes": "Clinical illustration of shock pathophysiology showing circulatory collapse  -  NurseNest nursing education",
  "sepsis-mastery": "Illustration of sepsis cascade from infection to organ dysfunction  -  NurseNest nursing education",
  "burn-management": "Hand-drawn illustration of burn wound classification and tissue layers  -  NurseNest nursing education",
  "cellulitis": "Clinical illustration of cellulitis showing skin infection and inflammation layers  -  NurseNest nursing education",
  "cardiogenic-shock": "Medical illustration of cardiogenic shock with failing cardiac output  -  NurseNest nursing education",
  "aaa-rupture": "Illustration of abdominal aortic aneurysm with rupture risk anatomy  -  NurseNest nursing education",
  "pe-dvt": "Clinical diagram of pulmonary embolism and deep vein thrombosis pathology  -  NurseNest nursing education",
  "pe-recognition": "Medical illustration of pulmonary embolism lodged in pulmonary vasculature  -  NurseNest nursing education",
  "cardiac-monitoring": "Illustration of cardiac monitoring with ECG lead placement  -  NurseNest nursing education",
  "cardiac-rhythm-rn": "ECG rhythm interpretation illustration for registered nurses  -  NurseNest nursing education",
  "cardiac-auscultation-rn": "Heart auscultation landmarks and cardiac cycle sounds illustration  -  NurseNest nursing education",
  "hypertension-management": "Clinical illustration of hypertension effects on cardiac and vascular system  -  NurseNest nursing education",
  "aortic-dissection": "Medical illustration of aortic dissection showing intimal tear and false lumen  -  NurseNest nursing education",
  "carotid-endarterectomy": "Surgical illustration of carotid endarterectomy procedure  -  NurseNest nursing education",
  "pneumonia-basics": "Hand-drawn illustration of pneumonia showing alveolar consolidation  -  NurseNest nursing education",
  "pneumonia-management": "Clinical illustration of pneumonia treatment and lung pathology  -  NurseNest nursing education",
  "pneumonia-community": "Illustration of community-acquired pneumonia with bacterial invasion of alveoli  -  NurseNest nursing education",
  "pneumonia-hospital": "Medical illustration of hospital-acquired pneumonia and ventilator-associated infection  -  NurseNest nursing education",
  "pneumonia-aspiration": "Illustration of aspiration pneumonia showing gastric content entering airways  -  NurseNest nursing education",
  "active-tb": "Clinical illustration of active tuberculosis with lung cavitation and acid-fast bacilli  -  NurseNest nursing education",
  "tuberculosis": "Detailed tuberculosis pathology illustration showing granuloma formation  -  NurseNest nursing education",
  "latent-tb": "Illustration of latent tuberculosis infection with encapsulated granuloma  -  NurseNest nursing education",
  "tb-screening": "Medical illustration of tuberculosis screening methods and Mantoux test  -  NurseNest nursing education",
  "tracheostomy-care": "Hand-drawn illustration of tracheostomy tube placement and airway anatomy  -  NurseNest nursing education",
  "tracheostomy": "Detailed tracheostomy anatomy illustration showing tube components  -  NurseNest nursing education",
  "tracheostomy-suctioning": "Clinical illustration of tracheostomy suctioning technique  -  NurseNest nursing education",
  "laryngectomy": "Medical illustration of laryngectomy and permanent stoma  -  NurseNest nursing education",
  "parkinsons-disease": "Illustration of Parkinson disease showing dopaminergic neuron degeneration in substantia nigra  -  NurseNest nursing education",
  "parkinsons": "Clinical illustration of Parkinson disease motor symptoms and basal ganglia pathology  -  NurseNest nursing education",
  "multiple-sclerosis": "Medical illustration of multiple sclerosis showing demyelination of nerve fibers  -  NurseNest nursing education",
  "ms-management": "Illustration of multiple sclerosis nerve damage and myelin sheath destruction  -  NurseNest nursing education",
  "stroke": "Hand-drawn illustration of stroke showing ischemic and hemorrhagic brain pathology  -  NurseNest nursing education",
  "stroke-advanced": "Advanced stroke illustration with penumbra zone and cerebral circulation  -  NurseNest nursing education",
  "brain-abscess": "Clinical illustration of brain abscess with encapsulated infection  -  NurseNest nursing education",
  "delirium-vs-dementia": "Comparative illustration of delirium versus dementia brain changes  -  NurseNest nursing education",
  "delirium": "Medical illustration of delirium showing acute brain dysfunction  -  NurseNest nursing education",
  "dementia-care": "Illustration of dementia showing progressive brain atrophy  -  NurseNest nursing education",
  "cranial-nerve-assessment": "Detailed illustration of the twelve cranial nerves and their pathways  -  NurseNest nursing education",
  "cranial-nerves": "Hand-drawn cranial nerve anatomy diagram for clinical assessment  -  NurseNest nursing education",
  "trigeminal-neuralgia": "Clinical illustration of trigeminal neuralgia showing affected nerve branches  -  NurseNest nursing education",
  "carpal-tunnel": "Medical illustration of carpal tunnel syndrome showing median nerve compression  -  NurseNest nursing education",
  "carpal-tunnel-syndrome": "Detailed illustration of carpal tunnel anatomy with nerve entrapment  -  NurseNest nursing education",
  "cerebral-edema": "Illustration of cerebral edema showing brain swelling and increased intracranial pressure  -  NurseNest nursing education",
  "myasthenia-gravis": "Clinical illustration of myasthenia gravis showing neuromuscular junction antibody attack  -  NurseNest nursing education",
  "concussion": "Medical illustration of concussion showing brain impact and axonal injury  -  NurseNest nursing education",
  "concussion-management": "Illustration of concussion management with brain trauma visualization  -  NurseNest nursing education",
  "tbi-management": "Traumatic brain injury management illustration with cerebral pathology  -  NurseNest nursing education",
  "bells-palsy": "Hand-drawn illustration of Bell palsy showing facial nerve inflammation  -  NurseNest nursing education",
  "cystic-fibrosis": "Clinical illustration of cystic fibrosis showing thick mucus in airways and CFTR defect  -  NurseNest nursing education",
  "cf-management": "Detailed cystic fibrosis pathophysiology illustration with chloride channel dysfunction  -  NurseNest nursing education",
  "pertussis-basics": "Medical illustration of pertussis (whooping cough) showing Bordetella pertussis bacteria  -  NurseNest nursing education",
  "whooping-cough": "Illustration of whooping cough airway inflammation and paroxysmal coughing mechanism  -  NurseNest nursing education",
  "bronchiectasis": "Clinical illustration of bronchiectasis showing permanently dilated bronchi  -  NurseNest nursing education",
  "bronchiectasis-management": "Detailed bronchiectasis pathology illustration with airway wall destruction  -  NurseNest nursing education",
  "pleurisy": "Medical illustration of pleurisy showing inflamed pleural membranes  -  NurseNest nursing education",
  "pleural-effusion": "Illustration of pleural effusion with fluid accumulation in pleural space  -  NurseNest nursing education",
  "chest-physiotherapy": "Hand-drawn illustration of chest physiotherapy techniques and postural drainage positions  -  NurseNest nursing education",
  "chest-physio": "Clinical chest physiotherapy illustration showing percussion and vibration techniques  -  NurseNest nursing education",
  "postural-drainage": "Illustration of postural drainage positions for respiratory secretion clearance  -  NurseNest nursing education",
  "rsv-management": "Medical illustration of respiratory syncytial virus (RSV) and bronchiolitis  -  NurseNest nursing education",
  "rsv-bronchiolitis": "Detailed RSV illustration showing viral infection of bronchioles  -  NurseNest nursing education",
  "hemoptysis": "Clinical illustration of hemoptysis showing blood in airway and potential causes  -  NurseNest nursing education",
  "hemoptysis-management": "Medical illustration of hemoptysis management and pulmonary bleeding sources  -  NurseNest nursing education",
  "abg-basics": "Illustration of arterial blood gas interpretation and electrolyte balance  -  NurseNest nursing education",
  "abg-interpretation-rn": "Detailed ABG interpretation illustration for registered nurses  -  NurseNest nursing education",
  "inflammatory-response": "Hand-drawn illustration of the inflammatory response cascade and immune cell activation  -  NurseNest nursing education",
  "inflammation": "Clinical illustration of inflammation pathways and tissue response  -  NurseNest nursing education",
  "retinal-detachment": "Medical illustration of retinal detachment showing separation of retinal layers  -  NurseNest nursing education",
  "pressure-injuries": "Illustration of pressure injury staging from Stage 1 to unstageable  -  NurseNest nursing education",
  "pressure-ulcers": "Detailed pressure ulcer illustration showing tissue damage layers  -  NurseNest nursing education",
  "pressure-injury-staging": "Clinical illustration of pressure injury staging classification system  -  NurseNest nursing education",
  "innate-immunity": "Hand-drawn illustration of the innate immune system with phagocytes and natural killer cells  -  NurseNest nursing education",
  "innate-immune-system": "Detailed innate immunity illustration showing first-line immune defenses  -  NurseNest nursing education",
  "adaptive-immunity": "Medical illustration of adaptive immune system with T-cells and B-cells  -  NurseNest nursing education",
  "adaptive-immune-system": "Detailed adaptive immunity illustration showing antibody production and memory cells  -  NurseNest nursing education",
  "immune-response": "Comprehensive immune response illustration with innate and adaptive pathways  -  NurseNest nursing education",
  "conjunctivitis": "Clinical illustration of conjunctivitis showing eye inflammation and discharge  -  NurseNest nursing education",
  "pink-eye": "Illustration of pink eye (conjunctivitis) with bacterial and viral causes  -  NurseNest nursing education",
  "aplastic-anemia": "Medical illustration of aplastic anemia showing bone marrow failure  -  NurseNest nursing education",
  "alopecia": "Hand-drawn illustration of alopecia showing hair follicle pathology  -  NurseNest nursing education",
  "alopecia-areata": "Clinical illustration of alopecia areata with autoimmune hair loss  -  NurseNest nursing education",
  "pemphigus": "Medical illustration of pemphigus vulgaris showing skin blistering and autoimmune attack  -  NurseNest nursing education",
  "pemphigus-vulgaris": "Detailed pemphigus vulgaris illustration with intraepidermal blister formation  -  NurseNest nursing education",
  "polycythemia": "Illustration of polycythemia vera showing excess red blood cell production  -  NurseNest nursing education",
  "polycythemia-vera": "Clinical illustration of polycythemia vera with bone marrow overproduction  -  NurseNest nursing education",
  "atopic-dermatitis": "Hand-drawn illustration of atopic dermatitis showing skin inflammation and eczema patterns  -  NurseNest nursing education",
  "eczema-atopic-dermatitis": "Medical illustration of eczema with skin barrier dysfunction  -  NurseNest nursing education",
  "eczema": "Clinical illustration of eczema showing inflammatory skin response  -  NurseNest nursing education",
  "otitis-media": "Illustration of otitis media showing middle ear infection and fluid buildup  -  NurseNest nursing education",
  "otitis-externa": "Clinical illustration of otitis externa (swimmer ear) with external ear canal infection  -  NurseNest nursing education",
  "ear-infection": "Medical illustration of ear infection anatomy and inflammatory response  -  NurseNest nursing education",
  "stevens-johnson-syndrome": "Hand-drawn illustration of Stevens-Johnson syndrome showing severe skin reaction  -  NurseNest nursing education",
  "toxic-epidermal-necrolysis": "Clinical illustration of toxic epidermal necrolysis with epidermal detachment  -  NurseNest nursing education",
  "herpes-simplex": "Medical illustration of herpes simplex virus showing vesicular skin lesions  -  NurseNest nursing education",
  "hsv": "Illustration of HSV infection with viral replication in epithelial cells  -  NurseNest nursing education",
  "cold-sores": "Clinical illustration of cold sores showing herpes labialis pathology  -  NurseNest nursing education",
  "herpes-zoster": "Hand-drawn illustration of herpes zoster (shingles) showing dermatomal distribution  -  NurseNest nursing education",
  "herpes-zoster-shingles": "Medical illustration of shingles with varicella-zoster virus reactivation  -  NurseNest nursing education",
  "shingles": "Clinical illustration of shingles showing nerve-distributed vesicular rash  -  NurseNest nursing education",
  "varicella-zoster": "Illustration of varicella-zoster virus lifecycle and reactivation  -  NurseNest nursing education",
  "glaucoma": "Detailed illustration of glaucoma showing increased intraocular pressure and optic nerve damage  -  NurseNest nursing education",
  "glaucoma-management": "Medical illustration of glaucoma management with aqueous humor drainage  -  NurseNest nursing education",
  "vitiligo": "Hand-drawn illustration of vitiligo showing melanocyte loss and depigmentation patterns  -  NurseNest nursing education",
  "cell-structure": "Detailed cell structure illustration showing organelles and membrane components  -  NurseNest nursing education",
  "cell-biology": "Clinical cell biology illustration with labeled cellular organelles  -  NurseNest nursing education",
  "homeostasis": "Illustration of homeostasis feedback loops showing negative and positive feedback mechanisms  -  NurseNest nursing education",
  "feedback-loops": "Medical illustration of physiological feedback loop regulation  -  NurseNest nursing education",
  "psoriasis": "Clinical illustration of psoriasis showing epidermal hyperproliferation and plaque formation  -  NurseNest nursing education",
  "contact-dermatitis": "Illustration of contact dermatitis showing allergic skin reaction  -  NurseNest nursing education",
  "melanoma": "Medical illustration of melanoma showing malignant melanocyte transformation  -  NurseNest nursing education",
  "urticaria": "Clinical illustration of urticaria (hives) showing mast cell histamine release  -  NurseNest nursing education",
  "scabies": "Medical illustration of scabies mite infestation in skin layers  -  NurseNest nursing education",
  "impetigo": "Illustration of impetigo showing superficial bacterial skin infection  -  NurseNest nursing education",
  "anaphylaxis": "Clinical illustration of anaphylaxis showing systemic allergic response  -  NurseNest nursing education",
  "compartment-syndrome": "Medical illustration of compartment syndrome showing tissue pressure buildup  -  NurseNest nursing education",
  "malignant-hyperthermia": "Illustration of malignant hyperthermia showing uncontrolled muscle metabolism  -  NurseNest nursing education",
  "ards-management": "Clinical illustration of acute respiratory distress syndrome with alveolar damage  -  NurseNest nursing education",
  "oxygen-therapy": "Medical illustration of oxygen therapy delivery methods and respiratory support  -  NurseNest nursing education",
  "chest-tube-care": "Illustration of chest tube placement and pleural drainage system  -  NurseNest nursing education",
  "sterile-technique": "Hand-drawn illustration of sterile technique principles and aseptic field  -  NurseNest nursing education",
  "seizure-safety": "Clinical illustration of seizure pathophysiology and neuronal excitability  -  NurseNest nursing education",
  "increased-icp": "Medical illustration of increased intracranial pressure with brain herniation risk  -  NurseNest nursing education",
  "increased-icp-np": "Advanced ICP management illustration for nurse practitioners  -  NurseNest nursing education",
  "breast-cancer": "Illustration of breast cancer showing tumor growth and staging  -  NurseNest nursing education",
  "cervical-cancer": "Clinical illustration of cervical cancer with HPV-related cellular changes  -  NurseNest nursing education",
  "prostate-cancer": "Medical illustration of prostate cancer showing glandular involvement  -  NurseNest nursing education",
  "multiple-myeloma": "Illustration of multiple myeloma showing plasma cell proliferation in bone marrow  -  NurseNest nursing education",
  "basal-cell-carcinoma": "Clinical illustration of basal cell carcinoma skin cancer  -  NurseNest nursing education",
  "squamous-cell-carcinoma": "Medical illustration of squamous cell carcinoma  -  NurseNest nursing education",
  "potassium-imbalance-rpn": "Illustration of potassium imbalance showing hyperkalemia and hypokalemia electrolyte effects  -  NurseNest nursing education",
  "hyperkalemia-emergency-np": "Clinical illustration of hyperkalemia emergency with ECG changes and treatment  -  NurseNest nursing education",
};

const systemAltText: Record<string, string> = {
  cardiovascular: "Cardiovascular system medical illustration  -  NurseNest nursing education",
  respiratory: "Respiratory system medical illustration  -  NurseNest nursing education",
  neurological: "Neurological system medical illustration  -  NurseNest nursing education",
  gastrointestinal: "Gastrointestinal system medical illustration  -  NurseNest nursing education",
  renal: "Renal and urinary system medical illustration  -  NurseNest nursing education",
  endocrine: "Endocrine system medical illustration  -  NurseNest nursing education",
  hematology: "Hematology and blood system medical illustration  -  NurseNest nursing education",
  musculoskeletal: "Musculoskeletal system medical illustration  -  NurseNest nursing education",
  immune: "Immune system medical illustration  -  NurseNest nursing education",
  maternity: "Maternity and obstetric nursing medical illustration  -  NurseNest nursing education",
  pediatrics: "Pediatric nursing medical illustration  -  NurseNest nursing education",
  "mental-health": "Mental health nursing medical illustration  -  NurseNest nursing education",
  oncology: "Oncology nursing medical illustration  -  NurseNest nursing education",
  pharmacology: "Pharmacology and medication medical illustration  -  NurseNest nursing education",
  fundamentals: "Nursing fundamentals medical illustration  -  NurseNest nursing education",
  emergency: "Emergency nursing medical illustration  -  NurseNest nursing education",
  sensory: "Sensory system (eye and ear) medical illustration  -  NurseNest nursing education",
  "wound-care": "Wound care nursing medical illustration  -  NurseNest nursing education",
  delegation: "Nursing delegation and prioritization illustration  -  NurseNest nursing education",
  "infection-control": "Infection control nursing medical illustration  -  NurseNest nursing education",
  pain: "Pain management nursing medical illustration  -  NurseNest nursing education",
  palliative: "Palliative and end-of-life care medical illustration  -  NurseNest nursing education",
  community: "Community health nursing illustration  -  NurseNest nursing education",
  cell: "Cell structure and biology medical illustration  -  NurseNest nursing education",
  homeostasis: "Homeostasis and feedback mechanisms medical illustration  -  NurseNest nursing education",
  reproductive: "Reproductive system medical illustration  -  NurseNest nursing education",
  assessment: "Health assessment nursing medical illustration  -  NurseNest nursing education",
};

export function getImageAltText(lessonId: string, fallbackTitle?: string): string {
  if (illustrationAltText[lessonId]) {
    return illustrationAltText[lessonId];
  }

  for (const [key, alt] of Object.entries(systemAltText)) {
    if (lessonId.includes(key)) {
      return alt;
    }
  }

  if (fallbackTitle) {
    return `Medical illustration for ${fallbackTitle}  -  NurseNest nursing education`;
  }

  return "NurseNest hand-drawn medical illustration for nursing education";
}

export function getImageTitle(lessonId: string, lessonTitle?: string): string {
  if (lessonTitle) {
    return `${lessonTitle}  -  NurseNest Clinical Illustration`;
  }
  return "NurseNest Clinical Illustration";
}

export function getImageStructuredData(lessonId: string, src: string, lessonTitle?: string) {
  return {
    "@type": "ImageObject",
    name: getImageTitle(lessonId, lessonTitle),
    description: getImageAltText(lessonId, lessonTitle),
    contentUrl: src,
    creator: {
      "@type": "Organization",
      name: "NurseNest",
      url: "https://www.nursenest.ca",
    },
    copyrightHolder: {
      "@type": "Organization",
      name: "NurseNest",
    },
    copyrightNotice: `© ${new Date().getFullYear()} NurseNest. All rights reserved.`,
    license: "https://www.nursenest.ca/terms",
    acquireLicensePage: "https://www.nursenest.ca/terms",
  };
}
