const illustrationAltText: Record<string, string> = {
  "infective-endocarditis": "Hand-drawn medical illustration of infective endocarditis showing heart valve vegetation and bacterial colonies  -  NurseNest nursing education",
  "peripheral-artery-disease": "Clinical illustration of peripheral artery disease showing arterial plaque buildup and reduced blood flow  -  NurseNest nursing education",
  "pacemaker-care": "Detailed illustration of cardiac pacemaker placement and lead positioning in the heart  -  NurseNest nursing education",
  "dysrhythmias": "Medical illustration of cardiac dysrhythmias and cardioversion procedure  -  NurseNest nursing education",
  "mi-management": "Illustration of the cardiac cycle showing myocardial infarction pathophysiology  -  NurseNest nursing education",
  "mi-acute": "Clinical diagram of acute myocardial infarction with coronary artery occlusion  -  NurseNest nursing education",
  "cardiovascular-rpn": "Hand-drawn cardiovascular system overview for practical nursing education  -  NurseNest",
  "cardiovascular-rn": "Cardiovascular system anatomy and physiology illustration for registered nurses  -  NurseNest",
  "cardiovascular-np": "Advanced cardiovascular pathophysiology illustration for nurse practitioners  -  NurseNest",
  "chf-basics": "Illustration of congestive heart failure showing cardiac chamber dilation and fluid backup  -  NurseNest",
  "hf-advanced": "Advanced heart failure pathophysiology diagram with ejection fraction concepts  -  NurseNest",
  "copd-exacerbation": "Medical illustration of COPD showing airway obstruction and hyperinflated alveoli  -  NurseNest nursing education",
  "asthma-emergency": "Clinical illustration of acute asthma showing bronchospasm and airway inflammation  -  NurseNest nursing education",
  "asthma-copd": "Comparative illustration of asthma versus COPD airway pathology  -  NurseNest nursing education",
  "hand-hygiene": "Illustration of hand hygiene technique and bacterial transmission prevention  -  NurseNest nursing education",
  "ppe-basics": "Medical illustration of proper PPE donning and doffing with bacteria visualization  -  NurseNest nursing education",
  "isolation-precautions-rpn": "Illustration of virus particle structure and isolation precaution types  -  NurseNest nursing education",
  "airborne-precautions": "Clinical diagram of airborne virus transmission and respiratory protection  -  NurseNest nursing education",
  "droplet-precautions": "Illustration of droplet precaution measures with viral particle spread patterns  -  NurseNest nursing education",
  "neuritis-neuropathy": "Detailed nerve fiber illustration showing neuritis and neuropathy pathology  -  NurseNest nursing education",
  "tumor-classification": "Medical illustration of tumor classification types and staging system  -  NurseNest nursing education",
  "radiation-therapy": "Clinical illustration of radiation therapy targeting tumor cells  -  NurseNest nursing education",
  "treatment-of-cancer": "Comprehensive cancer treatment modalities illustration  -  NurseNest nursing education",
  "hodgkin-lymphoma": "Illustration of Hodgkin lymphoma showing Reed-Sternberg cells  -  NurseNest nursing education",
  "non-hodgkin-lymphoma": "Medical illustration of non-Hodgkin lymphoma cell types and lymph node involvement  -  NurseNest nursing education",
  "aki-management": "Hand-drawn kidney anatomy illustration showing acute kidney injury pathology  -  NurseNest nursing education",
  "ckd-management": "Clinical illustration of chronic kidney disease stages and nephron damage  -  NurseNest nursing education",
  "rhabdomyolysis": "Illustration of rhabdomyolysis showing muscle fiber breakdown and kidney impact  -  NurseNest nursing education",
  "av-fistula": "Detailed illustration of arteriovenous fistula for hemodialysis access  -  NurseNest nursing education",
  "dialysis-steal": "Medical illustration of dialysis steal syndrome and vascular access complications  -  NurseNest nursing education",
  "shock-syndromes": "Clinical illustration of shock pathophysiology showing circulatory collapse  -  NurseNest nursing education",
  "sepsis-mastery": "Illustration of sepsis cascade from infection to organ dysfunction  -  NurseNest nursing education",
  "burn-management": "Hand-drawn illustration of burn wound classification and tissue layers  -  NurseNest nursing education",
  "cellulitis": "Clinical illustration of cellulitis showing skin infection and inflammation layers  -  NurseNest nursing education",
  "cardiogenic-shock": "Medical illustration of cardiogenic shock with failing cardiac output  -  NurseNest nursing education",
  "aaa-rupture": "Illustration of abdominal aortic aneurysm with rupture risk anatomy  -  NurseNest nursing education",
  "pe-dvt": "Clinical diagram of pulmonary embolism and deep vein thrombosis pathology  -  NurseNest nursing education",
  "pe-recognition": "Medical illustration of pulmonary embolism lodged in pulmonary vasculature  -  NurseNest nursing education",
  "cardiac-monitoring": "Illustration of cardiac monitoring with ECG lead placement  -  NurseNest nursing education",
  "cardiac-rhythm-rn": "ECG rhythm interpretation illustration for registered nurses  -  NurseNest nursing education",
  "cardiac-auscultation-rn": "Heart auscultation landmarks and cardiac cycle sounds illustration  -  NurseNest nursing education",
  "hypertension-management": "Clinical illustration of hypertension effects on cardiac and vascular system  -  NurseNest nursing education",
  "aortic-dissection": "Medical illustration of aortic dissection showing intimal tear and false lumen  -  NurseNest nursing education",
  "carotid-endarterectomy": "Surgical illustration of carotid endarterectomy procedure  -  NurseNest nursing education",
  "pneumonia-basics": "Hand-drawn illustration of pneumonia showing alveolar consolidation  -  NurseNest nursing education",
  "pneumonia-management": "Clinical illustration of pneumonia treatment and lung pathology  -  NurseNest nursing education",
  "pneumonia-community": "Illustration of community-acquired pneumonia with bacterial invasion of alveoli  -  NurseNest nursing education",
  "pneumonia-hospital": "Medical illustration of hospital-acquired pneumonia and ventilator-associated infection  -  NurseNest nursing education",
  "pneumonia-aspiration": "Illustration of aspiration pneumonia showing gastric content entering airways  -  NurseNest nursing education",
  "active-tb": "Clinical illustration of active tuberculosis with lung cavitation and acid-fast bacilli  -  NurseNest nursing education",
  "tuberculosis": "Detailed tuberculosis pathology illustration showing granuloma formation  -  NurseNest nursing education",
  "latent-tb": "Illustration of latent tuberculosis infection with encapsulated granuloma  -  NurseNest nursing education",
  "tb-screening": "Medical illustration of tuberculosis screening methods and Mantoux test  -  NurseNest nursing education",
  "tracheostomy-care": "Hand-drawn illustration of tracheostomy tube placement and airway anatomy  -  NurseNest nursing education",
  "tracheostomy": "Detailed tracheostomy anatomy illustration showing tube components  -  NurseNest nursing education",
  "tracheostomy-suctioning": "Clinical illustration of tracheostomy suctioning technique  -  NurseNest nursing education",
  "laryngectomy": "Medical illustration of laryngectomy and permanent stoma  -  NurseNest nursing education",
  "parkinsons-disease": "Illustration of Parkinson disease showing dopaminergic neuron degeneration in substantia nigra  -  NurseNest nursing education",
  "parkinsons": "Clinical illustration of Parkinson disease motor symptoms and basal ganglia pathology  -  NurseNest nursing education",
  "multiple-sclerosis": "Medical illustration of multiple sclerosis showing demyelination of nerve fibers  -  NurseNest nursing education",
  "ms-management": "Illustration of multiple sclerosis nerve damage and myelin sheath destruction  -  NurseNest nursing education",
  "stroke": "Hand-drawn illustration of stroke showing ischemic and hemorrhagic brain pathology  -  NurseNest nursing education",
  "stroke-advanced": "Advanced stroke illustration with penumbra zone and cerebral circulation  -  NurseNest nursing education",
  "brain-abscess": "Clinical illustration of brain abscess with encapsulated infection  -  NurseNest nursing education",
  "delirium-vs-dementia": "Comparative illustration of delirium versus dementia brain changes  -  NurseNest nursing education",
  "delirium": "Medical illustration of delirium showing acute brain dysfunction  -  NurseNest nursing education",
  "dementia-care": "Illustration of dementia showing progressive brain atrophy  -  NurseNest nursing education",
  "cranial-nerve-assessment": "Detailed illustration of the twelve cranial nerves and their pathways  -  NurseNest nursing education",
  "cranial-nerves": "Hand-drawn cranial nerve anatomy diagram for clinical assessment  -  NurseNest nursing education",
  "trigeminal-neuralgia": "Clinical illustration of trigeminal neuralgia showing affected nerve branches  -  NurseNest nursing education",
  "carpal-tunnel": "Medical illustration of carpal tunnel syndrome showing median nerve compression  -  NurseNest nursing education",
  "carpal-tunnel-syndrome": "Detailed illustration of carpal tunnel anatomy with nerve entrapment  -  NurseNest nursing education",
  "cerebral-edema": "Illustration of cerebral edema showing brain swelling and increased intracranial pressure  -  NurseNest nursing education",
  "myasthenia-gravis": "Clinical illustration of myasthenia gravis showing neuromuscular junction antibody attack  -  NurseNest nursing education",
  "concussion": "Medical illustration of concussion showing brain impact and axonal injury  -  NurseNest nursing education",
  "concussion-management": "Illustration of concussion management with brain trauma visualization  -  NurseNest nursing education",
  "tbi-management": "Traumatic brain injury management illustration with cerebral pathology  -  NurseNest nursing education",
  "bells-palsy": "Hand-drawn illustration of Bell palsy showing facial nerve inflammation  -  NurseNest nursing education",
  "cystic-fibrosis": "Clinical illustration of cystic fibrosis showing thick mucus in airways and CFTR defect  -  NurseNest nursing education",
  "cf-management": "Detailed cystic fibrosis pathophysiology illustration with chloride channel dysfunction  -  NurseNest nursing education",
  "pertussis-basics": "Medical illustration of pertussis (whooping cough) showing Bordetella pertussis bacteria  -  NurseNest nursing education",
  "whooping-cough": "Illustration of whooping cough airway inflammation and paroxysmal coughing mechanism  -  NurseNest nursing education",
  "bronchiectasis": "Clinical illustration of bronchiectasis showing permanently dilated bronchi  -  NurseNest nursing education",
  "bronchiectasis-management": "Detailed bronchiectasis pathology illustration with airway wall destruction  -  NurseNest nursing education",
  "pleurisy": "Medical illustration of pleurisy showing inflamed pleural membranes  -  NurseNest nursing education",
  "pleural-effusion": "Illustration of pleural effusion with fluid accumulation in pleural space  -  NurseNest nursing education",
  "chest-physiotherapy": "Hand-drawn illustration of chest physiotherapy techniques and postural drainage positions  -  NurseNest nursing education",
  "chest-physio": "Clinical chest physiotherapy illustration showing percussion and vibration techniques  -  NurseNest nursing education",
  "postural-drainage": "Illustration of postural drainage positions for respiratory secretion clearance  -  NurseNest nursing education",
  "rsv-management": "Medical illustration of respiratory syncytial virus (RSV) and bronchiolitis  -  NurseNest nursing education",
  "rsv-bronchiolitis": "Detailed RSV illustration showing viral infection of bronchioles  -  NurseNest nursing education",
  "hemoptysis": "Clinical illustration of hemoptysis showing blood in airway and potential causes  -  NurseNest nursing education",
  "hemoptysis-management": "Medical illustration of hemoptysis management and pulmonary bleeding sources  -  NurseNest nursing education",
  "abg-basics": "Illustration of arterial blood gas interpretation and electrolyte balance  -  NurseNest nursing education",
  "abg-interpretation-rn": "Detailed ABG interpretation illustration for registered nurses  -  NurseNest nursing education",
  "inflammatory-response": "Hand-drawn illustration of the inflammatory response cascade and immune cell activation  -  NurseNest nursing education",
  "inflammation": "Clinical illustration of inflammation pathways and tissue response  -  NurseNest nursing education",
  "retinal-detachment": "Medical illustration of retinal detachment showing separation of retinal layers  -  NurseNest nursing education",
  "pressure-injuries": "Illustration of pressure injury staging from Stage 1 to unstageable  -  NurseNest nursing education",
  "pressure-ulcers": "Detailed pressure ulcer illustration showing tissue damage layers  -  NurseNest nursing education",
  "pressure-injury-staging": "Clinical illustration of pressure injury staging classification system  -  NurseNest nursing education",
  "innate-immunity": "Hand-drawn illustration of the innate immune system with phagocytes and natural killer cells  -  NurseNest nursing education",
  "innate-immune-system": "Detailed innate immunity illustration showing first-line immune defenses  -  NurseNest nursing education",
  "adaptive-immunity": "Medical illustration of adaptive immune system with T-cells and B-cells  -  NurseNest nursing education",
  "adaptive-immune-system": "Detailed adaptive immunity illustration showing antibody production and memory cells  -  NurseNest nursing education",
  "immune-response": "Comprehensive immune response illustration with innate and adaptive pathways  -  NurseNest nursing education",
  "conjunctivitis": "Clinical illustration of conjunctivitis showing eye inflammation and discharge  -  NurseNest nursing education",
  "pink-eye": "Illustration of pink eye (conjunctivitis) with bacterial and viral causes  -  NurseNest nursing education",
  "aplastic-anemia": "Medical illustration of aplastic anemia showing bone marrow failure  -  NurseNest nursing education",
  "alopecia": "Hand-drawn illustration of alopecia showing hair follicle pathology  -  NurseNest nursing education",
  "alopecia-areata": "Clinical illustration of alopecia areata with autoimmune hair loss  -  NurseNest nursing education",
  "pemphigus": "Medical illustration of pemphigus vulgaris showing skin blistering and autoimmune attack  -  NurseNest nursing education",
  "pemphigus-vulgaris": "Detailed pemphigus vulgaris illustration with intraepidermal blister formation  -  NurseNest nursing education",
  "polycythemia": "Illustration of polycythemia vera showing excess red blood cell production  -  NurseNest nursing education",
  "polycythemia-vera": "Clinical illustration of polycythemia vera with bone marrow overproduction  -  NurseNest nursing education",
  "atopic-dermatitis": "Hand-drawn illustration of atopic dermatitis showing skin inflammation and eczema patterns  -  NurseNest nursing education",
  "eczema-atopic-dermatitis": "Medical illustration of eczema with skin barrier dysfunction  -  NurseNest nursing education",
  "eczema": "Clinical illustration of eczema showing inflammatory skin response  -  NurseNest nursing education",
  "otitis-media": "Illustration of otitis media showing middle ear infection and fluid buildup  -  NurseNest nursing education",
  "otitis-externa": "Clinical illustration of otitis externa (swimmer ear) with external ear canal infection  -  NurseNest nursing education",
  "ear-infection": "Medical illustration of ear infection anatomy and inflammatory response  -  NurseNest nursing education",
  "stevens-johnson-syndrome": "Hand-drawn illustration of Stevens-Johnson syndrome showing severe skin reaction  -  NurseNest nursing education",
  "toxic-epidermal-necrolysis": "Clinical illustration of toxic epidermal necrolysis with epidermal detachment  -  NurseNest nursing education",
  "herpes-simplex": "Medical illustration of herpes simplex virus showing vesicular skin lesions  -  NurseNest nursing education",
  "hsv": "Illustration of HSV infection with viral replication in epithelial cells  -  NurseNest nursing education",
  "cold-sores": "Clinical illustration of cold sores showing herpes labialis pathology  -  NurseNest nursing education",
  "herpes-zoster": "Hand-drawn illustration of herpes zoster (shingles) showing dermatomal distribution  -  NurseNest nursing education",
  "herpes-zoster-shingles": "Medical illustration of shingles with varicella-zoster virus reactivation  -  NurseNest nursing education",
  "shingles": "Clinical illustration of shingles showing nerve-distributed vesicular rash  -  NurseNest nursing education",
  "varicella-zoster": "Illustration of varicella-zoster virus lifecycle and reactivation  -  NurseNest nursing education",
  "glaucoma": "Detailed illustration of glaucoma showing increased intraocular pressure and optic nerve damage  -  NurseNest nursing education",
  "glaucoma-management": "Medical illustration of glaucoma management with aqueous humor drainage  -  NurseNest nursing education",
  "vitiligo": "Hand-drawn illustration of vitiligo showing melanocyte loss and depigmentation patterns  -  NurseNest nursing education",
  "cell-structure": "Detailed cell structure illustration showing organelles and membrane components  -  NurseNest nursing education",
  "cell-biology": "Clinical cell biology illustration with labeled cellular organelles  -  NurseNest nursing education",
  "homeostasis": "Illustration of homeostasis feedback loops showing negative and positive feedback mechanisms  -  NurseNest nursing education",
  "feedback-loops": "Medical illustration of physiological feedback loop regulation  -  NurseNest nursing education",
  "psoriasis": "Clinical illustration of psoriasis showing epidermal hyperproliferation and plaque formation  -  NurseNest nursing education",
  "contact-dermatitis": "Illustration of contact dermatitis showing allergic skin reaction  -  NurseNest nursing education",
  "melanoma": "Medical illustration of melanoma showing malignant melanocyte transformation  -  NurseNest nursing education",
  "urticaria": "Clinical illustration of urticaria (hives) showing mast cell histamine release  -  NurseNest nursing education",
  "scabies": "Medical illustration of scabies mite infestation in skin layers  -  NurseNest nursing education",
  "impetigo": "Illustration of impetigo showing superficial bacterial skin infection  -  NurseNest nursing education",
  "anaphylaxis": "Clinical illustration of anaphylaxis showing systemic allergic response  -  NurseNest nursing education",
  "compartment-syndrome": "Medical illustration of compartment syndrome showing tissue pressure buildup  -  NurseNest nursing education",
  "malignant-hyperthermia": "Illustration of malignant hyperthermia showing uncontrolled muscle metabolism  -  NurseNest nursing education",
  "ards-management": "Clinical illustration of acute respiratory distress syndrome with alveolar damage  -  NurseNest nursing education",
  "oxygen-therapy": "Medical illustration of oxygen therapy delivery methods and respiratory support  -  NurseNest nursing education",
  "chest-tube-care": "Illustration of chest tube placement and pleural drainage system  -  NurseNest nursing education",
  "sterile-technique": "Hand-drawn illustration of sterile technique principles and aseptic field  -  NurseNest nursing education",
  "seizure-safety": "Clinical illustration of seizure pathophysiology and neuronal excitability  -  NurseNest nursing education",
  "increased-icp": "Medical illustration of increased intracranial pressure with brain herniation risk  -  NurseNest nursing education",
  "increased-icp-np": "Advanced ICP management illustration for nurse practitioners  -  NurseNest nursing education",
  "breast-cancer": "Illustration of breast cancer showing tumor growth and staging  -  NurseNest nursing education",
  "cervical-cancer": "Clinical illustration of cervical cancer with HPV-related cellular changes  -  NurseNest nursing education",
  "prostate-cancer": "Medical illustration of prostate cancer showing glandular involvement  -  NurseNest nursing education",
  "multiple-myeloma": "Illustration of multiple myeloma showing plasma cell proliferation in bone marrow  -  NurseNest nursing education",
  "basal-cell-carcinoma": "Clinical illustration of basal cell carcinoma skin cancer  -  NurseNest nursing education",
  "squamous-cell-carcinoma": "Medical illustration of squamous cell carcinoma  -  NurseNest nursing education",
  "potassium-imbalance-rpn": "Illustration of potassium imbalance showing hyperkalemia and hypokalemia electrolyte effects  -  NurseNest nursing education",
  "hyperkalemia-emergency-np": "Clinical illustration of hyperkalemia emergency with ECG changes and treatment  -  NurseNest nursing education",
};

const systemAltText: Record<string, string> = {
  cardiovascular: "Cardiovascular system medical illustration  -  NurseNest nursing education",
  respiratory: "Respiratory system medical illustration  -  NurseNest nursing education",
  neurological: "Neurological system medical illustration  -  NurseNest nursing education",
  gastrointestinal: "Gastrointestinal system medical illustration  -  NurseNest nursing education",
  renal: "Renal and urinary system medical illustration  -  NurseNest nursing education",
  endocrine: "Endocrine system medical illustration  -  NurseNest nursing education",
  hematology: "Hematology and blood system medical illustration  -  NurseNest nursing education",
  musculoskeletal: "Musculoskeletal system medical illustration  -  NurseNest nursing education",
  immune: "Immune system medical illustration  -  NurseNest nursing education",
  maternity: "Maternity and obstetric nursing medical illustration  -  NurseNest nursing education",
  pediatrics: "Pediatric nursing medical illustration  -  NurseNest nursing education",
  "mental-health": "Mental health nursing medical illustration  -  NurseNest nursing education",
  oncology: "Oncology nursing medical illustration  -  NurseNest nursing education",
  pharmacology: "Pharmacology and medication medical illustration  -  NurseNest nursing education",
  fundamentals: "Nursing fundamentals medical illustration  -  NurseNest nursing education",
  emergency: "Emergency nursing medical illustration  -  NurseNest nursing education",
  sensory: "Sensory system (eye and ear) medical illustration  -  NurseNest nursing education",
  "wound-care": "Wound care nursing medical illustration  -  NurseNest nursing education",
  delegation: "Nursing delegation and prioritization illustration  -  NurseNest nursing education",
  "infection-control": "Infection control nursing medical illustration  -  NurseNest nursing education",
  pain: "Pain management nursing medical illustration  -  NurseNest nursing education",
  palliative: "Palliative and end-of-life care medical illustration  -  NurseNest nursing education",
  community: "Community health nursing illustration  -  NurseNest nursing education",
  cell: "Cell structure and biology medical illustration  -  NurseNest nursing education",
  homeostasis: "Homeostasis and feedback mechanisms medical illustration  -  NurseNest nursing education",
  reproductive: "Reproductive system medical illustration  -  NurseNest nursing education",
  assessment: "Health assessment nursing medical illustration  -  NurseNest nursing education",
};

export function getImageAltText(lessonId: string, fallbackTitle?: string): string {
  if (illustrationAltText[lessonId]) {
    return illustrationAltText[lessonId];
  }

  for (const [key, alt] of Object.entries(systemAltText)) {
    if (lessonId.includes(key)) {
      return alt;
    }
  }

  if (fallbackTitle) {
    return `Medical illustration for ${fallbackTitle}  -  NurseNest nursing education`;
  }

  return "NurseNest hand-drawn medical illustration for nursing education";
}

const illustrationCaption: Record<string, string> = {
  "mi-management": "Coronary artery occlusion with thrombus formation causing downstream myocardial ischemia, injury, and necrosis zones",
  "mi-acute": "Atherosclerotic plaque rupture in coronary artery leading to acute myocardial infarction with coagulative necrosis",
  "mi-pathophysiology": "Cross-section showing coronary occlusion with ischemic zone, injury zone, and necrotic myocardial tissue",
  "hf-advanced": "Comparison of normal heart versus failing heart showing dilated chambers, thinned walls, and pulmonary congestion",
  "hf-cell-pathology": "Hypertrophied cardiac myocytes with disorganized sarcomeres compared to normal organized muscle fibers",
  "heart-failure": "Heart failure pathophysiology showing ventricular dilation, mitral regurgitation, and peripheral edema",
  "chf-basics": "Congestive heart failure with fluid backup into lungs and systemic circulation",
  "copd-exacerbation": "Emphysematous lung with destroyed alveolar walls and chronic bronchitis with thickened airway mucosa",
  "copd-basics-rpn": "COPD pathophysiology showing air trapping, goblet cell hyperplasia, and inflammatory airway changes",
  "asthma-emergency": "Asthmatic bronchiole with bronchospasm, mucosal edema, and mucus plugging versus normal open airway",
  "asthma-basics-rpn": "Comparison of normal versus asthmatic bronchiole showing smooth muscle contraction and mast cell degranulation",
  "asthma-copd": "Side-by-side comparison of asthma (reversible obstruction) versus COPD (irreversible destruction)",
  "stroke-advanced": "Ischemic stroke with clot in cerebral artery showing core infarct and salvageable penumbra zone",
  "stroke": "Two types of stroke: ischemic (blood clot blocking artery) and hemorrhagic (ruptured vessel with blood pooling)",
  "aki-management": "Three types of acute kidney injury: pre-renal (decreased blood flow), intrinsic (tubular damage), and post-renal (obstruction)",
  "ckd-management": "Progressive nephron damage showing glomerular sclerosis and tubular atrophy in chronic kidney disease",
  "dka-hhns": "DKA cascade: insulin deficiency leading to fat breakdown, ketone body production, and metabolic acidosis",
  "dka-management": "Diabetic ketoacidosis showing depleted beta cells, cellular glucose starvation, and Kussmaul breathing",
  "sepsis-mastery": "Sepsis cascade: bacterial invasion triggering cytokine storm, endothelial damage, vasodilation, and multi-organ failure",
  "pe-recognition": "Deep vein thrombus breaking free and lodging in pulmonary artery causing ventilation-perfusion mismatch",
  "pe-dvt": "Pulmonary embolism pathway from DVT in leg through right heart to pulmonary vasculature",
  "increased-icp": "Brain with mass effect showing midline shift, uncal herniation, and brainstem compression with fixed dilated pupil",
  "increased-icp-np": "Increased intracranial pressure causing cerebral herniation syndromes and compressed blood vessels",
  "icp-basics": "Intracranial pressure pathophysiology with swollen brain, compressed ventricles, and tonsillar herniation",
  "preeclampsia": "Abnormal placental spiral artery remodeling causing systemic effects: cerebral edema, proteinuria, and hepatic congestion",
  "sickle-cell": "Sickle-shaped red blood cells blocking small vessels, causing tissue ischemia and splenic sequestration",
  "stevens-johnson-syndrome": "Stevens-Johnson syndrome showing targetoid lesions, vesicle formation, and epidermal detachment with mucosal involvement",
  "stevens-johnson-basics-rpn": "Severe skin reaction with concentric ring lesions and sheet-like skin peeling revealing raw dermis",
  "toxic-epidermal-necrolysis": "Full-thickness epidermal necrosis with extensive skin detachment and subepidermal separation",
  "pressure-injuries": "Pressure injury stages: intact reddened skin (Stage 1), partial-thickness loss (Stage 2), full-thickness with visible fat (Stage 3), exposed muscle/bone (Stage 4)",
  "pressure-ulcers": "Cross-section showing progressive tissue damage over bony prominences from surface redness to deep ulceration",
  "pressure-injury-staging": "Four stages of pressure injury depth from epidermis through dermis, subcutaneous fat, to muscle and bone",
  "burn-management": "Burn depth classification: superficial (red, intact), partial thickness (blisters), and full thickness (waxy white, all layers destroyed)",
  "psoriasis": "Psoriatic skin with hyperkeratosis, elongated rete ridges, and dilated tortuous capillaries compared to normal skin",
  "herpes-zoster": "Herpes zoster reactivation from dorsal root ganglion along sensory nerve with dermatomal vesicular rash pattern",
  "herpes-zoster-shingles": "Shingles showing grouped vesicles in unilateral band-like distribution following a single dermatome",
  "shingles": "Varicella zoster virus reactivating from nerve ganglion causing vesicles at various stages along a dermatome",
  "shingles-herpes-zoster-rpn": "Dermatomal distribution of herpes zoster rash with vesicles progressing to pustules and crusted lesions",
  "cellulitis": "Cellulitis showing diffuse spreading infection into deep dermis versus erysipelas with sharply demarcated raised border",
  "compartment-syndrome": "Lower leg fascial compartments with one showing increased pressure, compressed blood vessels, and muscle ischemia",
  "guillain-barre": "Peripheral nerve showing segmental demyelination by macrophages with ascending paralysis pattern",
  "ards-management": "ARDS alveolus with hyaline membrane formation, protein-rich edema fluid, and damaged type I pneumocytes versus normal",
  "pneumonia-basics": "Lobar consolidation with alveoli filled with purulent exudate containing neutrophils, bacteria, and fibrin strands",
  "pneumonia-management": "Pneumonia pathophysiology with congested capillaries, inflammatory alveolar exudate, and pleural effusion",
  "pneumonia-community": "Community-acquired pneumonia showing bacterial invasion of alveoli and inflammatory consolidation",
  "pneumonia-hospital": "Hospital-acquired pneumonia with ventilator-associated inflammatory changes in lung tissue",
  "pneumonia-aspiration": "Aspiration pneumonia with gastric contents entering lower airways causing chemical and bacterial pneumonitis",
  "pneumonia-basics-rpn": "Pneumonia cross-section showing infected alveoli with exudate alongside normal aerated alveoli",
  "myasthenia-gravis": "Neuromuscular junction showing antibodies destroying acetylcholine receptors, causing muscle weakness and ptosis",
  "dic-basics": "DIC paradox: simultaneous microthrombi in small vessels consuming clotting factors while causing diffuse bleeding",
  "coagulation-cascade": "Coagulation cascade with excessive factor consumption leading to fibrinolysis and D-dimer production",
  "cirrhosis-management": "Cirrhotic liver with portal hypertension causing esophageal varices, ascites, splenomegaly, and caput medusae",
  "acute-pancreatitis": "Pancreatitis showing autodigestion by activated enzymes, fat necrosis, and Grey Turner/Cullen signs",
  "parkinsons-disease": "Depleted dopaminergic neurons in substantia nigra with Lewy bodies, causing tremor, rigidity, and shuffling gait",
  "parkinsons": "Parkinson disease showing basal ganglia circuit imbalance with characteristic motor signs on body silhouette",
  "multiple-sclerosis": "MS showing demyelinated nerve fibers with inflammatory plaques, oligodendrocyte damage, and astrocyte scarring",
  "ms-management": "Multiple sclerosis with periventricular white matter lesions and spinal cord demyelination",
  "thyroid-function": "Comparison of hypothyroid (goitrous, lymphocytic infiltration) versus hyperthyroid (diffuse enlargement, follicular hyperplasia)",
  "hypothyroidism-basics": "Hypothyroidism effects: weight gain, bradycardia, cold intolerance, dry skin, and periorbital edema",
  "hyperthyroidism-basics": "Hyperthyroidism effects: weight loss, tachycardia, heat intolerance, tremor, and exophthalmos",
  "thyroidectomy": "Thyroid gland disorders with cellular changes in Hashimoto versus Graves disease",
  "adrenal-insufficiency": "Addison disease showing atrophied adrenal cortex with cortisol and aldosterone deficiency effects",
  "adrenal-function": "Adrenal gland cross-section showing destroyed cortical zones with ACTH-driven hyperpigmentation",
  "electrolyte-safety": "Electrolyte effects on cardiac cells: hyperkalemia (peaked T waves, wide QRS) versus hypokalemia (flat T waves, U waves)",
  "gi-bleed": "GI bleeding sources: esophageal varices, Mallory-Weiss tear, gastric ulcer, diverticular bleed, and colorectal polyp",
  "gi-bleed-basics-rpn": "Upper and lower GI bleeding sources with ulcer penetrating through wall layers to blood vessel",
  "sle-autoimmune": "Lupus showing butterfly malar rash, joint synovitis, pericarditis, and glomerulonephritis from immune complex deposits",
  "anaphylaxis": "Anaphylaxis: mast cell degranulation releasing histamine causing laryngeal edema, bronchospasm, vasodilation, and urticaria",
  "active-tb": "Tuberculosis granuloma with central caseous necrosis, Langhans giant cells, and epithelioid macrophage cuff",
  "tuberculosis": "TB comparison: latent (walled-off granuloma) versus active (cavity formation with liquefaction and acid-fast bacilli)",
  "latent-tb": "Latent TB with encapsulated Ghon complex granuloma and fibrotic capsule containing dormant bacilli",
  "tb-screening": "Primary Ghon complex showing caseating granuloma in mid-lung zone with hilar lymph node involvement",
  "tb-basics-rpn": "Tuberculosis pathophysiology showing granuloma structure and bacterial containment in latent versus active disease",
  "seizure-safety": "Seizure pathophysiology: hypersynchronous neuronal firing with excessive glutamate and insufficient GABA inhibition",
  "seizure-types-priorities-rpn": "Focal seizure origin in temporal lobe spreading to generalized bilateral hemisphere involvement",
  "status-epilepticus": "Sustained seizure activity showing abnormal spike-and-wave pattern spreading across brain hemispheres",
  "placenta-previa-abruption": "Placenta previa (implanted over cervical os) versus placental abruption (premature separation with retroplacental clot)",
  "meningitis": "Inflamed meninges with purulent exudate in subarachnoid space, cloudy CSF, and petechial rash of meningococcemia",
  "glaucoma": "Glaucoma: open-angle (clogged trabecular meshwork) versus angle-closure (iris blocking drainage), with optic disc cupping",
  "glaucoma-management": "Aqueous humor drainage impairment causing elevated intraocular pressure and optic nerve damage",
  "glaucoma-rpn": "Comparison of normal optic disc versus glaucomatous cupping with peripheral visual field loss pattern",
  "postpartum-hemorrhage": "PPH four T's: Tone (boggy uterus), Trauma (laceration), Tissue (retained placenta), Thrombin (coagulopathy)",
  "postpartum-hemorrhage-basics-rpn": "Postpartum hemorrhage showing atonic uterus versus well-contracted uterus with spiral artery hemostasis",
  "ulcerative-colitis": "Ulcerative colitis showing continuous mucosal inflammation from rectum proximally, with crypt abscesses and pseudopolyps",
  "peptic-ulcer": "Peptic ulcer disease: gastric ulcer crater with exposed blood vessel, H. pylori colonization, and disrupted mucosal barrier",
  "peptic-ulcer-basics-rpn": "Gastric and duodenal ulcers showing mucosa erosion with H. pylori bacteria and complications of perforation and bleeding",
  "bowel-obstruction": "Mechanical bowel obstruction with dilated proximal loops, collapsed distal bowel, and adhesion band causing obstruction",
  "acute-abdomen": "Bowel obstruction and volvulus showing twisted ischemic bowel with bacterial translocation and third-spacing",
  "cushing-syndrome": "Cushing syndrome features: moon face, buffalo hump, central obesity, purple striae, thin extremities, and easy bruising",
  "siadh-di": "SIADH (excess ADH, water retention, hyponatremia) versus Diabetes Insipidus (deficient ADH, water loss, hypernatremia)",
  "siadh-basics-rpn": "SIADH showing pituitary releasing excess ADH causing dilute blood and concentrated urine with cerebral edema risk",
  "diabetes-insipidus-basics-rpn": "Diabetes insipidus: kidneys unable to concentrate urine, producing massive dilute output with dehydration",
  "retinal-detachment": "Retinal detachment types: rhegmatogenous (tear), tractional (fibrovascular pulling), and exudative (fluid leakage)",
  "retinal-detachment-rpn": "Retina peeling away from pigment epithelium with subretinal fluid accumulation and photoreceptor ischemia",
  "aortic-dissection": "Aortic dissection: intimal tear creating false lumen between aortic wall layers with branch vessel malperfusion",
  "dvt-management": "Deep vein thrombosis with Virchow triad: venous stasis, endothelial injury, and hypercoagulability forming layered thrombus",
  "pad-claudication": "Peripheral arterial disease with atherosclerotic narrowing causing intermittent claudication and tissue ischemia",
  "neonatal-jaundice-basics": "Neonatal jaundice: immature liver unable to conjugate bilirubin, with risk of kernicterus and phototherapy mechanism",
  "hyperbilirubinemia": "Bilirubin metabolism: RBC breakdown to unconjugated bilirubin, hepatic conjugation, and neonatal liver immaturity",
  "breast-cancer": "Invasive ductal carcinoma breaking through basement membrane with lymphatic spread and peau d'orange skin changes",
  "rhabdomyolysis": "Crushed muscle fibers releasing myoglobin, potassium, and phosphate, causing myoglobin cast nephropathy in kidneys",
  "av-fistula": "Surgically created arteriovenous fistula connecting radial artery to cephalic vein for hemodialysis access",
  "dialysis-steal": "AV fistula with steal syndrome showing arterialized vein and hand ischemia distal to the access site",
  "infective-endocarditis": "Valve vegetations (fibrin, platelets, bacteria) with embolic phenomena: Janeway lesions, Osler nodes, splinter hemorrhages",
  "endocarditis-basics-rpn": "Endocarditis showing infected valve leaflets with septic emboli traveling to brain, kidney, and skin",
  "gestational-diabetes": "Placental hormones causing maternal insulin resistance with fetal macrosomia and neonatal hypoglycemia risk",
  "fetal-monitoring-rn": "Fetal heart rate patterns: early decelerations (head compression), late (uteroplacental insufficiency), variable (cord compression)",
  "fetal-monitoring-basics-rpn": "Fetal heart rate tracing showing baseline variability, accelerations, and deceleration types with uterine contractions",
  "malignant-hyperthermia": "Abnormal ryanodine receptor releasing massive calcium causing sustained muscle contraction, heat production, and cell breakdown",
  "cardiogenic-shock": "Massive left ventricular failure with decreased cardiac output, pulmonary congestion, and compensatory vasoconstriction",
  "shock-syndromes": "Shock states showing cardiovascular collapse with decreased perfusion to vital organs",
  "shock-types-recognition-rpn": "Types of shock: cardiogenic, distributive, hypovolemic, and obstructive with hemodynamic differences",
  "tracheostomy-care": "Tracheostomy tube anatomy: outer and inner cannula, cuff, obturator, positioned between tracheal rings with surrounding anatomy",
  "tracheostomy": "Sagittal neck cross-section showing tracheostomy tube placement between 2nd and 3rd tracheal rings",
  "tracheostomy-suctioning": "Suctioning catheter inserted through tracheostomy tube with surrounding airway anatomy",
  "tracheostomy-basics-rpn": "Tracheostomy tube components and correct positioning with thyroid gland and esophagus visible",
  "chest-tube-care": "Chest tube in pleural space draining pneumothorax through three-chamber drainage system with lung re-expansion",
  "eczema-atopic-dermatitis": "Atopic dermatitis: impaired skin barrier with filaggrin loss, allergen penetration, and Th2 immune response with pruritus",
  "atopic-dermatitis": "Eczema showing disrupted stratum corneum, transepidermal water loss, and itch-scratch cycle with lichenification",
  "contact-dermatitis": "Contact dermatitis with allergic skin reaction causing erythema, vesicles, and excoriations from scratching",
  "skin-integrity": "Wound healing phases: hemostasis (platelet plug), inflammation (immune cells), proliferation (granulation), and remodeling (collagen)",
  "wound-care": "Wound healing progression from hemostasis through inflammatory, proliferative, and remodeling phases",
  "blood-products": "Blood typing showing red blood cell surface antigens (A, B, AB, O) with corresponding plasma antibodies",
  "blood-transfusion-rpn": "Blood type compatibility: ABO system with antigens on RBC surface and antibodies in plasma",
  "insulin-safety": "Pancreatic islets of Langerhans with beta cells producing insulin and glucose uptake at cellular receptors",
  "dm-type1": "Type 1 diabetes: autoimmune destruction of pancreatic beta cells with absolute insulin deficiency",
  "dm-type2": "Type 2 diabetes: insulin resistance at cellular receptors with progressive beta cell dysfunction",
  "diabetes-lifespan": "Pancreatic function showing insulin regulation of blood glucose across the lifespan",
  "fracture-types": "Bone fracture classifications: transverse, oblique, spiral, comminuted, greenstick, and compound (open)",
  "fracture-sprain-care": "Various fracture patterns on long bone showing cortical disruption and displacement types",
  "cast-care": "Bone fracture immobilization with cast showing cortical and cancellous bone structure",
  "sle-autoimmune": "Systemic lupus erythematosus: antinuclear antibodies attacking cell nuclei with butterfly rash and joint inflammation",
  "spinal-cord-injury": "Spinal cord cross-section showing gray matter, white matter, nerve roots, and meningeal layers",
  "atrial-fibrillation-rn": "ECG rhythm showing irregularly irregular pattern without distinct P waves characteristic of atrial fibrillation",
  "atrial-flutter-rn": "ECG tracing showing sawtooth flutter waves with regular atrial activity and ventricular response",
  "vtach-management": "Wide complex ventricular tachycardia rhythm on ECG monitor with rapid regular QRS complexes",
  "vfib-management": "Ventricular fibrillation showing chaotic electrical activity without organized QRS complexes",
  "heart-block-complete": "Complete heart block with independent atrial and ventricular rhythms showing AV dissociation",
  "cardiac-rhythm-rn": "Normal sinus rhythm ECG strip with clearly visible P waves, QRS complexes, and T waves",
};

export function getImageCaption(lessonId: string): string | undefined {
  return illustrationCaption[lessonId];
}

export function getImageTitle(lessonId: string, lessonTitle?: string): string {
  if (lessonTitle) {
    return `${lessonTitle}  -  NurseNest Clinical Illustration`;
  }
  return "NurseNest Clinical Illustration";
}

export function getImageStructuredData(lessonId: string, src: string, lessonTitle?: string) {
  return {
    "@type": "ImageObject",
    name: getImageTitle(lessonId, lessonTitle),
    description: getImageAltText(lessonId, lessonTitle),
    contentUrl: src,
    creator: {
      "@type": "Organization",
      name: "NurseNest",
      url: "https://www.nursenest.ca",
    },
    copyrightHolder: {
      "@type": "Organization",
      name: "NurseNest",
    },
    copyrightNotice: `© ${new Date().getFullYear()} NurseNest. All rights reserved.`,
    license: "https://www.nursenest.ca/terms",
    acquireLicensePage: "https://www.nursenest.ca/terms",
  };
}
