import type { AlliedAuthoredTopic } from "./types";

export const alliedTopics03: AlliedAuthoredTopic[] = [
  {
    id: "imaging-radiation-protection",
    careerType: "imaging",
    examTag: "ARRT Radiography",
    regionScope: "US",
    category: "Safety",
    topic: "Radiation Protection and ALARA",
    bottomLine: "Use justification, optimization, time-distance-shielding principles, collimation, appropriate technique, and exposure monitoring to keep radiation dose as low as reasonably achievable while producing diagnostic images.",
    coreConcept: "Patient and occupational dose are reduced most effectively by avoiding unnecessary exposure and controlling beam size, technique, distance, shielding, and repeat imaging.",
    recognition: "Repeat exposures, poor collimation, unnecessary fluoroscopy time, close proximity to scatter, or technique that is inconsistent with patient size increases avoidable dose.",
    workflow: "Verify indication and identity, assess pregnancy status when relevant, select protocol, collimate, choose appropriate exposure factors, use shielding and distance for staff, acquire the image, evaluate quality, and avoid repeats through correction of the root cause.",
    interpretation: "A technically acceptable image at lower dose is preferable to a cosmetically ideal image obtained with unnecessary exposure; dose and image quality must be optimized together.",
    safety: "Never trade away required diagnostic quality, but do not increase dose merely to reduce image noise beyond what the clinical task requires.",
    redFlags: "Unintended exposure, wrong patient/body part, equipment dose alarm, pregnancy concern, or repeated fluoroscopic exposure requires immediate pause and escalation.",
    commonErrors: "Using shielding instead of collimation as the primary dose-control strategy, standing close to scatter without need, and repeating images before identifying why the first image failed.",
    examFocus: "ARRT questions often ask which action reduces dose most directly without degrading required diagnostic information.",
    glossary: [
      { term: "ALARA", definition: "Radiation protection principle of keeping exposure as low as reasonably achievable." },
      { term: "Collimation", definition: "Restriction of the x-ray beam to the area of clinical interest." },
    ],
  },
  {
    id: "imaging-image-quality",
    careerType: "imaging",
    examTag: "ARRT Radiography",
    regionScope: "US",
    category: "Image Production",
    topic: "Exposure Factors and Image Quality",
    bottomLine: "Control receptor exposure, contrast, spatial resolution, distortion, and noise by matching kVp, mAs, geometry, collimation, grid use, motion control, and detector processing to the exam.",
    coreConcept: "Technique changes affect photon energy and quantity differently; digital post-processing cannot recover information that was never captured or remove all consequences of overexposure.",
    recognition: "Quantum mottle suggests inadequate receptor exposure, motion reduces sharpness, poor positioning causes distortion, and scatter reduces contrast.",
    workflow: "Assess patient habitus and exam goal, choose kVp/mAs and grid appropriately, position and center accurately, minimize motion, collimate, expose, evaluate histogram/exposure indicator and anatomy, then correct the specific failure if a repeat is truly needed.",
    interpretation: "An image can look acceptable on a digital display while exposure is excessive, so exposure indicators and technique history matter in dose management.",
    safety: "Do not compensate for poor positioning or motion by simply increasing exposure; fix the underlying geometry or immobilization problem.",
    redFlags: "Repeated saturation, exposure indicators consistently outside target, clipping of required anatomy, or equipment behavior inconsistent with selected technique requires investigation.",
    commonErrors: "Using brightness as a proxy for exposure in digital imaging, ignoring exposure indicators, and increasing mAs to fix motion blur.",
    examFocus: "Know which factor primarily changes penetration, receptor exposure, scatter, magnification, and motion unsharpness.",
    glossary: [
      { term: "Quantum mottle", definition: "Image noise caused by insufficient detected x-ray photons." },
      { term: "Exposure indicator", definition: "Digital system metric reflecting detector exposure relative to the system target." },
    ],
  },
  {
    id: "imaging-positioning-chest",
    careerType: "imaging",
    examTag: "ARRT Radiography",
    regionScope: "US",
    category: "Procedures",
    topic: "Chest Radiography Positioning and Evaluation",
    bottomLine: "A diagnostic chest image requires correct projection, inspiration, rotation control, centering, coverage, and exposure sufficient to evaluate lungs and mediastinum without avoidable repeat imaging.",
    coreConcept: "Positioning changes apparent heart size, lung expansion, scapular superimposition, and mediastinal geometry; projection matters when interpreting anatomy.",
    recognition: "Rotation is suggested by asymmetric medial clavicles, poor inspiration by low rib count, and AP projection can magnify the heart compared with PA.",
    workflow: "Confirm projection and patient ability, position chest against receptor when feasible, elevate chin, roll shoulders forward for PA, center appropriately, coach full inspiration, expose, and evaluate anatomy and technical quality.",
    interpretation: "Apparent cardiomegaly on a portable AP image may partly reflect magnification and should not be interpreted like a standard upright PA image.",
    safety: "Prioritize respiratory stability and lines/tubes in critically ill patients rather than forcing ideal positioning that compromises safety.",
    redFlags: "Severe respiratory distress, unstable chest tube or line, sudden deterioration, or inability to safely stand requires adapted technique and clinical coordination.",
    commonErrors: "Clipping costophrenic angles, rotating the patient, failing to move scapulae laterally, and judging heart size without considering projection.",
    examFocus: "ARRT items often ask which positioning error explains a specific image appearance.",
    glossary: [
      { term: "PA projection", definition: "Posteroanterior projection in which the x-ray beam enters posteriorly and exits anteriorly." },
      { term: "Rotation", definition: "Misalignment of the patient relative to the receptor that distorts thoracic symmetry." },
    ],
  },
  {
    id: "imaging-contrast-media",
    careerType: "imaging",
    examTag: "ARRT Radiography",
    regionScope: "US",
    category: "Patient Care",
    topic: "Iodinated Contrast Media Safety",
    bottomLine: "Screen for prior reaction and relevant risk factors, verify the correct agent and route, maintain emergency readiness, recognize acute reactions quickly, and stop or escalate according to severity.",
    coreConcept: "Contrast reactions range from mild self-limited symptoms to severe airway, cardiovascular, or anaphylactoid emergencies; early recognition matters more than predicting every reaction.",
    recognition: "Limited hives or nausea may be mild, while facial or laryngeal edema, wheeze, severe hypotension, altered consciousness, or rapidly progressive symptoms are severe.",
    workflow: "Verify identity/order, review screening information, establish required access, confirm contrast and dose, monitor during administration, stop injection if a serious reaction or extravasation occurs, summon help, and document.",
    interpretation: "A prior contrast reaction is more clinically relevant than unrelated food or shellfish allergy; risk assessment should not be based on myths.",
    safety: "Never leave a patient with evolving airway or circulatory symptoms unattended; have emergency equipment and escalation pathways immediately available.",
    redFlags: "Stridor, bronchospasm, hypotension, cyanosis, rapidly expanding extravasation, severe pain, neurovascular compromise, or loss of consciousness requires urgent response.",
    commonErrors: "Treating shellfish allergy as a unique iodinated-contrast contraindication, underestimating progressive symptoms, and failing to verify contrast identity before injection.",
    examFocus: "Classify reaction severity and choose the first safety action rather than overfocusing on rare mechanisms.",
    glossary: [
      { term: "Extravasation", definition: "Inadvertent leakage of injected contrast or medication into surrounding tissue." },
      { term: "Iodinated contrast", definition: "Iodine-containing radiopaque agent commonly used in CT and angiographic imaging." },
    ],
  },
  {
    id: "imaging-mobile-carm",
    careerType: "imaging",
    examTag: "ARRT Radiography",
    regionScope: "US",
    category: "Procedures",
    topic: "Mobile and C-Arm Imaging",
    bottomLine: "Portable and fluoroscopic imaging requires deliberate positioning, infection control, beam geometry, communication, and scatter protection because the environment is less controlled than a fixed room.",
    coreConcept: "Scatter exposure rises near the patient and during fluoroscopy; distance, shielding, pulse rate, beam-on time, collimation, and equipment geometry all influence staff and patient dose.",
    recognition: "Crowded rooms, sterile fields, life-support equipment, repeated fluoroscopic runs, and poor source-detector geometry create predictable safety risks.",
    workflow: "Coordinate with the care team, verify patient/procedure, protect sterile fields, position equipment and detector, maximize practical distance and shielding, collimate, minimize beam-on time, acquire only required images, and document exposure as required.",
    interpretation: "Keeping the detector close to the patient and using efficient geometry generally improves image quality and reduces unnecessary dose compared with avoidable air gaps.",
    safety: "Do not move equipment through sterile or critical lines without a clear plan and team communication.",
    redFlags: "Loss of sterility, line/tube displacement, unexpected high-dose alert, collision risk, or inability to maintain staff radiation protection requires pause and correction.",
    commonErrors: "Relying on lead alone while standing unnecessarily close, leaving the beam on during repositioning, and failing to communicate before moving the C-arm.",
    examFocus: "Choose geometry and workflow actions that reduce scatter and fluoroscopy time without compromising the procedure.",
    glossary: [
      { term: "Scatter radiation", definition: "Radiation deflected from its original path after interaction, a major source of occupational exposure in fluoroscopy." },
      { term: "Pulse rate", definition: "Number of fluoroscopic x-ray pulses per second; lower rates can reduce dose when clinically adequate." },
    ],
  },
  {
    id: "imaging-trauma-spine",
    careerType: "imaging",
    examTag: "ARRT Radiography",
    regionScope: "US",
    category: "Procedures",
    topic: "Trauma Imaging and Spinal Precautions",
    bottomLine: "In trauma, preserve alignment and life-support priorities, use horizontal-beam or adapted techniques when needed, and never force positioning that could worsen an unstable injury.",
    coreConcept: "Diagnostic positioning must be modified when movement risk outweighs the benefit of a standard projection.",
    recognition: "High-energy mechanism, focal spine pain, neurologic deficit, altered mental status, or existing immobilization indicates the need for coordinated movement and precautions.",
    workflow: "Review trauma status, coordinate with the team, maintain required alignment, place detector and tube without unnecessary movement, use adapted projections, evaluate required anatomy, and communicate any safety concern before repositioning.",
    interpretation: "An imperfect but diagnostic image obtained safely may be preferable to an ideal projection requiring hazardous movement.",
    safety: "Do not remove immobilization or flex/extend a potentially unstable spine solely to obtain a textbook projection without authorization.",
    redFlags: "New neurologic symptoms, hemodynamic instability, airway compromise, severe pain with movement, or unstable devices requires immediate stop and team reassessment.",
    commonErrors: "Moving the patient to fit routine positioning, prioritizing image perfection over stabilization, and failing to coordinate logrolling.",
    examFocus: "Safety overrides routine positioning rules in unstable trauma.",
    glossary: [
      { term: "Horizontal-beam projection", definition: "Projection using a horizontal x-ray beam to image a patient who cannot be safely repositioned." },
      { term: "Spinal precautions", definition: "Measures used to limit unnecessary spinal movement when instability is possible." },
    ],
  },

  {
    id: "sono-physics-frequency",
    careerType: "diagnosticSonography",
    examTag: "ARDMS SPI",
    regionScope: "BOTH",
    category: "Ultrasound Physics",
    topic: "Frequency, Wavelength, Resolution, and Penetration",
    bottomLine: "Higher frequency improves axial resolution but reduces penetration, so transducer frequency must match target depth and diagnostic task.",
    coreConcept: "Frequency and wavelength are inversely related in a given medium; attenuation rises with frequency, limiting depth.",
    recognition: "A superficial target imaged with unnecessarily low frequency loses detail, while a deep target imaged with too high a frequency may be inadequately visualized.",
    workflow: "Estimate target depth, choose the highest frequency that still penetrates adequately, optimize focal zone and depth, then adjust gain rather than using gain to compensate for absent penetration.",
    interpretation: "Poor visualization caused by attenuation will not be fixed simply by increasing overall gain because gain amplifies noise as well as signal.",
    safety: "Use output power conservatively and optimize image quality with receiver controls before increasing acoustic output when possible.",
    redFlags: "Persistent inability to visualize the target despite appropriate transducer and settings should prompt alternate window, lower frequency, or modality escalation rather than endless gain increase.",
    commonErrors: "Confusing gain with transmitted power, using maximum depth for every exam, and choosing frequency without considering target depth.",
    examFocus: "SPI questions frequently link one physics change to its trade-off in penetration or resolution.",
    glossary: [
      { term: "Frequency", definition: "Number of acoustic cycles per second, measured in hertz." },
      { term: "Wavelength", definition: "Physical length of one acoustic cycle; inversely related to frequency in a fixed medium." },
    ],
  },
  {
    id: "sono-doppler-aliasing",
    careerType: "diagnosticSonography",
    examTag: "ARDMS SPI",
    regionScope: "BOTH",
    category: "Doppler",
    topic: "Pulsed-Wave Doppler and Aliasing",
    bottomLine: "Aliasing occurs when Doppler shift exceeds the Nyquist limit in pulsed-wave Doppler; correct it by increasing PRF/scale, lowering transmit frequency, shifting baseline, using a lower Doppler frequency, or changing modality when appropriate.",
    coreConcept: "The Nyquist limit equals one-half the pulse repetition frequency, so sampling rate constrains the maximum unambiguous Doppler shift.",
    recognition: "Spectral wraparound or abrupt color reversal in high-velocity flow can represent aliasing rather than true reversal.",
    workflow: "Confirm the artifact, increase scale/PRF, adjust baseline, reduce depth if possible to permit higher PRF, lower Doppler frequency, optimize angle, and use continuous-wave Doppler if very high velocity must be measured without range specificity.",
    interpretation: "Baseline shift changes display allocation but does not increase the true Nyquist limit; PRF or other acquisition changes are needed to expand measurable velocity range.",
    safety: "Do not report an aliased velocity as a true peak value without correcting the acquisition limitation.",
    redFlags: "A velocity used for stenosis grading that remains clipped or aliased requires technical correction before diagnostic interpretation.",
    commonErrors: "Treating baseline shift as a true increase in Nyquist limit and measuring a truncated spectral envelope.",
    examFocus: "Know which control actually changes sampling limits versus only changing display.",
    glossary: [
      { term: "Nyquist limit", definition: "Maximum Doppler frequency shift measurable without aliasing in pulsed-wave Doppler, equal to half the PRF." },
      { term: "PRF", definition: "Pulse repetition frequency, the number of transmitted pulse groups per second." },
    ],
  },
  {
    id: "sono-artifacts",
    careerType: "diagnosticSonography",
    examTag: "ARDMS SPI",
    regionScope: "BOTH",
    category: "Ultrasound Physics",
    topic: "Ultrasound Artifacts and Their Mechanisms",
    bottomLine: "Recognize artifacts by the assumption the system violated—propagation speed, straight-line travel, single reflection, attenuation, or beam geometry—and use that mechanism to decide whether the finding is real.",
    coreConcept: "Ultrasound systems make simplifying assumptions that can create mirror image, reverberation, shadowing, enhancement, refraction, side-lobe, and speed-displacement artifacts.",
    recognition: "Clean posterior shadowing behind calcification, enhancement behind fluid, repeated equally spaced echoes, and duplicated structures across strong reflectors are classic patterns.",
    workflow: "Identify the suspected artifact, change angle or window, alter frequency/focus, compare orthogonal planes, adjust harmonics or compounding when useful, and confirm whether the structure persists anatomically.",
    interpretation: "An artifact that changes predictably with beam angle or window is less likely to represent fixed anatomy.",
    safety: "Do not label pathology from a single plane when a known artifact mechanism is plausible and can be tested with another view.",
    redFlags: "Apparent mass, thrombus, or absent flow that disappears with technical correction should not be reported as pathology without confirmation.",
    commonErrors: "Memorizing artifact names without mechanisms and failing to test a suspicious finding in another plane.",
    examFocus: "SPI commonly asks which violated assumption produced the artifact.",
    glossary: [
      { term: "Reverberation", definition: "Artifact caused by repeated back-and-forth reflections between strong interfaces." },
      { term: "Posterior enhancement", definition: "Increased echoes deep to a low-attenuation structure such as simple fluid." },
    ],
  },
  {
    id: "sono-abdominal-aorta",
    careerType: "diagnosticSonography",
    examTag: "ARDMS SPI",
    regionScope: "BOTH",
    category: "Abdominal Sonography",
    topic: "Abdominal Aorta and Aneurysm Assessment",
    bottomLine: "Survey the abdominal aorta in orthogonal planes, measure outer wall to outer wall at the maximum diameter according to laboratory protocol, evaluate iliac extension, and recognize rupture warning signs.",
    coreConcept: "Aneurysm assessment depends on true maximal diameter and anatomy; oblique measurement can overestimate size.",
    recognition: "Focal dilation, mural thrombus, loss of parallel walls, tenderness with known aneurysm, retroperitoneal fluid, or hemodynamic instability can indicate clinically significant disease.",
    workflow: "Identify proximal, mid, distal aorta and bifurcation, image transverse and longitudinally, optimize gain and depth, measure perpendicular to vessel axis, evaluate iliacs when required, and document limitations.",
    interpretation: "Mural thrombus does not reduce the aneurysm's external diameter for risk assessment; measure the full outer wall dimension.",
    safety: "In an unstable patient with suspected rupture, do not prolong scanning for perfect documentation at the expense of emergency care.",
    redFlags: "Severe abdominal/back pain, hypotension, known aneurysm, retroperitoneal fluid, or rapidly enlarging aneurysm warrants urgent escalation.",
    commonErrors: "Measuring the patent lumen instead of outer diameter, using an oblique plane, and failing to scan the entire aorta.",
    examFocus: "Differentiate lumen from total aneurysm diameter and know why orthogonal imaging matters.",
    glossary: [
      { term: "Mural thrombus", definition: "Thrombus attached to the vessel wall within an aneurysm." },
      { term: "Orthogonal planes", definition: "Imaging planes oriented at right angles, typically transverse and longitudinal." },
    ],
  },
  {
    id: "sono-gallbladder",
    careerType: "diagnosticSonography",
    examTag: "ARDMS SPI",
    regionScope: "BOTH",
    category: "Abdominal Sonography",
    topic: "Gallbladder, Gallstones, and Acute Cholecystitis",
    bottomLine: "Differentiate mobile shadowing stones from sludge and polyps, assess wall and pericholecystic findings, evaluate the sonographic Murphy sign, and correlate with ductal dilation and clinical context.",
    coreConcept: "Acute cholecystitis is a pattern diagnosis; no single ultrasound finding is sufficient in every case.",
    recognition: "Mobile echogenic foci with posterior shadowing support stones; wall thickening, distention, pericholecystic fluid, impacted neck stone, and focal sonographic tenderness increase concern for inflammation.",
    workflow: "Scan supine and decubitus or erect when possible, assess mobility and shadowing, measure wall appropriately, evaluate common bile duct, test focal tenderness with the probe, and document associated findings.",
    interpretation: "Wall thickening is nonspecific and can occur with systemic edema states; it gains meaning when combined with gallstone and inflammatory findings.",
    safety: "Do not repeatedly apply painful probe pressure in a very tender patient beyond what is necessary to establish the finding.",
    redFlags: "Obstructive jaundice, markedly dilated ducts, suspected choledocholithiasis, gallbladder perforation features, or systemic instability requires prompt communication.",
    commonErrors: "Calling sludge a stone without shadowing/mobility, overcalling nonspecific wall thickening, and failing to reposition the patient.",
    examFocus: "Choose the combination of findings that best supports acute cholecystitis rather than one isolated sign.",
    glossary: [
      { term: "Sonographic Murphy sign", definition: "Maximal focal tenderness when the ultrasound transducer presses directly over the gallbladder." },
      { term: "Posterior shadowing", definition: "Reduced echoes deep to a strongly attenuating or reflecting structure such as a calcified stone." },
    ],
  },
  {
    id: "sono-ob-dating",
    careerType: "diagnosticSonography",
    examTag: "ARDMS SPI",
    regionScope: "BOTH",
    category: "Obstetric Sonography",
    topic: "First-Trimester Pregnancy Dating and Viability",
    bottomLine: "Use standardized first-trimester measurements and diagnostic criteria conservatively, document location and viability findings, and avoid declaring pregnancy failure from borderline measurements.",
    coreConcept: "Early pregnancy structures appear in a predictable sequence, but biologic and measurement variation require strict criteria before diagnosing nonviability.",
    recognition: "Gestational sac, yolk sac, embryo, cardiac activity, crown-rump length, adnexal mass, and free fluid are key findings in early pregnancy evaluation.",
    workflow: "Confirm indication and dates, evaluate uterus and adnexa, identify pregnancy location, obtain standardized measurements, document cardiac activity when present, assess free fluid, and follow established criteria for indeterminate findings.",
    interpretation: "A single borderline measurement should not be used to diagnose pregnancy failure; repeat imaging at an appropriate interval may be required.",
    safety: "Use the lowest acoustic output and shortest scanning time needed for diagnostic information, especially in early pregnancy.",
    redFlags: "No confirmed intrauterine pregnancy with pain or bleeding, adnexal mass, significant free fluid, or hemodynamic instability raises concern for ectopic pregnancy and requires urgent communication.",
    commonErrors: "Using nonstandard measurement planes, overcalling a pseudogestational sac, and diagnosing nonviability before criteria are met.",
    examFocus: "Dating and viability questions emphasize correct measurement and conservative thresholds.",
    glossary: [
      { term: "Crown-rump length", definition: "Standard first-trimester embryonic/fetal length measurement used for pregnancy dating." },
      { term: "Pregnancy of unknown location", definition: "Positive pregnancy test without definite intrauterine or ectopic pregnancy identified on imaging." },
    ],
  },
  {
    id: "sono-dvt",
    careerType: "diagnosticSonography",
    examTag: "ARDMS SPI",
    regionScope: "BOTH",
    category: "Vascular Sonography",
    topic: "Lower-Extremity Venous Duplex for DVT",
    bottomLine: "Failure of a vein to compress fully is the primary ultrasound sign of acute DVT; combine compression imaging with color and spectral Doppler as appropriate and scan the required venous segments systematically.",
    coreConcept: "Normal veins collapse under transducer pressure; intraluminal thrombus prevents complete apposition of the walls.",
    recognition: "Noncompressibility, intraluminal echoes, reduced or absent color filling, loss of phasicity, or abnormal augmentation can support venous obstruction.",
    workflow: "Identify vein and adjacent artery, compress at regular intervals, assess color filling and flow characteristics, compare sides when needed, document thrombus extent and limitations, and communicate acute proximal findings promptly.",
    interpretation: "Color filling alone cannot exclude thrombus if compression is abnormal or technically inadequate.",
    safety: "Do not perform forceful augmentation or compression over a markedly painful or clinically unstable area beyond protocol requirements.",
    redFlags: "Acute proximal DVT, extensive iliofemoral thrombosis, severe swelling with threatened limb, or symptoms concerning for pulmonary embolism requires prompt escalation.",
    commonErrors: "Relying on color Doppler instead of compression, confusing artery for vein, and skipping technically difficult segments without documenting limitations.",
    examFocus: "Compression is the decisive sign in standard lower-extremity DVT assessment.",
    glossary: [
      { term: "Compression ultrasound", definition: "Technique assessing whether a vein collapses completely under transducer pressure." },
      { term: "Phasicity", definition: "Normal variation of venous flow with respiration." },
    ],
  },

  {
    id: "cardiacsono-standard-views",
    careerType: "cardiacSonographer",
    examTag: "ARDMS RDCS",
    regionScope: "BOTH",
    category: "Echocardiography",
    topic: "Standard Transthoracic Echocardiographic Views",
    bottomLine: "Acquire standard parasternal, apical, subcostal, and suprasternal views with correct orientation before relying on measurements or Doppler conclusions.",
    coreConcept: "Off-axis imaging changes chamber dimensions, wall thickness, valve appearance, and Doppler alignment, creating avoidable measurement error.",
    recognition: "Foreshortened apex, asymmetric ventricular shape, incomplete valve visualization, or unusual chamber proportions can indicate an off-axis view.",
    workflow: "Start with a standard window, optimize depth and sector width, align the imaging plane to true anatomy, acquire required 2D/M-mode/Doppler data, and use alternate windows when the standard view is limited.",
    interpretation: "A measurement from a foreshortened or oblique plane may underestimate ventricular length or distort function and should not be treated as equivalent to a standard acquisition.",
    safety: "Adapt patient position and scanning pressure for dyspnea, pain, lines, surgery, or hemodynamic instability rather than forcing a routine position.",
    redFlags: "New tamponade physiology, severe ventricular dysfunction, suspected aortic catastrophe, or unstable rhythm during scanning requires immediate communication.",
    commonErrors: "Accepting foreshortened apical views, measuring from nonstandard planes, and narrowing focus so much that important adjacent pathology is missed.",
    examFocus: "RDCS items often ask which view or plane best demonstrates a structure or produces a valid measurement.",
    glossary: [
      { term: "Foreshortening", definition: "Off-axis imaging that truncates the true apex and can distort chamber measurements." },
      { term: "Acoustic window", definition: "Body location and orientation used to transmit and receive ultrasound for cardiac imaging." },
    ],
  },
  {
    id: "cardiacsono-lv-function",
    careerType: "cardiacSonographer",
    examTag: "ARDMS RDCS",
    regionScope: "BOTH",
    category: "Ventricular Function",
    topic: "Left Ventricular Size and Systolic Function",
    bottomLine: "Assess LV function with standardized chamber views, regional wall motion, and validated quantitative methods while avoiding foreshortening and tracing errors.",
    coreConcept: "Ejection fraction reflects volumetric change, but overall function assessment also includes chamber size, wall motion, stroke volume, loading conditions, and image quality.",
    recognition: "Global hypokinesis, regional wall-motion abnormality, chamber dilation, reduced endocardial excursion, or discordant visual and calculated function should prompt careful review.",
    workflow: "Acquire nonforeshortened apical views, optimize endocardial border, trace end-diastolic and end-systolic contours using the validated method, review wall motion segmentally, compare prior studies, and report limitations.",
    interpretation: "Poor endocardial definition can make quantitative EF unreliable; contrast enhancement or an alternate validated method may be needed rather than overconfident tracing.",
    safety: "Communicate newly severe dysfunction or associated hemodynamic findings promptly when the clinical situation is unstable.",
    redFlags: "New severe LV dysfunction, mechanical complication after infarction, marked regional abnormality with ischemic symptoms, or shock physiology requires urgent escalation.",
    commonErrors: "Tracing trabeculations as cavity, foreshortening, assuming EF alone defines hemodynamic status, and ignoring loading conditions.",
    examFocus: "Know how acquisition quality affects Simpson-type volumetric calculation and how regional versus global dysfunction differs.",
    glossary: [
      { term: "Ejection fraction", definition: "Percentage of end-diastolic ventricular volume ejected during systole." },
      { term: "Regional wall motion", definition: "Segmental pattern of myocardial contraction used to identify localized dysfunction." },
    ],
  },
  {
    id: "cardiacsono-aortic-stenosis",
    careerType: "cardiacSonographer",
    examTag: "ARDMS RDCS",
    regionScope: "BOTH",
    category: "Valvular Disease",
    topic: "Aortic Stenosis Doppler Assessment",
    bottomLine: "Grade aortic stenosis using an integrated approach that includes valve morphology, multiple-window peak velocity, mean gradient, continuity-equation valve area, flow state, and data quality.",
    coreConcept: "Doppler underestimates velocity when the beam is not parallel to flow, while continuity-equation error is strongly influenced by LVOT measurement because area depends on diameter squared.",
    recognition: "Calcified restricted cusps, high transvalvular velocity, increased mean gradient, reduced calculated valve area, and discordant low-flow patterns require systematic evaluation.",
    workflow: "Image valve morphology, measure LVOT carefully, obtain pulsed Doppler at the correct LVOT location, acquire continuous-wave Doppler from multiple windows, trace envelopes, calculate gradients/area, and assess stroke volume/flow.",
    interpretation: "Discordant severe valve area with low gradient may reflect low flow, measurement error, or specific low-gradient AS physiology rather than automatically proving or excluding severe stenosis.",
    safety: "Do not report severity from a single suboptimal Doppler window; search for the highest well-aligned velocity.",
    redFlags: "Very severe stenosis with symptoms, reduced LV function, low-flow shock physiology, or new decompensation requires prompt communication.",
    commonErrors: "Using one window only, tracing weak envelopes, placing PW sample too close to the valve, and measuring LVOT obliquely.",
    examFocus: "RDCS questions often center on sources of error in continuity equation and Doppler alignment.",
    glossary: [
      { term: "Continuity equation", definition: "Flow-conservation calculation used to estimate aortic valve area from LVOT and transvalvular velocities." },
      { term: "Mean gradient", definition: "Average systolic pressure gradient across the valve derived from Doppler velocities." },
    ],
  },
  {
    id: "cardiacsono-mitral-regurgitation",
    careerType: "cardiacSonographer",
    examTag: "ARDMS RDCS",
    regionScope: "BOTH",
    category: "Valvular Disease",
    topic: "Mitral Regurgitation Assessment",
    bottomLine: "Assess mitral regurgitation by mechanism and an integrated severity approach using color, vena contracta, flow convergence or quantitative methods, pulmonary venous flow, chamber response, and CW Doppler rather than jet area alone.",
    coreConcept: "Color jet size is strongly affected by loading conditions and machine settings; severity requires multiple concordant findings.",
    recognition: "Flail leaflet, prolapse, restricted leaflet, annular dilation, eccentric wall-hugging jet, systolic pulmonary venous flow reversal, or dense CW signal can support significant MR.",
    workflow: "Define valve morphology and mechanism, optimize color scale, assess jet origin and direction, obtain quantitative parameters when feasible, sample pulmonary veins, assess LA/LV response, and integrate all findings.",
    interpretation: "An eccentric Coanda-effect jet can look deceptively small on color despite severe regurgitation.",
    safety: "Do not downgrade severity because a jet is visually small if the mechanism and supporting hemodynamic findings indicate significant regurgitation.",
    redFlags: "Acute severe MR, flail leaflet with pulmonary edema, mechanical complication after MI, or hemodynamic instability requires urgent communication.",
    commonErrors: "Grading by jet area alone, ignoring eccentric jets, and failing to define mechanism.",
    examFocus: "Mechanism plus integrated severity is the tested principle; no single color measurement is sufficient.",
    glossary: [
      { term: "Vena contracta", definition: "Narrowest portion of a regurgitant jet just downstream from the orifice." },
      { term: "Coanda effect", definition: "Tendency of an eccentric jet to hug an adjacent wall, which can make color jet area underestimate severity." },
    ],
  },
  {
    id: "cardiacsono-diastolic-function",
    careerType: "cardiacSonographer",
    examTag: "ARDMS RDCS",
    regionScope: "BOTH",
    category: "Hemodynamics",
    topic: "Diastolic Function and Filling Pressure",
    bottomLine: "Evaluate diastolic function with age- and rhythm-aware integration of transmitral inflow, tissue Doppler, LA volume, TR velocity, and supporting findings rather than interpreting E/A ratio in isolation.",
    coreConcept: "Transmitral filling depends on relaxation, compliance, left atrial pressure, heart rate, and rhythm, so similar E/A patterns can occur in different physiologic states.",
    recognition: "Reduced e' velocity, elevated E/e', enlarged LA, high TR velocity, short deceleration time, or pseudonormal filling patterns can support elevated filling pressure when concordant.",
    workflow: "Confirm rhythm and heart rate, obtain mitral inflow correctly, measure septal/lateral tissue Doppler, assess LA volume and TR velocity, review LV structure/function, and apply the appropriate integrated algorithm.",
    interpretation: "A seemingly normal E/A ratio can be pseudonormal in a patient with impaired relaxation and elevated LA pressure; tissue Doppler and chamber response help distinguish it.",
    safety: "Report indeterminate findings when criteria are discordant rather than forcing a grade unsupported by data.",
    redFlags: "Markedly elevated filling-pressure pattern with acute pulmonary edema, severe hypertension, or unstable symptoms warrants prompt communication.",
    commonErrors: "Using E/A alone, ignoring rhythm, and applying sinus-rhythm thresholds unchanged to atrial fibrillation.",
    examFocus: "RDCS questions emphasize integrated variables and rhythm-specific limitations.",
    glossary: [
      { term: "e' velocity", definition: "Early diastolic mitral annular tissue Doppler velocity used as a marker of myocardial relaxation." },
      { term: "E/e'", definition: "Ratio of transmitral E velocity to annular e' velocity used as one component in estimating LV filling pressure." },
    ],
  },
  {
    id: "cardiacsono-pericardial-effusion",
    careerType: "cardiacSonographer",
    examTag: "ARDMS RDCS",
    regionScope: "BOTH",
    category: "Pericardial Disease",
    topic: "Pericardial Effusion and Tamponade Physiology",
    bottomLine: "Identify effusion location and size, then assess hemodynamic impact using chamber collapse, respiratory flow variation, IVC findings, and the clinical state; tamponade is a physiologic diagnosis, not a size measurement.",
    coreConcept: "Pericardial pressure can impair filling when it exceeds chamber pressure, and rapid accumulation can cause tamponade with a smaller effusion than chronic slow accumulation.",
    recognition: "Right atrial systolic collapse, right ventricular diastolic collapse, exaggerated respiratory inflow variation, plethoric IVC, tachycardia, and hypotension support tamponade physiology.",
    workflow: "Survey multiple windows, distinguish pericardial from pleural fluid and fat, measure where appropriate, assess chamber interaction and Doppler respiratory variation, evaluate IVC, and correlate urgently with clinical signs.",
    interpretation: "Large effusion without collapse may be less hemodynamically significant than a smaller rapidly accumulating effusion with clear tamponade physiology.",
    safety: "If tamponade physiology is present in an unstable patient, stop pursuing exhaustive measurements and communicate immediately.",
    redFlags: "Hypotension, tachycardia, RV diastolic collapse, severe respiratory variation, and a new effusion after invasive procedure are urgent findings.",
    commonErrors: "Calling tamponade from effusion size alone, confusing pleural fluid with pericardial fluid, and overlooking right-sided chamber collapse timing.",
    examFocus: "Differentiate anatomic effusion from hemodynamic tamponade.",
    glossary: [
      { term: "Tamponade", definition: "Hemodynamic impairment of cardiac filling caused by elevated pericardial pressure." },
      { term: "Plethoric IVC", definition: "Dilated inferior vena cava with reduced inspiratory collapse, a supportive sign of elevated right atrial pressure." },
    ],
  },
  {
    id: "cardiacsono-rv-pulmonary-pressure",
    careerType: "cardiacSonographer",
    examTag: "ARDMS RDCS",
    regionScope: "BOTH",
    category: "Right Heart",
    topic: "Right Ventricular Function and Pulmonary Pressure Estimation",
    bottomLine: "Assess RV size and function from multiple views and estimate pulmonary pressure only when a reliable TR signal and appropriate right-atrial pressure estimate are available.",
    coreConcept: "The RV's complex geometry makes single-plane assessment unreliable; pressure estimation from TR velocity depends heavily on Doppler alignment and signal quality.",
    recognition: "RV dilation, reduced TAPSE or tissue Doppler S', septal flattening, enlarged RA, high TR velocity, and dilated pulmonary artery can support RV pressure or volume overload.",
    workflow: "Optimize RV-focused views, assess dimensions and systolic indices, interrogate TR from multiple windows, use the best complete envelope, estimate RA pressure cautiously, and integrate septal/IVC/pulmonary findings.",
    interpretation: "An incomplete or poorly aligned TR envelope can substantially underestimate pulmonary pressure and should not be forced into a numeric estimate.",
    safety: "Report inability to estimate pressure when data are inadequate; false precision can mislead management.",
    redFlags: "Acute RV dilation with severe dysfunction, McConnell-type pattern in compatible context, severe pulmonary hypertension with syncope, or shock physiology requires prompt communication.",
    commonErrors: "Using a weak incomplete TR signal, estimating RA pressure from IVC without context, and judging RV function from one measurement.",
    examFocus: "Know which measurements assess RV function versus pressure and what invalidates a pressure estimate.",
    glossary: [
      { term: "TAPSE", definition: "Tricuspid annular plane systolic excursion, a measure of longitudinal RV systolic motion." },
      { term: "TR velocity", definition: "Peak tricuspid regurgitation velocity used with the Bernoulli equation to estimate RV-to-RA systolic gradient." },
    ],
  },
  {
    id: "cardiacsono-prosthetic-valves",
    careerType: "cardiacSonographer",
    examTag: "ARDMS RDCS",
    regionScope: "BOTH",
    category: "Valvular Disease",
    topic: "Prosthetic Valve Echocardiography",
    bottomLine: "Interpret prosthetic valves using valve type and size, baseline study, Doppler velocities/gradients, flow state, regurgitation pattern, and structural imaging; do not apply native-valve expectations blindly.",
    coreConcept: "Normal prosthetic valves have characteristic flow profiles and may show physiologic regurgitation; obstruction and patient-prosthesis mismatch require different reasoning.",
    recognition: "Rising gradients from baseline, new restricted leaflet motion, abnormal acceleration time, new pathologic regurgitation, rocking, or paravalvular leak can indicate dysfunction.",
    workflow: "Identify prosthesis type/size, compare prior study, acquire multiple imaging and Doppler windows, calculate relevant indices, assess regurgitation and chamber response, and document limitations from shadowing.",
    interpretation: "High gradient can reflect high flow, small effective orifice/patient-prosthesis mismatch, or true obstruction; trend and supporting indices distinguish them.",
    safety: "New dehiscence, severe regurgitation, or obstructive pattern with symptoms should be communicated promptly.",
    redFlags: "Rocking prosthesis, new severe paravalvular regurgitation, abrupt gradient rise, suspected thrombosis, or endocarditis complication requires urgent escalation.",
    commonErrors: "Comparing to native valve thresholds alone, ignoring valve size and baseline, and labeling physiologic mechanical-valve washing jets as pathologic.",
    examFocus: "Use baseline comparison and prosthesis-specific hemodynamics rather than one isolated gradient.",
    glossary: [
      { term: "Patient-prosthesis mismatch", definition: "Normally functioning prosthetic valve with effective orifice area too small relative to patient body size." },
      { term: "Paravalvular leak", definition: "Regurgitation occurring around rather than through a prosthetic valve sewing ring." },
    ],
  },
];
