import type { AlliedAuthoredTopic } from "./types";

export const DIAGNOSTIC_SONOGRAPHY_PROGRAM_TARGETS = Object.freeze({
  minimumTopics: 200,
  lessonsPerTopic: 5,
  minimumLessons: 1_000,
  minimumQuestionsPerTopic: 60,
  authoredQuestionsPerTopic: 100,
  minimumQuestions: 3_000,
});

/**
 * Diagnostic medical sonography curriculum expansion.
 *
 * These are original teaching blueprints aligned to the competency domains of
 * ARDMS SPI/RDMS and Sonography Canada. They do not reproduce recalled or
 * protected examination items. Each blueprint materializes into five lessons
 * and one hundred original questions through the canonical Allied builders.
 */
export const diagnosticSonographyTopics10: AlliedAuthoredTopic[] = [
  {
    id: "dms-spi-pulse-parameters",
    careerType: "diagnosticMedicalSonography",
    examTag: "ARDMS SPI | Sonography Canada Generalist",
    regionScope: "BOTH",
    category: "Sonography Principles and Instrumentation",
    topic: "Pulse Parameters and Sound Propagation",
    bottomLine: "Connect frequency, period, wavelength, propagation speed, amplitude, power, intensity, pulse duration, spatial pulse length, pulse repetition period, and duty factor instead of memorizing each variable in isolation; the relationships predict resolution, penetration, timing, and exposure.",
    coreConcept: "Frequency and period are reciprocals, wavelength equals propagation speed divided by frequency, and the system assumes an average soft-tissue speed of 1540 m/s when converting round-trip time into depth. Pulse duration equals cycles multiplied by period, while spatial pulse length equals cycles multiplied by wavelength.",
    recognition: "A higher-frequency pulse has a shorter period and wavelength in the same medium; fewer cycles and stronger damping shorten the pulse. A wrong-depth display after sound crosses a medium with a nonstandard speed is a propagation-speed error rather than a gain or attenuation problem.",
    workflow: "Name the requested variable, write its defining relationship, hold medium-dependent variables separate from source-dependent variables, convert units before calculating, and test whether the result fits the expected direction. For depth, remember that the pulse travels to the reflector and back.",
    interpretation: "Changing the source frequency changes wavelength but not propagation speed in a given medium. Increasing pulse repetition frequency shortens the listening interval and reduces maximum unambiguous depth; it does not directly shorten the individual pulse or improve axial resolution.",
    safety: "Use output power and dwell time deliberately. A technically attractive image does not justify unnecessary acoustic output, and changing receiver gain is preferred to increasing transmitted power when the diagnostic information can be recovered without increasing exposure.",
    redFlags: "A calculation that ignores round-trip travel, mixes microseconds with seconds, treats speed as frequency-dependent in soft tissue, or confuses pulse repetition frequency with transmit frequency can reverse the clinical conclusion and must be corrected before relying on the measurement.",
    commonErrors: "Common traps include using wavelength equals frequency divided by speed, assuming higher frequency travels faster, confusing pulse duration with pulse repetition period, and stating that duty factor describes listening time rather than the fraction of time the transducer transmits.",
    examFocus: "Expect multistep questions that ask which parameter changes when frequency, cycle count, damping, imaging depth, or pulse repetition frequency changes; solve from the relationship rather than from a memorized slogan.",
    glossary: [
      { term: "Spatial pulse length", definition: "Physical length of one pulse, calculated as number of cycles multiplied by wavelength." },
      { term: "Duty factor", definition: "Fraction of the pulse repetition period during which sound is being transmitted." },
    ],
  },
  {
    id: "dms-spi-attenuation-interactions",
    careerType: "diagnosticMedicalSonography",
    examTag: "ARDMS SPI | Sonography Canada Generalist",
    regionScope: "BOTH",
    category: "Sonography Principles and Instrumentation",
    topic: "Attenuation and Tissue Interactions",
    bottomLine: "Predict image appearance by separating attenuation from reflection, refraction, scattering, and absorption. Attenuation rises with path length and frequency, while the strength of reflection at a boundary depends mainly on acoustic-impedance mismatch and incidence angle.",
    coreConcept: "Acoustic impedance equals density multiplied by propagation speed. At an interface, part of the incident energy may reflect and part may transmit; absorption converts sound to heat, scattering redirects energy in many directions, and refraction changes direction when speed differs across an oblique boundary.",
    recognition: "Strong specular reflectors are brightest when insonated near perpendicular, rough or small interfaces generate scattered echoes, fluid transmits efficiently, and calcification, bone, or gas can markedly limit transmission. Edge shadowing often reflects refraction rather than central absorption.",
    workflow: "Identify the interface and beam angle, compare expected acoustic impedances and propagation speeds, decide which interaction dominates, then adjust frequency, window, focal position, steering, or compounding. Do not use gain to pretend that missing transmitted information was acquired.",
    interpretation: "A weak distal echo may reflect true attenuation, poor angle, or lack of transmitted energy. Posterior enhancement behind fluid and shadowing behind a highly attenuating object are comparative phenomena relative to adjacent tissue at the same depth.",
    safety: "When repeated insonation or increased power does not restore diagnostic information, change the acoustic window or technique rather than escalating output indefinitely. Document structures that remain incompletely assessed.",
    redFlags: "Failure to distinguish artifact from pathology, especially at organ margins or behind calculi and gas, can create a false mass, hide disease, or trigger an unnecessary intervention and requires orthogonal confirmation.",
    commonErrors: "Do not equate all bright echoes with high attenuation, all shadows with calcification, or all signal loss with inadequate gain. Refraction requires oblique incidence and different propagation speeds, while reflection depends on impedance mismatch.",
    examFocus: "Questions commonly test the attenuation-frequency relationship, impedance equation, incidence-angle effects, Rayleigh scattering, and the mechanism behind enhancement, shadowing, edge artifact, and altered propagation speed.",
    glossary: [
      { term: "Acoustic impedance", definition: "Product of a medium's density and sound propagation speed, governing reflection at interfaces." },
      { term: "Refraction", definition: "Change in sound direction at an oblique boundary when propagation speeds differ." },
    ],
  },
  {
    id: "dms-spi-transducer-construction",
    careerType: "diagnosticMedicalSonography",
    examTag: "ARDMS SPI | Sonography Canada Generalist",
    regionScope: "BOTH",
    category: "Sonography Principles and Instrumentation",
    topic: "Transducer Construction and Array Operation",
    bottomLine: "Choose and evaluate a transducer by linking piezoelectric conversion, element thickness, backing, matching layers, aperture, focusing, steering, footprint, and array architecture to the required depth, resolution, field of view, and access window.",
    coreConcept: "Piezoelectric material converts electrical energy to mechanical vibration during transmission and returning mechanical pressure to voltage during reception. Backing damps ringing and broadens bandwidth; matching layers improve transmission across the large impedance difference between the element and tissue.",
    recognition: "Linear arrays provide a rectangular field and high-frequency superficial detail, curvilinear arrays provide a wider deep field, phased arrays steer through a small footprint, and endocavitary probes bring higher frequencies close to pelvic structures. A dead element creates a persistent dropout tied to the probe.",
    workflow: "Match footprint and frequency to the window and target, inspect probe and cable, confirm correct preset, orient the marker, optimize aperture and focus, test suspicious dropout in another plane or with another transducer, and remove damaged equipment from clinical use according to policy.",
    interpretation: "Electronic sequencing and timing shape, focus, and steer the beam. Aperture and element activation may change with depth; a broad bandwidth supports short pulses and multiple operating frequencies, but the chosen clinical frequency still balances penetration against detail.",
    safety: "Follow manufacturer-compatible cleaning and high-level disinfection requirements, inspect for cracks or delamination, use approved leak testing where applicable, and never continue with a damaged endocavitary or transesophageal probe.",
    redFlags: "Cracked lens material, exposed wiring, failed leak test, unexplained heating, recurrent electrical noise, or a persistent element dropout can threaten the patient or invalidate the examination and requires immediate equipment quarantine and reporting.",
    commonErrors: "Common errors include choosing frequency without considering depth, calling every dropout anatomy, confusing backing with matching-layer function, and assuming electronic focusing corrects an unsuitable footprint or inaccessible acoustic window.",
    examFocus: "Know the functions of each transducer layer, the clinical strengths of linear, curvilinear, phased, matrix, and endocavitary arrays, and how element timing controls steering and focusing.",
    glossary: [
      { term: "Backing material", definition: "Damping material behind the active element that reduces ringing and shortens the pulse." },
      { term: "Matching layer", definition: "Intermediate-impedance layer that improves transfer of acoustic energy between element and patient." },
    ],
  },
  {
    id: "dms-spi-resolution-beam",
    careerType: "diagnosticMedicalSonography",
    examTag: "ARDMS SPI | Sonography Canada Generalist",
    regionScope: "BOTH",
    category: "Sonography Principles and Instrumentation",
    topic: "Beam Formation and Spatial Resolution",
    bottomLine: "Distinguish axial, lateral, elevational, contrast, and temporal resolution and improve the one that limits the clinical task. Axial resolution follows spatial pulse length, while lateral and elevational resolution follow beam thickness in their respective planes.",
    coreConcept: "Two reflectors can be separated only when the imaging system samples them distinctly. Axial resolution is approximately one-half the spatial pulse length and is usually constant with depth for a selected pulse; lateral resolution is best where the beam is narrowest, usually near focus.",
    recognition: "Structures stacked along the beam challenge axial resolution, side-by-side structures challenge lateral resolution, and partial-volume echoes within the slice challenge elevational resolution. Motion that looks discontinuous points to inadequate temporal rather than spatial resolution.",
    workflow: "Define the plane of separation or motion, select the highest frequency that still penetrates, place the focus at or just below the target, narrow sector width and reduce depth when frame rate matters, and confirm a suspected finding in an orthogonal plane.",
    interpretation: "Increasing line density may improve lateral sampling but lower frame rate. Multiple focal zones may sharpen more than one depth while reducing temporal resolution. Receiver processing can improve perceived contrast but cannot reconstruct unresolved anatomy.",
    safety: "Optimize acquisition before making measurements; a precise caliper placed on blurred or partially volumed borders is not an accurate measurement. State technical limitations when resolution prevents reliable characterization.",
    redFlags: "A suspected septation, mural nodule, thrombus, fetal structure, or vessel wall abnormality seen in only one plane at the slice edge must not be accepted without repeat imaging and orthogonal confirmation.",
    commonErrors: "Do not claim that gain improves spatial resolution, that axial resolution changes with focal depth, or that more focal zones always improve the study. The correct adjustment depends on which resolution dimension is limiting.",
    examFocus: "Expect to identify the limiting resolution from reflector orientation and to predict effects of frequency, cycle count, damping, focus, aperture, depth, sector width, line density, and focal-zone count.",
    glossary: [
      { term: "Axial resolution", definition: "Ability to distinguish reflectors separated parallel to the ultrasound beam." },
      { term: "Elevational resolution", definition: "Ability to distinguish structures across the thickness of the imaging slice." },
    ],
  },
  {
    id: "dms-spi-doppler-equation",
    careerType: "diagnosticMedicalSonography",
    examTag: "ARDMS SPI | Sonography Canada Generalist",
    regionScope: "BOTH",
    category: "Sonography Principles and Instrumentation",
    topic: "Doppler Equation and Hemodynamics",
    bottomLine: "Treat every Doppler value as the result of transmitted frequency, reflector velocity, propagation speed, and the cosine of the insonation angle. Reliable velocity measurement requires a representative sample, complete spectral envelope, and angle correction aligned with true flow direction.",
    coreConcept: "The Doppler shift is proportional to transmitted frequency, target velocity, and cosine of the angle, and inversely proportional to propagation speed. Measured shift approaches zero near 90 degrees, so small angle errors at steep angles create large velocity errors.",
    recognition: "Laminar flow tends to show organized velocity distribution, disturbed flow produces spectral broadening and variance, and stenosis accelerates velocity as cross-sectional area falls when volume flow is conserved. Proximal, focal, and distal waveform changes must be interpreted together.",
    workflow: "Identify the vessel and flow direction in B-mode and color, optimize scale and wall filter, keep a small sample volume centered in the stream, align the cursor with the vessel or jet rather than the skin, use the validated angle range, and record reproducible waveforms.",
    interpretation: "A high displayed velocity may be real acceleration or an artifact of angle, scale, sample placement, or spectral tracing. Hemodynamic significance is determined with waveform morphology, ratios, anatomic narrowing, collateral evidence, and the applicable validated criteria.",
    safety: "Never force an angle correction onto an uncertain flow direction or report a fabricated velocity from an incomplete envelope. Repeat from another window and document when the vessel cannot be assessed reliably.",
    redFlags: "A newly absent signal, severe focal acceleration with post-stenotic disturbance, reversed organ flow, acute venous obstruction, or waveform suggesting threatened perfusion requires prompt verification and communication under local protocol.",
    commonErrors: "Common traps include treating red as arterial and blue as venous, applying angle correction at 90 degrees, tracing noise, using a large gate that includes wall motion, and interpreting one velocity without the clinical and anatomic context.",
    examFocus: "Be ready to rearrange the Doppler equation, predict angle-error direction, distinguish velocity from frequency shift, and connect continuity, resistance, pressure gradients, and waveform morphology to disease.",
    glossary: [
      { term: "Doppler shift", definition: "Difference between transmitted and received frequencies caused by motion of acoustic reflectors." },
      { term: "Spectral broadening", definition: "Display of a wider range of velocities, which may reflect disturbed flow or technical factors." },
    ],
  },
  {
    id: "dms-spi-aliasing-controls",
    careerType: "diagnosticMedicalSonography",
    examTag: "ARDMS SPI | Sonography Canada Generalist",
    regionScope: "BOTH",
    category: "Sonography Principles and Instrumentation",
    topic: "Aliasing and Doppler Optimization",
    bottomLine: "Aliasing is a sampling problem in pulsed Doppler: frequencies above one-half the pulse repetition frequency cross the Nyquist limit. Correct it by choosing an adjustment that expands the measurable range without destroying sensitivity to the flow being studied.",
    coreConcept: "The Nyquist limit equals one-half PRF. Imaging depth caps PRF because the system must wait for returning echoes; transmitted frequency, Doppler angle, baseline position, scale, wall filter, gain, and Doppler mode affect how the waveform or color map is displayed and sampled.",
    recognition: "Spectral aliasing wraps the waveform across the baseline, whereas color aliasing shows abrupt color reversal according to the map. True turbulence may coexist with aliasing but persists as disordered flow after scale and gain are optimized.",
    workflow: "Increase scale or PRF, shift the baseline for unidirectional spectral display, lower transmitted frequency, reduce depth, choose a shallower sample window, or use continuous-wave Doppler when peak velocity rather than range specificity is required. Preserve low-flow sensitivity when that is the clinical task.",
    interpretation: "Baseline shift changes display capacity but not the underlying Nyquist limit. Continuous-wave Doppler measures high velocities without aliasing but sacrifices depth specificity, while high-PRF Doppler trades some range ambiguity for greater velocity capability.",
    safety: "Do not eliminate a clinically important low-flow signal by reflexively increasing scale or wall filter. Optimize for the question: detecting slow perfusion requires different settings than recording a high-velocity stenotic jet.",
    redFlags: "A waveform that changes diagnosis only after extreme scale, wall-filter, steering, or gain adjustments must be reacquired with documented technique; apparent absence of flow should be confirmed with sensitive settings and another plane before escalation.",
    commonErrors: "Do not call every mosaic turbulent flow, claim baseline shift raises PRF, use wall filter to correct true aliasing, or switch to continuous-wave Doppler when precise range localization is essential.",
    examFocus: "Questions test the Nyquist relationship, the depth-PRF tradeoff, which control corrects a specific aliasing presentation, and the tradeoff between pulsed, continuous-wave, high-PRF, color, and power Doppler.",
    glossary: [
      { term: "Nyquist limit", definition: "Highest Doppler shift sampled without aliasing, equal to one-half the pulse repetition frequency." },
      { term: "Range ambiguity", definition: "Uncertainty about the depth from which a Doppler signal originated." },
    ],
  },
  {
    id: "dms-spi-bmode-artifacts",
    careerType: "diagnosticMedicalSonography",
    examTag: "ARDMS SPI | Sonography Canada Generalist",
    regionScope: "BOTH",
    category: "Sonography Principles and Instrumentation",
    topic: "B-Mode Artifacts and Corrective Techniques",
    bottomLine: "Name an artifact from its geometry and violated system assumption, then use a targeted manoeuvre to test it. Reverberation, comet tail, ring-down, mirror image, refraction, speed error, side lobes, grating lobes, slice thickness, shadowing, and enhancement have different mechanisms.",
    coreConcept: "B-mode assumes sound travels in a straight line at 1540 m/s, echoes return after one reflection, attenuation is uniform, and a detected echo came from the main beam. Artifacts arise when anatomy or beam behaviour violates one or more of these assumptions.",
    recognition: "Equally spaced repeats suggest reverberation, duplicated anatomy across a strong reflector suggests mirror image, misplaced structures suggest refraction, low-level echoes in a cyst may reflect slice thickness, and clean posterior change suggests shadowing or enhancement.",
    workflow: "Scan in an orthogonal plane, change the acoustic window, alter angle or patient position, adjust focal zone and frequency, use harmonic imaging or spatial compounding when appropriate, and check whether the finding remains anatomically coherent across settings.",
    interpretation: "Some artifacts are diagnostically useful: clean shadowing supports a calcified interface, enhancement supports fluid, and dirty shadowing or ring-down can suggest gas. The artifact is evidence only when its mechanism fits the anatomy and persists appropriately.",
    safety: "Never erase an unexplained echo with aggressive gain reduction or label it artifact without a reproducible test. Preserve representative images and document limitations when an artifact obscures required anatomy.",
    redFlags: "A possible ectopic pregnancy, thrombus, mass nodule, free fluid, fetal anomaly, or organ injury that could also be artifact requires immediate multiplanar verification and escalation when uncertainty remains clinically important.",
    commonErrors: "Common errors include confusing ring-down with comet tail, calling edge shadowing a calculus, mistaking mirror image for a second lesion, and assuming harmonic imaging removes all beam-width and multipath artifacts.",
    examFocus: "Expect image-based descriptions asking for the mechanism, violated assumption, and best confirming adjustment rather than simply the artifact name.",
    glossary: [
      { term: "Reverberation", definition: "Repeated echoes caused by sound traveling back and forth between strong reflectors." },
      { term: "Slice-thickness artifact", definition: "False echoes created when off-plane structures contribute to one displayed imaging slice." },
    ],
  },
  {
    id: "dms-spi-image-optimization",
    careerType: "diagnosticMedicalSonography",
    examTag: "ARDMS SPI | Sonography Canada Generalist",
    regionScope: "BOTH",
    category: "Sonography Principles and Instrumentation",
    topic: "B-Mode Image Optimization",
    bottomLine: "Optimize in a deliberate order: select the correct probe and preset, set depth and field of view, place the focal zone, establish overall gain and time-gain compensation, then refine frequency, dynamic range, harmonics, compounding, persistence, line density, and post-processing for the diagnostic task.",
    coreConcept: "Transmit controls change the insonifying pulse or sampling, receiver controls change amplification of returning signals, and post-processing changes display after storage. Knowing where a control acts prevents unnecessary exposure and preserves raw diagnostic information.",
    recognition: "Uniform excessive brightness points to overall gain, depth-dependent imbalance points to TGC, washed-out tissue differences may need dynamic-range adjustment, blurred motion may reflect persistence or frame rate, and inadequate deep detail may require lower frequency or a new window.",
    workflow: "Begin with anatomy and clinical question, maximize the target on screen without clipping context, use the highest penetrative frequency, place focus at the target, balance near-to-far gain, and change one advanced control at a time while checking whether borders and internal texture become more truthful.",
    interpretation: "A prettier image is not automatically a more diagnostic image. Narrow dynamic range increases contrast but can remove subtle gray information; smoothing and persistence reduce noise while potentially blurring small structures or rapid motion.",
    safety: "Prefer receiver gain over acoustic output when possible, keep output and dwell time as low as reasonably achievable, and avoid repeated prolonged Doppler interrogation of sensitive fetal structures without a clinical indication.",
    redFlags: "If required anatomy remains absent after systematic optimization, do not keep scanning indefinitely or imply a normal study. Change windows, obtain help, document the limitation, and follow the pathway for incomplete or urgent examinations.",
    commonErrors: "Common errors include using power as a brightness control, placing focus far from the target, leaving excessive depth, applying heavy persistence to moving anatomy, and compensating for an unsuitable transducer with gain.",
    examFocus: "Differentiate pre-processing from post-processing, transmit from receive controls, and select the single adjustment that fixes the described defect with the least tradeoff.",
    glossary: [
      { term: "Time-gain compensation", definition: "Depth-selective amplification used to compensate for attenuation of deeper returning echoes." },
      { term: "Dynamic range", definition: "Range of echo amplitudes mapped to the display, affecting the number of gray shades and contrast." },
    ],
  },
  {
    id: "dms-spi-bioeffects-alara",
    careerType: "diagnosticMedicalSonography",
    examTag: "ARDMS SPI | Sonography Canada Generalist",
    regionScope: "BOTH",
    category: "Patient Care and Sonographic Safety",
    topic: "Bioeffects, Output Indices, and ALARA",
    bottomLine: "Use diagnostic ultrasound only for a clinical purpose and obtain the needed information with the lowest reasonable output and shortest dwell time. Interpret thermal and mechanical indices as exposure guides, not proof that an examination is either harmful or risk-free.",
    coreConcept: "Absorption can produce tissue heating, while rarefactional pressure contributes to mechanical effects such as cavitation in susceptible conditions. Thermal index estimates relative heating potential and mechanical index relates to nonthermal mechanical-effect potential.",
    recognition: "Risk management becomes especially important with spectral Doppler, prolonged stationary insonation, sensitive embryonic or fetal tissues, bone near the focus, gas-containing tissues, contrast agents, and examinations performed for nonmedical keepsake purposes.",
    workflow: "Confirm indication, select an appropriate preset, begin at low output, optimize with receiver controls and efficient scanning, monitor displayed indices, limit dwell time, document clinically required measurements, and stop once diagnostic information is obtained.",
    interpretation: "A displayed index is a model-dependent estimate affected by mode and assumptions. Higher values and longer exposure increase concern, but the clinical response is thoughtful optimization rather than an unsupported universal cutoff applied without context.",
    safety: "Avoid unnecessary first-trimester pulsed Doppler, keep the beam moving when prolonged observation is unnecessary, use M-mode when it answers the fetal-heart-rate question, and follow professional guidance and local policy for contrast-enhanced or research applications.",
    redFlags: "Nonmedical scanning, prolonged high-output Doppler without indication, failure to monitor output indices, a hot or damaged transducer, or scanning that continues after the diagnostic endpoint requires immediate correction and reporting as appropriate.",
    commonErrors: "Do not say ultrasound uses ionizing radiation, treat MI and TI as measured tissue injury, assume receiver gain increases patient exposure, or invoke ALARA to justify images too poor to answer the clinical question.",
    examFocus: "Know which control changes acoustic output, which modes tend to produce greater time-averaged intensity, what TI and MI represent, and how to apply ALARA in realistic obstetric and nonobstetric cases.",
    glossary: [
      { term: "Thermal index", definition: "On-screen estimate related to the potential for ultrasound-induced tissue heating under modeled conditions." },
      { term: "Mechanical index", definition: "On-screen indicator related to peak rarefactional pressure and potential nonthermal mechanical effects." },
    ],
  },
  {
    id: "dms-spi-quality-assurance",
    careerType: "diagnosticMedicalSonography",
    examTag: "ARDMS SPI | Sonography Canada Generalist",
    regionScope: "BOTH",
    category: "Professional Practice and Quality",
    topic: "Equipment Quality Assurance and Infection Prevention",
    bottomLine: "Quality assurance is a trend-based safety system, not a one-time image check. Test equipment consistently, recognize probe and system failure patterns, maintain traceable records, and pair every examination with risk-based cleaning, disinfection, and barrier practice.",
    coreConcept: "Performance testing evaluates uniformity, sensitivity, distance accuracy, resolution, dead zone, display, and Doppler function against a baseline. Infection prevention classifies equipment by contact risk and applies the required cleaning and disinfection level before reuse.",
    recognition: "Persistent vertical dropout suggests element failure, progressive loss of penetration suggests sensitivity change, inaccurate calipers suggest distance-calibration error, and recurrent contamination or barrier failure signals a process defect rather than an isolated inconvenience.",
    workflow: "Inspect equipment before use, perform scheduled phantom and functional checks with the same method and settings, compare with baseline and tolerance, label and remove unsafe equipment, report and document defects, clean before disinfection, and verify reprocessing compatibility.",
    interpretation: "One abnormal test should be confirmed according to protocol, but a concerning safety defect should not remain in service during investigation. Trends matter because gradual deterioration may stay within a broad limit while still representing meaningful change.",
    safety: "Use standard precautions for every patient, high-level disinfect semicritical probes according to approved instructions, store reprocessed probes to prevent recontamination, and never allow a probe cover to substitute for required cleaning and disinfection.",
    redFlags: "Cracked probe housing, failed electrical or leak test, visible soil after cleaning, expired or ineffective disinfectant, missing reprocessing traceability, or a QA failure that can alter diagnosis requires equipment quarantine and escalation.",
    commonErrors: "Common errors include testing with inconsistent settings, deleting failed results, continuing to use a probe because the image still appears plausible, and assuming an intact cover eliminates the need for high-level disinfection.",
    examFocus: "Expect questions about which phantom test detects a described failure, how to respond to out-of-tolerance results, and the correct cleaning or disinfection level for intact skin, mucous-membrane, and sterile-tissue contact.",
    glossary: [
      { term: "Uniformity", definition: "Consistency of image response across the field when scanning a uniform test object." },
      { term: "High-level disinfection", definition: "Reprocessing that destroys all microorganisms except high numbers of bacterial spores and is required for semicritical devices." },
    ],
  },
];
