import type { AlliedAuthoredTopic } from "./types";

const EXAM = "ARDMS OB/GYN | Sonography Canada Generalist";
const C = "Obstetric and Gynecologic Sonography";

export const diagnosticSonographyObGynTopics12: AlliedAuthoredTopic[] = [
  {
    id: "dms-obgyn-pelvic-anatomy", careerType: "diagnosticMedicalSonography", examTag: EXAM, regionScope: "BOTH", category: C,
    topic: "Pelvic Anatomy, Technique, and Menstrual Physiology",
    bottomLine: "Select transabdominal, transvaginal, transperineal, or transrectal technique according to the clinical question and consent, then orient the uterus, endometrium, cervix, ovaries, adnexa, cul-de-sac, bladder, bowel, and pelvic vessels before interpreting pathology.",
    coreConcept: "Uterine and endometrial appearance changes with age, hormones, cycle phase, pregnancy, medication, and surgery. Transabdominal imaging provides overview through a filled bladder, while transvaginal imaging uses proximity and higher frequency for detailed pelvic assessment.",
    recognition: "Normal ovaries contain follicles and move separately from the uterus; the endometrium changes from thin menstrual to trilaminar proliferative and echogenic secretory patterns; uterine version and flexion describe different relationships and must not be confused with mass effect.",
    workflow: "Verify indication and pregnancy status, explain options and obtain informed consent, use a chaperone according to policy and patient preference, complete an overview, orient every plane, measure structures reproducibly, survey adnexa and free fluid, and document limitations or declined components.",
    interpretation: "A measurement is meaningful only in the correct plane and physiologic context. Small pelvic fluid may be physiologic around ovulation, and nonvisualization of a postmenopausal ovary is not automatically abnormal when the adnexa are otherwise clear.",
    safety: "Protect privacy and autonomy during intimate imaging, allow the patient to stop at any time, never imply that internal imaging is mandatory, follow probe-cover and high-level disinfection requirements, and modify the examination for pain or trauma history.",
    redFlags: "Severe pain, heavy bleeding, hemodynamic symptoms, a positive pregnancy test without a confirmed intrauterine pregnancy, marked adnexal tenderness, or a complex mass with free fluid requires prompt escalation.",
    commonErrors: "Common errors are measuring an oblique uterus, mistaking bowel for adnexal pathology, omitting consent, assuming nonvisualization equals absence, using cycle-independent endometrial expectations, and failing to survey both adnexa.",
    examFocus: "Know pelvic orientation, hormonal-cycle changes, age-specific expectations, transducer selection, preparation, consent, infection prevention, and the strengths and limitations of each approach.",
    glossary: [{ term: "Version", definition: "Relationship of the uterine axis to the vaginal axis." }, { term: "Flexion", definition: "Relationship of the uterine body to the cervix." }],
  },
  {
    id: "dms-obgyn-uterus-endometrium", careerType: "diagnosticMedicalSonography", examTag: EXAM, regionScope: "BOTH", category: C,
    topic: "Uterine and Endometrial Pathology",
    bottomLine: "Characterize uterine disease by location within endometrium, myometrium, serosa, or cervix; define number, size, borders, vascularity, cavity distortion, and physiologic context rather than treating every heterogeneous uterus or thick endometrium as the same disease.",
    coreConcept: "Leiomyomas arise from smooth muscle and vary with degeneration; adenomyosis reflects ectopic endometrial tissue within myometrium; polyps and hyperplasia affect the cavity; malignancy risk depends on symptoms, age, hormonal state, morphology, and clinical history.",
    recognition: "Fibroids are commonly well-circumscribed with shadowing and peripheral flow, adenomyosis may show globular asymmetry, fan-shaped shadowing and myometrial cysts, polyps may have a feeding vessel, and endometrial lesions require careful cavity-focused imaging.",
    workflow: "Acquire true sagittal and transverse uterine planes, measure lesions in three dimensions, classify relation to cavity and serosa, measure endometrium correctly without intracavitary fluid, assess junctional features and vascularity, and use saline infusion or other imaging when clinically indicated.",
    interpretation: "Endometrial thickness is not a stand-alone cancer test and thresholds differ by bleeding status and menopausal context. Heterogeneity, focal lesion, vascularity, symptoms, and risk factors can matter more than one number.",
    safety: "Do not proceed with saline infusion when contraindicated, and communicate suspected retained products with hemorrhage, invasive placentation, uterine infection, or a suspicious endometrial or cervical mass promptly.",
    redFlags: "Postmenopausal bleeding with abnormal endometrium, a rapidly changing mass after menopause, marked vascularity with hemorrhage, invasive-appearing lesion, or acute bleeding with instability requires expedited review.",
    commonErrors: "Common errors are including intracavitary fluid in endometrial measurement, calling every shadowing mass a fibroid, overlooking adenomyosis, measuring lesions in oblique planes, and applying premenopausal expectations after menopause.",
    examFocus: "Differentiate leiomyoma locations and degeneration, adenomyosis, polyps, hyperplasia, carcinoma, cervical lesions, retained products, and postoperative changes using morphology and context.",
    glossary: [{ term: "Adenomyosis", definition: "Endometrial glands and stroma within the myometrium with associated muscular change." }, { term: "Submucosal leiomyoma", definition: "Fibroid that projects toward or distorts the endometrial cavity." }],
  },
  {
    id: "dms-obgyn-adnexal-masses", careerType: "diagnosticMedicalSonography", examTag: EXAM, regionScope: "BOTH", category: C,
    topic: "Ovarian and Adnexal Mass Characterization",
    bottomLine: "Determine whether a lesion is ovarian, tubal, uterine, bowel, or extraovarian, then describe size, locularity, wall, septa, solid components, papillary projections, acoustic behavior, vascularity, free fluid, and change over time using a standardized risk framework.",
    coreConcept: "Functional cysts evolve with the cycle, hemorrhage organizes and retracts, endometriomas contain chronic blood, dermoids contain fat and calcified material, and neoplasms range from benign cystic lesions to solid vascular invasive disease.",
    recognition: "A hemorrhagic cyst may show reticular fibrin without internal flow, an endometrioma often has homogeneous low-level echoes, a dermoid may show echogenic lines or shadow, and papillary projections with internal vascularity and ascites increase concern.",
    workflow: "Find the ovary separately if possible, assess mobility and tenderness, scan in orthogonal planes, optimize low-flow Doppler without creating noise, document every risk feature, inspect contralateral adnexa and peritoneal spaces, and compare with prior imaging and menopausal status.",
    interpretation: "Size alone does not determine malignancy, and absent Doppler flow does not prove benignity. Pattern, solid vascular tissue, irregularity, ascites, growth, symptoms, and age must be integrated through the locally adopted reporting system.",
    safety: "Avoid definitive histologic labels when morphology is indeterminate, recognize torsion or rupture superimposed on a mass, and communicate high-risk features through the established urgent pathway.",
    redFlags: "Irregular solid vascular components, papillary projections, ascites, peritoneal nodules, bilateral complex masses, rupture with hemoperitoneum, or acute pain suggesting torsion requires prompt escalation.",
    commonErrors: "Common errors are calling color noise true flow, mistaking clot for a solid nodule without Doppler, failing to prove lesion origin, overcalling a classic hemorrhagic cyst, and ignoring menopausal status.",
    examFocus: "Distinguish functional cyst, hemorrhagic cyst, endometrioma, dermoid, hydrosalpinx, paraovarian cyst, benign neoplasm, and suspicious malignant morphology.",
    glossary: [{ term: "Papillary projection", definition: "Solid tissue protruding from a cyst wall or septum into the cyst cavity." }, { term: "Retracting clot", definition: "Avascular solid-appearing component with concave margins that develops as blood organizes." }],
  },
  {
    id: "dms-obgyn-torsion-emergency", careerType: "diagnosticMedicalSonography", examTag: EXAM, regionScope: "BOTH", category: C,
    topic: "Adnexal Torsion and Acute Pelvic Emergencies",
    bottomLine: "Treat torsion as a time-sensitive clinical-sonographic diagnosis: ovarian enlargement, edema, peripheral follicles, twisted pedicle, abnormal position, free fluid, and altered venous or arterial flow are supportive, but preserved flow does not exclude intermittent or partial torsion.",
    coreConcept: "Twisting first compromises lymphatic and venous drainage, causing edema and enlargement, then may impair arterial inflow and produce ischemia or infarction. Dual ovarian blood supply and intermittent detorsion explain why arterial signals can remain present.",
    recognition: "An enlarged tender ovary, heterogeneous stroma, peripheral follicles, absent or reduced venous flow, high-resistance arterial flow, whirlpool sign, or coexisting mass supports torsion; ruptured cyst, PID, appendicitis, and ectopic pregnancy may overlap clinically.",
    workflow: "Confirm pregnancy status, locate both ovaries, compare size and position, use gentle transvaginal and transabdominal imaging, assess venous and arterial waveforms with sensitive settings, seek a twisted pedicle, evaluate masses and free fluid, and communicate the integrated concern immediately.",
    interpretation: "Normal arterial flow is not a rule-out test. The strongest conclusion combines morphology, asymmetry, tenderness, pedicle appearance, venous findings, risk factors, and symptoms rather than waiting for complete absent perfusion.",
    safety: "Do not prolong scanning to obtain perfect waveforms when the ovary is morphologically suspicious and the patient has acute pain; ovarian salvage depends on timely clinical action.",
    redFlags: "Whirlpool sign, markedly enlarged avascular ovary, hemorrhagic mass with free fluid, hemodynamic instability, pregnancy of unknown location, or severe pain with vomiting requires urgent escalation.",
    commonErrors: "Common errors are excluding torsion because arterial flow is present, comparing only spectral traces without grayscale morphology, using excessive pressure, missing an abnormally positioned ovary, and delaying communication.",
    examFocus: "Understand the sequence of vascular compromise, why flow can persist, and how to distinguish torsion from hemorrhagic cyst, ectopic pregnancy, tubo-ovarian abscess, and other acute pelvic conditions.",
    glossary: [{ term: "Whirlpool sign", definition: "Twisted vascular pedicle seen as concentric or spiraling vessels and tissue." }, { term: "Ovarian edema", definition: "Stromal swelling from impaired lymphatic and venous drainage during torsion." }],
  },
  {
    id: "dms-obgyn-ectopic-pul", careerType: "diagnosticMedicalSonography", examTag: EXAM, regionScope: "BOTH", category: C,
    topic: "Ectopic Pregnancy and Pregnancy of Unknown Location",
    bottomLine: "A positive pregnancy test without a definite intrauterine or extrauterine pregnancy is a pregnancy of unknown location, not automatically ectopic; integrate symptoms, serial quantitative hCG, high-quality transvaginal imaging, adnexal findings, and free fluid while prioritizing maternal stability.",
    coreConcept: "Implantation outside the endometrial cavity most often occurs in the tube and can rupture before a classic mass is visible. hCG trends and discriminatory concepts guide follow-up but do not replace imaging or clinical judgment.",
    recognition: "A definite extrauterine gestational sac with yolk sac or embryo establishes ectopic pregnancy; a tubal ring, complex separate adnexal mass, hematosalpinx, or echogenic hemoperitoneum is suspicious; a pseudosac lacks the features of a true implanted gestational sac.",
    workflow: "Assess vital stability and pain, survey uterus and endometrium, identify both ovaries, examine each adnexa separately, inspect cul-de-sac and upper abdomen for blood when indicated, document whether findings are definite or indeterminate, and activate serial follow-up or urgent care pathways.",
    interpretation: "One hCG value cannot locate a pregnancy, and an empty uterus above a threshold raises concern but is not by itself definitive. A small central fluid collection must not be called an intrauterine pregnancy without appropriate sac features.",
    safety: "Stop routine imaging and escalate immediately for instability, severe pain, syncope, shoulder pain, or large hemoperitoneum. Avoid false reassurance from low hCG, because rupture can occur at varied levels.",
    redFlags: "Extrauterine embryo, significant echogenic free fluid, rapidly worsening pain, peritoneal signs, syncope, hypotension, or a suspicious adnexal mass with no definite intrauterine pregnancy requires urgent management.",
    commonErrors: "Common errors are calling any endometrial fluid a gestational sac, relying on a single hCG, mistaking corpus luteum for ectopic mass, failing to prove a mass is separate from the ovary, and omitting upper-abdominal fluid survey when rupture is suspected.",
    examFocus: "Differentiate definite, probable, and unknown pregnancy location; understand true versus pseudosac features, corpus luteum overlap, hCG limitations, unusual implantation sites, and rupture signs.",
    glossary: [{ term: "Pregnancy of unknown location", definition: "Positive pregnancy test with no definite intrauterine or extrauterine pregnancy seen on ultrasound." }, { term: "Tubal ring", definition: "Echogenic ring-like adnexal structure separate from the ovary that can support tubal ectopic pregnancy." }],
  },
  {
    id: "dms-obgyn-early-pregnancy", careerType: "diagnosticMedicalSonography", examTag: EXAM, regionScope: "BOTH", category: C,
    topic: "First-Trimester Dating, Viability, and Pregnancy Failure",
    bottomLine: "Establish location, number, chorionicity when relevant, dating, cardiac activity, and surrounding anatomy using validated measurement technique and conservative diagnostic criteria; when thresholds are not met, classify uncertainty and arrange follow-up rather than diagnosing failure too early.",
    coreConcept: "Early structures appear in sequence as gestational sac, yolk sac, embryo, and cardiac activity. Crown-rump length is the preferred early dating measure, while mean sac diameter is used before a measurable embryo; growth and visibility depend on true planes and equipment quality.",
    recognition: "A true sac is implanted within endometrium with expected decidual features, the yolk sac confirms an intrauterine gestational sac, and cardiac activity should be documented without unnecessary exposure. Subchorionic hemorrhage lies between chorion and uterine wall.",
    workflow: "Confirm location, image sac and embryo in orthogonal planes, measure mean sac diameter correctly, measure crown-rump length in a neutral midline embryo, assess cardiac activity with M-mode when adequate, inspect cervix and adnexa, and apply validated criteria and follow-up intervals.",
    interpretation: "Borderline measurements and uncertain dates require repeat assessment. A slow heart rate, irregular sac, large yolk sac, or small sac relative to embryo may be concerning but should not be substituted for definitive failure criteria.",
    safety: "Use ALARA, avoid routine pulsed Doppler for early embryonic heart assessment, communicate heavy bleeding or instability, and use neutral language when viability is uncertain.",
    redFlags: "Definitive criteria for failed pregnancy, cervical or cesarean-scar implantation, heterotopic concern, large hemorrhage with symptoms, or substantial free fluid requires prompt clinical review.",
    commonErrors: "Common errors are including the yolk sac in sac measurement, measuring a curved embryo, using Doppler unnecessarily, diagnosing failure from dates alone, and overlooking adnexa after seeing an intrauterine pregnancy in a high-risk patient.",
    examFocus: "Know developmental sequence, correct MSD and CRL technique, conservative viability criteria, multifetal chorionicity clues, subchorionic hemorrhage, and abnormal implantation sites.",
    glossary: [{ term: "Crown-rump length", definition: "Maximum straight-line embryonic or fetal length used for first-trimester dating." }, { term: "Mean sac diameter", definition: "Average of three orthogonal inner gestational-sac measurements." }],
  },
  {
    id: "dms-obgyn-fetal-biometry", careerType: "diagnosticMedicalSonography", examTag: EXAM, regionScope: "BOTH", category: C,
    topic: "Fetal Biometry, Growth, and Amniotic Fluid",
    bottomLine: "Reliable growth assessment depends on standard planes, correct caliper placement, internally consistent dating, serial trend, fluid assessment, and clinical context; a calculated percentile is only as trustworthy as the acquisition and reference used.",
    coreConcept: "Head, abdomen, and femur measurements sample different growth dimensions. Estimated fetal weight combines measurement error from each parameter, and true growth restriction reflects placental or fetal disease rather than simply a fetus below one percentile cutoff.",
    recognition: "A correct head plane shows midline falx and required landmarks without posterior fossa distortion, abdominal circumference is measured at the portal-sinus/stomach plane, and femur length excludes epiphyses. Disproportion and falling growth trajectory matter.",
    workflow: "Verify dating basis, acquire each standard plane independently, measure with specified caliper convention, repeat doubtful values, calculate growth and fluid with the approved method, assess anatomy and placenta, compare serial data, and add Doppler when clinically indicated.",
    interpretation: "One small measurement may reflect plane error, constitution, anomaly, or true growth restriction. Estimated weight has inherent uncertainty; serial interval, Doppler, fluid, maternal disease, and fetal anatomy refine significance.",
    safety: "Do not repeatedly manipulate or prolong the study solely to obtain cosmetically ideal images, and promptly communicate severe growth abnormality, absent fluid, hydrops, or critical Doppler findings.",
    redFlags: "Severe early growth restriction, absent or reversed umbilical arterial end-diastolic flow, oligohydramnios with suspected membrane rupture, hydrops, or major discordance in multifetal pregnancy requires urgent review.",
    commonErrors: "Common errors are using oblique planes, including epiphyses, compressing the abdomen, changing dating from late measurements without indication, overinterpreting a single percentile, and mixing fluid-assessment methods.",
    examFocus: "Recognize standard biometry planes, symmetric versus asymmetric patterns, dating hierarchy, estimated-weight limitations, fluid methods, macrosomia, growth restriction, and serial-growth principles.",
    glossary: [{ term: "Estimated fetal weight", definition: "Model-derived weight estimate calculated from fetal biometric measurements." }, { term: "Maximum vertical pocket", definition: "Deepest qualifying pocket of amniotic fluid measured vertically without fetal parts or cord." }],
  },
  {
    id: "dms-obgyn-fetal-anatomy", careerType: "diagnosticMedicalSonography", examTag: EXAM, regionScope: "BOTH", category: C,
    topic: "Systematic Fetal Anatomic Survey",
    bottomLine: "Perform fetal anatomy as a reproducible head-to-toe survey with standard planes, organ-system checkpoints, placental and cord assessment, and documented limitations; normal growth or one reassuring view never substitutes for completion of required anatomy.",
    coreConcept: "Congenital anomalies arise from disrupted development, genetics, infection, vascular events, or environmental influences and may affect multiple systems. A systematic search reduces satisfaction-of-search error and prompts targeted evaluation of associated findings.",
    recognition: "Standard evaluation includes brain and face, spine, thorax and heart, abdominal wall and organs, kidneys and bladder, limbs, cord insertion and vessels, placenta, cervix, fluid, and fetal activity using planes appropriate to gestational age.",
    workflow: "Confirm lie and orientation, survey globally, acquire each required standard plane, follow an abnormality through orthogonal views, examine associated systems, use color selectively, document completed and incomplete structures, and arrange repeat or specialist assessment when needed.",
    interpretation: "A soft marker is not equivalent to a structural anomaly and its significance depends on isolation, screening history, gestational age, and population risk. Some anomalies evolve and may not be detectable at one examination.",
    safety: "Use respectful neutral communication, avoid speculative bedside diagnosis outside role, maintain ALARA, and escalate major or time-sensitive findings through the local maternal-fetal pathway.",
    redFlags: "Hydrops, major cardiac defect, open neural-tube defect, severe ventriculomegaly, abdominal-wall defect, absent kidneys or bladder filling, lethal skeletal pattern, or severe fluid abnormality requires prompt specialist review.",
    commonErrors: "Common errors are accepting nonstandard planes, mistaking position for deformity, stopping after one anomaly, overcalling soft markers, failing to document incomplete views, and ignoring placenta, cord, cervix, or fluid.",
    examFocus: "Expect anatomy-plane recognition, anomaly associations, normal variants, soft-marker limitations, and the correct next step when required anatomy is incomplete or a major abnormality is detected.",
    glossary: [{ term: "Soft marker", definition: "Minor sonographic feature that may alter aneuploidy risk but is not itself a structural malformation." }, { term: "Hydrops fetalis", definition: "Abnormal fetal fluid accumulation in at least two body compartments." }],
  },
  {
    id: "dms-obgyn-placenta-cervix", careerType: "diagnosticMedicalSonography", examTag: EXAM, regionScope: "BOTH", category: C,
    topic: "Placenta, Cord, Cervix, and Obstetric Hemorrhage",
    bottomLine: "Localize placental edge relative to the internal cervical os with the best technique, assess morphology and cord insertion, evaluate cervix dynamically when indicated, and distinguish previa, abruption, vasa previa, invasive placentation, and benign placental variants.",
    coreConcept: "Placental implantation, migration of the lower segment, trophoblastic invasion, cord-vessel course, cervical competence, and maternal bleeding interact. Some dangerous conditions are primarily clinical and may be sonographically occult.",
    recognition: "Transvaginal imaging safely and accurately defines placental-os distance, color Doppler can identify vessels crossing the os, lacunae and disrupted interfaces may support placenta accreta spectrum, and a short cervix must be measured in a true closed canal without pressure.",
    workflow: "Obtain transabdominal overview, use transvaginal imaging with consent when indicated, empty an overfull bladder, identify internal and external os, measure the shortest reproducible closed cervical length, map placental edge and cord insertion, and use low-flow color for suspected fetal vessels.",
    interpretation: "Abruption can be absent on ultrasound, placental lakes are not synonymous with invasive placentation, and apparent previa may resolve after bladder emptying or later gestation. Diagnosis requires context and sometimes specialist imaging.",
    safety: "Do not perform digital vaginal examination when previa or vasa previa is possible, avoid excessive probe pressure during cervical measurement, and immediately escalate significant bleeding, fetal vessels over the os, or suspected invasive placentation.",
    redFlags: "Vasa previa, placenta covering the os with bleeding, suspected percreta involving bladder, concealed abruption with maternal or fetal compromise, funic presentation, or markedly shortened opening cervix requires urgent review.",
    commonErrors: "Common errors are measuring cervix transabdominally despite poor visualization, overdistending the bladder, confusing placental lakes with lacunae, excluding abruption after a negative scan, and failing to locate cord insertion.",
    examFocus: "Differentiate previa and low-lying placenta, vasa previa, abruption limitations, accreta-spectrum markers, marginal or velamentous insertion, cervical shortening, funneling, and dynamic change.",
    glossary: [{ term: "Vasa previa", definition: "Unprotected fetal vessels traversing membranes over or near the internal cervical os." }, { term: "Placenta accreta spectrum", definition: "Abnormally adherent or invasive placentation caused by deficient decidual interface." }],
  },
  {
    id: "dms-obgyn-maternal-fetal-doppler", careerType: "diagnosticMedicalSonography", examTag: EXAM, regionScope: "BOTH", category: C,
    topic: "Maternal-Fetal Doppler and High-Risk Surveillance",
    bottomLine: "Acquire maternal and fetal Doppler from the correct vessel and sampling site with optimized scale, angle, wall filter, fetal quiescence, and reproducible waveforms; interpret indices by gestational age and clinical indication rather than as isolated numbers.",
    coreConcept: "Placental resistance shapes umbilical arterial flow, fetal cerebral redistribution lowers middle cerebral arterial resistance, venous changes can reflect cardiac compromise, and uterine arterial impedance reflects maternal placental perfusion.",
    recognition: "Absent or reversed umbilical arterial end-diastolic flow indicates severe placental resistance, reduced MCA pulsatility may support brain-sparing or anemia assessment in context, and abnormal ductus venosus a-wave can signal advanced compromise.",
    workflow: "Confirm indication and gestational age, identify the vessel anatomically and with color, sample the protocol-specified segment, minimize angle where required, record several uniform waveforms without fetal breathing or motion, trace correctly, and compare with validated reference ranges.",
    interpretation: "Different sampling sites produce different normal values. An isolated abnormal index should be confirmed technically and integrated with growth, fluid, biophysical assessment, maternal disease, and the surveillance protocol.",
    safety: "Use the shortest necessary spectral dwell time and appropriate output, especially early in gestation, and communicate critical waveforms immediately rather than waiting to finish a routine image list.",
    redFlags: "Reversed umbilical arterial flow, abnormal ductus venosus in a compromised fetus, severe fetal bradycardia, hydrops, or Doppler findings indicating major anemia or placental failure requires urgent escalation.",
    commonErrors: "Common errors are sampling the wrong vessel, using mismatched reference ranges, tracing noisy envelopes, applying excessive wall filter, interpreting motion artifact, and treating one Doppler index as the entire fetal assessment.",
    examFocus: "Know vessel identification, sampling sites, resistance and pulsatility indices, placental resistance, redistribution, anemia surveillance, venous deterioration, and ALARA application.",
    glossary: [{ term: "Pulsatility index", definition: "Doppler resistance measure calculated from peak systolic, end-diastolic, and mean velocities." }, { term: "Brain-sparing", definition: "Reduced cerebral vascular resistance during fetal hypoxemic stress, often reflected by lower MCA pulsatility." }],
  },
];
