import type { AlliedAuthoredTopic } from "./types";

const EXAM = "ARDMS RDCS | Sonography Canada Cardiac";
const C = "Cardiac Sonography";

export const diagnosticSonographyCardiacGapTopics16: AlliedAuthoredTopic[] = [
  {
    id: "dms-cardiac-ischemia", careerType: "diagnosticMedicalSonography", examTag: EXAM, regionScope: "BOTH", category: C, topic: "Coronary Territories, Ischemia, and Regional Wall Motion",
    bottomLine: "Assess regional function from nonforeshortened standard views, compare endocardial excursion and myocardial thickening across segments, map abnormalities to more than one view and integrate coronary territory, loading conditions, conduction, prior infarction and clinical timing.",
    coreConcept: "Reduced coronary perfusion first impairs relaxation and systolic thickening, with prolonged ischemia causing infarction, remodeling and mechanical complications. Coronary territories overlap and collateral supply prevents a rigid one-segment-one-artery interpretation.",
    recognition: "Hypokinesis, akinesis, dyskinesis, wall thinning, aneurysm and scar patterns must be distinguished from translational motion, tethering and poor border definition; acute infarction can produce papillary rupture, septal defect, free-wall rupture or RV involvement.",
    workflow: "Acquire complete parasternal and apical views without foreshortening, optimize frame rate and borders, assess each segment in two orthogonal views, compare thickening rather than motion alone, review ECG and prior studies and use contrast when indicated and authorized.",
    interpretation: "Septal motion can be abnormal with bundle-branch block, pacing, surgery or RV pressure overload without coronary ischemia. A technically unseen segment is not normal and must be reported as limited.",
    safety: "Recognize active chest pain, malignant rhythm and hemodynamic deterioration during imaging; stop routine acquisition and communicate suspected acute mechanical complication or new severe regional dysfunction immediately.",
    redFlags: "New septal defect, acute severe mitral regurgitation, pericardial blood with tamponade, contained rupture, large new regional abnormality or RV infarction with instability requires urgent escalation.",
    commonErrors: "Common errors are accepting a foreshortened apex, judging translation instead of thickening, assigning coronary territory from one segment, missing RV involvement and calling poorly seen myocardium normal.",
    examFocus: "Know segment models, coronary distributions and overlap, definitions of regional motion, infarction complications, aneurysm versus pseudoaneurysm and nonischemic causes of abnormal septal motion.",
    glossary: [{ term: "Dyskinesis", definition: "Paradoxical outward myocardial motion during systole." }, { term: "Tethering", definition: "Apparent movement of a dysfunctional segment caused by adjacent contracting myocardium." }],
  },
  {
    id: "dms-cardiac-cardiomyopathy", careerType: "diagnosticMedicalSonography", examTag: EXAM, regionScope: "BOTH", category: C, topic: "Cardiomyopathies and Ventricular Remodeling",
    bottomLine: "Differentiate dilated, hypertrophic, restrictive, infiltrative, arrhythmogenic and stress-related cardiomyopathy by chamber geometry, wall thickness, systolic and diastolic function, obstruction, strain patterns, right-heart involvement and family or clinical context.",
    coreConcept: "Myocyte disease, fibrosis, infiltration, disarray or loading stress remodels ventricles differently. Hypertrophy can obstruct outflow dynamically, dilation reduces contractile efficiency and restrictive physiology raises filling pressure despite preserved early ejection fraction.",
    recognition: "Dilated cardiomyopathy produces chamber enlargement and global dysfunction; hypertrophic disease may show asymmetric thickening and systolic anterior motion; amyloid-type infiltration may show increased thickness, atrial enlargement, restrictive filling and characteristic strain distribution.",
    workflow: "Measure chambers and walls in validated planes, assess global and regional function, LVOT gradient at rest and provocation when appropriate, valve interaction, diastolic indices, atria, RV, pericardium and strain, then compare prior studies and report confounders.",
    interpretation: "Increased wall thickness can reflect hypertension, athletic adaptation, storage or infiltration rather than sarcomeric hypertrophic cardiomyopathy. Preserved EF does not mean preserved myocardial function.",
    safety: "Do not perform unsafe provocation in unstable patients, recognize obstructive physiology or arrhythmia and promptly communicate new severe dysfunction, intracardiac thrombus or high-risk obstructive findings.",
    redFlags: "Severe dynamic obstruction with symptoms, apical aneurysm, ventricular thrombus, new biventricular failure, marked strain abnormality with infiltrative signs or arrhythmogenic RV disease requires urgent specialist review.",
    commonErrors: "Common errors are measuring obliquely, labeling hypertrophy from one segment, using EF alone, ignoring blood pressure and loading conditions, and missing RV or atrial involvement.",
    examFocus: "Differentiate major cardiomyopathy phenotypes, dynamic obstruction, systolic anterior motion, infiltrative clues, strain patterns, athlete's heart, hypertensive remodeling and stress cardiomyopathy.",
    glossary: [{ term: "Systolic anterior motion", definition: "Anterior displacement of mitral tissue toward the LV outflow tract during systole." }, { term: "Global longitudinal strain", definition: "Percentage shortening of myocardium along the ventricular long axis, used to detect subtle dysfunction." }],
  },
  {
    id: "dms-cardiac-valves", careerType: "diagnosticMedicalSonography", examTag: EXAM, regionScope: "BOTH", category: C, topic: "Mitral Stenosis, Aortic Regurgitation, and Right-Sided Valves",
    bottomLine: "Define valve morphology and mechanism, then grade severity with an integrated set of Doppler, quantitative, chamber-response and hemodynamic findings; never use one jet area, gradient or calculated valve area without checking rhythm, flow and measurement quality.",
    coreConcept: "Stenosis creates a pressure gradient dependent on orifice area and flow, while regurgitation creates volume load influenced by driving pressure and compliance. Chronic disease remodels chambers; acute disease can be severe before enlargement occurs.",
    recognition: "Rheumatic mitral stenosis produces commissural fusion and doming; severe aortic regurgitation may show a dense decelerating CW signal and flow reversal; significant tricuspid regurgitation affects hepatic venous flow and right-heart size; pulmonic disease alters RV load.",
    workflow: "Acquire morphology in multiple views, align CW Doppler from the best window, measure gradients at documented heart rate, use validated area or regurgitation methods, assess pulmonary and venous responses, chambers and pressure and reconcile discordant parameters.",
    interpretation: "Tachycardia and high flow raise mitral gradients, pressure half-time is altered by compliance, eccentric regurgitant jets can look small and severe acute regurgitation may lack chronic chamber enlargement.",
    safety: "Communicate newly severe valve disease with pulmonary edema, RV failure, suspected endocarditis or hemodynamic compromise rather than delaying for exhaustive low-value measurements.",
    redFlags: "Acute severe aortic or mitral regurgitation, critical mitral stenosis in pregnancy, severe TR with RV failure, obstructed pulmonic flow or valve destruction with instability requires urgent escalation.",
    commonErrors: "Common errors are grading by color area alone, ignoring heart rate and flow, tracing incomplete envelopes, applying native thresholds to prostheses and forcing concordance when data quality is poor.",
    examFocus: "Know mechanisms and integrated severity for mitral stenosis, aortic regurgitation, tricuspid and pulmonic disease, acute versus chronic response and common Doppler limitations.",
    glossary: [{ term: "Pressure half-time", definition: "Time for a transmitral or regurgitant pressure gradient to fall by half, influenced by valve and chamber compliance." }, { term: "Holodiastolic flow reversal", definition: "Reverse arterial flow throughout diastole, supporting significant aortic regurgitation when properly sampled." }],
  },
  {
    id: "dms-cardiac-masses-infection", careerType: "diagnosticMedicalSonography", examTag: EXAM, regionScope: "BOTH", category: C, topic: "Endocarditis, Intracardiac Masses, and Thrombus",
    bottomLine: "Characterize an intracardiac structure by attachment, location, mobility, texture, vascularity, hemodynamic effect and clinical context; distinguish normal variants and artifact from thrombus, vegetation and tumor through multiplanar imaging and escalation to TEE or other modalities when needed.",
    coreConcept: "Thrombus forms in low-flow or injured regions, vegetation attaches to infected endocardial surfaces and tumors arise from characteristic locations. Embolic risk relates to mobility, friability and clinical context, not size alone.",
    recognition: "LV apical thrombus occurs with akinetic segments, left-atrial appendage thrombus with stasis, vegetation is an independently mobile valve-associated mass and myxoma often attaches near the interatrial septum; reverberation and trabeculation are common mimics.",
    workflow: "Optimize multiple views and settings, prove the finding in more than one plane, define attachment and motion, use contrast when authorized for border or thrombus clarification, assess valve destruction and embolic consequences, compare prior studies and recommend appropriate escalation.",
    interpretation: "A negative transthoracic study does not exclude endocarditis when suspicion is high, and a mobile valve strand is not automatically vegetation. Clinical cultures, devices, surgery and pretest probability determine meaning.",
    safety: "Use infection and line precautions, recognize unstable valve destruction or obstructive mass and promptly communicate a highly mobile embolic lesion, abscess, fistula or device infection.",
    redFlags: "Valve perforation, root abscess, new severe regurgitation, prosthetic dehiscence, obstructive atrial mass, large mobile thrombus or infected device with hemodynamic compromise requires urgent review.",
    commonErrors: "Common errors are diagnosing vegetation from any mobile echo, missing the apex, confusing pectinate muscle or moderator band with mass, relying on one view and ignoring a high-risk negative-study limitation.",
    examFocus: "Differentiate thrombus, vegetation, myxoma, metastasis, normal variants and artifact; understand endocarditis complications, device infections, embolic risk and TTE versus TEE roles.",
    glossary: [{ term: "Vegetation", definition: "Infected mass of platelets, fibrin and microorganisms attached to endocardial tissue or a device." }, { term: "Spontaneous echo contrast", definition: "Smoke-like swirling echoes caused by red-cell aggregation in low-flow blood, associated with thrombotic risk." }],
  },
  {
    id: "dms-cardiac-congenital", careerType: "diagnosticMedicalSonography", examTag: EXAM, regionScope: "BOTH", category: C, topic: "Adult Congenital Shunts and Structural Connections",
    bottomLine: "Approach congenital disease by sequential segmental anatomy—systemic and pulmonary venous return, atrial arrangement, atrioventricular connections, ventriculoarterial connections, outflow and great arteries—before measuring a shunt or naming a defect.",
    coreConcept: "Pressure and resistance determine shunt direction and chamber volume load. ASD typically enlarges right heart, VSD loads pulmonary circulation and left heart depending on size and resistance and patent ductus links descending aorta to pulmonary artery.",
    recognition: "Color dropout alone is not a defect; true shunts require anatomic discontinuity and flow pattern. Right-heart dilation with septal flattening may support significant atrial-level shunt, while high-velocity restrictive VSD differs from a large low-gradient defect with pulmonary hypertension.",
    workflow: "Establish situs and connections, image septa in multiple planes, optimize low-velocity color scale, record spectral direction and velocity, assess chamber response and pulmonary pressure, calculate shunt information only from valid measurements and use agitated saline under protocol when indicated.",
    interpretation: "A high VSD velocity can indicate a small restrictive defect rather than severe hemodynamic burden, and an ASD may be missed by color if alignment is poor. Eisenmenger physiology reverses expected direction as pulmonary resistance rises.",
    safety: "Follow injection and embolic precautions for saline contrast, recognize cyanosis or severe pulmonary hypertension and communicate newly identified major connections or shunt reversal promptly.",
    redFlags: "Right-to-left shunt with hypoxemia, severe pulmonary hypertension, obstructed anomalous venous return, ruptured sinus of Valsalva, acute device complication or congenital lesion with heart failure requires urgent specialist review.",
    commonErrors: "Common errors are calling apical dropout an ASD, naming anatomy before tracing connections, calculating Qp/Qs from poor diameters, ignoring chamber response and mistaking restrictive high velocity for a large defect.",
    examFocus: "Know ASD, VSD, PDA, anomalous venous return, coarctation, bicuspid aortic valve, repaired congenital anatomy, shunt direction and sequential segmental analysis.",
    glossary: [{ term: "Qp/Qs", definition: "Ratio of pulmonary to systemic blood flow used to estimate net shunt magnitude when measurements are valid." }, { term: "Eisenmenger physiology", definition: "Reversal of a longstanding left-to-right shunt after severe pulmonary vascular resistance develops." }],
  },
  {
    id: "dms-cardiac-advanced-procedures", careerType: "diagnosticMedicalSonography", examTag: EXAM, regionScope: "BOTH", category: C, topic: "Stress Echo, Ultrasound Enhancement, and TEE Safety",
    bottomLine: "Advanced echocardiography requires protocol discipline: establish diagnostic baseline images, screen contraindications, acquire matched views rapidly at target stress, administer enhancement agents only within authorization and monitor continuously, and treat TEE as an invasive procedure with airway and esophageal risk.",
    coreConcept: "Stress increases myocardial demand and can reveal inducible dysfunction, enhancement agents improve endocardial or Doppler signals through intravascular microbubbles and TEE places a high-frequency probe close to posterior cardiac structures at the cost of procedural risk.",
    recognition: "New or worsening regional dysfunction under stress supports ischemia, failure to reach adequate workload reduces sensitivity, microbubble opacification improves border definition and TEE excels for atrial appendage, prosthetic valve, aorta and endocarditis assessment.",
    workflow: "Verify order, consent and contraindications, obtain baseline vitals/ECG and matched views, prepare emergency equipment, follow exercise or pharmacologic protocol, capture peak images, monitor recovery, follow agent handling requirements and complete TEE timeout, sedation and reprocessing workflows.",
    interpretation: "A technically limited or submaximal stress study is not definitively negative, conduction and loading changes can mimic ischemia and enhancement artifacts must be corrected by mechanical-index and gain adjustments.",
    safety: "Stop for serious symptoms, ischemic ECG change, malignant arrhythmia, hypotension or severe hypertension; for TEE protect airway, verify fasting and esophageal history and do not advance against resistance.",
    redFlags: "Sustained ventricular arrhythmia, acute coronary syndrome, severe hypotension, bronchospasm or reaction, esophageal bleeding, perforation concern or airway compromise requires immediate emergency response.",
    commonErrors: "Common errors are mismatching stress views, delaying peak acquisition, calling a submaximal test normal, overdestroying contrast bubbles, skipping contraindication screening and treating TEE probe cleaning as routine low-level disinfection.",
    examFocus: "Know stress endpoints and artifacts, exercise versus pharmacologic effects, enhancement optimization and reactions, TEE indications, contraindications, sedation monitoring and high-level disinfection.",
    glossary: [{ term: "Inducible ischemia", definition: "New or worsening regional myocardial dysfunction during stress caused by inadequate coronary flow reserve." }, { term: "Ultrasound enhancement agent", definition: "Intravascular microbubble agent used to improve blood-pool and endocardial visualization." }],
  },
];
