import type { AlliedAuthoredTopic } from "./types";

export const alliedTopics06: AlliedAuthoredTopic[] = [
  {
    id: "rrt-ventilator-waveforms-dyssynchrony",
    careerType: "rrt",
    examTag: "NBRC TMC/CSE",
    regionScope: "US",
    category: "Mechanical Ventilation",
    topic: "Ventilator Waveforms and Patient-Ventilator Dyssynchrony",
    bottomLine: "Read pressure, flow, and volume waveforms together to identify the mechanism of dyssynchrony before changing ventilator settings or sedation.",
    coreConcept: "Trigger, flow, cycle, and PEEP problems create recognizable waveform patterns; correcting the mechanical mismatch is often safer than reflexively deepening sedation.",
    recognition: "Missed efforts, double triggering, flow starvation, ineffective triggering, breath stacking, expiratory flow that fails to return to baseline, and abrupt pressure changes are the key bedside patterns.",
    workflow: "Confirm the airway and circuit, identify whether the problem is trigger, inspiratory flow, cycling, obstruction, or intrinsic PEEP, correlate with patient effort, make one targeted change, and reassess the waveform response.",
    interpretation: "A scooped pressure contour can reflect flow starvation, stacked breaths can indicate delayed cycling or high drive, and expiratory flow remaining above baseline before the next breath supports gas trapping.",
    safety: "Do not silence alarms or suppress respiratory drive before ruling out tube obstruction, pneumothorax, severe bronchospasm, auto-PEEP, pain, or an inappropriate ventilator setting.",
    redFlags: "Sudden loss of delivered volume, rapidly rising pressure, severe breath stacking, new hypotension, unilateral breath sounds, or refractory desaturation requires immediate bedside evaluation.",
    commonErrors: "Treating every abnormal waveform with sedation, changing multiple settings simultaneously, and interpreting graphics without checking the patient, circuit, and airway first.",
    examFocus: "NBRC scenarios reward identifying the waveform mechanism and the single ventilator adjustment most likely to correct it.",
    glossary: [
      { term: "Double triggering", definition: "Two ventilator breaths delivered for one prolonged patient inspiratory effort, potentially causing breath stacking." },
      { term: "Flow starvation", definition: "Inspiratory flow that is insufficient for patient demand, producing distress and characteristic pressure waveform distortion." },
    ],
  },
  {
    id: "rrt-inhaled-pulmonary-vasodilators",
    careerType: "rrt",
    examTag: "NBRC TMC/CSE",
    regionScope: "US",
    category: "Advanced Respiratory Support",
    topic: "Inhaled Pulmonary Vasodilators and Refractory Hypoxemia",
    bottomLine: "Use inhaled pulmonary vasodilators as targeted rescue therapy when appropriate, evaluate response promptly, and never let a transient oxygenation improvement delay definitive treatment of the underlying cause.",
    coreConcept: "Selective pulmonary vasodilation in ventilated lung units can improve ventilation-perfusion matching and reduce right-ventricular afterload without the same degree of systemic vasodilation as intravenous therapy.",
    recognition: "Severe pulmonary hypertension, acute right-ventricular strain, or refractory hypoxemia despite optimized conventional support can prompt consideration of an inhaled vasodilator strategy.",
    workflow: "Confirm the indication, optimize oxygenation and ventilation first, establish a baseline for oxygenation and hemodynamics, start the ordered agent with correct delivery equipment, monitor response, and plan gradual weaning when appropriate.",
    interpretation: "A meaningful response is a reproducible improvement in oxygenation or pulmonary hemodynamics without unacceptable systemic effects; lack of benefit should trigger reassessment rather than indefinite continuation.",
    safety: "Abrupt withdrawal can worsen pulmonary pressures or oxygenation; monitor delivery-system function, methemoglobin risk where relevant, platelet effects, and rebound physiology during weaning.",
    redFlags: "Sudden desaturation during therapy, suspected delivery failure, worsening right-heart failure, severe hypotension, or rebound pulmonary hypertension requires immediate escalation.",
    commonErrors: "Starting rescue therapy before correcting airway or ventilator problems, assuming better saturation equals improved survival, and discontinuing abruptly without a weaning plan.",
    examFocus: "Know the physiologic purpose, monitoring priorities, and complications rather than memorizing a single dose.",
    glossary: [
      { term: "Selective pulmonary vasodilation", definition: "Preferential reduction of pulmonary vascular tone in ventilated regions of the lung." },
      { term: "Rebound pulmonary hypertension", definition: "Acute rise in pulmonary vascular resistance after rapid withdrawal of pulmonary vasodilator support." },
    ],
  },
  {
    id: "paramedic-obstetric-emergencies",
    careerType: "paramedic",
    examTag: "NREMT Paramedic",
    regionScope: "US",
    category: "Obstetrics and Neonatal Care",
    topic: "Prehospital Obstetric Emergencies and Imminent Birth",
    bottomLine: "In obstetric emergencies, stabilize maternal ABCs first, identify time-critical complications, prepare for delivery only when birth is imminent, and anticipate neonatal support before the infant arrives.",
    coreConcept: "Maternal perfusion and oxygenation directly affect fetal status; many prehospital obstetric decisions are about recognizing when transport remains safest versus when birth or a life-threatening complication makes immediate field intervention necessary.",
    recognition: "Crowining, involuntary pushing, very frequent contractions, visible presenting part, severe vaginal bleeding, seizures, prolapsed cord, or shoulder dystocia are major decision-changing cues.",
    workflow: "Assess maternal stability, pregnancy stage and chief complication, position appropriately, establish transport priority, prepare delivery and neonatal equipment if birth is imminent, support controlled delivery, then reassess mother and newborn continuously.",
    interpretation: "Bleeding with shock, seizure with pregnancy-related hypertension, prolapsed cord, or failure of the shoulders to deliver after the head are emergencies requiring specific supportive maneuvers and rapid obstetric destination planning.",
    safety: "Do not pull on the infant, cord, or placenta; avoid unnecessary vaginal examinations; protect maternal privacy and warmth while maintaining access for resuscitation.",
    redFlags: "Massive hemorrhage, maternal seizure, shock, prolapsed cord, breech presentation with entrapment, shoulder dystocia, or neonatal apnea/bradycardia requires immediate escalation and coordinated resuscitation.",
    commonErrors: "Delaying transport for a routine delivery setup, traction on the head during shoulder dystocia, and focusing on the fetus while maternal perfusion is deteriorating.",
    examFocus: "NREMT cases often test whether birth is truly imminent and whether the first priority is maternal resuscitation, transport, or a specific delivery maneuver.",
    glossary: [
      { term: "Crowning", definition: "Persistent visibility of the fetal presenting part at the vaginal opening, indicating imminent birth." },
      { term: "Shoulder dystocia", definition: "Failure of the shoulders to deliver after the fetal head, requiring prompt obstetric maneuvers without traction on the head." },
    ],
  },
  {
    id: "paramedic-hazmat-decontamination",
    careerType: "paramedic",
    examTag: "NREMT Paramedic",
    regionScope: "US",
    category: "Operations",
    topic: "Hazardous Materials Recognition and Decontamination",
    bottomLine: "Do not become the next patient: recognize the hot zone, use the incident command system, select appropriate PPE, and perform decontamination before routine treatment when contamination threatens rescuers or receiving facilities.",
    coreConcept: "Hazardous-materials incidents require controlling exposure pathways and scene contamination before ordinary patient-care priorities can be performed safely.",
    recognition: "Placards, multiple patients with similar unexplained symptoms, unusual odors or vapor clouds, leaking containers, industrial locations, and responder symptoms are major clues.",
    workflow: "Stage uphill/upwind when possible, establish command and zones, identify the substance from a safe position, request specialty resources, remove the patient from exposure when trained and equipped, decontaminate, then continue medical care in the clean zone.",
    interpretation: "Symptoms alone rarely identify a chemical reliably; scene information, exposure route, toxidrome pattern, and specialist resources should guide the response.",
    safety: "Never enter a contaminated zone in routine EMS PPE when the hazard requires higher protection, and prevent contaminated patients or equipment from entering ambulances or emergency departments before decontamination.",
    redFlags: "Responder symptoms, expanding vapor cloud, oxygen-deficient atmosphere, secondary device, unknown liquid contamination, or rapidly deteriorating multiple casualties requires withdrawal and specialized hazmat support.",
    commonErrors: "Rushing into the hot zone, relying on odor, performing wet decontamination when dry removal would suffice, and transporting a contaminated patient without protecting the crew and hospital.",
    examFocus: "The safest answer often begins with scene control and responder protection before direct patient contact.",
    glossary: [
      { term: "Hot zone", definition: "Area of active contamination or highest hazard where entry requires specialized controls and PPE." },
      { term: "Decontamination corridor", definition: "Controlled transition area used to reduce or remove contamination before movement into the clean zone." },
    ],
  },
  {
    id: "mlt-antibody-identification-panels",
    careerType: "mlt",
    examTag: "ASCP MLT",
    regionScope: "US",
    category: "Immunohematology",
    topic: "Red Cell Antibody Identification Panels",
    bottomLine: "Interpret antibody panels systematically by phase, reaction strength, rule-outs, antigen profile, autocontrol, and patient history before assigning specificity.",
    coreConcept: "Clinically significant alloantibodies show characteristic reactivity patterns tied to antigen expression and testing phase, but multiple antibodies, dosage, and autoantibodies can distort simple pattern matching.",
    recognition: "A positive screen followed by selective panel reactivity, phase-dependent strength, dosage effects, and compatible rule-outs are the key pattern elements.",
    workflow: "Review the antibody screen and history, inspect the panel pattern by phase, rule out antibodies only with appropriately antigen-negative cells, evaluate dosage, check autocontrol and DAT when indicated, phenotype or genotype the patient as appropriate, and select antigen-negative crossmatch-compatible units.",
    interpretation: "A negative autocontrol supports alloantibody more than autoantibody, while broad reactivity with a positive autocontrol raises concern for an autoantibody or other nonspecific interference.",
    safety: "Do not issue incompatible blood merely because an antibody appears weak; clinically significant historical antibodies remain relevant even when currently undetectable.",
    redFlags: "Unexplained panreactivity, recent transfusion complicating phenotype, discrepant historical antibodies, incompatible crossmatches, or suspected hemolytic transfusion reaction requires senior blood-bank review.",
    commonErrors: "Ruling out an antibody with a heterozygous cell when dosage matters, ignoring historical antibodies, and naming specificity from one positive cell without pattern confirmation.",
    examFocus: "ASCP questions emphasize disciplined rule-out logic, dosage, autocontrol interpretation, and safe unit selection.",
    glossary: [
      { term: "Dosage", definition: "Stronger antibody reactivity against cells homozygous for an antigen than against heterozygous cells." },
      { term: "Autocontrol", definition: "Testing patient plasma against the patient's own red cells to help distinguish allo- from auto-reactivity." },
    ],
  },
  {
    id: "mlt-method-validation-delta-checks",
    careerType: "mlt",
    examTag: "ASCP MLT",
    regionScope: "US",
    category: "Laboratory Operations",
    topic: "Method Verification, Validation, and Delta Checks",
    bottomLine: "A laboratory result is trustworthy only when the method is fit for purpose and the individual patient result passes analytic and plausibility checks before release.",
    coreConcept: "Verification confirms that an established method performs as claimed in the local laboratory, while validation is broader and is required for modified or laboratory-developed procedures; delta checks detect unexpected change within one patient over time.",
    recognition: "Precision, accuracy or bias, reportable range, reference interval verification, analytical sensitivity, carryover, and clinically implausible patient-to-patient changes are common validation and release checkpoints.",
    workflow: "Define intended use, establish acceptance criteria before testing, collect appropriate comparison and precision data, document findings, obtain approval, implement QC, and monitor post-implementation performance; for delta flags, verify identity, specimen quality, and clinical plausibility before release.",
    interpretation: "A statistically different result is not automatically clinically unacceptable; acceptance should be tied to predefined analytical and clinical performance goals.",
    safety: "Never override a failed validation characteristic or delta flag without investigation and documentation; patient misidentification and specimen mix-ups can present as dramatic deltas.",
    redFlags: "Systematic bias near a medical decision point, unexplained carryover, recurrent calibration drift, impossible physiologic deltas, or QC failure invalidates routine reporting until resolved.",
    commonErrors: "Choosing acceptance limits after seeing the data, treating correlation alone as proof of agreement, and assuming a delta flag means the analyzer is wrong rather than checking patient/specimen identity.",
    examFocus: "Differentiate precision from accuracy, verification from validation, and analytic error from preanalytic/specimen-identity problems.",
    glossary: [
      { term: "Verification", definition: "Local confirmation that an established test system meets specified performance claims for its intended use." },
      { term: "Delta check", definition: "Comparison of a patient's current result with prior results to detect an unexpected change that may indicate error or a major clinical event." },
    ],
  },
  {
    id: "pharmacy-sterile-compounding-workflow",
    careerType: "pharmacyTech",
    examTag: "PTCB CPHT",
    regionScope: "US",
    category: "Compounding",
    topic: "Sterile Compounding Workflow and Aseptic Technique",
    bottomLine: "Sterile compounding safety depends on controlled environments, disciplined hand hygiene and garbing, first-air protection, accurate calculations, and immediate correction of any break in aseptic technique.",
    coreConcept: "Microbial contamination risk rises when critical sites are touched, blocked from first air, or exposed to contaminated surfaces; technique and environment work together rather than substituting for one another.",
    recognition: "Blocked airflow, touch contamination of needle hubs or vial stoppers after disinfection, poor garbing sequence, cluttered primary engineering controls, and unverified calculations are common failure points.",
    workflow: "Perform required cleaning and hand hygiene, garb in the correct sequence, disinfect components, organize supplies to preserve first air, perform calculations and independent checks, compound with aseptic manipulations, inspect the final preparation, label, document, and store appropriately.",
    interpretation: "A visually clear product can still be contaminated; sterility cannot be inferred from appearance, so process integrity is the primary defense.",
    safety: "Discard or restart when a critical-site contamination event cannot be reliably corrected, and escalate equipment or environmental excursions rather than compounding through them.",
    redFlags: "Loss of environmental control, visible particulates, calculation discrepancy, damaged container closure, uncertain sterility, or incorrect beyond-use information requires the preparation to be held.",
    commonErrors: "Reaching over critical sites, assuming gloves are sterile indefinitely, skipping friction and drying during disinfection, and prioritizing speed over process integrity.",
    examFocus: "PTCB items commonly test first-air protection, critical sites, workflow sequencing, calculations, and what to do after a contamination event.",
    glossary: [
      { term: "First air", definition: "Unidirectional HEPA-filtered air reaching a critical site without obstruction or prior contact with a potential contaminant." },
      { term: "Critical site", definition: "Location on a sterile component that must remain sterile to protect the compounded preparation from contamination." },
    ],
  },
  {
    id: "pharmacy-controlled-substance-diversion",
    careerType: "pharmacyTech",
    examTag: "PTCB CPHT",
    regionScope: "US",
    category: "Medication Safety and Operations",
    topic: "Controlled Substance Inventory and Diversion Prevention",
    bottomLine: "Controlled-substance handling requires exact chain-of-custody practices, discrepancy reconciliation, secure storage, and prompt escalation of suspected diversion.",
    coreConcept: "Diversion prevention is a systems problem: access control, documentation, physical security, inventory reconciliation, and separation of duties create overlapping safeguards.",
    recognition: "Unexplained count discrepancies, repeated waste anomalies, unusual access patterns, altered records, excessive overrides, or inventory movement that does not match dispensing activity are warning signs.",
    workflow: "Follow authorized receiving and storage procedures, document every movement, perform required counts, reconcile discrepancies immediately, preserve records and evidence, and notify the pharmacist or designated compliance pathway according to policy.",
    interpretation: "A discrepancy is not proof of diversion, but it is never something to normalize or postpone; process errors, documentation errors, and intentional diversion must be distinguished through timely investigation.",
    safety: "Do not independently confront a suspected diverter or alter records to make counts match; preserve the audit trail and follow the escalation process.",
    redFlags: "Repeated unresolved discrepancies, evidence of tampering, missing controlled stock, forged documentation, or suspicious access outside assigned duties requires immediate escalation.",
    commonErrors: "Back-dating corrections, sharing credentials, leaving controlled stock unsecured, and treating small discrepancies as too minor to investigate.",
    examFocus: "Focus on documentation integrity, security, discrepancy response, and technician scope rather than memorizing enforcement trivia.",
    glossary: [
      { term: "Diversion", definition: "Unauthorized redirection of a controlled medication from legitimate handling or patient care." },
      { term: "Chain of custody", definition: "Documented control and accountability for a medication or item as it moves between authorized handlers." },
    ],
  },
  {
    id: "imaging-ct-contrast-reaction-extravasation",
    careerType: "imaging",
    examTag: "ARRT Radiography",
    regionScope: "US",
    category: "Patient Care",
    topic: "Iodinated Contrast Reactions and Extravasation",
    bottomLine: "Before contrast administration, verify the indication and patient risks; during and after injection, distinguish physiologic effects, allergic-like reactions, and extravasation so the response matches the actual problem.",
    coreConcept: "Contrast complications differ in mechanism and urgency: allergic-like reactions require severity-based emergency response, while extravasation requires immediate injection stop, limb assessment, and escalation based on tissue risk.",
    recognition: "Urticaria, airway symptoms, hypotension, vomiting, vasovagal signs, local pain, swelling, tightness, or resistance at the injection site are important cues.",
    workflow: "Complete screening, verify access and injection plan, observe the patient, stop injection for suspected extravasation or serious reaction, assess ABCs or the affected limb, summon appropriate help, document the event, and provide follow-up instructions.",
    interpretation: "A warm sensation or metallic taste can be transient physiologic effects, whereas bronchospasm, facial edema, hypotension, or progressive limb neurovascular compromise requires escalation.",
    safety: "Never restart a failed high-pressure injection through a questionable line and never dismiss increasing pain or tense swelling as routine contrast discomfort.",
    redFlags: "Stridor, hypoxia, severe bronchospasm, shock, altered mental status, rapidly expanding swelling, blistering, severe pain, or distal neurovascular change requires urgent response.",
    commonErrors: "Calling every symptom an allergy, delaying emergency activation while finishing the scan, and under-documenting extravasation severity and follow-up.",
    examFocus: "ARRT questions usually test reaction recognition, first action, and safe post-event management rather than rare pharmacology details.",
    glossary: [
      { term: "Extravasation", definition: "Unintended leakage of injected contrast from the vessel into surrounding tissue." },
      { term: "Allergic-like reaction", definition: "Contrast reaction with features resembling hypersensitivity, such as urticaria, bronchospasm, or anaphylaxis." },
    ],
  },
  {
    id: "imaging-mri-screening-implants",
    careerType: "imaging",
    examTag: "ARRT Radiography",
    regionScope: "US",
    category: "Safety",
    topic: "MRI Safety Screening and Implant Verification",
    bottomLine: "MRI safety depends on rigorous screening and device-specific verification before a patient or object enters the controlled magnet environment.",
    coreConcept: "The static magnetic field is always present; projectile risk, device displacement, heating, induced currents, and device malfunction can occur even when no imaging sequence is actively running.",
    recognition: "Unknown implants, prior surgery, metal fragments, implanted pumps or stimulators, abandoned leads, oxygen cylinders, tools, and ferromagnetic accessories are major hazards.",
    workflow: "Use a standardized screening process, verify device make/model and conditions when an implant is present, remove prohibited objects, ensure MR-compatible monitoring and emergency equipment, confirm zone access controls, and proceed only when the safety status is resolved.",
    interpretation: "A patient report that an implant is 'MRI safe' is not sufficient when conditions are device-specific; documentation and current device labeling govern the decision.",
    safety: "Do not bring conventional ferromagnetic emergency equipment into the scanner room and do not bypass screening because a study is urgent.",
    redFlags: "Unidentified implant, suspected orbital metal, nonverified pacemaker or neurostimulator, ferromagnetic object in a controlled zone, or patient emergency near the bore requires stopping and activating the MRI safety process.",
    commonErrors: "Assuming all modern implants are safe, relying on memory rather than device documentation, and forgetting that ancillary equipment can become a projectile.",
    examFocus: "Know the hierarchy: screen, verify, control the environment, and never substitute urgency for device-specific safety confirmation.",
    glossary: [
      { term: "MR Conditional", definition: "Device shown to be safe only under specified MRI conditions such as field strength, SAR, positioning, or scan parameters." },
      { term: "Projectile effect", definition: "Forceful attraction of a ferromagnetic object toward the MRI magnet." },
    ],
  },
  {
    id: "sonography-optimization-artifacts",
    careerType: "diagnosticSonography",
    examTag: "ARDMS SPI",
    regionScope: "US",
    category: "Ultrasound Physics",
    topic: "Image Optimization and Artifact Recognition",
    bottomLine: "Optimize the image by changing the parameter that matches the problem—frequency, depth, focus, gain, dynamic range, Doppler scale, or angle—before assuming an abnormal image represents pathology.",
    coreConcept: "Ultrasound image quality reflects tradeoffs among penetration, resolution, frame rate, and signal processing; artifacts arise when the assumptions used to construct the image are violated.",
    recognition: "Reverberation, mirror image, posterior enhancement, acoustic shadowing, side lobes, aliasing, blooming, and anisotropy can mimic or hide disease.",
    workflow: "Define the clinical target, select the highest practical frequency, set depth and focal zone, adjust overall and time-gain compensation, optimize dynamic range and persistence, then use alternate planes or parameter changes to test whether a finding persists.",
    interpretation: "A true structure should behave consistently across planes and appropriate setting changes; artifacts often change or disappear when beam angle, frequency, focus, or transducer position changes.",
    safety: "Use output power and dwell time consistent with the examination goal and avoid unnecessary prolonged exposure, especially in sensitive tissues.",
    redFlags: "A suspected urgent pathology that is visible only in one poor-quality plane, severe image degradation despite optimization, or a finding inconsistent with anatomy should prompt repeat acquisition or higher-level review.",
    commonErrors: "Compensating for poor penetration with excessive gain, ignoring angle dependence, and treating aliasing or anisotropy as pathology without testing the artifact mechanism.",
    examFocus: "SPI questions reward linking each artifact to its physical cause and choosing the most targeted control adjustment.",
    glossary: [
      { term: "Anisotropy", definition: "Angle-dependent change in echogenicity, especially in tendons and other organized structures." },
      { term: "Aliasing", definition: "Doppler artifact occurring when the Doppler shift exceeds the Nyquist limit in pulsed-wave sampling." },
    ],
  },
  {
    id: "sonography-venous-duplex-dvt",
    careerType: "diagnosticSonography",
    examTag: "ARDMS SPI",
    regionScope: "US",
    category: "Vascular Sonography",
    topic: "Lower-Extremity Venous Duplex for Suspected DVT",
    bottomLine: "Compression is the core criterion for acute lower-extremity DVT assessment; Doppler findings support the interpretation but do not replace complete anatomic compression where required.",
    coreConcept: "A normal vein collapses with adequate transducer pressure, while acute thrombus can prevent complete coaptation and alter venous flow patterns.",
    recognition: "Noncompressibility, intraluminal echoes, venous distention, absent or reduced color filling, and abnormal phasicity or augmentation are key findings.",
    workflow: "Confirm indication and protocol, scan the required venous segments in transverse compression, use color and spectral Doppler to assess flow characteristics, document abnormal segments and extent, and communicate urgent findings according to policy.",
    interpretation: "Noncompressibility is highly significant; chronic post-thrombotic change may show echogenic wall-adherent material, smaller caliber, collateralization, or partial recanalization rather than the distended appearance of acute thrombus.",
    safety: "Use gentle technique in painful or postoperative limbs and avoid aggressive augmentation when contraindicated by local protocol or clinical concern.",
    redFlags: "Extensive proximal thrombus, phlegmasia features, sudden cardiopulmonary symptoms during the exam, or findings suggesting iliocaval obstruction requires prompt escalation.",
    commonErrors: "Skipping compression because color flow appears present, confusing artery for vein, and calling chronic wall thickening an acute occlusive clot without considering morphology and history.",
    examFocus: "Expect questions on compression technique, acute-versus-chronic features, and why color alone cannot exclude DVT.",
    glossary: [
      { term: "Compressibility", definition: "Ability of a vein to collapse fully under transducer pressure, a primary criterion for excluding thrombus in assessed segments." },
      { term: "Phasicity", definition: "Respiratory variation in venous Doppler flow that reflects pressure transmission and proximal patency." },
    ],
  },
  {
    id: "cardiac-sonography-diastolic-function",
    careerType: "cardiacSonographer",
    examTag: "ARDMS RDCS",
    regionScope: "US",
    category: "Adult Echocardiography",
    topic: "Diastolic Function and Filling Pressure Assessment",
    bottomLine: "Grade diastolic function from an integrated pattern of transmitral inflow, tissue Doppler, atrial size, pulmonary pressures, rhythm, and clinical context rather than a single E/A ratio.",
    coreConcept: "Ventricular relaxation and compliance alter the pressure gradient between the left atrium and ventricle, changing mitral inflow and tissue velocities in predictable but context-dependent ways.",
    recognition: "Abnormal e' velocity, elevated E/e', enlarged left atrium, altered E/A pattern, shortened or prolonged deceleration time, and increased tricuspid-regurgitation velocity can support elevated filling pressure.",
    workflow: "Confirm image and Doppler quality, note rhythm and valve disease, acquire standardized mitral inflow and tissue Doppler measurements, integrate supporting variables, and identify situations where standard algorithms are unreliable.",
    interpretation: "Pseudonormal inflow can look deceptively normal, so tissue Doppler and other corroborating variables are necessary when relaxation abnormality is suspected.",
    safety: "Do not overstate filling pressure when key measurements are technically poor or confounded by arrhythmia, severe mitral disease, pacing, or other known limitations.",
    redFlags: "New severe pulmonary pressure elevation, marked right-heart strain, major valve abnormality, or hemodynamic instability discovered during the study requires timely clinical communication.",
    commonErrors: "Assigning grade from E/A ratio alone, ignoring rhythm, and measuring tissue Doppler away from the annular sample location.",
    examFocus: "RDCS-style questions emphasize integrated interpretation and recognition of situations where the standard algorithm should not be applied mechanically.",
    glossary: [
      { term: "e' velocity", definition: "Early diastolic mitral annular tissue Doppler velocity used as an index of myocardial relaxation." },
      { term: "Pseudonormal filling", definition: "Transmitral inflow pattern that appears normal because elevated atrial pressure masks impaired relaxation." },
    ],
  },
  {
    id: "cardiac-sonography-prosthetic-valves",
    careerType: "cardiacSonographer",
    examTag: "ARDMS RDCS",
    regionScope: "US",
    category: "Adult Echocardiography",
    topic: "Prosthetic Valve Hemodynamics and Dysfunction",
    bottomLine: "Assess prosthetic valves by knowing the valve type and size, comparing Doppler findings with expected and prior values, and looking for obstruction, regurgitation, dehiscence, or thrombosis as a pattern.",
    coreConcept: "Normal prosthetic valves have nonzero gradients and characteristic flow profiles; dysfunction is identified by unexpectedly high or changing gradients, abnormal flow contour, reduced effective orifice area, or pathologic regurgitation.",
    recognition: "Rising velocity or gradient from baseline, prolonged acceleration time, abnormal regurgitant jets, rocking motion, restricted leaflet motion, or new hemolysis-compatible findings can suggest dysfunction.",
    workflow: "Identify valve type and position, optimize standard views, record CW Doppler from multiple windows, measure required timing and velocity parameters, assess regurgitation and motion, compare with prior studies and reference values, and document limitations.",
    interpretation: "A high gradient can reflect obstruction, high flow, patient-prosthesis mismatch, or measurement error; serial comparison and flow-independent clues help separate them.",
    safety: "Do not label obstruction from one elevated velocity without confirming alignment and hemodynamic context, but do not delay communication when severe new dysfunction is apparent.",
    redFlags: "New severe prosthetic regurgitation, suspected dehiscence, thrombosis with obstruction, major gradient rise with symptoms, or unstable hemodynamics requires urgent escalation.",
    commonErrors: "Using native-valve thresholds without considering prosthesis type, ignoring prior baseline studies, and measuring from a suboptimal Doppler window.",
    examFocus: "Differentiate true obstruction from high-flow states and patient-prosthesis mismatch using multiple Doppler features and prior comparison.",
    glossary: [
      { term: "Patient-prosthesis mismatch", definition: "A normally functioning prosthesis whose effective orifice area is too small relative to patient body size." },
      { term: "Acceleration time", definition: "Time from onset of systolic flow to peak velocity, useful in evaluating some prosthetic valve obstruction patterns." },
    ],
  },
  {
    id: "ota-cognitive-perceptual-stroke-rehab",
    careerType: "occupationalTherapyAssistant",
    examTag: "NBCOT COTA",
    regionScope: "US",
    category: "Adult Rehabilitation",
    topic: "Cognitive-Perceptual Rehabilitation After Stroke",
    bottomLine: "Translate cognitive and perceptual impairments into functional safety problems, then use task-specific remediation and compensatory strategies within the OT plan of care.",
    coreConcept: "Attention, neglect, visual-perceptual processing, executive function, and apraxia can impair ADLs even when strength appears adequate; treatment must connect impairment to occupation.",
    recognition: "Collisions on one side, incomplete grooming, poor sequencing, unsafe judgment, perseveration, difficulty initiating tasks, or inconsistent object use are common functional cues.",
    workflow: "Observe performance in meaningful tasks, follow the OTR-established goals, grade environmental complexity, cue only as much as needed, use scanning or external supports when indicated, document response, and communicate changes to the supervising OTR.",
    interpretation: "Improved performance with visual anchors or reduced distraction suggests a compensatory strategy is helping; generalization to new contexts is more meaningful than success on one practiced task.",
    safety: "Do not allow independent mobility, cooking, medication management, or community tasks when neglect or executive dysfunction creates unrecognized hazards.",
    redFlags: "New neurologic decline, acute change in cognition, repeated unsafe behavior despite cueing, or inability to follow basic safety directions requires escalation.",
    commonErrors: "Treating paper-and-pencil performance as equivalent to functional ability, over-cueing so the patient never problem-solves, and ignoring caregiver training.",
    examFocus: "NBCOT/COTA questions emphasize occupation-based intervention, grading, safety, and communication within the assistant role.",
    glossary: [
      { term: "Unilateral neglect", definition: "Failure to attend or respond to stimuli on one side despite adequate primary sensory function." },
      { term: "Apraxia", definition: "Impaired motor planning that disrupts learned purposeful movement despite sufficient strength." },
    ],
  },
  {
    id: "ota-orthosis-skin-safety",
    careerType: "occupationalTherapyAssistant",
    examTag: "NBCOT COTA",
    regionScope: "US",
    category: "Physical Disabilities",
    topic: "Upper-Extremity Orthosis Use, Fit, and Skin Safety",
    bottomLine: "An orthosis is therapeutic only when fit, wear schedule, skin response, and functional use are monitored; pain, pressure, or neurovascular compromise are not normal adaptation.",
    coreConcept: "Orthoses apply controlled forces over time to position, protect, or mobilize tissue, so small fit errors can create concentrated pressure, skin injury, edema, or nerve compression.",
    recognition: "Persistent redness, blistering, numbness, swelling, increased pain, pressure over bony prominences, or reduced function after donning are warning signs.",
    workflow: "Inspect the skin before use, verify straps and landmarks, follow the prescribed wear schedule, educate on donning/doffing and cleaning, reassess skin after use, document tolerance, and communicate needed modifications to the OTR or responsible clinician.",
    interpretation: "Brief mild erythema that resolves rapidly differs from persistent focal redness or neurologic symptoms, which suggest excessive pressure or poor fit.",
    safety: "Stop use and escalate rather than independently reshaping or changing the therapeutic design beyond delegated competence and local policy.",
    redFlags: "Persistent skin discoloration, blistering, severe pain, paresthesia, cold digits, delayed capillary refill, or rapidly increasing edema requires prompt reassessment.",
    commonErrors: "Tightening straps to stop migration without checking fit, placing material over open skin without authorization, and assuming discomfort is required for benefit.",
    examFocus: "Prioritize skin integrity, patient education, adherence, and assistant-versus-OTR role boundaries.",
    glossary: [
      { term: "Orthosis", definition: "External device used to support, align, protect, or influence motion of a body segment." },
      { term: "Pressure area", definition: "Localized region where orthotic force is concentrated and may threaten tissue integrity." },
    ],
  },
  {
    id: "pta-cardiopulmonary-exercise-monitoring",
    careerType: "physiotherapyAssistant",
    examTag: "FSBPT PTA",
    regionScope: "US",
    category: "Cardiopulmonary Rehabilitation",
    topic: "Exercise Monitoring in Cardiopulmonary Rehabilitation",
    bottomLine: "During delegated cardiopulmonary exercise, trend symptoms, heart rate, blood pressure, oxygenation, perceived exertion, and recovery; stop and escalate when the response is unsafe or deviates from the plan of care.",
    coreConcept: "Exercise tolerance reflects the integrated cardiovascular, pulmonary, and muscular response; a safe progression depends on both workload and physiologic recovery.",
    recognition: "Disproportionate dyspnea, angina-like symptoms, dizziness, abnormal blood-pressure response, falling oxygen saturation, marked tachycardia, or delayed recovery are important cues.",
    workflow: "Review the PT-established parameters and precautions, obtain baseline measures, confirm equipment and oxygen plan, supervise graded activity, monitor physiologic and symptom response, apply authorized adjustments within the plan, and document recovery.",
    interpretation: "A rising workload with stable symptoms and appropriate recovery supports progression, while worsening symptoms at the same workload suggests regression or a new medical issue.",
    safety: "Do not independently change medical oxygen prescriptions, exercise contraindications, or treatment goals outside the delegated plan and local scope.",
    redFlags: "Chest pressure, syncope, new neurologic symptoms, severe desaturation, sustained dangerous dysrhythmia, or hemodynamic instability requires immediate stop and escalation.",
    commonErrors: "Progressing from workload alone, ignoring recovery time, and treating a target heart rate as valid despite medications or rhythm conditions that alter chronotropic response.",
    examFocus: "FSBPT PTA items emphasize monitoring, stop criteria, documentation, and when the assistant must return the patient to the PT or medical team.",
    glossary: [
      { term: "RPE", definition: "Rating of perceived exertion used to quantify the patient's subjective exercise intensity." },
      { term: "Recovery", definition: "Return of symptoms and physiologic measures toward baseline after exercise cessation." },
    ],
  },
  {
    id: "pta-total-joint-functional-progression",
    careerType: "physiotherapyAssistant",
    examTag: "FSBPT PTA",
    regionScope: "US",
    category: "Musculoskeletal Rehabilitation",
    topic: "Functional Progression After Total Hip or Knee Arthroplasty",
    bottomLine: "Progress mobility according to the PT plan, surgical precautions, pain and swelling response, strength, gait quality, and functional safety rather than a fixed postoperative day alone.",
    coreConcept: "Early mobility supports recovery, but progression is limited by tissue protection, fall risk, wound status, hemodynamic tolerance, and procedure-specific precautions.",
    recognition: "Improving transfer quality, gait distance, knee extension/flexion or hip control, stair performance, and reduced cueing support progression; increasing swelling, buckling, severe pain, or wound changes do not.",
    workflow: "Verify current precautions and weight-bearing status, assess baseline symptoms and vital tolerance, train transfers and assistive-device use, progress gait and functional exercise within the plan, reinforce home safety, and report deviations to the PT.",
    interpretation: "A patient may walk farther yet be less safe if gait mechanics deteriorate or assistance needs rise; quality and independence matter alongside distance.",
    safety: "Do not infer weight-bearing or hip precautions from the procedure name alone, because surgical approach and surgeon instructions can differ.",
    redFlags: "New calf swelling, chest symptoms, sudden severe joint pain, dislocation signs, fever with wound change, repeated buckling, or acute neurologic deficit requires escalation.",
    commonErrors: "Progressing too quickly because pain is low, failing to adjust assistive-device height, and measuring success only by distance.",
    examFocus: "Choose the progression that preserves precautions and safety while moving the patient toward functional independence.",
    glossary: [
      { term: "Weight-bearing status", definition: "Allowed amount of body weight through the operated limb as specified by the surgical plan." },
      { term: "Functional progression", definition: "Graded advancement of mobility and daily activities based on performance and safety criteria." },
    ],
  },
  {
    id: "surgical-counts-retained-items",
    careerType: "surgicalTechnologist",
    examTag: "NBSTSA CST",
    regionScope: "US",
    category: "Intraoperative Procedures",
    topic: "Surgical Counts and Retained-Item Prevention",
    bottomLine: "Counts are a team safety process: standardize timing, count audibly and visibly, reconcile discrepancies immediately, and never let pressure to close override unresolved count safety.",
    coreConcept: "Retained surgical items are prevented through multiple defenses—standardized counts, radiopaque items, communication, wound exploration, and imaging or escalation when a discrepancy persists.",
    recognition: "Interrupted counts, staff changes, emergency procedures, unexpected additional items, multiple cavities, and count discrepancies increase retained-item risk.",
    workflow: "Organize items consistently, perform counts with the circulating nurse at required phases, document additions, keep sharps and sponges controlled, announce discrepancies immediately, repeat the count, search methodically, and follow policy for imaging or further escalation.",
    interpretation: "A repeat count that remains incorrect is an unresolved safety event, not a documentation problem to be corrected after closure.",
    safety: "Do not alter the recorded count to match expectation or allow discarded materials to leave the room before required reconciliation.",
    redFlags: "Unresolved count, missing needle or sponge, emergency conversion, unexpected cavity entry, or specimen/material confusion requires immediate team stop and escalation.",
    commonErrors: "Counting from memory, allowing interruptions without restart, discarding counted items prematurely, and assuming a small needle is clinically insignificant.",
    examFocus: "NBSTSA questions often ask the technologist's first action after a discrepancy: announce it, stop routine progression, and begin the established reconciliation process.",
    glossary: [
      { term: "Closing count", definition: "Formal count performed at specified closure stages to confirm accountability for sponges, sharps, and instruments." },
      { term: "Retained surgical item", definition: "Unintentionally retained sponge, instrument, needle, or other material after a procedure." },
    ],
  },
  {
    id: "surgical-laparoscopic-energy-safety",
    careerType: "surgicalTechnologist",
    examTag: "NBSTSA CST",
    regionScope: "US",
    category: "Surgical Technology",
    topic: "Laparoscopic Insufflation and Electrosurgical Safety",
    bottomLine: "Safe laparoscopy depends on controlled access and insufflation, continuous awareness of energy-device hazards, and immediate response to signs of gas, thermal, or equipment complications.",
    coreConcept: "Pneumoperitoneum changes cardiopulmonary physiology while electrosurgical energy can injure tissue outside the intended target through insulation failure, coupling, or poor visualization.",
    recognition: "Abnormal insufflation pressure, poor abdominal distention, subcutaneous emphysema, equipment alarm, insulation defect, unexpected smoke, or unexplained tissue injury are important cues.",
    workflow: "Verify equipment and energy settings, prepare insufflation tubing and access devices, maintain organized cords and instruments, inspect insulation, monitor instrument exchanges and activation field, support smoke evacuation, and report abnormalities immediately.",
    interpretation: "High pressure with poor insufflation may indicate access or tubing problems, while unexpected tissue effect away from the active tip raises concern for energy transfer or insulation failure.",
    safety: "Do not activate energy without the active tip in view and do not reuse damaged insulated instruments merely because they still function electrically.",
    redFlags: "Sudden hemodynamic instability during insufflation, suspected gas embolism, extensive subcutaneous emphysema, equipment arcing, or visible unintended thermal injury requires immediate escalation.",
    commonErrors: "Focusing only on the operative field and ignoring cable/instrument integrity, using higher energy instead of correcting contact or visualization, and continuing after repeated insufflator alarms without identifying cause.",
    examFocus: "Connect equipment malfunction to patient risk and choose the action that removes the hazard before the procedure continues.",
    glossary: [
      { term: "Pneumoperitoneum", definition: "Gas insufflation of the peritoneal cavity to create working space for laparoscopy." },
      { term: "Capacitive coupling", definition: "Unintended transfer of electrical energy through intact insulation to nearby conductive tissue or instruments." },
    ],
  },
  {
    id: "him-clinical-documentation-integrity",
    careerType: "healthInfoMgmt",
    examTag: "AHIMA RHIT",
    regionScope: "US",
    category: "Data Content, Structure, and Standards",
    topic: "Clinical Documentation Integrity and Compliant Queries",
    bottomLine: "A compliant documentation query clarifies the health record without steering the provider toward a predetermined diagnosis or code.",
    coreConcept: "Clinical documentation must support accurate patient care, coding, quality reporting, and legal integrity; clarification is appropriate when the record is incomplete, conflicting, imprecise, or clinically inconsistent.",
    recognition: "Conflicting diagnoses, unclear acuity, missing linkage between conditions, ambiguous cause-and-effect statements, unsupported specificity, and discrepancy between clinical indicators and documentation can justify clarification.",
    workflow: "Identify the documentation gap, verify relevant clinical indicators, draft a neutral and nonleading query with appropriate answer options or open response, send through the approved workflow, preserve the query record, and ensure the final record reflects the provider's independent conclusion.",
    interpretation: "The purpose of the query is clarity, not maximizing reimbursement; a clinically reasonable provider response can include 'unable to determine' or another diagnosis not suggested by the query.",
    safety: "Do not use reimbursement pressure to influence query wording and do not retrospectively alter the provider's original record outside the authorized amendment process.",
    redFlags: "Patterned leading queries, repeated unsupported upcoding, deletion of unfavorable documentation, or alteration of finalized records outside policy requires compliance escalation.",
    commonErrors: "Embedding the desired diagnosis in the question, omitting contradictory indicators, and assuming a coder can infer a diagnosis that the provider did not document.",
    examFocus: "RHIT items test neutrality, documentation integrity, and the difference between clarifying the record and directing clinical conclusions.",
    glossary: [
      { term: "Compliant query", definition: "Neutral request for provider clarification based on the health record without directing a specific unsupported response." },
      { term: "Clinical indicators", definition: "Documented signs, symptoms, tests, treatments, and other facts relevant to a clinical condition under clarification." },
    ],
  },
  {
    id: "him-record-correction-audit-trail",
    careerType: "healthInfoMgmt",
    examTag: "AHIMA RHIT",
    regionScope: "US",
    category: "Information Protection",
    topic: "Health Record Corrections, Amendments, and Audit Trails",
    bottomLine: "Correct errors transparently: preserve the original entry, identify the author and date of correction, document the reason when required, and maintain an audit trail that shows what changed.",
    coreConcept: "The health record is a legal and clinical document; trustworthy correction processes preserve provenance instead of making prior information disappear.",
    recognition: "Wrong-patient entries, incorrect demographics, factual errors, late entries, amended diagnoses, and unauthorized edits are common integrity issues.",
    workflow: "Verify the error and authority to correct it, follow the organization's amendment process, preserve the original content, add the corrected information with attribution and timing, route patient-requested amendments appropriately, and monitor the audit log for unauthorized activity.",
    interpretation: "An amendment adds or corrects information while preserving provenance; deleting a valid historical entry or overwriting the audit trail undermines record integrity.",
    safety: "Never share credentials, backdate an entry to make it appear contemporaneous, or delete an erroneous clinical entry in a way that removes evidence of the correction.",
    redFlags: "Unauthorized mass edits, altered timestamps, missing audit events, access by users without a treatment/business need, or suspicious correction patterns requires privacy/security investigation.",
    commonErrors: "Using copy-paste to replace rather than amend, confusing a late entry with a correction, and treating the audit log as optional administrative data.",
    examFocus: "RHIT questions emphasize provenance, authorization, transparency, and privacy/security escalation.",
    glossary: [
      { term: "Audit trail", definition: "System record showing access, creation, modification, and other activity associated with electronic health information." },
      { term: "Amendment", definition: "Authorized addition or correction to the record that preserves the historical entry and identifies the change." },
    ],
  },
  {
    id: "psychotherapy-suicide-risk-safety-planning",
    careerType: "psychotherapist",
    examTag: "RP Qualifying",
    regionScope: "CAN",
    category: "Clinical Practice",
    topic: "Suicide Risk Formulation and Collaborative Safety Planning",
    bottomLine: "Suicide assessment is an ongoing clinical formulation, not a checklist score; identify acute and chronic risk, protective factors, access to means, intent, and the least restrictive safe level of care.",
    coreConcept: "Risk changes over time and is shaped by current intent, planning, capability, agitation, substance use, losses, psychiatric symptoms, supports, and ability to collaborate with a safety plan.",
    recognition: "Escalating hopelessness, recent attempt, preparatory behavior, specific plan, access to lethal means, intoxication, psychosis, severe agitation, and loss of protective supports are high-concern cues.",
    workflow: "Ask directly about suicidal thoughts and behavior, clarify intent and access to means, assess recent changes and supports, formulate acute versus baseline risk, collaborate on a concrete safety plan when appropriate, involve emergency resources when risk cannot be managed outpatient, and document reasoning.",
    interpretation: "Denial of current intent does not erase other high-risk evidence; the formulation should explain why the chosen disposition is safe given the total pattern.",
    safety: "Do not rely on no-suicide contracts or a numeric scale alone, and do not promise confidentiality when imminent safety obligations require disclosure under applicable law and professional standards.",
    redFlags: "Current intent with a feasible plan, inability to commit to immediate safety steps, command hallucinations, severe intoxication, rapidly worsening agitation, or recent high-lethality attempt requires urgent escalation.",
    commonErrors: "Avoiding direct questions, documenting only a score, overvaluing one protective factor, and creating a generic safety plan without means-safety or crisis-contact steps.",
    examFocus: "RP qualifying scenarios emphasize judgment, documentation, collaboration, boundaries, and proportionate escalation rather than rigid prediction.",
    glossary: [
      { term: "Risk formulation", definition: "Clinical synthesis of static and dynamic risk factors, protective factors, current state, and foreseeable changes used to guide management." },
      { term: "Safety plan", definition: "Collaborative, stepwise plan for recognizing warning signs, using internal coping strategies, contacting supports, reducing access to lethal means, and obtaining urgent help." },
    ],
  },
  {
    id: "psychotherapy-trauma-stabilization-window",
    careerType: "psychotherapist",
    examTag: "RP Qualifying",
    regionScope: "CAN",
    category: "Clinical Practice",
    topic: "Trauma Treatment Stabilization and Window of Tolerance",
    bottomLine: "Trauma processing should occur only when the client has sufficient stability, consent, and regulation capacity; pacing and grounding are clinical interventions, not delays in treatment.",
    coreConcept: "Clients may move into hyperarousal or hypoarousal when trauma activation exceeds their capacity to remain engaged; treatment must balance therapeutic exposure with regulation and safety.",
    recognition: "Dissociation, panic, shutdown, disorientation, self-harm urges, escalating substance use, sleep collapse, or inability to remain present during sessions signals a need to reassess pacing.",
    workflow: "Establish safety and goals, assess current supports and regulation skills, teach grounding and present-focused strategies, collaboratively monitor activation, titrate trauma work, pause processing when the client leaves a workable range, and reassess between-session functioning.",
    interpretation: "Strong emotion is not automatically harmful, but loss of orientation, sustained dysregulation, or functional deterioration suggests the intervention intensity exceeds current capacity.",
    safety: "Do not push disclosure or exposure because the therapist believes the client 'must face it'; informed consent and pacing remain central throughout treatment.",
    redFlags: "New suicidality, severe dissociation, inability to care for basic needs, acute psychosis, dangerous substance use, or repeated post-session destabilization requires higher-level assessment or modified treatment.",
    commonErrors: "Equating catharsis with progress, using grounding only after crisis occurs, and continuing a protocol rigidly despite clear destabilization.",
    examFocus: "Qualifying-exam cases often test whether the therapist prioritizes safety, consent, pacing, and scope rather than technique loyalty.",
    glossary: [
      { term: "Window of tolerance", definition: "Range of arousal within which a person can remain sufficiently regulated to process information and engage effectively." },
      { term: "Grounding", definition: "Present-focused strategies that help reduce dissociation or overwhelming arousal by orienting attention to current sensory and contextual cues." },
    ],
  },
  {
    id: "addictions-overdose-prevention-naloxone",
    careerType: "addictionsCounsellor",
    examTag: "IC&RC CAC",
    regionScope: "BOTH",
    category: "Addiction Counseling",
    topic: "Opioid Overdose Prevention, Naloxone, and Post-Overdose Engagement",
    bottomLine: "Overdose prevention combines naloxone access, recognition training, reduced-risk use strategies, emergency response, and nonjudgmental linkage to ongoing treatment after survival.",
    coreConcept: "Opioid overdose kills through respiratory depression; naloxone can temporarily reverse opioid effects but does not replace airway support, emergency assessment, or treatment of recurrent toxicity.",
    recognition: "Unresponsiveness, slow or absent breathing, cyanosis, pinpoint pupils, abnormal snoring or gurgling, and inability to awaken the person are classic overdose cues.",
    workflow: "Recognize overdose, activate emergency response, support breathing as trained, administer naloxone when available, repeat according to product/protocol if needed, remain with the person, reduce immediate hazards, and offer follow-up treatment and harm-reduction linkage without coercion.",
    interpretation: "Rapid awakening after naloxone supports opioid toxicity but does not exclude co-ingestants or recurrent sedation after naloxone wears off.",
    safety: "Counsellors should not exceed training or local scope; emphasize emergency response, rescue breathing/CPR according to training, and safe naloxone use rather than unsupported medical management.",
    redFlags: "No response to naloxone, persistent hypoxia, chest pain, seizure, severe agitation, recurrent sedation, or suspected polysubstance exposure requires emergency medical care.",
    commonErrors: "Assuming one naloxone dose ends the event, leaving the person alone after awakening, and using shame or treatment ultimatums immediately after an overdose.",
    examFocus: "IC&RC-style reasoning emphasizes harm reduction, client dignity, emergency recognition, and linkage to evidence-based treatment.",
    glossary: [
      { term: "Naloxone", definition: "Opioid antagonist used to reverse life-threatening opioid-induced respiratory depression." },
      { term: "Post-overdose engagement", definition: "Nonjudgmental follow-up after overdose focused on safety, treatment access, and reduction of future risk." },
    ],
  },
  {
    id: "addictions-motivational-interviewing-ambivalence",
    careerType: "addictionsCounsellor",
    examTag: "IC&RC CAC",
    regionScope: "BOTH",
    category: "Addiction Counseling",
    topic: "Motivational Interviewing for Ambivalence and Change Talk",
    bottomLine: "Motivational interviewing strengthens a client's own reasons for change through partnership, evocation, acceptance, and compassion rather than argument or persuasion.",
    coreConcept: "Ambivalence is expected in behavior change; reflective listening and strategic questions can increase change talk while confrontation often increases sustain talk and resistance.",
    recognition: "Statements about desire, ability, reasons, need, commitment, activation, or taking steps are forms of change talk; arguments for staying the same are sustain talk.",
    workflow: "Engage with open questions and reflections, focus on a mutually meaningful target, evoke the client's own motivations and discrepancies, reinforce change talk, summarize selectively without distorting, and move to planning when readiness is present.",
    interpretation: "More intense practitioner persuasion does not equal more motivation; the useful signal is whether the client is voicing and elaborating personally meaningful reasons and plans for change.",
    safety: "Motivational interviewing does not override urgent safety duties; intoxication, withdrawal emergencies, suicidality, violence risk, or inability to participate requires appropriate escalation first.",
    redFlags: "Acute medical instability, severe withdrawal, current suicidal intent, psychosis, or imminent violence risk takes priority over routine motivational work.",
    commonErrors: "Using reflections as disguised advice, arguing with sustain talk, asking question after question without reflections, and pushing an action plan before the client has selected a goal.",
    examFocus: "Choose responses that elicit and reinforce client-generated change language while preserving autonomy and safety.",
    glossary: [
      { term: "Change talk", definition: "Client language that favors movement toward change, including desire, ability, reasons, need, commitment, activation, and taking steps." },
      { term: "Sustain talk", definition: "Client language favoring continuation of the current behavior or status quo." },
    ],
  },
];
