import type { AlliedAuthoredTopic } from "./types";

export const alliedTopics04: AlliedAuthoredTopic[] = [
  {
    id: "ota-activity-analysis",
    careerType: "occupationalTherapyAssistant",
    examTag: "NBCOT COTA",
    regionScope: "US",
    category: "Domain and Process",
    topic: "Activity Analysis and Grading",
    bottomLine: "Break an occupation into motor, process, sensory, cognitive, environmental, and social demands, then grade one or more demands to create the just-right challenge tied to the intervention goal.",
    coreConcept: "Grading changes task demand while adaptation changes the way a task or environment is performed so participation becomes possible or safer.",
    recognition: "A task that is too difficult may show repeated failure, unsafe compensations, fatigue, loss of attention, or inability to complete the targeted step despite cueing.",
    workflow: "Identify the occupational goal, analyze task demands, compare them with client factors/performance skills, select the limiting demand, grade or adapt it, observe response, and document the functional effect.",
    interpretation: "Improvement during a simplified task does not automatically mean the underlying skill changed; distinguish compensation from remediation.",
    safety: "Do not increase challenge when the client loses safe body mechanics, judgment, balance, cardiopulmonary tolerance, or adherence to precautions.",
    redFlags: "New neurologic symptoms, severe dyspnea, chest pain, unsafe impulsivity, repeated loss of balance, or violation of surgical precautions requires stopping and escalation.",
    commonErrors: "Making several task changes at once, choosing an activity because it is entertaining rather than goal-linked, and confusing adaptation with restoration.",
    examFocus: "NBCOT items often ask which change best preserves occupation while adjusting one performance demand.",
    glossary: [{ term: "Grading", definition: "Systematically increasing or decreasing activity demands to match therapeutic goals and client ability." }, { term: "Adaptation", definition: "Modification of task, tool, environment, or method to enable participation." }],
  },
  {
    id: "ota-adl-training",
    careerType: "occupationalTherapyAssistant",
    examTag: "NBCOT COTA",
    regionScope: "US",
    category: "Intervention",
    topic: "ADL Retraining and Compensatory Strategies",
    bottomLine: "Train ADLs in the real or simulated performance context, prioritize safety and independence, and choose restorative versus compensatory methods according to the client goal and prognosis.",
    coreConcept: "Occupational performance improves when task practice is meaningful, context-specific, appropriately graded, and reinforced with consistent cues or adaptive methods.",
    recognition: "Difficulty sequencing, one-handed limitations, impaired balance, low endurance, visual neglect, pain, or cognitive deficits alter the safest dressing, bathing, toileting, and grooming strategy.",
    workflow: "Clarify the goal and precautions, observe baseline performance, identify the limiting step, select cueing/equipment/strategy, practice the whole task or key components, reassess independence, and document assistance level.",
    interpretation: "A client who completes the task only with repeated verbal cues remains limited in independent performance even if the physical steps are completed.",
    safety: "Use seated methods, pacing, environmental setup, and assistance when balance or cardiopulmonary tolerance makes standing ADLs unsafe.",
    redFlags: "Syncope, chest pain, acute confusion, new weakness, unsafe transfer behavior, or inability to follow critical precautions requires immediate reassessment.",
    commonErrors: "Overassisting instead of allowing problem solving, teaching equipment before assessing need, and documenting vague improvement without assistance level or cueing type.",
    examFocus: "Choose the least restrictive strategy that safely improves occupation and supports the established plan of care.",
    glossary: [{ term: "ADL", definition: "Activity of daily living such as bathing, dressing, toileting, grooming, feeding, and functional mobility." }, { term: "Compensation", definition: "Strategy that works around an impairment rather than directly restoring the impaired function." }],
  },
  {
    id: "ota-cognition",
    careerType: "occupationalTherapyAssistant",
    examTag: "NBCOT COTA",
    regionScope: "US",
    category: "Intervention",
    topic: "Functional Cognition and Cueing",
    bottomLine: "Evaluate cognition through occupational performance and use the least amount of cueing, structure, or environmental support needed for safe task completion.",
    coreConcept: "Functional cognition includes attention, memory, initiation, sequencing, problem solving, judgment, and self-monitoring as they appear during real tasks.",
    recognition: "Perseveration, skipped steps, unsafe choices, inability to self-correct, distractibility, or failure to initiate can reveal functional cognitive limitation even when conversation sounds normal.",
    workflow: "Choose a meaningful task, observe without unnecessary help, identify the breakdown, provide graded cues from least to more supportive, modify the environment when indicated, and document what level of support produced success.",
    interpretation: "Performance with a visual checklist may show successful compensation, not necessarily independent new learning; carryover must be assessed over time and context.",
    safety: "When judgment is impaired, do not remove supervision solely because motor ability is intact.",
    redFlags: "Acute change in cognition, new focal deficit, severe agitation, unsafe wandering, or inability to recognize hazards requires escalation beyond routine training.",
    commonErrors: "Testing cognition only through questions, cueing too early, and describing a client as independent while external structure is doing the work.",
    examFocus: "NBCOT scenarios commonly test cue hierarchy, environmental modification, and safety implications of executive dysfunction.",
    glossary: [{ term: "Functional cognition", definition: "Use of cognitive abilities during performance of everyday activities." }, { term: "Cue hierarchy", definition: "Progression from less to more assistance used to support task performance while preserving independence." }],
  },
  {
    id: "ota-ue-neuro",
    careerType: "occupationalTherapyAssistant",
    examTag: "NBCOT COTA",
    regionScope: "US",
    category: "Intervention",
    topic: "Upper-Extremity Neurorehabilitation After Stroke",
    bottomLine: "Protect the hemiparetic shoulder, facilitate meaningful use of the affected upper extremity when appropriate, prevent learned nonuse and injury, and integrate positioning, task practice, and compensatory methods into occupation.",
    coreConcept: "Motor recovery is influenced by task-specific practice, sensory feedback, tone, weakness, neglect, pain, and the ability to actively control the limb.",
    recognition: "Subluxation, pain, edema, spasticity, flaccidity, neglect, poor scapular mechanics, and sensory loss change handling and activity selection.",
    workflow: "Check precautions and shoulder status, position scapula and arm safely, use supported purposeful tasks within available control, train caregivers in protection, reassess pain and movement quality, and avoid traction on the arm.",
    interpretation: "More movement is not always better if it reinforces painful or abnormal compensatory patterns that reduce function.",
    safety: "Never pull on the affected arm during transfers and avoid aggressive overhead range when scapulohumeral mechanics are poor or pain increases.",
    redFlags: "New severe shoulder pain, marked swelling, sudden loss of function, autonomic changes, or new neurologic deficit requires medical/therapy reassessment.",
    commonErrors: "Using pulleys indiscriminately, allowing the arm to hang unsupported, and focusing on isolated exercise without occupational integration.",
    examFocus: "Shoulder protection and functionally meaningful task practice are high-yield priorities.",
    glossary: [{ term: "Hemiparesis", definition: "Weakness affecting one side of the body." }, { term: "Learned nonuse", definition: "Reduced use of an affected limb reinforced by repeated reliance on the unaffected limb." }],
  },
  {
    id: "ota-splinting",
    careerType: "occupationalTherapyAssistant",
    examTag: "NBCOT COTA",
    regionScope: "US",
    category: "Intervention",
    topic: "Orthosis Use, Skin Checks, and Wearing Schedules",
    bottomLine: "An orthosis must fit the therapeutic purpose without creating pressure, impaired circulation, nerve compression, pain, or skin injury; fit and wearing schedule require ongoing reassessment.",
    coreConcept: "Therapeutic positioning works only when forces are distributed safely and the client can use and monitor the device correctly.",
    recognition: "Persistent redness, numbness, tingling, swelling, pain, pressure areas, difficulty donning, or altered function indicates a fit or education problem.",
    workflow: "Verify the prescription/plan, inspect skin, apply orthosis correctly, check alignment and pressure, teach wear/care and warning signs, reassess after use, and communicate needed modification to the supervising OT.",
    interpretation: "Redness that does not resolve after device removal suggests excessive pressure and should not be normalized as expected wear.",
    safety: "Stop use and escalate when there is skin breakdown, neurovascular symptoms, severe pain, or device damage that changes alignment.",
    redFlags: "Blistering, open skin, pallor/cyanosis, numbness, severe swelling, or escalating pain requires immediate discontinuation and review.",
    commonErrors: "Tightening straps to stop migration without reassessing fit, ignoring persistent redness, and changing the orthosis design outside the plan/scope.",
    examFocus: "Know when to educate, when to modify within delegated parameters, and when to stop and consult the OT.",
    glossary: [{ term: "Orthosis", definition: "External device used to support, align, protect, prevent deformity, or assist function." }, { term: "Pressure area", definition: "Localized tissue stress from concentrated orthotic force or poor fit." }],
  },
  {
    id: "ota-pediatrics-sensory",
    careerType: "occupationalTherapyAssistant",
    examTag: "NBCOT COTA",
    regionScope: "US",
    category: "Pediatrics",
    topic: "Pediatric Sensory Regulation in Occupation",
    bottomLine: "Use sensory-informed strategies only when they are tied to a functional participation goal, individualized to observed response, and monitored for improved regulation rather than assumed from a diagnostic label.",
    coreConcept: "Sensory processing differences can alter arousal, attention, motor planning, feeding, dressing, play, and school participation, but response to input is individual and context dependent.",
    recognition: "Overresponsivity, sensory seeking, avoidance, shutdown, dysregulation, or difficulty transitioning may indicate that environmental or sensory demands are exceeding the child's current regulation capacity.",
    workflow: "Identify the occupation that is failing, observe triggers and successful conditions, select a simple strategy, implement within the routine, measure participation response, and adjust with the OT/family/team.",
    interpretation: "A child appearing calmer is useful only if the strategy improves safe participation and function in the target routine.",
    safety: "Avoid intense vestibular or other input when the child shows distress, pallor, nausea, disorientation, or worsening regulation.",
    redFlags: "Regression, loss of consciousness, seizure-like activity, severe feeding safety concern, or behavior suggesting medical rather than sensory cause requires escalation.",
    commonErrors: "Using the same sensory diet for every child, measuring success only by quiet behavior, and providing input without a functional goal.",
    examFocus: "NBCOT questions favor occupation-based, individualized, measurable strategies over generic sensory activities.",
    glossary: [{ term: "Sensory regulation", definition: "Ability to organize responses to sensory input in a way that supports functional arousal and participation." }, { term: "Overresponsivity", definition: "Disproportionately strong or aversive response to sensory input." }],
  },
  {
    id: "ota-ethics-scope",
    careerType: "occupationalTherapyAssistant",
    examTag: "NBCOT COTA",
    regionScope: "US",
    category: "Professional Practice",
    topic: "COTA Scope, Supervision, and Ethical Escalation",
    bottomLine: "Carry out delegated intervention within competence and supervision requirements, report meaningful changes, and defer evaluation, plan-of-care modification, and other OT-only decisions when required by law or policy.",
    coreConcept: "Safe delegation depends on client complexity, practitioner competence, supervision access, and clear accountability rather than task convenience.",
    recognition: "New goals, major status change, unexpected decline, need for discharge decision, intervention outside competence, or ethical conflict requires OT involvement.",
    workflow: "Clarify the plan and delegated task, confirm competence, deliver intervention, document response objectively, report changes promptly, and seek supervision before acting outside the established plan.",
    interpretation: "A request from another team member does not expand COTA scope or replace required OT supervision.",
    safety: "Do not independently alter goals or perform an unfamiliar high-risk intervention because scheduling or staffing makes consultation inconvenient.",
    redFlags: "Serious safety change, suspected abuse, major functional decline, conflict of interest, falsification request, or instruction outside scope requires immediate escalation.",
    commonErrors: "Treating routine familiarity as independent authority, delaying communication of decline, and documenting conclusions beyond observed performance.",
    examFocus: "When the scenario changes the plan rather than carrying it out, consultation with the OT is often the key step.",
    glossary: [{ term: "Delegation", definition: "Assignment of an intervention or task within legal scope and supervision structure." }, { term: "Supervision", definition: "Required professional oversight that supports safe and competent service delivery." }],
  },

  {
    id: "pta-gait-training",
    careerType: "physiotherapyAssistant",
    examTag: "FSBPT PTA",
    regionScope: "US",
    category: "Interventions",
    topic: "Gait Training With Assistive Devices",
    bottomLine: "Fit the device correctly, select the prescribed gait pattern, guard on the appropriate side, protect weight-bearing precautions, and progress only when balance and sequencing are safe.",
    coreConcept: "Assistive devices change base of support and load distribution; correct height and sequence are essential to reduce falls and protect healing tissue.",
    recognition: "Poor device placement, leaning through axillae, unsafe cadence, loss of prescribed weight-bearing, foot drag, or repeated sequencing errors indicates need for correction or more assistance.",
    workflow: "Confirm weight-bearing status and device, fit handles, teach sequence, position gait belt and guarding, practice level surfaces, add turns/obstacles/stairs as appropriate, and reassess fatigue and safety.",
    interpretation: "A faster gait is not progress if the patient sacrifices precautions, toe clearance, or balance.",
    safety: "Never progress to a less supportive device solely because the patient requests it; follow the PT plan and objective performance.",
    redFlags: "New dizziness, chest pain, acute shortness of breath, new weakness, repeated knee buckling, or inability to maintain precautions requires stopping and reassessment.",
    commonErrors: "Fitting crutches into the axilla, guarding from a poor position, and advancing stairs before level gait is safe.",
    examFocus: "FSBPT questions test device fit, sequence, weight-bearing status, and guarding position.",
    glossary: [{ term: "Weight-bearing status", definition: "Amount of load permitted through an extremity during mobility." }, { term: "Gait belt", definition: "Safety belt used to assist and guard a patient during transfers or ambulation." }],
  },
  {
    id: "pta-transfer-safety",
    careerType: "physiotherapyAssistant",
    examTag: "FSBPT PTA",
    regionScope: "US",
    category: "Interventions",
    topic: "Transfers, Bed Mobility, and Fall Prevention",
    bottomLine: "Choose the transfer method from strength, balance, cognition, precautions, lines, and environment; set up before moving and use enough assistance to prevent a fall.",
    coreConcept: "Most transfer failures are setup and judgment failures before they are strength failures.",
    recognition: "Poor sitting balance, impulsivity, orthostatic symptoms, inability to follow commands, lower-extremity buckling, or new pain increases transfer risk.",
    workflow: "Review precautions, lock equipment, clear obstacles, position surfaces, apply gait belt when appropriate, explain the sequence, guard the weak side, execute the transfer, and reassess symptoms.",
    interpretation: "A transfer completed with unsafe momentum or near-fall is not independent performance.",
    safety: "If the patient becomes unstable, use trained fall-management technique and call for help rather than trying to hold body weight with poor mechanics.",
    redFlags: "Syncope, new neurologic deficit, severe orthostatic hypotension, unstable fracture signs, or inability to safely bear weight requires immediate reassessment.",
    commonErrors: "Leaving wheelchair brakes unlocked, pulling on arms, failing to manage lines, and attempting a one-person transfer when two-person or mechanical assistance is indicated.",
    examFocus: "Prioritize setup and the safest assistance level over speed or patient preference.",
    glossary: [{ term: "Stand-pivot transfer", definition: "Transfer in which a patient rises to standing, pivots, and sits on another surface." }, { term: "Mechanical lift", definition: "Powered or manual device used to transfer patients who cannot safely perform sufficient active transfer." }],
  },
  {
    id: "pta-therapeutic-exercise",
    careerType: "physiotherapyAssistant",
    examTag: "FSBPT PTA",
    regionScope: "US",
    category: "Interventions",
    topic: "Therapeutic Exercise Progression",
    bottomLine: "Progress exercise according to the PT plan, tissue healing, movement quality, symptoms, and objective response rather than simply adding resistance each session.",
    coreConcept: "Exercise dose includes mode, intensity, volume, frequency, rest, range, speed, and complexity; changing any one can increase physiologic or mechanical demand.",
    recognition: "Substitution patterns, escalating pain, swelling, loss of form, breath holding, delayed recovery, or declining performance suggest excessive dose or need for modification.",
    workflow: "Confirm goals and precautions, establish baseline response, teach correct movement, monitor symptoms/vitals as appropriate, progress one variable, reassess quality, and report unexpected response.",
    interpretation: "Postexercise soreness may be expected in some contexts, but sharp pain, joint swelling, neurologic symptoms, or prolonged functional decline is not routine training response.",
    safety: "Do not independently exceed post-op restrictions or change an exercise category that requires PT reassessment.",
    redFlags: "Chest pain, syncope, new neurologic symptoms, acute joint instability, severe pain, or sudden swelling requires stopping and escalation.",
    commonErrors: "Progressing resistance despite poor form, treating pain as proof of effectiveness, and changing multiple dose variables simultaneously.",
    examFocus: "Choose a progression that preserves movement quality and respects healing/precautions.",
    glossary: [{ term: "Therapeutic exercise", definition: "Planned physical activity prescribed to address impairments, activity limits, and function." }, { term: "Exercise dose", definition: "Combined intensity, volume, frequency, duration, and other variables that determine exercise stress." }],
  },
  {
    id: "pta-cardiopulmonary-monitoring",
    careerType: "physiotherapyAssistant",
    examTag: "FSBPT PTA",
    regionScope: "US",
    category: "Safety",
    topic: "Vital-Sign and Cardiopulmonary Monitoring During Therapy",
    bottomLine: "Use symptoms plus vital-sign trends to judge exercise tolerance, stop for concerning changes, and escalate rather than pushing through physiologic instability.",
    coreConcept: "Heart rate, blood pressure, oxygen saturation, respiratory rate, perceived exertion, skin signs, and symptoms together reflect response to activity.",
    recognition: "Disproportionate dyspnea, chest discomfort, pallor, diaphoresis, dizziness, confusion, abnormal blood pressure response, or significant desaturation is concerning.",
    workflow: "Obtain baseline when indicated, select activity, monitor appropriate variables, ask about symptoms, stop or modify for abnormal response, allow recovery, recheck, and communicate unexpected findings.",
    interpretation: "A single device reading should be verified when inconsistent with the patient, but clinical deterioration should not be ignored while troubleshooting equipment.",
    safety: "Do not continue exercise solely to meet a time or distance goal when warning symptoms are developing.",
    redFlags: "Chest pain, syncope, severe desaturation, new arrhythmia symptoms, marked hypotension, or acute neurologic change requires immediate stop and emergency response as indicated.",
    commonErrors: "Watching the monitor instead of the patient, ignoring symptoms with 'normal' numbers, and failing to document recovery after stopping activity.",
    examFocus: "FSBPT scenarios prioritize the response to abnormal exercise tolerance over completion of the intervention.",
    glossary: [{ term: "Perceived exertion", definition: "Patient-reported estimate of effort used alongside physiologic measures during activity." }, { term: "Orthostatic hypotension", definition: "Blood pressure fall with position change that may cause dizziness, weakness, or syncope." }],
  },
  {
    id: "pta-neuro-stroke",
    careerType: "physiotherapyAssistant",
    examTag: "FSBPT PTA",
    regionScope: "US",
    category: "Neuromuscular",
    topic: "Stroke Mobility and Motor Control",
    bottomLine: "Train functional movement with safe alignment, task-specific repetition, appropriate cueing, and attention to neglect, tone, sensation, and fatigue while following the PT plan.",
    coreConcept: "Post-stroke mobility is shaped by weakness, motor control, sensory loss, tone, balance, cognition, and perceptual deficits rather than strength alone.",
    recognition: "Knee hyperextension, poor foot clearance, pushing behavior, neglect, impulsivity, abnormal synergy, or declining performance with fatigue changes intervention strategy.",
    workflow: "Assess current function within the plan, set up alignment and support, practice meaningful mobility, cue selectively, provide enough repetitions without sacrificing quality, reassess carryover, and report new deficits.",
    interpretation: "More assistance may be needed when cognition or neglect makes a physically capable movement unsafe.",
    safety: "Protect the affected shoulder and avoid unsafe pulling; use guarding and device setup appropriate to neglect and balance deficits.",
    redFlags: "New focal weakness, sudden severe headache, new speech change, acute loss of balance, or rapid neurologic decline requires emergency escalation.",
    commonErrors: "Overcueing every movement, focusing on isolated strength without functional practice, and treating neglect as a simple vision problem.",
    examFocus: "Choose task-specific mobility training while recognizing when a new neurologic finding is not part of routine recovery.",
    glossary: [{ term: "Neglect", definition: "Failure to attend to stimuli on one side of space, commonly after hemispheric stroke." }, { term: "Motor synergy", definition: "Stereotyped coupled movement pattern that may limit selective motor control after neurologic injury." }],
  },
  {
    id: "pta-orthopedic-precautions",
    careerType: "physiotherapyAssistant",
    examTag: "FSBPT PTA",
    regionScope: "US",
    category: "Musculoskeletal",
    topic: "Postoperative Orthopedic Precautions",
    bottomLine: "Know the surgeon/PT-specific movement and weight-bearing precautions, integrate them into transfers and exercise, and stop when pain, instability, wound concerns, or neurovascular changes suggest complication.",
    coreConcept: "Precautions protect healing tissue during a period when function may improve faster than biologic strength.",
    recognition: "Unexpected swelling, wound drainage, fever, calf pain, sudden loss of function, severe pain, paresthesia, or inability to maintain weight-bearing status can signal complication.",
    workflow: "Confirm procedure and current orders, teach precautions, set up mobility, perform prescribed exercises, monitor wound/limb response within scope, reinforce equipment use, and report abnormal findings.",
    interpretation: "A patient feeling better does not independently remove restrictions; progression follows updated medical/PT direction.",
    safety: "Do not improvise around unclear precautions—clarify before treatment.",
    redFlags: "Suspected DVT/PE, wound dehiscence, infection signs, new neurovascular deficit, dislocation signs, or acute fracture concern requires immediate escalation.",
    commonErrors: "Using generic precautions without checking procedure-specific orders and advancing weight bearing based on tolerance alone.",
    examFocus: "The safest answer respects current restrictions and recognizes complications early.",
    glossary: [{ term: "Weight-bearing precaution", definition: "Restriction defining how much load may be placed through a healing limb." }, { term: "Neurovascular status", definition: "Assessment of circulation, sensation, and motor function distal to an injury or procedure." }],
  },
  {
    id: "pta-professional-scope",
    careerType: "physiotherapyAssistant",
    examTag: "FSBPT PTA",
    regionScope: "US",
    category: "Professional Responsibilities",
    topic: "PTA Scope, Supervision, and Plan-of-Care Changes",
    bottomLine: "Implement the PT plan, collect relevant data, progress interventions within delegated parameters, and involve the PT when goals, diagnosis, major status changes, or plan-of-care decisions require reevaluation.",
    coreConcept: "PTA autonomy exists within the established plan and legal supervision framework; competence and patient complexity determine what can be safely delegated.",
    recognition: "Unexpected decline, plateau requiring new strategy, new diagnosis, major change in mobility, discharge question, or intervention outside competence requires PT communication.",
    workflow: "Review plan, confirm delegated intervention, treat and collect response data, document objective performance, communicate meaningful change, and await PT direction when the plan itself needs modification.",
    interpretation: "Progressing repetitions within allowed parameters differs from independently changing the therapeutic goal or selecting a new plan.",
    safety: "Do not continue an intervention that has become unsafe simply because it remains written in the prior plan.",
    redFlags: "Acute medical change, repeated adverse response, new contraindication, or request to act beyond legal scope requires immediate escalation.",
    commonErrors: "Confusing data collection with evaluation, delaying communication until the next scheduled visit, and changing goals without PT involvement.",
    examFocus: "FSBPT often tests whether the PTA should modify within plan, stop, or contact the PT.",
    glossary: [{ term: "Plan of care", definition: "PT-established treatment framework including goals, interventions, frequency, and progression parameters." }, { term: "Reevaluation", definition: "PT reassessment required when significant change may alter the plan of care." }],
  },

  {
    id: "surgtech-aseptic-technique",
    careerType: "surgicalTechnologist",
    examTag: "NBSTSA CST",
    regionScope: "US",
    category: "Perioperative Care",
    topic: "Aseptic Technique and Sterile Field Management",
    bottomLine: "Maintain the sterile field continuously, recognize contamination immediately, correct it without debate, and never allow workflow pressure to normalize an aseptic break.",
    coreConcept: "Sterility is binary at the point of contamination; uncertainty about a critical sterile item is managed as contamination.",
    recognition: "Contact with nonsterile surface, wet strike-through, dropped or compromised wrapper, field below waist or out of view, torn glove, or unsterile reach over the field is contamination.",
    workflow: "Inspect packaging, open and establish field correctly, monitor boundaries, pass and receive items without crossing contamination zones, replace contaminated items promptly, and communicate breaks immediately.",
    interpretation: "An item that cannot be verified as sterile is not made safe by wiping or relocating it within the field.",
    safety: "Speak up at the moment contamination occurs and replace the affected item or barrier before proceeding.",
    redFlags: "Major field contamination, glove puncture during implant handling, sterilization indicator failure, or unrecognized contamination discovered after use requires immediate team escalation.",
    commonErrors: "Turning away from an open sterile field, reaching over it, treating moisture as harmless, and hesitating to call contamination because surgery has started.",
    examFocus: "CST questions usually reward the action that restores sterility immediately.",
    glossary: [{ term: "Strike-through", definition: "Passage of microorganisms through a wet barrier from a nonsterile to sterile surface." }, { term: "Sterile field", definition: "Controlled area containing only items and surfaces maintained as sterile for a procedure." }],
  },
  {
    id: "surgtech-instrument-counts",
    careerType: "surgicalTechnologist",
    examTag: "NBSTSA CST",
    regionScope: "US",
    category: "Perioperative Care",
    topic: "Sponge, Sharps, and Instrument Counts",
    bottomLine: "Perform standardized counts with the circulating nurse at required times, reconcile discrepancies before closure when possible, and never alter documentation to make an incorrect count appear correct.",
    coreConcept: "Count systems prevent retained surgical items through redundancy, consistent sequencing, visual/audible verification, and immediate discrepancy response.",
    recognition: "Missing sponge, broken needle, unexpected instrument, emergency field change, staff handoff, or count interruption increases retained-item risk.",
    workflow: "Organize items, count audibly and visually with the circulator, document, maintain separation of counted items, repeat at required closure phases, stop and search for discrepancies, and follow imaging/escalation policy if unresolved.",
    interpretation: "A correct final count does not erase a known earlier discrepancy unless the cause is understood and all items are accounted for.",
    safety: "Do not allow closure to continue through an unexplained incorrect count without following the team's retained-item protocol.",
    redFlags: "Unresolved count, broken instrument with missing piece, missing needle, emergency conversion, or unplanned team turnover requires heightened reconciliation.",
    commonErrors: "Counting from memory, interrupting sequence, mixing counted and uncounted items, and changing the count sheet to match expectation.",
    examFocus: "Know count timing and the immediate sequence after a discrepancy.",
    glossary: [{ term: "Retained surgical item", definition: "Sponge, instrument, sharp, or other item unintentionally left in a patient after a procedure." }, { term: "Count discrepancy", definition: "Mismatch between expected and actual counted surgical items." }],
  },
  {
    id: "surgtech-positioning",
    careerType: "surgicalTechnologist",
    examTag: "NBSTSA CST",
    regionScope: "US",
    category: "Perioperative Care",
    topic: "Surgical Positioning and Pressure/Nerve Protection",
    bottomLine: "Position the patient for access while maintaining alignment, protecting pressure points and nerves, preserving ventilation/circulation, and securing the patient before table movement.",
    coreConcept: "Anesthetized patients cannot protect themselves from stretch, compression, shear, pressure, or impaired perfusion.",
    recognition: "Extreme arm abduction, pressure on fibular head, unsupported limbs, neck malalignment, excessive lithotomy changes, or sliding risk can cause preventable injury.",
    workflow: "Confirm planned position, coordinate team movement, pad pressure points, align joints, protect eyes and nerves, secure without impairing circulation, reassess after table changes, and document required elements.",
    interpretation: "More surgical exposure is not automatically safer if it requires excessive nerve stretch or compromises cardiopulmonary function.",
    safety: "Never reposition an anesthetized patient without coordinated control of airway, lines, limbs, and the surgical field.",
    redFlags: "Loss of airway access, sudden hemodynamic change after positioning, limb ischemia signs, equipment instability, or pressure on vulnerable nerve areas requires immediate correction.",
    commonErrors: "Tucking arms without checking fingers/IV lines, overabducting shoulders, and failing to reassess after table tilt.",
    examFocus: "Match common positions with the nerves and pressure areas most at risk.",
    glossary: [{ term: "Pressure injury", definition: "Localized tissue damage caused by prolonged pressure or pressure combined with shear." }, { term: "Positioning injury", definition: "Nerve, skin, musculoskeletal, or physiologic harm caused by operative positioning." }],
  },
  {
    id: "surgtech-electrosurgery",
    careerType: "surgicalTechnologist",
    examTag: "NBSTSA CST",
    regionScope: "US",
    category: "Equipment",
    topic: "Electrosurgery Safety",
    bottomLine: "Use electrosurgical equipment with correct setup, intact insulation, appropriate return-electrode practices for monopolar systems, fire-risk awareness, and immediate response to unintended energy injury.",
    coreConcept: "Electrical energy can injure tissue through alternate pathways, insulation failure, coupling, poor return contact, or ignition of fuels in an oxygen-enriched environment.",
    recognition: "Damaged insulation, pooled prep solution, high oxygen concentration near the field, poor return-pad site, unexpected burn, or arcing suggests increased hazard.",
    workflow: "Inspect equipment, verify mode and accessories, place return electrode appropriately when required, keep active electrode secured when not in use, manage fire triangle risks, announce activation near oxygen-rich fields, and investigate alarms.",
    interpretation: "Increasing power to overcome poor effect can worsen injury if the real problem is bad contact, damaged instrument, or incorrect setup.",
    safety: "Stop energy use when equipment integrity or patient return pathway is uncertain.",
    redFlags: "Fire, unexpected patient burn, return-electrode alarm, visible insulation defect, or ignition near airway requires immediate emergency response.",
    commonErrors: "Placing active electrode on drapes, using excessive power, ignoring insulation defects, and failing to coordinate around supplemental oxygen.",
    examFocus: "CST items often test the first prevention step for burns or surgical fire.",
    glossary: [{ term: "Monopolar electrosurgery", definition: "Electrosurgical circuit in which current travels from active electrode through patient to a return electrode." }, { term: "Insulation failure", definition: "Break in protective coating that permits unintended energy transfer to adjacent tissue." }],
  },
  {
    id: "surgtech-specimen-handling",
    careerType: "surgicalTechnologist",
    examTag: "NBSTSA CST",
    regionScope: "US",
    category: "Perioperative Care",
    topic: "Surgical Specimen Identification and Handling",
    bottomLine: "Preserve specimen identity, orientation, medium, labeling, and chain of custody from field to transfer; clarify uncertainties before the specimen leaves controlled handling.",
    coreConcept: "A correctly removed specimen can become diagnostically useless or dangerously misidentified through labeling or preservation error.",
    recognition: "Multiple specimens, frozen section, fresh tissue request, culture, forensic specimen, laterality/orientation markers, or conflicting labels require heightened verification.",
    workflow: "Confirm specimen with surgeon and circulator, keep specimens separated, state site/laterality and sequence, use correct container/medium, label per policy, document handoff, and protect chain of custody when required.",
    interpretation: "Formalin is appropriate for many pathology specimens but not for all cultures, frozen sections, or special studies; specimen destination determines handling.",
    safety: "Never relabel a specimen from memory after identity is uncertain; stop and resolve with the operative team.",
    redFlags: "Unlabeled specimen, mismatch between container and operative site, lost orientation marker, wrong preservative, or forensic custody break requires immediate escalation.",
    commonErrors: "Combining separately designated specimens, using routine preservative for culture, and sending before verbal verification.",
    examFocus: "Choose the handling method based on specimen purpose and preserve identity above convenience.",
    glossary: [{ term: "Frozen section", definition: "Rapid intraoperative pathology examination of fresh tissue that requires special handling rather than routine fixation." }, { term: "Chain of custody", definition: "Documented control of a specimen or item from collection through transfer, especially for forensic material." }],
  },
  {
    id: "surgtech-sterilization",
    careerType: "surgicalTechnologist",
    examTag: "NBSTSA CST",
    regionScope: "US",
    category: "Sterilization",
    topic: "Sterilization Indicators and Load Release",
    bottomLine: "Sterilization is a validated process verified by physical, chemical, and biologic monitoring as applicable; a failed indicator or compromised package means the item cannot be assumed sterile.",
    coreConcept: "Cleaning is required before sterilization because organic material and poor device preparation can prevent sterilant contact.",
    recognition: "Wet pack, torn wrapper, failed chemical indicator, failed biologic indicator, wrong cycle, overloaded chamber, or missing documentation invalidates confidence in sterility.",
    workflow: "Clean and inspect devices, package correctly, load according to process, run validated cycle, review physical parameters and indicators, allow proper drying/cooling, release only when criteria are met, and quarantine affected loads after failures.",
    interpretation: "External tape shows exposure to a process, not proof that sterilizing conditions reached every item.",
    safety: "Do not use an item because the case is urgent if sterility cannot be verified; obtain a verified alternative or follow emergency policy.",
    redFlags: "Biologic indicator failure, wet loads, sterilizer malfunction, implant load concern, or recall of previously released items requires immediate escalation.",
    commonErrors: "Confusing disinfection with sterilization, using flash/immediate-use processing for convenience, and treating one indicator as proof of the entire process.",
    examFocus: "Know what each indicator tells you and what to do after failure.",
    glossary: [{ term: "Biologic indicator", definition: "Test system containing resistant microorganisms used to challenge and monitor a sterilization process." }, { term: "Chemical indicator", definition: "Indicator that changes in response to one or more sterilization process parameters." }],
  },
];
