import type { AlliedAuthoredTopic } from "./types";

const EXAM = "ARDMS Abdomen | Sonography Canada Generalist";

export const diagnosticSonographyAbdominalTopics11: AlliedAuthoredTopic[] = [
  {
    id: "dms-abd-liver-diffuse",
    careerType: "diagnosticMedicalSonography", examTag: EXAM, regionScope: "BOTH",
    category: "Abdominal Sonography", topic: "Liver Anatomy and Diffuse Parenchymal Disease",
    bottomLine: "Evaluate hepatic size, contour, echotexture, echogenicity, vessels, and extrahepatic consequences together; diffuse liver disease is a pattern diagnosis, and a bright liver alone neither proves steatosis nor excludes fibrosis, inflammation, or infiltrative disease.",
    coreConcept: "Normal portal and hepatic venous landmarks define segments and lobes. Steatosis increases attenuation and echogenicity, chronic fibrosis remodels parenchyma and contour, and portal hypertension produces vascular and collateral consequences that may be more specific than coarse echotexture.",
    recognition: "Steatosis commonly produces hepatorenal contrast, vascular blurring, posterior attenuation, and focal sparing; cirrhosis may produce nodular surface, heterogeneous coarse texture, altered lobe proportions, splenomegaly, ascites, recanalized paraumbilical vein, and abnormal portal flow.",
    workflow: "Survey in orthogonal planes, compare liver with renal cortex only when the kidney is suitable, assess diaphragm and deep-vessel visibility, inspect surface and lobar proportions, evaluate portal and hepatic veins, search for ascites and collaterals, and document focal abnormalities separately.",
    interpretation: "Increased echogenicity is nonspecific and comparison is unreliable with medical renal disease. A smooth liver without ascites does not exclude compensated chronic liver disease, while surface nodularity and portal-hypertension signs substantially change the assessment.",
    safety: "Use multiple windows and lower frequency when attenuation hides the dome; document incomplete visualization rather than calling unseen parenchyma normal, and communicate new ascites, portal thrombosis, or suspicious focal lesions according to protocol.",
    redFlags: "New portal-vein thrombosis, reversed portal flow, marked ascites, a suspicious mass in cirrhosis, biliary obstruction, or decompensated clinical features requires prompt correlation and escalation.",
    commonErrors: "Common errors are diagnosing steatosis from brightness alone, comparing with an abnormal kidney, calling cirrhosis from coarse texture alone, mistaking focal fat for a mass, and omitting Doppler or portal-hypertension survey.",
    examFocus: "Differentiate diffuse patterns, recognize segmental landmarks and focal fat distributions, and select the finding most specific for portal hypertension or advanced chronic liver disease.",
    glossary: [{ term: "Hepatorenal contrast", definition: "Relative increase in liver echogenicity compared with renal cortex, used cautiously as one sign of steatosis." }, { term: "Focal sparing", definition: "Region of relatively normal liver within diffuse fatty infiltration that may mimic a hypoechoic lesion." }],
  },
  {
    id: "dms-abd-liver-focal",
    careerType: "diagnosticMedicalSonography", examTag: EXAM, regionScope: "BOTH",
    category: "Abdominal Sonography", topic: "Focal Liver Lesion Characterization",
    bottomLine: "Characterize a focal liver finding by number, location, border, echogenicity, internal architecture, posterior behavior, vascular pattern, background liver, and clinical context; ultrasound can identify classic benign patterns but often cannot provide final histology.",
    coreConcept: "Cysts transmit sound, calcification and gas attenuate, vascular lesions reflect blood-filled interfaces, and malignant lesions vary with necrosis, fibrosis, fat, and perfusion. Pretest risk changes the significance of the same appearance, especially in cirrhosis or known malignancy.",
    recognition: "A simple cyst is anechoic with a thin wall, enhancement, and no flow; a typical hemangioma is well-defined and echogenic but may be atypical; metastases can be multiple and variable; hepatocellular carcinoma can be heterogeneous with vascular invasion in a high-risk liver.",
    workflow: "Confirm the finding in two planes, distinguish true lesion from vessel or focal fat, measure reproducibly, document segment and relation to landmarks, assess internal and peripheral flow without overgaining, examine the remainder of liver and portal veins, and compare prior imaging.",
    interpretation: "No single grayscale feature reliably separates all benign and malignant lesions. Stability, risk factors, multiplicity, vascular invasion, growth, and concordant CT, MRI, or contrast-enhanced ultrasound information determine next steps.",
    safety: "Do not label an indeterminate solid lesion benign from echogenicity alone. Preserve representative cine and Doppler data, avoid excessive pressure over a painful lesion, and trigger the appropriate follow-up pathway.",
    redFlags: "Tumor thrombus, a new or enlarging solid lesion in cirrhosis, multiple lesions in a patient with cancer, internal hemorrhage, or a complex cystic lesion with mural nodularity requires expedited review.",
    commonErrors: "Common errors are confusing a vessel for a cyst, diagnosing hemangioma solely because a lesion is bright, missing an isoechoic mass that displaces vessels, measuring in inconsistent planes, and ignoring the background liver.",
    examFocus: "Expect integration questions that distinguish classic simple cyst criteria, pseudolesions, hemangioma patterns, metastases, abscess, and high-risk features rather than asking for histology from one isolated sign.",
    glossary: [{ term: "Target lesion", definition: "Mass with concentric echogenic and hypoechoic components; a nonspecific pattern often associated with metastasis." }, { term: "Tumor thrombus", definition: "Intravascular extension of neoplasm, sometimes showing internal vascularity and vessel expansion." }],
  },
  {
    id: "dms-abd-hepatic-doppler",
    careerType: "diagnosticMedicalSonography", examTag: EXAM, regionScope: "BOTH",
    category: "Abdominal Vascular Sonography", topic: "Portal, Hepatic, and Transplant Doppler",
    bottomLine: "Interpret hepatic Doppler as a connected inflow-outflow circuit: main portal flow should be toward the liver, hepatic veins drain toward the heart with cardiac phasicity, and hepatic arterial resistance must be assessed with waveform quality and clinical timing.",
    coreConcept: "Portal pressure, hepatic resistance, right-heart pressure, respiration, collateral pathways, thrombosis, stenosis, and transplant anastomoses alter direction, velocity, phasicity, and resistance. A technically poor angle or excessive transducer pressure can mimic disease.",
    recognition: "Hepatofugal portal flow, absent or cavernomatous portal lumen, focal aliasing with velocity change at an anastomosis, damped hepatic venous phasicity, tardus-parvus arterial flow, or absent diastolic arterial flow may indicate important pathology in context.",
    workflow: "Confirm vessel identity in grayscale and color, record direction and waveform from the main and intrahepatic portal veins, hepatic veins, IVC, and hepatic artery, apply angle correction for velocities, compare prestenotic and stenotic segments, and follow transplant-specific protocols and baselines.",
    interpretation: "A single velocity threshold rarely stands alone. Diagnose stenosis from focal narrowing, color disturbance, velocity ratio, downstream effect, and reproducibility; interpret arterial resistance by postoperative timing because early transient changes may differ from persistent deterioration.",
    safety: "Minimize pressure that can collapse veins or alter portal velocity, use sterile technique for immediate postoperative wounds as required, and communicate absent transplant flow or acute thrombosis immediately.",
    redFlags: "Absent hepatic arterial flow after transplant, new portal or hepatic-vein thrombosis, flow reversal, a severe anastomotic velocity shift with downstream dampening, or IVC outflow obstruction requires urgent escalation.",
    commonErrors: "Common errors are reversing the color map mentally, confusing hepatic artery with portal branch, measuring without angle correction, calling stenosis from aliasing alone, and applying nontransplant expectations to an early transplant study.",
    examFocus: "Know normal vessel directions and waveform morphology, portal-hypertension changes, thrombosis and cavernous transformation, Budd-Chiari patterns, and transplant arterial, portal, venous, and biliary complications.",
    glossary: [{ term: "Hepatopetal", definition: "Blood flow directed toward the liver, normally describing portal venous flow." }, { term: "Cavernous transformation", definition: "Network of collateral channels that develops around a chronically occluded portal vein." }],
  },
  {
    id: "dms-abd-gallbladder",
    careerType: "diagnosticMedicalSonography", examTag: EXAM, regionScope: "BOTH",
    category: "Abdominal Sonography", topic: "Gallbladder Stones, Inflammation, and Polyps",
    bottomLine: "Diagnose gallbladder disease from concordant findings: mobility and shadowing establish typical stones, while acute cholecystitis requires inflammatory evidence and clinical correlation rather than wall thickness or tenderness alone.",
    coreConcept: "Calculi reflect and attenuate sound, obstruction raises intraluminal pressure, and inflammation produces wall edema, hyperemia, surrounding fluid, distention, and focal tenderness. Wall thickening is nonspecific and may result from systemic or adjacent disease.",
    recognition: "Stones are echogenic, mobile, and usually shadow; sludge layers and moves slowly without clean shadowing; adenomyomatosis can produce comet-tail artifact; polyps are attached nonshadowing lesions; acute cholecystitis may include an impacted neck stone and positive sonographic Murphy sign.",
    workflow: "Scan fasting when feasible, image supine and decubitus or upright, evaluate lumen, neck, wall, surrounding tissue, and common duct, use focal graded tenderness thoughtfully, assess vascularity when inflammation or a mass is suspected, and document mobility and shadowing.",
    interpretation: "Wall thickness over a simple threshold is not diagnostic in isolation. A negative Murphy sign may be unreliable after analgesia, with neuropathy, gangrene, or poor communication, and a contracted postprandial gallbladder can mimic wall disease.",
    safety: "Avoid forceful pressure in severe pain, recognize sepsis or perforation risk, and promptly communicate obstructing stones, emphysematous change, gangrene, perforation, or a suspicious mass.",
    redFlags: "Marked wall irregularity, intramural gas, sloughed membranes, pericholecystic collection, absent wall perfusion, impacted stone with worsening symptoms, or biliary dilation with jaundice requires urgent review.",
    commonErrors: "Common errors are mistaking bowel gas for stones, calling sludge a mass, diagnosing acute cholecystitis from wall thickening alone, failing to change position, and overlooking the gallbladder neck.",
    examFocus: "Differentiate stones, sludge, polyps, adenomyomatosis, porcelain gallbladder, chronic and acute cholecystitis, and complications by combining mobility, artifact, inflammation, and clinical data.",
    glossary: [{ term: "Sonographic Murphy sign", definition: "Maximal focal tenderness when the transducer directly compresses the visualized gallbladder." }, { term: "Wall-echo-shadow sign", definition: "Appearance of gallbladder wall, bright stone surface, and posterior shadow when the lumen is packed with stones." }],
  },
  {
    id: "dms-abd-biliary-tree",
    careerType: "diagnosticMedicalSonography", examTag: EXAM, regionScope: "BOTH",
    category: "Abdominal Sonography", topic: "Biliary Obstruction and Duct Evaluation",
    bottomLine: "When bile ducts are enlarged, determine the level and likely cause of obstruction by tracing intrahepatic ducts, common hepatic duct, common bile duct, porta hepatis, pancreatic head, and distal duct while integrating age, surgery, laboratory findings, and symptoms.",
    coreConcept: "Obstruction raises upstream duct pressure and produces dilation that depends on completeness, duration, compliance, and prior surgery. A duct diameter is contextual rather than universally abnormal, and early or intermittent obstruction may occur before marked dilation.",
    recognition: "Parallel-channel intrahepatic ducts, a dilated extrahepatic duct, an echogenic shadowing duct stone, abrupt taper, pancreatic-head mass, or intrahepatic-only dilation localizes different processes. Pneumobilia is branching and tends to be central with dirty artifact.",
    workflow: "Measure the duct inner-to-inner at a reproducible segment, confirm it is not the portal vein using color, follow it distally with graded compression and alternate positions, evaluate gallbladder and pancreas, inspect intrahepatic distribution, and compare prior studies and operative history.",
    interpretation: "A normal-caliber duct does not fully exclude an acute stone, and mild dilation may be physiologic after cholecystectomy or with age. Obstruction is stronger when ductal change, symptoms, laboratory abnormalities, and a visible cause agree.",
    safety: "Do not repeatedly compress a severely tender epigastrium, and promptly communicate obstructive findings with fever, jaundice, hypotension, or altered mental status because ascending cholangitis can deteriorate rapidly.",
    redFlags: "Charcot-type infectious features with obstruction, abrupt malignant-appearing cutoff, intrahepatic dilation with hilar lesion, pancreatic mass, or a duct stone with worsening jaundice requires expedited escalation.",
    commonErrors: "Common errors are measuring outer-to-outer, mistaking hepatic artery or portal vein for duct, assuming every enlarged duct contains a stone, ignoring prior cholecystectomy, and failing to examine the pancreatic head.",
    examFocus: "Localize obstruction from the distribution of dilation and distinguish choledocholithiasis, pancreatic or ampullary obstruction, hilar disease, pneumobilia, and normal postoperative variation.",
    glossary: [{ term: "Double-duct sign", definition: "Concurrent dilation of the common bile duct and pancreatic duct, raising concern for distal obstruction." }, { term: "Pneumobilia", definition: "Air within the biliary tree, producing echogenic branching foci with dirty shadow or reverberation." }],
  },
  {
    id: "dms-abd-pancreas",
    careerType: "diagnosticMedicalSonography", examTag: EXAM, regionScope: "BOTH",
    category: "Abdominal Sonography", topic: "Pancreatic Anatomy, Pancreatitis, and Masses",
    bottomLine: "Evaluate the pancreas by landmarks and consequences as well as direct visualization; bowel gas frequently limits the gland, so ductal dilation, biliary obstruction, vascular displacement, collections, and liver metastases may be decisive clues.",
    coreConcept: "The pancreas lies across the retroperitoneum with head in the duodenal curve, neck anterior to the portal confluence, body over the aorta and splenic vein, and tail toward the splenic hilum. Inflammation causes edema and fluid, while neoplasm can obstruct ducts and invade vessels.",
    recognition: "Acute pancreatitis may appear enlarged and hypoechoic with surrounding fluid but can be sonographically subtle; chronic disease may show calcification, duct irregularity, and atrophy; adenocarcinoma is often hypoechoic with ductal obstruction and contour change.",
    workflow: "Use epigastric transverse and longitudinal views, oral water or positional change when appropriate, identify splenic vein, portal confluence, SMA, aorta, and CBD, assess duct and gland contour, search for collections and vascular complications, and document nonvisualized segments.",
    interpretation: "Age, body habitus, fatty replacement, and equipment settings change echogenicity. Ultrasound is useful for biliary cause and complications of pancreatitis but a normal or incomplete examination does not exclude pancreatic disease.",
    safety: "Avoid aggressive prolonged pressure in acute abdominal pain, recognize unstable pancreatitis complications, and communicate a suspicious mass, pseudoaneurysm, venous thrombosis, or complex collection promptly.",
    redFlags: "A mass with double-duct obstruction, vascular encasement, portal or splenic-vein thrombosis, a pulsatile collection suggesting pseudoaneurysm, infected necrosis, or rapidly enlarging fluid collection requires urgent review.",
    commonErrors: "Common errors are mistaking stomach or lymph node for pancreas, calling fatty pancreas a mass, failing to use vascular landmarks, reporting unseen tail as normal, and assuming absent enlargement excludes acute pancreatitis.",
    examFocus: "Identify pancreatic parts by vascular landmarks and distinguish pancreatitis, pseudocyst, cystic neoplasm, adenocarcinoma, neuroendocrine tumor, and periampullary obstruction patterns.",
    glossary: [{ term: "Pseudocyst", definition: "Encapsulated pancreatic fluid collection with a mature wall and no epithelial lining, generally developing after pancreatitis." }, { term: "Portal confluence", definition: "Junction where the splenic and superior mesenteric veins form the portal vein behind the pancreatic neck." }],
  },
  {
    id: "dms-abd-spleen",
    careerType: "diagnosticMedicalSonography", examTag: EXAM, regionScope: "BOTH",
    category: "Abdominal Sonography", topic: "Spleen, Trauma, and Portal Hypertension",
    bottomLine: "Assess splenic size, contour, echotexture, hilum, vessels, and perisplenic spaces; splenomegaly is a sign with broad causes, while trauma and infarction require careful attention to contour, perfusion, free fluid, and clinical stability.",
    coreConcept: "The spleen filters blood and participates in immune and hematologic function. Congestion, infiltration, infection, hematologic disease, infarction, and trauma change size or texture, but subtle injury may be occult on ultrasound.",
    recognition: "Splenomegaly is best assessed with consistent long-axis technique; infarcts are often peripheral wedge-shaped hypoechoic areas with reduced perfusion; hematoma or laceration may distort contour or create heterogeneous regions and adjacent fluid.",
    workflow: "Scan through intercostal windows with respiration, measure in a true long axis, inspect diaphragm and left upper quadrant recesses, assess hilum and splenic vein, use Doppler for perfusion questions, and survey for ascites or collaterals when portal hypertension is suspected.",
    interpretation: "A normal-sized spleen does not exclude disease and size thresholds vary with body habitus and technique. In trauma, free fluid may be more evident than a parenchymal defect, and a negative focused examination cannot exclude injury in a stable patient with persistent concern.",
    safety: "Use gentle pressure after trauma or with marked splenomegaly, recognize hemodynamic instability, and stop routine measurements to communicate suspected rupture, active bleeding, or threatened perfusion.",
    redFlags: "Perisplenic free fluid after trauma, capsular disruption, expanding hematoma, absent or severely reduced perfusion, splenic-vein thrombosis, or a complex lesion with systemic infection requires urgent escalation.",
    commonErrors: "Common errors are measuring obliquely, including accessory spleen in the length, confusing pleural with peritoneal fluid, relying on negative ultrasound to exclude trauma, and interpreting every wedge-shaped region without Doppler confirmation.",
    examFocus: "Know normal landmarks, reliable measurement technique, accessory spleen, splenomegaly causes, infarction, abscess, trauma, and portal-hypertension associations.",
    glossary: [{ term: "Accessory spleen", definition: "Congenital focus of normal splenic tissue, commonly near the hilum or pancreatic tail." }, { term: "Splenic infarct", definition: "Region of ischemic splenic tissue, often peripheral and wedge shaped with reduced vascularity." }],
  },
  {
    id: "dms-abd-kidneys",
    careerType: "diagnosticMedicalSonography", examTag: EXAM, regionScope: "BOTH",
    category: "Abdominal Sonography", topic: "Renal Anatomy, Obstruction, and Parenchymal Disease",
    bottomLine: "Evaluate renal length, contour, cortical thickness and echogenicity, corticomedullary differentiation, sinus, collecting system, ureters when visible, bladder, and perfusion; hydronephrosis is collecting-system dilation, not automatically proof of mechanical obstruction.",
    coreConcept: "Urine production and drainage depend on renal perfusion, filtration, ureteral peristalsis, bladder pressure, and outlet patency. Obstruction produces pressure-dependent dilation, while reflux, pregnancy, a full bladder, and parapelvic cysts can mimic or cause nonobstructive dilation.",
    recognition: "Hydronephrosis produces communicating calyceal and pelvic fluid, stones may be echogenic with shadow or twinkle artifact, chronic disease may increase cortical echogenicity and reduce size, and acute processes can enlarge the kidney without marked echogenic change.",
    workflow: "Image each kidney in orthogonal planes, measure true long axis, compare cortex appropriately, assess collecting system and proximal/distal ureter, use color to separate vessels from fluid and evaluate jets, scan the bladder, change position or reassess after voiding when indicated.",
    interpretation: "Severity of dilation does not equal severity of functional impairment, and absence of a ureteral jet is nonspecific unless technique and observation time are adequate. Clinical symptoms, renal function, and complementary imaging guide significance.",
    safety: "Avoid delaying care in an infected obstructed system, solitary kidney, transplant, acute anuria, or severe pain with renal dysfunction. Communicate suspected pyonephrosis, acute bilateral obstruction, or vascular compromise promptly.",
    redFlags: "Hydronephrosis with fever and internal debris, absent perfusion, renal-vein thrombosis, obstructed solitary kidney, complex cyst with nodularity, or a solid vascular mass requires expedited assessment.",
    commonErrors: "Common errors are mistaking vessels or parapelvic cysts for hydronephrosis, measuring an oblique kidney, diagnosing medical renal disease from echogenicity alone, and calling obstruction from absent jet without adequate observation.",
    examFocus: "Differentiate obstructive from mimicking fluid patterns, acute from chronic parenchymal changes, simple from complex cysts, and recognize stones, infection, masses, congenital variants, and vascular emergencies.",
    glossary: [{ term: "Hydronephrosis", definition: "Dilation of the renal collecting system, which may be obstructive or nonobstructive." }, { term: "Twinkle artifact", definition: "Rapid color alternation behind a strongly reflecting rough interface, often supporting detection of a calculus." }],
  },
  {
    id: "dms-abd-bladder-prostate",
    careerType: "diagnosticMedicalSonography", examTag: EXAM, regionScope: "BOTH",
    category: "Abdominal Sonography", topic: "Bladder, Ureteral Jets, and Prostate Assessment",
    bottomLine: "A useful urinary-tract examination links bladder filling, wall and lumen findings, ureteral jets, pre- and post-void volumes, prostate size, kidneys, and symptoms; incomplete preparation or technique can create false wall thickening and unreliable residual measurements.",
    coreConcept: "Bladder shape and wall depend on distention, outlet resistance, detrusor function, inflammation, and adjacent pelvic anatomy. Residual volume reflects the balance of contractility and obstruction, while jet frequency varies with hydration and renal output.",
    recognition: "Trabeculation and diverticula suggest chronic pressure change, mobile dependent echoes may represent debris or clot, a stone is mobile and echogenic with shadowing, and a fixed vascular wall lesion is more concerning for tumor than uncomplicated debris.",
    workflow: "Confirm adequate but tolerable filling, image in transverse and longitudinal planes, evaluate wall, lumen, ureterovesical junctions, and jets, measure volume with consistent inner-wall dimensions, obtain post-void volume promptly, and assess prostate and upper tracts when indicated.",
    interpretation: "An underfilled bladder can look falsely thick-walled, absent jet during a short observation is not diagnostic of obstruction, and residual volume is time-sensitive because continued urine production increases the measured result.",
    safety: "Do not force prolonged bladder filling in severe pain or retention. Recognize acute retention, clot obstruction, infection with obstruction, and a suspicious vascular mass, and follow escalation protocols.",
    redFlags: "Large symptomatic residual, bilateral hydronephrosis with outlet obstruction, an immobile vascular bladder lesion, significant clot burden, emphysematous change, or suspected bladder rupture requires prompt review.",
    commonErrors: "Common errors are measuring outer walls, delaying the post-void scan, calling folds a mass in an underfilled bladder, assuming absent jets equal obstruction, and using prostate volume alone to infer symptom severity.",
    examFocus: "Expect volume calculation, preparation and timing questions, distinctions among clot, stone, ureterocele, diverticulum and tumor, and integration of outlet obstruction with upper-tract consequences.",
    glossary: [{ term: "Post-void residual", definition: "Urine volume remaining in the bladder measured promptly after voluntary voiding." }, { term: "Ureterocele", definition: "Cystic dilation of the distal ureter within the bladder, sometimes associated with duplicated collecting systems." }],
  },
  {
    id: "dms-abd-aorta-retroperitoneum",
    careerType: "diagnosticMedicalSonography", examTag: EXAM, regionScope: "BOTH",
    category: "Abdominal Sonography", topic: "Aorta, IVC, and Retroperitoneal Pathology",
    bottomLine: "Survey the aorta continuously from diaphragm to bifurcation, measure outer wall to outer wall perpendicular to its true axis, assess iliac arteries, and distinguish aneurysm, dissection, rupture, thrombus, lymphadenopathy, and adjacent masses from normal vascular and bowel structures.",
    coreConcept: "Aneurysmal dilation reflects wall degeneration and may contain mural thrombus without reducing total diameter. Rupture may track into retroperitoneal spaces, while dissection creates a mobile or fixed intimal flap separating flow channels.",
    recognition: "A fusiform or saccular enlarged aorta, mural thrombus, intimal flap with differential channel flow, periaortic hematoma, or loss of normal tissue planes is concerning. The IVC changes with volume, respiration, right-heart pressure, and obstruction.",
    workflow: "Use longitudinal and transverse imaging, sweep continuously, measure perpendicular to the vessel centerline, include the full outer diameter, evaluate bifurcation and common iliacs, apply color and spectral Doppler to suspected lumen abnormalities, and inspect retroperitoneal tissues.",
    interpretation: "Oblique measurement overestimates diameter, and excluding mural thrombus underestimates aneurysm size. A technically limited aorta is not a negative study; bowel gas and body habitus must be documented and alternate imaging considered.",
    safety: "Use minimal pressure over a painful pulsatile mass, do not delay emergency care to complete routine measurements, and immediately communicate suspected rupture, acute dissection, or thrombosed aneurysm with ischemic symptoms.",
    redFlags: "Hypotension with aneurysm, retroperitoneal fluid or hematoma, acute intimal flap, absent distal flow, rapidly expanding aneurysm, or IVC thrombosis extending toward the heart requires urgent escalation.",
    commonErrors: "Common errors are measuring inner-to-inner, measuring obliquely, excluding thrombus, confusing SMA with celiac axis, mistaking bowel for aneurysm, and reporting unseen segments as normal.",
    examFocus: "Know measurement conventions, aneurysm morphology and complications, dissection clues, rupture patterns, branch landmarks, IVC thrombosis, and retroperitoneal lymph-node relationships.",
    glossary: [{ term: "Mural thrombus", definition: "Thrombus attached to the vessel wall and contained within the total aneurysm diameter." }, { term: "Intimal flap", definition: "Separated inner arterial wall that may divide true and false lumens in dissection." }],
  },
];
