import type { AlliedAuthoredTopic } from "./types";

const EXAM = "ARDMS FE/RDCS Pediatric | Sonography Canada Cardiac";
const C = "Fetal and Pediatric Echocardiography";
const shared = { careerType: "diagnosticMedicalSonography", examTag: EXAM, regionScope: "BOTH", category: C } as const;

export const diagnosticSonographyFetalPediatricEchoTopics17: AlliedAuthoredTopic[] = [
  {
    ...shared, id: "dms-fetal-echo-screening", topic: "Fetal Cardiac Screening Views and Systematic Survey",
    bottomLine: "A reliable fetal cardiac survey establishes situs, cardiac position and axis, four-chamber anatomy, both outflow tracts, three-vessel-trachea view, arches, venous connections, rhythm and function; no single normal view excludes congenital heart disease.",
    coreConcept: "The fetal circulation uses the foramen ovale, ductus arteriosus and ductus venosus to direct oxygenated placental blood. Sequential imaging tests connections and proportionality rather than merely confirming four visible chambers.",
    recognition: "Normal findings include levocardia, balanced chambers, intact crux, crossing great arteries and leftward ductal and aortic arches. Axis deviation, disproportion, abnormal vessel number or alignment, cardiomegaly, effusion or hydrops warrants targeted evaluation.",
    workflow: "Confirm fetal lie and situs, optimize frequency and frame rate, sweep from abdomen through four chamber, outflows and three-vessel-trachea plane, add sagittal arches and systemic and pulmonary venous views, document rate, rhythm and function, and repeat limited planes after fetal repositioning.",
    interpretation: "A technically incomplete survey is indeterminate, not normal. Gestational age, fetal position, maternal habitus and motion affect visualization; subtle lesions such as coarctation or anomalous pulmonary venous return may evolve or remain difficult prenatally.",
    safety: "Apply ALARA, minimize spectral Doppler dwell and output, monitor thermal and mechanical indices, and refer rather than prolonging a nondiagnostic examination without clinical benefit.",
    redFlags: "Sustained bradycardia or tachycardia, hydrops, severe ventricular dysfunction, absent normal outflow crossing, major disproportion or suspected ductal restriction requires prompt fetal-medicine or pediatric-cardiology escalation.",
    commonErrors: "Calling a survey complete from four chambers alone, reversing situs, mistaking pulmonary artery bifurcation for aortic arch, excessive Doppler exposure and reporting unseen anatomy as normal are preventable errors.",
    examFocus: "Know screening planes, sequential segmental analysis, normal fetal shunts, cardiac axis, vessel relationships, image optimization and limits of prenatal detection.",
    glossary: [{ term: "Three-vessel-trachea view", definition: "Transverse upper-mediastinal plane showing pulmonary artery, ascending aorta and superior vena cava in relation to the trachea." }, { term: "Cardiac axis", definition: "Angle of the interventricular septum or long cardiac axis relative to the fetal thorax." }],
  },
  {
    ...shared, id: "dms-fetal-situs-segments", topic: "Fetal Situs and Sequential Segmental Cardiac Anatomy",
    bottomLine: "Name fetal cardiac anatomy only after establishing atrial arrangement, ventricular morphology, atrioventricular connections, ventriculoarterial connections and great-vessel position in sequence.",
    coreConcept: "Morphology—not right-left screen position—identifies chambers: the morphologic right ventricle has coarse trabeculation and a moderator band, while atrial arrangement follows appendage morphology and systemic venous relationships.",
    recognition: "Determine stomach and descending aorta laterality, IVC relationship, cardiac position and apex direction, then trace inflow and outflow. Discordant connections, bilateral caval patterns or interrupted IVC may accompany heterotaxy.",
    workflow: "Orient the fetus, label maternal and fetal sides, document abdominal situs, venous return, atrial and ventricular morphology, valve offset, outflow origins and arch sidedness, proving each connection with cine sweeps and color Doppler where useful.",
    interpretation: "Dextroposition from extracardiac mass differs from intrinsic dextrocardia; situs ambiguous cannot be forced into situs solitus or inversus. Connection-based description remains valid even when a complete diagnosis is uncertain.",
    safety: "Limit exposure and communicate uncertain or complex arrangement clearly so delivery planning is based on verified connections rather than an unsupported lesion label.",
    redFlags: "Heterotaxy with heart block, obstructed venous return, single-ventricle physiology, severe outflow obstruction or hydrops requires urgent multidisciplinary assessment.",
    commonErrors: "Using screen side as anatomy, identifying ventricles only by position, skipping venous return, confusing dextroposition with dextrocardia and naming a lesion before tracing connections cause major diagnostic errors.",
    examFocus: "Apply sequential segmental terminology, chamber morphology, situs solitus/inversus/ambiguous, levocardia/dextrocardia, concordance and discordance.",
    glossary: [{ term: "Atrioventricular concordance", definition: "Connection of morphologic right atrium to right ventricle and morphologic left atrium to left ventricle." }, { term: "Heterotaxy", definition: "Abnormal arrangement of thoracoabdominal organs across the left-right axis, often with complex venous and cardiac connections." }],
  },
  {
    ...shared, id: "dms-fetal-septal-avsd", topic: "Fetal Septal Defects and Atrioventricular Septal Defect",
    bottomLine: "Evaluate septa in multiple planes and distinguish normal fetal communications and artifact from true defects; atrioventricular septal defect is recognized at the crux by a common junction and abnormal valve anatomy rather than color dropout alone.",
    coreConcept: "The foramen ovale is physiologic before birth, small muscular ventricular defects may be occult, and endocardial-cushion maldevelopment produces atrial and ventricular septal deficiency with common or separate abnormal atrioventricular valves.",
    recognition: "A true VSD persists in orthogonal views with shunt flow; complete AVSD shows absent normal offset, a common valve and inlet septal defects. Primum defects lie adjacent to the atrioventricular valves and often accompany chromosomal or heterotaxy syndromes.",
    workflow: "Use an apical four-chamber view to reduce septal dropout, sweep through inlet, membranous and muscular septa, use appropriately scaled color without blooming, assess valve insertion and regurgitation, chamber balance and associated anomalies.",
    interpretation: "Apical septal dropout is artifact until proven otherwise, and prenatal shunt direction does not predict postnatal magnitude because fetal pressures are similar. AVSD severity depends on balance, valve regurgitation and associated obstruction.",
    safety: "Avoid unnecessary prolonged Doppler interrogation and promptly communicate unbalanced AVSD, severe valve regurgitation or associated heart block for delivery and neonatal planning.",
    redFlags: "Unbalanced ventricles, severe common-valve regurgitation, hydrops, complete heart block or associated obstructed venous return requires expedited specialist review.",
    commonErrors: "Diagnosing VSD from one dropout view, calling the foramen ovale an ASD, missing valve-level abnormality and assuming a small prenatal color jet defines postnatal significance are common traps.",
    examFocus: "Differentiate physiologic foramen ovale, ASD types, VSD locations, complete and partial AVSD, balanced versus unbalanced anatomy and artifact.",
    glossary: [{ term: "Crux", definition: "Central junction of atrial septum, ventricular septum and atrioventricular valves." }, { term: "Unbalanced AVSD", definition: "Atrioventricular septal defect in which the common junction preferentially connects to one ventricle, producing ventricular size imbalance." }],
  },
  {
    ...shared, id: "dms-fetal-conotruncal", topic: "Fetal Outflow and Conotruncal Anomalies",
    bottomLine: "Determine which ventricle gives rise to each great artery, whether the vessels cross, their relative size and the presence of obstruction; abnormal connections must be described before assigning a named conotruncal diagnosis.",
    coreConcept: "Conotruncal development separates and spirals the outflow tract. Malalignment may produce tetralogy of Fallot, transposition, double-outlet right ventricle, truncus arteriosus or pulmonary atresia with different ductal dependencies.",
    recognition: "Parallel rather than crossing great arteries suggests transposition; an overriding enlarged aorta with subaortic VSD and small pulmonary artery suggests tetralogy; one arterial trunk supplying systemic, pulmonary and coronary circulations suggests truncus.",
    workflow: "Trace each outflow from its ventricle in real time, record short-axis bifurcation, three-vessel-trachea relationships, valve motion and Doppler velocity, measure annuli and great vessels, assess ductal and arch flow and search for VSD and extracardiac associations.",
    interpretation: "A technically oblique outflow can simulate override or vessel disproportion. Direction of ductal flow and severity of obstruction help predict neonatal instability and prostaglandin dependence.",
    safety: "Use brief optimized Doppler and escalate suspected ductal-dependent disease early enough for planned delivery at a cardiac center.",
    redFlags: "Pulmonary or aortic atresia, restrictive atrial communication in transposition, reversed ductal flow, severe valve insufficiency or hydrops demands urgent specialist coordination.",
    commonErrors: "Assuming two vessels means normal outflows, failing to prove ventricular origin, confusing the ductal arch with aortic arch and overlooking associated VSD or coronary implications are high-risk errors.",
    examFocus: "Differentiate tetralogy, transposition, double-outlet right ventricle, truncus and pulmonary atresia by connections, crossing, VSD relation and three-vessel-trachea pattern.",
    glossary: [{ term: "Override", definition: "Origin of a great artery above and receiving inflow from both ventricles across a septal defect." }, { term: "Ductal-dependent circulation", definition: "Circulation requiring patency of the ductus arteriosus to maintain pulmonary or systemic blood flow after birth." }],
  },
  {
    ...shared, id: "dms-fetal-arches", topic: "Fetal Aortic Arch, Ductal Arch, and Vascular Rings",
    bottomLine: "Image both arches separately, confirm their ventricular origins, course and flow direction, and evaluate arch size, sidedness and branching; a normal-appearing four-chamber view does not exclude critical arch disease.",
    coreConcept: "The ductal arch arises from the right ventricle through the pulmonary artery and descends smoothly; the aortic arch arises from the left ventricle, has head-neck branches and a tighter candy-cane contour.",
    recognition: "Isthmic narrowing and ventricular or great-vessel disproportion suggest coarctation but are not diagnostic alone. A U-shaped confluence around the trachea supports double aortic arch, while a right arch with left ductus may form a vascular ring.",
    workflow: "Acquire sagittal aortic and ductal arches, transverse three-vessel-trachea view, measure isthmus and ductus with gestational-age references, document direction and velocity, assess head-neck branching, ventricles and associated defects, and arrange serial reassessment when suspicion persists.",
    interpretation: "Coarctation is difficult prenatally because the ductus bypasses the isthmus; late-gestation right-left disproportion can be physiologic. Diagnosis integrates serial size, flow, arch geometry and associated findings.",
    safety: "Do not overheat or prolong Doppler acquisition; promptly flag lesions that may become critical after ductal closure so neonatal surveillance and prostaglandin access are planned.",
    redFlags: "Reversed transverse-arch flow, severe isthmic hypoplasia, interrupted arch, constricted ductus with right-heart failure or complete vascular ring with associated anomalies requires urgent consultation.",
    commonErrors: "Calling the ductal arch the aorta, relying on one diameter, ignoring z-scores and gestational change, and dismissing abnormal flow because the four-chamber view is normal are common errors.",
    examFocus: "Know arch identification, coarctation limitations, interrupted arch, right aortic arch, double arch, vascular rings and ductal constriction.",
    glossary: [{ term: "Aortic isthmus", definition: "Aortic segment between the left subclavian artery and ductal insertion, a common site of coarctation." }, { term: "Vascular ring", definition: "Abnormal arch-vessel configuration that encircles the trachea and esophagus." }],
  },
  {
    ...shared, id: "dms-fetal-arrhythmia", topic: "Fetal Rhythm Assessment and Arrhythmias",
    bottomLine: "Classify fetal rhythm from atrial rate, ventricular rate, regularity and atrioventricular relationship using M-mode and pulsed Doppler; rate alone cannot distinguish ectopy, re-entry tachycardia and heart block.",
    coreConcept: "Mechanical atrial and ventricular events act as surrogates for electrical activation. Supraventricular tachycardia commonly has 1:1 conduction, atrial flutter has faster atrial than ventricular activity, and complete block has independent atrial and ventricular rhythms.",
    recognition: "Intermittent premature atrial contractions are common and often benign; sustained tachycardia can cause hydrops. Persistent ventricular bradycardia with atrioventricular dissociation suggests complete block, especially with maternal autoantibodies or structural disease.",
    workflow: "Record simultaneous atrial and ventricular wall motion by M-mode when alignment permits, confirm timing with mitral-aortic or venous-arterial Doppler, calculate separate rates, assess duration and variability, ventricular function, valve regurgitation, effusions and hydrops.",
    interpretation: "Blocked atrial ectopy can mimic bradycardia, and motion artifact can imitate irregularity. Mechanism, sustained duration and hemodynamic effect guide urgency more than a single rate measurement.",
    safety: "Keep Doppler sampling brief, observe fetal condition, and communicate sustained abnormal rhythm or deteriorating function immediately rather than repeatedly documenting the same event.",
    redFlags: "Sustained tachycardia, ventricular rate below expected range with dissociation, hydrops, severe dysfunction or ventricular tachycardia requires urgent fetal-cardiology and maternal-fetal-medicine management.",
    commonErrors: "Reporting only ventricular rate, failing to determine atrioventricular relation, mistaking blocked ectopy for complete block and overlooking hydrops are key errors.",
    examFocus: "Differentiate sinus rhythm, premature beats, SVT, atrial flutter, blocked bigeminy and complete heart block using mechanical timing patterns.",
    glossary: [{ term: "Atrioventricular dissociation", definition: "Independent atrial and ventricular activation without a consistent conduction relationship." }, { term: "Blocked atrial bigeminy", definition: "Alternating sinus and premature atrial beats in which premature beats fail to conduct, producing apparent bradycardia." }],
  },
  {
    ...shared, id: "dms-fetal-function-hydrops", topic: "Fetal Cardiac Function, Cardiomyopathy, and Hydrops",
    bottomLine: "Assess fetal function with chamber size, shortening, valve motion, regurgitation, venous Doppler and signs of congestion; hydrops is a final common pathway requiring a cause-directed survey, not a diagnosis by itself.",
    coreConcept: "Fetal cardiac failure elevates venous pressure and impairs forward flow, causing cardiomegaly, atrioventricular regurgitation, abnormal ductus venosus or umbilical venous flow and fluid accumulation in at least two fetal compartments.",
    recognition: "Reduced shortening, ventricular dilation or hypertrophy, valve regurgitation, pericardial or pleural effusion, ascites and skin edema indicate worsening physiology. Cardiomyopathy may be primary or related to anemia, infection, maternal disease, twin complications or arrhythmia.",
    workflow: "Measure cardiothoracic size and ventricular dimensions, examine contractility and valves, sample ductus venosus and umbilical vein only when indicated, survey all hydrops compartments, assess rhythm, placenta and Doppler evidence of anemia or placental disease, and compare serially.",
    interpretation: "A small isolated rim of pericardial fluid may be physiologic, whereas multiple fluid collections define hydrops. Normal fractional shortening does not exclude diastolic dysfunction or high-output failure.",
    safety: "Use the shortest effective Doppler protocol and escalate maternal symptoms or severe fetal compromise; maternal mirror syndrome can accompany advanced hydrops.",
    redFlags: "Progressive hydrops, absent or reversed ductus venosus a-wave, pulsatile umbilical vein, severe valve regurgitation, marked dysfunction or maternal mirror syndrome requires urgent management.",
    commonErrors: "Equating ejection appearance with complete function, calling one effusion hydrops, ignoring rhythm and anemia, and using adult thresholds in the fetus are common errors.",
    examFocus: "Integrate fetal heart failure signs, cardiomyopathy patterns, hydrops definition, venous Doppler deterioration and high-output causes.",
    glossary: [{ term: "Hydrops fetalis", definition: "Abnormal fluid in at least two fetal compartments, such as skin, pleural, pericardial or abdominal spaces." }, { term: "Mirror syndrome", definition: "Maternal edema and preeclampsia-like illness associated with severe fetal and placental hydrops." }],
  },
  {
    ...shared, id: "dms-pediatric-echo-views", topic: "Pediatric Echocardiographic Windows and Age-Adjusted Measurements",
    bottomLine: "A pediatric study is a segmental examination adapted to body size, age, cooperation and congenital anatomy; complete connections and Doppler data take priority over reproducing an adult protocol.",
    coreConcept: "Subcostal, parasternal, apical, suprasternal and right parasternal windows provide complementary anatomy. Measurements must use pediatric normative data indexed to body size, commonly expressed as z-scores.",
    recognition: "Subcostal views define situs, septa and venous return; suprasternal views define arch and systemic veins. High heart rates require high frame rate and sweep speed, while congenital repairs change expected geometry and flow.",
    workflow: "Verify identity, height and weight, review diagnosis and surgical history, establish situs and connections, obtain systematic windows, measure chambers, valves and vessels in validated planes, align spectral Doppler, calculate z-scores and document technical limitations.",
    interpretation: "A value normal for an adult may be abnormal for an infant and vice versa. Sedation, agitation, anemia and fever alter rate and flow; z-score validity depends on the correct measurement convention and reference model.",
    safety: "Use child-centered positioning, fall and infection precautions, continuous monitoring under sedation policy, and stop when distress outweighs incremental diagnostic value.",
    redFlags: "Cyanosis, respiratory deterioration, critical gradients, severe ventricular dysfunction, tamponade or unexpected postoperative obstruction requires immediate escalation.",
    commonErrors: "Applying adult reference ranges, omitting height or weight, using the wrong z-score convention, skipping subcostal or suprasternal windows and forcing prolonged imaging in a distressed child are errors.",
    examFocus: "Know pediatric windows, segmental order, z-scores, high-rate Doppler optimization, cooperation strategies and sedation responsibilities.",
    glossary: [{ term: "Z-score", definition: "Number of standard deviations a measurement lies above or below the expected mean for body size or age." }, { term: "Sequential segmental analysis", definition: "Systematic description of atrial arrangement, connections, ventricles, outflows and great arteries." }],
  },
  {
    ...shared, id: "dms-pediatric-shunts-obstruction", topic: "Pediatric Shunts, Outflow Obstruction, and Hemodynamic Burden",
    bottomLine: "Grade pediatric congenital lesions by anatomy, pressure and flow consequences: define the defect or obstruction, obtain well-aligned Doppler, and assess chamber remodeling, pulmonary pressure and downstream perfusion.",
    coreConcept: "Shunt magnitude depends on defect size and pulmonary-systemic resistance; Doppler velocity reflects pressure difference, not defect size alone. Obstruction raises proximal pressure and can cause hypertrophy, dysfunction or collateral flow.",
    recognition: "A small restrictive VSD may have high velocity with little chamber load, while a large unrestrictive defect may show lower velocity and pulmonary hypertension. Coarctation can produce arch narrowing, diastolic flow continuation and abdominal aortic flow abnormality.",
    workflow: "Define location and dimensions in orthogonal planes, map flow without color blooming, align CW Doppler, apply Bernoulli only to a complete envelope, evaluate atria, ventricles, valves, pulmonary arteries, arch and abdominal aorta, and reconcile gradient with clinical and morphologic findings.",
    interpretation: "Sedation and loading conditions change gradients; pressure recovery and serial stenoses can mislead. A falling gradient may reflect worsening ventricular function rather than improvement.",
    safety: "Recognize ductal-dependent systemic or pulmonary flow, avoid delaying escalation for exhaustive measurements, and use neonatal thermal and monitoring precautions.",
    redFlags: "Critical outflow obstruction, reversed shunt with hypoxemia, severe pulmonary hypertension, poor systemic perfusion, ventricular failure or closing-duct physiology needs emergency cardiology review.",
    commonErrors: "Equating velocity with defect severity, tracing an incomplete envelope, ignoring chamber burden, estimating RV pressure without accounting for RA pressure or obstruction and missing arch disease are common errors.",
    examFocus: "Integrate ASD, VSD, PDA, pulmonary and aortic stenosis, coarctation, Bernoulli assumptions, shunt direction and chamber response.",
    glossary: [{ term: "Restrictive defect", definition: "Defect small enough to maintain a substantial pressure difference between connected chambers or vessels." }, { term: "Diastolic runoff", definition: "Continued forward or reverse flow during diastole caused by a low-resistance connection such as a patent ductus." }],
  },
  {
    ...shared, id: "dms-pediatric-postoperative", topic: "Postoperative Congenital Heart Surveillance",
    bottomLine: "Interpret postoperative pediatric echocardiography from the known surgical pathway: identify every connection, conduit, baffle, patch and shunt, then assess patency, residual lesions, valve function, ventricular performance and effusion.",
    coreConcept: "Repair or palliation creates non-native flow pathways. Fontan circulation depends on passive systemic venous flow to pulmonary arteries, arterial switch transfers coronaries and great arteries, and conduits or patches can stenose, leak or degenerate.",
    recognition: "Residual shunt, baffle obstruction or leak, conduit gradient, branch pulmonary stenosis, neoaortic regurgitation, coronary-related dysfunction, cavopulmonary pathway flow changes and postoperative effusions have operation-specific significance.",
    workflow: "Review operative note and prior diagram, establish current segmental anatomy, trace surgically created pathways with two-dimensional and color imaging, sample expected inflow and outflow sites, quantify residual lesions, assess both ventricles and valves, compare immediately with prior studies and communicate new changes.",
    interpretation: "Expected postoperative flow may be low velocity and phasic; absence of a high gradient does not exclude obstruction in low-flow states. Ventricular morphology and loading determine which conventional indices remain valid.",
    safety: "Observe lines, wounds, oxygen and monitoring devices, use sterile precautions when required, and rapidly escalate new obstruction, severe dysfunction, tamponade or unexpected cyanosis.",
    redFlags: "Fontan pathway obstruction, thrombosis, tamponade, acute severe valve regurgitation, coronary ischemic pattern after arterial switch, conduit failure or new major residual shunt requires urgent congenital-cardiology review.",
    commonErrors: "Scanning without knowing the operation, applying native anatomy assumptions, measuring only peak gradient, overlooking branch vessels and calling low-flow pathways patent without color and spectral confirmation are errors.",
    examFocus: "Know surveillance principles for shunt and patch repair, arterial switch, tetralogy repair, conduits, Glenn and Fontan pathways, including expected flow and major complications.",
    glossary: [{ term: "Baffle", definition: "Surgically created intracardiac channel that redirects blood toward a desired chamber or vessel." }, { term: "Fontan circulation", definition: "Palliation routing systemic venous blood directly to pulmonary arteries without a subpulmonary ventricle." }],
  },
];
