import type { AlliedAuthoredTopic } from "./types";

const EXAM = "ARDMS RVT | Sonography Canada Vascular";
const C = "Vascular Sonography";

export const diagnosticSonographyVascularTopics13: AlliedAuthoredTopic[] = [
  {
    id: "dms-vas-carotid", careerType: "diagnosticMedicalSonography", examTag: EXAM, regionScope: "BOTH", category: C, topic: "Carotid Duplex and Cerebrovascular Disease",
    bottomLine: "Grade carotid disease from a complete duplex examination that combines grayscale plaque, color lumen assessment, angle-corrected velocities, velocity ratios, waveform morphology, and distal or collateral effects using the laboratory's validated criteria.",
    coreConcept: "A focal reduction in lumen raises velocity when volume flow is preserved, but severe near-occlusion may reduce flow. Plaque geometry, collateral circulation, cardiac output, tandem disease, contralateral obstruction, and technical angle all affect measured velocities.",
    recognition: "Atherosclerotic plaque commonly develops at the bulb and proximal internal carotid artery; focal aliasing, elevated ICA velocity, spectral disturbance, and increased ICA-to-CCA ratio support stenosis, while a tiny variable channel may indicate near-occlusion.",
    workflow: "Survey CCA, bulb, ICA, ECA and vertebral arteries in grayscale and color, identify vessels by anatomy and waveform, keep angle correction parallel to the lumen at 60 degrees or less, sample prestenotic, stenotic and distal segments, and document plaque morphology and limitations.",
    interpretation: "Velocity criteria cannot be applied blindly when rhythm is irregular, output is low, the opposite carotid is occluded, tandem lesions exist, or the residual lumen is nearly collapsed. Reconcile anatomy and hemodynamics before assigning a category.",
    safety: "Avoid excessive pressure over a painful recent surgical site or unstable plaque, recognize neurologic symptoms during scanning, and immediately follow the pathway for suspected acute occlusion or a mobile intraluminal lesion.",
    redFlags: "Acute ICA occlusion, near-occlusion with neurologic symptoms, mobile thrombus, dissection flap, pseudoaneurysm, or reversed vertebral flow with compatible ischemic symptoms requires prompt escalation.",
    commonErrors: "Common errors are confusing ICA and ECA, steering angle to the vessel wall instead of flow, sampling within color artifact, grading from one velocity, and failing to identify near-occlusion when velocity is unexpectedly low.",
    examFocus: "Know vessel identification, validated stenosis categories, ratio use, plaque and dissection features, vertebral direction, subclavian steal physiology, and limitations that invalidate routine velocity criteria.",
    glossary: [{ term: "Near-occlusion", definition: "Critical ICA narrowing with collapse or marked caliber reduction of the distal artery." }, { term: "ICA/CCA ratio", definition: "Ratio of peak systolic velocities used with other findings to support carotid stenosis grading." }],
  },
  {
    id: "dms-vas-transcranial", careerType: "diagnosticMedicalSonography", examTag: EXAM, regionScope: "BOTH", category: C, topic: "Transcranial Doppler and Intracranial Hemodynamics",
    bottomLine: "Identify intracranial vessels by window, depth, direction, waveform, and response to tracing maneuvers; interpret velocity and pulsatility in the context of age, carbon dioxide, blood pressure, hematocrit, collateral flow, and the clinical indication.",
    coreConcept: "Low-frequency ultrasound crosses thinner skull regions to sample basal cerebral arteries. Stenosis, vasospasm, emboli, collateral recruitment, distal resistance, and systemic physiology alter mean velocity and pulsatility.",
    recognition: "The transtemporal window samples MCA, ACA, PCA and terminal ICA; suboccipital windows assess vertebral and basilar arteries; focal velocity acceleration and turbulence support stenosis, while rising MCA velocity after hemorrhage can support vasospasm in context.",
    workflow: "Use the correct low-frequency probe, locate a reliable window, record depth and direction, trace vessels systematically, compare sides and serial examinations, calculate prescribed indices or ratios, and document absent windows rather than labeling flow absent.",
    interpretation: "High velocity may reflect stenosis, vasospasm, hyperemia or anemia, and low velocity may reflect poor window, low output or distal occlusion. Ratios and clinical context help distinguish diffuse hyperemia from focal vasoconstriction.",
    safety: "Minimize unnecessary dwell time and pressure, maintain monitoring in unstable patients, and communicate abrupt serial deterioration, microembolic signals, or waveforms suggesting critical intracranial compromise promptly.",
    redFlags: "New absent intracranial signal after a prior adequate window, severe focal acceleration, worsening vasospasm indices, embolic showers, or reverberating flow compatible with circulatory arrest protocol requires urgent specialist review.",
    commonErrors: "Common errors are identifying a vessel by direction alone, ignoring depth, diagnosing occlusion through a poor window, mixing peak and mean velocities, and applying a ratio outside its validated clinical setting.",
    examFocus: "Expect window and vessel identification, normal directions and depths, vasospasm versus hyperemia, stenosis, emboli monitoring, collateral pathways, and technical limitations.",
    glossary: [{ term: "Pulsatility index", definition: "Difference between peak systolic and end-diastolic velocity divided by mean velocity." }, { term: "Microembolic signal", definition: "Brief high-intensity unidirectional Doppler signal caused by material passing through the sample volume." }],
  },
  {
    id: "dms-vas-lower-dvt", careerType: "diagnosticMedicalSonography", examTag: EXAM, regionScope: "BOTH", category: C, topic: "Lower-Extremity Venous Thrombosis",
    bottomLine: "Complete compression is the central sign excluding thrombus in accessible deep-vein segments; integrate grayscale lumen, compressibility, color filling, spontaneous flow, phasicity and augmentation while tracing thrombus extent and documenting every technically limited segment.",
    coreConcept: "Acute thrombus obstructs or narrows the lumen and may be hypoechoic, whereas chronic change becomes echogenic, contracted, recanalized or collateralized. Proximal obstruction alters respiratory phasicity even when the local vein compresses.",
    recognition: "Noncompressibility establishes thrombus in the examined segment. Acute veins may be enlarged with soft thrombus and absent flow; chronic post-thrombotic veins may be small and irregular with synechiae, wall thickening and collateral channels.",
    workflow: "Start at the common femoral junction, compress at short intervals through the femoral and popliteal systems, include calf veins according to protocol, compare sides when central obstruction is suspected, record color and spectral findings, and define proximal and distal thrombus extent.",
    interpretation: "Color filling does not override abnormal compression, and absent color alone does not establish thrombosis. Symmetric loss of phasicity may reflect respiratory technique, whereas unilateral continuous flow raises concern for proximal obstruction.",
    safety: "Use only enough pressure to test compression, avoid forceful augmentation over known acute thrombus, and immediately communicate acute proximal or extensive iliofemoral disease and symptoms concerning for pulmonary embolism.",
    redFlags: "Mobile proximal thrombus, extensive iliofemoral occlusion, phlegmasia, threatened limb, recurrent thrombosis despite therapy, or respiratory symptoms during the examination requires urgent escalation.",
    commonErrors: "Common errors are following the duplicated femoral system incompletely, calling color fill a negative study, confusing artery and vein, skipping calf or iliac clues, and labeling thrombus age with unjustified certainty.",
    examFocus: "Know compression sequence, acute versus chronic features, central-obstruction clues, calf anatomy, duplicated systems, superficial extension risk, and when limited imaging requires repeat or alternate testing.",
    glossary: [{ term: "Phlegmasia", definition: "Severe extensive venous thrombosis producing marked swelling and threatened limb perfusion." }, { term: "Synechia", definition: "Fibrous intraluminal band representing chronic post-thrombotic change." }],
  },
  {
    id: "dms-vas-upper-venous", careerType: "diagnosticMedicalSonography", examTag: EXAM, regionScope: "BOTH", category: C, topic: "Upper-Extremity and Central Venous Thrombosis",
    bottomLine: "Assess upper-extremity thrombosis with compression where anatomy permits and with color, respiratory phasicity, cardiac pulsatility, augmentation, symmetry, and collateral patterns where the clavicle or thorax prevents direct compression.",
    coreConcept: "Catheters, malignancy, surgery, thoracic outlet compression and hypercoagulability predispose to thrombosis. Central obstruction may be inferred from damped or continuous peripheral waveforms and extensive collaterals despite incomplete visualization.",
    recognition: "Noncompressible jugular, axillary or brachial vein supports thrombosis; echogenic material around a line, absent color, asymmetric loss of pulsatility or phasicity, and chest-wall collaterals support more central disease.",
    workflow: "Trace internal jugular, subclavian, axillary, brachial, basilic and cephalic systems, compress accessible segments, compare bilateral central waveforms, document catheter relationship and thrombus extent, and assess positional change when thoracic outlet disease is the indication.",
    interpretation: "The subclavian vein cannot be reliably compressed beneath the clavicle, so a normal-looking lumen does not exclude thrombosis. Dynamic compression findings require symptom reproduction and validated protocol rather than position alone.",
    safety: "Do not manipulate a catheter, use painful excessive pressure, or provoke prolonged ischemic symptoms during positional testing; communicate acute central thrombosis or line-associated mobile thrombus promptly.",
    redFlags: "Acute innominate or subclavian occlusion, SVC-type collateral pattern, infected line-associated thrombosis, severe limb swelling, or acute neurologic or respiratory symptoms during provocative testing requires urgent review.",
    commonErrors: "Common errors are declaring the subclavian vein normal from failed compression, omitting bilateral waveform comparison, confusing lymph node with thrombus, and diagnosing thoracic outlet syndrome from positional flow change in an asymptomatic patient.",
    examFocus: "Understand accessible versus inaccessible compression sites, central-obstruction clues, catheter-associated disease, superficial-vein anatomy, and dynamic thoracic outlet limitations.",
    glossary: [{ term: "Central venous obstruction", definition: "Flow-limiting disease of the subclavian, innominate, or superior vena caval pathways." }, { term: "Collateral vein", definition: "Alternative venous channel enlarged to bypass an obstructed primary pathway." }],
  },
  {
    id: "dms-vas-venous-insufficiency", careerType: "diagnosticMedicalSonography", examTag: EXAM, regionScope: "BOTH", category: C, topic: "Venous Reflux and Insufficiency Mapping",
    bottomLine: "Map superficial, deep and perforating venous systems under physiologic loading, provoke flow with the protocol-appropriate maneuver, measure reflux duration at the correct site, and connect hemodynamic findings to symptoms and treatment planning.",
    coreConcept: "Valve failure permits retrograde flow and venous hypertension, while obstruction can create secondary reflux or collateral pathways. Standing or reverse Trendelenburg positioning distends veins and improves functional assessment when safe.",
    recognition: "Prolonged retrograde flow after distal augmentation or Valsalva supports reflux using laboratory thresholds; varicosities often connect to an incompetent axial vein or perforator, while chronic obstruction produces wall change and collaterals.",
    workflow: "Review symptoms and prior treatment, position for venous filling, assess deep patency first, trace saphenofemoral and saphenopopliteal junctions and named trunks, provoke reflux consistently, map tributaries and perforators, and document diameters and skin-related anatomy.",
    interpretation: "Reflux time depends on technique, position and vessel segment. A visible varicosity is not necessarily the source, and treatment planning requires tracing the reflux pathway rather than listing isolated abnormal points.",
    safety: "Use fall precautions while standing, adapt for frailty or orthostasis, avoid forceful augmentation over acute thrombus, and stop if the patient becomes presyncopal or develops severe pain.",
    redFlags: "Unexpected acute thrombosis, severe post-thrombotic obstruction, active ulcer infection, bleeding varicosity, or critical swelling inconsistent with uncomplicated reflux requires prompt escalation.",
    commonErrors: "Common errors are testing supine without adequate venous filling, using inconsistent augmentation, mapping only visible varices, ignoring deep obstruction, and assigning reflux from color appearance without timed spectral evidence.",
    examFocus: "Know superficial and perforator anatomy, reflux maneuvers and thresholds by segment, primary versus secondary disease, treatment-mapping logic, and physiologic positioning.",
    glossary: [{ term: "Reflux", definition: "Abnormally prolonged retrograde venous flow caused by valvular incompetence." }, { term: "Perforator", definition: "Vein connecting superficial and deep venous systems through the fascia." }],
  },
  {
    id: "dms-vas-lower-arterial", careerType: "diagnosticMedicalSonography", examTag: EXAM, regionScope: "BOTH", category: C, topic: "Lower-Extremity Arterial Duplex and Physiologic Testing",
    bottomLine: "Localize peripheral arterial disease by integrating pulse examination, ankle or toe pressures, waveform morphology, segmental changes, grayscale plaque, focal velocity ratios, post-stenotic disturbance, and distal perfusion rather than relying on one peak velocity.",
    coreConcept: "Stenosis accelerates flow and dissipates energy, producing downstream dampening when significant. Collaterals may preserve resting pressure, while calcified incompressible arteries can falsely elevate ankle-brachial indices and require toe or waveform assessment.",
    recognition: "A focal velocity increase with spectral broadening supports stenosis, monophasic tardus-parvus flow indicates proximal hemodynamic disease, absent signal suggests occlusion only after technical causes are excluded, and reactive hyperemia can reveal exercise-limited disease.",
    workflow: "Record bilateral pressures and waveforms as indicated, survey from common femoral through tibial and pedal arteries, sample before, within and after lesions with consistent angle, calculate ratios, map occlusions and collateral reconstitution, and correlate with symptoms and tissue status.",
    interpretation: "A normal resting ABI may miss disease in diabetes, distal disease or exertional symptoms, while an elevated ABI may be noncompressible rather than reassuring. Duplex categories should use the laboratory's validated velocity-ratio criteria.",
    safety: "Do not inflate cuffs over wounds, grafts or recent surgery without guidance, protect ischemic skin, and urgently escalate threatened-limb findings rather than completing every routine segment.",
    redFlags: "Acute absent flow with pain, pallor, paresthesia or weakness, severely reduced toe perfusion with tissue loss, thrombosed graft, pseudoaneurysm, or embolic occlusion requires immediate review.",
    commonErrors: "Common errors are angle-correcting to the wall, grading from absolute velocity without ratio, calling calcified ABI normal, omitting inflow disease, and failing to distinguish collateral flow from the native vessel.",
    examFocus: "Expect waveform localization, ABI and toe-index interpretation, velocity ratios, inflow versus outflow disease, acute occlusion, aneurysm, entrapment and exercise-testing principles.",
    glossary: [{ term: "Ankle-brachial index", definition: "Ratio of ankle systolic pressure to the higher brachial pressure used to assess lower-limb perfusion." }, { term: "Tardus-parvus", definition: "Delayed, damped arterial waveform distal to a significant proximal obstruction." }],
  },
  {
    id: "dms-vas-upper-arterial", careerType: "diagnosticMedicalSonography", examTag: EXAM, regionScope: "BOTH", category: C, topic: "Upper-Extremity Arterial Disease and Thoracic Outlet Testing",
    bottomLine: "Evaluate upper-limb perfusion from subclavian inflow to digital circulation with bilateral pressures, waveforms and duplex, and interpret positional testing only when symptoms, anatomy and reproducible hemodynamic change agree.",
    coreConcept: "Atherosclerosis, embolus, trauma, vasospasm, aneurysm and extrinsic compression can impair flow. The arm has rich collateral pathways, so pressure and waveform asymmetry may localize disease better than symptoms alone.",
    recognition: "Lower pressure and damped waveform in one arm suggest proximal obstruction, focal velocity acceleration supports stenosis, abrupt absent flow may indicate embolus, and aneurysmal dilation with mural thrombus can threaten distal digits.",
    workflow: "Compare brachial pressures and waveforms, trace subclavian, axillary, brachial, radial and ulnar arteries, use Allen-type or digital testing when indicated, sample lesions consistently, and perform positional maneuvers with baseline comparison and symptom monitoring.",
    interpretation: "Positional waveform reduction can occur in healthy people and does not alone diagnose arterial thoracic outlet syndrome. A clinically meaningful conclusion requires symptoms, reproducibility, arterial change and anatomic correlation.",
    safety: "Stop provocative positioning for neurologic symptoms, severe pain or persistent perfusion loss, avoid cuffs over dialysis access, and immediately communicate acute limb ischemia or expanding pseudoaneurysm.",
    redFlags: "Acute embolic occlusion, threatened hand, traumatic arterial disruption, subclavian aneurysm with thrombus, severe symptomatic compression, or steal affecting cerebral circulation requires urgent review.",
    commonErrors: "Common errors are ignoring bilateral pressure difference, diagnosing compression from color alone, confusing vein and artery, using excessive Doppler angle, and failing to document symptom correlation during maneuvers.",
    examFocus: "Know segmental localization, palmar-arch testing, vasospasm, embolic patterns, trauma, aneurysm, thoracic outlet limitations and subclavian-steal relationships.",
    glossary: [{ term: "Digital photoplethysmography", definition: "Optical recording of pulsatile blood-volume change in digits used for perfusion assessment." }, { term: "Arterial thoracic outlet syndrome", definition: "Symptomatic arterial compression at the thoracic outlet, often with structural or embolic consequences." }],
  },
  {
    id: "dms-vas-aorta-iliac", careerType: "diagnosticMedicalSonography", examTag: EXAM, regionScope: "BOTH", category: C, topic: "Aortoiliac Occlusive and Aneurysmal Disease",
    bottomLine: "Examine the abdominal aorta and iliac arteries as both an anatomic and hemodynamic system: measure aneurysms perpendicular to the vessel outer wall, include mural thrombus, and map stenosis or occlusion with inflow and downstream effects.",
    coreConcept: "Aneurysm reflects wall dilation and rupture risk, whereas aortoiliac stenosis reduces energy delivered to both limbs. Tortuosity, thrombus, dissection and prior endograft repair alter measurement and flow patterns.",
    recognition: "Focal enlargement, mural thrombus, intimal flap, perigraft sac flow, focal velocity ratio increase, distal monophasic waveforms or bilateral pressure reduction supports important disease depending on context.",
    workflow: "Scan from diaphragm through bifurcation and common iliacs, measure perpendicular outer-to-outer, use multiple planes for tortuosity, sample celiac and mesenteric landmarks as orientation, evaluate stenotic segments and distal waveforms, and follow repair-surveillance protocol when present.",
    interpretation: "Oblique measurement exaggerates diameter, and a normal residual lumen does not define total aneurysm size. After endovascular repair, sac trend and endoleak classification are more important than graft-lumen patency alone.",
    safety: "Use minimal pressure over a painful pulsatile mass, do not delay emergency action for a complete protocol when rupture is suspected, and protect recent operative sites.",
    redFlags: "Symptomatic aneurysm, retroperitoneal hematoma, acute dissection, thrombosed aneurysm, limb malperfusion, graft migration, or enlarging sac with endoleak requires urgent escalation.",
    commonErrors: "Common errors are measuring inner-to-inner, excluding thrombus, confusing tortuosity with aneurysm, missing common-iliac extension, and using color gain that fabricates or erases endoleak flow.",
    examFocus: "Know aneurysm measurement, rupture and dissection signs, aortoiliac stenosis localization, Leriche-type physiology, repair surveillance and endoleak categories.",
    glossary: [{ term: "Endoleak", definition: "Persistent blood flow outside an endograft lumen but within an aneurysm sac after repair." }, { term: "Mural thrombus", definition: "Thrombus attached to the aneurysm wall and included within total diameter." }],
  },
  {
    id: "dms-vas-renal-mesenteric", careerType: "diagnosticMedicalSonography", examTag: EXAM, regionScope: "BOTH", category: C, topic: "Renal and Mesenteric Arterial Duplex",
    bottomLine: "Diagnose renal or mesenteric stenosis from fasting preparation, complete vessel visualization, correct angle, focal velocity and ratio change, post-stenotic effects, organ waveforms and clinical indication; bowel gas or one elevated velocity must not become a false diagnosis.",
    coreConcept: "Renal stenosis may cause renovascular hypertension or ischemic nephropathy, while mesenteric disease becomes symptomatic when collateral capacity cannot meet postprandial demand. Respiration and vessel curvature strongly affect sampling.",
    recognition: "Focal renal velocity elevation with renal-aortic ratio change and distal turbulence supports stenosis; tardus-parvus intrarenal flow supports proximal disease. Mesenteric stenosis produces focal acceleration, while median arcuate compression varies with respiration.",
    workflow: "Confirm fasting status, record aortic velocity, identify vessel origins in longitudinal and transverse planes, sample origins and proximal-to-distal segments, assess renal size and intrarenal waveforms, examine celiac and SMA with respiratory maneuvers when indicated, and document limitations.",
    interpretation: "High aortic velocity can distort ratios, low output can suppress lesion velocities, and tortuosity can elevate velocity without fixed stenosis. Respiratory change alone does not establish clinically significant celiac compression.",
    safety: "Avoid prolonged pressure in severe abdominal pain, recognize acute mesenteric ischemia or renal infarction, and immediately communicate absent organ flow or severe findings with compatible symptoms.",
    redFlags: "Acute absent mesenteric flow with pain, dissection, renal-artery thrombosis, infarction, severe bilateral renal stenosis with deterioration, or symptomatic mesenteric multivessel disease requires urgent review.",
    commonErrors: "Common errors are mistaking branches, using the wrong aortic sample, angle-correcting across curves, diagnosing stenosis from color aliasing, and applying fasting criteria to a nonfasting technically limited study.",
    examFocus: "Know vessel origins, validated velocity and ratio concepts, intrarenal indirect signs, fibromuscular dysplasia patterns, mesenteric collateral pathways and respiratory celiac compression.",
    glossary: [{ term: "Renal-aortic ratio", definition: "Renal peak systolic velocity divided by aortic peak systolic velocity, used with other criteria." }, { term: "Mesenteric ischemia", definition: "Inadequate intestinal perfusion from arterial or venous compromise." }],
  },
  {
    id: "dms-vas-access-grafts", careerType: "diagnosticMedicalSonography", examTag: EXAM, regionScope: "BOTH", category: C, topic: "Dialysis Access, Bypass Graft, and Postoperative Surveillance",
    bottomLine: "Surveillance must trace the entire circuit: inflow artery, anastomosis, conduit, outflow vein or artery, and central pathway; combine anatomy, velocity ratios, volume flow, waveform change, access examination and prior trend to identify lesions threatening function.",
    coreConcept: "A fistula or graft depends on adequate inflow and low-resistance outflow. Stenosis increases velocity and reduces delivered flow, while aneurysm, pseudoaneurysm, thrombosis, steal and infection threaten access or limb safety.",
    recognition: "Focal narrowing with aliasing and velocity ratio, falling volume flow, elevated inflow resistance, outflow pulsatility, thrombus, abnormal sac-to-neck flow or distal ischemic waveform supports a complication.",
    workflow: "Review access type and surgery, inspect and palpate thrill, map inflow through outflow, sample before and within suspected lesions, measure volume flow at a validated site, assess aneurysm or pseudoaneurysm neck, test distal perfusion when symptomatic, and compare prior results.",
    interpretation: "One high anastomotic velocity may reflect expected geometry. Hemodynamic significance requires a reproducible focal ratio, narrowing, circuit effect, access dysfunction or trend; postoperative graft criteria must match the conduit and laboratory protocol.",
    safety: "Do not compress or place cuffs over a functioning access, protect thin aneurysmal skin, use infection precautions, and immediately escalate absent thrill, acute thrombosis, active bleeding, infected pseudoaneurysm or threatened hand.",
    redFlags: "Acute access thrombosis, impending rupture, skin ulceration over aneurysm, pseudoaneurysm infection, severe steal ischemia, graft occlusion or critical inflow/outflow lesion requires prompt intervention.",
    commonErrors: "Common errors are examining only the palpable access, skipping inflow or central outflow, measuring volume at a turbulent segment, calling expected anastomotic acceleration stenosis, and failing to compare with prior flow trend.",
    examFocus: "Expect circuit anatomy, maturation, stenosis localization, volume-flow technique, thrombosis, steal, aneurysm versus pseudoaneurysm, graft surveillance and urgent access complications.",
    glossary: [{ term: "Volume flow", definition: "Estimated blood volume passing a vessel per unit time, derived from diameter and time-averaged velocity." }, { term: "Steal syndrome", definition: "Symptomatic distal ischemia caused by diversion of arterial flow through a low-resistance access." }],
  },
];
