import type { AlliedAuthoredTopic } from "./types";

export const alliedTopics05: AlliedAuthoredTopic[] = [
  {
    id: "him-record-integrity",
    careerType: "healthInfoMgmt",
    examTag: "AHIMA RHIT",
    regionScope: "US",
    category: "Data Content, Structure, and Information Governance",
    topic: "Health Record Integrity and Data Quality",
    bottomLine: "A trustworthy health record must be complete, accurate, consistent, timely, attributable, and protected from improper alteration across its lifecycle.",
    coreConcept: "Data quality is not simply the absence of missing fields; information must faithfully represent the patient and encounter, retain provenance, and remain fit for clinical, legal, reimbursement, and analytic use.",
    recognition: "Duplicate records, contradictory demographics, late entries without attribution, copy-forward errors, mismatched encounter data, unsigned documentation, and inconsistent timestamps threaten record integrity.",
    workflow: "Identify the integrity issue, verify the authoritative source, preserve the audit trail, correct or merge information through approved processes, communicate unresolved discrepancies, and monitor for recurrence.",
    interpretation: "A correction should preserve what was originally recorded and who changed it; silently overwriting information undermines the legal and audit value of the record.",
    safety: "Never merge patient records or alter identifiers based on assumption alone; use validated identity criteria and the organization's correction process.",
    redFlags: "Potential wrong-patient documentation, identity theft, unauthorized alteration, duplicate records with conflicting clinical information, or broad interface corruption requires immediate escalation.",
    commonErrors: "Deleting erroneous documentation instead of amending it properly, merging similar names without sufficient identifiers, and treating copied text as verified current data.",
    examFocus: "RHIT questions often test which action best protects integrity, provenance, and the audit trail when information is wrong or duplicated.",
    glossary: [
      { term: "Data integrity", definition: "Accuracy, consistency, completeness, and reliability of information across its lifecycle." },
      { term: "Audit trail", definition: "Record of system activity showing who accessed or changed information and when." },
    ],
  },
  {
    id: "him-icd10cm-conventions",
    careerType: "healthInfoMgmt",
    examTag: "AHIMA RHIT",
    regionScope: "US",
    category: "Revenue Cycle and Coding",
    topic: "ICD-10-CM Coding Conventions and Sequencing",
    bottomLine: "Code from the complete documentation using the Alphabetic Index and Tabular List together, follow instructional notes and sequencing rules, and query when documentation is clinically ambiguous rather than inferring a diagnosis.",
    coreConcept: "Coding conventions such as code first, use additional code, Excludes notes, laterality, combination codes, and seventh characters are mandatory elements of code assignment.",
    recognition: "Documentation that supports multiple possible codes, lacks laterality or acuity, conflicts across notes, or uses nonspecific language despite available clinical detail may require clarification.",
    workflow: "Identify the documented condition, locate the term in the Alphabetic Index, verify the code in the Tabular List, apply instructional notes and specificity, sequence according to the encounter, and validate that documentation supports every assigned code.",
    interpretation: "A clinically likely diagnosis is not coded as established merely because test results suggest it; coding follows provider documentation and official guidance for the setting.",
    safety: "Do not upcode, unbundle, or infer unsupported specificity to improve reimbursement.",
    redFlags: "Conflicting principal-diagnosis documentation, unsupported high-severity code, missing required seventh character, or coding that changes payment without documentation support requires review.",
    commonErrors: "Coding directly from the index without tabular verification, overlooking Excludes or sequencing notes, and assigning specificity not stated in the record.",
    examFocus: "RHIT scenarios usually hinge on applying a convention or sequencing rule correctly, not on guessing the most clinically dramatic diagnosis.",
    glossary: [
      { term: "Combination code", definition: "Single code used to classify two diagnoses, a diagnosis with a manifestation, or a diagnosis with an associated complication." },
      { term: "Tabular List", definition: "Structured ICD-10-CM code list containing categories, codes, inclusion terms, instructional notes, and conventions." },
    ],
  },
  {
    id: "him-privacy-disclosure",
    careerType: "healthInfoMgmt",
    examTag: "AHIMA RHIT",
    regionScope: "US",
    category: "Privacy and Security",
    topic: "Privacy, Disclosure, and Minimum Necessary Principles",
    bottomLine: "Release health information only for a permitted purpose, verify identity and authority, disclose the appropriate scope, document the release, and route uncertain or restricted requests through privacy policy rather than improvising.",
    coreConcept: "Access to information depends on purpose, role, authorization, and applicable privacy rules; having technical access does not automatically create permission to view or disclose.",
    recognition: "Requests from family members, employers, law enforcement, attorneys, media, research teams, or staff without a treatment/business need require careful authority verification.",
    workflow: "Identify requester and purpose, verify authorization or permitted basis, confirm any special restrictions, apply minimum-necessary principles when applicable, disclose securely, record the release, and escalate ambiguous requests.",
    interpretation: "An urgent or persuasive requester does not eliminate privacy requirements; exceptions must come from law and policy, not convenience.",
    safety: "Do not send records to a new destination or person based only on verbal familiarity or caller confidence.",
    redFlags: "Suspected unauthorized access, misdirected disclosure, request involving specially protected information, identity mismatch, or large unusual export requires immediate privacy escalation.",
    commonErrors: "Assuming relatives are automatically entitled to records, disclosing the full chart when a narrower set is sufficient, and using unverified contact information supplied during the request.",
    examFocus: "RHIT items commonly test authorization, role-based access, minimum necessary, secure release, and what to do when authority is uncertain.",
    glossary: [
      { term: "Minimum necessary", definition: "Privacy principle limiting certain uses, disclosures, and requests to information reasonably needed for the purpose." },
      { term: "Authorization", definition: "Documented permission meeting required elements for a use or disclosure not otherwise permitted." },
    ],
  },
  {
    id: "him-revenue-cycle-denials",
    careerType: "healthInfoMgmt",
    examTag: "AHIMA RHIT",
    regionScope: "US",
    category: "Revenue Cycle and Coding",
    topic: "Revenue Cycle, Claims, and Denial Analysis",
    bottomLine: "Resolve denials by identifying the true root cause—registration, coverage, authorization, coding, documentation, medical necessity, billing, or payer processing—and correct the source process rather than repeatedly resubmitting unchanged claims.",
    coreConcept: "Revenue-cycle performance depends on accurate information flowing from scheduling and registration through documentation, coding, charge capture, claim submission, adjudication, and follow-up.",
    recognition: "Repeated denials by payer, code, provider, service line, or reason code signal a process defect rather than isolated claim noise.",
    workflow: "Read the denial reason, validate claim and record data, identify where the defect originated, correct supported errors, appeal when documentation supports the service, trend recurring causes, and feed prevention actions upstream.",
    interpretation: "A denial overturned on appeal can still represent a preventable process problem if the same documentation or authorization issue recurs.",
    safety: "Never change a diagnosis or code solely to obtain payment without documentation and coding support.",
    redFlags: "Systematic upcoding concern, widespread eligibility error, high-volume duplicate billing, suspected fraud, or denial trend affecting patient access requires leadership/compliance escalation.",
    commonErrors: "Treating every denial as a coding problem, resubmitting unchanged claims, and fixing individual claims without addressing the repeated source defect.",
    examFocus: "RHIT questions often ask for the best root-cause or process-improvement response rather than the fastest one-claim workaround.",
    glossary: [
      { term: "Denial", definition: "Payer refusal or reduction of payment for a submitted claim based on coverage, coding, documentation, authorization, or other rules." },
      { term: "Revenue cycle", definition: "Administrative and clinical processes that capture services and convert them into reimbursement from scheduling through final account resolution." },
    ],
  },
  {
    id: "him-cdi-query-ethics",
    careerType: "healthInfoMgmt",
    examTag: "AHIMA RHIT",
    regionScope: "US",
    category: "Data Content and Coding",
    topic: "Clinical Documentation Integrity and Compliant Queries",
    bottomLine: "A compliant query clarifies incomplete, conflicting, vague, or clinically inconsistent documentation without steering the provider toward a financially advantageous diagnosis.",
    coreConcept: "Clinical documentation integrity improves the accuracy of the record; the query is a clarification tool, not a mechanism to manufacture severity or reimbursement.",
    recognition: "Conflicting diagnoses, unsupported specificity, missing linkage, unclear acuity, contradictory test interpretation, or documentation that does not explain a clinically significant finding may justify a query.",
    workflow: "Review the full record, identify the precise ambiguity, cite relevant clinical indicators objectively, present reasonable response options when appropriate including other/unable to determine, and retain the query according to policy.",
    interpretation: "A provider is permitted to maintain the original documentation; a query should not imply that one answer is required.",
    safety: "Avoid leading language, reimbursement-focused wording, or selective presentation of evidence that favors one diagnosis.",
    redFlags: "Pressure to obtain a higher-paying code, repeated leading queries, query without clinical indicators, or retroactive alteration without proper process requires compliance review.",
    commonErrors: "Querying simply because a higher-specificity code exists, omitting contradictory evidence, and presenting only one desired diagnostic option.",
    examFocus: "Choose the query that is clinically supported, neutral, complete, and nonleading.",
    glossary: [
      { term: "Clinical indicators", definition: "Documented signs, symptoms, tests, treatments, and findings that provide context for a clarification query." },
      { term: "Leading query", definition: "Query phrased in a way that improperly directs or pressures a provider toward a particular response." },
    ],
  },

  {
    id: "socialwork-suicide-risk",
    careerType: "socialWorker",
    examTag: "ASWB Clinical",
    regionScope: "US",
    category: "Assessment and Intervention Planning",
    topic: "Suicide Risk Assessment and Safety Planning",
    bottomLine: "When suicide risk is possible, assess current thoughts, intent, plan, access to lethal means, past behavior, protective factors, acute stressors, and ability to collaborate on safety; the level of response follows current risk, not discomfort with the topic.",
    coreConcept: "Direct, calm inquiry about suicide supports assessment and does not create suicidal intent; risk formulation integrates dynamic and historical factors rather than relying on one checklist score.",
    recognition: "Current intent, preparatory behavior, access to highly lethal means, recent attempt, severe agitation, intoxication, psychosis, hopelessness, or inability to engage in safety planning can indicate elevated acute risk.",
    workflow: "Establish immediate safety, ask directly about ideation and behavior, assess intent/plan/means and recent changes, identify supports and protective factors, determine the appropriate level of care, reduce access to lethal means when possible, document reasoning, and arrange follow-up.",
    interpretation: "A verbal promise not to self-harm is not a substitute for a collaborative safety plan and risk-based disposition.",
    safety: "Do not leave a person with imminent risk alone or defer emergency escalation because confidentiality is being requested.",
    redFlags: "Current intent with available means, recent serious attempt, inability to maintain safety, severe intoxication, command hallucinations, or rapidly escalating agitation requires urgent emergency evaluation.",
    commonErrors: "Using a no-suicide contract as protection, avoiding direct questions, equating denial of ideation with zero risk, and failing to document the rationale for disposition.",
    examFocus: "ASWB questions prioritize immediate safety assessment and the least restrictive disposition that still adequately manages risk.",
    glossary: [
      { term: "Safety plan", definition: "Collaborative written plan identifying warning signs, coping strategies, supports, professional resources, and means-safety actions." },
      { term: "Protective factor", definition: "Individual, relational, cultural, or environmental factor that can reduce risk or support coping." },
    ],
  },
  {
    id: "socialwork-crisis-deescalation",
    careerType: "socialWorker",
    examTag: "ASWB Clinical",
    regionScope: "US",
    category: "Intervention",
    topic: "Crisis Intervention and De-escalation",
    bottomLine: "In crisis, first establish safety and regulation, reduce stimulation, use calm nonthreatening communication, clarify the immediate problem, mobilize supports, and move to problem solving only when the person can participate.",
    coreConcept: "High arousal narrows attention and problem-solving capacity, so effective de-escalation lowers threat and restores enough regulation for collaborative decision making.",
    recognition: "Pacing, clenched posture, escalating volume, threats, disorganization, panic, dissociation, inability to process complex questions, or rapidly changing behavior signals increasing crisis intensity.",
    workflow: "Assess immediate danger, maintain safe positioning and exit access, use short calm statements, validate emotion without agreeing to unsafe behavior, offer limited choices, reduce audience/stimulation, involve support or emergency resources as indicated, and reassess continuously.",
    interpretation: "Validation acknowledges experience; it does not require endorsing delusions, threats, or inaccurate beliefs.",
    safety: "Avoid cornering, arguing, sudden touch, power struggles, or lengthy interpretation when the person is acutely escalated.",
    redFlags: "Weapon access, specific threats, escalating violence, inability to redirect, severe intoxication, acute psychosis with dangerous behavior, or medical instability requires emergency support.",
    commonErrors: "Demanding insight during peak escalation, matching the person's volume, presenting too many choices, and prioritizing paperwork over immediate safety.",
    examFocus: "ASWB items usually reward safety, engagement, and de-escalation before deeper therapeutic exploration.",
    glossary: [
      { term: "De-escalation", definition: "Communication and environmental strategies intended to reduce acute arousal and risk while preserving dignity." },
      { term: "Crisis", definition: "State in which usual coping is insufficient and immediate functioning or safety is threatened." },
    ],
  },
  {
    id: "socialwork-ethics-boundaries",
    careerType: "socialWorker",
    examTag: "ASWB Clinical",
    regionScope: "US",
    category: "Professional Values and Ethics",
    topic: "Professional Boundaries, Confidentiality, and Ethical Decision Making",
    bottomLine: "Resolve ethical dilemmas by identifying competing duties, client welfare, law and policy, informed consent, conflicts of interest, consultation needs, and the least harmful ethically defensible action.",
    coreConcept: "Boundaries protect the professional relationship from exploitation, role confusion, impaired judgment, and conflicts between client needs and worker interests.",
    recognition: "Gifts, social-media contact, dual relationships, personal disclosure, financial entanglement, requests for secrecy, or services to closely connected people can create boundary or confidentiality risk.",
    workflow: "Define the ethical issue, review applicable standards/law/policy, assess client impact and power imbalance, consider alternatives, seek supervision or consultation when needed, communicate limits clearly, and document the decision process.",
    interpretation: "Not every incidental dual relationship is avoidable or unethical, especially in small communities, but risk, alternatives, boundaries, and documentation still require active management.",
    safety: "Do not use personal need, convenience, or fear of upsetting the client as the reason to cross a boundary or conceal a conflict.",
    redFlags: "Sexualized relationship, financial exploitation, serious confidentiality breach, falsification, retaliation, or practice outside competence requires immediate ethical and organizational escalation.",
    commonErrors: "Applying rigid rules without context, promising absolute confidentiality, and waiting for harm before seeking consultation.",
    examFocus: "ASWB questions often favor consultation and a reasoned ethical process before unilateral action when no immediate safety emergency exists.",
    glossary: [
      { term: "Dual relationship", definition: "Situation in which a social worker has another role or relationship with a client in addition to the professional role." },
      { term: "Conflict of interest", definition: "Situation in which personal, financial, or other interests could interfere with professional judgment or client welfare." },
    ],
  },
  {
    id: "socialwork-abuse-reporting",
    careerType: "socialWorker",
    examTag: "ASWB Clinical",
    regionScope: "US",
    category: "Professional Practice",
    topic: "Abuse, Neglect, and Mandatory Reporting Decisions",
    bottomLine: "When abuse or neglect is suspected, prioritize immediate safety, know the reporting duties that apply in the jurisdiction and role, make required reports promptly, and avoid conducting an investigation that belongs to protective services or law enforcement.",
    coreConcept: "Mandatory reporting thresholds and covered populations vary by jurisdiction, but clinicians generally act on reasonable suspicion rather than waiting to prove abuse themselves.",
    recognition: "Inconsistent injury history, delay in care, patterned injuries, fear of caregiver, coercive control, unsafe living conditions, exploitation, malnutrition, or disclosure can raise concern.",
    workflow: "Assess immediate danger and medical needs, clarify only enough information to determine the concern, consult law/policy when needed without delaying an urgent report, file with the appropriate authority, explain limits of confidentiality as appropriate, document facts and actions, and continue supportive care.",
    interpretation: "A client's request that suspected abuse remain secret does not override a legally applicable reporting duty, though the worker should disclose only what is required and maintain a supportive stance.",
    safety: "Do not confront a suspected perpetrator in a way that increases danger or coach the client into a detailed forensic narrative.",
    redFlags: "Immediate danger, severe injury, sexual assault, unsafe child or dependent adult returning to the alleged perpetrator, or escalating violence requires urgent protective response.",
    commonErrors: "Waiting for certainty, conducting an independent investigation, making promises of secrecy before discussing limits, and failing to document objective observations.",
    examFocus: "ASWB items distinguish reasonable-suspicion reporting from proof gathering and place immediate safety first.",
    glossary: [
      { term: "Mandatory reporting", definition: "Legally required report to a designated authority when specified concerns and thresholds are met." },
      { term: "Reasonable suspicion", definition: "Good-faith concern based on available facts that can trigger protective action without proof beyond doubt." },
    ],
  },
  {
    id: "socialwork-case-management",
    careerType: "socialWorker",
    examTag: "ASWB Clinical",
    regionScope: "US",
    category: "Intervention",
    topic: "Case Management, Resource Coordination, and Discharge Planning",
    bottomLine: "Effective case management aligns client goals, functional needs, risk, eligibility, informal supports, community resources, and follow-up into a realistic plan that the client can actually access.",
    coreConcept: "A referral is not a completed intervention until barriers such as transportation, cost, language, cognition, waitlists, documentation, and client readiness are addressed.",
    recognition: "Repeated missed appointments, medication access problems, housing instability, caregiver strain, lack of transportation, insurance gaps, or unsafe discharge environment can undermine an otherwise sound plan.",
    workflow: "Assess priorities and strengths, define goals with the client, identify resources and eligibility, obtain consent for coordination, make warm handoffs when possible, confirm access barriers, document the plan, and follow up on high-risk transitions.",
    interpretation: "The most comprehensive service is not always the best referral if the client cannot realistically reach, afford, understand, or accept it.",
    safety: "Do not discharge a high-risk client with a list of phone numbers when immediate shelter, medication, supervision, or crisis needs remain unresolved.",
    redFlags: "Unsafe housing, no access to essential medication or equipment, active abuse, severe caregiver collapse, inability to meet basic needs, or no safe follow-up after acute crisis requires escalation.",
    commonErrors: "Making referrals without client input, assuming resource availability, and failing to verify whether the receiving service actually accepted the referral.",
    examFocus: "ASWB scenarios favor client-centered coordination and addressing practical barriers before labeling a client noncompliant.",
    glossary: [
      { term: "Warm handoff", definition: "Direct transfer or introduction to another provider or service that improves continuity compared with a passive referral." },
      { term: "Discharge planning", definition: "Coordinated process preparing for safe transition from one level or setting of care to another." },
    ],
  },

  {
    id: "psychotherapy-alliance-consent",
    careerType: "psychotherapist",
    examTag: "RP Qualifying",
    regionScope: "CAN",
    category: "Professional Practice",
    topic: "Therapeutic Alliance, Consent, and Collaborative Goals",
    bottomLine: "Establish informed consent, clarify the therapeutic relationship and its limits, develop goals collaboratively, and revisit consent when the nature, risk, or direction of treatment materially changes.",
    coreConcept: "Consent is an ongoing process tied to capacity, information, voluntariness, and the specific intervention rather than a one-time signature.",
    recognition: "Client uncertainty about purpose, coercion from another person, changing treatment modality, unclear fees or communication boundaries, language barriers, or fluctuating capacity can undermine valid consent.",
    workflow: "Explain role and treatment approach, discuss benefits/risks/alternatives and confidentiality limits, assess understanding and voluntariness, identify goals, document consent, invite questions, and revisit as circumstances change.",
    interpretation: "Agreement to attend therapy does not automatically equal informed consent to every intervention or collateral disclosure.",
    safety: "Do not use therapeutic authority to pressure a client into a nonurgent intervention they do not understand or want.",
    redFlags: "Apparent incapacity for the decision, coercion, major misunderstanding of confidentiality, boundary confusion, or request for treatment outside competence requires consultation or modified consent process.",
    commonErrors: "Treating the intake form as permanent consent, using jargon without checking understanding, and setting clinician-owned goals disconnected from client priorities.",
    examFocus: "RP-style professional-practice questions favor explicit consent, collaboration, scope awareness, and documentation when the treatment relationship changes.",
    glossary: [
      { term: "Informed consent", definition: "Voluntary agreement based on adequate information, understanding, and capacity for the decision." },
      { term: "Therapeutic alliance", definition: "Collaborative relationship involving agreement on goals and tasks plus a trusting therapeutic bond." },
    ],
  },
  {
    id: "psychotherapy-risk-escalation",
    careerType: "psychotherapist",
    examTag: "RP Qualifying",
    regionScope: "CAN",
    category: "Assessment and Crisis",
    topic: "Risk Assessment, Confidentiality Limits, and Escalation",
    bottomLine: "Assess acute risk directly, explain confidentiality limits clearly, consult or escalate when safety exceeds outpatient management, and disclose only what is necessary under applicable law, standards, and policy.",
    coreConcept: "Risk assessment is continuous clinical reasoning that integrates current intent, behavior, access to means, history, mental state, supports, and ability to collaborate on safety.",
    recognition: "Escalating suicidal intent, violent intent, command hallucinations, severe intoxication, inability to care for basic needs, or rapid deterioration can exceed routine psychotherapy management.",
    workflow: "Establish immediate safety, assess the specific risk, review supports and means, determine whether emergency or higher-level evaluation is needed, consult when feasible, communicate the plan, make necessary disclosures, document reasoning, and arrange follow-up.",
    interpretation: "Confidentiality is fundamental but not absolute; the therapist should know the legal and professional basis before breaching it except when immediate emergency action cannot safely wait.",
    safety: "Do not manage imminent life-threatening risk solely through a future appointment or a promise from the client.",
    redFlags: "Imminent suicidal or homicidal intent, inability to maintain safety, severe psychosis, medical compromise, or dangerous intoxication requires urgent emergency response.",
    commonErrors: "Avoiding direct questions, making broad disclosures beyond the safety purpose, and documenting only the final disposition without the reasoning.",
    examFocus: "Choose proportionate safety action, consultation, and minimal necessary disclosure while preserving the therapeutic relationship where possible.",
    glossary: [
      { term: "Risk formulation", definition: "Clinical synthesis of acute and chronic risk factors, protective factors, and current circumstances to guide management." },
      { term: "Confidentiality limit", definition: "Circumstance in which privacy may be restricted because of legal, ethical, or safety obligations." },
    ],
  },
  {
    id: "psychotherapy-cbt-formulation",
    careerType: "psychotherapist",
    examTag: "RP Qualifying",
    regionScope: "CAN",
    category: "Clinical Intervention",
    topic: "CBT Case Formulation and Intervention Planning",
    bottomLine: "Use a collaborative formulation linking situations, thoughts, emotions, physiology, and behaviours to maintaining cycles, then select interventions that test or change the most relevant mechanism.",
    coreConcept: "CBT is not simply positive thinking; it examines how interpretations and behaviour patterns maintain distress and uses structured experiments, skills, and exposure when appropriate.",
    recognition: "Avoidance, safety behaviours, rumination, catastrophic interpretation, all-or-nothing thinking, withdrawal, and reassurance seeking can maintain symptoms across different presentations.",
    workflow: "Define the current problem and goals, map a recent example, identify maintaining thoughts and behaviours, normalize the model, choose one targeted intervention, assign collaborative between-session practice when appropriate, and review outcomes.",
    interpretation: "A belief that feels strongly true is still a hypothesis to examine; effective cognitive work uses evidence and behavioural learning rather than therapist argument.",
    safety: "Do not launch intense exposure or trauma processing before confirming readiness, consent, stability, and an appropriate treatment rationale.",
    redFlags: "Acute suicidality, severe dissociation, unstable psychosis, uncontrolled substance withdrawal, or medical instability requires stabilization or higher-level care before routine CBT tasks.",
    commonErrors: "Challenging thoughts before understanding their function, giving worksheets without formulation, and treating reassurance as cognitive restructuring.",
    examFocus: "RP questions often test whether the intervention follows logically from the collaboratively identified maintaining mechanism.",
    glossary: [
      { term: "Case formulation", definition: "Working hypothesis explaining how current problems developed and are maintained, used to guide individualized treatment." },
      { term: "Safety behaviour", definition: "Action intended to prevent feared outcomes that can inadvertently maintain anxiety by blocking corrective learning." },
    ],
  },
  {
    id: "psychotherapy-trauma-informed",
    careerType: "psychotherapist",
    examTag: "RP Qualifying",
    regionScope: "CAN",
    category: "Clinical Intervention",
    topic: "Trauma-Informed Care, Stabilization, and Pacing",
    bottomLine: "Trauma-informed psychotherapy prioritizes safety, choice, collaboration, predictability, cultural humility, and pacing; detailed trauma processing is not the first step when the client cannot remain sufficiently regulated and present.",
    coreConcept: "Trauma responses can involve hyperarousal, avoidance, intrusive memories, negative beliefs, dissociation, and altered threat perception; treatment should reduce reenactment and restore agency.",
    recognition: "Dissociation, flooding, shutdown, marked startle, avoidance, fragmented recall, inability to stay oriented, or destabilization after sessions signals a need to adjust pace and method.",
    workflow: "Establish safety and consent, assess current stability and supports, build grounding/regulation skills, create a shared treatment rationale, monitor window of tolerance, process trauma only when appropriate, and return to stabilization when needed.",
    interpretation: "Avoidance can maintain trauma symptoms, but forcing disclosure or exposure before readiness can increase dropout, dissociation, and loss of trust.",
    safety: "Do not require detailed recounting as proof of trauma or proceed when the client is repeatedly losing orientation or acute safety is unstable.",
    redFlags: "Severe dissociation, current abuse, acute suicidality, psychotic decompensation, uncontrolled substance withdrawal, or inability to return to baseline after sessions requires stabilization and possible higher-level support.",
    commonErrors: "Assuming all trauma work requires immediate narrative exposure, equating emotional intensity with therapeutic progress, and removing client choice to maintain a protocol timetable.",
    examFocus: "Select the intervention that preserves safety and agency while matching the client's current regulation capacity.",
    glossary: [
      { term: "Window of tolerance", definition: "Range of arousal within which a person can remain sufficiently regulated to process information and engage effectively." },
      { term: "Grounding", definition: "Technique used to orient attention to the present and reduce overwhelming dissociation or arousal." },
    ],
  },
  {
    id: "psychotherapy-boundaries-documentation",
    careerType: "psychotherapist",
    examTag: "RP Qualifying",
    regionScope: "CAN",
    category: "Professional Practice",
    topic: "Boundaries, Documentation, Privacy, and Professional Communication",
    bottomLine: "Maintain clear professional boundaries and records that are timely, factual, clinically relevant, privacy-conscious, and sufficient to support continuity, accountability, and the rationale for significant decisions.",
    coreConcept: "Therapeutic records are professional documents, not personal process notes; wording should distinguish client report, therapist observation, formulation, and action.",
    recognition: "Frequent personal messaging, social-media contact, gifts, dual-role pressure, vague risk notes, undocumented consultation, or storing client data outside approved systems increases professional risk.",
    workflow: "Set communication and boundary expectations early, document consent and clinically significant contacts, use approved systems, record assessment/intervention/response/plan, seek consultation for boundary complexity, and correct records transparently when needed.",
    interpretation: "A concise record can be adequate when it captures clinically material information and reasoning; excessive irrelevant personal detail can create its own privacy risk.",
    safety: "Do not use personal devices/accounts or informal channels for protected client information when they are not approved for the purpose.",
    redFlags: "Sexualized boundary crossing, falsified documentation, lost confidential data, unauthorized recording, or serious privacy breach requires immediate professional/organizational escalation.",
    commonErrors: "Documenting labels instead of observable facts, omitting risk reasoning, correcting notes by deleting prior content, and using casual messaging without clear boundaries.",
    examFocus: "Professional-practice questions favor transparent documentation, consultation, secure communication, and boundaries tied to client welfare.",
    glossary: [
      { term: "Clinical record", definition: "Professional documentation of relevant assessment, intervention, response, consent, consultation, and care planning." },
      { term: "Boundary crossing", definition: "Departure from customary professional boundaries that requires evaluation of purpose, risk, and client impact." },
    ],
  },

  {
    id: "addictions-screening-assessment",
    careerType: "addictionsCounsellor",
    examTag: "IC&RC CAC",
    regionScope: "BOTH",
    category: "Screening and Assessment",
    topic: "Substance Use Screening, Assessment, and Level-of-Care Reasoning",
    bottomLine: "Screen broadly, assess substance pattern and consequences in context, identify withdrawal and medical/psychiatric risk, and match services to severity, recovery environment, readiness, and safety rather than substance quantity alone.",
    coreConcept: "A thorough assessment integrates intoxication/withdrawal potential, biomedical conditions, emotional/behavioural needs, readiness, relapse risk, and recovery environment.",
    recognition: "Prior severe withdrawal, polysubstance use, overdose history, unstable housing, pregnancy, major medical illness, suicidality, or inability to stop despite severe consequences can increase level-of-care needs.",
    workflow: "Establish rapport, screen without judgment, clarify substances/route/frequency/last use, assess withdrawal and overdose history, evaluate medical and mental-health risk, identify supports and goals, determine referral needs, and document rationale.",
    interpretation: "A person using a smaller amount can still require urgent medical care if withdrawal history, comorbidity, route, or current symptoms create high risk.",
    safety: "Do not attempt to manage potentially dangerous withdrawal solely through counselling when medical assessment is indicated.",
    redFlags: "Seizure history with withdrawal, delirium, severe autonomic instability, overdose, pregnancy with high-risk use, acute suicidality, or severe intoxication requires urgent medical/emergency escalation.",
    commonErrors: "Focusing only on the primary reported substance, equating motivation with low risk, and recommending outpatient counselling before checking withdrawal safety.",
    examFocus: "IC&RC-style items prioritize safety screening and appropriate referral before routine counselling when acute risk is present.",
    glossary: [
      { term: "Withdrawal", definition: "Physiologic and psychological syndrome that can occur when a dependent substance is reduced or stopped." },
      { term: "Level of care", definition: "Intensity and setting of services matched to clinical severity, risks, supports, and treatment needs." },
    ],
  },
  {
    id: "addictions-motivational-interviewing",
    careerType: "addictionsCounsellor",
    examTag: "IC&RC CAC",
    regionScope: "BOTH",
    category: "Counselling",
    topic: "Motivational Interviewing and Change Talk",
    bottomLine: "Use partnership, acceptance, compassion, and evocation to help clients voice their own reasons for change; avoid arguing for change harder than the client does.",
    coreConcept: "Motivational interviewing strengthens motivation by exploring ambivalence and selectively evoking change talk rather than confronting resistance.",
    recognition: "Statements of desire, ability, reasons, need, commitment, activation, or steps toward change provide openings to deepen change talk; sustain talk reflects the other side of ambivalence.",
    workflow: "Engage with open questions and reflections, focus on a shared target, evoke the client's reasons and confidence, respond to sustain talk without confrontation, summarize change language, and plan only when readiness emerges.",
    interpretation: "Resistance often reflects interaction, not a fixed client trait; increasing confrontation can strengthen sustain talk.",
    safety: "Motivational style does not replace direct safety action when overdose, withdrawal, suicidality, violence, or medical instability requires urgent intervention.",
    redFlags: "Acute overdose, dangerous withdrawal, inability to remain conscious, immediate self-harm risk, or severe medical symptoms requires emergency response before motivational work.",
    commonErrors: "Giving a persuasion speech, labeling the client resistant, asking rapid-fire questions without reflections, and forcing a change plan before the client is ready.",
    examFocus: "Choose reflections and questions that evoke the client's own reasons for change rather than expert-driven confrontation.",
    glossary: [
      { term: "Change talk", definition: "Client language favoring movement toward change, including desire, ability, reasons, need, commitment, activation, and steps." },
      { term: "Sustain talk", definition: "Client language favoring continuation of the current behavior or status quo." },
    ],
  },
  {
    id: "addictions-withdrawal-escalation",
    careerType: "addictionsCounsellor",
    examTag: "IC&RC CAC",
    regionScope: "BOTH",
    category: "Case Management and Crisis",
    topic: "Withdrawal Risk Recognition and Medical Escalation",
    bottomLine: "Counsellors must recognize when withdrawal can become medically dangerous, identify high-risk history and current symptoms, and arrange appropriate medical assessment rather than treating all withdrawal as a counselling problem.",
    coreConcept: "Withdrawal risk differs by substance; alcohol and sedative-hypnotic withdrawal can be life threatening, while opioid withdrawal is usually not fatal by itself but can still create severe dehydration, relapse, overdose, pregnancy, or comorbidity risks.",
    recognition: "Prior withdrawal seizures or delirium, severe tremor, hallucinations, autonomic instability, confusion, persistent vomiting, polysubstance dependence, pregnancy, or serious medical illness increases concern.",
    workflow: "Ask what was used and when, assess prior withdrawal complications, observe current symptoms and mental status, identify medical/psychiatric comorbidity, determine whether emergency or supervised withdrawal management is needed, facilitate transfer, and document.",
    interpretation: "A client requesting to detox at home may still require medical care when historical or current risk exceeds what can be safely monitored outside a medical setting.",
    safety: "Do not advise abrupt unsupervised cessation of substances with potentially dangerous withdrawal when dependence and risk are significant.",
    redFlags: "Seizure, delirium, severe confusion, hallucinations with instability, extreme vital-sign abnormality, uncontrolled vomiting, chest pain, or reduced consciousness requires emergency medical response.",
    commonErrors: "Assuming withdrawal severity from last-use amount alone, overlooking sedative use, and continuing an intake interview while medical deterioration is occurring.",
    examFocus: "The safest answer identifies when to stop counselling and obtain medical evaluation.",
    glossary: [
      { term: "Withdrawal seizure", definition: "Seizure occurring in the context of abrupt reduction or cessation of a substance capable of producing physiologic dependence." },
      { term: "Delirium", definition: "Acute disturbance of attention and awareness with fluctuating cognition that can represent a medical emergency." },
    ],
  },
  {
    id: "addictions-relapse-recovery",
    careerType: "addictionsCounsellor",
    examTag: "IC&RC CAC",
    regionScope: "BOTH",
    category: "Counselling",
    topic: "Relapse Prevention, Overdose Risk, and Recovery Planning",
    bottomLine: "Relapse prevention identifies individualized triggers, warning signs, coping responses, supports, treatment and medication resources, and an overdose-safety plan without framing recurrence of use as moral failure.",
    coreConcept: "Return to use often develops through accumulating cues, stressors, decisions, and reduced coping before substance use occurs; early intervention in the chain creates more options.",
    recognition: "Isolation, missed treatment, romanticizing past use, reduced recovery routines, sleep disruption, high-risk contacts, craving escalation, and stopping medications can be early warning signs.",
    workflow: "Review recent patterns nonjudgmentally, map triggers and warning signs, identify coping and support steps, strengthen recovery environment, discuss overdose risk after reduced tolerance, connect with medication/treatment resources when relevant, and create a plan for rapid re-engagement after a lapse.",
    interpretation: "A lapse does not require abandoning treatment goals; it provides data about vulnerabilities and may require a higher level of care or different supports.",
    safety: "Explicitly address overdose risk after abstinence or reduced tolerance and ensure emergency resources are available according to local practice and client circumstances.",
    redFlags: "Recent nonfatal overdose, rapidly escalating use, solitary high-risk use, suicidal intent, pregnancy, severe withdrawal risk, or loss of housing/support may require urgent higher-level intervention.",
    commonErrors: "Using shame as motivation, creating a generic trigger list, failing to discuss lowered tolerance, and treating recurrence as proof that treatment failed.",
    examFocus: "IC&RC questions favor collaborative, individualized recovery planning and rapid re-engagement rather than punitive responses.",
    glossary: [
      { term: "Lapse", definition: "A return to substance use after a period of reduced or no use that can be addressed without assuming full abandonment of recovery goals." },
      { term: "Tolerance", definition: "Reduced response to a substance after repeated exposure, often decreasing after abstinence and increasing overdose risk on return to prior doses." },
    ],
  },
];
