import type { AlliedAuthoredTopic } from "./types";

export const alliedTopics02: AlliedAuthoredTopic[] = [
  {
    id: "mlt-cbc-indices",
    careerType: "mlt",
    examTag: "ASCP MLT",
    regionScope: "BOTH",
    category: "Hematology",
    topic: "CBC Indices and Anemia Pattern Recognition",
    bottomLine: "Interpret hemoglobin, hematocrit, MCV, MCHC, RDW, reticulocyte response, and smear morphology together before assigning an anemia pattern.",
    coreConcept: "Red-cell indices classify size and hemoglobinization, while RDW and reticulocytes add information about heterogeneity and marrow response.",
    recognition: "Microcytosis suggests impaired hemoglobin production, macrocytosis suggests altered DNA synthesis or reticulocytosis among other causes, and normocytic anemia requires attention to marrow response and clinical context.",
    workflow: "Verify analyzer flags and specimen integrity, review indices, calculate or confirm reticulocyte response, inspect the smear when criteria are met, correlate with prior results, and escalate unexpected critical findings.",
    interpretation: "A high RDW with microcytosis supports mixed cell sizes often seen as iron deficiency evolves, whereas a relatively uniform microcytosis can fit thalassemia trait when the rest of the pattern supports it.",
    safety: "Do not report implausible index combinations without checking for cold agglutinins, lipemia, hemolysis, clots, or other preanalytic and analytic interference.",
    redFlags: "Critical hemoglobin, fragmented cells, blasts, extreme leukocytosis, platelet clumps, or results inconsistent with the previous baseline require prompt verification and communication.",
    commonErrors: "Classifying anemia from MCV alone, ignoring reticulocyte response, and accepting an instrument result despite obvious internal inconsistency.",
    examFocus: "ASCP-style items reward pattern integration across indices, smear, and production response rather than memorizing one cutoff.",
    glossary: [
      { term: "MCV", definition: "Mean corpuscular volume, the average red blood cell volume used to classify cell size." },
      { term: "RDW", definition: "Red cell distribution width, a measure of variability in red blood cell size." },
    ],
  },
  {
    id: "mlt-peripheral-smear",
    careerType: "mlt",
    examTag: "ASCP MLT",
    regionScope: "BOTH",
    category: "Hematology",
    topic: "Peripheral Blood Smear Review",
    bottomLine: "A smear review validates automated findings, characterizes morphology, and identifies cells or artifacts that may require urgent manual confirmation or pathologist review.",
    coreConcept: "Automated analyzers quantify cells efficiently but morphology and abnormal populations still require microscopic correlation when flags or clinical thresholds are triggered.",
    recognition: "Schistocytes, spherocytes, target cells, blasts, atypical lymphocytes, platelet clumps, toxic neutrophil changes, and parasites each carry different diagnostic and reporting implications.",
    workflow: "Confirm specimen quality, select the monolayer, assess overall distribution at low power, perform the differential in an appropriate area, evaluate RBC and platelet morphology, document findings, and follow escalation criteria.",
    interpretation: "Morphology should be graded consistently and correlated with indices; apparent thrombocytopenia with platelet clumps can represent EDTA-associated pseudothrombocytopenia rather than true low platelets.",
    safety: "Potential blasts, significant schistocytosis, suspected malaria, or other critical morphology must follow laboratory urgent-review and communication policy.",
    redFlags: "New blasts, marked schistocytes with anemia and thrombocytopenia, intracellular parasites, or severe neutropenia requires prompt escalation.",
    commonErrors: "Reading the feather edge as the primary differential area, calling stain precipitate an inclusion, and reporting platelet estimate without checking for clumping.",
    examFocus: "Know where to examine the smear, which morphology fits each process, and which findings change urgency.",
    glossary: [
      { term: "Monolayer", definition: "Smear region where red cells are close but not substantially overlapping and morphology is best assessed." },
      { term: "Schistocyte", definition: "Fragmented red blood cell associated with mechanical or microangiopathic injury." },
    ],
  },
  {
    id: "mlt-coag-pt-aptt",
    careerType: "mlt",
    examTag: "ASCP MLT",
    regionScope: "BOTH",
    category: "Coagulation",
    topic: "PT, INR, aPTT, and Mixing Studies",
    bottomLine: "Interpret screening coagulation tests by pathway pattern and use a mixing study to distinguish factor deficiency from an inhibitor when appropriate.",
    coreConcept: "PT primarily reflects the extrinsic/common pathways and aPTT the intrinsic/common pathways; correction after mixing supports deficiency while failure to correct suggests an inhibitor, with important exceptions.",
    recognition: "Isolated prolonged PT, isolated prolonged aPTT, or prolongation of both narrows the differential when anticoagulant exposure and specimen quality are considered.",
    workflow: "Check fill volume, clotting, hematocrit considerations and medication history, repeat or verify as required, perform mixing study when indicated, then proceed to factor or inhibitor testing according to the pattern.",
    interpretation: "Immediate correction that loses correction after incubation can fit a time-dependent inhibitor; lupus anticoagulant may prolong phospholipid-dependent tests without implying a bleeding tendency.",
    safety: "Underfilled citrate tubes alter the blood-to-anticoagulant ratio and can falsely prolong results; do not interpret compromised specimens as true coagulopathy.",
    redFlags: "Unexpected critical prolongation, suspected heparin contamination, active bleeding with severe abnormalities, or a new inhibitor pattern requires rapid verification and communication.",
    commonErrors: "Ignoring specimen fill, assuming every prolonged aPTT means bleeding risk, and interpreting a mixing study without considering incubation and anticoagulants.",
    examFocus: "ASCP questions commonly test pathway localization and correction-versus-inhibitor logic.",
    glossary: [
      { term: "Mixing study", definition: "Test mixing patient plasma with normal plasma to help differentiate factor deficiency from an inhibitor." },
      { term: "INR", definition: "Standardized expression of prothrombin time used primarily to monitor vitamin K antagonist therapy." },
    ],
  },
  {
    id: "mlt-blood-bank-abo-rh",
    careerType: "mlt",
    examTag: "ASCP MLT",
    regionScope: "BOTH",
    category: "Transfusion Medicine",
    topic: "ABO/Rh Typing and Discrepancy Resolution",
    bottomLine: "ABO typing requires agreement between forward and reverse testing in appropriate patients; discrepancies must be resolved before routine transfusion decisions are finalized.",
    coreConcept: "Forward typing detects antigens on red cells and reverse typing detects expected naturally occurring antibodies in plasma or serum.",
    recognition: "Weak or missing reactions, mixed-field agglutination, recent transfusion, stem-cell transplant, age, immunodeficiency, cold-reactive antibodies, and technical error can produce discrepancies.",
    workflow: "Repeat and verify identification, inspect reactions and history, wash or modify testing as indicated, use additional reagent cells or temperatures when appropriate, document resolution, and use safe emergency products if transfusion cannot wait.",
    interpretation: "Unexpected reverse reactions may reflect cold antibodies or rouleaux; missing reverse antibodies can occur in neonates, older adults, or immunosuppressed patients.",
    safety: "Never force an ABO interpretation to fit an expected type. In unresolved urgent situations, use institutionally approved emergency-release components and continue the investigation.",
    redFlags: "ABO mismatch, mixed-field pattern without explanation, incompatible crossmatch with urgent transfusion need, or historical type conflict requires immediate escalation.",
    commonErrors: "Reading reactions after inappropriate delay, ignoring transfusion history, and treating forward typing alone as sufficient in routine adult testing.",
    examFocus: "Know the expected antigen-antibody relationship and choose the next test that resolves the specific discrepancy.",
    glossary: [
      { term: "Forward typing", definition: "ABO testing of patient red cells with anti-A and anti-B reagents." },
      { term: "Reverse typing", definition: "ABO testing of patient plasma or serum against reagent A1 and B cells." },
    ],
  },
  {
    id: "mlt-antibody-screen-id",
    careerType: "mlt",
    examTag: "ASCP MLT",
    regionScope: "BOTH",
    category: "Transfusion Medicine",
    topic: "Antibody Screening and Identification",
    bottomLine: "A positive antibody screen requires systematic pattern analysis, rule-outs using appropriately antigen-typed cells, autocontrol/DAT context, and confirmation with antigen-negative compatible units when clinically significant antibodies are identified.",
    coreConcept: "Reaction phase, strength, dosage, antigen profile, and patient phenotype or genotype help identify alloantibodies and distinguish them from autoantibodies or nonspecific reactivity.",
    recognition: "Panreactivity, variable panel reactions, dosage patterns, enzyme effects, and autocontrol results point toward different antibody mechanisms.",
    workflow: "Review history, confirm screen, run panel, compare reaction pattern with antigen matrix, rule out antibodies with adequate homozygous cells when required, phenotype/genotype the patient as appropriate, and select antigen-negative units.",
    interpretation: "A positive autocontrol with broad reactivity raises concern for autoantibody, whereas a negative autocontrol with a reproducible panel pattern supports alloantibody more strongly.",
    safety: "Do not stop after identifying one antibody if additional clinically significant specificities have not been excluded.",
    redFlags: "History of significant antibody, incompatible emergency transfusion, suspected delayed hemolytic reaction, or inability to locate compatible units requires transfusion-medicine escalation.",
    commonErrors: "Ruling out with heterozygous cells for dosage-prone antibodies, ignoring historical antibodies no longer detectable, and selecting units before completing clinically relevant exclusions.",
    examFocus: "Panel questions are pattern-recognition problems: phase, dosage, autocontrol, and antigen matrix must all agree.",
    glossary: [
      { term: "Dosage", definition: "Stronger antibody reaction with cells homozygous for the corresponding antigen than with heterozygous cells." },
      { term: "Autocontrol", definition: "Testing patient serum or plasma against the patient's own red cells to assess self-reactivity." },
    ],
  },
  {
    id: "mlt-gram-stain",
    careerType: "mlt",
    examTag: "ASCP MLT",
    regionScope: "BOTH",
    category: "Microbiology",
    topic: "Gram Stain Technique and Interpretation",
    bottomLine: "A valid Gram stain depends on smear quality and controlled decolorization; report Gram reaction, morphology, arrangement, inflammatory cells, and specimen-quality clues in clinical context.",
    coreConcept: "Gram-positive cell walls retain the crystal-violet iodine complex after decolorization, while gram-negative organisms are decolorized and take up the counterstain.",
    recognition: "Gram-positive cocci in clusters, gram-positive cocci in chains, gram-negative rods, gram-negative diplococci, yeast, and mixed flora each guide culture workup and urgent communication differently.",
    workflow: "Prepare an appropriate thin smear, fix, apply primary stain, mordant, controlled decolorizer and counterstain, review under oil immersion, correlate with specimen quality, and document promptly.",
    interpretation: "Overdecolorization can make gram-positive organisms appear gram negative; thick smears and old cultures can also produce gram-variable results.",
    safety: "Critical direct-smear findings from sterile sites or positive blood cultures must be communicated according to laboratory policy without waiting for final identification.",
    redFlags: "Organisms in CSF, unexpected organisms from sterile body fluids, mixed morphologies suggesting polymicrobial sepsis, or discrepancy with culture requires urgent review.",
    commonErrors: "Overdecolorizing, using an overly thick smear, reading stain precipitate as bacteria, and ignoring sputum contamination indicators.",
    examFocus: "Technique errors often appear as interpretation questions; identify what procedural fault would create the observed pattern.",
    glossary: [
      { term: "Mordant", definition: "Reagent such as iodine that forms a complex with the primary stain and enhances retention." },
      { term: "Decolorization", definition: "Critical Gram stain step that differentiates organisms based on cell-wall properties." },
    ],
  },
  {
    id: "mlt-culture-ast",
    careerType: "mlt",
    examTag: "ASCP MLT",
    regionScope: "BOTH",
    category: "Microbiology",
    topic: "Culture Workup and Antimicrobial Susceptibility Testing",
    bottomLine: "Identify clinically significant isolates with appropriate methods, perform susceptibility testing under standardized conditions, apply current interpretive criteria, and recognize intrinsic or unusual resistance patterns that require confirmation.",
    coreConcept: "Susceptibility results are only valid when organism identification, inoculum, medium, incubation, method, quality control, and breakpoints are appropriate.",
    recognition: "Unexpected resistance, skipped wells, colonies inside inhibition zones, inducible resistance patterns, or discordance between identification and susceptibility can signal technical or biologic problems.",
    workflow: "Confirm a pure clinically relevant isolate, standardize inoculum, perform the validated AST method, review QC, apply current breakpoints, investigate unusual phenotypes, and report with required comments or suppressions.",
    interpretation: "MIC is the lowest concentration preventing visible growth under test conditions; susceptibility category depends on standardized breakpoint interpretation rather than the MIC number alone.",
    safety: "Potential multidrug-resistant or high-consequence organisms may require confirmatory testing, infection-control notification, or referral according to policy.",
    redFlags: "Carbapenem resistance in Enterobacterales, vancomycin resistance in enterococci, unusual staphylococcal beta-lactam patterns, or QC failure invalidates routine release until addressed.",
    commonErrors: "Using nonstandard inoculum, reading too early or late, applying breakpoints for the wrong organism-drug pair, and reporting intrinsic resistance as if it were a tested susceptible option.",
    examFocus: "Separate method mechanics from interpretation and always check whether the QC result makes patient results reportable.",
    glossary: [
      { term: "MIC", definition: "Minimum inhibitory concentration, the lowest antimicrobial concentration that prevents visible growth under standardized conditions." },
      { term: "Breakpoint", definition: "Interpretive threshold used to categorize an organism-drug result based on clinical and microbiologic evidence." },
    ],
  },
  {
    id: "mlt-chemistry-qc",
    careerType: "mlt",
    examTag: "ASCP MLT",
    regionScope: "BOTH",
    category: "Clinical Chemistry",
    topic: "Quality Control, Westgard Rules, and Calibration",
    bottomLine: "Use quality-control data to detect random and systematic error before releasing patient results, investigate the cause, and restore acceptable performance rather than repeatedly rerunning controls without analysis.",
    coreConcept: "Control results estimate analytical stability; different rule violations suggest different error patterns and guide troubleshooting.",
    recognition: "A single extreme control, persistent shift, progressive trend, or increasing scatter each points toward different sources such as random error, calibration shift, reagent deterioration, or instrument instability.",
    workflow: "Review the rule violation and both control levels, inspect recent trends and maintenance, check reagents/calibration/environment, correct a plausible cause, rerun QC, and assess whether patient results since the last acceptable QC require review.",
    interpretation: "A shift suggests abrupt systematic change while a trend suggests gradual systematic drift; isolated scatter is more consistent with random error.",
    safety: "Do not report affected patient results while QC is unacceptable simply because repeat controls occasionally fall into range without an identified resolution.",
    redFlags: "Multiple control levels fail, calibrator or reagent lot changed, analyzer flags indicate instability, or critical patient values cluster unexpectedly requires broader investigation.",
    commonErrors: "Rerunning controls until one passes, ignoring Levey-Jennings history, and recalibrating reflexively without considering the source of error.",
    examFocus: "Match the QC pattern to random versus systematic error and choose the most logical troubleshooting step.",
    glossary: [
      { term: "Systematic error", definition: "Consistent bias affecting results in one direction, often due to calibration, reagent, or method changes." },
      { term: "Random error", definition: "Unpredictable imprecision causing scattered results around the expected mean." },
    ],
  },
  {
    id: "mlt-electrolytes-osmolality",
    careerType: "mlt",
    examTag: "ASCP MLT",
    regionScope: "BOTH",
    category: "Clinical Chemistry",
    topic: "Electrolytes, Anion Gap, and Osmolality",
    bottomLine: "Interpret sodium, potassium, chloride, bicarbonate, anion gap, glucose, renal function, and measured or calculated osmolality as a coherent physiologic pattern while checking for specimen interference.",
    coreConcept: "Electrolyte abnormalities can be true physiologic derangements or artifacts from hemolysis, contamination, hyperlipidemia, paraproteinemia, or measurement method.",
    recognition: "Unexpected severe potassium elevation in a hemolyzed specimen, sodium discordant with osmolality, or a large osmolal gap should trigger analytical and clinical correlation before interpretation.",
    workflow: "Check specimen indices and collection history, verify critical values, calculate gaps when relevant, compare with prior results, correlate with glucose/renal/acid-base data, and communicate confirmed critical findings.",
    interpretation: "An elevated anion gap suggests unmeasured anions but is influenced by albumin; an elevated osmolal gap can support unmeasured osmoles but is not specific by itself.",
    safety: "Do not report a potentially spurious critical potassium without following the laboratory's hemolysis and critical-value policy; conversely, do not delay communication of a verified life-threatening result.",
    redFlags: "Severe sodium disturbance, confirmed critical potassium, markedly elevated osmolal gap with toxic exposure concern, or rapidly changing electrolytes requires urgent communication.",
    commonErrors: "Ignoring hemolysis, treating calculated gaps as diagnoses, and overlooking method-dependent pseudohyponatremia.",
    examFocus: "Expect calculation plus interference reasoning, not arithmetic in isolation.",
    glossary: [
      { term: "Anion gap", definition: "Calculated difference between routinely measured cations and anions used to estimate unmeasured ions." },
      { term: "Osmolal gap", definition: "Difference between measured and calculated serum osmolality that can suggest unmeasured osmoles." },
    ],
  },
  {
    id: "mlt-urinalysis-sediment",
    careerType: "mlt",
    examTag: "ASCP MLT",
    regionScope: "BOTH",
    category: "Urinalysis and Body Fluids",
    topic: "Urinalysis and Urine Sediment",
    bottomLine: "Interpret physical, chemical, and microscopic urine findings together and recognize when specimen age, contamination, pH, concentration, or interfering substances explain discordant results.",
    coreConcept: "Dipstick reactions screen for analytes while microscopy identifies cells, casts, crystals, organisms, and contaminants that refine renal and urinary-tract interpretation.",
    recognition: "RBC casts suggest glomerular bleeding, WBC casts suggest renal inflammation or infection, granular casts can reflect tubular injury, and squamous epithelial cells suggest contamination.",
    workflow: "Verify specimen type and age, assess appearance and specific gravity, perform reagent-strip testing within timing requirements, centrifuge and examine sediment consistently, correlate findings, and investigate discordance.",
    interpretation: "Positive blood with few or no RBCs can reflect hemoglobin or myoglobin; positive leukocyte esterase with no WBCs may reflect lysed cells or analytic interference.",
    safety: "Fresh specimens matter because cells lyse, bacteria multiply, pH rises, and casts degrade during delay at room temperature.",
    redFlags: "Cellular casts, heavy protein with pathologic sediment, unexpected organisms in a sterilely collected specimen, or findings suggesting acute renal injury should be reported according to policy.",
    commonErrors: "Reading reagent pads outside specified timing, misidentifying artifacts as casts, and failing to correlate dipstick blood with microscopic RBCs.",
    examFocus: "Questions often present a dipstick-microscopy mismatch and ask which mechanism explains it.",
    glossary: [
      { term: "Cast", definition: "Cylindrical structure formed in renal tubules from Tamm-Horsfall protein and cellular or granular material." },
      { term: "Specific gravity", definition: "Measure reflecting urine concentration relative to water." },
    ],
  },

  {
    id: "pharmtech-prescription-processing",
    careerType: "pharmacyTech",
    examTag: "PTCB CPHT",
    regionScope: "BOTH",
    category: "Medication Order Entry and Processing",
    topic: "Prescription and Medication Order Processing",
    bottomLine: "Enter medication orders exactly, identify missing or ambiguous information, apply legal and workflow requirements, and route clinical judgment questions to the pharmacist rather than resolving them independently.",
    coreConcept: "Technician accuracy depends on preserving the prescriber's intended drug, strength, dosage form, route, directions, quantity, and patient while separating technical processing from pharmacist-only clinical decisions.",
    recognition: "Illegible directions, conflicting strength and quantity, duplicate patient profiles, unusual dosage form, missing prescriber information, or unclear route requires clarification before final processing.",
    workflow: "Match the correct patient, transcribe the order, select product and package size, calculate quantity or days supply as appropriate, generate label, perform technical checks, and send the prescription through pharmacist verification.",
    interpretation: "A computer alert may be technical, formulary, duplicate, allergy, interaction, or dose related; the technician can gather information but must not override clinical alerts outside scope.",
    safety: "Never guess an unclear prescription or change a clinically meaningful instruction to make the claim or label process successfully.",
    redFlags: "Wrong patient, wrong drug selection, look-alike/sound-alike confusion, decimal ambiguity, controlled-substance irregularity, or allergy/interaction alert requires immediate stop and escalation.",
    commonErrors: "Autopopulating old directions, selecting the wrong salt or dosage form, misreading zeroes and decimals, and bypassing an alert without pharmacist review.",
    examFocus: "PTCB items frequently test technician-versus-pharmacist scope and the safest response to incomplete or conflicting orders.",
    glossary: [
      { term: "SIG", definition: "Directions for use translated from the prescription into clear patient-facing instructions." },
      { term: "Days supply", definition: "Estimated number of days a dispensed quantity will last when taken as directed." },
    ],
  },
  {
    id: "pharmtech-calculations",
    careerType: "pharmacyTech",
    examTag: "PTCB CPHT",
    regionScope: "BOTH",
    category: "Calculations",
    topic: "Pharmacy Calculations and Dimensional Analysis",
    bottomLine: "Set up calculations with units visible, convert only when necessary, perform a reasonableness check, and use leading zero/no trailing zero conventions to reduce medication error risk.",
    coreConcept: "Dimensional analysis tracks units through concentration, dose, volume, quantity, ratio, percentage, and dilution calculations so unit cancellation verifies the setup.",
    recognition: "Dose orders stated in mg with stock in mg/mL, percentage strengths, ratio strengths, days supply, infusion rates, and reconstitution problems each require a clear unit pathway.",
    workflow: "Identify the requested unit, list known quantities, convert to compatible units, build the equation so unwanted units cancel, calculate, round only at the appropriate final stage, and estimate whether the answer is plausible.",
    interpretation: "An answer that is orders of magnitude larger or smaller than the stock container or expected dose usually signals a conversion or decimal error.",
    safety: "Use a leading zero for values below one and never use a trailing zero; avoid unsafe abbreviations and recheck high-alert calculations independently when policy requires.",
    redFlags: "Tenfold or hundredfold dose discrepancy, unclear unit, conflicting concentration, or an answer incompatible with available dosage forms requires stop-and-verify action.",
    commonErrors: "Mixing mg and mcg, rounding too early, omitting units, misreading percentage strength, and moving decimal places without a written conversion.",
    examFocus: "PTCB calculations are easiest when units drive the equation; do not rely on memorized shortcuts you cannot audit.",
    glossary: [
      { term: "Dimensional analysis", definition: "Calculation method that uses conversion factors so units cancel to the desired final unit." },
      { term: "Concentration", definition: "Amount of active ingredient contained in a defined amount of solution or product." },
    ],
  },
  {
    id: "pharmtech-sterile-compounding",
    careerType: "pharmacyTech",
    examTag: "PTCB CPHT",
    regionScope: "BOTH",
    category: "Compounding",
    topic: "Sterile Compounding and Aseptic Technique",
    bottomLine: "Sterile compounding depends on hand hygiene, garbing, controlled environments, critical-site protection, first-air principles, accurate calculations, and immediate correction of any breach in aseptic technique.",
    coreConcept: "Microbial and particulate contamination risk is controlled by engineering controls plus operator behavior; even a clean-looking preparation can be contaminated after a critical-site breach.",
    recognition: "Touching a sterile critical site, blocking first air, poor disinfection, incorrect workflow, visible particulate matter, damaged packaging, or expired component invalidates the process until corrected.",
    workflow: "Perform required hand hygiene and garbing, disinfect supplies, stage without overcrowding, protect first air, disinfect vial stoppers/ampule necks, manipulate sterile components correctly, inspect the final product, label, and document.",
    interpretation: "A contamination event is assessed by what critical site or environment was compromised, not by whether contamination is visible.",
    safety: "Never continue after touching a sterile critical site or using a compromised component; replace or re-prepare according to policy.",
    redFlags: "Broken container integrity, visible particles, wrong ingredient or concentration, environmental-control failure, or unidentified final preparation requires quarantine and escalation.",
    commonErrors: "Reaching over critical sites, failing to allow disinfectant to dry, blocking first air, reusing contaminated gloves, and confusing sterile with merely clean technique.",
    examFocus: "Questions often describe a subtle technique breach and ask whether the preparation remains acceptable.",
    glossary: [
      { term: "Critical site", definition: "Sterile surface or opening that can contact a sterile ingredient or fluid pathway and must remain protected from contamination." },
      { term: "First air", definition: "HEPA-filtered air reaching a critical site without first passing over contamination sources." },
    ],
  },
  {
    id: "pharmtech-nonsterile-compounding",
    careerType: "pharmacyTech",
    examTag: "PTCB CPHT",
    regionScope: "BOTH",
    category: "Compounding",
    topic: "Nonsterile Compounding Fundamentals",
    bottomLine: "Accurate nonsterile compounding requires verified formula, correct ingredients and calculations, appropriate equipment and geometric mixing technique, contamination control, complete documentation, and pharmacist verification.",
    coreConcept: "Uniformity and stability depend on physicochemical properties and mixing method, not just combining the listed ingredients.",
    recognition: "Potent low-dose ingredients, insoluble powders, levigation needs, hygroscopic materials, incompatible vehicles, and modified-release dosage forms require special attention.",
    workflow: "Review master formulation, calculate quantities, gather and verify ingredients, weigh or measure accurately, use appropriate mixing technique, transfer to suitable container, label with required information, document, and submit for verification.",
    interpretation: "Uneven texture, phase separation, unexpected color or odor, or yield discrepancy can indicate an error in measurement, compatibility, or technique.",
    safety: "Do not compound from an uncertain formula or substitute an ingredient without pharmacist authorization and appropriate formulation review.",
    redFlags: "Wrong ingredient, potency concern, incompatible mixture, contamination, missing lot/expiration data, or large yield discrepancy requires stop and investigation.",
    commonErrors: "Using household measuring logic, failing to account for density or displacement when relevant, skipping geometric dilution, and assigning unsupported beyond-use information.",
    examFocus: "Know the purpose of trituration, levigation, geometric dilution, and suitable dosage-form containers.",
    glossary: [
      { term: "Geometric dilution", definition: "Stepwise mixing method used to distribute a small amount of potent powder evenly through a larger diluent mass." },
      { term: "Levigation", definition: "Reducing particle size and forming a smooth paste with a small amount of suitable liquid before incorporation." },
    ],
  },
  {
    id: "pharmtech-controlled-substances",
    careerType: "pharmacyTech",
    examTag: "PTCB CPHT",
    regionScope: "US",
    category: "Federal Requirements",
    topic: "Controlled Substance Handling and Documentation",
    bottomLine: "Controlled substances require exact inventory, ordering, storage, transfer, dispensing, recordkeeping, and discrepancy procedures; technicians must know when a task is permitted and when pharmacist involvement is mandatory.",
    coreConcept: "Closed-system accountability reduces diversion by creating traceable records from acquisition through dispensing or destruction.",
    recognition: "Inventory mismatch, altered prescription, unusual refill request, incomplete transfer, missing documentation, or unexplained perpetual-inventory variance can indicate error or diversion.",
    workflow: "Follow schedule-specific ordering and receipt requirements, maintain required records, verify counts as policy directs, document dispensing, reconcile discrepancies promptly, and escalate suspicious activity.",
    interpretation: "A discrepancy is not corrected by silently adjusting the inventory; the cause must be investigated and documented according to regulation and policy.",
    safety: "Protect controlled-substance access and records, never share credentials, and do not bypass witness or documentation steps to save time.",
    redFlags: "Unexplained loss, forged or altered order, repeated count variance, unauthorized access, or missing required record requires immediate pharmacist/management escalation.",
    commonErrors: "Treating all schedules as identical, assuming a computer count replaces required records, and correcting inventory without documenting the reason.",
    examFocus: "PTCB questions test schedule distinctions, documentation, and technician scope more than memorizing isolated legal trivia.",
    glossary: [
      { term: "Diversion", definition: "Transfer of a controlled substance from lawful handling into unauthorized possession or use." },
      { term: "Perpetual inventory", definition: "Running inventory record updated with each receipt and dispensing transaction." },
    ],
  },
  {
    id: "pharmtech-medication-safety",
    careerType: "pharmacyTech",
    examTag: "PTCB CPHT",
    regionScope: "BOTH",
    category: "Medication Safety",
    topic: "Medication Errors, LASA Drugs, and High-Alert Safety",
    bottomLine: "Prevent medication errors by using standardized verification, separating look-alike/sound-alike risks, applying barcode and independent-check systems correctly, and stopping whenever patient, drug, strength, dosage form, or directions do not align.",
    coreConcept: "Most serious errors emerge from system vulnerabilities plus human factors; safety layers should make the wrong action difficult and the correct action easy to verify.",
    recognition: "Similar packaging, similar names, multiple strengths, concentrated electrolytes, insulin, anticoagulants, opioids, and decimal-dependent doses warrant heightened attention.",
    workflow: "Use two patient identifiers, read the full drug name and strength, compare product to order at multiple checkpoints, scan when required, separate LASA stock, and route discrepancies for pharmacist resolution.",
    interpretation: "Barcode technology reduces selection errors but does not replace visual verification or clinical review; a scan mismatch is a stop signal, not a nuisance alert.",
    safety: "Never override an identification mismatch or bypass a required independent check to maintain speed.",
    redFlags: "Wrong patient profile, tenfold strength difference, high-alert medication mismatch, allergy conflict, or product that does not match the label requires immediate stop and correction.",
    commonErrors: "Selecting from a drop-down by the first few letters, relying on package color, bypassing barcode alerts, and allowing interruptions during final product selection.",
    examFocus: "Choose the system-level action that prevents recurrence, not merely the action that fixes one label.",
    glossary: [
      { term: "LASA", definition: "Look-alike/sound-alike medication pairs with increased risk of selection or communication error." },
      { term: "High-alert medication", definition: "Medication with heightened risk of significant patient harm when used in error." },
    ],
  },
  {
    id: "pharmtech-inventory-storage",
    careerType: "pharmacyTech",
    examTag: "PTCB CPHT",
    regionScope: "BOTH",
    category: "Medication Management",
    topic: "Medication Inventory, Storage, and Recall Management",
    bottomLine: "Maintain medication integrity through correct storage conditions, rotation, expiration control, quarantine, recall response, and documentation from receipt through removal from stock.",
    coreConcept: "Temperature, light, moisture, security, packaging, and time can alter product stability even when the product appears normal.",
    recognition: "Temperature excursion, damaged seal, recalled lot, short dating, moisture damage, frozen product, or storage in the wrong security area requires evaluation before use.",
    workflow: "Inspect deliveries, verify quantities and conditions, place products in correct storage, rotate by expiration, monitor temperatures, quarantine questionable stock, execute recalls by lot/NDC as directed, and document disposition.",
    interpretation: "A temperature excursion does not automatically mean a product is safe or unusable; stability information and manufacturer/policy guidance determine disposition.",
    safety: "Keep quarantined and recalled stock physically separated from active inventory so it cannot be dispensed accidentally.",
    redFlags: "Cold-chain breach, controlled-substance count mismatch, counterfeit concern, recalled lot in active stock, or missing temperature documentation requires immediate escalation.",
    commonErrors: "Returning quarantined stock to shelves without authorization, checking recall by drug name but not lot, and assuming room temperature is acceptable without documented range.",
    examFocus: "Inventory questions often test the next action after a storage excursion or recall notice.",
    glossary: [
      { term: "Quarantine", definition: "Physical and system separation of stock that must not be dispensed pending investigation or disposition." },
      { term: "Cold chain", definition: "Controlled temperature pathway required to preserve stability of temperature-sensitive products." },
    ],
  },
  {
    id: "pharmtech-insurance-adjudication",
    careerType: "pharmacyTech",
    examTag: "PTCB CPHT",
    regionScope: "US",
    category: "Billing and Reimbursement",
    topic: "Third-Party Claims and Rejection Resolution",
    bottomLine: "Resolve pharmacy claim rejections by identifying the exact technical reason, correcting information within technician scope, and escalating clinical or authorization issues rather than manipulating data to force payment.",
    coreConcept: "Electronic adjudication checks patient eligibility, product identifiers, quantity, days supply, refill timing, prescriber information, coverage rules, and plan limitations.",
    recognition: "Refill-too-soon, prior authorization, nonformulary product, invalid person code, days-supply mismatch, quantity limit, and coordination-of-benefits messages require different responses.",
    workflow: "Read the rejection code and message, verify demographic and prescription data, correct technical errors, contact patient/plan/prescriber as appropriate, document actions, and send clinical substitutions or authorization decisions to the pharmacist/prescriber.",
    interpretation: "A paid claim only confirms adjudication, not clinical appropriateness; claim success must not override medication-safety review.",
    safety: "Never falsify days supply, quantity, diagnosis, or prescriber data to bypass a payer restriction.",
    redFlags: "Repeated rejection requiring altered clinical information, suspected identity mismatch, early controlled-substance refill, or request to misrepresent claim data requires pharmacist escalation.",
    commonErrors: "Guessing at override codes, changing days supply to obtain payment, and treating prior authorization as a technical rejection the technician can approve.",
    examFocus: "Separate correctable data-entry problems from insurer or prescriber decisions outside technician authority.",
    glossary: [
      { term: "Prior authorization", definition: "Payer requirement for prescriber or plan approval before coverage of a medication or service." },
      { term: "Adjudication", definition: "Electronic processing of a pharmacy claim against benefit and coverage rules." },
    ],
  },
  {
    id: "pharmtech-hazardous-drugs",
    careerType: "pharmacyTech",
    examTag: "PTCB CPHT",
    regionScope: "BOTH",
    category: "Compounding and Safety",
    topic: "Hazardous Drug Handling",
    bottomLine: "Hazardous drugs require designated engineering controls, appropriate PPE, closed or controlled handling techniques, spill preparedness, decontamination, and waste segregation throughout receiving, compounding, transport, and disposal.",
    coreConcept: "Exposure can occur through inhalation, dermal contact, ingestion, sharps injury, or surface contamination, so containment must extend beyond the compounding step.",
    recognition: "Damaged hazardous-drug packaging, visible residue, spill, leaking connection, contaminated PPE, or incorrect containment area requires immediate control and cleanup according to procedure.",
    workflow: "Identify hazardous status, receive and store separately, don required PPE, compound or manipulate in approved controls, contain transport, decontaminate surfaces, dispose in designated waste, and document exposures or spills.",
    interpretation: "A product can remain hazardous even when it is an intact tablet; handling requirements depend on dosage form and task, not simply whether compounding occurs.",
    safety: "Never clean a hazardous spill without the correct spill kit, PPE, and trained procedure; restrict the area and escalate.",
    redFlags: "Large spill, broken chemotherapy container, skin or eye exposure, sharps injury with hazardous drug, or engineering-control failure requires immediate exposure response.",
    commonErrors: "Using ordinary waste, transporting in open bins, wearing incomplete PPE, and treating intact oral hazardous products as risk free.",
    examFocus: "Know which control applies at each stage: receipt, storage, compounding, administration support, spill response, and disposal.",
    glossary: [
      { term: "Hazardous drug", definition: "Drug with characteristics such as carcinogenicity, reproductive toxicity, genotoxicity, organ toxicity at low doses, or similar hazard." },
      { term: "Decontamination", definition: "Process of removing or inactivating hazardous drug residue from surfaces and equipment." },
    ],
  },
  {
    id: "pharmtech-vaccine-storage",
    careerType: "pharmacyTech",
    examTag: "PTCB CPHT",
    regionScope: "BOTH",
    category: "Medication Management",
    topic: "Vaccine Storage, Handling, and Inventory Integrity",
    bottomLine: "Vaccines must remain within product-specific storage conditions, be monitored with reliable temperature systems, protected from avoidable excursions, and quarantined rather than used when integrity is uncertain.",
    coreConcept: "Loss of potency from improper storage may not be visible and can result in ineffective immunization.",
    recognition: "Out-of-range temperature, power outage, door left open, product stored in the wrong unit, expired vial, or damaged packaging requires immediate integrity assessment.",
    workflow: "Monitor and document temperatures, store by product requirements, minimize door opening, rotate stock, respond to alarms, label and quarantine affected product, document excursion details, and obtain disposition guidance.",
    interpretation: "Do not discard or administer excursion-affected vaccine until stability guidance determines whether it remains usable.",
    safety: "Maintain clear separation of quarantined product and never relabel it as usable without documented authorization.",
    redFlags: "Freezing of freeze-sensitive vaccine, prolonged warm excursion, undocumented storage interval, or repeated monitoring failure requires urgent inventory review.",
    commonErrors: "Using a simple household thermometer without adequate monitoring capability, placing product in unstable locations, and assuming a brief excursion is harmless without evaluation.",
    examFocus: "The safe answer after an excursion is usually quarantine, document, and seek stability guidance before use.",
    glossary: [
      { term: "Temperature excursion", definition: "Storage condition outside the recommended temperature range for a product." },
      { term: "Quarantine", definition: "Segregation of questionable stock so it cannot be used until disposition is determined." },
    ],
  },
];
