import type { AlliedAuthoredTopic } from "./types";

export const alliedTopics07: AlliedAuthoredTopic[] = [
  {
    id: "rrt-weaning-extubation-readiness",
    careerType: "rrt",
    examTag: "NBRC TMC/CSE",
    regionScope: "US",
    category: "Mechanical Ventilation",
    topic: "Ventilator Liberation and Extubation Readiness",
    bottomLine: "Ventilator liberation requires daily assessment of reversible barriers, a successful spontaneous breathing trial, and confirmation that the patient can protect the airway after the tube is removed.",
    coreConcept: "Passing a spontaneous breathing trial tests ventilatory reserve but does not prove extubation safety; secretion burden, cough strength, mental status, upper-airway patency, and hemodynamic stability also matter.",
    recognition: "Improving disease process, acceptable oxygenation on modest support, hemodynamic stability, adequate spontaneous drive, manageable secretions, and an intact airway-protection strategy support liberation assessment.",
    workflow: "Screen readiness, minimize avoidable sedation, perform an appropriate spontaneous breathing trial, assess respiratory pattern and gas exchange, evaluate airway protection and secretion clearance, then extubate with a post-extubation support plan when criteria are met.",
    interpretation: "Tachypnea, distress, worsening gas exchange, diaphoresis, arrhythmia, or hemodynamic instability during the trial suggests failure and should trigger correction of reversible causes before another attempt.",
    safety: "Do not equate a successful trial with automatic extubation; anticipate post-extubation stridor, high-risk respiratory failure, and the need for noninvasive or high-flow support in selected patients.",
    redFlags: "New stridor, rapidly increasing work of breathing, inability to clear secretions, progressive hypercapnia, altered mental status, or refractory hypoxemia after extubation requires immediate escalation.",
    commonErrors: "Delaying daily readiness screening, using arbitrary ventilator settings as the only criterion, ignoring airway-protection risk, and persisting with noninvasive rescue when urgent reintubation is indicated.",
    examFocus: "NBRC scenarios test the difference between readiness for a breathing trial, passing the trial, and readiness for extubation.",
    glossary: [
      { term: "Spontaneous breathing trial", definition: "A monitored period of minimal ventilatory assistance used to assess readiness for liberation from mechanical ventilation." },
      { term: "Extubation failure", definition: "Need for reintubation after planned tube removal, usually because respiratory or airway-protection demands exceed patient reserve." },
    ],
  },
  {
    id: "rrt-bronchoscopy-assistance",
    careerType: "rrt",
    examTag: "NBRC TMC/CSE",
    regionScope: "US",
    category: "Pulmonary Diagnostics",
    topic: "Bronchoscopy Preparation, Assistance, and Complications",
    bottomLine: "Safe bronchoscopy support means preparing the airway and equipment, maintaining oxygenation and monitoring during the procedure, and recognizing bleeding, bronchospasm, pneumothorax, or sedation-related deterioration afterward.",
    coreConcept: "Bronchoscopy can diagnose and treat airway problems but instrumentation and sedation can worsen gas exchange, provoke bronchospasm, cause bleeding, or create barotrauma-related complications.",
    recognition: "Indications include airway inspection, secretion or foreign-body removal, sampling, localization of bleeding, and evaluation of abnormal imaging when bronchoscopic access can answer the clinical question.",
    workflow: "Verify indication and consent processes, review oxygenation and bleeding risk, prepare suction and airway rescue equipment, support oxygenation and monitoring, handle specimens correctly, and perform structured post-procedure respiratory reassessment.",
    interpretation: "New hypoxemia or distress after bronchoscopy should not be attributed automatically to sedation; evaluate for retained secretions, bronchospasm, bleeding, pneumothorax, or airway edema.",
    safety: "Maintain immediate access to oxygen, suction, and advanced airway equipment, and escalate rapidly when bleeding or ventilation cannot be controlled.",
    redFlags: "Persistent large-volume hemoptysis, severe desaturation, unilateral breath-sound loss, hypotension, stridor, or inability to ventilate requires urgent intervention.",
    commonErrors: "Underestimating post-procedure deterioration, mishandling specimens, failing to reassess after sedation, and assuming all bleeding is expected and self-limited.",
    examFocus: "Expect questions on preparation, oxygenation, specimen handling, and the first response to acute post-bronchoscopy respiratory compromise.",
    glossary: [
      { term: "Bronchoalveolar lavage", definition: "Instillation and retrieval of sterile fluid through a bronchoscope to sample distal airways and alveolar spaces." },
      { term: "Transbronchial biopsy", definition: "Bronchoscopic sampling of lung tissue that carries bleeding and pneumothorax risk." },
    ],
  },
  {
    id: "paramedic-pediatric-respiratory-failure",
    careerType: "paramedic",
    examTag: "NREMT Paramedic",
    regionScope: "US",
    category: "Pediatrics",
    topic: "Pediatric Respiratory Distress and Failure",
    bottomLine: "Children usually deteriorate from respiratory failure before cardiac arrest, so recognize fatigue early and support oxygenation and ventilation before bradycardia and shock develop.",
    coreConcept: "Smaller airways, higher metabolic demand, and limited respiratory reserve make pediatric patients vulnerable to rapid decompensation when obstruction, lung disease, or impaired drive increases work of breathing.",
    recognition: "Retractions, nasal flaring, grunting, abnormal positioning, poor air entry, altered mental status, cyanosis, decreasing respiratory effort, or bradycardia are progressively concerning signs.",
    workflow: "Use a rapid pediatric assessment, position and suction as needed, provide oxygen, assist ventilation when effort or exchange is inadequate, treat the likely cause within protocol, and reassess continuously during transport.",
    interpretation: "A quieter child with less visible effort may be improving or may be exhausted; mental status, air movement, color, heart rate, and ventilation determine which.",
    safety: "Use age- and size-appropriate equipment and avoid excessive ventilation pressure or rate; poor mask seal is a common correctable cause of ineffective bag-mask ventilation.",
    redFlags: "Weak or irregular respirations, poor chest rise, central cyanosis, altered consciousness, bradycardia, or silent chest requires immediate assisted ventilation and escalation.",
    commonErrors: "Waiting for oxygen saturation alone to show deterioration, assuming less wheeze means improvement, and using adult ventilation technique without pediatric sizing or rate adjustments.",
    examFocus: "NREMT items emphasize distinguishing distress from failure and choosing assisted ventilation before arrest physiology appears.",
    glossary: [
      { term: "Respiratory distress", definition: "Compensated increased work of breathing while oxygenation and ventilation are still being maintained." },
      { term: "Respiratory failure", definition: "Inability to maintain adequate oxygenation or ventilation despite compensatory effort." },
    ],
  },
  {
    id: "paramedic-acute-behavioral-crisis",
    careerType: "paramedic",
    examTag: "NREMT Paramedic",
    regionScope: "US",
    category: "Behavioral Emergencies",
    topic: "Acute Behavioral Crisis and Excited Agitation",
    bottomLine: "Treat dangerous agitation as a medical and safety emergency: control the scene, search for reversible physiologic causes, use the least coercive effective approach, and monitor closely after any restraint or sedation.",
    coreConcept: "Severe agitation can arise from intoxication, hypoxia, hypoglycemia, hyperthermia, head injury, infection, psychiatric illness, or mixed causes, and prolonged struggle increases metabolic and cardiovascular risk.",
    recognition: "Extreme agitation, paranoia, unusual strength, incoherent speech, diaphoresis, hyperthermia, pain insensitivity, stimulant exposure, trauma, or abnormal vital signs should prompt medical rather than purely psychiatric framing.",
    workflow: "Ensure responder safety, reduce stimulation, attempt verbal de-escalation when feasible, assess glucose and oxygenation, identify trauma or toxidrome clues, use protocol-authorized restraint or medication only when required, then monitor airway, ventilation, circulation, temperature, and mental status continuously.",
    interpretation: "Persistent agitation after initial control can reflect undertreated physiology, while sudden quietness can signal exhaustion, hypoxia, or cardiovascular collapse rather than resolution.",
    safety: "Avoid prone positional restraint and never leave a restrained or sedated patient without continuous physiologic monitoring and repeated airway assessment.",
    redFlags: "Hyperthermia, severe acidosis suspicion, chest pain, dysrhythmia, profound hypoxia, sudden collapse, seizure, or rapidly declining consciousness requires immediate resuscitative escalation.",
    commonErrors: "Labeling the presentation psychiatric before checking physiologic causes, using force without a monitoring plan, and interpreting cessation of struggle as proof of improvement.",
    examFocus: "Prioritize safety plus medical assessment, and recognize the monitoring burden created by chemical or physical restraint.",
    glossary: [
      { term: "Verbal de-escalation", definition: "Structured communication intended to reduce agitation while preserving dignity and minimizing coercion." },
      { term: "Positional asphyxia", definition: "Respiratory compromise caused by body position or restraint that restricts ventilation." },
    ],
  },
  {
    id: "mlt-body-fluid-cell-counts",
    careerType: "mlt",
    examTag: "ASCP MLT",
    regionScope: "US",
    category: "Hematology and Body Fluids",
    topic: "Body Fluid Cell Counts and Differentials",
    bottomLine: "Body-fluid analysis is only useful when the specimen is identified correctly, counted with an appropriate method, morphologic findings are verified, and results are interpreted in the context of the fluid source.",
    coreConcept: "Pleural, peritoneal, synovial, cerebrospinal, and other fluids have different expected cellular patterns and stability characteristics, so one universal reference framework is unsafe.",
    recognition: "Clotting, delayed transport, traumatic collection, very low cell concentration, highly viscous samples, or unexpected malignant-appearing cells can materially alter counting and differential strategy.",
    workflow: "Confirm specimen type and collection details, inspect appearance, mix appropriately, choose manual or automated counting method, perform dilution when required, prepare differential slides, identify cells systematically, and escalate atypical or malignant morphology according to policy.",
    interpretation: "Neutrophilic, lymphocytic, eosinophilic, hemorrhagic, or atypical-cell predominance narrows the differential only when combined with chemistry, microbiology, and clinical context.",
    safety: "Do not report automated classifications blindly when the analyzer is not validated for the fluid type or flags abnormal populations.",
    redFlags: "Unexpected blasts, malignant-appearing cells, gross mismatch between instrument count and smear, clotted CSF, or probable specimen misidentification requires immediate review.",
    commonErrors: "Applying blood reference ranges to fluids, failing to account for clotting or dilution, and releasing unreviewed instrument differentials on unsupported specimen types.",
    examFocus: "ASCP questions often test specimen limitations, counting method selection, and when microscopic verification is mandatory.",
    glossary: [
      { term: "Hemocytometer", definition: "Calibrated counting chamber used for manual enumeration of cells in fluids." },
      { term: "Cytocentrifugation", definition: "Technique that concentrates cells from low-cellularity fluids onto a small slide area for morphologic review." },
    ],
  },
  {
    id: "mlt-molecular-diagnostic-controls",
    careerType: "mlt",
    examTag: "ASCP MLT",
    regionScope: "US",
    category: "Molecular Diagnostics",
    topic: "Molecular Testing Controls and Contamination Prevention",
    bottomLine: "A molecular result is valid only when extraction, amplification, positive, negative, and internal controls behave as expected and workflow prevents amplicon contamination.",
    coreConcept: "Nucleic-acid amplification is highly sensitive, so contamination can create false positives while extraction failure or inhibitors can create false negatives unless internal controls expose the problem.",
    recognition: "Unexpected negative internal control, positive no-template control, drift in amplification characteristics, clustered low-level positives, or contamination after high-copy specimens are warning patterns.",
    workflow: "Maintain unidirectional pre- and post-amplification workflow, use dedicated equipment, include required controls, review control performance before patient results, investigate failures, decontaminate when indicated, and repeat only after the cause is addressed.",
    interpretation: "A failed internal control makes a negative patient result uninterpretable, while a positive negative-control invalidates the run until contamination is excluded and corrected.",
    safety: "Never release patient results from a failed control set simply because the individual amplification curve appears plausible.",
    redFlags: "Repeated contamination, discordant controls, unexpected multi-sample positivity, or loss of internal-control signal across specimens requires run rejection and system investigation.",
    commonErrors: "Opening amplified products in pre-amplification areas, treating controls as optional, and repeating the same failed run without identifying the source of failure.",
    examFocus: "Know what each control proves and which patient results become invalid when that control fails.",
    glossary: [
      { term: "Internal control", definition: "Target included or co-extracted to demonstrate that extraction and amplification were adequate and not significantly inhibited." },
      { term: "Amplicon contamination", definition: "Introduction of previously amplified nucleic acid into new reactions, causing false-positive results." },
    ],
  },
  {
    id: "pharmacy-medication-reconciliation-transitions",
    careerType: "pharmacyTech",
    examTag: "PTCB CPHT",
    regionScope: "US",
    category: "Medication Safety and Operations",
    topic: "Medication Reconciliation and Care Transitions",
    bottomLine: "Accurate medication reconciliation depends on building the best possible medication history from multiple sources, identifying discrepancies, and routing clinical decisions to the pharmacist or prescriber rather than guessing.",
    coreConcept: "Medication lists become unsafe when omissions, duplications, dose changes, discontinued drugs, or nonprescription products are carried forward without verification during transitions of care.",
    recognition: "Conflicting lists, duplicate therapies, unclear dose or frequency, recent hospitalization, multiple pharmacies, adherence problems, and high-risk medications are common discrepancy signals.",
    workflow: "Interview the patient or caregiver, compare pharmacy and health-record sources, verify names, strengths, routes, frequencies and actual use, document uncertainty explicitly, and escalate discrepancies for pharmacist reconciliation.",
    interpretation: "A difference between sources can represent an intentional treatment change or an error; technicians collect and clarify source data but do not independently resolve clinical intent.",
    safety: "Never infer that a medication should be continued or stopped based only on one stale list; preserve uncertainty until a qualified clinician resolves it.",
    redFlags: "Conflicting anticoagulant, insulin, opioid, transplant, seizure, or cardiac medication information requires prompt pharmacist review before dispensing or transition completion.",
    commonErrors: "Copying the EHR list without interviewing the patient, ignoring OTC and herbal products, and converting an information discrepancy into an unauthorized clinical decision.",
    examFocus: "PTCB questions emphasize accurate data collection, scope boundaries, and escalation of high-risk discrepancies.",
    glossary: [
      { term: "Medication reconciliation", definition: "Formal process of comparing medication information across transitions to identify and resolve discrepancies." },
      { term: "Medication history", definition: "Structured record of prescription, nonprescription, and other products a patient is actually taking or recently took." },
    ],
  },
  {
    id: "pharmacy-hazardous-drug-handling",
    careerType: "pharmacyTech",
    examTag: "PTCB CPHT",
    regionScope: "US",
    category: "Compounding",
    topic: "Hazardous Drug Handling and Exposure Prevention",
    bottomLine: "Hazardous-drug safety requires engineering controls, correct PPE, closed handling practices where indicated, decontamination procedures, and immediate response to spills or exposure.",
    coreConcept: "Hazardous drugs can expose workers through aerosols, droplets, contaminated surfaces, sharps, or excreta; no single barrier is sufficient, so layered controls are required.",
    recognition: "Antineoplastic and other designated hazardous drugs, damaged packages, spills, contaminated work surfaces, improper gown or glove use, and unsafe transport create exposure risk.",
    workflow: "Verify hazardous classification, receive and store in designated areas, use required containment and PPE, compound in the correct engineering control, label and transport safely, perform deactivation/decontamination/cleaning as required, and manage spills with a defined response kit and reporting process.",
    interpretation: "A visibly clean surface may still contain drug residue; environmental and procedural controls are necessary even without an obvious spill.",
    safety: "Do not compound or clean hazardous drugs without required PPE and containment, and never improvise spill response when an exposure-control procedure exists.",
    redFlags: "Large spill, damaged cytotoxic container, skin or eye exposure, sharps injury, engineering-control failure, or contamination outside the designated area requires immediate escalation.",
    commonErrors: "Using routine exam gloves as the only protection, transporting hazardous drugs in unprotected containers, and confusing ordinary cleaning with hazardous-drug deactivation and decontamination.",
    examFocus: "Expect questions about hierarchy of controls, PPE, spill response, and separation of hazardous-drug workflow from routine compounding.",
    glossary: [
      { term: "Containment primary engineering control", definition: "Ventilated device designed to contain hazardous drug contamination during compounding." },
      { term: "Decontamination", definition: "Removal of hazardous drug residue from surfaces using an appropriate process." },
    ],
  },
  {
    id: "imaging-trauma-radiography",
    careerType: "imaging",
    examTag: "ARRT Radiography",
    regionScope: "US",
    category: "Procedures",
    topic: "Trauma Radiography and Motion-Limited Patients",
    bottomLine: "In trauma imaging, preserve life-saving immobilization and lines while adapting projections and equipment to obtain diagnostic images with the fewest safe movements and exposures.",
    coreConcept: "Trauma radiography balances image quality against the risk of moving unstable anatomy, disrupting devices, worsening pain, or delaying higher-priority resuscitation.",
    recognition: "Spinal precautions, unstable fractures, chest tubes, traction, mechanical ventilation, severe pain, altered consciousness, and inability to cooperate all change routine positioning strategy.",
    workflow: "Confirm patient identity and requested anatomy, communicate with the trauma team, inspect immobilization and devices, choose horizontal-beam or modified projections when needed, position the detector rather than the patient when possible, collimate tightly, and evaluate the image before repeating.",
    interpretation: "A technically imperfect trauma image can still be diagnostically adequate; repeat imaging should be justified by missing anatomy or insufficient diagnostic quality, not aesthetics alone.",
    safety: "Do not remove cervical stabilization, traction, or life-support devices merely to reproduce a routine textbook position without explicit clinical coordination.",
    redFlags: "New neurologic symptoms during movement, device displacement, sudden respiratory compromise, hemodynamic deterioration, or suspected unstable spine requires stopping and immediate team reassessment.",
    commonErrors: "Forcing routine positioning, repeating images for minor cosmetic reasons, and moving the patient before coordinating lines, tubes, and immobilization.",
    examFocus: "ARRT items reward modified positioning that protects the patient while still answering the diagnostic question.",
    glossary: [
      { term: "Horizontal-beam projection", definition: "Projection made with the x-ray beam parallel to the floor, often used when trauma prevents routine positioning." },
      { term: "Diagnostic adequacy", definition: "Image quality sufficient to answer the clinical question even if the image is not technically ideal." },
    ],
  },
  {
    id: "imaging-mobile-radiography-infection-control",
    careerType: "imaging",
    examTag: "ARRT Radiography",
    regionScope: "US",
    category: "Patient Care",
    topic: "Mobile Radiography, Isolation, and Equipment Decontamination",
    bottomLine: "Mobile imaging must prevent the radiography unit, detector, and accessories from becoming vectors while still maintaining image quality and radiation safety at the bedside.",
    coreConcept: "Portable equipment moves between patients and care areas, so contact surfaces, detector handling, hand hygiene, PPE sequencing, and clean/dirty workflow are core patient-safety competencies.",
    recognition: "Isolation signage, draining wounds, multidrug-resistant organisms, respiratory precautions, contaminated linens, and high-touch detector surfaces all require deliberate infection-control planning.",
    workflow: "Review precautions before entry, gather only needed equipment, protect or dedicate detector surfaces when appropriate, perform hand hygiene and PPE correctly, minimize environmental contact, obtain the image, then clean and disinfect equipment according to material-compatible policy before leaving the workflow cycle.",
    interpretation: "A barrier cover reduces contamination but does not automatically replace required cleaning and disinfection of equipment surfaces.",
    safety: "Avoid bringing unnecessary accessories into isolation rooms and prevent contaminated gloves from touching clean controls, door handles, or documentation devices.",
    redFlags: "Visible contamination of equipment, blood or body-fluid exposure, isolation breach, damaged detector cover, or incompatible disinfectant use requires immediate correction and reporting.",
    commonErrors: "Treating the detector cover as complete decontamination, touching clean equipment with contaminated gloves, and cleaning electronics with products not approved for the device.",
    examFocus: "Know how standard and transmission-based precautions alter portable imaging workflow without compromising radiation protection.",
    glossary: [
      { term: "Fomite", definition: "Inanimate object capable of carrying infectious material between people or environments." },
      { term: "Clean-to-dirty workflow", definition: "Process design that prevents contaminated items or hands from recontaminating cleaned equipment or supplies." },
    ],
  },
  {
    id: "sonography-vascular-doppler-hemodynamics",
    careerType: "diagnosticSonography",
    examTag: "ARDMS SPI",
    regionScope: "US",
    category: "Doppler Physics",
    topic: "Spectral Doppler Hemodynamics and Stenosis Recognition",
    bottomLine: "Interpret spectral Doppler by combining angle-correct velocity, waveform morphology, turbulence, and downstream effects rather than diagnosing stenosis from one velocity number in isolation.",
    coreConcept: "As a vessel narrows, velocity rises through the narrowed segment, flow can become disturbed, and distal waveforms may change depending on lesion severity and vascular bed.",
    recognition: "Focal velocity acceleration, spectral broadening, aliasing, post-stenotic turbulence, tardus-parvus morphology, and altered resistive patterns are major hemodynamic clues.",
    workflow: "Optimize grayscale and color first, align the Doppler cursor with flow, use accepted angle correction, sample before/within/after a suspected lesion, document morphology and velocities, and compare with validated criteria for the vessel examined.",
    interpretation: "High velocity can be caused by true stenosis, tortuosity, poor angle correction, low sample placement, or systemic hemodynamic factors, so technical quality must be verified before grading disease.",
    safety: "Do not overcall disease from artifact or undercall severe disease because a near-occlusive lesion no longer generates the highest velocity.",
    redFlags: "Absent expected flow, severely damped distal waveform, suspected acute occlusion, or technically unexplained major asymmetry requires urgent review.",
    commonErrors: "Using angle correction above accepted limits, sampling only at one point, and treating aliasing alone as proof of hemodynamically significant stenosis.",
    examFocus: "SPI questions emphasize Doppler equation principles, angle dependence, aliasing, and the relationship between stenosis and waveform change.",
    glossary: [
      { term: "Tardus-parvus", definition: "Delayed, damped systolic upstroke distal to a significant upstream obstruction." },
      { term: "Spectral broadening", definition: "Filling-in of the spectral window caused by a range of velocities, which may reflect disturbed flow or technical factors." },
    ],
  },
  {
    id: "sonography-obstetric-biometry-growth",
    careerType: "diagnosticSonography",
    examTag: "ARDMS SPI",
    regionScope: "US",
    category: "Clinical Application",
    topic: "Obstetric Biometry, Growth, and Measurement Quality",
    bottomLine: "Reliable fetal-growth assessment depends on standardized image planes and reproducible measurements; a precise caliper on the wrong plane is still a wrong measurement.",
    coreConcept: "Biometric parameters estimate gestational size and growth only when acquisition planes meet anatomic criteria and serial interpretation accounts for expected measurement variability.",
    recognition: "Off-axis head planes, compressed abdominal contours, poorly visualized landmarks, foreshortened femur, and inconsistent dating can create false growth abnormalities.",
    workflow: "Confirm the clinical question and dating basis, obtain standard head, abdominal, and femur planes, place calipers according to protocol, document image quality, calculate estimated size using validated formulas, and compare serial measurements when growth rather than dating is the question.",
    interpretation: "A single small parameter does not prove growth restriction; pattern, dating confidence, serial growth, fluid, Doppler findings, and clinical context determine concern.",
    safety: "Avoid repeated unnecessary scanning solely to force a preferred measurement and escalate when technically adequate imaging shows a concerning growth pattern or abnormal Doppler physiology.",
    redFlags: "Marked interval growth failure, abnormal umbilical flow pattern, severe oligohydramnios, or major biometric discordance requires prompt clinical review.",
    commonErrors: "Measuring anatomy on nonstandard planes, changing gestational dating late because of size discrepancy, and reporting false precision beyond measurement reliability.",
    examFocus: "Know standard measurement planes, common technical errors, and the distinction between dating and growth assessment.",
    glossary: [
      { term: "Biometry", definition: "Standardized measurement of fetal structures used to estimate gestational size and growth." },
      { term: "Estimated fetal weight", definition: "Calculated estimate derived from fetal biometric measurements using a validated formula." },
    ],
  },
  {
    id: "cardiacsonographer-diastolic-function",
    careerType: "cardiacSonographer",
    examTag: "ARDMS RDCS",
    regionScope: "US",
    category: "Echocardiography",
    topic: "Left Ventricular Diastolic Function Assessment",
    bottomLine: "Grade diastolic function by integrating transmitral inflow, tissue Doppler, chamber structure, pulmonary pressures, rhythm, and clinical context rather than relying on E/A ratio alone.",
    coreConcept: "Relaxation, compliance, filling pressure, age, heart rate, and rhythm all influence diastolic Doppler patterns, so multiple parameters are required to estimate filling physiology.",
    recognition: "Abnormal e-prime, elevated E/e-prime, left atrial enlargement, altered E/A pattern, shortened or prolonged deceleration time, and elevated pulmonary pressure estimates can support abnormal filling physiology.",
    workflow: "Acquire high-quality mitral inflow and tissue Doppler, document chamber dimensions and systolic function, assess rhythm and heart rate, integrate supportive pulmonary venous or tricuspid findings when needed, and apply the laboratory's current guideline-based algorithm.",
    interpretation: "A seemingly normal E/A ratio can represent pseudonormal filling, while atrial fibrillation, mitral disease, pacing, and other conditions require modified interpretation.",
    safety: "Do not assign a diastolic grade mechanically when required criteria are missing or the rhythm/valve condition invalidates the standard algorithm.",
    redFlags: "Markedly elevated filling-pressure indicators with acute dyspnea, severe pulmonary hypertension, or new hemodynamic deterioration warrants urgent clinical communication.",
    commonErrors: "Using E/A ratio alone, ignoring rhythm, and reporting a definite grade from incomplete or technically unreliable measurements.",
    examFocus: "RDCS questions test integration of Doppler and structural parameters and recognition of situations where the routine algorithm does not apply.",
    glossary: [
      { term: "e-prime", definition: "Early diastolic mitral annular tissue velocity used as an index of myocardial relaxation." },
      { term: "Pseudonormal filling", definition: "Transmitral inflow pattern that appears normal because elevated filling pressure masks impaired relaxation." },
    ],
  },
  {
    id: "cardiacsonographer-right-ventricular-function",
    careerType: "cardiacSonographer",
    examTag: "ARDMS RDCS",
    regionScope: "US",
    category: "Echocardiography",
    topic: "Right Ventricular Size, Function, and Pressure Overload",
    bottomLine: "Right-heart assessment requires dedicated views and multiple functional indices because the right ventricle's geometry makes a single visual estimate unreliable.",
    coreConcept: "Pressure overload, volume overload, pulmonary vascular disease, ischemia, and left-heart disease alter right-ventricular size, wall motion, septal configuration, tricuspid regurgitation, and venous pressure findings.",
    recognition: "RV dilation, reduced longitudinal motion, abnormal fractional area change, septal flattening, elevated tricuspid regurgitant velocity, enlarged IVC, and right atrial enlargement are important patterns.",
    workflow: "Obtain RV-focused views, assess chamber size and wall motion, measure validated functional indices, evaluate tricuspid regurgitation, estimate pulmonary pressure when feasible, inspect septal shape and IVC, and integrate with clinical context.",
    interpretation: "Septal flattening predominantly in systole supports pressure overload, while diastolic flattening can suggest volume overload; mixed patterns require broader interpretation.",
    safety: "Do not report pulmonary pressure from a poor-quality or incomplete tricuspid regurgitation envelope without stating uncertainty.",
    redFlags: "New severe RV dysfunction, McConnell-like regional pattern with acute symptoms, severe pulmonary hypertension, or pericardial constraint with hemodynamic compromise requires urgent communication.",
    commonErrors: "Assessing the RV only from a standard apical view, equating TAPSE with global RV function in every condition, and overestimating pulmonary pressure from an incomplete Doppler envelope.",
    examFocus: "Know dedicated RV measurements, overload patterns, and limitations of pressure estimation.",
    glossary: [
      { term: "TAPSE", definition: "Tricuspid annular plane systolic excursion, a measure of RV longitudinal systolic motion." },
      { term: "Fractional area change", definition: "Percent change in right-ventricular area from diastole to systole in an appropriate view." },
    ],
  },
  {
    id: "ota-cognitive-rehab-executive-function",
    careerType: "occupationalTherapyAssistant",
    examTag: "NBCOT COTA",
    regionScope: "US",
    category: "Adult Rehabilitation",
    topic: "Cognitive Rehabilitation and Executive Function",
    bottomLine: "Cognitive rehabilitation should connect impairment to real occupational performance and use graded strategies that improve safety, independence, and carryover in daily routines.",
    coreConcept: "Attention, memory, initiation, planning, inhibition, and self-monitoring interact during occupations; intervention can restore skills, teach compensatory strategies, or modify environments.",
    recognition: "Missed steps, unsafe sequencing, poor error awareness, perseveration, distractibility, task abandonment, and inability to generalize learning are functional executive deficits.",
    workflow: "Observe performance in meaningful tasks, identify the cognitive barrier, collaborate on a functional goal, choose restorative or compensatory strategy, grade task complexity, provide cues systematically, and document level of assistance and carryover.",
    interpretation: "Success under heavy cueing does not prove independent function; the ability to initiate, self-correct, and transfer strategies to new contexts determines real-world usefulness.",
    safety: "High-risk activities such as medication management, cooking, driving-related tasks, and community mobility require explicit safety boundaries and supervision decisions within the OT plan of care.",
    redFlags: "New acute confusion, major decline from baseline, unsafe impulsivity, inability to recognize hazards, or neurologic deterioration requires clinical escalation rather than routine progression of therapy.",
    commonErrors: "Using tabletop drills without occupational relevance, fading cues too quickly, and documenting task completion without describing cognitive assistance required.",
    examFocus: "NBCOT items emphasize occupation-based assessment, cueing hierarchy, compensatory strategies, and safety-aware grading.",
    glossary: [
      { term: "Metacognition", definition: "Awareness and regulation of one's own thinking and performance." },
      { term: "Error awareness", definition: "Ability to recognize a mistake during or after task performance and use that information to adjust behavior." },
    ],
  },
  {
    id: "ota-low-vision-adl-adaptation",
    careerType: "occupationalTherapyAssistant",
    examTag: "NBCOT COTA",
    regionScope: "US",
    category: "Adult Rehabilitation",
    topic: "Low Vision Adaptation for Activities of Daily Living",
    bottomLine: "Low-vision intervention improves occupational performance by optimizing contrast, lighting, organization, magnification, scanning, and environmental consistency around the client's actual goals.",
    coreConcept: "Visual acuity loss, field loss, contrast sensitivity, glare, and visual processing limitations affect occupations differently, so adaptation must match the specific impairment and task demand.",
    recognition: "Difficulty finding items, missing food or objects on one side, medication errors, poor stair detection, glare intolerance, and inability to read labels are common functional presentations.",
    workflow: "Identify meaningful tasks and visual barriers, optimize lighting and glare control, increase contrast, simplify and organize environments, trial magnification or auditory supports, train scanning or eccentric viewing strategies when appropriate, and verify safe carryover.",
    interpretation: "A device that improves near acuity in clinic may still fail if it is too complex, reduces field of view, or does not fit the client's routine and dexterity.",
    safety: "Prioritize fall prevention, medication labeling, cooking hazards, and community navigation; environmental changes should be consistent enough to reduce search burden.",
    redFlags: "Sudden vision loss, new field deficit, eye pain, neurologic symptoms, or rapid decline requires medical evaluation rather than routine adaptive training.",
    commonErrors: "Assuming brighter light always helps, changing environmental organization without client agreement, and recommending devices without task-specific training.",
    examFocus: "Match the adaptation to the visual deficit and occupational goal, with safety and usability taking priority over device complexity.",
    glossary: [
      { term: "Contrast sensitivity", definition: "Ability to distinguish an object from its background when differences in brightness or color are subtle." },
      { term: "Eccentric viewing", definition: "Use of a healthier peripheral retinal area instead of a damaged central visual area to improve functional vision." },
    ],
  },
  {
    id: "pta-vestibular-rehab-balance",
    careerType: "physiotherapyAssistant",
    examTag: "FSBPT PTA",
    regionScope: "US",
    category: "Neuromuscular Rehabilitation",
    topic: "Vestibular Rehabilitation and Balance Progression",
    bottomLine: "Vestibular rehabilitation uses symptom-guided gaze, habituation, balance, and mobility activities within the PT plan while the PTA monitors safety, response, and functional carryover.",
    coreConcept: "Gaze instability, motion sensitivity, sensory mismatch, and balance deficits can improve through adaptation, habituation, substitution, and progressively challenging postural tasks.",
    recognition: "Oscillopsia, dizziness with head motion, veering, visually induced symptoms, impaired balance in low light or on compliant surfaces, and fear-driven activity restriction are common findings.",
    workflow: "Confirm the PT-established diagnosis and precautions, monitor baseline symptoms, perform prescribed gaze or balance exercises, manipulate speed, base of support and sensory input gradually, guard closely, provide recovery time, and report unexpected responses.",
    interpretation: "Mild temporary symptom provocation can be therapeutic in selected exercises, but escalating or prolonged symptoms may mean the dose is excessive or the presentation is not behaving as expected.",
    safety: "Use appropriate guarding and assistive devices, avoid unsupervised high-fall-risk tasks, and follow restrictions for cervical, vascular, or neurologic concerns.",
    redFlags: "New focal neurologic deficit, severe headache, syncope, chest pain, persistent vomiting, new hearing loss, or symptoms inconsistent with the established plan requires immediate escalation.",
    commonErrors: "Progressing balance challenge faster than safety allows, treating every dizziness complaint as peripheral vestibular dysfunction, and failing to document symptom duration and recovery.",
    examFocus: "FSBPT questions emphasize safe progression within the PT plan and recognition of central or medical red flags.",
    glossary: [
      { term: "Gaze stabilization", definition: "Exercise designed to improve visual stability during head movement through vestibulo-ocular adaptation or substitution." },
      { term: "Habituation", definition: "Reduction in symptom response through repeated controlled exposure to a provoking movement or visual stimulus." },
    ],
  },
  {
    id: "pta-cardiopulmonary-rehab-monitoring",
    careerType: "physiotherapyAssistant",
    examTag: "FSBPT PTA",
    regionScope: "US",
    category: "Cardiopulmonary Rehabilitation",
    topic: "Exercise Monitoring in Cardiac and Pulmonary Rehabilitation",
    bottomLine: "Safe rehabilitation exercise requires pre-session screening, appropriate intensity, symptom and vital-sign monitoring, and immediate modification when physiologic response is abnormal.",
    coreConcept: "Heart rate, blood pressure, oxygen saturation, perceived exertion, dyspnea, rhythm, medications, and disease-specific limitations determine exercise tolerance and progression.",
    recognition: "Excessive dyspnea, angina-like symptoms, abnormal blood-pressure response, dizziness, desaturation, palpitations, or disproportionate fatigue are warning responses during exercise.",
    workflow: "Review the PT plan and precautions, obtain baseline symptoms and vital signs, begin prescribed warm-up and exercise, monitor response at defined intervals, adjust workload within authorized parameters, cool down, and document recovery.",
    interpretation: "A heart-rate target may be unreliable with beta-blockade, pacing, autonomic dysfunction, or atrial fibrillation, so symptoms and perceived exertion become especially important.",
    safety: "Stop or reduce exercise for concerning symptoms or abnormal physiologic response and follow the facility escalation protocol rather than pushing to complete the planned workload.",
    redFlags: "Chest pressure, syncope or near-syncope, severe dyspnea, new neurologic symptoms, significant arrhythmia, marked hypotension, or sustained concerning desaturation requires immediate escalation.",
    commonErrors: "Using heart rate alone to dose exercise, ignoring medication effects, and documenting only distance or workload without physiologic response.",
    examFocus: "Know when to continue, modify, stop, or escalate based on integrated cardiopulmonary response.",
    glossary: [
      { term: "Rate of perceived exertion", definition: "Patient-reported estimate of exercise intensity used alongside objective physiologic measures." },
      { term: "Chronotropic response", definition: "Heart-rate change in response to exercise demand." },
    ],
  },
  {
    id: "surgtech-robotic-surgery-setup",
    careerType: "surgicalTechnologist",
    examTag: "NBSTSA CST",
    regionScope: "US",
    category: "Intraoperative Procedures",
    topic: "Robotic Surgery Setup and Docking Safety",
    bottomLine: "Robotic surgery safety depends on correct room layout, patient positioning, instrument and port planning, sterile docking, collision prevention, and an immediate undocking plan for emergencies.",
    coreConcept: "Once the robot is docked, patient access can be restricted and external arm collisions can transmit force to ports or tissue, so setup errors become harder to correct safely.",
    recognition: "Limited airway access, steep positioning, pressure-risk areas, arm collisions, port tension, instrument mismatch, and loss of sterility are major robotic workflow hazards.",
    workflow: "Verify procedure and system readiness, arrange the room for anesthesia and team access, position and protect the patient, prepare robotic instruments, maintain sterility during draping and docking, confirm arm clearance, track instruments, and remain ready for rapid undocking.",
    interpretation: "Resistance or unexpected instrument movement should not be overcome by force; external collisions, trocar position, instrument articulation, and tissue interaction must be reassessed.",
    safety: "Protect pressure points and nerves during prolonged positioning, maintain awareness of emergency access limitations, and never exchange or remove robotic instruments outside the established safe sequence.",
    redFlags: "Patient instability requiring immediate access, robotic malfunction, port dislodgement, loss of insufflation with concern for injury, or uncontrolled bleeding requires coordinated emergency response and possible undocking.",
    commonErrors: "Docking before confirming anesthesia access, allowing arm collisions, incomplete instrument counts, and underestimating positioning injury risk during long procedures.",
    examFocus: "CST questions emphasize sterile setup, positioning, instrument accountability, team communication, and emergency undocking readiness.",
    glossary: [
      { term: "Docking", definition: "Positioning and connecting the robotic patient-side system to the placed surgical ports." },
      { term: "Port collision", definition: "Contact or excessive external force between robotic arms or access ports that can impair motion or transmit force to the patient." },
    ],
  },
  {
    id: "surgtech-specimen-handling-orientation",
    careerType: "surgicalTechnologist",
    examTag: "NBSTSA CST",
    regionScope: "US",
    category: "Intraoperative Procedures",
    topic: "Surgical Specimen Handling, Orientation, and Chain of Custody",
    bottomLine: "A specimen is clinically useful only if the correct tissue reaches the correct destination with accurate identity, orientation, medium, labeling, documentation, and handoff.",
    coreConcept: "Specimen errors can destroy diagnostic value or cause wrong-patient results; some tissues require fresh transport, some fixation, some sterile handling, and forensic specimens require documented chain of custody.",
    recognition: "Unlabeled containers, uncertain laterality, missing orientation markers, incorrect preservative, crushed tissue, delayed transport, and specimens for culture placed in fixative are critical failure points.",
    workflow: "Confirm specimen source verbally, maintain orientation markers, protect tissue from damage, place it in the correct container or medium, complete labeling at the point of handoff, read back critical identifiers, document transfer, and preserve chain of custody when applicable.",
    interpretation: "The specimen name alone may be insufficient when margins, laterality, anatomic orientation, or separate sites change pathologic interpretation.",
    safety: "Never relabel an uncertain specimen from memory; stop the workflow and resolve identity with the surgical team before the specimen leaves controlled custody.",
    redFlags: "Uncertain patient identity, mismatched labels, lost specimen, wrong preservative, damaged margin orientation, or broken forensic custody requires immediate escalation and incident handling.",
    commonErrors: "Prelabeling containers before specimen confirmation, putting culture specimens in formalin, and failing to communicate orientation markers to pathology.",
    examFocus: "Expect questions on correct medium, labeling, orientation, read-back, and chain-of-custody responsibilities.",
    glossary: [
      { term: "Orientation marker", definition: "Suture, clip, ink, or other agreed marker that identifies a specific margin or anatomic direction for pathology." },
      { term: "Chain of custody", definition: "Documented chronological control of a specimen or evidence item from collection through transfer and final disposition." },
    ],
  },
  {
    id: "him-data-governance-master-patient-index",
    careerType: "healthInfoMgmt",
    examTag: "AHIMA RHIT",
    regionScope: "US",
    category: "Data Management",
    topic: "Data Governance and Master Patient Index Integrity",
    bottomLine: "High-quality health information depends on governed data definitions, unique patient identity, duplicate prevention, and controlled correction of demographic or record-linkage errors.",
    coreConcept: "When one patient has duplicate records or two patients are overlaid into one record, every downstream function—clinical care, billing, analytics, privacy, and quality reporting—can be corrupted.",
    recognition: "Near-matching demographics, repeated identifiers, conflicting allergies or histories, impossible encounter overlap, duplicate names, and unexpectedly merged results can signal MPI integrity problems.",
    workflow: "Apply standardized identity matching rules, investigate suspected duplicates or overlays using authoritative sources, preserve the audit trail, merge or unmerge only through approved governance workflow, and communicate corrections to affected systems.",
    interpretation: "A high algorithmic match score supports review but does not replace human validation when identity uncertainty could combine two different patients.",
    safety: "Never merge records solely because names and birth dates match; use multiple identifiers and follow organizational correction procedures.",
    redFlags: "Evidence that two individuals share one chart, conflicting blood types or major diagnoses, privacy exposure from mislinked records, or downstream propagation of a wrong merge requires urgent remediation.",
    commonErrors: "Treating duplicate cleanup as clerical housekeeping, deleting records instead of preserving provenance, and fixing one system without addressing linked downstream copies.",
    examFocus: "RHIT questions emphasize data integrity, governance, auditability, and patient-identity risk across information systems.",
    glossary: [
      { term: "Master patient index", definition: "Enterprise index used to identify and link records belonging to the same patient across systems or encounters." },
      { term: "Record overlay", definition: "Serious error in which information from two different patients is combined into one health record." },
    ],
  },
  {
    id: "him-clinical-documentation-integrity",
    careerType: "healthInfoMgmt",
    examTag: "AHIMA RHIT",
    regionScope: "US",
    category: "Revenue Cycle and Documentation",
    topic: "Clinical Documentation Integrity and Compliant Query Practice",
    bottomLine: "Clinical documentation integrity improves record clarity and coding accuracy through nonleading, clinically supported queries that preserve provider judgment rather than steering the answer.",
    coreConcept: "Documentation must reflect the patient's clinical reality; ambiguous, conflicting, incomplete, or nonspecific documentation can distort coding, quality reporting, reimbursement, and continuity of care.",
    recognition: "Conflicting diagnoses, unclear cause-and-effect, abnormal clinical indicators without a documented diagnosis, unspecified conditions, and contradictory discharge documentation are common query triggers.",
    workflow: "Identify the documentation gap, verify supporting clinical indicators, determine whether a query is necessary, use a compliant nonleading format with reasonable response options, preserve the query as required, and update coding only from provider documentation.",
    interpretation: "Clinical indicators support a query but do not authorize the HIM professional to assign an undocumented diagnosis independently.",
    safety: "Avoid queries designed to maximize reimbursement rather than clarify the record, and never present only one financially favorable answer when alternatives are clinically plausible.",
    redFlags: "Systematic leading queries, retroactive unsupported diagnosis changes, pressure to alter records for reimbursement, or conflicting final diagnoses that affect patient safety requires compliance escalation.",
    commonErrors: "Coding directly from labs, making the query itself the diagnosis, and treating all specificity gaps as automatically query-worthy without clinical relevance.",
    examFocus: "RHIT items distinguish compliant clarification from leading documentation manipulation and reinforce provider responsibility for diagnoses.",
    glossary: [
      { term: "Clinical documentation integrity", definition: "Process of improving completeness, clarity, consistency, and clinical support of health-record documentation." },
      { term: "Provider query", definition: "Formal request for clarification of health-record documentation using a compliant, nonleading approach." },
    ],
  },
  {
    id: "socialwork-child-safeguarding-assessment",
    careerType: "socialWorker",
    examTag: "ASWB Clinical",
    regionScope: "US",
    category: "Assessment and Intervention",
    topic: "Child Safeguarding Assessment and Trauma-Informed Response",
    bottomLine: "When child maltreatment is suspected, prioritize immediate safety, obtain developmentally appropriate information without contaminating disclosure, document objectively, and follow applicable reporting and multidisciplinary procedures.",
    coreConcept: "The social worker's role is not to conduct an uncontrolled forensic interrogation; it is to assess safety, support the child, gather clinically necessary information, and activate mandated systems appropriately.",
    recognition: "Injury patterns inconsistent with history or development, delayed care, fearful behavior, sexualized behavior, caregiver explanations that change, neglect indicators, and disclosure are significant cues.",
    workflow: "Assess immediate danger and medical needs, speak with the child in a safe developmentally appropriate manner, use open nonleading prompts, avoid repeated questioning, document exact statements and observations, consult required safeguarding resources, and complete mandated reporting according to jurisdiction and setting.",
    interpretation: "A child's recantation or inconsistent detail does not by itself rule out abuse; fear, loyalty, development, trauma, and interviewer effects can alter disclosure.",
    safety: "Do not confront the alleged perpetrator in a way that increases danger or pressure the child for proof before initiating required protection steps.",
    redFlags: "Immediate threat, serious injury, suicidal risk, unsafe discharge setting, trafficking concern, or caregiver interference with urgent protection requires immediate escalation.",
    commonErrors: "Asking leading questions, promising secrecy, delaying a required report until certainty is achieved, and documenting conclusions instead of observations and statements.",
    examFocus: "ASWB questions prioritize safety, least-contaminating assessment, mandated obligations, and trauma-informed engagement.",
    glossary: [
      { term: "Forensic interview", definition: "Specialized structured interview designed to obtain legally reliable information from a child while minimizing suggestion and repeated questioning." },
      { term: "Trauma-informed care", definition: "Approach that recognizes trauma effects and emphasizes safety, choice, collaboration, trust, and avoidance of retraumatization." },
    ],
  },
  {
    id: "socialwork-capacity-supported-decision-making",
    careerType: "socialWorker",
    examTag: "ASWB Clinical",
    regionScope: "US",
    category: "Ethics and Professional Practice",
    topic: "Decision-Making Capacity, Autonomy, and Supported Decision-Making",
    bottomLine: "Respect autonomy by maximizing the client's ability to understand and choose, distinguishing decision-making capacity from disagreement, diagnosis, disability, or clinician preference.",
    coreConcept: "Capacity is task- and decision-specific and can fluctuate; support, communication accommodations, treatment of reversible barriers, and less restrictive alternatives should be considered before substituting another decision-maker.",
    recognition: "Inability to understand relevant information, appreciate consequences, reason about options, or communicate a stable choice can raise capacity concern, especially when cognition or consciousness fluctuates.",
    workflow: "Clarify the decision and stakes, address communication and sensory barriers, assess understanding and appreciation, explore reasoning and values, identify reversible contributors, use supported decision-making resources, and escalate for formal evaluation when required by role or law.",
    interpretation: "An apparently unwise choice does not prove incapacity; the question is whether the person can meaningfully understand, appreciate, reason, and communicate regarding that specific decision.",
    safety: "Avoid broad labels such as 'incapable' based solely on diagnosis, age, disability, homelessness, substance use, or refusal of recommended care.",
    redFlags: "Rapid cognitive change, delirium, coercion, exploitation, inability to meet immediate safety needs, or high-stakes refusal without apparent understanding requires urgent interdisciplinary assessment.",
    commonErrors: "Equating disagreement with incapacity, failing to provide accommodations, and jumping directly to guardianship without considering less restrictive supports.",
    examFocus: "ASWB questions emphasize autonomy, least-restrictive intervention, functional assessment, and appropriate interdisciplinary or legal referral.",
    glossary: [
      { term: "Decision-making capacity", definition: "Functional ability to understand, appreciate, reason about, and communicate a choice regarding a specific decision." },
      { term: "Supported decision-making", definition: "Use of trusted supports and accommodations to help a person make and communicate their own decisions." },
    ],
  },
  {
    id: "psychotherapy-trauma-stabilization-window",
    careerType: "psychotherapist",
    examTag: "RP Qualifying",
    regionScope: "CAN",
    category: "Clinical Practice",
    topic: "Trauma Stabilization, Arousal Regulation, and Pacing",
    bottomLine: "Trauma therapy should match the client's current capacity for regulation; stabilization and safety take priority when exposure or processing would overwhelm coping and increase risk.",
    coreConcept: "Clients move between tolerable arousal, hyperarousal, and hypoarousal; treatment pacing aims to widen regulation capacity while maintaining collaboration and avoiding unnecessary retraumatization.",
    recognition: "Panic, dissociation, shutdown, flooding, fragmented attention, loss of present orientation, self-harm escalation, and inability to recover after sessions suggest that treatment intensity may exceed current capacity.",
    workflow: "Assess current risk and stability, establish collaborative grounding and regulation strategies, monitor arousal during trauma-related work, titrate exposure or processing, pause when regulation collapses, and revisit goals and consent as treatment evolves.",
    interpretation: "Strong emotion is not automatically harmful, but persistent disorganization or inability to return to baseline suggests the intervention is poorly timed or dosed.",
    safety: "Do not force detailed trauma disclosure to prove readiness, and reassess suicidality, self-harm, substance use, or interpersonal danger when destabilization emerges.",
    redFlags: "Escalating suicidal intent, severe dissociation with safety impairment, psychosis, uncontrolled substance withdrawal, ongoing interpersonal violence, or inability to maintain basic safety requires immediate escalation beyond routine trauma processing.",
    commonErrors: "Moving into exposure before establishing safety, treating dissociation as resistance, and assuming a protocol should continue unchanged despite clear destabilization.",
    examFocus: "RP-qualifying scenarios emphasize consent, pacing, competence, risk assessment, and adapting treatment to client stability.",
    glossary: [
      { term: "Window of tolerance", definition: "Range of arousal within which a person can remain present, process information, and use coping skills effectively." },
      { term: "Grounding", definition: "Strategy that helps orient attention to the present moment and current environment during overwhelming arousal or dissociation." },
    ],
  },
  {
    id: "psychotherapy-therapeutic-rupture-repair",
    careerType: "psychotherapist",
    examTag: "RP Qualifying",
    regionScope: "CAN",
    category: "Clinical Practice",
    topic: "Therapeutic Alliance Rupture and Repair",
    bottomLine: "Alliance ruptures should be addressed directly and collaboratively because avoidance can deepen mistrust while thoughtful repair can strengthen treatment engagement.",
    coreConcept: "Ruptures can involve withdrawal, confrontation, misunderstanding, cultural misattunement, boundary strain, unmet expectations, or therapist error; repair requires curiosity rather than defensiveness.",
    recognition: "Sudden disengagement, missed appointments, minimal responses, anger, compliance without collaboration, topic avoidance, or explicit criticism can signal an alliance rupture.",
    workflow: "Notice the change, invite the client's perspective, validate impact without prematurely defending intent, clarify misunderstandings, acknowledge therapist contribution when present, revisit goals and expectations, and adjust the treatment approach collaboratively.",
    interpretation: "A rupture does not automatically mean therapy should end; the pattern, safety context, boundary issue, and client's wishes determine whether repair, referral, or termination is appropriate.",
    safety: "Do not pressure a client to forgive a therapist error or use the therapeutic relationship to meet the therapist's emotional needs.",
    redFlags: "Boundary violation, exploitation, threats, stalking risk, severe deterioration linked to treatment, or practice beyond competence requires formal consultation, protection steps, and potentially transfer of care.",
    commonErrors: "Ignoring withdrawal, overexplaining the therapist's intent, pathologizing valid feedback, and continuing the same intervention without checking shared goals.",
    examFocus: "Choose responses that protect client autonomy, address power dynamics, repair where appropriate, and use consultation when ethical concerns exceed routine alliance work.",
    glossary: [
      { term: "Alliance rupture", definition: "Tension or breakdown in collaborative bond, goals, or tasks within psychotherapy." },
      { term: "Repair", definition: "Collaborative process of acknowledging and working through an alliance disruption to restore or appropriately redefine the therapeutic relationship." },
    ],
  },
  {
    id: "addictions-stimulant-use-disorder-care",
    careerType: "addictionsCounsellor",
    examTag: "IC&RC CAC",
    regionScope: "BOTH",
    category: "Substance Use Counseling",
    topic: "Stimulant Use Disorder Assessment and Recovery Planning",
    bottomLine: "Stimulant-use care combines medical-risk screening, motivational and behavioral interventions, contingency-based reinforcement where available, harm reduction, and treatment of co-occurring psychiatric and social needs.",
    coreConcept: "Stimulants can cause cardiovascular, neurologic, psychiatric, sleep, nutritional, and infectious harms while repeated use reinforces powerful cue-driven patterns and post-use dysphoria.",
    recognition: "Binge use, prolonged wakefulness, paranoia, weight loss, chest pain, agitation, severe depression after use, compulsive sexual risk, and escalating route or dose are clinically important patterns.",
    workflow: "Assess acute medical and psychiatric risk, clarify substances and route, evaluate motivation and goals, identify triggers and consequences, build a collaborative plan using evidence-based behavioral strategies, integrate harm reduction, and coordinate medical or psychiatric care when indicated.",
    interpretation: "A lapse is clinically important but does not erase progress; examine triggers, safety consequences, and what needs to change in the recovery plan.",
    safety: "Acute chest pain, severe agitation, psychosis, hyperthermia, neurologic deficit, or suicidal crisis requires medical or emergency escalation before routine counseling.",
    redFlags: "Stimulant-associated chest pain, seizure, severe hypertension, psychosis, suicidality, hyperthermia, or sudden collapse requires urgent emergency response.",
    commonErrors: "Treating abstinence as the only acceptable engagement goal, ignoring post-use depression, and attempting counseling during uncontrolled intoxication or medical instability.",
    examFocus: "IC&RC scenarios emphasize stage-matched engagement, behavioral treatment, harm reduction, and recognition of emergencies beyond counseling scope.",
    glossary: [
      { term: "Contingency management", definition: "Behavioral intervention that provides structured reinforcement for objectively verified recovery-related behaviors." },
      { term: "Post-use crash", definition: "Period of fatigue, dysphoria, sleep change, and reduced motivation that can follow intense stimulant use." },
    ],
  },
  {
    id: "addictions-recovery-capital-relapse-planning",
    careerType: "addictionsCounsellor",
    examTag: "IC&RC CAC",
    regionScope: "BOTH",
    category: "Recovery Support",
    topic: "Recovery Capital, Relapse Prevention, and Continuing Care",
    bottomLine: "Sustained recovery is strengthened by practical, social, personal, and community resources—not only by motivation—so relapse prevention should build recovery capital and a realistic continuing-care plan.",
    coreConcept: "Housing, relationships, transportation, income, health care, identity, coping skills, community connection, and access to treatment can either buffer or amplify relapse risk.",
    recognition: "Increasing isolation, missed treatment, return to high-risk contacts, sleep disruption, craving, financial stress, loss of housing, untreated pain, and shame after a lapse are common risk signals.",
    workflow: "Map strengths and barriers, identify high-risk situations and early warning signs, develop coping and support actions, specify what happens after a lapse, connect the client with practical resources and peer/professional supports, and review the plan after transitions or setbacks.",
    interpretation: "Repeated relapse risk may reflect insufficient recovery resources or untreated co-occurring needs rather than simple lack of commitment.",
    safety: "After a period of reduced opioid use, relapse can carry increased overdose risk because tolerance has fallen; continuing-care planning should include overdose prevention when opioids are involved.",
    redFlags: "Loss of housing, domestic violence, severe depression, suicidal thinking, overdose, dangerous withdrawal, or abrupt disengagement from essential medication treatment requires immediate escalation and coordinated support.",
    commonErrors: "Using a generic trigger list without concrete response steps, framing relapse as moral failure, and planning recovery without addressing housing, transportation, finances, or social environment.",
    examFocus: "IC&RC questions reward individualized continuing care, strengths-based planning, practical resource linkage, and rapid response to a lapse without abandonment.",
    glossary: [
      { term: "Recovery capital", definition: "Internal and external resources that support initiation and maintenance of recovery." },
      { term: "Relapse prevention plan", definition: "Specific strategy for recognizing risk, using coping and support responses, and recovering quickly from a lapse or escalation in craving." },
    ],
  },
];
