import type { AlliedAuthoredTopic } from "./types";

export const alliedTopics01: AlliedAuthoredTopic[] = [
  {
    id: "rrt-abg-acid-base",
    careerType: "rrt",
    examTag: "NBRC TMC/CSE",
    regionScope: "BOTH",
    category: "Patient Data Evaluation",
    topic: "ABG Interpretation and Acid-Base Disorders",
    bottomLine: "Interpret pH first, then PaCO2 and bicarbonate, and decide whether compensation is appropriate before naming the disorder.",
    coreConcept: "Respiratory processes change PaCO2 while metabolic processes change bicarbonate; compensation moves the opposite component in the direction that limits the pH disturbance but does not create overcompensation.",
    recognition: "Acidemia is pH below the reference interval and alkalemia is above it. A PaCO2 change opposite the pH points to a respiratory primary process; a bicarbonate change in the same direction as pH points to a metabolic primary process.",
    workflow: "Confirm specimen validity and oxygen conditions, classify pH, identify the primary disturbance, assess compensation, evaluate oxygenation, then correlate with the clinical picture and trend.",
    interpretation: "A near-normal pH with both PaCO2 and bicarbonate abnormal can represent compensation or a mixed disorder; expected-compensation rules and the clinical context distinguish them.",
    safety: "Treat the patient, not a single number. Escalate severe acidemia, rapidly rising PaCO2 with declining mental status, or worsening hypoxemia while the cause is being evaluated.",
    redFlags: "pH near or below 7.20, acute hypercapnia with somnolence, severe hypoxemia, or an ABG pattern incompatible with the observed ventilation should trigger immediate reassessment.",
    commonErrors: "Naming the disorder from PaCO2 alone, ignoring compensation, applying room-air oxygenation expectations to a patient receiving oxygen, and failing to question a venous or air-contaminated specimen.",
    examFocus: "NBRC-style items often ask for the next action after pattern recognition, so connect the gas to ventilation, oxygenation, and the bedside problem rather than stopping at the label.",
    glossary: [
      { term: "PaCO2", definition: "Arterial partial pressure of carbon dioxide and a key marker of alveolar ventilation." },
      { term: "Compensation", definition: "Physiologic adjustment of the nonprimary acid-base component that limits a pH disturbance." },
    ],
  },
  {
    id: "rrt-mechanical-ventilation-basics",
    careerType: "rrt",
    examTag: "NBRC TMC/CSE",
    regionScope: "BOTH",
    category: "Mechanical Ventilation",
    topic: "Initial Mechanical Ventilator Setup",
    bottomLine: "Choose initial settings from the indication, predicted body weight, oxygenation need, and ventilation target, then reassess pressures, volumes, gas exchange, and patient synchrony.",
    coreConcept: "Tidal volume protects the lung when based on predicted body weight, while minute ventilation primarily controls PaCO2 and FiO2/PEEP primarily influence oxygenation.",
    recognition: "The indication for ventilation may be oxygenation failure, ventilation failure, airway protection, or excessive work of breathing; each changes the initial priorities.",
    workflow: "Verify airway placement, select mode and lung-protective tidal volume, set rate, FiO2 and PEEP, establish alarms, obtain early clinical and gas-exchange reassessment, and titrate to response.",
    interpretation: "High peak pressure with stable plateau pressure suggests airway resistance; high peak and plateau pressures suggest reduced respiratory-system compliance.",
    safety: "Use the lowest FiO2 that achieves the oxygenation target, avoid excessive tidal volume and plateau pressure, and never silence an alarm without finding its cause.",
    redFlags: "Sudden desaturation, absent breath sounds, rapidly rising pressures, hypotension after positive-pressure initiation, or inability to pass a suction catheter requires immediate bedside evaluation.",
    commonErrors: "Using actual body weight for tidal volume, treating every high-pressure alarm by lowering the alarm limit, and changing several variables before reassessing the effect of one intervention.",
    examFocus: "Distinguish oxygenation adjustments from ventilation adjustments and identify pressure patterns before changing settings.",
    glossary: [
      { term: "Plateau pressure", definition: "Pressure measured during an inspiratory hold that approximates alveolar pressure when flow is zero." },
      { term: "Predicted body weight", definition: "Height- and sex-based weight used to select lung-protective tidal volume." },
    ],
  },
  {
    id: "rrt-ards-lung-protective-ventilation",
    careerType: "rrt",
    examTag: "NBRC TMC/CSE",
    regionScope: "BOTH",
    category: "Mechanical Ventilation",
    topic: "ARDS and Lung-Protective Ventilation",
    bottomLine: "ARDS management prioritizes low tidal volume ventilation, limitation of injurious pressures, adequate PEEP, and conservative oxygen exposure while treating the cause.",
    coreConcept: "Heterogeneous injured lungs have reduced aerated volume, so normal-sized tidal volumes can overdistend remaining functional units and worsen ventilator-induced lung injury.",
    recognition: "Acute hypoxemia with bilateral opacities not fully explained by cardiac failure and reduced PaO2/FiO2 ratio supports the syndrome when timing and risk factors fit.",
    workflow: "Confirm the syndrome, use predicted-body-weight tidal volume, monitor plateau and driving pressure trends, titrate PEEP/FiO2 to oxygenation, consider prone positioning in severe disease, and reassess synchrony.",
    interpretation: "Improved saturation alone is not enough if plateau pressure is excessive or hemodynamics are deteriorating; oxygenation and lung protection must be balanced.",
    safety: "Avoid reflexively increasing tidal volume for hypercapnia when permissive hypercapnia is acceptable and pH remains tolerable; escalating pressure can cause barotrauma and volutrauma.",
    redFlags: "Refractory hypoxemia, new unilateral absent breath sounds, abrupt pressure changes, severe acidosis, or shock after ventilator changes requires urgent escalation.",
    commonErrors: "Using actual weight, chasing a normal PaCO2 at the expense of injurious ventilation, and overlooking proning or secretion/airway problems when oxygenation worsens.",
    examFocus: "Expect questions that force a choice between normalizing gases and protecting the lung; lung protection generally wins unless there is an immediate life threat.",
    glossary: [
      { term: "Driving pressure", definition: "Plateau pressure minus PEEP, reflecting the pressure applied to inflate the respiratory system above end-expiratory pressure." },
      { term: "Prone positioning", definition: "Turning the patient prone to improve ventilation-perfusion matching and recruit dorsal lung regions in severe ARDS." },
    ],
  },
  {
    id: "rrt-airway-suctioning",
    careerType: "rrt",
    examTag: "NBRC TMC/CSE",
    regionScope: "BOTH",
    category: "Airway Management",
    topic: "Artificial Airway Suctioning",
    bottomLine: "Suction only when assessment indicates retained secretions or airway obstruction, use sterile or appropriate closed technique, limit duration, and reassess oxygenation and breath sounds afterward.",
    coreConcept: "Suctioning removes secretions but can also cause hypoxemia, mucosal trauma, bronchospasm, atelectasis, and dysrhythmia if performed unnecessarily or aggressively.",
    recognition: "Visible secretions, coarse breath sounds, sawtooth ventilator graphics, rising airway resistance, reduced delivered volume, or unexplained desaturation can indicate a need for suctioning.",
    workflow: "Assess first, preoxygenate when indicated, select appropriate catheter size and pressure, insert without suction, apply suction while withdrawing for a brief pass, allow recovery, then reassess.",
    interpretation: "Improved breath sounds, lower resistance, better delivered volume, or improved oxygenation supports effective secretion removal; no improvement prompts a search for another cause.",
    safety: "Stop for severe desaturation, bradycardia, significant dysrhythmia, or hemodynamic instability and provide recovery support before another attempt.",
    redFlags: "Inability to pass the catheter suggests tube obstruction or displacement; acute unilateral findings may suggest mainstem intubation or pneumothorax rather than secretions.",
    commonErrors: "Routine scheduled suctioning without assessment, prolonged suction time, excessive catheter diameter, instilling saline as a default, and failing to reassess after the procedure.",
    examFocus: "The best answer often begins with assessment and indication, not the procedure itself.",
    glossary: [
      { term: "Closed suction", definition: "In-line suction system that permits suctioning without disconnecting the ventilator circuit." },
      { term: "Airway resistance", definition: "Opposition to flow through the airways, which rises with secretions, bronchospasm, or tube narrowing." },
    ],
  },
  {
    id: "rrt-oxygen-delivery-devices",
    careerType: "rrt",
    examTag: "NBRC TMC/CSE",
    regionScope: "BOTH",
    category: "Oxygen Therapy",
    topic: "Oxygen Delivery Devices and Titration",
    bottomLine: "Select the device by required FiO2, flow demand, precision, humidity needs, and patient tolerance, then titrate to a defined oxygenation target.",
    coreConcept: "Low-flow devices provide variable FiO2 because patient inspiratory flow entrains room air, while high-flow systems can meet or exceed inspiratory demand and provide more predictable FiO2.",
    recognition: "A patient who is tachypneic or has high inspiratory demand may receive less FiO2 than expected from a low-flow device even when the set flow is unchanged.",
    workflow: "Define target saturation, assess severity and inspiratory demand, select device, verify fit and flow, humidify when indicated, reassess response, and escalate if the target is not met safely.",
    interpretation: "Failure to improve may reflect insufficient delivered FiO2, shunt physiology, poor interface fit, airway disease, or worsening underlying pathology rather than a simple need for more flow.",
    safety: "Avoid uncontrolled oxygen escalation without reassessment; oxygen is a drug with both under-treatment and overexposure risks.",
    redFlags: "Persistent hypoxemia, increasing work of breathing, altered mental status, or rising PaCO2 with clinical deterioration requires escalation beyond simple device adjustment.",
    commonErrors: "Assuming nasal cannula delivers a fixed FiO2, using a device that cannot meet inspiratory flow demand, and failing to set a target before titration.",
    examFocus: "Know which devices are variable versus fixed performance and match the device to the clinical requirement, not just a memorized flow range.",
    glossary: [
      { term: "FiO2", definition: "Fraction of inspired oxygen delivered to the patient." },
      { term: "High-flow system", definition: "System designed to meet or exceed patient inspiratory flow and provide a more predictable gas mixture." },
    ],
  },
  {
    id: "rrt-asthma-severe-exacerbation",
    careerType: "rrt",
    examTag: "NBRC TMC/CSE",
    regionScope: "BOTH",
    category: "Airway Disease",
    topic: "Severe Asthma Exacerbation",
    bottomLine: "Treat severe asthma rapidly with inhaled bronchodilation, systemic anti-inflammatory therapy, oxygen as needed, and repeated assessment for fatigue or impending ventilatory failure.",
    coreConcept: "Bronchospasm, mucosal edema, and mucus narrowing increase resistance and cause dynamic hyperinflation; a normalizing PaCO2 in a tiring patient can signal deterioration rather than improvement.",
    recognition: "Severe distress, inability to speak normally, accessory muscle use, diminished air movement, altered mental status, or rising/normal PaCO2 despite marked tachypnea are concerning cues.",
    workflow: "Assess severity, deliver rapid bronchodilator therapy, add anticholinergic therapy in severe cases, ensure systemic corticosteroid treatment, monitor response, and escalate ventilatory support if fatigue develops.",
    interpretation: "Wheezing can decrease because airflow improves or because airflow becomes critically low; breath sounds, work of breathing, mental status, and gas exchange determine which.",
    safety: "Avoid excessive minute ventilation after intubation; allow prolonged exhalation to limit auto-PEEP and hypotension from dynamic hyperinflation.",
    redFlags: "Silent chest, exhaustion, confusion, cyanosis, bradycardia, hypotension, or rising PaCO2 with acidemia indicates impending or established respiratory failure.",
    commonErrors: "Equating louder wheezing with worse disease in every case, delaying systemic corticosteroids, and ventilating too aggressively after intubation.",
    examFocus: "Trend airflow and fatigue cues; the dangerous patient may have less wheeze, not more.",
    glossary: [
      { term: "Auto-PEEP", definition: "Positive pressure remaining at end expiration because incomplete exhalation traps gas." },
      { term: "Dynamic hyperinflation", definition: "Progressive air trapping caused by insufficient expiratory time relative to airflow obstruction." },
    ],
  },
  {
    id: "rrt-copd-exacerbation-niv",
    careerType: "rrt",
    examTag: "NBRC TMC/CSE",
    regionScope: "BOTH",
    category: "Noninvasive Ventilation",
    topic: "COPD Exacerbation and Noninvasive Ventilation",
    bottomLine: "In a cooperative patient with acute hypercapnic COPD exacerbation and respiratory acidosis, noninvasive ventilation can reduce work of breathing and avoid intubation when no contraindication is present.",
    coreConcept: "Pressure support augments tidal volume and ventilation while expiratory pressure offsets intrinsic PEEP and improves triggering, reducing respiratory muscle load.",
    recognition: "Tachypnea, accessory muscle use, hypercapnia with acidemia, and persistent distress despite initial medical therapy support NIV consideration when airway protection is intact.",
    workflow: "Confirm indication and contraindications, choose an interface, start tolerable inspiratory and expiratory pressures, minimize leak, reassess comfort, respiratory rate, tidal volume, gas exchange, and mental status early.",
    interpretation: "Falling respiratory rate, improved pH/PaCO2, reduced work of breathing, and better comfort suggest success; worsening acidosis or mental status suggests failure.",
    safety: "Do not persist with NIV in a patient who cannot protect the airway, is vomiting, has severe hemodynamic instability, or is rapidly deteriorating.",
    redFlags: "Worsening encephalopathy, inability to clear secretions, escalating oxygen need, severe acidosis, or shock should prompt preparation for invasive airway management.",
    commonErrors: "Treating NIV as a set-and-forget device, ignoring mask leak and synchrony, and delaying intubation after clear signs of failure.",
    examFocus: "NIV questions hinge on selecting the right patient and recognizing early failure rather than memorizing one pressure setting.",
    glossary: [
      { term: "Pressure support", definition: "Inspiratory pressure assistance above expiratory pressure that augments spontaneous tidal volume." },
      { term: "Intrinsic PEEP", definition: "End-expiratory pressure caused by incomplete exhalation and gas trapping." },
    ],
  },
  {
    id: "rrt-pft-obstruction-restriction",
    careerType: "rrt",
    examTag: "NBRC TMC/CSE",
    regionScope: "BOTH",
    category: "Pulmonary Diagnostics",
    topic: "Pulmonary Function Test Pattern Recognition",
    bottomLine: "Use the FEV1/FVC relationship to identify obstruction, lung volumes to confirm restriction, and diffusion capacity plus clinical context to refine the differential.",
    coreConcept: "Spirometry can suggest restriction but cannot confirm low total lung capacity; true restriction requires reduced TLC measured by an appropriate lung-volume method.",
    recognition: "A reduced FEV1/FVC ratio supports obstruction; reduced FVC with preserved ratio can reflect restriction, air trapping, poor effort, or mixed disease.",
    workflow: "Check acceptability and reproducibility first, interpret spirometry, evaluate bronchodilator response when performed, review lung volumes, then DLCO and flow-volume loop morphology.",
    interpretation: "Low DLCO with obstruction can suggest emphysema or pulmonary vascular disease, while normal/high DLCO with obstruction may fit asthma; restriction with low DLCO suggests parenchymal disease more than extrapulmonary restriction.",
    safety: "Do not interpret technically unacceptable maneuvers as disease. Stop testing when patient safety criteria or severe symptoms require termination.",
    redFlags: "Marked chest pain, syncope, severe desaturation, hemoptysis, or inability to perform reproducible maneuvers requires stopping and reassessing the test plan.",
    commonErrors: "Calling restriction from low FVC alone, ignoring poor effort, and using a single maneuver instead of reproducible acceptable efforts.",
    examFocus: "Quality comes before physiology; NBRC items frequently embed an invalid maneuver that must be recognized before interpretation.",
    glossary: [
      { term: "FEV1/FVC", definition: "Ratio of forced expiratory volume in one second to forced vital capacity, central to identifying airflow obstruction." },
      { term: "DLCO", definition: "Diffusing capacity of the lung for carbon monoxide, reflecting gas transfer across the alveolar-capillary interface." },
    ],
  },
  {
    id: "rrt-ventilator-waveforms-autopeep",
    careerType: "rrt",
    examTag: "NBRC TMC/CSE",
    regionScope: "BOTH",
    category: "Mechanical Ventilation",
    topic: "Ventilator Waveforms and Auto-PEEP",
    bottomLine: "Waveforms reveal patient-ventilator interaction; expiratory flow that does not return to baseline before the next breath is a key clue to air trapping and auto-PEEP.",
    coreConcept: "Incomplete exhalation increases end-expiratory lung volume and intrinsic pressure, worsening work of breathing and potentially reducing venous return.",
    recognition: "Persistent expiratory flow at the next breath, trigger delay, flow starvation, double triggering, or scooped pressure/flow patterns can identify specific forms of asynchrony.",
    workflow: "Identify the waveform abnormality, correlate with bedside findings, determine whether the cause is patient demand, resistance, compliance, timing, or trigger settings, change one variable, then reassess.",
    interpretation: "Auto-PEEP can improve by increasing expiratory time through lower rate, shorter inspiratory time, higher inspiratory flow, or treatment of obstruction rather than by simply lowering set PEEP.",
    safety: "Severe dynamic hyperinflation can cause hypotension and barotrauma; if a ventilated obstructive patient suddenly collapses, disconnecting briefly to allow exhalation may be lifesaving while the cause is corrected.",
    redFlags: "Acute hypotension with high pressures, sudden desaturation, new absent breath sounds, or a waveform change with loss of delivered volume requires immediate bedside assessment.",
    commonErrors: "Reading numeric values without waveforms, treating asynchrony with sedation before correcting settings, and failing to allow enough expiratory time in obstructive disease.",
    examFocus: "Translate waveform shape into mechanics and a targeted ventilator adjustment.",
    glossary: [
      { term: "Flow starvation", definition: "Insufficient inspiratory flow relative to patient demand, often seen as a concave pressure-time waveform in volume-targeted ventilation." },
      { term: "Double triggering", definition: "Two ventilator breaths delivered with little or no exhalation between them because patient inspiratory effort outlasts the set inspiratory cycle." },
    ],
  },
  {
    id: "rrt-weaning-sbt",
    careerType: "rrt",
    examTag: "NBRC TMC/CSE",
    regionScope: "BOTH",
    category: "Mechanical Ventilation",
    topic: "Ventilator Liberation and Spontaneous Breathing Trials",
    bottomLine: "Successful liberation requires improvement of the original problem, adequate oxygenation and hemodynamics, ability to initiate breaths, and a tolerable spontaneous breathing trial plus airway-protection assessment.",
    coreConcept: "A spontaneous breathing trial tests whether the patient can sustain the work of breathing with minimal support; passing the trial does not guarantee safe extubation if airway protection is poor.",
    recognition: "Readiness includes improving disease, manageable secretions, stable cardiovascular status, acceptable oxygenation on modest support, and sufficient alertness/drive.",
    workflow: "Screen for readiness, reduce sedation when appropriate, perform an SBT, monitor symptoms and objective tolerance, identify reversible failure causes, and separately assess extubation readiness.",
    interpretation: "Tachypnea, distress, hypoxemia, marked tachycardia, hemodynamic instability, or worsening gas exchange during the trial suggests failure and a need to address the cause before repeating.",
    safety: "Do not extubate solely because a numeric weaning index looks favorable; cough, secretion burden, mental status, upper-airway risk, and overall trajectory matter.",
    redFlags: "Stridor risk, weak cough with copious secretions, severe agitation or obtundation, recurrent apnea, or unstable cardiac status argues against immediate extubation.",
    commonErrors: "Using one index as a yes/no rule, performing trials before disease stabilization, and conflating SBT success with airway-protection readiness.",
    examFocus: "Separate readiness to breathe from readiness to protect the airway.",
    glossary: [
      { term: "SBT", definition: "Spontaneous breathing trial using minimal support to assess ability to sustain breathing without full ventilator assistance." },
      { term: "Extubation readiness", definition: "Broader assessment of respiratory independence plus airway protection, secretion management, and upper-airway safety." },
    ],
  },

  {
    id: "paramedic-primary-assessment",
    careerType: "paramedic",
    examTag: "NREMT Paramedic",
    regionScope: "BOTH",
    category: "Patient Assessment",
    topic: "Primary Assessment and Immediate Life Threats",
    bottomLine: "The primary assessment identifies and treats immediate threats to airway, breathing, circulation, neurologic status, and exposure before a detailed history or secondary exam.",
    coreConcept: "Prehospital priorities are dynamic; assessment and treatment happen together, and a newly discovered life threat resets the sequence.",
    recognition: "Inability to speak, abnormal airway sounds, severe respiratory distress, weak central pulses, uncontrolled hemorrhage, altered mental status, or signs of shock require immediate action.",
    workflow: "Confirm scene safety and initial impression, assess airway, breathing and circulation with immediate interventions, evaluate disability, expose as needed, choose transport priority, then continue reassessment.",
    interpretation: "A normal single vital sign does not cancel an abnormal clinical impression; trends, perfusion, work of breathing, mental status, and mechanism or complaint determine acuity.",
    safety: "Do not delay transport or definitive care for low-value procedures when a time-critical threat has already been identified.",
    redFlags: "Uncontrolled major bleeding, threatened airway, apnea or ineffective ventilation, shock, rapidly changing mental status, or peri-arrest physiology requires immediate intervention and transport coordination.",
    commonErrors: "Completing a full history before stabilizing ABC threats, anchoring on one normal measurement, and failing to repeat the primary assessment after an intervention.",
    examFocus: "NREMT questions frequently reward the first action that treats the most immediate threat, not the most complete diagnostic plan.",
    glossary: [
      { term: "Primary assessment", definition: "Rapid systematic assessment aimed at identifying and treating immediate life threats." },
      { term: "General impression", definition: "Early overall judgment of patient acuity based on appearance, work of breathing, interaction, and environment." },
    ],
  },
  {
    id: "paramedic-airway-ventilation",
    careerType: "paramedic",
    examTag: "NREMT Paramedic",
    regionScope: "BOTH",
    category: "Airway and Respiration",
    topic: "Airway Management and Ventilation",
    bottomLine: "Open and maintain the airway with the least invasive effective method, ventilate when breathing is inadequate, and confirm advanced airway placement continuously with clinical assessment and waveform capnography when available.",
    coreConcept: "Oxygenation and ventilation are different problems: oxygen raises inspired oxygen concentration, while ventilation requires movement of gas to remove carbon dioxide.",
    recognition: "Snoring suggests soft-tissue obstruction, gurgling suggests fluid, stridor suggests upper-airway narrowing, and poor chest rise with altered mental status may indicate inadequate ventilation despite spontaneous breathing.",
    workflow: "Position and open the airway, suction when needed, use adjuncts appropriately, provide BVM ventilation with visible chest rise, escalate to advanced airway when indicated, and continuously confirm placement.",
    interpretation: "A rising ETCO2 after resuscitation can indicate improved perfusion; abrupt loss of waveform after intubation suggests disconnection, displacement, obstruction, or severe perfusion loss.",
    safety: "Avoid excessive ventilation rate and pressure, which can reduce venous return, worsen gastric inflation, and increase aspiration risk.",
    redFlags: "Cannot ventilate, cannot oxygenate, progressive airway edema, severe facial trauma, or loss of capnography waveform after advanced airway placement requires immediate corrective action.",
    commonErrors: "Equating a high oxygen flow with adequate ventilation, relying on auscultation alone to confirm an ET tube, and ventilating too rapidly.",
    examFocus: "Choose the simplest effective airway first and distinguish failure of oxygenation from failure of ventilation.",
    glossary: [
      { term: "Waveform capnography", definition: "Continuous graphical measurement of exhaled carbon dioxide used to confirm and monitor ventilation and advanced airway placement." },
      { term: "BVM", definition: "Bag-valve-mask device used to provide positive-pressure ventilation." },
    ],
  },
  {
    id: "paramedic-shock-perfusion",
    careerType: "paramedic",
    examTag: "NREMT Paramedic",
    regionScope: "BOTH",
    category: "Cardiology and Resuscitation",
    topic: "Shock Recognition and Perfusion",
    bottomLine: "Recognize shock from inadequate tissue perfusion before hypotension appears, identify the likely category, control reversible causes, support oxygenation and circulation, and transport promptly.",
    coreConcept: "Compensatory tachycardia and vasoconstriction can preserve blood pressure early, so skin signs, mental status, pulse quality, capillary refill, and overall presentation may reveal shock first.",
    recognition: "Tachycardia, cool or abnormal skin, delayed refill, anxiety or confusion, weak pulses, narrow pulse pressure, and mechanism suggesting blood or fluid loss can precede overt hypotension.",
    workflow: "Control hemorrhage, support airway and breathing, establish indicated vascular access, choose fluid or blood strategy within protocol and shock type, keep warm, reassess perfusion, and expedite definitive care.",
    interpretation: "Not all shock should receive indiscriminate large-volume crystalloid; cardiogenic and obstructive states can worsen with excessive fluid, while hemorrhagic shock needs bleeding control and blood-focused resuscitation when available.",
    safety: "Treat the cause and avoid interventions that delay hemorrhage control or transport. Reassess after every bolus or major intervention.",
    redFlags: "Altered mental status, absent radial pulses, severe hypotension, uncontrolled hemorrhage, distended neck veins with hypotension, or rapidly worsening respiratory distress indicates decompensation.",
    commonErrors: "Waiting for hypotension to diagnose shock, giving the same fluid plan to every shock type, and failing to prevent hypothermia in trauma.",
    examFocus: "Classify shock by physiology and mechanism, then choose the intervention that corrects the cause rather than a one-size-fits-all vital-sign response.",
    glossary: [
      { term: "Compensated shock", definition: "Early shock in which compensatory mechanisms maintain blood pressure despite impaired perfusion." },
      { term: "Obstructive shock", definition: "Shock caused by mechanical obstruction to cardiac filling or outflow, such as tension pneumothorax or massive pulmonary embolism." },
    ],
  },
  {
    id: "paramedic-acs-12lead",
    careerType: "paramedic",
    examTag: "NREMT Paramedic",
    regionScope: "BOTH",
    category: "Cardiology and Resuscitation",
    topic: "Acute Coronary Syndrome and 12-Lead ECG",
    bottomLine: "Obtain and interpret a 12-lead ECG early in suspected ACS, treat symptoms and immediate threats, identify STEMI or high-risk ischemia, and activate the appropriate reperfusion pathway without avoidable delay.",
    coreConcept: "Coronary occlusion produces time-sensitive myocardial ischemia; ECG findings, symptoms, hemodynamics, and contraindications guide prehospital treatment and destination decisions.",
    recognition: "Pressure-like chest discomfort, diaphoresis, dyspnea, nausea, syncope, atypical symptoms in older adults or people with diabetes, and ischemic ST-T changes should raise concern.",
    workflow: "Perform ABC assessment, acquire early 12-lead, give protocol-directed antiplatelet therapy when appropriate, use nitrates only when hemodynamically suitable, repeat ECGs, and notify the receiving system early.",
    interpretation: "Inferior STEMI plus hypotension or clear lungs should prompt consideration of right ventricular involvement; right-sided leads can change nitrate decisions.",
    safety: "Check blood pressure, recent phosphodiesterase inhibitor use, suspected right ventricular infarction, and other contraindications before nitrates.",
    redFlags: "Cardiogenic shock, malignant dysrhythmia, ongoing severe ischemia, dynamic ST elevation, or deteriorating mental status requires rapid escalation and destination prioritization.",
    commonErrors: "Delaying the ECG until after a complete history, assuming a nondiagnostic first tracing excludes ACS, and giving nitrates reflexively to a hypotensive patient.",
    examFocus: "The next best step is often an early ECG or reperfusion-system action, not additional history gathering.",
    glossary: [
      { term: "STEMI", definition: "ST-elevation myocardial infarction caused by acute coronary occlusion requiring urgent reperfusion evaluation." },
      { term: "Right ventricular infarction", definition: "Infarction involving the right ventricle, often associated with inferior MI and preload sensitivity." },
    ],
  },
  {
    id: "paramedic-cardiac-arrest",
    careerType: "paramedic",
    examTag: "NREMT Paramedic",
    regionScope: "BOTH",
    category: "Cardiology and Resuscitation",
    topic: "Adult Cardiac Arrest Algorithms",
    bottomLine: "High-quality CPR, early defibrillation for shockable rhythms, minimal interruptions, appropriate medications, and active treatment of reversible causes drive adult cardiac arrest care.",
    coreConcept: "Coronary and cerebral perfusion fall rapidly when compressions stop, so procedures must be organized around continuous high-quality CPR and rhythm-specific actions.",
    recognition: "Unresponsiveness, absent normal breathing, and no definite pulse within a brief check define cardiac arrest; the first rhythm then determines shockable versus nonshockable pathway.",
    workflow: "Start CPR, attach monitor/defibrillator, shock VF/pulseless VT promptly, resume compressions immediately, obtain vascular access without delaying CPR, use medications per algorithm, and search for reversible causes.",
    interpretation: "A sudden sustained rise in ETCO2 during CPR can indicate return of spontaneous circulation; persistently low ETCO2 also prompts reassessment of compression quality and reversible causes.",
    safety: "Coordinate defibrillation clearly, minimize peri-shock pause, avoid excessive ventilation, and confirm everyone is clear before shock delivery.",
    redFlags: "Recurrent VF, refractory shockable rhythm, severe hypothermia, suspected toxicologic arrest, or traumatic arrest may require protocol-specific modifications and destination decisions.",
    commonErrors: "Pausing compressions for intubation or repeated pulse checks, delaying defibrillation, and hyperventilating after an advanced airway is placed.",
    examFocus: "When several interventions are plausible, choose the one that preserves compressions and delivers indicated defibrillation fastest.",
    glossary: [
      { term: "Peri-shock pause", definition: "Interruption in chest compressions immediately before and after defibrillation; it should be minimized." },
      { term: "ROSC", definition: "Return of spontaneous circulation with an effective perfusing rhythm after cardiac arrest." },
    ],
  },
  {
    id: "paramedic-stroke-assessment",
    careerType: "paramedic",
    examTag: "NREMT Paramedic",
    regionScope: "BOTH",
    category: "Neurology",
    topic: "Acute Stroke Recognition and Destination Decisions",
    bottomLine: "Establish last-known-well time, identify focal neurologic deficits, check glucose, support ABCs, use a validated stroke screen, and transport to an appropriate stroke-capable destination without delay.",
    coreConcept: "Reperfusion benefit is time dependent, and large-vessel occlusion may require endovascular therapy, so prehospital recognition influences both treatment window and destination.",
    recognition: "New facial weakness, arm drift, speech disturbance, gaze deviation, neglect, severe unilateral weakness, or sudden posterior circulation symptoms should trigger stroke evaluation.",
    workflow: "Assess ABCs, determine last known well, check glucose, perform stroke scale, identify anticoagulant use and major mimics, establish transport priority, prenotify the receiving center, and reassess.",
    interpretation: "Hypoglycemia can mimic stroke and must be corrected, but improvement after glucose does not justify ignoring persistent focal deficits.",
    safety: "Avoid unnecessary on-scene delays and avoid aggressive blood-pressure lowering unless directed by protocol for another emergency.",
    redFlags: "Airway compromise, repeated vomiting, rapidly declining consciousness, seizure with persistent deficit, or signs suggesting intracranial hemorrhage requires high-acuity transport and airway readiness.",
    commonErrors: "Using symptom discovery time instead of last-known-well, forgetting glucose, and transporting to the nearest facility when protocol calls for a higher-level stroke destination.",
    examFocus: "Time anchors and destination choice are often more important than performing extra procedures on scene.",
    glossary: [
      { term: "Last known well", definition: "The last time the patient was known to be at neurologic baseline, used to determine treatment eligibility windows." },
      { term: "Large-vessel occlusion", definition: "Occlusion of a major intracranial artery that may be amenable to mechanical thrombectomy." },
    ],
  },
  {
    id: "paramedic-trauma-hemorrhage",
    careerType: "paramedic",
    examTag: "NREMT Paramedic",
    regionScope: "BOTH",
    category: "Trauma",
    topic: "Major Trauma and Hemorrhage Control",
    bottomLine: "Control life-threatening external hemorrhage immediately, identify occult bleeding and chest threats during the primary assessment, prevent hypothermia, and minimize scene time for patients needing definitive trauma care.",
    coreConcept: "Exsanguination can kill before airway procedures are completed; modern trauma sequencing allows catastrophic hemorrhage control to precede traditional ABC steps when necessary.",
    recognition: "Pulsatile or uncontrolled bleeding, shock signs, unstable pelvis, penetrating torso injury, expanding hematoma, absent breath sounds with shock, or high-risk mechanism indicates major trauma.",
    workflow: "Use direct pressure or tourniquet for severe extremity bleeding, pack junctional wounds when appropriate, assess airway and chest, stabilize major threats, prevent heat loss, choose trauma destination, and transport rapidly.",
    interpretation: "A temporarily normal blood pressure does not exclude dangerous bleeding; mechanism, pulse quality, skin, mental status, shock index trends, and serial exams matter.",
    safety: "Do not loosen an effective tourniquet in the field simply because bleeding has stopped, and do not delay transport for procedures that do not change immediate survival.",
    redFlags: "Persistent shock, suspected tension pneumothorax, pelvic instability with hypotension, uncontrolled junctional hemorrhage, or deteriorating mental status demands immediate escalation.",
    commonErrors: "Repeatedly removing dressings to inspect a wound, delaying tourniquet use in life-threatening extremity hemorrhage, and allowing preventable hypothermia.",
    examFocus: "Prioritize hemorrhage control and rapid transport over diagnostic completeness.",
    glossary: [
      { term: "Junctional hemorrhage", definition: "Severe bleeding at areas such as the groin or axilla where standard limb tourniquets are not effective." },
      { term: "Shock index", definition: "Heart rate divided by systolic blood pressure; a rising value can support concern for worsening circulatory compromise." },
    ],
  },
  {
    id: "paramedic-anaphylaxis",
    careerType: "paramedic",
    examTag: "NREMT Paramedic",
    regionScope: "BOTH",
    category: "Medical Emergencies",
    topic: "Anaphylaxis and Epinephrine",
    bottomLine: "Intramuscular epinephrine is first-line treatment for anaphylaxis; airway support, oxygenation, fluids, bronchodilation, and repeated reassessment are adjuncts rather than substitutes.",
    coreConcept: "Anaphylaxis causes vasodilation, capillary leak, bronchospasm, and upper-airway edema; epinephrine reverses these through alpha and beta adrenergic effects.",
    recognition: "Acute illness with airway compromise, bronchospasm, hypotension, or involvement of multiple organ systems after a likely trigger supports anaphylaxis even when hives are absent.",
    workflow: "Give IM epinephrine promptly, position appropriately, support airway and breathing, obtain vascular access and fluids for shock, add bronchodilator for persistent bronchospasm, repeat epinephrine as indicated, and transport.",
    interpretation: "Improved skin findings do not guarantee resolution of airway or circulatory risk; repeat assessment of voice, stridor, wheeze, blood pressure, and mental status.",
    safety: "Do not delay IM epinephrine while attempting IV access or giving antihistamines. Antihistamines do not treat airway edema or shock.",
    redFlags: "Stridor, progressive tongue swelling, refractory hypotension, severe bronchospasm, altered mental status, or biphasic recurrence requires aggressive support and rapid transport.",
    commonErrors: "Treating with antihistamines first, waiting for a rash, and using an inappropriate route or concentration for epinephrine.",
    examFocus: "When anaphylaxis is present, epinephrine comes before supportive adjuncts unless an immediate basic airway maneuver is required simultaneously.",
    glossary: [
      { term: "Anaphylaxis", definition: "Rapid systemic hypersensitivity reaction that can cause life-threatening airway, breathing, or circulatory compromise." },
      { term: "Biphasic reaction", definition: "Recurrence of anaphylactic symptoms after initial resolution without re-exposure to the trigger." },
    ],
  },
  {
    id: "paramedic-seizure-status",
    careerType: "paramedic",
    examTag: "NREMT Paramedic",
    regionScope: "BOTH",
    category: "Neurology",
    topic: "Seizure and Status Epilepticus",
    bottomLine: "Protect the patient, support airway and oxygenation, check glucose, treat prolonged or recurrent seizure activity promptly with protocol-directed benzodiazepine therapy, and look for reversible causes.",
    coreConcept: "Prolonged seizures increase metabolic demand, acidosis, hyperthermia, aspiration risk, and neuronal injury, so persistent activity requires time-sensitive treatment.",
    recognition: "Ongoing convulsions, repeated seizures without recovery, subtle persistent motor activity with depressed consciousness, or prolonged postictal compromise can represent status epilepticus.",
    workflow: "Protect from injury, maintain airway positioning and suction readiness, assess breathing, check glucose, time the seizure, give benzodiazepine when indicated, reassess ventilation, and transport while evaluating causes.",
    interpretation: "Postictal confusion should gradually improve; persistent or worsening unresponsiveness requires reassessment for ongoing seizure, hypoxia, hypoglycemia, trauma, stroke, or toxicologic cause.",
    safety: "Do not place objects in the mouth or forcibly restrain convulsions; after benzodiazepines, be ready to assist ventilation.",
    redFlags: "Pregnancy with seizure, severe hyperthermia, persistent hypoxia, repeated seizure without recovery, significant trauma, or focal deficit after the event requires urgent escalation.",
    commonErrors: "Focusing on IV access while the airway is unprotected, failing to check glucose, and underestimating respiratory depression after sedating medication.",
    examFocus: "The best answer often combines seizure termination with airway and ventilation readiness.",
    glossary: [
      { term: "Status epilepticus", definition: "Prolonged seizure activity or recurrent seizures without return to baseline requiring urgent treatment." },
      { term: "Postictal state", definition: "Transient period of neurologic impairment following a seizure." },
    ],
  },
  {
    id: "paramedic-pediatric-respiratory-distress",
    careerType: "paramedic",
    examTag: "NREMT Paramedic",
    regionScope: "BOTH",
    category: "Pediatrics",
    topic: "Pediatric Respiratory Distress and Failure",
    bottomLine: "Children compensate for respiratory illness until they tire; recognize work of breathing early, support oxygenation and ventilation, and treat a slowing respiratory rate with worsening mental status as deterioration, not improvement.",
    coreConcept: "Pediatric cardiac arrest is often the endpoint of progressive respiratory failure, making early airway and ventilation support especially important.",
    recognition: "Retractions, nasal flaring, grunting, head bobbing, abnormal breath sounds, tachypnea, poor feeding, cyanosis, or altered interaction indicate increasing severity.",
    workflow: "Use a pediatric assessment triangle, position the airway, suction gently when needed, provide oxygen, support BVM ventilation for inadequate effort, identify likely upper versus lower airway process, and reassess frequently.",
    interpretation: "A child who was tachypneic and becomes bradypneic, quiet, or less responsive is likely tiring and moving toward failure.",
    safety: "Avoid agitating a child with suspected critical upper-airway obstruction unnecessarily; keep resuscitation equipment ready while prioritizing oxygenation and transport.",
    redFlags: "Poor air movement, cyanosis despite oxygen, bradypnea, apnea, altered consciousness, weak pulses, or exhaustion indicates respiratory failure or peri-arrest physiology.",
    commonErrors: "Assuming quieter breathing means improvement, using adult-sized equipment, and delaying assisted ventilation because spontaneous breaths are still present but ineffective.",
    examFocus: "Differentiate distress from failure; declining effort in a sick child is a bad sign.",
    glossary: [
      { term: "Pediatric assessment triangle", definition: "Rapid visual assessment of appearance, work of breathing, and circulation to skin." },
      { term: "Respiratory failure", definition: "Inability to maintain adequate oxygenation or ventilation despite compensatory effort." },
    ],
  },
];
