import type { AlliedAuthoredTopic } from "./types";

const topic = (
  id: string, careerType: string, examTag: string, regionScope: "US" | "CAN" | "BOTH",
  category: string, name: string, bottomLine: string, coreConcept: string,
  recognition: string, workflow: string, interpretation: string, safety: string,
  redFlags: string, commonErrors: string, examFocus: string,
  glossary: Array<{ term: string; definition: string }>,
): AlliedAuthoredTopic => ({ id, careerType, examTag, regionScope, category, topic: name, bottomLine, coreConcept, recognition, workflow, interpretation, safety, redFlags, commonErrors, examFocus, glossary });

export const alliedTopics08: AlliedAuthoredTopic[] = [
  topic("rrt-ecmo-respiratory-support", "rrt", "NBRC TMC/CSE", "US", "Advanced Respiratory Support", "ECMO Fundamentals for Respiratory Therapists",
    "ECMO supports gas exchange or circulation when conventional therapy cannot safely meet physiologic needs; bedside care still requires lung protection, circuit awareness, and rapid recognition of failure.",
    "Venovenous ECMO primarily supports oxygenation and carbon-dioxide removal, whereas venoarterial ECMO also provides circulatory support; blood flow and sweep gas affect different components of gas exchange.",
    "Refractory hypoxemia or hypercapnia despite optimized ventilation, severe reversible respiratory failure, and escalating ventilator injury risk can prompt ECMO evaluation in an appropriate center.",
    "Verify the ECMO mode and goals, assess native lung function and ventilator settings, trend oxygenation and carbon dioxide, inspect circuit observations within role, coordinate airway care, and escalate changes immediately.",
    "A falling arterial saturation may reflect patient, ventilator, cannula, circuit, recirculation, or oxygenator problems; identify the physiologic compartment before changing support.",
    "Never manipulate ECMO hardware outside role or local policy; protect the airway and circuit, use meticulous infection precautions, and treat abrupt circuit or patient changes as emergencies.",
    "Sudden desaturation, loss of circuit flow, visible air, major bleeding, acute hypotension, rapidly rising carbon dioxide, or suspected oxygenator failure requires immediate ECMO-team escalation.",
    "Treating ECMO as a replacement for bedside respiratory assessment, confusing sweep with blood-flow effects, and increasing ventilator intensity despite an established lung-rest strategy.",
    "NBRC-level reasoning emphasizes which variable affects oxygenation versus carbon-dioxide clearance and recognition of emergencies requiring immediate team escalation.",
    [{ term: "Sweep gas", definition: "Gas flow through the membrane oxygenator that strongly influences carbon-dioxide removal." }, { term: "Recirculation", definition: "Return of oxygenated extracorporeal blood into the drainage cannula, reducing effective systemic oxygen delivery." }]),

  topic("rrt-neonatal-ventilation", "rrt", "NBRC TMC/CSE", "US", "Neonatal Respiratory Care", "Neonatal Respiratory Distress and Ventilatory Support",
    "Support neonatal gas exchange with the least injurious effective pressure and oxygen while correcting temperature, airway, surfactant, and transition problems that increase respiratory work.",
    "Premature and newborn lungs differ in compliance, airway caliber, functional residual capacity, oxygen toxicity susceptibility, and surfactant availability, making adult ventilation assumptions unsafe.",
    "Grunting, retractions, nasal flaring, apnea, cyanosis, poor air entry, rising oxygen need, and abnormal blood gases indicate worsening neonatal respiratory compromise.",
    "Stabilize temperature and airway position, assess spontaneous effort, provide appropriately blended oxygen or CPAP, assist ventilation when indicated, verify pressures and chest movement, and reassess gas exchange frequently.",
    "Excess oxygen or pressure can be harmful even when saturation improves; interpret response alongside work of breathing, perfusion, blood gases, and gestational context.",
    "Use neonatal-sized interfaces and pressure limits, avoid hyperoxia, and recognize that excessive ventilation can rapidly cause air leak or hypocapnia.",
    "Persistent bradycardia, apnea, severe retractions with fatigue, asymmetric breath sounds, rapidly rising oxygen requirement, or poor perfusion requires immediate escalation.",
    "Using adult device assumptions, chasing high saturation targets, overlooking temperature and positioning, and escalating pressure without checking seal, airway patency, and pneumothorax.",
    "Differentiate oxygenation failure, ventilation failure, surfactant deficiency, apnea, and air leak while choosing age-appropriate support.",
    [{ term: "CPAP", definition: "Continuous positive airway pressure used to maintain functional residual capacity during spontaneous breathing." }, { term: "Surfactant", definition: "Surface-active material that reduces alveolar surface tension and improves lung compliance." }]),

  topic("paramedic-toxic-alcohols", "paramedic", "NREMT Paramedic", "US", "Toxicology", "Toxic Alcohol and High-Risk Ingestion Recognition",
    "Suspect dangerous toxic ingestion from physiology and exposure history, stabilize ABCs, identify toxidrome and metabolic clues, and transport early for definitive antidotal and extracorporeal therapy when indicated.",
    "Methanol, ethylene glycol, and other high-risk ingestions may initially resemble ethanol intoxication before toxic metabolites produce severe acidosis and organ injury.",
    "Visual complaints, unexplained high-anion-gap acidosis when known, renal symptoms, altered mental status, tachypnea, seizures, or credible access to toxic alcohols are high-risk clues.",
    "Protect airway and ventilation, check glucose, obtain focused exposure history and containers when safe, treat seizures and shock per protocol, contact poison resources when available, and prioritize capable destination transport.",
    "A relatively well-appearing early patient can still have a lethal exposure; absence of dramatic symptoms does not safely exclude toxic alcohol poisoning.",
    "Do not induce vomiting or delay transport attempting field identification; preserve responder safety around unknown chemicals and bring product information without contaminating the ambulance.",
    "Severe altered consciousness, seizures, shock, respiratory failure, visual disturbance, or suspected substantial toxic alcohol ingestion requires urgent transport and notification.",
    "Assuming all alcohol-smelling or intoxicated patients have ethanol exposure, waiting for late organ findings, and overlooking co-ingestion, trauma, or hypoglycemia.",
    "NREMT questions emphasize stabilization, poison recognition, and destination urgency rather than definitive hospital dosing.",
    [{ term: "Toxic metabolite", definition: "Harmful product formed when the body metabolizes a parent substance." }, { term: "Anion gap", definition: "Calculated relationship among measured electrolytes that can reveal unmeasured acids in selected poisonings." }]),

  topic("paramedic-crush-syndrome", "paramedic", "NREMT Paramedic", "US", "Trauma", "Crush Injury and Reperfusion Risk",
    "A prolonged crush injury can become more dangerous at release because potassium, acids, and cellular contents enter the circulation; anticipate deterioration before extrication is completed.",
    "Sustained muscle compression causes ischemic cellular injury and rhabdomyolysis; reperfusion can abruptly worsen hyperkalemia, acidosis, dysrhythmia, and shock.",
    "Prolonged entrapment, major muscle compression, swollen or tense extremities, dark urine when present, shock, or ECG changes after release increase concern.",
    "Coordinate with rescue, establish monitoring and vascular access when feasible, begin protocol-directed supportive therapy before release in high-risk cases, prepare for dysrhythmia treatment, and transport to an appropriate trauma center.",
    "A patient may appear stable while trapped because toxic metabolites remain sequestered; deterioration immediately after release is a predictable physiologic hazard.",
    "Do not delay life-saving extrication when the environment is unsafe, but when time permits coordinate medical preparation with rescue rather than treating release as a purely mechanical event.",
    "Wide-complex dysrhythmia, sudden hypotension, cardiac arrest, severe extremity swelling with neurovascular compromise, or prolonged multisite compression requires immediate escalation.",
    "Waiting until after release to establish a plan, focusing only on orthopedic injury, and failing to anticipate hyperkalemia-related cardiac instability.",
    "Recognize the pre-release preparation priority and the cardiovascular consequences of reperfusion.",
    [{ term: "Rhabdomyolysis", definition: "Breakdown of skeletal muscle with release of intracellular contents into the circulation." }, { term: "Reperfusion", definition: "Restoration of blood flow to ischemic tissue, which can abruptly release accumulated metabolites." }]),

  topic("mlt-flow-cytometry-basics", "mlt", "ASCP MLT", "US", "Hematology", "Flow Cytometry Principles and Leukemia/Lymphoma Screening",
    "Flow cytometry classifies cell populations by light scatter and antigen expression, but meaningful interpretation requires correct gating, controls, specimen quality, and correlation with morphology.",
    "Cells pass individually through a laser; forward and side scatter approximate size and internal complexity while fluorochrome-labeled antibodies identify antigen patterns.",
    "Unexplained blasts, atypical lymphoid populations, cytopenias with abnormal morphology, or suspected hematolymphoid malignancy can prompt immunophenotypic testing.",
    "Verify specimen and viability, review morphology, apply appropriate antibody panels and controls, establish gates, evaluate antigen patterns, and correlate with clinical, morphologic, cytogenetic, or molecular findings.",
    "No single antigen usually defines a malignancy; abnormal combinations, intensity, maturation pattern, and clonality-related findings are interpreted together.",
    "Poor viability, delayed specimens, nonspecific binding, incorrect gating, and inadequate controls can create misleading populations and require technical review.",
    "Unexpected loss of viability, implausible population distribution, control failure, or a critical new blast population requires prompt senior review and appropriate communication.",
    "Calling disease from one marker, ignoring morphology, using an inappropriate gate, and interpreting percentages without considering absolute counts and specimen composition.",
    "ASCP items focus on scatter, fluorochromes, gating, controls, and pattern-based rather than single-marker interpretation.",
    [{ term: "Gate", definition: "Defined region used to select a cell population for focused flow-cytometric analysis." }, { term: "Fluorochrome", definition: "Fluorescent molecule attached to an antibody and detected after laser excitation." }]),

  topic("mlt-mass-spectrometry", "mlt", "ASCP MLT", "US", "Clinical Chemistry", "Mass Spectrometry and Confirmatory Testing",
    "Mass spectrometry improves analytical specificity by separating and detecting compounds according to mass-to-charge behavior, but specimen preparation, calibration, internal standards, and interference review remain essential.",
    "Chromatographic separation followed by mass analysis can distinguish compounds that immunoassays cross-react with, making the method useful for confirmatory and targeted quantitative testing.",
    "Unexpected screening results, therapeutic drug measurement, toxicology confirmation, endocrine testing, and assays requiring high analytical specificity are common applications.",
    "Verify specimen suitability, perform extraction or preparation, use calibrators and internal standards, review retention and ion criteria, assess QC, quantify within the validated range, and investigate discordant results.",
    "A detected signal is valid only when identity criteria, calibration, controls, and quantitative limits are satisfied; low-level noise is not automatically a positive result.",
    "Carryover, matrix effects, ion suppression, contamination, and incorrect internal-standard performance can produce clinically important errors.",
    "Control failure, major carryover, internal-standard failure, retention mismatch, or a result outside validated measurement capability requires withholding release.",
    "Assuming mass spectrometry is error-proof, ignoring preanalytic contamination, and reporting peaks without validated identification criteria.",
    "Differentiate screening immunoassay from confirmatory analytical methods and recognize the purpose of internal standards and chromatography.",
    [{ term: "Internal standard", definition: "Known compound added to specimens and calibrators to monitor extraction and analytical performance." }, { term: "Ion suppression", definition: "Matrix-related reduction in ionization efficiency that can decrease measured signal." }]),

  topic("pharmacy-medication-reconciliation", "pharmacyTech", "PTCB CPHT", "BOTH", "Medication Safety", "Medication Reconciliation and Transition-of-Care Support",
    "Medication reconciliation prevents omissions, duplications, interactions, and unintended continuation by building the most accurate medication history possible and resolving discrepancies through the pharmacist or prescriber workflow.",
    "Medication lists from one source are often incomplete; reconciliation compares multiple sources and distinguishes intentional therapeutic changes from accidental discrepancies.",
    "Recent hospitalization, multiple prescribers, polypharmacy, unclear adherence, duplicate products, high-alert medicines, and conflicting lists increase discrepancy risk.",
    "Collect medication name, strength, route, schedule, indication when known, last use, allergies, adherence, OTC and natural products; compare records and flag discrepancies for pharmacist review.",
    "A difference between lists is not automatically an error; determine whether it is intentional, documented, clinically plausible, and communicated to the patient and next care setting.",
    "Technicians must not independently make clinical decisions outside scope; ambiguous dosing, allergy conflicts, or therapeutic substitutions require pharmacist escalation.",
    "Unexplained anticoagulant, insulin, opioid, anticonvulsant, transplant, or other high-alert discrepancy requires prompt pharmacist review before transition.",
    "Copying the old list without verification, omitting nonprescription products, treating adherence as yes/no without clarification, and silently resolving clinical discrepancies.",
    "PTCB/PEBC-style reasoning emphasizes accurate collection, scope boundaries, and escalation of clinically meaningful discrepancies.",
    [{ term: "Medication reconciliation", definition: "Formal process of comparing medication information across transitions to identify and resolve discrepancies." }, { term: "Best possible medication history", definition: "Systematically obtained medication history using patient interview plus other reliable information sources." }]),

  topic("pharmacy-hazardous-drugs", "pharmacyTech", "PTCB CPHT", "US", "Compounding", "Hazardous Drug Handling and Exposure Prevention",
    "Hazardous-drug safety depends on recognizing exposure risk, using engineering controls and PPE, preventing contamination, and following dedicated receiving, preparation, transport, spill, and waste procedures.",
    "Hazardous drugs can expose workers through aerosols, droplets, contaminated surfaces, sharps, or excreta; layered controls reduce occupational exposure.",
    "Antineoplastic agents and other drugs identified by institutional hazardous-drug policy require special handling from receipt through disposal.",
    "Identify the drug and hazard category, use required engineering controls and PPE, follow negative-pressure or containment procedures when applicable, label and transport securely, decontaminate surfaces, and manage waste per policy.",
    "Visible cleanliness does not prove absence of contamination; safe handling relies on validated process and environmental controls rather than appearance.",
    "Never improvise spill cleanup or use routine compounding controls when hazardous-drug requirements call for higher containment.",
    "Spill outside containment, PPE breach, sharps exposure, damaged hazardous-drug package, ventilation failure, or symptomatic exposure requires immediate exposure protocol activation.",
    "Treating hazardous and nonhazardous compounding as equivalent, inconsistent PPE, transporting unsealed preparations, and cleaning spills without the designated kit and procedure.",
    "Know hierarchy of controls, PPE, containment principles, and the first response to exposure or a spill.",
    [{ term: "Containment", definition: "Engineering and procedural controls designed to keep hazardous drug contamination from spreading." }, { term: "Deactivation", definition: "Treatment intended to render a hazardous drug inactive before further decontamination and cleaning steps." }]),

  topic("imaging-trauma-radiography", "imaging", "ARRT Radiography", "US", "Procedures", "Trauma Radiography and Modified Positioning",
    "Trauma imaging prioritizes life threats, spinal and fracture precautions, diagnostic coverage, and image acquisition with the least patient movement compatible with the clinical question.",
    "Standard positioning may be unsafe after trauma; horizontal-beam and modified projections preserve alignment while still demonstrating anatomy and fluid or air relationships.",
    "Unstable mechanism, suspected spinal injury, severe pain, deformity, immobilization devices, or inability to cooperate requires adaptation before moving the patient.",
    "Review the request and precautions, communicate with the trauma team, preserve immobilization, position equipment rather than forcing the patient, collimate, obtain required projections, evaluate coverage and exposure, and repeat only when necessary.",
    "A technically imperfect image may still be diagnostically adequate in an unstable patient; balance ideal positioning against the risk created by movement or delay.",
    "Never remove immobilization or manipulate a suspected unstable injury without appropriate clinical authorization and assistance.",
    "Deteriorating airway or circulation, new neurologic deficit, uncontrolled movement risk, or suspected unstable cervical or pelvic injury requires team coordination before imaging maneuvers.",
    "Chasing textbook positioning despite instability, unnecessary repeats, poor communication during detector placement, and cropping anatomy needed for trauma interpretation.",
    "ARRT items test modified projections, horizontal-beam principles, radiation protection, and patient safety under trauma constraints.",
    [{ term: "Horizontal beam", definition: "X-ray beam directed parallel to the floor, useful when the patient cannot safely change position." }, { term: "Trauma modification", definition: "Adaptation of a standard projection to preserve diagnostic value while respecting injury precautions." }]),

  topic("imaging-fluoroscopy-dose", "imaging", "ARRT Radiography", "US", "Radiation Safety",