ALTER TABLE ai_jobs
  ADD COLUMN IF NOT EXISTS tier text,
  ADD COLUMN IF NOT EXISTS content_type text,
  ADD COLUMN IF NOT EXISTS config jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS progress jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS logs jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS model text DEFAULT 'gpt-4o-mini',
  ADD COLUMN IF NOT EXISTS model_tier text DEFAULT 'cheapest',
  ADD COLUMN IF NOT EXISTS batch_size integer DEFAULT 25,
  ADD COLUMN IF NOT EXISTS spend_cap double precision,
  ADD COLUMN IF NOT EXISTS duplicate_protection boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS dry_run boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS topic text,
  ADD COLUMN IF NOT EXISTS specialty text,
  ADD COLUMN IF NOT EXISTS framework text,
  ADD COLUMN IF NOT EXISTS current_stage text,
  ADD COLUMN IF NOT EXISTS cost_estimate double precision DEFAULT 0,
  ADD COLUMN IF NOT EXISTS actual_cost double precision DEFAULT 0,
  ADD COLUMN IF NOT EXISTS item_count integer DEFAULT 1,
  ADD COLUMN IF NOT EXISTS items_completed integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS items_failed integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS duplicates_skipped integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS retry_count integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS max_retries integer DEFAULT 3,
  ADD COLUMN IF NOT EXISTS created_by text,
  ADD COLUMN IF NOT EXISTS started_at timestamptz,
  ADD COLUMN IF NOT EXISTS completed_at timestamptz,
  ADD COLUMN IF NOT EXISTS cancelled_at timestamptz,
  ADD COLUMN IF NOT EXISTS paused_at timestamptz,
  ADD COLUMN IF NOT EXISTS resumed_at timestamptz,
  ADD COLUMN IF NOT EXISTS error text;
