name: nursenest
region: tor

services:
  - name: web
    environment_slug: docker
    source_dir: /
    http_port: 5000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    health_check:
      http_path: /
      initial_delay_seconds: 30
      period_seconds: 15
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 6
    envs:
      - key: NODE_ENV
        value: production
        scope: RUN_TIME
      - key: PORT
        value: "5000"
        scope: RUN_TIME
      - key: ADMIN_JWT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
