import OpenAI from "openai";
import { storage } from "./storage";

const openai = new OpenAI({
  apiKey: process.env.AI_INTEGRATIONS_OPENAI_API_KEY,
  baseURL: process.env.AI_INTEGRATIONS_OPENAI_BASE_URL,
});

const NURSING_TOPICS = [
  "Clinical judgment in nursing practice",
  "NCLEX-RN preparation strategies",
  "Patient safety and medication administration",
  "Evidence-based nursing interventions",
  "Nursing assessment techniques",
  "Critical care nursing fundamentals",
  "Pediatric nursing considerations",
  "Maternal-newborn nursing care",
  "Mental health nursing approaches",
  "Geriatric nursing best practices",
  "Wound care management",
  "Pain management in nursing",
  "Infection control protocols",
  "Nursing documentation standards",
  "Pharmacology for nurses",
  "Cardiovascular nursing assessment",
  "Respiratory nursing interventions",
  "Neurological nursing assessment",
  "Endocrine disorders in nursing",
  "Gastrointestinal nursing care",
  "Renal and urinary nursing",
  "Musculoskeletal nursing assessment",
  "Integumentary system nursing care",
  "Fluid and electrolyte balance",
  "Acid-base imbalances in nursing",
  "Nursing leadership and management",
  "Cultural competence in nursing",
  "Nursing ethics and legal considerations",
  "Telehealth nursing practices",
  "New graduate nurse transition tips",
  "ICU nursing orientation essentials",
  "Emergency department nursing skills",
  "Surgical nursing pre-op and post-op care",
  "Oncology nursing fundamentals",
  "Diabetes management for nurses",
  "Hypertension nursing care plans",
  "Heart failure nursing interventions",
  "COPD nursing management",
  "Stroke nursing assessment and care",
  "Sepsis identification and management",
  "Blood transfusion nursing protocols",
  "IV therapy and venipuncture skills",
  "Nursing care plan development",
  "SBAR communication in nursing",
  "Delegation in nursing practice",
  "Time management for nurses",
  "Burnout prevention in nursing",
  "Nursing research and EBP",
  "Quality improvement in nursing",
  "Patient education strategies",
];

function formatAPA7Citation(author: string, year: number, title: string, source: string, url?: string): string {
  const urlPart = url ? ` ${url}` : "";
  return `${author} (${year}). ${title}. *${source}*.${urlPart}`;
}

function formatMLACitation(author: string, title: string, source: string, year: number, url?: string): string {
  const urlPart = url ? ` ${url}` : "";
  return `${author}. "${title}." *${source}*, ${year}.${urlPart}`;
}

export function formatCitations(citations: Array<{author: string; year: number; title: string; source: string; url?: string}>, style: "apa7" | "mla"): string {
  if (style === "apa7") {
    return citations.map(c => formatAPA7Citation(c.author, c.year, c.title, c.source, c.url)).join("\n\n");
  }
  return citations.map(c => formatMLACitation(c.author, c.title, c.source, c.year, c.url)).join("\n\n");
}

export async function generateBlogPost(topic?: string, citationStyle: "apa7" | "mla" = "apa7"): Promise<{
  title: string;
  slug: string;
  summary: string;
  content: any[];
  tags: string[];
  seoTitle: string;
  seoDescription: string;
  seoKeywords: string[];
  primaryKeyword: string;
  citations: string;
}> {
  const selectedTopic = topic || NURSING_TOPICS[Math.floor(Math.random() * NURSING_TOPICS.length)];

  const response = await openai.chat.completions.create({
    model: "gpt-5-mini",
    messages: [
      {
        role: "system",
        content: `You are a scholarly nursing education content writer creating medically accurate, evidence-based, citable blog posts for NurseNest, a nursing education platform. Write content suitable for nursing students (RPN/LVN, RN, and NP levels) at a scholarly level so students can cite these posts in their academic work.

CRITICAL RULES:
- All medical information must be clinically accurate and evidence-based
- Include proper nursing scope of practice considerations
- NurseNest is NOT affiliated with NCLEX, NCSBN, CNO, or any regulatory body
- Use professional academic language that is still accessible
- Include clinical pearls and practical tips
- ABSOLUTELY NO em dashes (--), en dashes, or any dash longer than a hyphen. Use commas, semicolons, colons, or periods instead.
- ABSOLUTELY NO emojis, checkmarks, bullet point symbols, or any unicode special characters
- ABSOLUTELY NO phrases like "In conclusion", "Let's explore", "dive into", "In this article", or other AI-typical phrasing
- Write in a formal academic tone as if published in a nursing education journal
- Do NOT use exclamation marks
- The writing must read as if authored by a human clinical educator, not generated by AI
- MUST include a dedicated section comparing Adults vs Pediatrics with developmental considerations (age-specific differences in presentation, assessment, treatment, dosing, vital sign norms, developmental milestones, and family-centered care implications)
- MUST use in-text APA 7 citations throughout the post (e.g., "According to Potter et al. (2023)..." or "...has been documented in clinical literature (Hockenberry & Wilson, 2022)")
- Every factual clinical claim MUST have an in-text citation

SCHOLARLY SOURCE REQUIREMENTS (MANDATORY):
- ALL references MUST be from peer-reviewed scholarly sources published within the last 5 years (2021-2026)
- Acceptable sources: peer-reviewed nursing journals (e.g., Journal of Clinical Nursing, American Journal of Nursing, Nursing Research, Journal of Nursing Education, Journal of Advanced Nursing, International Journal of Nursing Studies, Clinical Nursing Research, Journal of Nursing Scholarship), systematic reviews, meta-analyses, clinical practice guidelines from recognized bodies (e.g., AHA, ANA, RNAO, CNA)
- Each reference MUST include a real DOI URL when available (format: https://doi.org/10.xxxx/xxxxx)
- Do NOT fabricate citations. Only cite sources that are plausible real publications from known nursing/medical journals
- Include a minimum of 6 peer-reviewed references
- Every clinical claim, statistic, or practice recommendation MUST have an in-text citation
- In-text citations must appear naturally within the paragraph text, not just at the end

You must respond with valid JSON in this exact format:
{
  "title": "Blog post title",
  "slug": "url-friendly-slug",
  "summary": "2-3 sentence scholarly summary",
  "content": [
    {"type": "heading", "text": "Section heading"},
    {"type": "paragraph", "text": "Paragraph with in-text APA7 citations like (Author, Year)..."},
    {"type": "heading", "text": "Adult vs Pediatric Considerations"},
    {"type": "paragraph", "text": "Detailed comparison of adult and pediatric differences with developmental considerations..."},
    {"type": "list", "items": ["item1", "item2"]},
    {"type": "callout", "text": "Clinical pearl or important note"}
  ],
  "tags": ["tag1", "tag2"],
  "seoTitle": "SEO optimized title (60 chars max)",
  "seoDescription": "Meta description (155 chars max)",
  "seoKeywords": ["keyword1", "keyword2"],
  "primaryKeyword": "main keyword",
  "citations": [
    {"author": "Author, A. B.", "year": 2024, "title": "Source Title", "source": "Journal Name or Publisher", "url": "https://doi.org/10.xxxx/xxxxx"}
  ]
}`
      },
      {
        role: "user",
        content: `Write a comprehensive, scholarly, medically accurate nursing education blog post about: "${selectedTopic}".

Requirements:
1. Include a minimum of 6 peer-reviewed scholarly citations in APA 7 format
2. ALL sources MUST be from peer-reviewed journals published between 2021-2026 (within the last 5 years)
3. Use ONLY scholarly sources: peer-reviewed nursing journals, systematic reviews, meta-analyses, or clinical practice guidelines from recognized professional bodies
4. Every in-text citation must correspond to a reference in the citations array, and every reference must be cited in-text at least once
5. In-text APA 7 citations must appear naturally within paragraph text (e.g., "According to Potter et al. (2023)..." or "...has been documented (Hockenberry & Wilson, 2022)")
6. The post should be 1000-1500 words with multiple sections, clinical pearls, and practical application tips
7. MUST include a dedicated "Adult vs Pediatric Considerations" section covering:
   - Age-specific differences in presentation and pathophysiology
   - Developmental considerations across pediatric age groups (neonate, infant, toddler, school-age, adolescent)
   - Differences in assessment findings, vital sign norms, and treatment approaches
   - Family-centered care implications
   - Pediatric-specific safety considerations and dosing differences
8. Write at a scholarly level suitable for academic citation by nursing students
9. Each citation must include a DOI URL when available (format: https://doi.org/10.xxxx/xxxxx)`
      }
    ],
    response_format: { type: "json_object" },
    max_completion_tokens: 8192,
  });

  const parsed = JSON.parse(response.choices[0]?.message?.content || "{}");

  function stripDashes(str: string): string {
    return str
      .replace(/\u2014/g, ", ")
      .replace(/\u2013/g, " to ")
      .replace(/ - /g, ", ")
      .replace(/–/g, " to ")
      .replace(/\s*--\s*/g, ", ");
  }

  if (parsed.content && Array.isArray(parsed.content)) {
    parsed.content = parsed.content.map((block: any) => {
      if (block.text) block.text = stripDashes(block.text);
      if (block.content) block.content = stripDashes(block.content);
      if (block.items && Array.isArray(block.items)) {
        block.items = block.items.map((item: string) => stripDashes(item));
      }
      return block;
    });
  }

  if (parsed.title) parsed.title = stripDashes(parsed.title);
  if (parsed.summary) parsed.summary = stripDashes(parsed.summary);

  const formattedCitations = parsed.citations
    ? formatCitations(parsed.citations, citationStyle)
    : "";

  if (parsed.citations && Array.isArray(parsed.citations) && parsed.citations.length > 0) {
    const referenceItems = parsed.citations.map((c: any) => {
      if (citationStyle === "apa7") {
        return formatAPA7Citation(c.author, c.year, c.title, c.source, c.url);
      }
      return formatMLACitation(c.author, c.title, c.source, c.year, c.url);
    });
    parsed.content.push(
      { type: "heading", text: citationStyle === "apa7" ? "References (APA 7th Edition)" : "Works Cited (MLA)" },
      { type: "references", items: referenceItems }
    );
  }

  return {
    title: parsed.title || selectedTopic,
    slug: parsed.slug || selectedTopic.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""),
    summary: parsed.summary || "",
    content: parsed.content || [],
    tags: parsed.tags || [],
    seoTitle: parsed.seoTitle || parsed.title || selectedTopic,
    seoDescription: parsed.seoDescription || parsed.summary || "",
    seoKeywords: parsed.seoKeywords || [],
    primaryKeyword: parsed.primaryKeyword || "",
    citations: formattedCitations,
  };
}

export async function runBlogScheduler(): Promise<{ generated: number; message: string }> {
  const config = await storage.getBlogConfig();
  if (!config || !config.isActive) {
    return { generated: 0, message: "Blog automation is not active" };
  }

  const now = new Date();
  const dayCount = config.dayCount || 0;
  const totalPosts = config.totalPostsGenerated || 0;

  let postsToGenerate = 0;
  if (dayCount < 120) {
    postsToGenerate = config.postsPerDay || 2;
  } else if (dayCount < 220) {
    postsToGenerate = 1;
  } else {
    return { generated: 0, message: "Blog schedule complete (220 days)" };
  }

  if (config.lastPostAt) {
    const lastPost = new Date(config.lastPostAt);
    const hoursSince = (now.getTime() - lastPost.getTime()) / (1000 * 60 * 60);
    if (hoursSince < 12) {
      return { generated: 0, message: "Too soon since last post" };
    }
  }

  const citationStyle = (config.citationStyle as "apa7" | "mla") || "apa7";
  let generated = 0;

  for (let i = 0; i < postsToGenerate; i++) {
    try {
      const post = await generateBlogPost(undefined, citationStyle);

      const isDup = await storage.checkDuplicateSlug(post.slug);
      const finalSlug = isDup ? `${post.slug}-${Date.now()}` : post.slug;

      await storage.createContentItem({
        title: post.title,
        slug: finalSlug,
        type: "blog",
        category: "nursing-education",
        tier: "free",
        status: "published",
        tags: post.tags,
        summary: post.summary,
        content: post.content,
        seoTitle: post.seoTitle,
        seoDescription: post.seoDescription,
        seoKeywords: post.seoKeywords,
        primaryKeyword: post.primaryKeyword,
        publishedAt: now,
        autoPublish: true,
        authorName: "Erika Godin, RN",
      });

      generated++;
    } catch (error) {
      console.error("Blog generation error:", error);
    }
  }

  await storage.upsertBlogConfig({
    dayCount: dayCount + 1,
    totalPostsGenerated: totalPosts + generated,
    lastPostAt: now,
  });

  return { generated, message: `Generated ${generated} posts (day ${dayCount + 1})` };
}
