import { rnMusculoskeletalIntegumentaryBankBatch1Questions } from "../../client/src/data/exam-questions/rn-musculoskeletal-integumentary-bank-batch1";
import { rnMusculoskeletalIntegumentaryBankBatch2Questions } from "../../client/src/data/exam-questions/rn-musculoskeletal-integumentary-bank-batch2";
import { rnMusculoskeletalIntegumentaryBankBatch3Questions } from "../../client/src/data/exam-questions/rn-musculoskeletal-integumentary-bank-batch3";
import { rnMusculoskeletalIntegumentaryRegionalBankBatch1Questions } from "../../client/src/data/exam-questions/rn-musculoskeletal-integumentary-regional-bank-batch1";
import type { ExamQuestion } from "../../client/src/data/exam-questions/types";

const shared:ExamQuestion[]=[...rnMusculoskeletalIntegumentaryBankBatch1Questions,...rnMusculoskeletalIntegumentaryBankBatch2Questions,...rnMusculoskeletalIntegumentaryBankBatch3Questions];
const all:ExamQuestion[]=[...shared,...rnMusculoskeletalIntegumentaryRegionalBankBatch1Questions];
function fail(m:string):never{throw new Error(m)}
function correct(q:ExamQuestion){return q.t==="sata"&&q.ca?q.ca:[q.a]}
if(rnMusculoskeletalIntegumentaryBankBatch1Questions.length!==50)fail(`RN_MSK_SKIN_BATCH1_COUNT:${rnMusculoskeletalIntegumentaryBankBatch1Questions.length}`);
if(rnMusculoskeletalIntegumentaryBankBatch2Questions.length!==50)fail(`RN_MSK_SKIN_BATCH2_COUNT:${rnMusculoskeletalIntegumentaryBankBatch2Questions.length}`);
if(rnMusculoskeletalIntegumentaryBankBatch3Questions.length!==50)fail(`RN_MSK_SKIN_BATCH3_COUNT:${rnMusculoskeletalIntegumentaryBankBatch3Questions.length}`);
if(shared.length!==150)fail(`RN_MSK_SKIN_SHARED_COUNT:${shared.length}`);if(all.length!==170)fail(`RN_MSK_SKIN_TOTAL_COUNT:${all.length}`);
const can=rnMusculoskeletalIntegumentaryRegionalBankBatch1Questions.filter(q=>q.regionScope==="CAN"),us=rnMusculoskeletalIntegumentaryRegionalBankBatch1Questions.filter(q=>q.regionScope==="US");if(can.length!==10)fail(`RN_MSK_SKIN_CAN_COUNT:${can.length}`);if(us.length!==10)fail(`RN_MSK_SKIN_US_COUNT:${us.length}`);
const seen=new Set<string>();for(const [i,q] of all.entries()){const stem=q.q.trim().toLowerCase();if(q.q.trim().length<25)fail(`RN_MSK_SKIN_THIN_STEM:${i}`);if(seen.has(stem))fail(`RN_MSK_SKIN_DUPLICATE_STEM:${q.q}`);seen.add(stem);if(!Array.isArray(q.o)||q.o.length<4)fail(`RN_MSK_SKIN_OPTIONS_INVALID:${i}`);const c=correct(q);if(!c.length||c.some(x=>!Number.isInteger(x)||x<0||x>=q.o.length))fail(`RN_MSK_SKIN_ANSWER_INVALID:${i}`);if(new Set(c).size!==c.length)fail(`RN_MSK_SKIN_ANSWER_DUPLICATE:${i}`);if(!q.r||q.r.trim().length<40)fail(`RN_MSK_SKIN_RATIONALE_THIN:${i}`);const wrong=q.o.length-c.length;if(!Array.isArray(q.dr)||q.dr.length!==wrong)fail(`RN_MSK_SKIN_DISTRACTOR_INVALID:${i}:${q.dr?.length??0}/${wrong}`);if(q.dr.some(x=>x.trim().length<20))fail(`RN_MSK_SKIN_DISTRACTOR_THIN:${i}`);if(q.t==="sata"&&(!q.ca||q.ca.length<2))fail(`RN_MSK_SKIN_SATA_INVALID:${i}`)}
for(const q of rnMusculoskeletalIntegumentaryRegionalBankBatch1Questions){if(q.regionScope==="CAN"&&q.countryCode!=="CA")fail(`RN_MSK_SKIN_CAN_COUNTRY:${q.q}`);if(q.regionScope==="US"&&q.countryCode!=="US")fail(`RN_MSK_SKIN_US_COUNTRY:${q.q}`);if(!q.topic||!q.cognitiveLevel||!q.difficulty)fail(`RN_MSK_SKIN_REGIONAL_METADATA:${q.q}`)}
console.log({status:"PASS",shared:shared.length,regional:20,total:all.length,canada:can.length,unitedStates:us.length,distractorRationales:all.filter(q=>Array.isArray(q.dr)).length});