import crypto from "crypto";
import { pool } from "../storage";
import { rnLeadershipBankBatch1Questions } from "../../client/src/data/exam-questions/rn-leadership-bank-batch1";
import { rnLeadershipBankBatch2Questions } from "../../client/src/data/exam-questions/rn-leadership-bank-batch2";
import { rnLeadershipBankBatch3Questions } from "../../client/src/data/exam-questions/rn-leadership-bank-batch3";
import { rnLeadershipRegionalBankBatch1Questions } from "../../client/src/data/exam-questions/rn-leadership-regional-bank-batch1";
import type { ExamQuestion } from "../../client/src/data/exam-questions/types";
const shared:ExamQuestion[]=[...rnLeadershipBankBatch1Questions,...rnLeadershipBankBatch2Questions,...rnLeadershipBankBatch3Questions];
const hash=(s:string)=>crypto.createHash("sha256").update(s.trim().toLowerCase()).digest("hex").substring(0,32);const answers=(q:ExamQuestion)=>q.t==="sata"&&q.ca?q.ca:[q.a];
function topicFor(stem:string){const s=stem.toLowerCase();if(/delegate|assignment|assign|supervis|float|competence/.test(s))return"Delegation, Assignment & Supervision";if(/assess first|priority|first action|deteriorat|unstable|acuity/.test(s))return"Prioritization & Acuity";if(/staff|workload|fatigue|overtime|resource/.test(s))return"Staffing & Resource Allocation";if(/quality|root-cause|root cause|near miss|run chart|process measure|outcome measure|just culture/.test(s))return"Quality Improvement & Safety Culture";if(/conflict|incivility|moral distress|ethic|refus|impaired colleague|psychological safety/.test(s))return"Ethics, Conflict & Professional Practice";if(/discharge|transition|follow-up|case management|care coordination|transportation|caregiver|teach-back/.test(s))return"Care Coordination & Transitions";if(/phishing|ehr|downtime|cyber|privacy|algorithm|ai|barcode|dashboard|informatics/.test(s))return"Informatics, Privacy & Data Safety";if(/handoff|communication|chain of command|sbar|closed-loop|interpreter/.test(s))return"Team Communication & Escalation";return"Leadership & Management";}
async function insert(q:ExamQuestion,region:"BOTH"|"CAN"|"US",country:string|null,topic:string,difficulty=3,cognitive="application",licensing="NCSBN"){const h=hash(q.q);const ex=await pool.query(`SELECT id FROM exam_questions WHERE stem_hash=$1 OR lower(trim(stem))=lower(trim($2)) LIMIT 1`,[h,q.q]);if(ex.rows.length)return"skipped" as const;const sata=q.t==="sata";await pool.query(`INSERT INTO exam_questions (id,tier,exam,question_type,status,stem,options,correct_answer,rationale,distractor_rationales,difficulty,body_system,topic,country_code,licensing_body,language_code,cognitive_level,question_format,lab_unit_variant,medication_naming_variant,region_scope,is_mock_exam_eligible,is_adaptive_eligible,career_type,domain,tags,stem_hash,created_at,updated_at) VALUES (gen_random_uuid(),'rn','NCLEX-RN',$1,'published',$2,$3,$4,$5,$6,$7,'Leadership & Management',$8,$9,$10,'en',$11,$12,'mixed','generic_international',$13,true,true,'nursing','Management of Care',$14,$15,NOW(),NOW())`,[sata?"sata":"multiple_choice",q.q,JSON.stringify(q.o),JSON.stringify(answers(q)),q.r,JSON.stringify(q.dr??[]),difficulty,topic,country,licensing,cognitive,sata?"SATA":"MCQ",region,["rn","nclex-rn","leadership","management-of-care",region.toLowerCase(),topic.toLowerCase().replace(/[^a-z0-9]+/g,"-")],h]);return"inserted" as const;}
async function main(){await pool.query(`ALTER TABLE exam_questions ADD COLUMN IF NOT EXISTS stem_hash TEXT`);await pool.query(`ALTER TABLE exam_questions ADD COLUMN IF NOT EXISTS distractor_rationales JSONB DEFAULT '[]'::jsonb`);if(rnLeadershipBankBatch1Questions.length!==50)throw new Error(`RN_LEAD_BATCH1:${rnLeadershipBankBatch1Questions.length}`);if(rnLeadershipBankBatch2Questions.length!==50)throw new Error(`RN_LEAD_BATCH2:${rnLeadershipBankBatch2Questions.length}`);if(rnLeadershipBankBatch3Questions.length!==50)throw new Error(`RN_LEAD_BATCH3:${rnLeadershipBankBatch3Questions.length}`);if(shared.length!==150)throw new Error(`RN_LEAD_SHARED:${shared.length}`);if(rnLeadershipRegionalBankBatch1Questions.length!==20)throw new Error(`RN_LEAD_REGIONAL:${rnLeadershipRegionalBankBatch1Questions.length}`);let inserted=0,skipped=0;for(const q of shared){(await insert(q,"BOTH",null,topicFor(q.q)))==="inserted"?inserted++:skipped++;}for(const q of rnLeadershipRegionalBankBatch1Questions){(await insert(q,q.regionScope,q.countryCode,q.topic,q.difficulty,q.cognitiveLevel,q.licensingBody))==="inserted"?inserted++:skipped++;}console.log({authored:170,inserted,skipped});}
main().then(()=>process.exit(0)).catch(e=>{console.error(e);process.exit(1);});