import crypto from "crypto";
import { pool } from "../storage";
import { rnMentalHealthBankBatch1Questions } from "../../client/src/data/exam-questions/rn-mental-health-bank-batch1";
import { rnMentalHealthBankBatch2Questions } from "../../client/src/data/exam-questions/rn-mental-health-bank-batch2";
import { rnMentalHealthBankBatch3Questions } from "../../client/src/data/exam-questions/rn-mental-health-bank-batch3";
import { rnMentalHealthRegionalBankBatch1Questions } from "../../client/src/data/exam-questions/rn-mental-health-regional-bank-batch1";
import type { ExamQuestion } from "../../client/src/data/exam-questions/types";

const shared: ExamQuestion[]=[...rnMentalHealthBankBatch1Questions,...rnMentalHealthBankBatch2Questions,...rnMentalHealthBankBatch3Questions];
const hash=(s:string)=>crypto.createHash("sha256").update(s.trim().toLowerCase()).digest("hex").substring(0,32);
const answers=(q:ExamQuestion)=>q.t==="sata"&&q.ca?q.ca:[q.a];
function topicFor(stem:string){const s=stem.toLowerCase();if(/suicid|self-harm|self-injur/.test(s))return"Suicide & Self-Harm";if(/schizoph|psychosis|hallucin|delusion|paranoi/.test(s))return"Psychosis & Schizophrenia";if(/mania|bipolar|lithium|valproate|lamotrigine|carbamazepine/.test(s))return"Bipolar & Mood Stabilizers";if(/depress|ssri|maoi|ect|catatonia|serotonin/.test(s))return"Depression & Antidepressant Safety";if(/antipsych|clozapine|dystonia|akathisia|tardive|neuroleptic/.test(s))return"Antipsychotic Safety";if(/panic|anxiety|ocd|phobia|buspirone|benzodiazepine/.test(s))return"Anxiety & OCD";if(/ptsd|trauma|dissoci|sexual-assault|acute stress/.test(s))return"Trauma & Dissociation";if(/anorexia|bulimia|binge-eating|refeeding/.test(s))return"Eating Disorders";if(/alcohol|opioid|naloxone|buprenorphine|methadone|naltrexone|cocaine|stimulant|substance/.test(s))return"Substance Use & Withdrawal";if(/borderline|antisocial|narciss|avoidant|dependent personality|personality/.test(s))return"Personality Disorders";if(/delirium|dementia/.test(s))return"Delirium & Dementia";if(/adhd|autism|adolescent|child/.test(s))return"Child & Adolescent Mental Health";if(/restraint|seclusion|de-escalat|aggress|violence/.test(s))return"De-escalation & Restrictive Interventions";if(/insomnia|sleep/.test(s))return"Sleep & Behavioral Health";return"Therapeutic Communication & Psychiatric Nursing";}
async function insert(q:ExamQuestion,region:"BOTH"|"CAN"|"US",country:string|null,topic:string,difficulty=3,cognitive="application"){const h=hash(q.q);const ex=await pool.query(`SELECT id FROM exam_questions WHERE stem_hash=$1 OR lower(trim(stem))=lower(trim($2)) LIMIT 1`,[h,q.q]);if(ex.rows.length)return"skipped" as const;const sata=q.t==="sata";await pool.query(`INSERT INTO exam_questions (id,tier,exam,question_type,status,stem,options,correct_answer,rationale,distractor_rationales,difficulty,body_system,topic,country_code,licensing_body,language_code,cognitive_level,question_format,lab_unit_variant,medication_naming_variant,region_scope,is_mock_exam_eligible,is_adaptive_eligible,career_type,domain,tags,stem_hash,created_at,updated_at) VALUES (gen_random_uuid(),'rn','NCLEX-RN',$1,'published',$2,$3,$4,$5,$6,$7,'Mental Health',$8,$9,'NCSBN','en',$10,$11,$12,$13,$14,true,true,'nursing','Psychosocial Integrity',$15,$16,NOW(),NOW())`,[sata?"sata":"multiple_choice",q.q,JSON.stringify(q.o),JSON.stringify(answers(q)),q.r,JSON.stringify(q.dr??[]),difficulty,topic,country,cognitive,sata?"SATA":"MCQ",region==="CAN"?"SI":region==="US"?"US_conventional":"mixed",region==="CAN"?"Canadian_generic":region==="US"?"US_generic":"generic_international",region,["rn","nclex-rn","mental-health",region.toLowerCase(),topic.toLowerCase().replace(/[^a-z0-9]+/g,"-")],h]);return"inserted" as const;}
async function main(){await pool.query(`ALTER TABLE exam_questions ADD COLUMN IF NOT EXISTS stem_hash TEXT`);await pool.query(`ALTER TABLE exam_questions ADD COLUMN IF NOT EXISTS distractor_rationales JSONB DEFAULT '[]'::jsonb`);if(rnMentalHealthBankBatch1Questions.length!==50)throw new Error(`RN_MH_BATCH1:${rnMentalHealthBankBatch1Questions.length}`);if(rnMentalHealthBankBatch2Questions.length!==50)throw new Error(`RN_MH_BATCH2:${rnMentalHealthBankBatch2Questions.length}`);if(rnMentalHealthBankBatch3Questions.length!==50)throw new Error(`RN_MH_BATCH3:${rnMentalHealthBankBatch3Questions.length}`);if(shared.length!==150)throw new Error(`RN_MH_SHARED:${shared.length}`);if(rnMentalHealthRegionalBankBatch1Questions.length!==20)throw new Error(`RN_MH_REGIONAL:${rnMentalHealthRegionalBankBatch1Questions.length}`);let inserted=0,skipped=0;for(const q of shared){(await insert(q,"BOTH",null,topicFor(q.q)))==="inserted"?inserted++:skipped++;}for(const q of rnMentalHealthRegionalBankBatch1Questions){(await insert(q,q.regionScope,q.countryCode,q.topic,q.difficulty,q.cognitiveLevel))==="inserted"?inserted++:skipped++;}console.log({authored:170,inserted,skipped});}
main().then(()=>process.exit(0)).catch(e=>{console.error(e);process.exit(1);});