import crypto from "crypto";
import { pool } from "../storage";
import { rnMusculoskeletalIntegumentaryBankBatch1Questions } from "../../client/src/data/exam-questions/rn-musculoskeletal-integumentary-bank-batch1";
import { rnMusculoskeletalIntegumentaryBankBatch2Questions } from "../../client/src/data/exam-questions/rn-musculoskeletal-integumentary-bank-batch2";
import { rnMusculoskeletalIntegumentaryBankBatch3Questions } from "../../client/src/data/exam-questions/rn-musculoskeletal-integumentary-bank-batch3";
import { rnMusculoskeletalIntegumentaryRegionalBankBatch1Questions } from "../../client/src/data/exam-questions/rn-musculoskeletal-integumentary-regional-bank-batch1";
import type { ExamQuestion } from "../../client/src/data/exam-questions/types";

const shared: ExamQuestion[]=[...rnMusculoskeletalIntegumentaryBankBatch1Questions,...rnMusculoskeletalIntegumentaryBankBatch2Questions,...rnMusculoskeletalIntegumentaryBankBatch3Questions];
function hash(s:string){return crypto.createHash("sha256").update(s.trim().toLowerCase()).digest("hex").substring(0,32);}
function answers(q:ExamQuestion){return q.t==="sata"&&q.ca?q.ca:[q.a];}
function topicFor(stem:string){const s=stem.toLowerCase();if(/compartment|fracture|cast|traction|fixator|hip disloc|pelvic/.test(s))return"Fractures & Orthopedic Emergencies";if(/arthroplasty|joint replacement|prosthetic joint/.test(s))return"Joint Replacement";if(/amput|prosthesis|residual limb/.test(s))return"Amputation & Prosthetics";if(/osteomyel|septic arthritis|bone infection/.test(s))return"Bone & Joint Infection";if(/osteoarthritis|\boa\b/.test(s))return"Osteoarthritis";if(/rheumatoid|methotrexate|tnf inhibitor/.test(s))return"Rheumatoid Arthritis";if(/gout|pseudogout|urate|cppd/.test(s))return"Crystal Arthritis";if(/osteopor|fragility|bisphosphonate|denosumab|vitamin d/.test(s))return"Osteoporosis & Fragility Fractures";if(/back pain|cauda|spinal|scoliosis|bone tumor/.test(s))return"Spine & Bone Disorders";if(/pressure injury|sacrum|heel eschar|deep tissue/.test(s))return"Pressure Injuries";if(/venous|arterial ulcer|diabetic foot|chronic wound|wound exudate/.test(s))return"Chronic Wounds & Ulcers";if(/cellulitis|necrotizing|lymphangitis/.test(s))return"Skin & Soft-Tissue Infection";if(/burn|inhalation injury|carbon monoxide|escharotomy/.test(s))return"Burns & Inhalation Injury";if(/skin tear|dehiscence|evisceration|negative-pressure|npwt|surgical wound/.test(s))return"Skin Tears & Surgical Wounds";return"Musculoskeletal & Integumentary Clinical Judgment";}

async function insert(q:ExamQuestion,region:"BOTH"|"CAN"|"US",country:string|null,topic:string,difficulty=3,cognitive="application"){
 const stemHash=hash(q.q);const existing=await pool.query(`SELECT id FROM exam_questions WHERE stem_hash=$1 OR lower(trim(stem))=lower(trim($2)) LIMIT 1`,[stemHash,q.q]);if(existing.rows.length)return"skipped" as const;
 const sata=q.t==="sata";
 await pool.query(`INSERT INTO exam_questions (id,tier,exam,question_type,status,stem,options,correct_answer,rationale,distractor_rationales,difficulty,body_system,topic,country_code,licensing_body,language_code,cognitive_level,question_format,lab_unit_variant,medication_naming_variant,region_scope,is_mock_exam_eligible,is_adaptive_eligible,career_type,domain,tags,stem_hash,created_at,updated_at) VALUES (gen_random_uuid(),'rn','NCLEX-RN',$1,'published',$2,$3,$4,$5,$6,$7,'Musculoskeletal & Integumentary',$8,$9,'NCSBN','en',$10,$11,$12,$13,$14,true,true,'nursing','Physiological Integrity',$15,$16,NOW(),NOW())`,[sata?"sata":"multiple_choice",q.q,JSON.stringify(q.o),JSON.stringify(answers(q)),q.r,JSON.stringify(q.dr??[]),difficulty,topic,country,cognitive,sata?"SATA":"MCQ",region==="CAN"?"SI":region==="US"?"US_conventional":"mixed",region==="CAN"?"Canadian_generic":region==="US"?"US_generic":"generic_international",region,["rn","nclex-rn","musculoskeletal","integumentary",region.toLowerCase(),topic.toLowerCase().replace(/[^a-z0-9]+/g,"-")],stemHash]);return"inserted" as const;
}

async function main(){
 await pool.query(`ALTER TABLE exam_questions ADD COLUMN IF NOT EXISTS stem_hash TEXT`);await pool.query(`ALTER TABLE exam_questions ADD COLUMN IF NOT EXISTS distractor_rationales JSONB DEFAULT '[]'::jsonb`);await pool.query(`CREATE INDEX IF NOT EXISTS idx_exam_questions_stem_hash ON exam_questions(stem_hash)`);
 if(rnMusculoskeletalIntegumentaryBankBatch1Questions.length!==50)throw new Error(`RN_MSK_SKIN_BATCH1_COUNT_INVALID:${rnMusculoskeletalIntegumentaryBankBatch1Questions.length}`);if(rnMusculoskeletalIntegumentaryBankBatch2Questions.length!==50)throw new Error(`RN_MSK_SKIN_BATCH2_COUNT_INVALID:${rnMusculoskeletalIntegumentaryBankBatch2Questions.length}`);if(rnMusculoskeletalIntegumentaryBankBatch3Questions.length!==50)throw new Error(`RN_MSK_SKIN_BATCH3_COUNT_INVALID:${rnMusculoskeletalIntegumentaryBankBatch3Questions.length}`);if(shared.length!==150)throw new Error(`RN_MSK_SKIN_SHARED_COUNT_INVALID:${shared.length}`);if(rnMusculoskeletalIntegumentaryRegionalBankBatch1Questions.length!==20)throw new Error(`RN_MSK_SKIN_REGIONAL_COUNT_INVALID:${rnMusculoskeletalIntegumentaryRegionalBankBatch1Questions.length}`);
 let inserted=0,skipped=0;for(const q of shared){(await insert(q,"BOTH",null,topicFor(q.q)))==="inserted"?inserted++:skipped++;}for(const q of rnMusculoskeletalIntegumentaryRegionalBankBatch1Questions){(await insert(q,q.regionScope,q.countryCode,q.topic,q.difficulty,q.cognitiveLevel))==="inserted"?inserted++:skipped++;}
 console.log({authored:170,inserted,skipped});
}
main().then(()=>process.exit(0)).catch(e=>{console.error(e);process.exit(1);});