import crypto from "crypto";
import { pool } from "../storage";
import { rnCriticalCareEmergencyBankBatch1Questions } from "../../client/src/data/exam-questions/rn-critical-care-emergency-bank-batch1";
import { rnCriticalCareEmergencyBankBatch2Questions } from "../../client/src/data/exam-questions/rn-critical-care-emergency-bank-batch2";
import { rnCriticalCareEmergencyBankBatch3Questions } from "../../client/src/data/exam-questions/rn-critical-care-emergency-bank-batch3";
import { rnCriticalCareEmergencyRegionalBankBatch1Questions } from "../../client/src/data/exam-questions/rn-critical-care-emergency-regional-bank-batch1";
import type { ExamQuestion } from "../../client/src/data/exam-questions/types";
const shared:ExamQuestion[]=[...rnCriticalCareEmergencyBankBatch1Questions,...rnCriticalCareEmergencyBankBatch2Questions,...rnCriticalCareEmergencyBankBatch3Questions];
const hash=(s:string)=>crypto.createHash("sha256").update(s.trim().toLowerCase()).digest("hex").substring(0,32);const answers=(q:ExamQuestion)=>q.t==="sata"&&q.ca?q.ca:[q.a];
function topicFor(stem:string){const s=stem.toLowerCase();if(/sepsis|septic|lactate|source control|norepinephrine|vasopressin/.test(s))return"Sepsis & Septic Shock";if(/shock|perfusion|fluid responsive|passive leg|arterial catheter|map|vasopressor/.test(s))return"Shock & Hemodynamic Support";if(/cardiac arrest|vf|pulseless|rosc|defibr|cardioversion|bradycardia|cpr|etco2/.test(s))return"Resuscitation & Post-Cardiac Arrest";if(/ventilat|intubat|ards|prone|airway|suction|capnograph/.test(s))return"Airway, Ventilation & ARDS";if(/trauma|hemorrhage|fracture|burn|crush|flail|pelvic|damage-control|massive/.test(s))return"Trauma & Massive Hemorrhage";if(/overdose|toxicity|poison|acetaminophen|salicylate|opioid|digoxin|methanol|ethylene|cyanide|organophosphate|serotonin|neuroleptic|malignant hyperthermia/.test(s))return"Toxicology & Antidotes";if(/hyperkal|hyponat|dka|adrenal|thyroid storm|myxedema/.test(s))return"Metabolic & Endocrine Emergencies";if(/seizure|status epileptic|herniation|evd|subarachnoid|intracerebral|stroke/.test(s))return"Neurocritical Emergencies";if(/crrt|hemodialysis|dialysis|arterial line|central line|chest tube|feeding-tube/.test(s))return"Critical-Care Devices & Procedures";if(/delirium|sedation|mobility|vte prophylaxis|stress-ulcer|post-intensive/.test(s))return"ICU Support & Recovery";return"Critical Care & Emergency";}
async function insert(q:ExamQuestion,region:"BOTH"|"CAN"|"US",country:string|null,topic:string,difficulty=3,cognitive="application",licensing="NCSBN"){const h=hash(q.q);const ex=await pool.query(`SELECT id FROM exam_questions WHERE stem_hash=$1 OR lower(trim(stem))=lower(trim($2)) LIMIT 1`,[h,q.q]);if(ex.rows.length)return"skipped" as const;const sata=q.t==="sata";await pool.query(`INSERT INTO exam_questions (id,tier,exam,question_type,status,stem,options,correct_answer,rationale,distractor_rationales,difficulty,body_system,topic,country_code,licensing_body,language_code,cognitive_level,question_format,lab_unit_variant,medication_naming_variant,region_scope,is_mock_exam_eligible,is_adaptive_eligible,career_type,domain,tags,stem_hash,created_at,updated_at) VALUES (gen_random_uuid(),'rn','NCLEX-RN',$1,'published',$2,$3,$4,$5,$6,$7,'Critical Care & Emergency',$8,$9,$10,'en',$11,$12,'mixed','generic_international',$13,true,true,'nursing','Physiological Integrity',$14,$15,NOW(),NOW())`,[sata?"sata":"multiple_choice",q.q,JSON.stringify(q.o),JSON.stringify(answers(q)),q.r,JSON.stringify(q.dr??[]),difficulty,topic,country,licensing,cognitive,sata?"SATA":"MCQ",region,["rn","nclex-rn","critical-care","emergency",region.toLowerCase(),topic.toLowerCase().replace(/[^a-z0-9]+/g,"-")],h]);return"inserted" as const;}
async function main(){await pool.query(`ALTER TABLE exam_questions ADD COLUMN IF NOT EXISTS stem_hash TEXT`);await pool.query(`ALTER TABLE exam_questions ADD COLUMN IF NOT EXISTS distractor_rationales JSONB DEFAULT '[]'::jsonb`);if(rnCriticalCareEmergencyBankBatch1Questions.length!==50)throw new Error(`RN_CRIT_BATCH1:${rnCriticalCareEmergencyBankBatch1Questions.length}`);if(rnCriticalCareEmergencyBankBatch2Questions.length!==50)throw new Error(`RN_CRIT_BATCH2:${rnCriticalCareEmergencyBankBatch2Questions.length}`);if(rnCriticalCareEmergencyBankBatch3Questions.length!==50)throw new Error(`RN_CRIT_BATCH3:${rnCriticalCareEmergencyBankBatch3Questions.length}`);if(shared.length!==150)throw new Error(`RN_CRIT_SHARED:${shared.length}`);if(rnCriticalCareEmergencyRegionalBankBatch1Questions.length!==20)throw new Error(`RN_CRIT_REGIONAL:${rnCriticalCareEmergencyRegionalBankBatch1Questions.length}`);let inserted=0,skipped=0;for(const q of shared){(await insert(q,"BOTH",null,topicFor(q.q)))==="inserted"?inserted++:skipped++;}for(const q of rnCriticalCareEmergencyRegionalBankBatch1Questions){(await insert(q,q.regionScope,q.countryCode,q.topic,q.difficulty,q.cognitiveLevel,q.licensingBody))==="inserted"?inserted++:skipped++;}console.log({authored:170,inserted,skipped});}
main().then(()=>process.exit(0)).catch(e=>{console.error(e);process.exit(1);});