import crypto from "crypto";
import { pool } from "../storage";
import { rnRespiratoryRound2Batch1Questions } from "../../client/src/data/exam-questions/rn-respiratory-round2-batch1";
import { rnRespiratoryRound2Batch2Questions } from "../../client/src/data/exam-questions/rn-respiratory-round2-batch2";
import { rnRespiratoryRound2Batch3Questions } from "../../client/src/data/exam-questions/rn-respiratory-round2-batch3";
import { rnRespiratoryRound2Batch4Questions } from "../../client/src/data/exam-questions/rn-respiratory-round2-batch4";
import { rnRespiratoryRound2Batch5Questions } from "../../client/src/data/exam-questions/rn-respiratory-round2-batch5";
import type { ExamQuestion } from "../../client/src/data/exam-questions/types";
const questions:ExamQuestion[]=[...rnRespiratoryRound2Batch1Questions,...rnRespiratoryRound2Batch2Questions,...rnRespiratoryRound2Batch3Questions,...rnRespiratoryRound2Batch4Questions,...rnRespiratoryRound2Batch5Questions];
const hash=(s:string)=>crypto.createHash("sha256").update(s.trim().toLowerCase()).digest("hex").substring(0,32);
function topicFor(s0:string){const s=s0.toLowerCase();if(/spirom|dlco|abg|capnograph|thoracentes|bronchoscop|venturi|nonrebreather|high-flow|oxygen device|fremitus|percussion/.test(s))return"Respiratory Assessment & Diagnostics";if(/asthma|albuterol|salbutamol|corticosteroid|montelukast|spacer/.test(s))return"Asthma & Airway Pharmacology";if(/copd|emphysema|alpha-1|roflumilast/.test(s))return"COPD";if(/bronchiect/.test(s))return"Bronchiectasis";if(/cystic fibrosis|cftr|pancreatic enzyme/.test(s))return"Cystic Fibrosis";if(/fibrosis|interstitial|nintedanib|pirfenidone|hypersensitivity pneumonitis|amiodarone/.test(s))return"Interstitial & Occupational Lung Disease";if(/pulmonary hypertension|prostacyclin|sildenafil|right-heart/.test(s))return"Pulmonary Hypertension";if(/sleep apnea|cpap|obesity hypoventilation/.test(s))return"Sleep-Disordered Breathing";if(/pneumonia|aspirat|empyema|influenza|rsv|fung|histoplas|coccidio|blastomy|asperg|pneumocystis/.test(s))return"Respiratory Infection";if(/tuberculosis|isoniazid|rifamp|ethambutol/.test(s))return"Tuberculosis";if(/pulmonary embol|thrombol|vte/.test(s))return"Pulmonary Embolism & VTE";if(/pneumothorax|chest tube|water-seal|subcutaneous emphysema|hemothorax|chylothorax|pleural/.test(s))return"Pleural Disease & Chest Tubes";if(/ards|peep|plateau|prone/.test(s))return"ARDS";if(/ventilator|intubat|tracheost|suction|weaning|spontaneous breathing/.test(s))return"Mechanical Ventilation & Artificial Airways";if(/lobectomy|pneumonectomy|bronchopleural|lung-transplant|thoracic surgery/.test(s))return"Thoracic Surgery & Transplant";if(/croup|bronchiolitis|epiglottitis|foreign body|child|infant|pediatric/.test(s))return"Pediatric Respiratory";if(/myasthenia|guillain|als|spinal cord/.test(s))return"Neuromuscular Respiratory Failure";if(/lung cancer|pancoast|superior vena cava|radiation pneumonitis/.test(s))return"Lung Cancer & Treatment Complications";return"Respiratory Clinical Judgment";}
async function main(){await pool.query(`ALTER TABLE exam_questions ADD COLUMN IF NOT EXISTS stem_hash TEXT`);await pool.query(`ALTER TABLE exam_questions ADD COLUMN IF NOT EXISTS distractor_rationales JSONB DEFAULT '[]'::jsonb`);if(questions.length<200)throw new Error(`RN_RESP_ROUND2_MINIMUM_NOT_MET:${questions.length}/200`);let inserted=0,skipped=0;for(const q of questions){const h=hash(q.q);const ex=await pool.query(`SELECT id FROM exam_questions WHERE stem_hash=$1 OR lower(trim(stem))=lower(trim($2)) LIMIT 1`,[h,q.q]);if(ex.rows.length){skipped++;continue;}const sata=q.t==="sata"&&Array.isArray(q.ca);const ans=sata?q.ca:[q.a];const topic=topicFor(q.q);await pool.query(`INSERT INTO exam_questions (id,tier,exam,question_type,status,stem,options,correct_answer,rationale,distractor_rationales,difficulty,body_system,topic,country_code,licensing_body,language_code,cognitive_level,question_format,lab_unit_variant,medication_naming_variant,region_scope,is_mock_exam_eligible,is_adaptive_eligible,career_type,domain,tags,stem_hash,created_at,updated_at) VALUES (gen_random_uuid(),'rn','NCLEX-RN',$1,'published',$2,$3,$4,$5,$6,3,'Respiratory',$7,NULL,'NCSBN','en','application',$8,'mixed','generic_international','BOTH',true,true,'nursing','Physiological Integrity',$9,$10,NOW(),NOW())`,[sata?"sata":"multiple_choice",q.q,JSON.stringify(q.o),JSON.stringify(ans),q.r,JSON.stringify(q.dr??[]),topic,sata?"SATA":"MCQ",["rn","nclex-rn","respiratory","round2","shared-ca-us",topic.toLowerCase().replace(/[^a-z0-9]+/g,"-")],h]);inserted++;}console.log({authored:questions.length,inserted,skipped,minimumRequired:200});}
main().then(()=>process.exit(0)).catch(e=>{console.error(e);process.exit(1);});