import crypto from "crypto";
import { pool } from "../storage";
import { rnCommunityPublicHealthBankBatch1Questions } from "../../client/src/data/exam-questions/rn-community-public-health-bank-batch1";
import { rnCommunityPublicHealthBankBatch2Questions } from "../../client/src/data/exam-questions/rn-community-public-health-bank-batch2";
import { rnCommunityPublicHealthBankBatch3Questions } from "../../client/src/data/exam-questions/rn-community-public-health-bank-batch3";
import { rnCommunityPublicHealthRegionalBankBatch1Questions } from "../../client/src/data/exam-questions/rn-community-public-health-regional-bank-batch1";
import type { ExamQuestion } from "../../client/src/data/exam-questions/types";
const shared:ExamQuestion[]=[...rnCommunityPublicHealthBankBatch1Questions,...rnCommunityPublicHealthBankBatch2Questions,...rnCommunityPublicHealthBankBatch3Questions];
const hash=(s:string)=>crypto.createHash("sha256").update(s.trim().toLowerCase()).digest("hex").substring(0,32);const answers=(q:ExamQuestion)=>q.t==="sata"&&q.ca?q.ca:[q.a];
function topicFor(stem:string){const s=stem.toLowerCase();if(/incidence|prevalence|attack rate|case definition|surveillance|sensitivity|specificity|predictive|epidemic|outbreak curve|bias/.test(s))return"Epidemiology & Surveillance";if(/primary prevention|secondary prevention|tertiary prevention|screening|overdiagnosis|lead-time|length-time/.test(s))return"Prevention & Screening";if(/community assessment|asset|equity|inequit|social determinant|food insecurity|transportation|housing|indigenous|rural/.test(s))return"Community Assessment, Equity & SDOH";if(/home|caregiver|school|student|workplace|worker|occupational/.test(s))return"Home, School & Occupational Health";if(/vaccine|immuniz/.test(s))return"Immunization & Vaccine Programs";if(/harm reduction|naloxone|syringe|opioid|homeless|shelter/.test(s))return"Harm Reduction & Vulnerable Populations";if(/disaster|emergency|shelter|evacuat|wildfire|flood|prepared|mitigation|recovery|mass gathering/.test(s))return"Emergency Preparedness & Disaster Health";if(/environment|lead|air quality|heat|water|mold|generator|pedestrian/.test(s))return"Environmental Health & Injury Prevention";if(/program|evaluation|run|outcome|process|sustain|participatory|policy|advoca/.test(s))return"Program Planning, Evaluation & Policy";if(/contact tracing|reportable|communicable|partner notification|hiv|tuberculosis|hepatitis/.test(s))return"Communicable Disease Control";return"Community & Public Health";}
async function insert(q:ExamQuestion,region:"BOTH"|"CAN"|"US",country:string|null,topic:string,difficulty=3,cognitive="application",licensing="NCSBN"){const h=hash(q.q);const ex=await pool.query(`SELECT id FROM exam_questions WHERE stem_hash=$1 OR lower(trim(stem))=lower(trim($2)) LIMIT 1`,[h,q.q]);if(ex.rows.length)return"skipped" as const;const sata=q.t==="sata";await pool.query(`INSERT INTO exam_questions (id,tier,exam,question_type,status,stem,options,correct_answer,rationale,distractor_rationales,difficulty,body_system,topic,country_code,licensing_body,language_code,cognitive_level,question_format,lab_unit_variant,medication_naming_variant,region_scope,is_mock_exam_eligible,is_adaptive_eligible,career_type,domain,tags,stem_hash,created_at,updated_at) VALUES (gen_random_uuid(),'rn','NCLEX-RN',$1,'published',$2,$3,$4,$5,$6,$7,'Community & Public Health',$8,$9,$10,'en',$11,$12,'mixed','generic_international',$13,true,true,'nursing','Health Promotion and Maintenance',$14,$15,NOW(),NOW())`,[sata?"sata":"multiple_choice",q.q,JSON.stringify(q.o),JSON.stringify(answers(q)),q.r,JSON.stringify(q.dr??[]),difficulty,topic,country,licensing,cognitive,sata?"SATA":"MCQ",region,["rn","nclex-rn","community","public-health",region.toLowerCase(),topic.toLowerCase().replace(/[^a-z0-9]+/g,"-")],h]);return"inserted" as const;}
async function main(){await pool.query(`ALTER TABLE exam_questions ADD COLUMN IF NOT EXISTS stem_hash TEXT`);await pool.query(`ALTER TABLE exam_questions ADD COLUMN IF NOT EXISTS distractor_rationales JSONB DEFAULT '[]'::jsonb`);if(rnCommunityPublicHealthBankBatch1Questions.length!==51)throw new Error(`RN_COMM_BATCH1:${rnCommunityPublicHealthBankBatch1Questions.length}`);if(rnCommunityPublicHealthBankBatch2Questions.length!==49)throw new Error(`RN_COMM_BATCH2:${rnCommunityPublicHealthBankBatch2Questions.length}`);if(rnCommunityPublicHealthBankBatch3Questions.length!==53)throw new Error(`RN_COMM_BATCH3:${rnCommunityPublicHealthBankBatch3Questions.length}`);if(shared.length!==153)throw new Error(`RN_COMM_SHARED:${shared.length}`);if(rnCommunityPublicHealthRegionalBankBatch1Questions.length!==20)throw new Error(`RN_COMM_REGIONAL:${rnCommunityPublicHealthRegionalBankBatch1Questions.length}`);let inserted=0,skipped=0;for(const q of shared){(await insert(q,"BOTH",null,topicFor(q.q)))==="inserted"?inserted++:skipped++;}for(const q of rnCommunityPublicHealthRegionalBankBatch1Questions){(await insert(q,q.regionScope,q.countryCode,q.topic,q.difficulty,q.cognitiveLevel,q.licensingBody))==="inserted"?inserted++:skipped++;}console.log({authored:173,inserted,skipped});}
main().then(()=>process.exit(0)).catch(e=>{console.error(e);process.exit(1);});