import crypto from "crypto";
import { pool } from "../storage";
import { rnGastrointestinalRound3Batch1Questions } from "../../client/src/data/exam-questions/rn-gastrointestinal-round3-batch1";
import { rnGastrointestinalRound3Batch2Questions } from "../../client/src/data/exam-questions/rn-gastrointestinal-round3-batch2";
import { rnGastrointestinalRound3Batch3Questions } from "../../client/src/data/exam-questions/rn-gastrointestinal-round3-batch3";
import { rnGastrointestinalRound3Batch4Questions } from "../../client/src/data/exam-questions/rn-gastrointestinal-round3-batch4";
import type { ExamQuestion } from "../../client/src/data/exam-questions/types";
const all:ExamQuestion[]=[...rnGastrointestinalRound3Batch1Questions,...rnGastrointestinalRound3Batch2Questions,...rnGastrointestinalRound3Batch3Questions,...rnGastrointestinalRound3Batch4Questions];const hash=(s:string)=>crypto.createHash("sha256").update(s.trim().toLowerCase()).digest("hex").substring(0,32);const answers=(q:ExamQuestion)=>q.t==="sata"&&q.ca?q.ca:[q.a];
function topicFor(stem:string){const s=stem.toLowerCase();if(/hematem|melena|bleed|varice|cirrhos|ascites|hepatic encephal|sbp|hepatorenal|tips|portal/.test(s))return"GI Hemorrhage, Portal Hypertension & Decompensated Cirrhosis";if(/pancreat|cholecyst|cholang|ercp|obstruction|mesenteric|c\. difficile|ulcerative|crohn|ibd|megacolon/.test(s))return"Pancreatic, Biliary, Bowel & IBD Emergencies";if(/refeeding|enteral|parenteral|feeding tube|ileostomy|colostomy|short-bowel|celiac|dysphagia|esophag|gastrect|whipple|colonoscopy|endoscop/.test(s))return"Nutrition, Ostomy, Malabsorption & GI Procedures";if(/acute liver|hepatitis|autoimmune hepatitis|pbc|psc|hemochrom|wilson|steatotic|hcc|pancreatic cancer|cholangiocarc|esophageal cancer|colorectal cancer|capecitabine|oxaliplatin|irinotecan|5-fu/.test(s))return"Hepatology & GI Oncology";return"Gastrointestinal & Hepatic Clinical Judgment";}
async function insert(q:ExamQuestion){const h=hash(q.q);const ex=await pool.query(`SELECT id FROM exam_questions WHERE stem_hash=$1 OR lower(trim(stem))=lower(trim($2)) LIMIT 1`,[h,q.q]);if(ex.rows.length)return"skipped" as const;const sata=q.t==="sata";const topic=topicFor(q.q);await pool.query(`INSERT INTO exam_questions (id,tier,exam,question_type,status,stem,options,correct_answer,rationale,distractor_rationales,difficulty,body_system,topic,country_code,licensing_body,language_code,cognitive_level,question_format,lab_unit_variant,medication_naming_variant,region_scope,is_mock_exam_eligible,is_adaptive_eligible,career_type,domain,tags,stem_hash,created_at,updated_at) VALUES (gen_random_uuid(),'rn','NCLEX-RN',$1,'published',$2,$3,$4,$5,$6,3,'Gastrointestinal & Hepatic',$7,NULL,'NCSBN','en','application',$8,'mixed','generic_international','BOTH',true,true,'nursing','Physiological Integrity',$9,$10,NOW(),NOW())`,[sata?"sata":"multiple_choice",q.q,JSON.stringify(q.o),JSON.stringify(answers(q)),q.r,JSON.stringify(q.dr??[]),topic,sata?"SATA":"MCQ",["rn","nclex-rn","gastrointestinal","hepatic","round-3","both",topic.toLowerCase().replace(/[^a-z0-9]+/g,"-")],h]);return"inserted" as const;}
async function main(){await pool.query(`ALTER TABLE exam_questions ADD COLUMN IF NOT EXISTS stem_hash TEXT`);await pool.query(`ALTER TABLE exam_questions ADD COLUMN IF NOT EXISTS distractor_rationales JSONB DEFAULT '[]'::jsonb`);if(all.length<200)throw new Error(`RN_GI_R3_BELOW_200:${all.length}`);if(all.some(q=>!Array.isArray(q.dr)))throw new Error('RN_GI_R3_MISSING_DR');let inserted=0,skipped=0;for(const q of all){(await insert(q))==="inserted"?inserted++:skipped++;}console.log({authored:all.length,inserted,skipped,regionScope:'BOTH'});}
main().then(()=>process.exit(0)).catch(e=>{console.error(e);process.exit(1);});