import crypto from "crypto";
import { pool } from "../storage";
import { rnMentalHealthRound3Batch1Questions } from "../../client/src/data/exam-questions/rn-mental-health-round3-batch1";
import { rnMentalHealthRound3Batch2Questions } from "../../client/src/data/exam-questions/rn-mental-health-round3-batch2";
import { rnMentalHealthRound3Batch3Questions } from "../../client/src/data/exam-questions/rn-mental-health-round3-batch3";
import { rnMentalHealthRound3Batch4Questions } from "../../client/src/data/exam-questions/rn-mental-health-round3-batch4";
import type { ExamQuestion } from "../../client/src/data/exam-questions/types";
const all:ExamQuestion[]=[...rnMentalHealthRound3Batch1Questions,...rnMentalHealthRound3Batch2Questions,...rnMentalHealthRound3Batch3Questions,...rnMentalHealthRound3Batch4Questions];const hash=(s:string)=>crypto.createHash("sha256").update(s.trim().toLowerCase()).digest("hex").substring(0,32);const answers=(q:ExamQuestion)=>q.t==="sata"&&q.ca?q.ca:[q.a];
function topicFor(stem:string){const s=stem.toLowerCase();if(/suicid|self-harm|agitat|violence|psychosis|schizoph|clozapine|nms|serotonin|mania|lithium|catatonia|ect|delirium/.test(s))return"Acute Psychiatric Safety & Severe Mental Illness";if(/panic|ocd|ptsd|trauma|eating|anorexia|bulimia|refeeding|alcohol|benzodiazepine|opioid|buprenorphine|methadone|stimulant|cannabis|substance/.test(s))return"Anxiety, Trauma, Eating & Substance Disorders";if(/personality|dementia|functional|somatic|dissociative|adhd|autism|insomnia|sleep|grief|intimate partner|strangulation|sexual assault/.test(s))return"Therapeutic, Neurocognitive & Psychosocial Care";if(/ssri|snri|bupropion|mirtazapine|trazodone|maoi|antipsychotic|valproate|carbamazepine|lamotrigine|pregnan|breastfeed|discharge|relapse|reconciliation|metabolic|qt|access|recovery/.test(s))return"Psychopharmacology, Monitoring & Transition Safety";return"Mental Health Clinical Judgment";}
async function insert(q:ExamQuestion){const h=hash(q.q);const ex=await pool.query(`SELECT id FROM exam_questions WHERE stem_hash=$1 OR lower(trim(stem))=lower(trim($2)) LIMIT 1`,[h,q.q]);if(ex.rows.length)return"skipped" as const;const sata=q.t==="sata";const topic=topicFor(q.q);await pool.query(`INSERT INTO exam_questions (id,tier,exam,question_type,status,stem,options,correct_answer,rationale,distractor_rationales,difficulty,body_system,topic,country_code,licensing_body,language_code,cognitive_level,question_format,lab_unit_variant,medication_naming_variant,region_scope,is_mock_exam_eligible,is_adaptive_eligible,career_type,domain,tags,stem_hash,created_at,updated_at) VALUES (gen_random_uuid(),'rn','NCLEX-RN',$1,'published',$2,$3,$4,$5,$6,3,'Mental Health',$7,NULL,'NCSBN','en','application',$8,'mixed','generic_international','BOTH',true,true,'nursing','Psychosocial Integrity',$9,$10,NOW(),NOW())`,[sata?"sata":"multiple_choice",q.q,JSON.stringify(q.o),JSON.stringify(answers(q)),q.r,JSON.stringify(q.dr??[]),topic,sata?"SATA":"MCQ",["rn","nclex-rn","mental-health","round-3","both",topic.toLowerCase().replace(/[^a-z0-9]+/g,"-")],h]);return"inserted" as const;}
async function main(){await pool.query(`ALTER TABLE exam_questions ADD COLUMN IF NOT EXISTS stem_hash TEXT`);await pool.query(`ALTER TABLE exam_questions ADD COLUMN IF NOT EXISTS distractor_rationales JSONB DEFAULT '[]'::jsonb`);if(all.length<200)throw new Error(`RN_MH_R3_BELOW_200:${all.length}`);if(all.some(q=>!Array.isArray(q.dr)))throw new Error('RN_MH_R3_MISSING_DR');let inserted=0,skipped=0;for(const q of all){(await insert(q))==="inserted"?inserted++:skipped++;}console.log({authored:all.length,inserted,skipped,regionScope:'BOTH'});}
main().then(()=>process.exit(0)).catch(e=>{console.error(e);process.exit(1);});