import crypto from "crypto";
import { pool } from "../storage";
import { rnRenalRound2Batch1Questions } from "../../client/src/data/exam-questions/rn-renal-round2-batch1";
import { rnRenalRound2Batch2Questions } from "../../client/src/data/exam-questions/rn-renal-round2-batch2";
import { rnRenalRound2Batch3Questions } from "../../client/src/data/exam-questions/rn-renal-round2-batch3";
import { rnRenalRound2Batch4Questions } from "../../client/src/data/exam-questions/rn-renal-round2-batch4";
import type { ExamQuestion } from "../../client/src/data/exam-questions/types";
const batches=[rnRenalRound2Batch1Questions,rnRenalRound2Batch2Questions,rnRenalRound2Batch3Questions,rnRenalRound2Batch4Questions];const all:ExamQuestion[]=batches.flat();const hash=(s:string)=>crypto.createHash("sha256").update(s.trim().toLowerCase()).digest("hex").substring(0,32);const answers=(q:ExamQuestion)=>q.t==="sata"&&q.ca?q.ca:[q.a];
function topicFor(stem:string){const s=stem.toLowerCase();if(/acute kidney|aki|hyperkal|acid|rhabdo|nephrotox|urine microscopy|contrast/.test(s))return"AKI, Electrolytes & Acid-Base";if(/chronic kidney|ckd|albumin|egfr|anemia|erythrop|phosphate|pth|mineral|gout|conservative/.test(s))return"CKD Progression & Complications";if(/hemodialysis|fistula|graft|peritoneal|crrt|dialysis catheter/.test(s))return"Dialysis, CRRT & Access";if(/transplant|tacrolimus|mycophenolate|bk virus|cmv/.test(s))return"Kidney Transplant";if(/nephrotic|nephritic|glomerul|vasculitis|anti-gbm|lupus/.test(s))return"Glomerular & Immune Kidney Disease";if(/stone|nephrolith|pyeloneph|cystitis|retention|bph|tamsulosin|turp|hematuria|bladder|renal cell|ileal conduit/.test(s))return"Urinary Tract, Obstruction & Malignancy";return"Renal & Urinary Round 2";}
async function main(){await pool.query(`ALTER TABLE exam_questions ADD COLUMN IF NOT EXISTS stem_hash TEXT`);await pool.query(`ALTER TABLE exam_questions ADD COLUMN IF NOT EXISTS distractor_rationales JSONB DEFAULT '[]'::jsonb`);if(batches.some((b,i)=>b.length<45))throw new Error(`RN_RENAL_R2_THIN_BATCH:${batches.map((b,i)=>`${i+1}:${b.length}`).join(',')}`);if(all.length<200)throw new Error(`RN_RENAL_R2_MINIMUM_NOT_MET:${all.length}/200`);let inserted=0,skipped=0;for(const q of all){const h=hash(q.q);const ex=await pool.query(`SELECT id FROM exam_questions WHERE stem_hash=$1 OR lower(trim(stem))=lower(trim($2)) LIMIT 1`,[h,q.q]);if(ex.rows.length){skipped++;continue;}const sata=q.t==="sata";await pool.query(`INSERT INTO exam_questions (id,tier,exam,question_type,status,stem,options,correct_answer,rationale,distractor_rationales,difficulty,body_system,topic,country_code,licensing_body,language_code,cognitive_level,question_format,lab_unit_variant,medication_naming_variant,region_scope,is_mock_exam_eligible,is_adaptive_eligible,career_type,domain,tags,stem_hash,created_at,updated_at) VALUES (gen_random_uuid(),'rn','NCLEX-RN',$1,'published',$2,$3,$4,$5,$6,3,'Renal & Urinary',$7,NULL,'NCSBN','en','application',$8,'mixed','generic_international','BOTH',true,true,'nursing','Physiological Integrity',$9,$10,NOW(),NOW())`,[sata?"sata":"multiple_choice",q.q,JSON.stringify(q.o),JSON.stringify(answers(q)),q.r,JSON.stringify(q.dr??[]),topicFor(q.q),sata?"SATA":"MCQ",["rn","nclex-rn","renal","round2","shared-ca-us",topicFor(q.q).toLowerCase().replace(/[^a-z0-9]+/g,"-")],h]);inserted++;}console.log({authored:all.length,minimum:200,inserted,skipped,regionScope:"BOTH"});}
main().then(()=>process.exit(0)).catch(e=>{console.error(e);process.exit(1);});