import crypto from "crypto";
import { pool } from "../storage";
import { rnInfectiousDiseaseBankBatch1Questions } from "../../client/src/data/exam-questions/rn-infectious-disease-bank-batch1";
import { rnInfectiousDiseaseBankBatch2Questions } from "../../client/src/data/exam-questions/rn-infectious-disease-bank-batch2";
import { rnInfectiousDiseaseBankBatch3Questions } from "../../client/src/data/exam-questions/rn-infectious-disease-bank-batch3";
import { rnInfectiousDiseaseRegionalBankBatch1Questions } from "../../client/src/data/exam-questions/rn-infectious-disease-regional-bank-batch1";
import type { ExamQuestion } from "../../client/src/data/exam-questions/types";
const shared:ExamQuestion[]=[...rnInfectiousDiseaseBankBatch1Questions,...rnInfectiousDiseaseBankBatch2Questions,...rnInfectiousDiseaseBankBatch3Questions];
const hash=(s:string)=>crypto.createHash("sha256").update(s.trim().toLowerCase()).digest("hex").substring(0,32);const answers=(q:ExamQuestion)=>q.t==="sata"&&q.ca?q.ca:[q.a];
function topicFor(stem:string){const s=stem.toLowerCase();if(/sepsis|septic|source control|lactate|norepinephrine/.test(s))return"Sepsis & Source Control";if(/steward|antibiotic|culture|broad-spectrum|de-escal/.test(s))return"Antimicrobial Stewardship";if(/c\. difficile|clostridioides|toxic megacolon/.test(s))return"C. difficile";if(/mrsa|vre|esbl|cre|mdro/.test(s))return"Multidrug-Resistant Organisms";if(/central line|clabsi|urinary catheter|cauti|ventilator|vap/.test(s))return"Device-Associated Infection Prevention";if(/tubercul|isoniazid|rifampin|ethambutol|pyrazinamide/.test(s))return"Tuberculosis";if(/\bhiv\b|antiretroviral|pneumocystis|cryptococ|toxoplasma|candida esophag/.test(s))return"HIV & Opportunistic Infections";if(/mening|encephal|meningococ/.test(s))return"Meningitis & Encephalitis";if(/needlestick|occupational|blood splash|post-exposure|hepatitis b|hepatitis c/.test(s))return"Blood-Borne & Occupational Exposure";if(/influenza|respiratory virus|mask|aerosol-generating/.test(s))return"Respiratory Viral Infection Control";if(/syphilis|gonorr|chlamydia|herpes|hpv|sti/.test(s))return"Sexually Transmitted Infections";if(/malaria|dengue|histoplas|blastomy|aspergill|giardia|cryptospor/.test(s))return"Travel, Fungal & Parasitic Infection";if(/ppe|negative-pressure|positive-pressure|equipment|cleaning|isolation/.test(s))return"PPE, Isolation & Environmental Control";if(/surgical-site|abscess|necrotizing|food|salmonella|campylobacter|shiga/.test(s))return"Wound, Surgical & Food-Borne Infection";return"Infectious Disease Clinical Judgment";}
async function insert(q:ExamQuestion,region:"BOTH"|"CAN"|"US",country:string|null,topic:string,difficulty=3,cognitive="application"){const h=hash(q.q);const ex=await pool.query(`SELECT id FROM exam_questions WHERE stem_hash=$1 OR lower(trim(stem))=lower(trim($2)) LIMIT 1`,[h,q.q]);if(ex.rows.length)return"skipped" as const;const sata=q.t==="sata";await pool.query(`INSERT INTO exam_questions (id,tier,exam,question_type,status,stem,options,correct_answer,rationale,distractor_rationales,difficulty,body_system,topic,country_code,licensing_body,language_code,cognitive_level,question_format,lab_unit_variant,medication_naming_variant,region_scope,is_mock_exam_eligible,is_adaptive_eligible,career_type,domain,tags,stem_hash,created_at,updated_at) VALUES (gen_random_uuid(),'rn','NCLEX-RN',$1,'published',$2,$3,$4,$5,$6,$7,'Infectious Disease & Infection Control',$8,$9,'NCSBN','en',$10,$11,$12,$13,$14,true,true,'nursing','Safety & Infection Control',$15,$16,NOW(),NOW())`,[sata?"sata":"multiple_choice",q.q,JSON.stringify(q.o),JSON.stringify(answers(q)),q.r,JSON.stringify(q.dr??[]),difficulty,topic,country,cognitive,sata?"SATA":"MCQ",region==="CAN"?"SI":region==="US"?"US_conventional":"mixed",region==="CAN"?"Canadian_generic":region==="US"?"US_generic":"generic_international",region,["rn","nclex-rn","infectious-disease","infection-control",region.toLowerCase(),topic.toLowerCase().replace(/[^a-z0-9]+/g,"-")],h]);return"inserted" as const;}
async function main(){await pool.query(`ALTER TABLE exam_questions ADD COLUMN IF NOT EXISTS stem_hash TEXT`);await pool.query(`ALTER TABLE exam_questions ADD COLUMN IF NOT EXISTS distractor_rationales JSONB DEFAULT '[]'::jsonb`);if(rnInfectiousDiseaseBankBatch1Questions.length!==50)throw new Error(`RN_ID_BATCH1:${rnInfectiousDiseaseBankBatch1Questions.length}`);if(rnInfectiousDiseaseBankBatch2Questions.length!==50)throw new Error(`RN_ID_BATCH2:${rnInfectiousDiseaseBankBatch2Questions.length}`);if(rnInfectiousDiseaseBankBatch3Questions.length!==50)throw new Error(`RN_ID_BATCH3:${rnInfectiousDiseaseBankBatch3Questions.length}`);if(shared.length!==150)throw new Error(`RN_ID_SHARED:${shared.length}`);if(rnInfectiousDiseaseRegionalBankBatch1Questions.length!==20)throw new Error(`RN_ID_REGIONAL:${rnInfectiousDiseaseRegionalBankBatch1Questions.length}`);let inserted=0,skipped=0;for(const q of shared){(await insert(q,"BOTH",null,topicFor(q.q)))==="inserted"?inserted++:skipped++;}for(const q of rnInfectiousDiseaseRegionalBankBatch1Questions){(await insert(q,q.regionScope,q.countryCode,q.topic,q.difficulty,q.cognitiveLevel))==="inserted"?inserted++:skipped++;}console.log({authored:170,inserted,skipped});}
main().then(()=>process.exit(0)).catch(e=>{console.error(e);process.exit(1);});