import crypto from "crypto";
import { pool } from "../storage";
import { rnOncologyBankBatch1Questions } from "../../client/src/data/exam-questions/rn-oncology-bank-batch1";
import { rnOncologyBankBatch2Questions } from "../../client/src/data/exam-questions/rn-oncology-bank-batch2";
import { rnOncologyBankBatch3Questions } from "../../client/src/data/exam-questions/rn-oncology-bank-batch3";
import { rnOncologyRegionalBankBatch1Questions } from "../../client/src/data/exam-questions/rn-oncology-regional-bank-batch1";
import type { ExamQuestion } from "../../client/src/data/exam-questions/types";
const shared:ExamQuestion[]=[...rnOncologyBankBatch1Questions,...rnOncologyBankBatch2Questions,...rnOncologyBankBatch3Questions];
const hash=(s:string)=>crypto.createHash("sha256").update(s.trim().toLowerCase()).digest("hex").substring(0,32);const answers=(q:ExamQuestion)=>q.t==="sata"&&q.ca?q.ca:[q.a];
function topicFor(stem:string){const s=stem.toLowerCase();if(/neutropen|febrile/.test(s))return"Febrile Neutropenia & Infection";if(/tumor lysis|rasburicase|uric acid/.test(s))return"Tumor Lysis Syndrome";if(/spinal cord|superior vena cava|hypercalcemia|siadh|leukostasis|dic/.test(s))return"Oncologic Emergencies";if(/extravas|vesicant|doxorubicin|cisplatin|mesna|bleomycin|vincristine|methotrexate|mucositis/.test(s))return"Systemic Therapy Safety";if(/checkpoint|car-t|cytokine|icans|tocilizumab/.test(s))return"Immunotherapy & Cellular Therapy";if(/breast|lung|colorectal|prostate|ovarian|cervical|endometrial|testicular|melanoma|bladder|kidney|pancreatic|liver|head-and-neck|brain-tumor/.test(s))return"Solid Tumor Nursing";if(/radiation|brachytherapy/.test(s))return"Radiation Oncology";if(/pain|palliative|hospice|dyspnea|ascites|bowel obstruction|cachexia/.test(s))return"Palliative & Supportive Oncology";if(/leukemia|lymphoma|myeloma|stem-cell|graft-versus-host|transplant/.test(s))return"Hematologic Malignancy & Transplant";if(/survivor|fertility|late effect|caregiver|return-to-work|cognitive/.test(s))return"Cancer Survivorship";return"Oncology Clinical Judgment";}
async function insert(q:ExamQuestion,region:"BOTH"|"CAN"|"US",country:string|null,topic:string,difficulty=3,cognitive="application"){const h=hash(q.q);const ex=await pool.query(`SELECT id FROM exam_questions WHERE stem_hash=$1 OR lower(trim(stem))=lower(trim($2)) LIMIT 1`,[h,q.q]);if(ex.rows.length)return"skipped" as const;const sata=q.t==="sata";await pool.query(`INSERT INTO exam_questions (id,tier,exam,question_type,status,stem,options,correct_answer,rationale,distractor_rationales,difficulty,body_system,topic,country_code,licensing_body,language_code,cognitive_level,question_format,lab_unit_variant,medication_naming_variant,region_scope,is_mock_exam_eligible,is_adaptive_eligible,career_type,domain,tags,stem_hash,created_at,updated_at) VALUES (gen_random_uuid(),'rn','NCLEX-RN',$1,'published',$2,$3,$4,$5,$6,$7,'Oncology',$8,$9,'NCSBN','en',$10,$11,$12,$13,$14,true,true,'nursing','Physiological Integrity',$15,$16,NOW(),NOW())`,[sata?"sata":"multiple_choice",q.q,JSON.stringify(q.o),JSON.stringify(answers(q)),q.r,JSON.stringify(q.dr??[]),difficulty,topic,country,cognitive,sata?"SATA":"MCQ",region==="CAN"?"SI":region==="US"?"US_conventional":"mixed",region==="CAN"?"Canadian_generic":region==="US"?"US_generic":"generic_international",region,["rn","nclex-rn","oncology",region.toLowerCase(),topic.toLowerCase().replace(/[^a-z0-9]+/g,"-")],h]);return"inserted" as const;}
async function main(){await pool.query(`ALTER TABLE exam_questions ADD COLUMN IF NOT EXISTS stem_hash TEXT`);await pool.query(`ALTER TABLE exam_questions ADD COLUMN IF NOT EXISTS distractor_rationales JSONB DEFAULT '[]'::jsonb`);if(rnOncologyBankBatch1Questions.length!==50)throw new Error(`RN_ONC_BATCH1:${rnOncologyBankBatch1Questions.length}`);if(rnOncologyBankBatch2Questions.length!==48)throw new Error(`RN_ONC_BATCH2:${rnOncologyBankBatch2Questions.length}`);if(rnOncologyBankBatch3Questions.length!==52)throw new Error(`RN_ONC_BATCH3:${rnOncologyBankBatch3Questions.length}`);if(shared.length!==150)throw new Error(`RN_ONC_SHARED:${shared.length}`);if(rnOncologyRegionalBankBatch1Questions.length!==20)throw new Error(`RN_ONC_REGIONAL:${rnOncologyRegionalBankBatch1Questions.length}`);let inserted=0,skipped=0;for(const q of shared){(await insert(q,"BOTH",null,topicFor(q.q)))==="inserted"?inserted++:skipped++;}for(const q of rnOncologyRegionalBankBatch1Questions){(await insert(q,q.regionScope,q.countryCode,q.topic,q.difficulty,q.cognitiveLevel))==="inserted"?inserted++:skipped++;}console.log({authored:170,inserted,skipped});}
main().then(()=>process.exit(0)).catch(e=>{console.error(e);process.exit(1);});