import crypto from "crypto";
import { pool } from "../storage";
import { rnFundamentalsRound2Batch1Questions } from "../../client/src/data/exam-questions/rn-fundamentals-round2-batch1";
import { rnFundamentalsRound2Batch2Questions } from "../../client/src/data/exam-questions/rn-fundamentals-round2-batch2";
import { rnFundamentalsRound2Batch3Questions } from "../../client/src/data/exam-questions/rn-fundamentals-round2-batch3";
import { rnFundamentalsRound2Batch4Questions } from "../../client/src/data/exam-questions/rn-fundamentals-round2-batch4";
import type { ExamQuestion } from "../../client/src/data/exam-questions/types";
const all:ExamQuestion[]=[...rnFundamentalsRound2Batch1Questions,...rnFundamentalsRound2Batch2Questions,...rnFundamentalsRound2Batch3Questions,...rnFundamentalsRound2Batch4Questions];
const hash=(s:string)=>crypto.createHash("sha256").update(s.trim().toLowerCase()).digest("hex").substring(0,32);
const answers=(q:ExamQuestion)=>q.t==="sata"&&q.ca?q.ca:[q.a];
function topicFor(stem:string){const s=stem.toLowerCase();if(/deteriorat|perfusion|shock|vital|oliguria/.test(s))return"Deterioration & Perfusion";if(/fall|transfer|walker|mobility|orthostatic/.test(s))return"Falls & Mobility";if(/pressure|wound|skin|heel|moisture/.test(s))return"Skin & Pressure Injury";if(/swallow|aspirat|feeding|nutrition|refeeding/.test(s))return"Nutrition & Aspiration";if(/bowel|ostomy|ileostomy|constipat|diarrhea/.test(s))return"Bowel & Ostomy Care";if(/urinary|catheter|bladder|urostomy|nephrostomy/.test(s))return"Urinary Elimination";if(/specimen|culture|sputum|24-hour urine/.test(s))return"Specimen Collection";if(/oxygen|tracheostomy|suction|spirometer|airway/.test(s))return"Oxygen & Airway Basics";if(/surgery|perioperative|consent|drain|dehisc|chest tube|ng tube/.test(s))return"Perioperative, Tubes & Drains";if(/transfusion|taco|trali|blood administration/.test(s))return"Transfusion Basics";if(/pain|opioid|comfort|sleep|hearing|vision/.test(s))return"Pain, Comfort & Sensory Care";if(/handoff|documentation|identifier|critical result|incident|teach-back|interpreter|discharge|transition|reconciliation|ehr|barcode|ai|cyber/.test(s))return"Communication & Transition Safety";return"Fundamentals & Basic Care";}
async function insert(q:ExamQuestion){const h=hash(q.q);const ex=await pool.query(`SELECT id FROM exam_questions WHERE stem_hash=$1 OR lower(trim(stem))=lower(trim($2)) LIMIT 1`,[h,q.q]);if(ex.rows.length)return"skipped" as const;const sata=q.t==="sata";await pool.query(`INSERT INTO exam_questions (id,tier,exam,question_type,status,stem,options,correct_answer,rationale,distractor_rationales,difficulty,body_system,topic,country_code,licensing_body,language_code,cognitive_level,question_format,lab_unit_variant,medication_naming_variant,region_scope,is_mock_exam_eligible,is_adaptive_eligible,career_type,domain,tags,stem_hash,created_at,updated_at) VALUES (gen_random_uuid(),'rn','NCLEX-RN',$1,'published',$2,$3,$4,$5,$6,3,'Fundamentals & Basic Care',$7,NULL,'NCSBN','en','application',$8,'mixed','generic_international','BOTH',true,true,'nursing','Basic Care & Comfort',$9,$10,NOW(),NOW())`,[sata?"sata":"multiple_choice",q.q,JSON.stringify(q.o),JSON.stringify(answers(q)),q.r,JSON.stringify(q.dr??[]),topicFor(q.q),sata?"SATA":"MCQ",["rn","nclex-rn","fundamentals","round-2","both",topicFor(q.q).toLowerCase().replace(/[^a-z0-9]+/g,"-")],h]);return"inserted" as const;}
async function main(){await pool.query(`ALTER TABLE exam_questions ADD COLUMN IF NOT EXISTS stem_hash TEXT`);await pool.query(`ALTER TABLE exam_questions ADD COLUMN IF NOT EXISTS distractor_rationales JSONB DEFAULT '[]'::jsonb`);if(all.length<200)throw new Error(`RN_FUND_R2_BELOW_200:${all.length}`);if(all.some(q=>!Array.isArray(q.dr)))throw new Error('RN_FUND_R2_MISSING_DR');let inserted=0,skipped=0;for(const q of all){(await insert(q))==="inserted"?inserted++:skipped++;}console.log({authored:all.length,inserted,skipped,regionScope:'BOTH'});}
main().then(()=>process.exit(0)).catch(e=>{console.error(e);process.exit(1);});