import crypto from "crypto";
import { pool } from "../storage";
import { rnFundamentalsBankBatch1Questions } from "../../client/src/data/exam-questions/rn-fundamentals-bank-batch1";
import { rnFundamentalsBankBatch2Questions } from "../../client/src/data/exam-questions/rn-fundamentals-bank-batch2";
import { rnFundamentalsBankBatch3Questions } from "../../client/src/data/exam-questions/rn-fundamentals-bank-batch3";
import { rnFundamentalsRegionalBankBatch1Questions } from "../../client/src/data/exam-questions/rn-fundamentals-regional-bank-batch1";
import type { ExamQuestion } from "../../client/src/data/exam-questions/types";
const shared:ExamQuestion[]=[...rnFundamentalsBankBatch1Questions,...rnFundamentalsBankBatch2Questions,...rnFundamentalsBankBatch3Questions];
const hash=(s:string)=>crypto.createHash("sha256").update(s.trim().toLowerCase()).digest("hex").substring(0,32);const answers=(q:ExamQuestion)=>q.t==="sata"&&q.ca?q.ca:[q.a];
function topicFor(stem:string){const s=stem.toLowerCase();if(/priority|deteriorat|warning score|shock|perfusion|first/.test(s))return"Prioritization & Deterioration";if(/fall|walker|gait|transfer|orthostatic|mobility/.test(s))return"Falls & Mobility";if(/pressure injury|wound healing|heel|device pressure|incontinence-associated/.test(s))return"Pressure Injury & Skin Integrity";if(/restraint|seclusion/.test(s))return"Least-Restrictive Safety";if(/oral care|hygiene|foot|bath|skin/.test(s))return"Hygiene & Skin Care";if(/position|fowler|aspiration|swallow|feeding|dysphagia/.test(s))return"Positioning, Nutrition & Aspiration";if(/fluid|intake|output|weight|dehydrat|overload/.test(s))return"Fluid Balance & I&O";if(/bowel|constipat|diarrhea|ostomy|colostomy|ileostomy/.test(s))return"Bowel Elimination & Ostomy";if(/urinary|catheter|void|retention|incontinence|bladder/.test(s))return"Urinary Elimination";if(/specimen|culture|24-hour urine|blood culture/.test(s))return"Specimen Collection";if(/oxygen|suction|tracheostomy|airway/.test(s))return"Basic Oxygen & Airway Care";if(/surgery|operative|postoperative|consent|incision|dehisc|drain/.test(s))return"Perioperative & Wound Care";if(/transfusion|blood product|taco|trali/.test(s))return"Transfusion Basics";if(/pain|sleep|hearing|vision/.test(s))return"Comfort, Sleep & Sensory Care";if(/identifier|handoff|critical lab|documentation|incident|medication error/.test(s))return"Patient Safety & Communication";return"Fundamentals & Basic Care";}
async function insert(q:ExamQuestion,region:"BOTH"|"CAN"|"US",country:string|null,topic:string,difficulty=3,cognitive="application"){const h=hash(q.q);const ex=await pool.query(`SELECT id FROM exam_questions WHERE stem_hash=$1 OR lower(trim(stem))=lower(trim($2)) LIMIT 1`,[h,q.q]);if(ex.rows.length)return"skipped" as const;const sata=q.t==="sata";await pool.query(`INSERT INTO exam_questions (id,tier,exam,question_type,status,stem,options,correct_answer,rationale,distractor_rationales,difficulty,body_system,topic,country_code,licensing_body,language_code,cognitive_level,question_format,lab_unit_variant,medication_naming_variant,region_scope,is_mock_exam_eligible,is_adaptive_eligible,career_type,domain,tags,stem_hash,created_at,updated_at) VALUES (gen_random_uuid(),'rn','NCLEX-RN',$1,'published',$2,$3,$4,$5,$6,$7,'Fundamentals & Basic Care',$8,$9,'NCSBN','en',$10,$11,$12,$13,$14,true,true,'nursing','Basic Care & Comfort',$15,$16,NOW(),NOW())`,[sata?"sata":"multiple_choice",q.q,JSON.stringify(q.o),JSON.stringify(answers(q)),q.r,JSON.stringify(q.dr??[]),difficulty,topic,country,cognitive,sata?"SATA":"MCQ",region==="CAN"?"SI":region==="US"?"US_conventional":"mixed",region==="CAN"?"Canadian_generic":region==="US"?"US_generic":"generic_international",region,["rn","nclex-rn","fundamentals","basic-care",region.toLowerCase(),topic.toLowerCase().replace(/[^a-z0-9]+/g,"-")],h]);return"inserted" as const;}
async function main(){await pool.query(`ALTER TABLE exam_questions ADD COLUMN IF NOT EXISTS stem_hash TEXT`);await pool.query(`ALTER TABLE exam_questions ADD COLUMN IF NOT EXISTS distractor_rationales JSONB DEFAULT '[]'::jsonb`);if(rnFundamentalsBankBatch1Questions.length!==50)throw new Error(`RN_FUND_BATCH1:${rnFundamentalsBankBatch1Questions.length}`);if(rnFundamentalsBankBatch2Questions.length!==50)throw new Error(`RN_FUND_BATCH2:${rnFundamentalsBankBatch2Questions.length}`);if(rnFundamentalsBankBatch3Questions.length!==50)throw new Error(`RN_FUND_BATCH3:${rnFundamentalsBankBatch3Questions.length}`);if(shared.length!==150)throw new Error(`RN_FUND_SHARED:${shared.length}`);if(rnFundamentalsRegionalBankBatch1Questions.length!==20)throw new Error(`RN_FUND_REGIONAL:${rnFundamentalsRegionalBankBatch1Questions.length}`);let inserted=0,skipped=0;for(const q of shared){(await insert(q,"BOTH",null,topicFor(q.q)))==="inserted"?inserted++:skipped++;}for(const q of rnFundamentalsRegionalBankBatch1Questions){(await insert(q,q.regionScope,q.countryCode,q.topic,q.difficulty,q.cognitiveLevel))==="inserted"?inserted++:skipped++;}console.log({authored:170,inserted,skipped});}
main().then(()=>process.exit(0)).catch(e=>{console.error(e);process.exit(1);});