import crypto from "crypto";
import { pool } from "../storage";
import { rnMaternalNewbornBankBatch1Questions } from "../../client/src/data/exam-questions/rn-maternal-newborn-bank-batch1";
import { rnMaternalNewbornBankBatch2Questions } from "../../client/src/data/exam-questions/rn-maternal-newborn-bank-batch2";
import { rnMaternalNewbornBankBatch3Questions } from "../../client/src/data/exam-questions/rn-maternal-newborn-bank-batch3";
import { rnMaternalNewbornRegionalBankBatch1Questions } from "../../client/src/data/exam-questions/rn-maternal-newborn-regional-bank-batch1";
import type { ExamQuestion } from "../../client/src/data/exam-questions/types";
const shared:ExamQuestion[]=[...rnMaternalNewbornBankBatch1Questions,...rnMaternalNewbornBankBatch2Questions,...rnMaternalNewbornBankBatch3Questions];
const hash=(s:string)=>crypto.createHash("sha256").update(s.trim().toLowerCase()).digest("hex").substring(0,32);const answers=(q:ExamQuestion)=>q.t==="sata"&&q.ca?q.ca:[q.a];
function topicFor(stem:string){const s=stem.toLowerCase();if(/preeclamp|eclamp|hellp|hypertension/.test(s))return"Hypertensive Disorders of Pregnancy";if(/diabet|glucose|dka/.test(s))return"Diabetes in Pregnancy";if(/previa|abruption|ectopic|vaginal bleeding/.test(s))return"Obstetric Bleeding";if(/pprom|preterm|corticosteroid|fetal movement|nonstress|biophysical|rh-negative|alloimmun/.test(s))return"Antepartum High Risk";if(/fetal heart|deceler|variability|tachysystole|oxytocin|labor|cord prolapse|shoulder dystocia|uterine rupture|amniotic fluid|chorio|vacuum/.test(s))return"Intrapartum & Fetal Surveillance";if(/postpartum hemorr|boggy|fundus|uterotonic|lochia|endometritis|mastitis|postpartum preeclamp|psychosis/.test(s))return"Postpartum Care & Emergencies";if(/newborn|neonatal|bilirubin|jaundice|phototherapy|hypogly|respiratory distress|necrotizing enterocolitis|ductal|breastfeeding|cephalo|subgaleal/.test(s))return"Newborn Care & Emergencies";return"Maternal-Newborn Clinical Judgment";}
async function insert(q:ExamQuestion,region:"BOTH"|"CAN"|"US",country:string|null,topic:string,difficulty=3,cognitive="application"){const h=hash(q.q);const ex=await pool.query(`SELECT id FROM exam_questions WHERE stem_hash=$1 OR lower(trim(stem))=lower(trim($2)) LIMIT 1`,[h,q.q]);if(ex.rows.length)return"skipped" as const;const sata=q.t==="sata";await pool.query(`INSERT INTO exam_questions (id,tier,exam,question_type,status,stem,options,correct_answer,rationale,distractor_rationales,difficulty,body_system,topic,country_code,licensing_body,language_code,cognitive_level,question_format,lab_unit_variant,medication_naming_variant,region_scope,is_mock_exam_eligible,is_adaptive_eligible,career_type,domain,tags,stem_hash,created_at,updated_at) VALUES (gen_random_uuid(),'rn','NCLEX-RN',$1,'published',$2,$3,$4,$5,$6,$7,'Maternal-Newborn',$8,$9,'NCSBN','en',$10,$11,$12,$13,$14,true,true,'nursing','Health Promotion & Physiological Integrity',$15,$16,NOW(),NOW())`,[sata?"sata":"multiple_choice",q.q,JSON.stringify(q.o),JSON.stringify(answers(q)),q.r,JSON.stringify(q.dr??[]),difficulty,topic,country,cognitive,sata?"SATA":"MCQ",region==="CAN"?"SI":region==="US"?"US_conventional":"mixed",region==="CAN"?"Canadian_generic":region==="US"?"US_generic":"generic_international",region,["rn","nclex-rn","maternal-newborn",region.toLowerCase(),topic.toLowerCase().replace(/[^a-z0-9]+/g,"-")],h]);return"inserted" as const;}
async function main(){await pool.query(`ALTER TABLE exam_questions ADD COLUMN IF NOT EXISTS stem_hash TEXT`);await pool.query(`ALTER TABLE exam_questions ADD COLUMN IF NOT EXISTS distractor_rationales JSONB DEFAULT '[]'::jsonb`);if(rnMaternalNewbornBankBatch1Questions.length!==50)throw new Error(`RN_MAT_BATCH1:${rnMaternalNewbornBankBatch1Questions.length}`);if(rnMaternalNewbornBankBatch2Questions.length!==47)throw new Error(`RN_MAT_BATCH2:${rnMaternalNewbornBankBatch2Questions.length}`);if(rnMaternalNewbornBankBatch3Questions.length!==53)throw new Error(`RN_MAT_BATCH3:${rnMaternalNewbornBankBatch3Questions.length}`);if(shared.length!==150)throw new Error(`RN_MAT_SHARED:${shared.length}`);if(rnMaternalNewbornRegionalBankBatch1Questions.length!==20)throw new Error(`RN_MAT_REGIONAL:${rnMaternalNewbornRegionalBankBatch1Questions.length}`);let inserted=0,skipped=0;for(const q of shared){(await insert(q,"BOTH",null,topicFor(q.q)))==="inserted"?inserted++:skipped++;}for(const q of rnMaternalNewbornRegionalBankBatch1Questions){(await insert(q,q.regionScope,q.countryCode,q.topic,q.difficulty,q.cognitiveLevel))==="inserted"?inserted++:skipped++;}console.log({authored:170,inserted,skipped});}
main().then(()=>process.exit(0)).catch(e=>{console.error(e);process.exit(1);});