import crypto from "crypto";
import { pool } from "../storage";
import { rnPharmacologyBankBatch1Questions } from "../../client/src/data/exam-questions/rn-pharmacology-bank-batch1";
import { rnPharmacologyBankBatch2Questions } from "../../client/src/data/exam-questions/rn-pharmacology-bank-batch2";
import { rnPharmacologyBankBatch3Questions } from "../../client/src/data/exam-questions/rn-pharmacology-bank-batch3";
import { rnPharmacologyRegionalBankBatch1Questions } from "../../client/src/data/exam-questions/rn-pharmacology-regional-bank-batch1";
import type { ExamQuestion } from "../../client/src/data/exam-questions/types";
const shared:ExamQuestion[]=[...rnPharmacologyBankBatch1Questions,...rnPharmacologyBankBatch2Questions,...rnPharmacologyBankBatch3Questions];
const hash=(s:string)=>crypto.createHash("sha256").update(s.trim().toLowerCase()).digest("hex").substring(0,32);const answers=(q:ExamQuestion)=>q.t==="sata"&&q.ca?q.ca:[q.a];
function topicFor(stem:string){const s=stem.toLowerCase();if(/insulin|hypogly|glucagon/.test(s))return"Insulin & Glucose-Lowering Safety";if(/heparin|warfarin|apixaban|dabigatran|anticoag/.test(s))return"Anticoagulants";if(/opioid|morphine|fentanyl|methadone|naloxone/.test(s))return"Opioids & Sedatives";if(/potassium|magnesium|hypertonic|calcium/.test(s))return"High-Alert Electrolytes";if(/ace inhibitor|arb|sacubitril|spironolactone|furosemide|thiazide|beta-block|amlodipine|diltiazem|nitroglycerin|statin|amiodarone|adenosine|sotalol|digoxin|norepinephrine/.test(s))return"Cardiovascular Pharmacology";if(/albuterol|salbutamol|inhaled corticosteroid|tiotropium|ipratropium|laba|roflumilast|prednisone/.test(s))return"Respiratory Pharmacology";if(/vancomycin|gentamicin|penicillin|doxycycline|linezolid|clindamycin|rifampin|isoniazid|fluoroquinolone|metronidazole|antibiotic/.test(s))return"Antimicrobial Pharmacology";if(/levothyroxine|methimazole|propylthiouracil|sulfonylurea|sglt2|glp-1|pioglitazone|bisphosphonate|denosumab/.test(s))return"Endocrine Pharmacology";if(/ssri|bupropion|clozapine|haloperidol|lithium|valproate|carbamazepine|lamotrigine/.test(s))return"Psychiatric Pharmacology";if(/proton-pump|acetaminophen|nsaid/.test(s))return"GI & Analgesic Pharmacology";if(/tacrolimus|cyclosporine|mycophenolate|immunosuppress/.test(s))return"Transplant & Immunosuppressant Pharmacology";return"Medication Safety & Clinical Pharmacology";}
async function insert(q:ExamQuestion,region:"BOTH"|"CAN"|"US",country:string|null,topic:string,difficulty=3,cognitive="application"){const h=hash(q.q);const ex=await pool.query(`SELECT id FROM exam_questions WHERE stem_hash=$1 OR lower(trim(stem))=lower(trim($2)) LIMIT 1`,[h,q.q]);if(ex.rows.length)return"skipped" as const;const sata=q.t==="sata";await pool.query(`INSERT INTO exam_questions (id,tier,exam,question_type,status,stem,options,correct_answer,rationale,distractor_rationales,difficulty,body_system,topic,country_code,licensing_body,language_code,cognitive_level,question_format,lab_unit_variant,medication_naming_variant,region_scope,is_mock_exam_eligible,is_adaptive_eligible,career_type,domain,tags,stem_hash,created_at,updated_at) VALUES (gen_random_uuid(),'rn','NCLEX-RN',$1,'published',$2,$3,$4,$5,$6,$7,'Pharmacology',$8,$9,'NCSBN','en',$10,$11,$12,$13,$14,true,true,'nursing','Pharmacological & Parenteral Therapies',$15,$16,NOW(),NOW())`,[sata?"sata":"multiple_choice",q.q,JSON.stringify(q.o),JSON.stringify(answers(q)),q.r,JSON.stringify(q.dr??[]),difficulty,topic,country,cognitive,sata?"SATA":"MCQ",region==="CAN"?"SI":region==="US"?"US_conventional":"mixed",region==="CAN"?"Canadian_generic":region==="US"?"US_generic":"generic_international",region,["rn","nclex-rn","pharmacology",region.toLowerCase(),topic.toLowerCase().replace(/[^a-z0-9]+/g,"-")],h]);return"inserted" as const;}
async function main(){await pool.query(`ALTER TABLE exam_questions ADD COLUMN IF NOT EXISTS stem_hash TEXT`);await pool.query(`ALTER TABLE exam_questions ADD COLUMN IF NOT EXISTS distractor_rationales JSONB DEFAULT '[]'::jsonb`);if(rnPharmacologyBankBatch1Questions.length!==50)throw new Error(`RN_PHARM_BATCH1:${rnPharmacologyBankBatch1Questions.length}`);if(rnPharmacologyBankBatch2Questions.length!==50)throw new Error(`RN_PHARM_BATCH2:${rnPharmacologyBankBatch2Questions.length}`);if(rnPharmacologyBankBatch3Questions.length!==50)throw new Error(`RN_PHARM_BATCH3:${rnPharmacologyBankBatch3Questions.length}`);if(shared.length!==150)throw new Error(`RN_PHARM_SHARED:${shared.length}`);if(rnPharmacologyRegionalBankBatch1Questions.length!==20)throw new Error(`RN_PHARM_REGIONAL:${rnPharmacologyRegionalBankBatch1Questions.length}`);let inserted=0,skipped=0;for(const q of shared){(await insert(q,"BOTH",null,topicFor(q.q)))==="inserted"?inserted++:skipped++;}for(const q of rnPharmacologyRegionalBankBatch1Questions){(await insert(q,q.regionScope,q.countryCode,q.topic,q.difficulty,q.cognitiveLevel))==="inserted"?inserted++:skipped++;}console.log({authored:170,inserted,skipped});}
main().then(()=>process.exit(0)).catch(e=>{console.error(e);process.exit(1);});