import crypto from "crypto";
import { pool } from "../storage";
import { rnCommunityPublicHealthRound2Batch1Questions } from "../../client/src/data/exam-questions/rn-community-public-health-round2-batch1";
import { rnCommunityPublicHealthRound2Batch2Questions } from "../../client/src/data/exam-questions/rn-community-public-health-round2-batch2";
import { rnCommunityPublicHealthRound2Batch3Questions } from "../../client/src/data/exam-questions/rn-community-public-health-round2-batch3";
import { rnCommunityPublicHealthRound2Batch4Questions } from "../../client/src/data/exam-questions/rn-community-public-health-round2-batch4";
import type { ExamQuestion } from "../../client/src/data/exam-questions/types";
const batches=[rnCommunityPublicHealthRound2Batch1Questions,rnCommunityPublicHealthRound2Batch2Questions,rnCommunityPublicHealthRound2Batch3Questions,rnCommunityPublicHealthRound2Batch4Questions];
const all:ExamQuestion[]=batches.flat();
const hash=(s:string)=>crypto.createHash("sha256").update(s.trim().toLowerCase()).digest("hex").substring(0,32);
const answers=(q:ExamQuestion)=>q.t==="sata"&&q.ca?q.ca:[q.a];
function topicFor(stem:string){const s=stem.toLowerCase();if(/outbreak|surveillance|incidence|prevalence|screen|case definition|epidemic|attack rate|bias|predictive/.test(s))return"Epidemiology, Screening & Surveillance";if(/home|school|occupational|telehealth|rural|homeless|harm reduction|caregiver|community clinic|transport/.test(s))return"Community, Home & Access";if(/heat|wildfire|lead|carbon monoxide|flood|chemical|climate|environment/.test(s))return"Environmental & Climate Health";if(/disaster|shelter|mass casualty|evacuat|preparedness|mitigation|recovery|psychological first aid/.test(s))return"Disaster & Emergency Preparedness";if(/program|logic model|fidelity|evaluation|policy|advocacy|equity|cost-effect|sustainab/.test(s))return"Program Evaluation, Policy & Equity";if(/dashboard|data|algorithm|model|surveillance system|wastewater|privacy|version control|denominator/.test(s))return"Public Health Informatics & Data Quality";return"Community & Public Health";}
async function insert(q:ExamQuestion){const h=hash(q.q);const ex=await pool.query(`SELECT id FROM exam_questions WHERE stem_hash=$1 OR lower(trim(stem))=lower(trim($2)) LIMIT 1`,[h,q.q]);if(ex.rows.length)return"skipped" as const;const sata=q.t==="sata";await pool.query(`INSERT INTO exam_questions (id,tier,exam,question_type,status,stem,options,correct_answer,rationale,distractor_rationales,difficulty,body_system,topic,country_code,licensing_body,language_code,cognitive_level,question_format,lab_unit_variant,medication_naming_variant,region_scope,is_mock_exam_eligible,is_adaptive_eligible,career_type,domain,tags,stem_hash,created_at,updated_at) VALUES (gen_random_uuid(),'rn','NCLEX-RN',$1,'published',$2,$3,$4,$5,$6,3,'Community & Public Health',$7,NULL,'NCSBN','en','analysis',$8,'mixed','generic_international','BOTH',true,true,'nursing','Health Promotion & Maintenance',$9,$10,NOW(),NOW())`,[sata?"sata":"multiple_choice",q.q,JSON.stringify(q.o),JSON.stringify(answers(q)),q.r,JSON.stringify(q.dr??[]),topicFor(q.q),sata?"SATA":"MCQ",["rn","nclex-rn","community","public-health","round2","both",topicFor(q.q).toLowerCase().replace(/[^a-z0-9]+/g,"-")],h]);return"inserted" as const;}
async function main(){await pool.query(`ALTER TABLE exam_questions ADD COLUMN IF NOT EXISTS stem_hash TEXT`);await pool.query(`ALTER TABLE exam_questions ADD COLUMN IF NOT EXISTS distractor_rationales JSONB DEFAULT '[]'::jsonb`);batches.forEach((b,i)=>{if(b.length<45)throw new Error(`RN_COMM_R2_BATCH_${i+1}_THIN:${b.length}`)});if(all.length<200)throw new Error(`RN_COMM_R2_TOTAL:${all.length}`);let inserted=0,skipped=0;for(const q of all){(await insert(q))==="inserted"?inserted++:skipped++;}console.log({authored:all.length,inserted,skipped,regionScope:"BOTH"});}
main().then(()=>process.exit(0)).catch(e=>{console.error(e);process.exit(1);});