import crypto from "crypto";
import { pool } from "../storage";
import { rnRespiratoryRound3Batch1Questions } from "../../client/src/data/exam-questions/rn-respiratory-round3-batch1";
import { rnRespiratoryRound3Batch2Questions } from "../../client/src/data/exam-questions/rn-respiratory-round3-batch2";
import { rnRespiratoryRound3Batch3Questions } from "../../client/src/data/exam-questions/rn-respiratory-round3-batch3";
import { rnRespiratoryRound3Batch4Questions } from "../../client/src/data/exam-questions/rn-respiratory-round3-batch4";
import type { ExamQuestion } from "../../client/src/data/exam-questions/types";
const all:ExamQuestion[]=[...rnRespiratoryRound3Batch1Questions,...rnRespiratoryRound3Batch2Questions,...rnRespiratoryRound3Batch3Questions,...rnRespiratoryRound3Batch4Questions];
const hash=(s:string)=>crypto.createHash("sha256").update(s.trim().toLowerCase()).digest("hex").substring(0,32); const answers=(q:ExamQuestion)=>q.t==="sata"&&q.ca?q.ca:[q.a];
function topicFor(stem:string){const s=stem.toLowerCase();if(/abg|paco2|ph |ventilat|capnograph|co2|hypercapn|hypovent/.test(s))return"Gas Exchange & Ventilation";if(/asthma|eosinoph|biologic|inhaled corticosteroid|spacer/.test(s))return"Asthma & Airway Disease";if(/copd|bronchiect|cystic|alpha-1|pulmonary rehab/.test(s))return"Chronic Obstructive & Suppurative Lung Disease";if(/pulmonary hypertension|prostacyclin|right-ventricular|right ventricular/.test(s))return"Pulmonary Hypertension & RV Failure";if(/pulmonary embol|pe\b|thrombol/.test(s))return"Pulmonary Embolism";if(/ards|plateau|peep|prone|ventilator|auto-peep|extubat/.test(s))return"ARDS & Mechanical Ventilation";if(/chest tube|pneumothor|hemothor|pleural|thoracentes|empyema|chylothor/.test(s))return"Pleural & Chest Drainage";if(/tracheost|suction|myasthen|guillain|als\b|neuromuscular|spinal cord/.test(s))return"Artificial Airway & Neuromuscular Respiratory Failure";if(/smoke|inhalation|carbon monoxide|burn|flail|rib fracture/.test(s))return"Respiratory Trauma & Inhalation Injury";return"Respiratory Clinical Judgment";}
async function insert(q:ExamQuestion){const h=hash(q.q);const ex=await pool.query(`SELECT id FROM exam_questions WHERE stem_hash=$1 OR lower(trim(stem))=lower(trim($2)) LIMIT 1`,[h,q.q]);if(ex.rows.length)return"skipped" as const;const sata=q.t==="sata";const topic=topicFor(q.q);await pool.query(`INSERT INTO exam_questions (id,tier,exam,question_type,status,stem,options,correct_answer,rationale,distractor_rationales,difficulty,body_system,topic,country_code,licensing_body,language_code,cognitive_level,question_format,lab_unit_variant,medication_naming_variant,region_scope,is_mock_exam_eligible,is_adaptive_eligible,career_type,domain,tags,stem_hash,created_at,updated_at) VALUES (gen_random_uuid(),'rn','NCLEX-RN',$1,'published',$2,$3,$4,$5,$6,3,'Respiratory',$7,NULL,'NCSBN','en','application',$8,'mixed','generic_international','BOTH',true,true,'nursing','Physiological Integrity',$9,$10,NOW(),NOW())`,[sata?"sata":"multiple_choice",q.q,JSON.stringify(q.o),JSON.stringify(answers(q)),q.r,JSON.stringify(q.dr??[]),topic,sata?"SATA":"MCQ",["rn","nclex-rn","respiratory","round-3","both",topic.toLowerCase().replace(/[^a-z0-9]+/g,"-")],h]);return"inserted" as const;}
async function main(){await pool.query(`ALTER TABLE exam_questions ADD COLUMN IF NOT EXISTS stem_hash TEXT`);await pool.query(`ALTER TABLE exam_questions ADD COLUMN IF NOT EXISTS distractor_rationales JSONB DEFAULT '[]'::jsonb`);if(all.length<200)throw new Error(`RN_RESP_R3_BELOW_200:${all.length}`);if(all.some(q=>!Array.isArray(q.dr)))throw new Error('RN_RESP_R3_MISSING_DR');let inserted=0,skipped=0;for(const q of all){(await insert(q))==="inserted"?inserted++:skipped++;}console.log({authored:all.length,inserted,skipped,regionScope:'BOTH'});}
main().then(()=>process.exit(0)).catch(e=>{console.error(e);process.exit(1);});