import crypto from "crypto";
import { pool } from "../storage";
import { rnInfectiousRound2Batch1Questions } from "../../client/src/data/exam-questions/rn-infectious-round2-batch1";
import { rnInfectiousRound2Batch2Questions } from "../../client/src/data/exam-questions/rn-infectious-round2-batch2";
import { rnInfectiousRound2Batch3Questions } from "../../client/src/data/exam-questions/rn-infectious-round2-batch3";
import { rnInfectiousRound2Batch4Questions } from "../../client/src/data/exam-questions/rn-infectious-round2-batch4";
import type { ExamQuestion } from "../../client/src/data/exam-questions/types";
const batches=[rnInfectiousRound2Batch1Questions,rnInfectiousRound2Batch2Questions,rnInfectiousRound2Batch3Questions,rnInfectiousRound2Batch4Questions];const all:ExamQuestion[]=batches.flat();const hash=(s:string)=>crypto.createHash("sha256").update(s.trim().toLowerCase()).digest("hex").substring(0,32);const answers=(q:ExamQuestion)=>q.t==="sata"&&q.ca?q.ca:[q.a];
function topicFor(stem:string){const s=stem.toLowerCase();if(/sepsis|steward|c\. difficile|mdro|mrsa|vre|esbl|cre|source control|antibiotic/.test(s))return"Sepsis, Stewardship & MDROs";if(/tuberculosis|isoniazid|rifamp|ethambutol|hiv|pneumocystis|cryptococ|meningitis|encephalitis|needlestick|pep|hepatitis b|hepatitis c/.test(s))return"TB, HIV, CNS Infection & Occupational Exposure";if(/central line|catheter|cauti|clabsi|ventilator|vap|influenza|rsv|measles|varicella|airborne|negative-pressure|respirator|ppe/.test(s))return"Device & Respiratory Infection Control";if(/malaria|dengue|rabies|tetanus|lyme|ricketts|giardia|vibrio|asperg|histoplas|coccidio|blastomy|immunosuppress|splenect|complement/.test(s))return"Travel, Fungal & Immunocompromised Host";return"Infectious Disease Round 2";}
async function main(){await pool.query(`ALTER TABLE exam_questions ADD COLUMN IF NOT EXISTS stem_hash TEXT`);await pool.query(`ALTER TABLE exam_questions ADD COLUMN IF NOT EXISTS distractor_rationales JSONB DEFAULT '[]'::jsonb`);if(batches.some((b,i)=>b.length<45))throw new Error(`RN_INFECT_R2_THIN_BATCH:${batches.map((b,i)=>`${i+1}:${b.length}`).join(',')}`);if(all.length<200)throw new Error(`RN_INFECT_R2_MINIMUM_NOT_MET:${all.length}/200`);let inserted=0,skipped=0;for(const q of all){const h=hash(q.q);const ex=await pool.query(`SELECT id FROM exam_questions WHERE stem_hash=$1 OR lower(trim(stem))=lower(trim($2)) LIMIT 1`,[h,q.q]);if(ex.rows.length){skipped++;continue;}const sata=q.t==="sata";await pool.query(`INSERT INTO exam_questions (id,tier,exam,question_type,status,stem,options,correct_answer,rationale,distractor_rationales,difficulty,body_system,topic,country_code,licensing_body,language_code,cognitive_level,question_format,lab_unit_variant,medication_naming_variant,region_scope,is_mock_exam_eligible,is_adaptive_eligible,career_type,domain,tags,stem_hash,created_at,updated_at) VALUES (gen_random_uuid(),'rn','NCLEX-RN',$1,'published',$2,$3,$4,$5,$6,3,'Infectious Disease & Infection Control',$7,NULL,'NCSBN','en','application',$8,'mixed','generic_international','BOTH',true,true,'nursing','Safety & Infection Control',$9,$10,NOW(),NOW())`,[sata?"sata":"multiple_choice",q.q,JSON.stringify(q.o),JSON.stringify(answers(q)),q.r,JSON.stringify(q.dr??[]),topicFor(q.q),sata?"SATA":"MCQ",["rn","nclex-rn","infectious-disease","round2","shared-ca-us",topicFor(q.q).toLowerCase().replace(/[^a-z0-9]+/g,"-")],h]);inserted++;}console.log({authored:all.length,minimum:200,inserted,skipped,regionScope:"BOTH"});}
main().then(()=>process.exit(0)).catch(e=>{console.error(e);process.exit(1);});