/**
 * Deterministic tier/exam enrichment for legacy ai_cache MCQ line items **before** mapLegacyItemToExamQuestion.
 * No silent defaults to NCLEX-RN or free tier. Low-confidence cases remain missing → strict mapper rejects.
 *
 * Priority: explicit item → parent row → deterministic inference → manual mapping → path/filename signals.
 */
import * as fs from "fs";
import * as path from "path";

export type MetadataProvenanceSource =
  | "explicit_item_field"
  | "parent_metadata"
  | "filename"
  | "path_segment"
  | "cache_key"
  | "inferred_rule"
  | "manual_mapping";

export type NursingEnrichmentContext = {
  sourceFileName: string;
  /** Directory containing the JSON (for path_segment / bundle name if needed). */
  exportDirAbs: string;
  cacheKey: string | null;
  rowIndex: number;
  outputItemIndex: number;
  parentRow: Record<string, unknown>;
};

export type EnrichmentAudit = {
  originalTier: string | null;
  originalExam: string | null;
  mergedTier: string | null;
  mergedExam: string | null;
  tierSource: MetadataProvenanceSource | null;
  examSource: MetadataProvenanceSource | null;
  tierDetail?: string;
  examDetail?: string;
  manualMappingKey?: string;
  inferredRuleIds: string[];
  ambiguous: boolean;
  ambiguousReasons: string[];
};

export type ManualMappingFileV1 = {
  version: 1;
  description?: string;
  /** Reviewed only — never autogenerated by tools. */
  reviewed?: boolean;
  cacheKeyExact: Record<string, { tier: string; exam: string; note?: string }>;
  cacheKeyPatterns: Array<{
    pattern: string;
    tier: string;
    exam: string;
    description?: string;
  }>;
};

let cachedManual: ManualMappingFileV1 | null | undefined;

function optStr(o: Record<string, unknown>, ...keys: string[]): string | null {
  for (const k of keys) {
    const v = o[k];
    if (typeof v === "string" && v.trim()) return v.trim();
  }
  return null;
}

function readJsonIfExists(abs: string): ManualMappingFileV1 | null {
  if (!fs.existsSync(abs)) return null;
  try {
    const raw = fs.readFileSync(abs, "utf8");
    const p = JSON.parse(raw) as ManualMappingFileV1;
    if (p?.version !== 1) return null;
    if (!p.cacheKeyExact || typeof p.cacheKeyExact !== "object") p.cacheKeyExact = {};
    if (!Array.isArray(p.cacheKeyPatterns)) p.cacheKeyPatterns = [];
    return p;
  } catch {
    return null;
  }
}

/** Default path next to repo root; override with NURSING_METADATA_MAP_PATH. */
export function resolveManualMappingPath(repoRoot: string): string {
  const env = process.env.NURSING_METADATA_MAP_PATH?.trim();
  if (env) return path.isAbsolute(env) ? env : path.resolve(repoRoot, env);
  return path.join(repoRoot, "config", "nursing-export-metadata-mapping.json");
}

export function loadManualMapping(repoRoot: string): ManualMappingFileV1 | null {
  return readJsonIfExists(resolveManualMappingPath(repoRoot));
}

export function loadManualMappingCached(repoRoot: string = process.cwd()): ManualMappingFileV1 | null {
  if (cachedManual !== undefined) return cachedManual;
  cachedManual = loadManualMapping(repoRoot);
  return cachedManual;
}

/** For tests / CLI that reset module state. */
export function clearManualMappingCache(): void {
  cachedManual = undefined;
}

/**
 * High-confidence cache_key → (tier, exam). Order: more specific substrings first.
 * IDs are stable for audit output.
 */
const CACHE_KEY_INFERENCE_RULES: Array<{
  id: string;
  test: (ck: string) => boolean;
  tier: string;
  exam: string;
}> = [
  { id: "infer_nclex_rn", test: (ck) => /nclex[-_]?rn/i.test(ck), tier: "rn", exam: "NCLEX_RN" },
  { id: "infer_nclex_pn", test: (ck) => /nclex[-_]?pn/i.test(ck), tier: "rpn", exam: "NCLEX_PN" },
  {
    id: "infer_rex_pn",
    test: (ck) => /(rex[-_]?pn|rexpn|rex_pn|cpnre)/i.test(ck),
    tier: "rpn",
    exam: "REx-PN",
  },
  { id: "infer_aanp", test: (ck) => /aanp/i.test(ck), tier: "np", exam: "AANP" },
  { id: "infer_ancc", test: (ck) => /\bancc\b/i.test(ck), tier: "np", exam: "ANCC" },
];

function inferFromCacheKey(cacheKey: string | null): { tier: string; exam: string; ruleId: string } | null {
  if (!cacheKey || !cacheKey.trim()) return null;
  const ck = cacheKey;
  for (const r of CACHE_KEY_INFERENCE_RULES) {
    if (r.test(ck)) return { tier: r.tier, exam: r.exam, ruleId: r.id };
  }
  return null;
}

function extractParentMetadata(parent: Record<string, unknown>): {
  tier?: string;
  exam?: string;
  detail: string;
} | null {
  const tierDirect = optStr(parent, "tier");
  const examDirect = optStr(parent, "exam", "exam_type", "examType");
  if (tierDirect && examDirect) {
    return { tier: tierDirect, exam: examDirect, detail: "parent_row_top_level" };
  }

  const metaRaw = parent.metadata ?? parent.extra ?? parent.job_metadata ?? parent.jobMetadata;
  if (metaRaw && typeof metaRaw === "object" && !Array.isArray(metaRaw)) {
    const m = metaRaw as Record<string, unknown>;
    const tier = optStr(m, "tier", "contentTier", "content_tier");
    const exam = optStr(m, "exam", "exam_type", "examType", "examCode", "exam_code");
    if (tier && exam) return { tier, exam, detail: "parent_metadata_object" };
  }

  if (tierDirect || examDirect) {
    return {
      tier: tierDirect ?? undefined,
      exam: examDirect ?? undefined,
      detail: "parent_partial",
    };
  }
  return null;
}

function applyManualMapping(
  cacheKey: string | null,
  manual: ManualMappingFileV1 | null,
): { tier: string; exam: string; key: string } | null {
  if (!manual || !cacheKey) return null;
  const exact = manual.cacheKeyExact[cacheKey];
  if (exact?.tier && exact.exam) return { tier: exact.tier.trim(), exam: exact.exam.trim(), key: `exact:${cacheKey}` };

  for (const p of manual.cacheKeyPatterns) {
    try {
      const re = new RegExp(p.pattern);
      if (re.test(cacheKey) && p.tier && p.exam) {
        return { tier: p.tier.trim(), exam: p.exam.trim(), key: `pattern:${p.pattern}` };
      }
    } catch {
      /* invalid regex in hand-edited file — skip */
    }
  }
  return null;
}

export function enrichNursingExamItemMetadata(
  item: Record<string, unknown>,
  ctx: NursingEnrichmentContext,
  manual: ManualMappingFileV1 | null,
): { merged: Record<string, unknown>; audit: EnrichmentAudit } {
  const inferredRuleIds: string[] = [];
  const ambiguousReasons: string[] = [];

  const origTier = typeof item.tier === "string" && item.tier.trim() ? item.tier.trim() : null;
  const origExam = typeof item.exam === "string" && item.exam.trim() ? item.exam.trim() : null;

  let tier = origTier;
  let exam = origExam;
  let tierSource: MetadataProvenanceSource | null = origTier ? "explicit_item_field" : null;
  let examSource: MetadataProvenanceSource | null = origExam ? "explicit_item_field" : null;
  let tierDetail: string | undefined = origTier ? "item.tier" : undefined;
  let examDetail: string | undefined = origExam ? "item.exam" : undefined;
  let manualMappingKey: string | undefined;

  const merged: Record<string, unknown> = { ...item };

  if (!tier || !exam) {
    const pm = extractParentMetadata(ctx.parentRow);
    if (pm) {
      if (!tier && pm.tier) {
        tier = pm.tier;
        tierSource = "parent_metadata";
        tierDetail = pm.detail;
      }
      if (!exam && pm.exam) {
        exam = pm.exam;
        examSource = "parent_metadata";
        examDetail = pm.detail;
      }
    }
  }

  /** Deterministic cache_key rules before hand-maintained overrides. */
  if (!tier || !exam) {
    const inf = inferFromCacheKey(ctx.cacheKey);
    if (inf) {
      if (!tier) {
        tier = inf.tier;
        tierSource = "inferred_rule";
        tierDetail = `cache_key:${inf.ruleId}`;
        inferredRuleIds.push(inf.ruleId);
      }
      if (!exam) {
        exam = inf.exam;
        examSource = "inferred_rule";
        examDetail = `cache_key:${inf.ruleId}`;
        if (!inferredRuleIds.includes(inf.ruleId)) inferredRuleIds.push(inf.ruleId);
      }
    }
  }

  /** Manual mapping overrides / fills gaps after inference (reviewed file only). */
  if (!tier || !exam) {
    const man = applyManualMapping(ctx.cacheKey, manual);
    if (man) {
      if (!tier) {
        tier = man.tier;
        tierSource = "manual_mapping";
        tierDetail = man.key;
      }
      if (!exam) {
        exam = man.exam;
        examSource = "manual_mapping";
        examDetail = man.key;
      }
      manualMappingKey = man.key;
    }
  }

  /** Optional: export bundle folder name as weak signal — only when single segment matches REx-PN / NCLEX (strict). */
  if (!tier || !exam) {
    const base = path.basename(ctx.exportDirAbs);
    const sub = inferFromCacheKey(base);
    if (sub) {
      if (!tier) {
        tier = sub.tier;
        tierSource = "path_segment";
        tierDetail = `export_dir:${base}:${sub.ruleId}`;
        inferredRuleIds.push(`${sub.ruleId}_path`);
      }
      if (!exam) {
        exam = sub.exam;
        examSource = "path_segment";
        examDetail = `export_dir:${base}:${sub.ruleId}`;
      }
    }
  }

  if (!tier || !exam) {
    const fn = ctx.sourceFileName;
    const sub = inferFromCacheKey(fn);
    if (sub) {
      if (!tier) {
        tier = sub.tier;
        tierSource = "filename";
        tierDetail = `file:${fn}:${sub.ruleId}`;
      }
      if (!exam) {
        exam = sub.exam;
        examSource = "filename";
        examDetail = `file:${fn}:${sub.ruleId}`;
      }
    }
  }

  if (tier) merged.tier = tier;
  if (exam) merged.exam = exam;

  if (!tier) ambiguousReasons.push("missing_tier_after_enrichment");
  if (!exam) ambiguousReasons.push("missing_exam_after_enrichment");
  const ambiguous = Boolean(!tier || !exam);

  const audit: EnrichmentAudit = {
    originalTier: origTier,
    originalExam: origExam,
    mergedTier: tier,
    mergedExam: exam,
    tierSource,
    examSource,
    tierDetail,
    examDetail,
    manualMappingKey,
    inferredRuleIds,
    ambiguous,
    ambiguousReasons,
  };

  return { merged, audit };
}

/** Resolve repo root (cwd for scripts). */
export function defaultRepoRoot(): string {
  return process.cwd();
}
