import fs from "fs";
import path from "path";
import {
  PROJECT_ROOT,
  getTimestamp,
  ensureDir,
  collectFiles,
  writeBackupLog,
  type BackupResult,
} from "./backup-engine";

const DEPLOYMENT_README = `# NurseNest Deployment Recovery Guide

## Overview
This bundle contains everything needed to deploy NurseNest on a new host.

## Prerequisites
- Node.js 20+
- PostgreSQL 15+
- A Stripe account (for payments)
- An OpenAI API key (for AI features)

## Step-by-Step Recovery

### 1. Install Dependencies
\`\`\`bash
npm install
\`\`\`

### 2. Environment Variables
Copy \`.env.example\` to \`.env\` and fill in all required values:
\`\`\`bash
cp .env.example .env
\`\`\`

Key variables:
- \`DATABASE_URL\` - PostgreSQL connection string
- \`STRIPE_SECRET_KEY\` / \`STRIPE_PUBLISHABLE_KEY\` - Stripe credentials
- \`OPENAI_API_KEY\` - OpenAI API key
- \`SESSION_SECRET\` - Random string for session encryption

See \`config/env-schema.json\` for full documentation of each variable.

### 3. Database Setup
Run migrations:
\`\`\`bash
npx drizzle-kit push
\`\`\`

Or apply SQL files manually:
\`\`\`bash
psql $DATABASE_URL < migrations/0000_numerous_marvex.sql
psql $DATABASE_URL < migrations/0001_add_clinical_pearl.sql
psql $DATABASE_URL < migrations/0002_adaptive_engine_upgrade.sql
psql $DATABASE_URL < migrations/0003_fix_schema_drift.sql
psql $DATABASE_URL < migrations/0004_readiness_engine.sql
\`\`\`

### 4. Seed Data (if available)
If you have content backup JSON files, import them:
\`\`\`bash
# Content items, exam questions, flashcards etc. can be imported
# from the backups/content/ directory
\`\`\`

### 5. Build
\`\`\`bash
npm run build
\`\`\`

### 6. Start
\`\`\`bash
npm run start
\`\`\`

The app will be available on port 5000.

### 7. Verify Deployment

#### Authentication
- Create an admin account and verify login works
- Check session persistence across page reloads

#### Payments (Stripe)
- Verify Stripe webhook endpoint is configured
- Test a subscription flow with Stripe test keys
- Confirm pricing plans load correctly

#### Translations
- Check that translation files load for supported locales
- Verify language switcher functions correctly

#### Content
- Verify lessons, question banks, and flashcards load
- Check that exam simulations work
- Test the AI tutor if OpenAI key is configured

#### SEO
- Confirm sitemap.xml is served
- Verify robots.txt is correct
- Check meta tags render on key pages

### 8. Asset Restoration
Upload any backed-up assets to your object storage provider.
Configure \`PUBLIC_OBJECT_SEARCH_PATHS\` to point to the new storage.

## Troubleshooting
- If DB migrations fail, check your PostgreSQL version (15+ required)
- If Stripe errors occur, verify webhook signing secret
- For AI feature errors, check OPENAI_API_KEY and model availability
- For session issues, ensure SESSION_SECRET is set

## Support
This deployment bundle was generated by NurseNest Backup System v1.0.0.
`;

async function runDeploymentExport() {
  const startTime = Date.now();
  const timestamp = getTimestamp();
  const exportDir = path.join(PROJECT_ROOT, "exports", "deployment-ready");
  ensureDir(exportDir);

  console.log(`[EXPORT:DEPLOYMENT] Starting deployment export at ${timestamp}`);

  const warnings: string[] = [];
  const errors: string[] = [];
  let fileCount = 0;

  try {
    fs.writeFileSync(path.join(exportDir, "DEPLOYMENT_README.md"), DEPLOYMENT_README);
    fileCount++;

    const essentialFiles = [
      "package.json",
      "tsconfig.json",
      "vite.config.ts",
      "drizzle.config.ts",
      "postcss.config.js",
      ".env.example",
    ];

    for (const f of essentialFiles) {
      const src = path.join(PROJECT_ROOT, f);
      if (fs.existsSync(src)) {
        fs.copyFileSync(src, path.join(exportDir, f));
        fileCount++;
      } else {
        warnings.push(`Missing: ${f}`);
      }
    }

    const migDir = path.join(exportDir, "migrations");
    ensureDir(migDir);
    const srcMigDir = path.join(PROJECT_ROOT, "migrations");
    if (fs.existsSync(srcMigDir)) {
      const migFiles = fs.readdirSync(srcMigDir).filter((f) => f.endsWith(".sql"));
      for (const f of migFiles) {
        fs.copyFileSync(path.join(srcMigDir, f), path.join(migDir, f));
        fileCount++;
      }
    }

    const schemaFile = path.join(PROJECT_ROOT, "shared", "schema.ts");
    if (fs.existsSync(schemaFile)) {
      const schemaDir = path.join(exportDir, "shared");
      ensureDir(schemaDir);
      fs.copyFileSync(schemaFile, path.join(schemaDir, "schema.ts"));
      fileCount++;
    }

    if (fs.existsSync(path.join(PROJECT_ROOT, "config", "env-schema.json"))) {
      const cfgDir = path.join(exportDir, "config");
      ensureDir(cfgDir);
      fs.copyFileSync(
        path.join(PROJECT_ROOT, "config", "env-schema.json"),
        path.join(cfgDir, "env-schema.json")
      );
      fileCount++;
    }

    fs.writeFileSync(path.join(exportDir, "export-metadata.json"), JSON.stringify({
      type: "deployment-ready",
      timestamp,
      createdAt: new Date().toISOString(),
      version: "1.0.0",
      fileCount,
    }, null, 2));
    fileCount++;

    const exportsLogDir = path.join(PROJECT_ROOT, "exports", "logs");
    ensureDir(exportsLogDir);

    const result: BackupResult = {
      timestamp,
      type: "deployment-export",
      status: "success",
      fileCount,
      archiveSize: 0,
      archivePath: exportDir,
      validationResult: "pass",
      warnings,
      errors,
      duration: Date.now() - startTime,
    };

    writeBackupLog(result);

    fs.writeFileSync(
      path.join(exportsLogDir, `deployment-export-${timestamp}.json`),
      JSON.stringify(result, null, 2)
    );

    console.log(`[EXPORT:DEPLOYMENT] Complete!`);
    console.log(`  Files: ${fileCount}`);
    console.log(`  Output: ${exportDir}`);
    return result;
  } catch (e: any) {
    errors.push(e.message);
    console.error(`[EXPORT:DEPLOYMENT] Failed: ${e.message}`);
    return null;
  }
}

runDeploymentExport().then(result => {
  if (!result) process.exit(1);
}).catch(e => {
  console.error(e);
  process.exit(1);
});
