import fs from "node:fs";
import path from "node:path";
import ts from "typescript";
import { QUESTION_SOURCE_QUARANTINE_PATHS } from "../client/src/data/exam-questions/question-quarantine";

const ROOTS=["client/src/data/exam-questions","client/src/data/career-questions","client/src/data/newgrad/scenario-questions","client/src/pages/international-nurses"];
type Family="explicit-v2"|"structured-bank-question"|"advanced-structured"|"legacy-flat-with-rationale"|"question-like-other";
type Row={id:string;file:string;line:number;family:Family;tier:string;questionType:string};
function rel(file:string){return file.split(path.sep).join("/");}
function unwrap(n:ts.Expression):ts.Expression{while(ts.isAsExpression(n)||ts.isTypeAssertionExpression(n)||ts.isParenthesizedExpression(n)||ts.isNonNullExpression(n))n=n.expression;return n;}
function propName(p:ts.ObjectLiteralElementLike):string|null{return ts.isPropertyAssignment(p)&&(ts.isIdentifier(p.name)||ts.isStringLiteralLike(p.name))?p.name.text:null;}
function getProp(n:ts.ObjectLiteralExpression,k:string):ts.Expression|null{for(const p of n.properties)if(propName(p)===k&&ts.isPropertyAssignment(p))return p.initializer;return null;}
function literalString(n:ts.Expression|null):string{if(!n)return"";n=unwrap(n);return ts.isStringLiteralLike(n)?n.text.trim():"";}
function hasArray(n:ts.Expression|null):boolean{if(!n)return false;n=unwrap(n);return ts.isArrayLiteralExpression(n)&&n.elements.length>0;}
function hasObject(n:ts.Expression|null):boolean{if(!n)return false;n=unwrap(n);return ts.isObjectLiteralExpression(n)&&n.properties.length>0;}
function collectFiles(root:string):string[]{if(!fs.existsSync(root))return[];const out:string[]=[];const walk=(d:string)=>{for(const e of fs.readdirSync(d,{withFileTypes:true})){const f=path.join(d,e.name);if(e.isDirectory())walk(f);else if(/\.(ts|tsx)$/.test(e.name)&&!/\.test\.|\.spec\./.test(e.name)&&!e.name.includes("question-contract-enrichment")&&!QUESTION_SOURCE_QUARANTINE_PATHS.has(rel(f)))out.push(f);}};walk(root);return out;}
function familyFor(n:ts.ObjectLiteralExpression):Family|null{const stem=literalString(getProp(n,"stem"))||literalString(getProp(n,"question"))||literalString(getProp(n,"questionText"));const rationale=literalString(getProp(n,"rationale"))||literalString(getProp(n,"rationaleCorrect"))||literalString(getProp(n,"rationale_correct"))||literalString(getProp(n,"overallRationale"));const flatOptions=getProp(n,"options")||getProp(n,"answerOptions");const structured=hasArray(getProp(n,"rows"))||hasArray(getProp(n,"timepoints"))||hasArray(getProp(n,"questions"))||hasArray(getProp(n,"items"))||hasArray(getProp(n,"highlightSpans"))||hasArray(getProp(n,"centerOptions"));if(!stem&&!rationale&&!flatOptions&&!structured)return null;const explicitCorrect=literalString(getProp(n,"correctAnswerExplanation"))||literalString(getProp(n,"correct_answer_explanation"));const explicitHint=literalString(getProp(n,"hint"))||literalString(getProp(n,"examStrategy"));const explicitWhy=literalString(getProp(n,"whyThisMatters"))||literalString(getProp(n,"keyTakeaway"));const explicitPearl=literalString(getProp(n,"clinicalPearl"))||literalString(getProp(n,"examPearl"));const explicitDistractors=hasObject(getProp(n,"distractorRationales"))||hasObject(getProp(n,"distractor_rationales"));if(explicitCorrect&&explicitHint&&explicitWhy&&explicitPearl&&(explicitDistractors||literalString(getProp(n,"questionType"))==="ORDERED_RESPONSE"))return"explicit-v2";const rationaleCorrect=literalString(getProp(n,"rationaleCorrect"))||literalString(getProp(n,"rationale_correct"));const clinicalCorrelation=literalString(getProp(n,"clinicalCorrelation"))||literalString(getProp(n,"clinical_correlation"));if(rationaleCorrect&&clinicalCorrelation&&(hasArray(getProp(n,"rationaleIncorrect"))||hasArray(getProp(n,"rationale_incorrect"))))return"structured-bank-question";if(structured)return"advanced-structured";if(stem&&rationale&&flatOptions)return"legacy-flat-with-rationale";return"question-like-other";}
const rows:Row[]=[];for(const file of ROOTS.flatMap(collectFiles)){const source=fs.readFileSync(file,"utf8"),sf=ts.createSourceFile(file,source,ts.ScriptTarget.Latest,true,file.endsWith(".tsx")?ts.ScriptKind.TSX:ts.ScriptKind.TS);let ordinal=0;const visit=(n:ts.Node)=>{if(ts.isObjectLiteralExpression(n)){ordinal++;const family=familyFor(n);if(family){const id=literalString(getProp(n,"id"))||literalString(getProp(n,"questionId"))||`source-${path.basename(file,path.extname(file))}-${ordinal}`;const tier=literalString(getProp(n,"tier"))||literalString(getProp(n,"servingTier"))||"allied";const questionType=literalString(getProp(n,"questionType"))||literalString(getProp(n,"question_type"))||literalString(getProp(n,"type"))||"unknown";const lc=sf.getLineAndCharacterOfPosition(n.getStart(sf));rows.push({id,file:rel(file),line:lc.line+1,family,tier,questionType});}}ts.forEachChild(n,visit);};visit(sf);}
const byFamily:Record<string,number>={},byTier:Record<string,Record<string,number>>={},byFile:Record<string,Record<string,number>>={};for(const row of rows){byFamily[row.family]=(byFamily[row.family]||0)+1;byTier[row.tier]||={};byTier[row.tier][row.family]=(byTier[row.tier][row.family]||0)+1;byFile[row.file]||={};byFile[row.file][row.family]=(byFile[row.file][row.family]||0)+1;}
const files=Object.entries(byFile).map(([file,families])=>({file,total:Object.values(families).reduce((a,b)=>a+b,0),families})).sort((a,b)=>b.total-a.total);
console.log(JSON.stringify({totalObjects:rows.length,quarantinedFilesExcluded:QUESTION_SOURCE_QUARANTINE_PATHS.size,byFamily,byTier,largestFiles:files.slice(0,100)},null,2));
