import fs from "node:fs";
import path from "node:path";
import ts from "typescript";
import { QUESTION_SOURCE_QUARANTINE_PATHS } from "../client/src/data/exam-questions/question-quarantine";

const ROOTS=["client/src/data/exam-questions","client/src/data/career-questions","client/src/data/newgrad/scenario-questions","client/src/pages/international-nurses"];
const OVERLAYS=[path.resolve("client/src/data/question-contract-enrichment.generated.ts"),path.resolve("client/src/data/question-contract-enrichment.curated.ts")];
type Row={id:string;file:string;line:number;tier:string;hasAuthoredInline:boolean;fingerprint:string};
function rel(file:string){return file.split(path.sep).join("/");}
function text(v:unknown):string{return typeof v==="string"?v.trim():"";}
function norm(v:string):string{return v.toLowerCase().replace(/\s+/g," ").replace(/[.!?,;:]+$/g,"").trim();}
function propName(p:ts.ObjectLiteralElementLike):string|null{return ts.isPropertyAssignment(p)&&(ts.isIdentifier(p.name)||ts.isStringLiteralLike(p.name))?p.name.text:null;}
function getProp(n:ts.ObjectLiteralExpression,name:string):ts.Expression|null{for(const p of n.properties)if(propName(p)===name&&ts.isPropertyAssignment(p))return p.initializer;return null;}
function unwrap(n:ts.Expression):ts.Expression{while(ts.isAsExpression(n)||ts.isTypeAssertionExpression(n)||ts.isParenthesizedExpression(n)||ts.isNonNullExpression(n))n=n.expression;return n;}
function literalString(n:ts.Expression|null):string{if(!n)return"";n=unwrap(n);return ts.isStringLiteralLike(n)?n.text.trim():"";}
function optionTexts(n:ts.Expression|null):string[]{if(!n)return[];n=unwrap(n);if(!ts.isArrayLiteralExpression(n))return[];return n.elements.map(e=>{if(!ts.isExpression(e))return"";const x=unwrap(e);if(ts.isStringLiteralLike(x))return x.text.trim();if(ts.isObjectLiteralExpression(x))return literalString(getProp(x,"text"))||literalString(getProp(x,"content"))||literalString(getProp(x,"value"))||literalString(getProp(x,"label"));return"";}).filter(Boolean);}
function hasNonEmptyObject(n:ts.Expression|null):boolean{if(!n)return false;n=unwrap(n);return ts.isObjectLiteralExpression(n)&&n.properties.length>0;}
function hasNonEmptyArray(n:ts.Expression|null):boolean{if(!n)return false;n=unwrap(n);return ts.isArrayLiteralExpression(n)&&n.elements.length>0;}
function collectFiles(root:string):string[]{if(!fs.existsSync(root))return[];const out:string[]=[];const walk=(dir:string)=>{for(const e of fs.readdirSync(dir,{withFileTypes:true})){const f=path.join(dir,e.name);if(e.isDirectory())walk(f);else if(/\.(ts|tsx)$/.test(e.name)&&!/\.test\.|\.spec\./.test(e.name)&&!e.name.includes("question-contract-enrichment")&&!QUESTION_SOURCE_QUARANTINE_PATHS.has(rel(f)))out.push(f);}};walk(root);return out;}
function scan():Row[]{const rows:Row[]=[];for(const file of ROOTS.flatMap(collectFiles)){const source=fs.readFileSync(file,"utf8"),sf=ts.createSourceFile(file,source,ts.ScriptTarget.Latest,true,file.endsWith(".tsx")?ts.ScriptKind.TSX:ts.ScriptKind.TS);let ordinal=0;const visit=(node:ts.Node)=>{if(ts.isObjectLiteralExpression(node)){ordinal++;const stem=literalString(getProp(node,"stem"))||literalString(getProp(node,"question"))||literalString(getProp(node,"questionText"));const rationale=literalString(getProp(node,"rationale"))||literalString(getProp(node,"rationaleCorrect"))||literalString(getProp(node,"rationale_correct"));const optionNode=getProp(node,"options")||getProp(node,"answerOptions");const optionList=optionTexts(optionNode);if(stem&&rationale&&optionNode&&optionList.length>=2){const explicit=literalString(getProp(node,"id"))||literalString(getProp(node,"questionId"));const id=explicit||`source-${path.basename(file,path.extname(file)).toLowerCase().replace(/[^a-z0-9]+/g,"-")}-${String(ordinal).padStart(6,"0")}`;const rationaleCorrect=literalString(getProp(node,"rationaleCorrect"))||literalString(getProp(node,"rationale_correct"));const inlineCorrect=literalString(getProp(node,"correctAnswerExplanation"))||literalString(getProp(node,"correct_answer_explanation"))||rationaleCorrect;const inlineHint=literalString(getProp(node,"hint"))||literalString(getProp(node,"examStrategy"));const clinicalCorrelation=literalString(getProp(node,"clinicalCorrelation"))||literalString(getProp(node,"clinical_correlation"));const inlineWhy=literalString(getProp(node,"whyThisMatters"))||literalString(getProp(node,"keyTakeaway"))||clinicalCorrelation;const inlinePearl=literalString(getProp(node,"clinicalPearl"))||literalString(getProp(node,"examPearl"))||rationaleCorrect;const inlineDistractors=hasNonEmptyObject(getProp(node,"distractorRationales"))||hasNonEmptyObject(getProp(node,"distractor_rationales"));const structuredDistractors=hasNonEmptyArray(getProp(node,"rationaleIncorrect"))||hasNonEmptyArray(getProp(node,"rationale_incorrect"));const structuredSourceAuthored=!!rationaleCorrect&&!!clinicalCorrelation&&structuredDistractors;const qtype=literalString(getProp(node,"questionType"))||literalString(getProp(node,"question_type"))||literalString(getProp(node,"type"))||"MCQ";const tier=literalString(getProp(node,"tier"))||literalString(getProp(node,"servingTier"))||"allied";const fingerprint=`${norm(tier)}::${norm(qtype)}::${norm(stem)}::${optionList.map(norm).join("||")}`;const lc=sf.getLineAndCharacterOfPosition(node.getStart(sf));const explicitV2=!!inlineCorrect&&!!inlineHint&&!!inlineWhy&&!!inlinePearl&&inlineDistractors;rows.push({id,file:rel(file),line:lc.line+1,tier,fingerprint,hasAuthoredInline:explicitV2||structuredSourceAuthored});}}ts.forEachChild(node,visit);};visit(sf);}return rows;}
function overlayIds(){const authored=new Set<string>(),needsReview=new Set<string>();for(const overlayPath of OVERLAYS){if(!fs.existsSync(overlayPath))continue;const source=fs.readFileSync(overlayPath,"utf8"),sf=ts.createSourceFile(overlayPath,source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TS);const visit=(node:ts.Node)=>{if(ts.isPropertyAssignment(node)&&(ts.isStringLiteralLike(node.name)||ts.isIdentifier(node.name))&&ts.isObjectLiteralExpression(node.initializer)){const id=node.name.text,status=literalString(getProp(node.initializer,"editorialStatus"));if(status==="authored-v2")authored.add(id);if(status==="needs-review")needsReview.add(id);}ts.forEachChild(node,visit);};visit(sf);}return{authored,needsReview};}
const rows=scan(),overlay=overlayIds(),byFingerprint=new Map<string,Row>();for(const row of rows)if(!byFingerprint.has(row.fingerprint))byFingerprint.set(row.fingerprint,row);const active=[...byFingerprint.values()],duplicateSourceObjectsExcluded=rows.length-active.length,complete=active.filter(r=>r.hasAuthoredInline||overlay.authored.has(r.id)),missing=active.filter(r=>!r.hasAuthoredInline&&!overlay.authored.has(r.id)),needsReview=active.filter(r=>overlay.needsReview.has(r.id));
const byTier:Record<string,{total:number;authoredV2:number;missing:number}>={};for(const row of active){byTier[row.tier]||={total:0,authoredV2:0,missing:0};byTier[row.tier].total++;if(row.hasAuthoredInline||overlay.authored.has(row.id))byTier[row.tier].authoredV2++;else byTier[row.tier].missing++;}
const result={sourceQuestionObjects:rows.length,canonicalUniqueLearnerQuestions:active.length,duplicateSourceObjectsExcluded,quarantinedFilesExcluded:QUESTION_SOURCE_QUARANTINE_PATHS.size,authoredV2:complete.length,missingAuthoredV2:missing.length,needsReview:needsReview.length,coveragePercent:active.length?Math.round((complete.length/active.length)*10000)/100:100,byTier,sampleMissing:missing.slice(0,200),sampleNeedsReview:needsReview.slice(0,200)};
console.log(JSON.stringify(result,null,2));if(missing.length||needsReview.length)process.exitCode=2;
