import OpenAI from "openai";
import { createHash } from "node:crypto";
import { pool } from "../server/storage";
import { auditQuestionPublicationContract } from "../server/question-publication-contract";
import { canonicalQuestionType, usesFlatOptions } from "../server/question-interaction-contract";
import { resolveExamJurisdiction } from "../shared/question-jurisdictions";

type Row=Record<string,any>; type Columns=Set<string>;
type Store={table:string;columns:Columns;id:string;stem:string;answer?:string;type?:string;payload?:string};
type Option={id:string;text:string;label:string};

const APPLY=process.argv.includes("--apply"); const AI=process.argv.includes("--ai");
const LIMIT=Number(process.argv.find(a=>a.startsWith("--limit="))?.split("=")[1]||0)||Number.POSITIVE_INFINITY;
const TABLE_ONLY=process.argv.find(a=>a.startsWith("--table="))?.split("=")[1]||null;
function qi(v:string){return `"${v.replace(/"/g,'""')}"`;}
function text(v:unknown){return typeof v==="string"?v.trim():"";} function parse(v:unknown):any{if(typeof v!=="string")return v;try{return JSON.parse(v);}catch{return v;}}
function first(c:Columns,names:string[]){return names.find(n=>c.has(n));} function slug(v:string){return v.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,90);}
function stableId(scope:string,kind:string,index:number,label:string){const h=createHash("sha1").update(label.trim().toLowerCase()).digest("hex").slice(0,10);return `${slug(scope)||"q"}:${kind}:${String(index+1).padStart(2,"0")}:${h}`;}

async function discover():Promise<Store[]>{
  const tables=await pool.query(`SELECT table_name FROM information_schema.tables WHERE table_schema='public' AND table_type='BASE TABLE' AND (table_name='exam_questions' OR table_name LIKE '%question%') ORDER BY table_name`); const out:Store[]=[];
  for(const t of tables.rows){if(TABLE_ONLY&&t.table_name!==TABLE_ONLY)continue;const cr=await pool.query(`SELECT column_name FROM information_schema.columns WHERE table_schema='public' AND table_name=$1`,[t.table_name]);const c=new Set<string>(cr.rows.map((r:any)=>r.column_name));
    if(!c.has("contract_question_id")||!c.has("contract_interaction_payload"))continue;const id=first(c,["id","question_id","blueprint_id"]);const stem=first(c,["stem","question","question_text"]);if(!id||!stem)continue;
    out.push({table:t.table_name,columns:c,id,stem,answer:first(c,["correct_answer","correct_index","answer_key","correct"]),type:first(c,["question_type","question_format","type"]),payload:first(c,["ngn_payload","interaction_payload","exhibit_data","payload"])});
  }return out;
}

function legacyOptions(row:Row,s:Store,qid:string):Option[]{
  const existing=parse(row.contract_options);if(Array.isArray(existing)&&existing.length&&existing.every((o:any)=>text(o?.id)&&text(o?.text)))return existing.map((o:any,i:number)=>({id:text(o.id),text:text(o.text),label:text(o.label)||String.fromCharCode(65+i)}));
  const col=first(s.columns,["options","answer_options","choices"]);let raw:any[]=[];if(col){const p=parse(row[col]);if(Array.isArray(p))raw=p;}else raw=["option_a","option_b","option_c","option_d","option_e","option_f"].filter(k=>s.columns.has(k)&&text(row[k])).map(k=>row[k]);
  return raw.map((o:any,i:number)=>{const label=String.fromCharCode(65+i);if(o&&typeof o==="object"){const t=text(o.text)||text(o.content)||text(o.value)||text(o.label);return{id:text(o.id)||text(o.optionId)||text(o.option_id)||stableId(qid,"opt",i,t),text:t,label:text(o.label)||label};}const t=String(o??"").trim();return{id:stableId(qid,"opt",i,t),text:t,label};}).filter(o=>o.text);
}
function flatten(v:any):any[]{const p=parse(v);if(Array.isArray(p))return p.flatMap(flatten);if(p&&typeof p==="object"){for(const k of["ids","answers","selected","correct","answer","id","value","index"])if(k in p)return flatten(p[k]);}return[p];}
function answerIds(raw:any,options:Option[]):string[]{const out:string[]=[];for(const v of flatten(raw)){if(v==null)continue;if(typeof v==="number"&&Number.isInteger(v)){const o=options[v]||(v>0?options[v-1]:undefined);if(o)out.push(o.id);continue;}const n=String(v).trim();const o=options.find(x=>x.id.toLowerCase()===n.toLowerCase())||options.find(x=>x.label.toLowerCase()===n.toLowerCase())||options.find(x=>x.text.toLowerCase()===n.toLowerCase());if(o)out.push(o.id);}return[...new Set(out)];}
function distractors(raw:any,options:Option[],correct:Set<string>):Record<string,string>{const p=parse(raw);const src=p&&typeof p==="object"&&!Array.isArray(p)?p:{};const out:Record<string,string>={};for(const[k,v]of Object.entries(src)){const r=text(v);if(!r)continue;const num=Number(k);const o=options.find(x=>x.id.toLowerCase()===k.toLowerCase())||options.find(x=>x.label.toLowerCase()===k.toLowerCase())||(Number.isInteger(num)?options[num]||(num>0?options[num-1]:undefined):undefined)||options.find(x=>x.text.toLowerCase()===k.toLowerCase());if(o&&!correct.has(o.id))out[o.id]=r;}return out;}
function alias(row:Row,s:Store,names:string[]):any{const k=first(s.columns,names);return k?row[k]:undefined;} function tags(row:Row,s:Store){const v=parse(alias(row,s,["tags"]));if(Array.isArray(v))return v.filter(Boolean);if(typeof v==="string")return v.split(/[,|]/).map(x=>x.trim()).filter(Boolean);return[];}

function addIdsToChoiceArray(raw:any,scope:string,kind:string):any[]{const arr=parse(raw);if(!Array.isArray(arr))return[];return arr.map((item:any,i:number)=>{if(item&&typeof item==="object"){const label=text(item.text)||text(item.label)||text(item.content)||text(item.value)||text(item.name)||`${kind}-${i+1}`;return{...item,id:text(item.id)||text(item.optionId)||text(item.option_id)||text(item.choiceId)||stableId(scope,kind,i,label)};}const label=String(item??"").trim();return{id:stableId(scope,kind,i,label),text:label,label:String.fromCharCode(65+i)};});}
function structuredPayload(row:Row,s:Store,qid:string,type:string):any{
  const existing=parse(row.contract_interaction_payload);let p=existing&&typeof existing==="object"&&!Array.isArray(existing)&&Object.keys(existing).length?structuredClone(existing):parse(s.payload?row[s.payload]:alias(row,s,["ngn_payload","exhibit_data","payload","interaction_payload"]));
  if(!p||typeof p!=="object"||Array.isArray(p))p={};const ct=canonicalQuestionType(type);
  if(ct==="BOWTIE"){p.conditionOptions=addIdsToChoiceArray(p.conditionOptions??p.condition_options,qid,"condition");p.actionOptions=addIdsToChoiceArray(p.actionOptions??p.action_options,qid,"action");p.monitorOptions=addIdsToChoiceArray(p.monitorOptions??p.monitor_options,qid,"monitor");}
  if(ct==="MATRIX"){p.rows=addIdsToChoiceArray(p.rows,qid,"row");p.columns=addIdsToChoiceArray(p.columns,qid,"column");}
  if(ct==="CLOZE"){const blanks=parse(p.blanks??p.dropdowns);if(Array.isArray(blanks))p.blanks=blanks.map((b:any,i:number)=>{const id=text(b?.id)||stableId(qid,"blank",i,text(b?.label)||`blank-${i+1}`);return{...b,id,options:addIdsToChoiceArray(b?.options??b?.choices??b?.items,`${qid}:${id}`,"choice")};});}
  if(ct==="TREND"){const pts=parse(p.timepoints??p.timePoints??p.timeline);if(Array.isArray(pts))p.timepoints=pts.map((pt:any,i:number)=>({...pt,id:text(pt?.id)||stableId(qid,"timepoint",i,text(pt?.timestamp)||text(pt?.time)||`time-${i+1}`)}));}
  if(ct==="NGN_CASE"){const tabs=parse(p.tabs??p.exhibits);if(Array.isArray(tabs))p.tabs=tabs.map((t:any,i:number)=>({...t,id:text(t?.id)||stableId(qid,"tab",i,text(t?.title)||text(t?.label)||`tab-${i+1}`)}));const subs=parse(p.subQuestions??p.sub_questions??p.questions);if(Array.isArray(subs))p.subQuestions=subs.map((q:any,i:number)=>({...q,id:text(q?.id)||stableId(qid,"subq",i,text(q?.stem)||text(q?.question)||`subquestion-${i+1}`)}));}
  if(ct==="CHART_REVIEW"||ct==="ORDER_REVIEW"){const choices=p.choices??p.options??p.responses;if(choices)p.choices=addIdsToChoiceArray(choices,qid,"choice");}
  return p;
}
function countryMeta(row:Row,s:Store,exam:string){const explicit=text(row.contract_country_code)||text(alias(row,s,["country_code","country"]));const region=text(row.contract_region_scope)||text(alias(row,s,["region_scope","region_code","country_track"]));if(explicit)return{country:explicit.toUpperCase(),region};if(["CAN","CA"].includes(region.toUpperCase()))return{country:"CA",region:"CAN"};if(["US","USA"].includes(region.toUpperCase()))return{country:"US",region:"US"};const resolved=resolveExamJurisdiction(exam);if(resolved?.countryCode)return{country:resolved.countryCode,region:resolved.countryCode==="CA"?"CAN":resolved.countryCode,licensing:resolved.licensingBody};if(resolved?.global)return{country:"",region:"GLOBAL",licensing:resolved.licensingBody};return{country:"",region};}
function issueStatus(issues:any[]){return issues.some(i=>i.severity==="blocking")?"blocked":issues.length?"quality_only":"verified";}
function build(row:Row,s:Store){
  const id=text(row.contract_question_id)||`${s.table}:${String(row[s.id])}`;const rawType=text(alias(row,s,["question_type","question_format","type"]))||"MCQ";const ct=canonicalQuestionType(rawType);const flat=usesFlatOptions(ct);const options=flat?legacyOptions(row,s,id):[];
  const existingCorrect=parse(row.contract_correct_answer_ids);const correct=flat?answerIds(Array.isArray(existingCorrect)&&existingCorrect.length?existingCorrect:(s.answer?row[s.answer]:undefined),options):[];const drCol=first(s.columns,["distractor_rationales","incorrect_answer_rationale"]);const dr=flat?distractors(parse(row.contract_distractor_rationales)&&Object.keys(parse(row.contract_distractor_rationales)).length?row.contract_distractor_rationales:(drCol?row[drCol]:{}),options,new Set(correct)):{};
  const exam=text(alias(row,s,["exam","exam_tag","exam_type"]))||"";const cm=countryMeta(row,s,exam);const payload=flat?{}:structuredPayload(row,s,id,rawType);
  return{id,tier:text(alias(row,s,["tier","serving_tier"])),exam,question_type:rawType,stem:row[s.stem],options,correct_answer:correct,interactionPayload:payload,rationale:text(row.contract_rationale)||text(alias(row,s,["rationale","rationale_long","rationale_correct"])),distractor_rationales:dr,correct_answer_explanation:text(row.contract_correct_answer_explanation)||text(alias(row,s,["correct_answer_explanation","learning_objective"])),hint:text(row.contract_hint)||text(alias(row,s,["hint","exam_strategy"])),why_this_matters:text(row.contract_why_this_matters)||text(alias(row,s,["why_this_matters","key_takeaway","clinical_reasoning"])),clinical_pearl:text(row.contract_clinical_pearl)||text(alias(row,s,["clinical_pearl","exam_pearl","clinical_takeaway"])),mnemonic:text(row.contract_mnemonic)||text(alias(row,s,["mnemonic","memory_hook"])),country_code:cm.country,region_scope:cm.region,language_code:text(row.contract_language_code)||text(alias(row,s,["language_code","locale"]))||"en",licensing_body:text(row.contract_licensing_body)||text(alias(row,s,["licensing_body","regulatory_body"]))||cm.licensing||"",unit_system_support:parse(row.contract_unit_system_support)||parse(alias(row,s,["unit_system_support","lab_unit_variant"]))||{},unit_variants:parse(row.contract_unit_variants)||[],body_system:text(alias(row,s,["body_system","category","blueprint_category"])),topic:text(alias(row,s,["topic","subtopic"])),tags:tags(row,s),difficulty:Number(alias(row,s,["difficulty"]))};
}
function parseModel(raw:string){const m=raw.trim().replace(/^```json\s*/i,"").replace(/```$/i,"").match(/\{[\s\S]*\}/);if(!m)throw new Error("AI did not return JSON");return JSON.parse(m[0]);}
async function aiRepair(openai:OpenAI,q:any,issues:any[]){const prompt=`Repair only missing educational metadata for one existing exam question. Never change stable IDs, stem, option text, keyed answer, interaction structure, exam, tier, country, or difficulty. Return JSON only. Question=${JSON.stringify(q)} Issues=${issues.map(i=>i.code).join(",")}. Allowed: rationale, correct_answer_explanation, distractor_rationales keyed by stable option IDs, hint, why_this_matters, clinical_pearl, mnemonic, unit_system_support, unit_variants. For structured NGN items preserve interactionPayload. Never invent a mnemonic if no useful one exists.`;const r=await openai.chat.completions.create({model:process.env.QUESTION_REPAIR_MODEL||"gpt-4o-mini",temperature:.2,max_tokens:1800,messages:[{role:"user",content:prompt}]});return parseModel(r.choices[0]?.message?.content||"");}
async function write(s:Store,row:Row,q:any,issues:any[]){await pool.query(`UPDATE ${qi(s.table)} SET contract_question_id=$1,contract_options=$2::jsonb,contract_correct_answer_ids=$3::jsonb,contract_interaction_payload=$4::jsonb,contract_distractor_rationales=$5::jsonb,contract_rationale=$6,contract_correct_answer_explanation=$7,contract_hint=$8,contract_why_this_matters=$9,contract_clinical_pearl=$10,contract_mnemonic=$11,contract_country_code=$12,contract_region_scope=$13,contract_language_code=$14,contract_licensing_body=$15,contract_unit_system_support=$16::jsonb,contract_unit_variants=$17::jsonb,option_contract_version=2,publication_contract_version=2,contract_status=$18,contract_issues=$19::jsonb,contract_verified_at=NOW() WHERE ${qi(s.id)}=$20`,[q.id,JSON.stringify(q.options||[]),JSON.stringify(q.correct_answer||[]),JSON.stringify(q.interactionPayload||{}),JSON.stringify(q.distractor_rationales||{}),q.rationale||null,q.correct_answer_explanation||null,q.hint||null,q.why_this_matters||null,q.clinical_pearl||null,q.mnemonic||null,q.country_code||null,q.region_scope||null,q.language_code||"en",q.licensing_body||null,JSON.stringify(q.unit_system_support||{}),JSON.stringify(q.unit_variants||[]),issueStatus(issues),JSON.stringify(issues),row[s.id]]);}

async function main(){const stores=await discover();const apiKey=process.env.AI_INTEGRATIONS_OPENAI_API_KEY||process.env.OPENAI_API_KEY;const baseURL=process.env.AI_INTEGRATIONS_OPENAI_BASE_URL;const openai=AI&&apiKey?new OpenAI({apiKey,...(baseURL?{baseURL}:{})}):null;let remaining=LIMIT;const report:any={version:3,mode:APPLY?(AI?"apply+ai":"apply"):"audit",stores:{},totals:{rows:0,verified:0,blocked:0,qualityOnly:0,updated:0}};
  for(const s of stores){if(remaining<=0)break;const rr=await pool.query(`SELECT * FROM ${qi(s.table)} ORDER BY ${qi(s.id)} LIMIT $1`,[Number.isFinite(remaining)?remaining:1000000]);const stat:any={rows:0,verified:0,blocked:0,qualityOnly:0,updated:0,issues:{}};
    for(const row of rr.rows){if(remaining--<=0)break;stat.rows++;report.totals.rows++;let q=build(row,s);let issues=auditQuestionPublicationContract(q);if(!q.tier)issues.push({code:"missing_tier",field:"tier",severity:"blocking",detail:"Serving tier is required."});
      if(openai&&issues.some((i:any)=>["missing_rationale","missing_distractor_rationale","missing_correct_answer_explanation","missing_hint","missing_why_this_matters","missing_clinical_pearl","missing_si_conv_support","missing_unit_variants","invalid_unit_conversion"].includes(i.code))){try{const p=await aiRepair(openai,q,issues);q={...q,rationale:q.rationale||p.rationale,correct_answer_explanation:q.correct_answer_explanation||p.correct_answer_explanation,distractor_rationales:{...(q.distractor_rationales||{}),...(p.distractor_rationales||{})},hint:q.hint||p.hint,why_this_matters:q.why_this_matters||p.why_this_matters,clinical_pearl:q.clinical_pearl||p.clinical_pearl,mnemonic:q.mnemonic||p.mnemonic,unit_system_support:Object.keys(q.unit_system_support||{}).length?q.unit_system_support:p.unit_system_support,unit_variants:(q.unit_variants||[]).length?q.unit_variants:p.unit_variants};issues=auditQuestionPublicationContract(q);if(!q.tier)issues.push({code:"missing_tier",field:"tier",severity:"blocking",detail:"Serving tier is required."});}catch(e:any){issues.push({code:"ai_repair_failed",field:"contract",severity:"quality",detail:e.message});}}
      for(const i of issues)stat.issues[i.code]=(stat.issues[i.code]||0)+1;const st=issueStatus(issues);if(st==="blocked"){stat.blocked++;report.totals.blocked++;}else if(st==="quality_only"){stat.qualityOnly++;report.totals.qualityOnly++;}else{stat.verified++;report.totals.verified++;}if(APPLY){await write(s,row,q,issues);stat.updated++;report.totals.updated++;}
    }report.stores[s.table]=stat;if(APPLY)await pool.query(`INSERT INTO question_contract_store_registry(table_name,last_audited_at,total_rows,verified_rows,blocked_rows,quality_only_rows,last_issue_counts)VALUES($1,NOW(),$2,$3,$4,$5,$6::jsonb)ON CONFLICT(table_name)DO UPDATE SET last_audited_at=EXCLUDED.last_audited_at,total_rows=EXCLUDED.total_rows,verified_rows=EXCLUDED.verified_rows,blocked_rows=EXCLUDED.blocked_rows,quality_only_rows=EXCLUDED.quality_only_rows,last_issue_counts=EXCLUDED.last_issue_counts`,[s.table,stat.rows,stat.verified,stat.blocked,stat.qualityOnly,JSON.stringify(stat.issues)]);
  }console.log(JSON.stringify(report,null,2));if(report.totals.blocked>0)process.exitCode=2;}
main().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{try{await pool.end();}catch{}});
