import { spawnSync } from "node:child_process";
import { pool } from "../server/storage";

type Step = { name: string; args: string[]; optional?: boolean };
const APPLY=process.argv.includes("--apply");const AI=process.argv.includes("--ai");const DRY=process.argv.includes("--dry-run")||!APPLY;
function run(step:Step){const proc=spawnSync(process.execPath,["./node_modules/tsx/dist/cli.mjs",...step.args],{stdio:"inherit",env:process.env});if((proc.status??1)!==0&&!step.optional)throw new Error(`${step.name} failed with exit code ${proc.status}`);}
async function sidecarReady(){const r=await pool.query(`SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='exam_questions' AND column_name='contract_question_id') ready, EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='exam_question_translations' AND column_name='contract_status') translation_ready`);return Boolean(r.rows[0]?.ready)&&Boolean(r.rows[0]?.translation_ready);}
async function registrySummary(){try{return(await pool.query(`SELECT table_name,total_rows,verified_rows,blocked_rows,quality_only_rows,last_issue_counts FROM question_contract_store_registry ORDER BY blocked_rows DESC,table_name`)).rows;}catch{return[];}}
async function duplicateSummary(){try{return(await pool.query(`SELECT COUNT(*)::int duplicate_groups,COALESCE(SUM(jsonb_array_length(duplicate_ids)),0)::int duplicate_rows FROM question_duplicate_groups`)).rows[0]||{duplicate_groups:0,duplicate_rows:0};}catch{return{duplicate_groups:0,duplicate_rows:0};}}
async function main(){
  if(!(await sidecarReady()))throw new Error("Question/translation contract migrations are not fully applied. Apply the universal question-store, exam publication-gate, and exam_question_translation contract migrations first.");
  const backfillArgs=["script/backfill-all-question-stores-contract-v3.ts",...(APPLY?["--apply"]:[]),...(AI?["--ai"]:[])],orderedRepairArgs=["script/repair-ordered-response-contract-sidecars.ts",...(APPLY?["--apply"]:[])],canonicalRecheckArgs=["script/recheck-question-contract-registry.ts",...(APPLY?["--apply"]:[])],translationRepairArgs=["script/backfill-exam-question-translations-contract-v2.ts",...(APPLY?["--apply"]:[]),...(AI?["--ai"]:[])],translationRecheckArgs=["script/recheck-exam-question-translation-contract.ts",...(APPLY?["--apply"]:[])];
  const steps:Step[]=[
    {name:"contract-backfill",args:backfillArgs},{name:"ordered-response-sidecar-repair",args:orderedRepairArgs},{name:"country-label-backfill",args:["script/backfill-question-country-labels.ts",...(APPLY?["--apply"]:[])]},{name:"canonical-contract-recheck",args:canonicalRecheckArgs},{name:"duplicate-audit",args:["script/audit-retire-question-duplicates.ts",...(APPLY?["--apply"]:[])]},{name:"ordered-response-recheck-after-duplicates",args:orderedRepairArgs},{name:"canonical-contract-recheck-after-duplicates",args:canonicalRecheckArgs},{name:"translation-contract-repair",args:translationRepairArgs},{name:"translation-contract-recheck",args:translationRecheckArgs},{name:"source-estate-audit",args:["script/audit-active-question-source-estate.ts"]},{name:"authored-v2-source-coverage",args:["script/audit-active-question-enrichment-coverage.ts"]},{name:"interaction-mode-audit",args:["script/audit-active-question-interaction-modes.ts"]},{name:"template-content-audit",args:["script/audit-active-question-template-content.ts"]},{name:"quarantine-replacement-audit",args:["script/audit-question-source-quarantine.ts"]},{name:"career-question-contract",args:["script/audit-career-question-contract-v2.ts"]},{name:"career-quarantine-topic-parity",args:["script/audit-career-quarantine-topic-parity.ts"]},
  ];
  for(const step of steps)run(step);
  const registry=await registrySummary(),duplicates=await duplicateSummary();const blocked=registry.reduce((s,r)=>s+Number(r.blocked_rows||0),0),qualityOnly=registry.reduce((s,r)=>s+Number(r.quality_only_rows||0),0),total=registry.reduce((s,r)=>s+Number(r.total_rows||0),0),verified=registry.reduce((s,r)=>s+Number(r.verified_rows||0),0);
  const completion={mode:DRY?"audit":"apply",totalRows:total,verifiedRows:verified,blockedRows:blocked,qualityOnlyRows:qualityOnly,duplicateGroupsRemaining:Number(duplicates.duplicate_groups||0),duplicateRowsRemaining:Number(duplicates.duplicate_rows||0),stores:registry,complete:blocked===0&&qualityOnly===0&&Number(duplicates.duplicate_groups||0)===0&&total>0&&verified===total};console.log(JSON.stringify(completion,null,2));if(!completion.complete)process.exitCode=2;
}
main().catch(error=>{console.error("[question-contract-completion]",error);process.exitCode=1;}).finally(async()=>{try{await pool.end();}catch{}});
