import { Pool } from "pg";
import crypto from "crypto";
const pool = new Pool({ connectionString: process.env.DATABASE_URL });
function hash(s: string): string { return crypto.createHash("md5").update(s.toLowerCase().trim()).digest("hex"); }
function q(e:string,b:string,d:number,s:string,o:string[],c:number,r:string) {
  return {tier:"rpn",exam:e,stem:s,options:o,correct:c,rationale:r,diff:d,bs:b};
}

const QS = [
  q("REX-PN","Cardiovascular",3,"A client taking digoxin has a heart rate of 54 bpm. The nurse should:",["Administer the digoxin as scheduled","Hold the digoxin and notify the provider","Give the digoxin with food","Increase the dosage to compensate"],1,"Digoxin slows the heart rate. It should be held if HR < 60 bpm in adults. The provider should be notified as the dose may need adjustment. Check serum digoxin level and potassium (hypokalemia increases digoxin toxicity)."),
  q("REX-PN","Cardiovascular",2,"The nurse is preparing a client for a cardiac catheterization. Post-procedure monitoring includes:",["Ambulating the client immediately after the procedure","Checking the access site for hematoma and monitoring peripheral pulses","Elevating the head of bed to 90 degrees","Restricting all oral fluids for 12 hours"],1,"Post-cardiac catheterization: monitor the access site for bleeding/hematoma, check distal pulses, assess circulation (color, sensation, warmth), maintain pressure/closure device at puncture site, hydrate to flush contrast dye, and limit activity as prescribed."),
  q("RPN-CAT","Cardiovascular",3,"A client receiving a blood transfusion develops chills, fever, and back pain after 15 mL. The nurse suspects a hemolytic transfusion reaction and should first:",["Slow the transfusion rate","Stop the transfusion immediately and maintain IV with normal saline","Administer acetaminophen and continue","Increase the transfusion rate to complete quickly"],1,"Hemolytic reactions are life-threatening. Stop the transfusion immediately, maintain IV with NS (use new tubing), send the blood bag and client blood samples to the lab, monitor vital signs, and support circulation."),
  q("REX-PN","Cardiovascular",2,"A client with venous insufficiency should be taught to:",["Stand for prolonged periods to strengthen leg muscles","Elevate legs when sitting and wear compression stockings","Apply heat to the legs to improve circulation","Cross legs while sitting for comfort"],1,"Venous insufficiency management includes leg elevation above heart level when sitting/lying, compression stockings (applied before getting up), regular exercise (walking), weight management, and avoiding prolonged standing or sitting."),
  q("REX-PN","Respiratory",3,"A client with a pneumothorax has a chest tube connected to a water seal drainage system. The nurse observes continuous bubbling in the water seal chamber. This indicates:",["Normal drainage","A persistent air leak in the system","The chest tube is functioning properly","The pneumothorax has resolved"],1,"Continuous bubbling in the water seal chamber indicates an air leak. Intermittent bubbling with inspiration may be normal. The nurse should check all connections for tightness and assess for resolution of the pneumothorax."),
  q("REX-PN","Respiratory",2,"The nurse performs percussion and vibration for chest physiotherapy. The primary purpose is to:",["Improve oxygenation directly","Loosen and mobilize retained secretions for removal","Strengthen the respiratory muscles","Reduce bronchospasm"],1,"Percussion (cupped hands clapping on chest wall) and vibration loosen thick, retained secretions from bronchial walls, facilitating their movement to larger airways where they can be coughed out or suctioned."),
  q("RPN-CAT","Respiratory",3,"An acute asthma exacerbation unresponsive to initial nebulized albuterol should be treated with:",["Continued albuterol only at the same dose","Continuous nebulized albuterol with systemic corticosteroids and ipratropium bromide","Sedation to reduce respiratory effort","Antibiotics for suspected infection"],1,"Status asthmaticus management includes continuous nebulized albuterol, ipratropium bromide (additional bronchodilation through different mechanism), systemic corticosteroids (IV methylprednisolone), and preparation for possible intubation if respiratory failure develops."),
  q("REX-PN","Neurological",3,"A client with a head injury develops rhinorrhea with clear fluid from the nose. The nurse suspects CSF leak and should:",["Pack the nose with gauze tightly","Test the fluid for glucose (positive suggests CSF), do not suction or pack nasally","Instruct the client to blow their nose forcefully","Apply a nasal decongestant spray"],1,"CSF rhinorrhea following head injury indicates a basilar skull fracture. Test drainage for glucose (CSF contains glucose; mucus does not). Do NOT pack, suction, or insert anything nasally. Position client with HOB elevated. Report to provider immediately."),
  q("REX-PN","Neurological",2,"When caring for a client with a seizure disorder, the nurse should keep which equipment at bedside?",["Tongue depressor and padded forceps","Suction equipment, oxygen, padding for bed rails, and IV access","Restraints and tape","A bite block and jaw clamp"],1,"Bedside seizure precautions include suction (for secretions post-seizure), oxygen, padded side rails, IV access, and oral airway. Never force objects into the mouth during a seizure. Position on their side after the seizure."),
  q("RPN-CAT","Neurological",3,"Phenytoin (Dilantin) toxicity manifests as:",["Bradycardia and hypotension only","Nystagmus, ataxia, slurred speech, and diplopia","Increased seizure frequency","Hyperglycemia and polyuria"],1,"Phenytoin toxicity presents with cerebellar signs: nystagmus (earliest sign), ataxia, slurred speech, and diplopia. Severe toxicity causes confusion, lethargy, and cardiac arrhythmias. Therapeutic level is 10-20 mcg/mL."),
  q("REX-PN","Endocrine",3,"A client with pheochromocytoma has episodes of hypertensive crisis. The nurse should avoid:",["Blood pressure monitoring","Palpating the abdomen (can stimulate catecholamine release)","Monitoring heart rate","Providing emotional support"],1,"Palpating the abdomen over the adrenal gland can stimulate massive catecholamine release, causing life-threatening hypertensive crisis. Avoid abdominal palpation, inform the client about triggers, and ensure emergency antihypertensives are available."),
  q("REX-PN","Endocrine",2,"A client with diabetes has a blood glucose of 45 mg/dL and is conscious. The nurse should:",["Administer IV dextrose immediately","Give 15g of fast-acting carbohydrate and recheck in 15 minutes","Administer glucagon IM","Wait for the next scheduled meal"],1,"Conscious hypoglycemia follows the Rule of 15: give 15g fast-acting carbohydrate (4 oz juice, glucose tablets), wait 15 minutes, recheck glucose, repeat if still < 70 mg/dL. Follow with a protein snack once stable."),
  q("REX-PN","Gastrointestinal",3,"A client with cirrhosis develops esophageal varices. The nurse should anticipate:",["Aggressive oral anticoagulation","Prophylactic beta-blocker therapy and band ligation","High-fiber diet for bowel regulation","NG tube placement for feeding"],1,"Esophageal variceal prophylaxis includes non-selective beta-blockers (propranolol, nadolol) to reduce portal pressure and endoscopic variceal ligation (banding). Primary prophylaxis reduces first bleeding risk by 40-50%."),
  q("REX-PN","Gastrointestinal",2,"When performing NG tube irrigation, the nurse uses:",["Tap water for irrigation","Normal saline (0.9% NaCl) for irrigation","Sterile water for injection","Dextrose 5% solution"],1,"Normal saline is used for NG tube irrigation because it is isotonic and prevents electrolyte imbalances. Using plain water can cause hyponatremia through gastric sodium dilution. Typically 30-60 mL is used per irrigation."),
  q("REX-PN","Pharmacology",3,"A client receiving IV potassium must have the infusion:",["Administered by rapid IV push for quick correction","Diluted and administered via infusion pump at a rate not exceeding 10 mEq/hour peripherally","Given undiluted through a peripheral IV","Administered IM for faster absorption"],1,"IV potassium is never given by push (causes fatal cardiac arrest). Maximum peripheral rate is 10 mEq/hour (40 mEq/hour via central line with cardiac monitoring). Always use an infusion pump. Monitor ECG for hyperkalemia signs."),
  q("REX-PN","Pharmacology",2,"When administering ear drops to an adult, the nurse should pull the pinna:",["Down and back","Up and back to straighten the ear canal","Forward and down","In any comfortable direction"],1,"In adults, pulling the pinna up and back straightens the ear canal for medication delivery. In children under 3 years, pull the pinna down and back due to the shorter, more horizontal ear canal anatomy."),
  q("RPN-CAT","Pharmacology",3,"A client on warfarin has an INR of 5.2 with no active bleeding. The nurse should anticipate:",["Administering vitamin K IV immediately","Holding warfarin and monitoring INR closely","Administering fresh frozen plasma","Continuing warfarin at the current dose"],1,"INR 5-9 without bleeding: hold warfarin, monitor INR. Vitamin K may be given if INR > 9 or patient is at high bleeding risk. Active bleeding with elevated INR requires vitamin K, FFP, or prothrombin complex concentrate depending on severity."),
  q("REX-PN","Mental Health",3,"A client with PTSD avoids all situations reminiscent of the traumatic event. This symptom cluster is:",["Intrusion symptoms","Avoidance behaviors","Negative alterations in cognition","Arousal and reactivity changes"],1,"PTSD has 4 symptom clusters: intrusion (flashbacks, nightmares), avoidance (avoiding triggers), negative cognitions/mood (guilt, detachment), and hyperarousal (hypervigilance, startle response). Avoidance of trauma-associated stimuli is a hallmark feature."),
  q("REX-PN","Mental Health",2,"When a client expresses suicidal ideation, the nurse's first response should be to:",["Change the subject to distract the client","Directly ask about a specific plan, means, and intent","Leave to notify the provider immediately","Tell the client they have much to live for"],1,"Direct, non-judgmental assessment of suicidal ideation includes asking about specific plans, available means, timeline, and intent. This does NOT increase suicide risk. Leaving the client alone is dangerous. Reassurances may feel dismissive."),
  q("REX-PN","Pediatrics",3,"Croup (laryngotracheobronchitis) is characterized by:",["Productive cough and high fever","Barky (seal-like) cough, stridor, and hoarseness","Wheezing and prolonged expiration","Grunting and nasal flaring"],1,"Croup causes subglottic airway inflammation producing the characteristic barky cough, inspiratory stridor, and hoarseness. It is usually viral (parainfluenza). Cool mist humidification and dexamethasone are mainstays of treatment."),
  q("REX-PN","Pediatrics",2,"When measuring an infant's head circumference, the tape should be placed:",["Around the largest occipitofrontal diameter","Just above the ears across the forehead","At the level of the soft spot","Below the occipital protuberance"],0,"Head circumference is measured at the largest occipitofrontal circumference: just above the eyebrows and ears, over the most prominent part of the occiput. Serial measurements detect hydrocephalus or microcephaly."),
  q("RPN-CAT","Pediatrics",3,"A child with intussusception typically presents with:",["Constant mild abdominal discomfort","Sudden episodic colicky abdominal pain with currant jelly stools","Projectile vomiting after feeding","Chronic constipation"],1,"Intussusception (telescoping of one bowel segment into another) causes sudden, severe, intermittent, colicky abdominal pain with vomiting and red currant jelly stools (blood and mucus). The child draws up the legs during painful episodes."),
  q("REX-PN","Fundamentals",2,"The nurse should wash hands for at least:",["5 seconds with soap and water","20 seconds with soap and water","60 seconds with soap and water","10 seconds with water only"],1,"CDC recommends at least 20 seconds of handwashing with soap and water (sing Happy Birthday twice). Alcohol-based hand sanitizer (60%+ alcohol) is acceptable when hands are not visibly soiled. Hand hygiene is the most important infection prevention measure."),
  q("REX-PN","Fundamentals",3,"When administering blood products, the nurse should:",["Use a standard IV line with dextrose solution","Use a blood administration set with a filter and normal saline only","Mix blood with any IV solution for compatibility","Administer through a 24-gauge IV catheter"],1,"Blood products require a dedicated blood administration set with a 170-micron filter. Only normal saline is compatible (dextrose causes hemolysis, Ringer's causes clotting). Use at least an 18-gauge catheter for adequate flow."),
  q("RPN-CAT","Fundamentals",3,"A client with chronic pain says their pain is 4/10 but is grimacing and guarding. The nurse should:",["Document the self-reported pain level of 4/10 as the gold standard","Document both the verbal report and behavioral observations, and discuss discrepancy therapeutically","Override the client's report and document pain as 8/10","Ignore the behavioral cues entirely"],1,"Pain is a subjective experience and self-report is the gold standard. However, behavioral cues discrepant with verbal report should be documented alongside the client's stated level. Therapeutic discussion explores the discrepancy without invalidating the client's experience."),
  q("REX-PN","Musculoskeletal",3,"A client with a hip fracture repaired with a total hip arthroplasty should be instructed to avoid:",["Ankle pump exercises","Flexion of the hip beyond 90 degrees","Walking with a walker","Lying on the unaffected side with a pillow between the legs"],1,"Hip precautions after posterior approach THA: avoid hip flexion > 90 degrees, adduction past midline, and internal rotation. These movements risk posterior dislocation. Use elevated toilet seats, avoid low chairs, and use long-handled reachers."),
  q("REX-PN","Musculoskeletal",2,"A client with a leg cast reports increasing pain not relieved by prescribed analgesics. The nurse should:",["Continue the current pain medication regimen","Assess for neurovascular compromise and notify the provider","Elevate the leg higher","Apply ice over the cast"],1,"Unrelenting pain unresponsive to analgesics may indicate compartment syndrome or neurovascular compromise. Assess the 5 Ps (pain, paralysis, paresthesia, pallor, pulselessness) and notify the provider immediately. The cast may need to be bivalved."),
  q("REX-PN","Renal",3,"A client starting peritoneal dialysis develops cloudy dialysate effluent. The nurse should:",["Continue the exchange normally","Obtain a sample for cell count and culture, notify the provider","Increase the dwell time","Add antibiotics to the next exchange independently"],1,"Cloudy effluent is the hallmark of PD peritonitis. Prompt specimen collection for culture and cell count is essential. Empiric antibiotics (IP vancomycin + aminoglycoside or cephalosporin) are started after sample collection."),
  q("REX-PN","Renal",2,"A client with chronic kidney disease should limit dietary intake of:",["Carbohydrates","Potassium, phosphorus, and sodium","Vitamin C","Unsaturated fats"],1,"CKD dietary restrictions include potassium (prevents hyperkalemia-related arrhythmias), phosphorus (prevents renal osteodystrophy), sodium (controls blood pressure and fluid), and protein (reduces uremia). Fluid restriction may be needed in later stages."),
  q("REX-PN","Maternal/Newborn",3,"The nurse teaches a pregnant client about warning signs that require immediate medical attention. These include:",["Mild ankle swelling in the evening","Severe headache, visual changes, and sudden face/hand swelling","Increased vaginal discharge","Mild fatigue"],1,"Warning signs in pregnancy requiring immediate evaluation: severe headache, visual changes, sudden facial/hand edema (preeclampsia), vaginal bleeding, decreased fetal movement, ruptured membranes, and signs of preterm labor."),
  q("REX-PN","Maternal/Newborn",2,"Nagele rule estimates the expected date of delivery by:",["Adding 9 months to the LMP date","Subtracting 3 months from LMP, adding 7 days and 1 year","Adding 40 weeks from conception date","Counting 38 weeks from the last menstrual period"],1,"Nagele rule: subtract 3 months from the first day of the LMP, add 7 days, and add 1 year. This estimates a 40-week (280-day) gestational period. Example: LMP January 14 = EDD October 21."),
  q("REX-PN","Infection Control",3,"When administering an IM injection using Z-track technique, the nurse:",["Massages the site after injection","Displaces the tissue laterally before injection and releases after needle withdrawal","Injects at a 45-degree angle","Uses the smallest gauge needle available"],1,"Z-track technique prevents medication leakage into subcutaneous tissue. Pull skin laterally, insert needle at 90 degrees, inject slowly, wait 10 seconds, withdraw needle, then release skin. The displaced tissue seals the needle track."),
  q("REX-PN","Hematological",2,"The client with anemia complains of fatigue. The nurse should plan activities to:",["Encourage maximum exertion to build endurance","Alternate rest periods with activities to conserve energy","Restrict all activities until hemoglobin normalizes","Schedule all activities in the morning"],1,"Anemia-related fatigue management includes pacing activities, alternating rest and activity, prioritizing essential tasks, and energy conservation techniques. Gradual activity increase as tolerated promotes conditioning without exhaustion."),
  q("REX-PN","Integumentary",3,"Stage 2 pressure injury is characterized by:",["Intact skin with non-blanchable erythema","Partial-thickness skin loss involving the epidermis and/or dermis, presenting as a blister or shallow ulcer","Full-thickness tissue loss with visible subcutaneous fat","Full-thickness loss with exposed bone, tendon, or muscle"],1,"Stage 2: partial-thickness loss with exposed dermis. May present as an intact or ruptured serum-filled blister or shallow open ulcer. Stage 1 = intact skin with erythema, Stage 3 = full-thickness with subcutaneous fat visible, Stage 4 = exposed bone/muscle."),
  q("REX-PN","Immunological",2,"The nurse educates a client about the importance of the annual influenza vaccine. The vaccine should be given:",["Only to high-risk individuals","To all persons aged 6 months and older annually","Only during confirmed influenza outbreaks","Every 5 years for lasting immunity"],1,"The CDC recommends annual influenza vaccination for all persons aged >= 6 months. The virus mutates (antigenic drift), requiring updated vaccines each year. Vaccination is the most effective prevention measure and reduces severity of illness."),
  q("REX-PN","Reproductive",3,"A client with polycystic ovary syndrome presents with which characteristic findings?",["Regular menstrual cycles and weight loss","Irregular periods, hirsutism, acne, and insulin resistance","Hypotension and bradycardia","Decreased testosterone levels"],1,"PCOS is characterized by oligo/amenorrhea, hyperandrogenism (hirsutism, acne, alopecia), insulin resistance, and polycystic ovaries on ultrasound. Management includes OCPs, metformin, weight loss, and fertility treatment if desired."),
  q("REX-PN","Emergency",3,"Triage in a mass casualty event uses which classification system?",["First-come, first-served","START triage: immediate (red), delayed (yellow), minor (green), deceased (black)","Alphabetical by name","Based on insurance status"],1,"START (Simple Triage and Rapid Treatment) classifies victims: RED (immediate - life-threatening but salvageable), YELLOW (delayed - serious but can wait), GREEN (minor - walking wounded), BLACK (expectant/deceased - not salvageable with available resources)."),
  q("REX-PN","Oncology",2,"Tumor markers such as PSA are used primarily for:",["Definitive cancer diagnosis","Monitoring treatment response and detecting recurrence","Determining cancer stage","Prescribing chemotherapy doses"],1,"Tumor markers (PSA, CA-125, CEA, AFP) are used to monitor treatment response, detect recurrence, and assess disease progression. They are not used alone for diagnosis or screening (except PSA for prostate cancer screening, which is controversial)."),
  q("REX-PN","Perioperative",2,"The surgical timeout (universal protocol) requires verification of:",["Patient name only","Correct patient, correct procedure, and correct site","Surgical team names","Insurance information"],1,"The surgical timeout before incision verifies: correct patient identity, correct procedure, correct operative site, consent documentation, relevant imaging/labs available, antibiotic administration, and any special equipment needs. All team members participate."),
  q("REX-PN","Safety",2,"A nurse witnessing a colleague diverting narcotics should:",["Confront the colleague privately and keep it confidential","Report the incident through proper institutional channels immediately","Ignore it as it's not the nurse's responsibility","Wait to see if it happens again before reporting"],1,"Drug diversion is a legal and safety concern requiring immediate reporting through institutional channels. Failure to report endangers patients, enables substance abuse, and violates professional and legal obligations."),
  q("REX-PN","Geriatrics",2,"Polypharmacy in the elderly is defined as concurrent use of:",["2 or more medications","5 or more medications","10 or more medications","Any prescribed medication"],1,"Polypharmacy (5+ medications) increases risks of adverse drug reactions, drug interactions, falls, cognitive impairment, and non-adherence. Medication reconciliation and regular review are essential to identify potentially inappropriate medications."),
  q("REX-PN","Community Health",2,"The nurse's role in primary prevention includes:",["Screening for early disease detection","Health promotion activities such as vaccination and education","Treating established disease","Rehabilitation after illness"],0,"Primary prevention prevents disease before it occurs: immunization, health education, lifestyle modification, environmental protection, and risk factor reduction. Secondary prevention = early detection (screening). Tertiary prevention = managing established disease."),
  q("REX-PN","Ethics/Legal",3,"Informed consent requires disclosure of:",["Only the benefits of the procedure","Risks, benefits, alternatives, and consequences of refusing treatment","The provider's success rate statistics","Other patients' experiences"],1,"Informed consent requires the provider to explain: the procedure/treatment, expected benefits, material risks, alternative treatments, consequences of refusing treatment, and opportunity for questions. The client must be competent and voluntary."),
  q("REX-PN","Delegation",3,"The RPN should NOT delegate which type of task?",["Bathing and hygiene care","Initial client assessment and nursing diagnosis formulation","Routine vital sign measurement on stable clients","Ambulation of a stable client"],1,"Initial assessment and nursing diagnosis require professional nursing judgment and are within the registered nurse scope. RPNs can perform assessments within their scope but initial comprehensive assessment and care plan development are RN responsibilities."),
  q("REX-PN","Pharmacology",3,"A client on warfarin asks about diet. The nurse instructs the client to:",["Avoid all green vegetables completely","Maintain consistent vitamin K intake rather than eliminating it","Eat as much spinach as desired","Take extra vitamin K supplements"],1,"Consistent vitamin K intake is key - not elimination. Dramatic changes in vitamin K consumption alter warfarin effectiveness and INR stability. Eat a consistent amount of green leafy vegetables throughout the week."),
  q("REX-PN","Cardiovascular",3,"ACE inhibitor therapy commonly causes which side effect?",["Productive cough","Dry, persistent, non-productive cough","Weight gain","Hypokalemia"],1,"ACE inhibitor-induced cough (dry, persistent, non-productive) occurs in 5-20% of patients due to bradykinin accumulation. If intolerable, switching to an ARB eliminates the cough while maintaining similar cardioprotective benefits."),
  q("REX-PN","Respiratory",3,"Oxygen toxicity from prolonged high-concentration oxygen manifests as:",["Improved respiratory function","Pulmonary fibrosis, atelectasis, and retrolental fibroplasia in neonates","Bradycardia only","Hepatotoxicity"],1,"Prolonged exposure to FiO2 > 50% can cause oxygen toxicity: absorption atelectasis, decreased surfactant production, pulmonary edema, and fibrosis. In premature neonates, high oxygen causes retinopathy of prematurity."),
  q("REX-PN","Neurological",2,"Glasgow Coma Scale components assess:",["Pain level, anxiety, and depression","Eye opening, verbal response, and motor response","Respiratory function, pupil size, and reflexes","Blood pressure, heart rate, and temperature"],1,"GCS evaluates consciousness through three components: Eye opening (1-4), Verbal response (1-5), Motor response (1-6). Total score ranges from 3 (deep coma) to 15 (fully alert). Used for traumatic brain injury classification and trending."),
  q("REX-PN","Endocrine",3,"Diabetic neuropathy foot care includes:",["Soaking feet in hot water daily","Inspecting feet daily, wearing well-fitting shoes, and using lukewarm water for washing","Cutting toenails with scissors close to the skin","Walking barefoot to strengthen foot muscles"],1,"Daily foot inspection detects injuries early (neuropathy reduces sensation). Use lukewarm water (test with hands/thermometer), pat dry thoroughly, moisturize (not between toes), wear well-fitting shoes, have podiatrist trim nails, and never walk barefoot."),
  q("REX-PN","Gastrointestinal",3,"Total parenteral nutrition requires monitoring which laboratory value most closely?",["Hemoglobin","Blood glucose (due to high dextrose concentration)","Platelet count","Coagulation studies"],1,"TPN contains high dextrose concentrations that can cause hyperglycemia. Blood glucose monitoring (every 4-6 hours initially) is essential. Other monitored values include electrolytes, triglycerides, liver function, and prealbumin for nutritional status."),
  q("REX-PN","Pharmacology",2,"The nurse should assess the apical heart rate before administering:",["Acetaminophen","Digoxin (hold if HR < 60 bpm in adults)","Amoxicillin","Omeprazole"],1,"Digoxin decreases heart rate through vagal stimulation. Apical pulse assessment for 1 full minute before each dose is required. Hold and notify the provider if HR < 60 bpm in adults (< 70 in children, < 90-110 in infants)."),
  q("REX-PN","Mental Health",3,"Neuroleptic malignant syndrome from antipsychotics presents with:",["Drowsiness and mild tremor","Hyperthermia, severe muscle rigidity, altered consciousness, and autonomic instability","Anxiety and restlessness only","Dry mouth and constipation"],1,"NMS is a life-threatening emergency featuring high fever (> 40C), lead-pipe muscle rigidity, altered consciousness, and autonomic instability (tachycardia, labile BP, diaphoresis). Immediate drug discontinuation, dantrolene, and supportive care are required."),
  q("REX-PN","Pediatrics",3,"Erikson's stage of development for a toddler (1-3 years) is:",["Trust vs. Mistrust","Autonomy vs. Shame and Doubt","Initiative vs. Guilt","Industry vs. Inferiority"],1,"Toddlers develop autonomy through exploration and independent activities (feeding themselves, choosing clothes, toilet training). Excessive criticism or restriction leads to shame and doubt. Allow safe choices to foster autonomy."),
  q("REX-PN","Fundamentals",3,"The chain of infection includes which components in sequence?",["Organism, transmission, host","Infectious agent, reservoir, portal of exit, mode of transmission, portal of entry, susceptible host","Bacteria, virus, fungus, parasite","Incubation, prodromal, illness, convalescence"],1,"The chain of infection requires all six links for disease transmission. Breaking any link prevents infection. Nurses intervene at multiple points: hand hygiene (transmission), PPE (portal of entry), immunization (susceptible host), environmental cleaning (reservoir)."),
  q("REX-PN","Musculoskeletal",2,"A client with osteoporosis should be counseled about:",["Avoiding all physical activity to prevent fractures","Weight-bearing exercise, calcium/vitamin D supplementation, and fall prevention","Bed rest for bone healing","High-sodium diet for bone strength"],1,"Osteoporosis management includes weight-bearing exercise (walking, dancing), calcium 1200 mg/day, vitamin D 600-800 IU/day, fall prevention strategies, and bisphosphonate therapy as prescribed. Avoid excessive caffeine and alcohol."),
  q("REX-PN","Renal",2,"When measuring intake and output, the nurse should include:",["Only IV fluids as intake","All oral, IV, tube feeding, and irrigation fluid intake","Only urine as output","Food intake measured in calories"],1,"Accurate I&O includes ALL intake (oral fluids, IV, tube feedings, blood products, irrigation fluids) and ALL output (urine, emesis, wound drainage, diarrhea, chest tube drainage). Ice chips count as half their volume."),
  q("REX-PN","Maternal/Newborn",2,"The APGAR score assessed at 1 and 5 minutes after birth evaluates:",["Only respiratory effort and heart rate","Appearance, Pulse, Grimace, Activity, and Respiration","Weight, length, and head circumference","Gestational age and maturity"],1,"APGAR evaluates 5 criteria: Appearance (color), Pulse (heart rate), Grimace (reflex irritability), Activity (muscle tone), and Respiration (respiratory effort). Each scored 0-2 for total 0-10. Score guides immediate newborn interventions."),
  q("REX-PN","Infection Control",2,"Contact precautions require the nurse to:",["Wear an N95 respirator","Wear gloves and gown when entering the room","Use only hand hygiene without additional PPE","Wear a surgical mask only"],1,"Contact precautions prevent transmission of organisms spread by direct or indirect contact (MRSA, VRE, C. diff, scabies). Required PPE: gloves and gown upon room entry. Dedicated equipment and enhanced environmental cleaning are also important."),
  q("REX-PN","Hematological",3,"Iron supplements should be taken:",["With milk for better absorption","On an empty stomach with vitamin C to enhance absorption","At bedtime with calcium","With coffee or tea"],1,"Iron absorption is enhanced by vitamin C (ascorbic acid) and an acidic environment (empty stomach). Milk, calcium, antacids, and tannins (tea/coffee) decrease absorption. GI side effects (nausea, constipation) may require taking with small amounts of food."),
  q("REX-PN","Integumentary",2,"When providing wound care using sterile technique, the nurse cleans from:",["The outer edges toward the wound center","The wound center (cleanest area) outward toward the surrounding skin","Any direction that is convenient","In a back-and-forth scrubbing motion"],1,"Sterile wound cleaning moves from the cleanest area (wound center) to the least clean area (surrounding skin) to prevent introducing skin organisms into the wound. Use single strokes in one direction and discard each gauze after one pass."),
  q("REX-PN","Immunological",3,"A client with HIV has a CD4 count of 180 cells/mm3. The nurse knows this client is at risk for:",["No opportunistic infections","Pneumocystis jirovecii pneumonia (prophylaxis recommended at CD4 < 200)","Only bacterial infections","No additional concerns"],1,"CD4 < 200 cells/mm3 defines AIDS and significantly increases opportunistic infection risk. PJP prophylaxis (TMP-SMX) is indicated at CD4 < 200. Toxoplasmosis prophylaxis at < 100, MAC prophylaxis at < 50. ART should be initiated promptly."),
  q("REX-PN","Emergency",2,"For an unresponsive adult without a pulse, CPR compressions should be:",["At a rate of 80/minute and depth of 1 inch","At a rate of 100-120/minute and depth of at least 2 inches (5 cm)","At a rate of 60/minute","At any rate the rescuer can maintain"],1,"AHA guidelines: adult CPR compressions at 100-120/minute, depth at least 2 inches (5 cm) but not > 2.4 inches, allow full chest recoil, minimize interruptions. Compression-to-ventilation ratio is 30:2 for 1 or 2 rescuers without advanced airway."),
  q("REX-PN","Oncology",3,"A client with neutropenia (ANC < 500) should be protected by:",["Placing in a room with fresh flowers for comfort","Neutropenic precautions: private room, no fresh flowers/plants, meticulous hand hygiene, no raw foods","Restricting visitors entirely without exceptions","Administering prophylactic antibiotics to all visitors"],1,"Neutropenic precautions protect immunocompromised clients: private room, no fresh flowers or plants (harbor Aspergillus), meticulous hand hygiene, mask for visitors with respiratory symptoms, neutropenic diet (no raw foods), and daily assessment for infection signs."),
  q("REX-PN","Perioperative",3,"Post-general anesthesia, the nurse positions the client initially in:",["Prone position","Lateral (recovery) position to maintain airway and prevent aspiration","High Fowler's position","Trendelenburg position"],1,"The lateral (recovery) position with head slightly extended keeps the airway patent and allows secretions and potential vomitus to drain from the mouth, preventing aspiration. The client is transitioned to supine or other positions as consciousness returns."),
  q("REX-PN","Safety",3,"RACE is the fire safety acronym meaning:",["Run And Call Emergency","Rescue, Alarm, Contain, Extinguish/Evacuate","Report All Critical Emergencies","Respond, Assess, Clean, Exit"],1,"RACE fire response: Rescue anyone in danger, Alarm (pull fire alarm), Contain (close doors/windows), Extinguish small fires or Evacuate. PASS is for fire extinguisher use: Pull, Aim, Squeeze, Sweep."),
  q("REX-PN","Geriatrics",3,"Sundowning in dementia clients refers to:",["Improvement of cognitive function in the evening","Worsening confusion, agitation, and behavioral changes in late afternoon/evening","Drowsiness after sunset","Increased appetite in the evening"],1,"Sundowning describes increased confusion, agitation, wandering, and behavioral changes occurring in late afternoon and evening. Management includes maintaining a consistent routine, adequate daytime lighting, reducing evening stimulation, and ensuring adequate sleep."),
  q("REX-PN","Community Health",3,"The nurse identifies which level of prevention when administering a mammography screening?",["Primary prevention","Secondary prevention (early detection of disease)","Tertiary prevention","Quaternary prevention"],1,"Mammography screening is secondary prevention: early detection of disease before symptoms appear. Primary prevention prevents disease occurrence (vaccination). Tertiary prevention manages established disease (rehabilitation). Early detection improves treatment outcomes."),
  q("REX-PN","Ethics/Legal",2,"A client who is competent has the right to refuse treatment, including life-sustaining measures. This is based on the ethical principle of:",["Beneficence","Autonomy (self-determination)","Justice","Nonmaleficence"],1,"Autonomy means clients have the right to make their own healthcare decisions, including refusing treatment, even if healthcare providers disagree. This is legally and ethically protected through informed consent and advance directives."),
  q("REX-PN","Pharmacology",3,"Nitrofurantoin prescribed for UTI should be taken:",["On an empty stomach for maximum absorption","With food or milk to enhance absorption and reduce GI upset","Crushed and mixed with water","At bedtime without food"],1,"Nitrofurantoin absorption increases when taken with food, and food reduces GI side effects (nausea, vomiting). It reaches therapeutic concentrations only in the urinary tract. It is not effective for kidney infections."),
  q("REX-PN","Cardiovascular",2,"The nurse teaches a client about modifiable risk factors for coronary artery disease. These include:",["Age and family history","Smoking, hypertension, hyperlipidemia, diabetes, obesity, and physical inactivity","Gender and ethnicity","Genetic predisposition"],1,"Modifiable CAD risk factors can be changed through lifestyle and medical management. Smoking cessation, blood pressure control, lipid management, blood glucose control, weight management, exercise, and stress reduction all reduce cardiovascular risk."),
  q("REX-PN","Respiratory",2,"Peak expiratory flow rate (PEFR) monitoring is used primarily for clients with:",["Pneumonia","Asthma to assess airway obstruction severity and guide treatment","COPD exclusively","Heart failure"],1,"PEFR measures maximum speed of expiration and tracks asthma control. Green zone (80-100% of personal best) = well controlled; Yellow (50-80%) = caution; Red (< 50%) = medical emergency. Used to guide medication adjustments and recognize exacerbations early."),
  q("REX-PN","Neurological",2,"The pupil of an eye that is 'fixed and dilated' indicates:",["Normal neurological function","Potential compression of cranial nerve III (oculomotor) indicating brain herniation","Sleep state","Medication effect only"],1,"A fixed, dilated pupil (pupil that does not constrict to light) on one side suggests compression of CN III, often from uncal herniation due to elevated ICP. This is a neurosurgical emergency requiring immediate intervention."),
];

async function main() {
  let inserted = 0;
  const batchSize = 50;
  for (let i = 0; i < QS.length; i += batchSize) {
    const batch = QS.slice(i, i + batchSize);
    const values: string[] = [];
    const params: any[] = [];
    let idx = 1;
    for (const q of batch) {
      values.push(`($${idx},$${idx+1},$${idx+2},$${idx+3},$${idx+4},$${idx+5}::jsonb,$${idx+6}::jsonb,$${idx+7},$${idx+8}::integer,$${idx+9},$${idx+10},$${idx+11})`);
      params.push(q.tier,q.exam,"multiple_choice","published",q.stem,JSON.stringify(q.options),JSON.stringify([q.correct]),q.rationale,q.diff,q.bs,"BOTH",hash(q.stem));
      idx += 12;
    }
    const sql = `INSERT INTO exam_questions (tier, exam, question_type, status, stem, options, correct_answer, rationale, difficulty, body_system, region_scope, stem_hash)
                 SELECT v.* FROM (VALUES ${values.join(",")}) AS v(tier,exam,question_type,status,stem,options,correct_answer,rationale,difficulty,body_system,region_scope,stem_hash)
                 WHERE NOT EXISTS (SELECT 1 FROM exam_questions e WHERE e.stem_hash = v.stem_hash)`;
    const result = await pool.query(sql, params);
    inserted += result.rowCount || 0;
  }
  console.log(`[RPN-B5] Inserted ${inserted}/${QS.length}`);
  const counts = await pool.query(`SELECT tier, count(*) as cnt FROM exam_questions WHERE status='published' GROUP BY tier ORDER BY tier`);
  counts.rows.forEach((r: any) => console.log(`  ${r.tier}: ${r.cnt}`));
  await pool.end();
}
main().catch(e => { console.error(e); process.exit(1); });
