// Generated by script/enrich-active-source-question-contract.ts.
// Do not hand-edit generated entries. The empty object is a valid baseline until the bulk enrichment pass runs.
export type QuestionContractEnrichment = {
  correctAnswerExplanation?: string;
  distractorRationales?: Record<string, string>;
  hint?: string;
  whyThisMatters?: string;
  clinicalPearl?: string;
  mnemonic?: string;
  countryCode?: string;
  regionScope?: string;
  languageCode?: string;
  licensingBody?: string;
  unitSystemSupport?: { supported: string[]; default?: string };
  unitVariants?: Array<{
    token: string;
    quantity: string;
    si: { value: number | string; unit: string; display: string };
    conv: { value: number | string; unit: string; display: string };
  }>;
  editorialStatus?: "authored-v2" | "needs-review";
};

export const QUESTION_CONTRACT_ENRICHMENT: Record<string, QuestionContractEnrichment> = {};
