import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch4 = [
  {
    slug: "major-depressive-disorder",
    title: "Major Depressive Disorder",
    bodySystem: "Psychiatric",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PMHNP", "ENP"],
    recognize: "Persistent depressed mood or loss of interest plus neurovegetative/cognitive symptoms with functional impairment suggests MDD. Always screen for bipolar history, substance effects, medical mimics, and suicide risk before treatment.",
    diagnostics: "Diagnosis is clinical; use a validated scale such as PHQ-9 to quantify severity and follow response. Target labs only when history/exam suggests a medical contributor.",
    priorities: "Match psychotherapy, medication, or combined therapy to severity, preference, comorbidity, pregnancy status, and prior response. Build a specific follow-up and safety plan rather than prescribing and disappearing.",
    medicationSafety: "SSRIs/SNRIs can initially increase activation or GI symptoms and carry sexual side effects; watch for serotonin toxicity, discontinuation symptoms, hyponatremia in susceptible adults, and drug interactions.",
    redFlags: "Active suicidal intent/plan, inability to maintain safety, psychosis, catatonia, severe self-neglect, or mania requires urgent/emergency psychiatric evaluation.",
    examTraps: "Do not diagnose unipolar depression without asking about past mania/hypomania. A positive depression screen is not the same as a full diagnosis.",
    sourceKeys: ["APA_MDD_CURRENT"],
  },
  {
    slug: "bipolar-disorder",
    title: "Bipolar Disorder",
    bodySystem: "Psychiatric",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PMHNP", "ENP"],
    recognize: "Episodic elevated/irritable mood with decreased need for sleep, increased energy, pressured speech, grandiosity, impulsivity, or psychosis suggests mania/hypomania. Depression may be the presenting complaint.",
    diagnostics: "Establish episode duration, impairment, psychosis, substance use, medications, sleep pattern, family history, and medical mimics. Baseline metabolic, pregnancy, renal/thyroid, or other labs depend on the planned medication.",
    priorities: "Acute mania often needs a mood stabilizer and/or antipsychotic; severe cases may require hospitalization. Long-term treatment focuses on relapse prevention, sleep regularity, adherence, and substance-risk reduction.",
    medicationSafety: "Lithium requires renal/thyroid monitoring and has a narrow therapeutic index; dehydration, NSAIDs, ACEi/ARBs, and thiazides can raise levels. Valproate carries major fetal risk.",
    redFlags: "Severe agitation, psychosis, dangerous impulsivity, inability to sleep for days, suicidality, or inability to care for self may require emergency treatment.",
    examTraps: "Antidepressant monotherapy can destabilize bipolar disorder. Irritability alone is not mania.",
    sourceKeys: ["APA_BIPOLAR_CURRENT"],
  },
  {
    slug: "psychosis-schizophrenia",
    title: "Psychosis & Schizophrenia Spectrum",
    bodySystem: "Psychiatric",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PMHNP", "ENP"],
    recognize: "Hallucinations, delusions, disorganization, negative symptoms, or markedly impaired reality testing require a differential that includes substances, delirium, mood disorders, neurologic disease, and medication effects.",
    diagnostics: "First-episode psychosis needs medical/substance review, focused neurologic exam, and targeted labs/toxicology; imaging is selective. Assess danger, command hallucinations, self-care capacity, catatonia, and cognitive fluctuation.",
    priorities: "Use antipsychotic therapy plus psychosocial treatment and coordinated specialty care when available. Address adherence, housing, substance use, physical health, and metabolic risk. Clozapine is a key option for treatment-resistant schizophrenia and selected patients with persistent suicide risk.",
    medicationSafety: "Second-generation antipsychotics vary in metabolic, prolactin, QT, EPS, and sedation profiles. Clozapine can cause severe neutropenia, myocarditis, seizures, constipation/ileus and metabolic toxicity; ongoing ANC monitoring remains recommended, but the FDA removed the mandatory U.S. Clozapine REMS in June 2025.",
    redFlags: "Violent/suicidal intent, severe self-neglect, delirium, catatonia, neuroleptic malignant syndrome, clozapine-associated myocarditis symptoms, severe constipation/ileus, or serious infection/neutropenia needs urgent care.",
    examTraps: "Do not assume new psychosis in an older adult is schizophrenia. Fluctuating attention strongly suggests delirium until proven otherwise, and do not teach REMS enrollment as a current U.S. clozapine requirement.",
    sourceKeys: ["APA_SCHIZOPHRENIA_CURRENT", "FDA_CLOZAPINE_REMS_REMOVED_2025"],
  },
  {
    slug: "adhd",
    title: "ADHD Across the Lifespan",
    bodySystem: "Psychiatric",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PMHNP", "PNP"],
    recognize: "Inattention and/or hyperactivity-impulsivity must be developmentally inappropriate, persistent, impairing, and present across settings; symptoms should trace back to childhood even when diagnosed in adults.",
    diagnostics: "Use collateral history and validated scales, and screen for sleep disorders, anxiety/depression, trauma, learning disorder, substance use, thyroid disease, and medication effects. Routine neuroimaging or broad lab panels are not diagnostic.",
    priorities: "Behavioral/environmental strategies matter; stimulants are often first-line when appropriate, with nonstimulants as alternatives. Track symptom function, BP/HR, growth in children, sleep, appetite, and misuse risk.",
    medicationSafety: "Stimulants can worsen insomnia, appetite loss, BP/HR, and misuse/diversion risk. Atomoxetine, alpha-2 agonists, and other nonstimulants have distinct adverse-effect and interaction profiles.",
    redFlags: "Acute mania, psychosis, severe substance misuse, suicidality, or cardiovascular symptoms during treatment requires reassessment/escalation.",
    examTraps: "High energy or poor school performance alone is not ADHD. Treating unrecognized bipolar disorder with a stimulant can worsen instability.",
    sourceKeys: ["AAP_ADHD_CURRENT", "APA_ADHD_CURRENT"],
  },
  {
    slug: "opioid-use-disorder",
    title: "Opioid Use Disorder",
    bodySystem: "Psychiatric",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PMHNP", "ENP"],
    recognize: "Loss of control, craving, hazardous use, tolerance/withdrawal, and continued use despite harm suggest OUD. Ask directly about fentanyl exposure, overdose history, injection risk, pregnancy, and co-use of benzodiazepines/alcohol.",
    diagnostics: "Diagnosis is clinical. Toxicology can inform care but cannot by itself diagnose OUD; screen for HIV, hepatitis, pregnancy, mental-health risk, and other substance use as appropriate.",
    priorities: "Offer evidence-based medication treatment—buprenorphine or methadone are core options; naltrexone is appropriate for selected fully opioid-free patients. Provide naloxone and harm-reduction counseling. A federal X-waiver is no longer required to prescribe buprenorphine for OUD; current controlled-substance requirements still apply.",
    medicationSafety: "Buprenorphine initiation strategy must account for recent opioid exposure to avoid precipitated withdrawal. Combining opioids with sedatives increases respiratory-depression risk, but benzodiazepine use alone is not a reason to withhold OUD treatment.",
    redFlags: "Overdose, severe withdrawal with medical instability, suicidality, pregnancy complications, or serious infection requires urgent care.",
    examTraps: "Detoxification alone has high relapse and overdose risk. A positive opioid screen does not distinguish prescribed use from OUD, and do not teach the obsolete federal X-waiver requirement.",
    sourceKeys: ["SAMHSA_OUD_CURRENT", "SAMHSA_MAT_ACT_CURRENT"],
  },
  {
    slug: "suicide-risk",
    title: "Suicide Risk Assessment",
    bodySystem: "Psychiatric",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PMHNP", "PNP", "WHNP", "ENP"],
    recognize: "Passive death wish, active suicidal thoughts, plan, intent, preparatory behavior, prior attempts, agitation, substance use, psychosis, hopelessness, and access to lethal means all matter. Ask directly; it does not 'put the idea in someone's head.'",
    diagnostics: "Use a structured suicide assessment to organize—not replace—clinical judgment. Identify protective factors, supports, access to firearms/medications, recent losses, intoxication, and the patient's ability to collaborate on safety.",
    priorities: "High/imminent risk requires constant safety measures and emergency psychiatric evaluation. Lower-risk patients still need a collaborative safety plan, lethal-means counseling, rapid follow-up, and treatment of the underlying disorder.",
    medicationSafety: "Antidepressant initiation requires monitoring for worsening suicidality/activation, especially in younger patients. Avoid giving large quantities of high-lethality medications to a high-risk patient when safer dispensing is possible.",
    redFlags: "Current intent, specific plan with means, recent attempt, command hallucinations, severe intoxication, or inability/unwillingness to maintain safety = emergency.",
    examTraps: "A 'no-suicide contract' is not a safety plan and does not reduce clinician responsibility. Do not downgrade risk because the patient is calm.",
    sourceKeys: ["SAMHSA_SUICIDE_CURRENT"],
  },
  {
    slug: "well-child-development",
    title: "Well-Child Care & Development",
    bodySystem: "Pediatrics",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PNP"],
    recognize: "Well-child care is active surveillance: growth, development, behavior, nutrition, sleep, safety, school, family context, oral health, and age-appropriate risk screening.",
    diagnostics: "Plot growth correctly and look at trajectory, not one percentile. Use validated developmental/autism/behavioral screens at recommended ages and follow up abnormal screens with targeted evaluation or referral.",
    priorities: "Prioritize anticipatory guidance, immunization, injury prevention, nutrition, sleep, and early-intervention referral when milestones or social determinants raise concern.",
    medicationSafety: "Medication dosing in children is weight-based when appropriate; verify concentration and maximum dose. Avoid OTC cough/cold products in young children when not recommended.",
    redFlags: "Loss of milestones, signs of abuse, failure to thrive with instability, cyanosis, severe dehydration, or concerning neurologic findings needs urgent evaluation.",
    examTraps: "Crossing percentiles can matter more than being small. A parent concern about development deserves evaluation even if a brief office observation looks normal.",
    sourceKeys: ["AAP_BRIGHT_FUTURES_CURRENT", "CDC_VACCINES_2026"],
  },
  {
    slug: "pediatric-fever",
    title: "Fever in Infants & Children",
    bodySystem: "Pediatrics",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PNP", "ENP"],
    recognize: "Age changes everything. A febrile neonate/young infant has a much lower threshold for invasive bacterial infection evaluation than an immunized older child who looks well.",
    diagnostics: "Assess appearance, hydration, respiratory effort, perfusion, source, immunization, age, and risk factors. Testing is age- and risk-stratified rather than 'CBC for every fever.'",
    priorities: "Treat discomfort and dehydration, not the thermometer alone. Young infants and toxic-appearing children need protocol-driven evaluation and often parenteral antibiotics after cultures when indicated.",
    medicationSafety: "Use weight-based acetaminophen/ibuprofen when age-appropriate; avoid aspirin in children with viral illness. Never alternate antipyretics casually if it creates dosing confusion.",
    redFlags: "Poor perfusion, lethargy, meningismus, petechiae/purpura, respiratory distress, dehydration, seizure with concerning features, or fever in a very young infant requires urgent/emergency evaluation.",
    examTraps: "Teething does not explain a true high fever. Response to antipyretics does not distinguish viral from bacterial illness.",
    sourceKeys: ["AAP_FEBRILE_INFANT_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
