import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch26 = [
  {
    slug: "autism-spectrum-disorder",
    title: "Autism Spectrum Disorder",
    bodySystem: "Psychiatric",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PMHNP", "PNP"],
    recognize: "Persistent social-communication differences plus restricted/repetitive behaviors, sensory differences or inflexible routines beginning in the developmental period suggest autism. Presentation varies widely and can be masked, particularly in girls and adults.",
    diagnostics: "Use developmental history, caregiver/school information and validated screening to identify concern, then refer for comprehensive diagnostic assessment when needed. Evaluate hearing, language, intellectual/developmental profile, ADHD, anxiety, sleep and genetic features based on presentation.",
    priorities: "Support communication, adaptive function, school/community accommodations, caregiver needs and co-occurring conditions. Early developmental, speech-language, occupational and behavioral supports should be individualized and neurodiversity-respecting rather than aimed at erasing harmless autistic traits.",
    medicationSafety: "No medication treats the core social-communication features of autism. Risperidone/aripiprazole can reduce severe irritability in selected patients but carry metabolic, neurologic and prolactin risks; avoid polypharmacy for nonspecific behavior without defining the target symptom.",
    redFlags: "Developmental regression, seizure, self-injury, aggression with danger, severe food restriction/dehydration, catatonia or acute loss of function requires urgent targeted evaluation.",
    examTraps: "A normal brief eye-contact moment does not exclude autism. Screening tools identify risk; they do not replace a diagnostic developmental assessment.",
    sourceKeys: ["AAP_AUTISM_CURRENT", "APA_DSM5TR_AUTISM_CURRENT"],
  },
  {
    slug: "oppositional-defiant-conduct-disorders",
    title: "Oppositional Defiant & Conduct Disorders",
    bodySystem: "Psychiatric",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PMHNP", "PNP"],
    recognize: "ODD involves a persistent pattern of angry/irritable mood and argumentative/defiant behavior; conduct disorder adds aggression, serious rule violations, property destruction, theft or deceit that violates others' rights. Context and developmental appropriateness matter.",
    diagnostics: "Obtain multi-setting collateral information and assess ADHD, trauma, mood disorders, learning problems, autism, substance use, family stress, sleep and safety. Determine whether behavior is pervasive or occurs only in one conflictual environment.",
    priorities: "Parent-management training and family/school behavioral interventions are central; treat comorbid ADHD, depression, anxiety or trauma when present. Conduct disorder with aggression requires intensive psychosocial and safety planning.",
    medicationSafety: "Medication is not first-line for ODD itself. Antipsychotics may be used short-term for severe aggression in selected complex cases but require metabolic/EPS monitoring and a defined target and stop plan.",
    redFlags: "Weapon use, cruelty, fire-setting, severe aggression, suicidal behavior, exploitation, abuse exposure or inability to maintain safety requires urgent mental-health and safeguarding intervention.",
    examTraps: "Do not label developmentally normal limit-testing as ODD. A disruptive child may have untreated ADHD, trauma, language/learning disorder or autism that changes treatment.",
    sourceKeys: ["AACAP_DISRUPTIVE_CURRENT", "APA_DSM5TR_CURRENT"],
  },
  {
    slug: "somatic-symptom-illness-anxiety",
    title: "Somatic Symptom & Illness Anxiety Disorders",
    bodySystem: "Psychiatric",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PMHNP"],
    recognize: "Persistent excessive health-related thoughts, anxiety or behaviors can constitute somatic symptom or illness-anxiety disorder whether or not a real medical condition is present. The diagnosis is not shorthand for 'symptoms are imaginary.'",
    diagnostics: "Complete an appropriate medical assessment based on symptoms and red flags, then review prior testing, health anxiety, checking/reassurance behaviors, trauma, depression, anxiety and functional impact. Avoid repeating low-value tests solely to temporarily reduce anxiety.",
    priorities: "Use one coordinating clinician, scheduled follow-up, validation of suffering, functional goals and CBT or other evidence-based psychotherapy. Treat comorbid anxiety/depression and pursue new medical findings normally rather than dismissing them.",
    medicationSafety: "SSRIs/SNRIs may help comorbid anxiety/depression but are not substitutes for a therapeutic plan. Repeated sedative, opioid or unnecessary medical prescribing can reinforce symptoms and cause harm.",
    redFlags: "Objective neurologic deficit, weight loss, GI bleeding, fever, cardiopulmonary instability, suicidality or genuinely new high-risk symptoms requires standard medical/emergency evaluation regardless of psychiatric history.",
    examTraps: "A psychiatric diagnosis never removes the need to evaluate new red flags. The presence of genuine chronic disease does not exclude somatic symptom disorder if disproportionate distress/behavior is also present.",
    sourceKeys: ["APA_DSM5TR_SOMATIC_CURRENT"],
  },
  {
    slug: "cannabis-use-disorder",
    title: "Cannabis Use Disorder & Cannabis-Related Syndromes",
    bodySystem: "Psychiatric",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PMHNP", "PNP", "WHNP", "ENP"],
    recognize: "Loss of control, tolerance, withdrawal, impaired function and continued cannabis use despite harm suggests cannabis use disorder. Heavy use may contribute to anxiety, psychosis, cognitive impairment and recurrent hyperemesis relieved by hot bathing.",
    diagnostics: "Diagnosis is clinical; urine cannabinoid testing demonstrates exposure but not timing, impairment or disorder severity. Assess pregnancy, adolescent development, psychosis/bipolar risk, driving, co-use and cyclic vomiting patterns.",
    priorities: "Use motivational interviewing, CBT/contingency-based approaches and treatment of co-occurring conditions. Cannabis hyperemesis requires cessation counseling plus acute hydration/antiemetic strategies and exclusion of dangerous abdominal diagnoses.",
    medicationSafety: "No medication is universally approved to cure cannabis use disorder. Avoid compounding sedation with alcohol, opioids or benzodiazepines, and counsel that high-potency THC products increase psychiatric and impairment risks.",
    redFlags: "Psychosis with danger, severe dehydration/AKI from hyperemesis, suicidal behavior, pregnancy with severe vomiting or intoxication-related trauma requires urgent care.",
    examTraps: "A positive urine screen can remain positive long after intoxication. 'Medical' or legal status does not eliminate dependence, pregnancy, driving or psychosis risks.",
    sourceKeys: ["SAMHSA_CANNABIS_CURRENT", "APA_DSM5TR_CURRENT"],
  },
  {
    slug: "sedative-hypnotic-use-disorder",
    title: "Sedative-Hypnotic Use Disorder & Withdrawal",
    bodySystem: "Psychiatric",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PMHNP", "ENP"],
    recognize: "Escalating benzodiazepine or sedative use, early refills, impaired function, tolerance, withdrawal anxiety/insomnia/tremor and continued use despite harm suggests a sedative-use disorder. Abrupt withdrawal can be medically dangerous.",
    diagnostics: "Establish exact agent, dose, duration, last use, alcohol/opioid co-use and prior withdrawal seizure. Toxicology may support exposure but often misses some benzodiazepines and does not quantify dependence.",
    priorities: "Stabilize high-risk withdrawal and use an individualized gradual taper, often with specialty addiction/psychiatric support. Treat the underlying insomnia/anxiety with nondependence-forming therapies and address co-occurring substance use.",
    medicationSafety: "Abrupt benzodiazepine discontinuation can cause seizure, delirium and death. Combining benzodiazepines with opioids/alcohol markedly increases respiratory-depression risk; taper speed must account for dependence and patient stability.",
    redFlags: "Seizure, delirium, severe autonomic instability, hallucinations, high-dose short-acting dependence, pregnancy or concurrent alcohol withdrawal requires urgent monitored treatment.",
    examTraps: "Do not equate physiologic dependence from prescribed long-term use with addiction automatically, but do not dismiss misuse because the medication was initially prescribed.",
    sourceKeys: ["ASAM_BENZODIAZEPINE_TAPER_CURRENT", "SAMHSA_SEDATIVE_CURRENT"],
  },
  {
    slug: "pediatric-constipation",
    title: "Pediatric Constipation",
    bodySystem: "Pediatrics",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PNP"],
    recognize: "Infrequent painful hard stools, stool withholding, large-caliber stool, abdominal pain or overflow soiling commonly reflects functional constipation. Age at onset and growth or neurologic features determine whether an organic cause is likely.",
    diagnostics: "Functional constipation is usually diagnosed clinically. Look for delayed meconium passage, poor growth, severe distention, abnormal anus/spine/reflexes, blood without fissure or systemic endocrine/metabolic signs before ordering targeted testing.",
    priorities: "Disimpact when needed, then use maintenance osmotic laxative therapy, scheduled toilet sitting, positive reinforcement and adequate duration to prevent painful relapse. Family education about chronicity is essential.",
    medicationSafety: "Polyethylene glycol is commonly first-line and can require substantial maintenance dosing; do not use repeated enemas or stimulant rescue as the entire long-term strategy. Avoid mineral oil in aspiration-risk children.",
    redFlags: "Bilious vomiting, severe distention, failure to thrive, neurologic deficits, fever/toxicity, neonatal onset or suspected Hirschsprung disease requires urgent/specialty evaluation.",
    examTraps: "Overflow stool can be fecal impaction, not diarrhea. A normal abdominal x-ray is not required to diagnose typical functional constipation.",
    sourceKeys: ["NASPGHAN_CONSTIPATION_CURRENT", "AAP_CONSTIPATION_CURRENT"],
  },
  {
    slug: "adolescent-confidential-care",
    title: "Adolescent Confidential & Preventive Care",
    bodySystem: "Pediatrics",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PNP", "WHNP", "PMHNP"],
    recognize: "High-quality adolescent care includes private time with the clinician and confidential assessment of mood/suicide risk, substance use, sexuality, contraception/STIs, safety, school, eating, sleep and relationships while still encouraging healthy family involvement.",
    diagnostics: "Explain confidentiality and its limits before sensitive questions, use validated screening when appropriate, and know state-specific minor-consent rules plus federal protections and EHR/portal confidentiality limitations.",
    priorities: "Provide age-appropriate preventive services, vaccinations, STI/HIV testing and contraception according to current guidance, address mental health and safety, and help adolescents transition toward independent health-management skills.",
    medicationSafety: "Before prescribing sensitive medications, consider pharmacy claims, portal access and after-visit summaries that could inadvertently disclose confidential care. Medication decisions still require pregnancy, interaction, misuse and suicide-safety assessment.",
    redFlags: "Active suicidality, abuse/exploitation, trafficking, severe eating disorder, dangerous intoxication, violence or inability to maintain immediate safety overrides routine confidentiality and requires protective intervention under applicable law.",
    examTraps: "Confidentiality is not absolute, but routine parental presence throughout the entire visit undermines recommended adolescent care. Consent and confidentiality laws vary by state, so do not invent one national age rule.",
    sourceKeys: ["AAP_ADOLESCENT_CONFIDENTIALITY_2024", "AAP_ADOLESCENT_CONTRACEPTION_2024"],
  },
  {
    slug: "uterine-fibroids",
    title: "Uterine Fibroids",
    bodySystem: "Reproductive",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "WHNP"],
    recognize: "Leiomyomas can cause heavy/prolonged menstrual bleeding, bulk pressure, urinary or bowel symptoms, infertility, recurrent pregnancy complications or pain, but many are incidental. Rapidly changing symptoms still require assessment rather than assuming benign fibroids.",
    diagnostics: "Pregnancy testing and CBC are foundational when bleeding is present; pelvic ultrasound usually defines number, location and size. Use endometrial sampling based on age/risk and MRI selectively for complex anatomy or procedural planning.",
    priorities: "Management is guided by symptom severity, anemia, fibroid location/size, fertility and uterine-preservation goals: observation, hormonal/nonhormonal medical therapy, uterine artery embolization, myomectomy or hysterectomy are different tools for different goals.",
    medicationSafety: "Combined hormonal methods and tranexamic acid require thrombosis-risk review; GnRH agonist/antagonist strategies can cause hypoestrogenic effects and require duration/add-back planning. Correct iron deficiency from chronic bleeding.",
    redFlags: "Hemodynamic bleeding, severe anemia, pregnancy with acute pain/bleeding, postmenopausal growth or bleeding, rapidly enlarging atypical mass or torsion/degeneration with diagnostic uncertainty requires urgent/expedited gynecologic evaluation.",
    examTraps: "Fibroids are benign, but not every pelvic mass or abnormal bleeding episode in a patient with known fibroids should be attributed to them. Treatment choice depends heavily on fertility goals.",
    sourceKeys: ["ACOG_FIBROIDS_2025", "ACOG_AUB_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
