import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch14 = [
  {
    slug: "chronic-coronary-disease-stable-angina",
    title: "Chronic Coronary Disease & Stable Angina",
    bodySystem: "Cardiovascular",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Predictable exertional pressure or dyspnea relieved by rest suggests chronic coronary disease, but any new, accelerating, rest, prolonged, or unstable pattern must be treated as possible ACS rather than routine stable angina.",
    diagnostics: "Assess ECG, lipids, diabetes, kidney function, anemia and overall ASCVD risk; choose stress imaging, coronary CT angiography, or invasive evaluation according to pretest probability, symptoms, exercise capacity, prior disease, and local capability.",
    priorities: "Use secondary-prevention therapy, antianginal treatment, smoking cessation, exercise or cardiac rehabilitation, and control of BP, lipids and diabetes. Refer for revascularization evaluation when symptoms persist despite optimal therapy or high-risk anatomy is suspected.",
    medicationSafety: "Nitrates are contraindicated with recent PDE-5 inhibitors and can cause hypotension. Beta blockers and calcium-channel blockers require heart-rate, conduction and BP awareness; antiplatelet intensity depends on ischemic and bleeding risk.",
    redFlags: "Rest pain, dynamic ECG change, rising troponin, syncope, acute heart failure, refractory symptoms, or hemodynamic instability requires emergency ACS evaluation.",
    examTraps: "Do not call new chest pain stable because the patient already has CAD. Normal resting ECG and absence of pain in clinic do not exclude significant ischemia.",
    sourceKeys: ["ACC_CCD_2023", "ACS_2025"],
  },
  {
    slug: "valvular-heart-disease",
    title: "Valvular Heart Disease",
    bodySystem: "Cardiovascular",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP"],
    recognize: "New murmur plus exertional dyspnea, syncope, chest pain, heart failure, embolic symptoms, or atrial fibrillation raises concern for clinically significant valve disease. Symptoms and ventricular response matter more than murmur loudness alone.",
    diagnostics: "Transthoracic echocardiography defines valve anatomy, gradients, regurgitation severity, ventricular size/function and pulmonary pressures. ECG, chest imaging, exercise testing, TEE or catheterization answer selected staging or procedural questions.",
    priorities: "Treat congestion and comorbid disease while referring at guideline thresholds for repair or replacement before irreversible ventricular damage occurs. Severe symptomatic aortic stenosis and selected severe mitral disease require timely valve-team evaluation.",
    medicationSafety: "Vasodilators and diuretics can worsen hypotension in fixed severe outflow obstruction if used aggressively. Mechanical prosthetic valves require warfarin-based anticoagulation rather than a DOAC.",
    redFlags: "Syncope or angina with severe aortic stenosis, acute severe regurgitation, pulmonary edema, cardiogenic shock, or prosthetic-valve dysfunction requires urgent cardiology or emergency management.",
    examTraps: "Do not use medication as a substitute for definitive treatment of severe symptomatic mechanical valve disease. A soft murmur can still accompany severe low-flow aortic stenosis.",
    sourceKeys: ["ACC_AHA_VALVE_CURRENT"],
  },
  {
    slug: "infective-endocarditis",
    title: "Infective Endocarditis",
    bodySystem: "Cardiovascular",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Persistent fever with a new or changing murmur, embolic phenomena, unexplained bacteremia, prosthetic valve, intracardiac device, injection drug use, or recent invasive infection should raise concern for endocarditis.",
    diagnostics: "Obtain multiple blood-culture sets before antibiotics when the patient is stable enough, then perform echocardiography; TEE is more sensitive when prosthetic material, devices, complications, or high suspicion remain despite nondiagnostic TTE.",
    priorities: "Use prolonged organism-directed IV antibiotics with infectious-disease and cardiology collaboration. Evaluate early for surgery when there is heart failure, uncontrolled infection, abscess, prosthetic complication, recurrent embolization, or destructive valve disease.",
    medicationSafety: "Empiric antibiotics should reflect native versus prosthetic valve status and healthcare exposure, then narrow to susceptibilities. Aminoglycosides and other agents may require renal or serum-level monitoring.",
    redFlags: "Acute heart failure, stroke, conduction block, persistent bacteremia, periannular abscess, septic shock, or prosthetic dehiscence requires urgent specialty and often surgical escalation.",
    examTraps: "Do not give prophylactic antibiotics for every murmur or dental procedure; prophylaxis is reserved for specific highest-risk cardiac conditions and procedures. Negative early cultures do not exclude partially treated endocarditis.",
    sourceKeys: ["AHA_ENDOCARDITIS_CURRENT"],
  },
  {
    slug: "pericarditis-effusion",
    title: "Pericarditis & Pericardial Effusion",
    bodySystem: "Cardiovascular",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Sharp pleuritic chest pain improved by sitting forward, diffuse ST or PR changes, and a rub suggest acute pericarditis. Effusion may be silent until dyspnea, tachycardia, elevated JVP, pulsus paradoxus, or tamponade physiology develops.",
    diagnostics: "Use ECG, inflammatory markers, troponin, chest imaging and echocardiography to assess effusion and ventricular interaction. Search for post-viral, autoimmune, renal, malignant, post-MI, medication, TB, and procedural causes when clinically indicated.",
    priorities: "Uncomplicated idiopathic or viral pericarditis is commonly treated with an NSAID or aspirin plus colchicine and activity restriction. Large, symptomatic, purulent, malignant, or hemodynamically significant effusions require specialist drainage strategy.",
    medicationSafety: "NSAID choice depends on renal, GI, anticoagulant and cardiovascular risk; colchicine requires renal/hepatic and interaction review. Anticoagulation can worsen hemorrhagic effusion risk in selected contexts.",
    redFlags: "Hypotension, rising JVP, tachycardia, electrical alternans, severe dyspnea, right-sided chamber collapse, or shock suggests tamponade and requires emergency drainage-capable care.",
    examTraps: "Do not mistake diffuse pericarditis ST elevation for a territorial STEMI, but also do not dismiss focal ischemic changes as pericarditis. Beck triad is insensitive and may be absent.",
    sourceKeys: ["ACC_PERICARDITIS_CURRENT", "ESC_PERICARDIAL_CURRENT"],
  },
  {
    slug: "aortic-aneurysm-dissection",
    title: "Aortic Aneurysm & Acute Aortic Syndrome",
    bodySystem: "Cardiovascular",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Abrupt severe chest, back, or abdominal pain, pulse or BP asymmetry, neurologic deficit, new aortic regurgitation, syncope, or malperfusion should trigger acute aortic syndrome thinking. Many aneurysms are asymptomatic until expansion or rupture.",
    diagnostics: "Use urgent CT angiography for most stable suspected dissections, with TEE or MRI in selected circumstances. Chronic aneurysm management requires standardized serial imaging and attention to diameter, growth, valve anatomy, genetic syndrome and family history.",
    priorities: "Acute dissection needs rapid anti-impulse therapy, pain control and immediate surgical or vascular consultation; type A disease is generally a surgical emergency. Chronic aneurysm care focuses BP control, smoking cessation and threshold-based repair.",
    medicationSafety: "In acute dissection, beta blockade generally precedes vasodilator therapy to avoid reflex shear stress. Avoid thrombolysis or routine anticoagulation when dissection is a plausible stroke or chest-pain mimic.",
    redFlags: "Shock, tamponade, new focal neurologic deficit, limb or mesenteric ischemia, rupture, severe aortic regurgitation, or type A dissection requires immediate emergency surgery-capable care.",
    examTraps: "Do not require a tearing description or pulse deficit; both can be absent. A widened mediastinum is neither sensitive nor sufficient to exclude or confirm dissection.",
    sourceKeys: ["ACC_AHA_AORTIC_2022"],
  },
  {
    slug: "peripheral-artery-disease",
    title: "Peripheral Artery Disease",
    bodySystem: "Cardiovascular",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Exertional calf, thigh, or buttock discomfort relieved by rest, diminished pulses, poor wound healing, dependent rubor, or ischemic foot symptoms suggest PAD; many patients have atypical leg symptoms rather than classic claudication.",
    diagnostics: "Resting ABI is first-line when PAD is suspected, with exercise ABI, toe pressures, duplex, CTA or MRA used when ABI is nondiagnostic or anatomy is needed. Assess coronary, cerebrovascular, diabetes and smoking risk concurrently.",
    priorities: "Use antiplatelet and intensive lipid therapy when indicated, smoking cessation, structured exercise, foot care and risk-factor control. Revascularization is for lifestyle-limiting symptoms despite therapy or limb-threatening ischemia.",
    medicationSafety: "Cilostazol can improve claudication but is contraindicated in heart failure. Antithrombotic intensification can reduce ischemic events in selected patients but increases bleeding risk.",
    redFlags: "Sudden pain, pallor, pulselessness, paresthesia, paralysis or poikilothermia suggests acute limb ischemia and requires immediate vascular emergency evaluation.",
    examTraps: "Normal palpable pulses do not exclude PAD in every patient, and neuropathic pain can coexist. Do not advise complete activity avoidance for claudication; supervised or structured walking is therapeutic.",
    sourceKeys: ["ACC_AHA_PAD_2024"],
  },
  {
    slug: "syncope-evaluation",
    title: "Syncope Evaluation",
    bodySystem: "Cardiovascular",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "True syncope is transient loss of consciousness from global cerebral hypoperfusion with rapid recovery. Distinguish vasovagal, orthostatic, cardiac, seizure, metabolic, intoxication, and psychogenic events using witness history and prodrome.",
    diagnostics: "Obtain orthostatic vitals and ECG in essentially all unexplained syncope; targeted CBC, glucose, pregnancy test, echocardiography, ambulatory rhythm monitoring, or neurologic testing follows the suspected cause rather than a universal panel.",
    priorities: "Low-risk reflex or orthostatic syncope can often be managed with education and cause correction. Exertional, supine, arrhythmic, structural-heart, severe anemia/bleeding, or family sudden-death patterns need expedited cardiac evaluation.",
    medicationSafety: "Review diuretics, antihypertensives, alpha blockers, QT-prolonging agents and sedatives. Do not add pressor drugs for orthostasis before correcting dehydration and medication contributors when possible.",
    redFlags: "Syncope during exertion or while supine, abnormal ECG, chest pain, severe dyspnea, structural heart disease, GI bleeding, persistent neurologic deficit, or family history of sudden death requires urgent evaluation.",
    examTraps: "Do not order head CT for uncomplicated syncope without trauma or neurologic findings. Brief myoclonic movements can occur in syncope and do not automatically prove epilepsy.",
    sourceKeys: ["ACC_AHA_HRS_SYNCOPE_CURRENT"],
  },
  {
    slug: "cardiomyopathy-myocarditis",
    title: "Cardiomyopathy & Myocarditis",
    bodySystem: "Cardiovascular",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Unexplained heart failure, chest pain after viral illness, arrhythmia, syncope, family sudden death, abnormal ECG, or disproportionate dyspnea may reflect myocarditis or genetic, hypertrophic, dilated, infiltrative, or stress cardiomyopathy.",
    diagnostics: "Use ECG, troponin or BNP when indicated, echocardiography and cardiac MRI for tissue characterization; coronary evaluation excludes ischemic disease in appropriate adults. Family history and genetic counseling/testing matter in selected cardiomyopathies.",
    priorities: "Treat heart failure and arrhythmias by phenotype, restrict intense exercise during active myocarditis, and refer for cardiology/genetics when inherited disease is possible. HCM management includes sudden-death risk stratification and family screening.",
    medicationSafety: "Avoid drugs that worsen outflow obstruction or hypotension in obstructive HCM without specialist reasoning. NSAIDs can worsen fluid retention in heart failure; stimulant and QT-prolonging drugs require careful review in arrhythmic disease.",
    redFlags: "Cardiogenic shock, sustained ventricular arrhythmia, high-grade block, exertional syncope, rapidly falling EF, or fulminant myocarditis requires emergency or advanced-heart-failure care.",
    examTraps: "A young patient with chest pain and elevated troponin does not automatically have coronary ACS. Do not clear athletes with suspected myocarditis for intense exercise simply because symptoms improved.",
    sourceKeys: ["AHA_MYOCARDITIS_CURRENT", "ACC_HCM_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
