import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch45 = [
  {
    slug: "rheumatoid-arthritis-management",
    title: "Rheumatoid Arthritis: Diagnosis & Disease-Modifying Therapy",
    titleAliases: ["Rheumatoid Arthritis: Autoimmune Pathophysiology & Disease-Modifying Therapy"],
    slugAliases: ["np-clinical-rheumatoid-arthritis"],
    bodySystem: "Musculoskeletal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "Persistent inflammatory symmetric small-joint pain/swelling, morning stiffness, reduced grip and systemic symptoms suggest RA. Early disease can be seronegative and joint damage begins before deformities appear; distinguish from OA, viral arthritis, psoriatic disease, crystal arthritis and lupus.",
    diagnostics: "Document objective synovitis and obtain RF/anti-CCP, ESR/CRP, CBC/CMP and baseline imaging as appropriate; anti-CCP is highly specific but neither RF nor anti-CCP alone diagnoses RA. Before immunosuppressive therapy screen TB/hepatitis and vaccinations according to the planned agent.",
    priorities: "Refer early to rheumatology and initiate a conventional synthetic DMARD—methotrexate is preferred for many patients with moderate-high disease activity—using treat-to-target follow-up rather than prolonged NSAID/steroid-only care. Escalate/adjust DMARD strategy when remission or low disease activity is not achieved.",
    medicationSafety: "Methotrexate is weekly, not daily, and requires CBC/liver/renal monitoring, folate and pregnancy avoidance; biologics/JAK inhibitors increase infection risk and have class-specific warnings. Glucocorticoids should be minimized because cumulative toxicity is substantial.",
    redFlags: "Atlantoaxial instability symptoms, rapidly progressive neurologic deficit, septic-appearing monoarthritis, severe infection on immunosuppression, vasculitis or significant lung disease requires urgent specialty evaluation.",
    examTraps: "Do not wait for erosions or positive RF before referral and do not use repeated prednisone bursts as disease-modifying treatment. A patient with RA and one acutely hot joint can still have septic arthritis.",
    sourceKeys: ["ACR_RA_CURRENT"],
  },
  {
    slug: "systemic-lupus-erythematosus",
    title: "Systemic Lupus Erythematosus",
    bodySystem: "Musculoskeletal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "WHNP"],
    recognize: "SLE is a multisystem autoimmune disease that may combine inflammatory arthritis, photosensitive rash, oral ulcers, cytopenias, serositis, kidney disease, neurologic symptoms and thrombosis/pregnancy complications. Symptoms fluctuate and isolated positive ANA does not equal lupus.",
    diagnostics: "Use ANA as a sensitive entry test and disease-specific antibodies, complements, CBC, creatinine and urinalysis/protein quantification to establish phenotype and activity. New proteinuria/active urine sediment requires lupus-nephritis evaluation and often kidney biopsy to guide therapy.",
    priorities: "Hydroxychloroquine is foundational for most patients unless contraindicated, with sun protection and aggressive cardiovascular risk management. Organ-threatening renal, neurologic, hematologic or vasculitic disease requires rheumatology-directed immunosuppression matched to severity and pregnancy plans.",
    medicationSafety: "Hydroxychloroquine needs weight-appropriate dosing and retinal screening; immunosuppressants carry infection/fertility/teratogenic risks. Mycophenolate and methotrexate are teratogenic, whereas pregnancy-compatible lupus regimens must be planned before conception.",
    redFlags: "Rapidly rising creatinine, nephritic urine, severe cytopenia/hemolysis, CNS lupus, pulmonary hemorrhage, myocarditis, thrombosis or pregnancy with severe flare requires urgent specialty/inpatient care.",
    examTraps: "Do not diagnose SLE from ANA alone and do not stop hydroxychloroquine automatically during pregnancy when it remains indicated. Normal complement does not exclude every clinically important flare.",
    sourceKeys: ["ACR_SLE_2025", "ACR_LUPUS_NEPHRITIS_CURRENT"],
  },
  {
    slug: "axial-spondyloarthritis",
    title: "Axial Spondyloarthritis",
    bodySystem: "Musculoskeletal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "Inflammatory back pain beginning at younger age with morning stiffness, improvement with activity, alternating buttock pain, enthesitis, uveitis, psoriasis or IBD suggests axial spondyloarthritis. Normal plain films do not exclude nonradiographic disease.",
    diagnostics: "Assess inflammatory features and extra-articular disease; obtain CRP and pelvic radiographs, using SI-joint MRI when suspicion remains despite nondiagnostic radiography. HLA-B27 modifies probability but is neither necessary nor sufficient for diagnosis.",
    priorities: "Exercise/physical therapy and NSAIDs are first-line for many patients; persistent active axial disease warrants rheumatology referral for TNF- or IL-17-targeted therapy and other current options. Treat uveitis, psoriasis and IBD in a coordinated way because comorbidity can influence biologic choice.",
    medicationSafety: "Long-term systemic glucocorticoids are not recommended for axial disease. Biologics require infection/TB/hepatitis screening and vaccination planning; IL-17 blockade can aggravate inflammatory bowel disease in some patients.",
    redFlags: "Acute painful photophobic red eye, new neurologic deficit/cauda-equina symptoms, unstable spinal fracture after minor trauma in advanced ankylosis or severe infection on biologic therapy requires urgent care.",
    examTraps: "HLA-B27 positivity is not a diagnosis and mechanical back pain can coexist. Do not wait for bamboo-spine radiographs before recognizing inflammatory axial disease.",
    sourceKeys: ["ACR_SPA_CURRENT", "ASAS_SPA_CURRENT"],
  },
  {
    slug: "psoriatic-arthritis",
    title: "Psoriatic Arthritis",
    bodySystem: "Musculoskeletal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "Psoriatic arthritis can produce asymmetric oligoarthritis, symmetric polyarthritis, DIP disease, dactylitis, enthesitis or axial symptoms; nail pitting/onycholysis and hidden scalp/intergluteal psoriasis are important clues. Arthritis may precede obvious skin psoriasis.",
    diagnostics: "Diagnosis is clinical after documenting inflammatory joint/enthesis disease and psoriasis features while excluding RA, gout and other causes. ESR/CRP and imaging support activity/damage but may be normal; RF/anti-CCP can occasionally be positive and do not automatically redefine the disease.",
    priorities: "Refer active disease early for treat-to-target DMARD therapy; biologic or targeted treatment is chosen by peripheral versus axial disease, enthesitis, skin severity and comorbid IBD/uveitis. NSAIDs help symptoms but do not prevent structural damage.",
    medicationSafety: "Methotrexate and targeted immune agents require pregnancy, liver, marrow, infection and interaction review. Systemic corticosteroid use is minimized because of metabolic harm and concern for psoriasis destabilization; immunosuppression requires vaccination/infection planning.",
    redFlags: "Rapidly destructive arthritis, severe uveitis, systemic infection on immunosuppression or a single acutely hot joint with septic arthritis concern needs urgent evaluation.",
    examTraps: "Do not require visible plaque psoriasis at the first arthritis visit and do not classify DIP inflammation with nail disease as routine OA without examining for psoriasis.",
    sourceKeys: ["ACR_NPF_PSA_CURRENT"],
  },
  {
    slug: "inflammatory-myopathy",
    title: "Inflammatory Myopathy: Dermatomyositis & Polymyositis Patterns",
    bodySystem: "Musculoskeletal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP"],
    recognize: "Subacute symmetric proximal weakness—difficulty rising, climbing stairs or lifting arms—suggests inflammatory myopathy; dermatomyositis adds heliotrope/Gottron or other characteristic skin findings. Consider statin-associated immune necrotizing myopathy, inclusion-body myositis, endocrine/electrolyte disease and neuromuscular mimics.",
    diagnostics: "Check CK/aldolase, AST/ALT, inflammatory markers and myositis antibodies, then use EMG/MRI and selective muscle/skin biopsy to define phenotype. Screen for ILD and age/phenotype-appropriate malignancy because several myositis subsets carry increased cancer risk.",
    priorities: "Use rheumatology/neuromuscular expertise for glucocorticoid plus steroid-sparing immunotherapy matched to subtype and organ disease, alongside physical rehabilitation. Rapidly progressive ILD or dysphagia requires aggressive multidisciplinary care.",
    medicationSafety: "Immunosuppressants carry infection and organ-specific toxicity; glucocorticoid myopathy can paradoxically worsen proximal weakness during treatment. Statin-associated immune-mediated necrotizing myopathy persists despite statin withdrawal and requires immunotherapy.",
    redFlags: "Respiratory muscle weakness, aspiration/dysphagia, myocarditis/arrhythmia, rapidly progressive ILD or severe rhabdomyolysis/AKI requires urgent inpatient care.",
    examTraps: "Myalgia without objective weakness/CK elevation is not inflammatory myositis, and a patient on steroids who becomes weaker may have steroid myopathy rather than uncontrolled inflammation.",
    sourceKeys: ["ACR_IIM_CURRENT"],
  },
  {
    slug: "polymyalgia-rheumatica",
    title: "Polymyalgia Rheumatica",
    bodySystem: "Musculoskeletal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "New bilateral shoulder and/or hip girdle aching with pronounced morning stiffness in an adult over 50 plus elevated inflammatory markers suggests PMR. True objective muscle weakness is not typical and should redirect the differential toward myopathy or neurologic disease.",
    diagnostics: "Use ESR/CRP, CBC/CMP and targeted testing to exclude infection, malignancy, thyroid disease, RA and myopathy. Ask every patient about giant-cell arteritis symptoms—new headache, scalp tenderness, jaw claudication or visual symptoms—because the two diseases overlap.",
    priorities: "Treat uncomplicated PMR with low-to-moderate dose glucocorticoid followed by a slow individualized taper, reassessing symptoms and inflammatory markers; recurrent/prolonged disease may need rheumatology and steroid-sparing therapy.",
    medicationSafety: "Plan bone, glucose, BP and infection risk mitigation for prolonged glucocorticoid use; steroid response supports but does not prove the diagnosis. Never use a low PMR steroid dose when visual-threatening GCA is suspected.",
    redFlags: "Any new visual symptom, jaw claudication, focal neurologic deficit or aortic ischemic symptom suggests GCA and requires immediate high-dose steroid treatment and urgent specialist evaluation.",
    examTraps: "Do not diagnose PMR in a younger adult and do not call pain-limited movement true muscle weakness. Normal inflammatory markers make classic PMR less likely and warrant diagnostic reconsideration.",
    sourceKeys: ["ACR_EULAR_PMR_CURRENT", "ACR_GCA_CURRENT"],
  },
  {
    slug: "fibromyalgia-central-sensitization",
    title: "Fibromyalgia & Central Sensitization",
    bodySystem: "Musculoskeletal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PMHNP"],
    recognize: "Fibromyalgia causes chronic widespread pain with fatigue, unrefreshing sleep, cognitive symptoms and heightened sensory sensitivity without inflammatory tissue destruction. It frequently coexists with migraine, IBS, mood disorders and inflammatory disease rather than excluding them.",
    diagnostics: "Diagnosis is clinical using widespread pain/symptom criteria and a focused evaluation for mimics such as hypothyroidism, inflammatory arthritis, myopathy, sleep apnea and medication effects. Broad autoimmune panels or repeated imaging are low yield when exam lacks inflammatory/red-flag findings.",
    priorities: "Education, graded aerobic/strength activity, sleep optimization and CBT or other behavioral pain strategies are foundational; duloxetine, milnacipran, pregabalin or selected alternatives can be used according to comorbidity and adverse-effect profile.",
    medicationSafety: "Chronic opioids and systemic steroids are not recommended because they do not treat the mechanism and add substantial harm. Sedating drugs can worsen falls/cognition, particularly when gabapentinoids are combined with opioids or other CNS depressants.",
    redFlags: "Objective progressive weakness, swollen joints, fever, weight loss, focal neurologic deficit, markedly abnormal labs or new organ dysfunction should not be attributed to fibromyalgia without separate evaluation.",
    examTraps: "Normal inflammatory markers do not mean pain is imaginary, and fibromyalgia is not a diagnosis that erases future medical disease. Tender-point counting alone is outdated.",
    sourceKeys: ["ACR_FIBROMYALGIA_CURRENT"],
  },
  {
    slug: "septic-arthritis",
    title: "Septic Arthritis",
    bodySystem: "Musculoskeletal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PNP", "ENP"],
    recognize: "An acutely hot, swollen, painful joint with restricted passive motion is septic arthritis until excluded, especially with bacteremia, prosthesis, older age, immunosuppression or injection drug use. Fever may be absent and gout/CPPD can coexist with infection.",
    diagnostics: "Urgently aspirate the joint before antibiotics when the patient is stable: send synovial WBC/differential, Gram stain, culture and crystals; obtain blood cultures. No synovial WBC cutoff or presence of crystals alone safely excludes infection.",
    priorities: "Start empiric IV antibiotics after cultures—earlier if septic/unstable—and obtain urgent orthopedic/source-control management for drainage. Tailor therapy to culture, native versus prosthetic joint and organism.",
    medicationSafety: "Empiric therapy typically covers S. aureus/MRSA plus gram-negative organisms according to host risk, with renal dosing and rapid de-escalation. Do not inject intra-articular corticosteroid into an undiagnosed acutely inflamed joint before infection is excluded.",
    redFlags: "Sepsis/shock, prosthetic joint infection, rapidly destructive hip/shoulder infection, immunocompromise or adjacent osteomyelitis requires urgent inpatient multidisciplinary care.",
    examTraps: "Crystals do not rule out septic arthritis and a normal serum WBC or lack of fever is not reassuring enough to skip aspiration in a high-risk hot joint.",
    sourceKeys: ["IDSA_SEPTIC_ARTHRITIS_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
