import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch7 = [
  {
    slug: "ptsd",
    title: "Post-Traumatic Stress Disorder",
    bodySystem: "Psychiatric",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PMHNP", "ENP"],
    recognize: "PTSD involves trauma exposure plus intrusion, avoidance, negative mood/cognition, and hyperarousal lasting >1 month with impairment. Dissociation, substance use, depression, and sleep disturbance are common.",
    diagnostics: "Use a trauma-informed interview and validated tool to support assessment. Screen for suicide risk, IPV, substance use, TBI, depression, and medical consequences of trauma.",
    priorities: "Trauma-focused psychotherapy is central. SSRIs/SNRIs are common medication options when indicated; address sleep, substance use, safety, and social supports.",
    medicationSafety: "Benzodiazepines are generally a poor fit for PTSD because of dependence risk and lack of core PTSD benefit. Prazosin may be considered for trauma-related nightmares in selected patients while monitoring BP.",
    redFlags: "Active suicidality, ongoing violence/unsafe home environment, severe dissociation, psychosis, or inability to care for self requires urgent intervention.",
    examTraps: "Do not force detailed trauma disclosure before safety and readiness. Normal initial functioning after trauma does not rule out later PTSD.",
    sourceKeys: ["VA_DOD_PTSD_CURRENT"],
  },
  {
    slug: "alcohol-use-disorder",
    title: "Alcohol Use Disorder & Withdrawal",
    bodySystem: "Psychiatric",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PMHNP", "ENP", "AGACNP"],
    recognize: "Loss of control, craving, tolerance, withdrawal, hazardous use, and continued use despite harm suggest AUD. Ask amount, pattern, last drink, prior withdrawal seizure/DTs, liver disease, pregnancy, and sedative co-use.",
    diagnostics: "Use a validated screen, then clinical diagnostic criteria. Labs can show consequences but do not diagnose AUD. Withdrawal severity requires repeated clinical assessment.",
    priorities: "Offer medications for AUD when appropriate plus counseling/support; acute withdrawal may require benzodiazepine-based treatment, thiamine, fluids/electrolytes, and monitored care based on risk.",
    medicationSafety: "Disulfiram requires high adherence and careful selection; naltrexone has opioid and liver considerations; acamprosate requires renal dosing. Give thiamine before or with glucose in high-risk malnourished patients without delaying emergent hypoglycemia treatment.",
    redFlags: "History of severe withdrawal, seizure, delirium, unstable vitals, hallucinations, significant comorbidity, pregnancy, or suicidality may require inpatient/ED management.",
    examTraps: "Do not use a positive blood alcohol level to assume withdrawal cannot begin. 'Detox' without relapse-prevention treatment is incomplete care.",
    sourceKeys: ["ASAM_ALCOHOL_WITHDRAWAL_CURRENT"],
  },
  {
    slug: "insomnia",
    title: "Insomnia",
    bodySystem: "Psychiatric",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PMHNP", "ENP"],
    recognize: "Chronic insomnia is difficulty initiating/maintaining sleep or early awakening with daytime impairment despite adequate opportunity. Screen for OSA, restless legs, circadian disorder, pain, mood disorder, substances, and medications.",
    diagnostics: "Use a sleep history/diary and targeted evaluation; polysomnography is not routine for uncomplicated insomnia but is indicated when another sleep disorder is suspected.",
    priorities: "CBT-I is first-line for chronic insomnia. Address schedule, stimulus control, sleep restriction principles, light/circadian factors, and comorbid conditions before defaulting to sedatives.",
    medicationSafety: "Sedative-hypnotics can cause falls, cognitive impairment, complex sleep behaviors, dependence, and respiratory risk. Avoid combining CNS depressants and be especially cautious in older adults.",
    redFlags: "Severe mania, suicidality, dangerous daytime sleepiness, suspected severe OSA/hypoventilation, or withdrawal-related insomnia requires targeted urgent evaluation.",
    examTraps: "Generic 'sleep hygiene' alone is not equivalent to CBT-I. Long-term antihistamine use is not a benign chronic insomnia strategy.",
    sourceKeys: ["AASM_INSOMNIA_CURRENT"],
  },
  {
    slug: "eating-disorders",
    title: "Eating Disorders",
    bodySystem: "Psychiatric",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PMHNP", "PNP", "WHNP"],
    recognize: "Restriction, bingeing, purging, compulsive exercise, body-image disturbance, weight suppression, menstrual change, syncope, GI complaints, or unexplained electrolyte abnormalities may indicate an eating disorder at any body size.",
    diagnostics: "Assess orthostatic vitals, ECG when risk is present, electrolytes/Mg/Phos, CBC/CMP, pregnancy status, and medical consequences. Screen for suicide risk and comorbid anxiety/OCD/depression.",
    priorities: "Use multidisciplinary treatment with nutritional rehabilitation and evidence-based psychotherapy; level of care depends on medical instability, psychiatric risk, and ability to eat safely.",
    medicationSafety: "Avoid medications that increase seizure or arrhythmia risk in unstable patients. Refeeding requires monitoring for phosphorus, potassium, magnesium shifts, edema, and cardiac complications.",
    redFlags: "Bradycardia/hypotension, syncope, severe electrolyte abnormality, prolonged QT, acute food refusal/dehydration, suicidality, or refeeding risk requires urgent specialty/inpatient evaluation.",
    examTraps: "Normal BMI does not exclude a severe eating disorder. Amenorrhea is not required for anorexia nervosa.",
    sourceKeys: ["APA_EATING_DISORDERS_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
