import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch56 = [
  {
    slug: "ptsd-trauma-disorders",
    title: "PTSD & Trauma-Related Disorders",
    bodySystem: "Psychiatric",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PMHNP", "WHNP", "ENP"],
    recognize: "PTSD requires trauma exposure plus intrusive symptoms, avoidance, negative cognition/mood and hyperarousal lasting more than one month with impairment. Acute stress disorder occurs earlier; dissociation, substance use, depression, panic, TBI and ongoing interpersonal violence commonly coexist.",
    diagnostics: "Use a trauma-informed history and validated tool such as PCL-5 to quantify symptoms while assessing suicide risk, substance use, sleep, dissociation and current safety. Do not require the patient to recount graphic trauma details during routine screening to establish risk.",
    priorities: "Trauma-focused psychotherapy—prolonged exposure, cognitive processing therapy or EMDR—is first-line for many adults; SSRIs/SNRIs are evidence-based pharmacologic options when therapy is unavailable, insufficient or patient-preferred. Treat comorbid depression/SUD and address ongoing safety/housing/violence.",
    medicationSafety: "Benzodiazepines are not recommended for PTSD and can impair trauma-focused treatment/recovery; prazosin may help trauma-related nightmares in selected patients but is not a universal treatment for all PTSD symptoms and can cause orthostasis.",
    redFlags: "Active suicidality, psychosis, severe dissociation with unsafe behavior, ongoing violence/trafficking or substance withdrawal requires urgent safety intervention.",
    examTraps: "Do not diagnose PTSD from trauma exposure alone and do not use benzodiazepines as chronic first-line anxiety treatment in PTSD. Normal functioning in one domain does not exclude severe trauma symptoms elsewhere.",
    sourceKeys: ["VA_DOD_PTSD_CURRENT", "APA_PTSD_CURRENT"],
  },
  {
    slug: "anorexia-nervosa",
    title: "Anorexia Nervosa & Medical Stabilization",
    bodySystem: "Psychiatric",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PMHNP", "PNP", "WHNP", "ENP"],
    recognize: "Anorexia nervosa involves restriction causing significantly low weight, intense fear/behavior preventing weight gain and body-image disturbance; atypical anorexia can produce the same medical instability at a higher body weight after major weight loss.",
    diagnostics: "Assess weight trajectory rather than BMI alone, orthostatic vitals, ECG, electrolytes, phosphorus, magnesium, glucose, CBC/CMP and menstrual/endocrine effects; ask purging, exercise, laxative/diuretic and suicidality directly. Bradycardia/hypotension and lab abnormalities determine medical risk.",
    priorities: "Restore nutrition through an eating-disorder team with monitored refeeding, psychotherapy and family-based treatment for many adolescents. Hospitalize medically unstable patients and monitor phosphorus/magnesium/potassium/glucose and edema during refeeding.",
    medicationSafety: "No medication reliably restores core anorexia pathology without nutrition; avoid bupropion because seizure risk is increased in eating disorders. QT-prolonging/sedating drugs require caution in bradycardic/electrolyte-depleted patients.",
    redFlags: "Severe bradycardia/hypotension, syncope, hypoglycemia, electrolyte abnormality, prolonged QT, dehydration, acute food refusal or suicidality requires urgent medical stabilization.",
    examTraps: "Do not use normal BMI to rule out dangerous restrictive eating and do not wait for extreme emaciation before hospitalizing an unstable adolescent.",
    sourceKeys: ["APA_EATING_DISORDERS_CURRENT", "SAHM_RESTRICTIVE_ED_CURRENT"],
  },
  {
    slug: "bulimia-binge-eating-disorders",
    title: "Bulimia Nervosa & Binge-Eating Disorder",
    bodySystem: "Psychiatric",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PMHNP", "PNP", "WHNP"],
    recognize: "Bulimia combines recurrent binge episodes with compensatory vomiting, laxative/diuretic misuse, fasting or exercise and overvaluation of weight/shape; binge-eating disorder has recurrent binges without regular compensatory behavior. Weight can be normal or high, so appearance is not screening.",
    diagnostics: "Assess frequency/duration, purging methods, dental/parotid/esophageal symptoms, ECG and potassium/bicarbonate/magnesium when purging is present; screen depression, trauma, substance use and suicide risk. Marked metabolic alkalosis/hypokalemia suggests vomiting/diuretic behavior even when denied.",
    priorities: "CBT-based psychotherapy is first-line; fluoxetine at the evidence-based bulimia dose can reduce binge/purge behavior, while lisdexamfetamine is FDA-approved for moderate-severe binge-eating disorder in adults with appropriate stimulant-risk assessment.",
    medicationSafety: "Bupropion is contraindicated in bulimia/anorexia because of seizure risk; stimulant treatment can worsen BP, insomnia or misuse risk. Correct electrolytes before QT-prolonging drugs or intensive exercise.",
    redFlags: "Severe hypokalemia/QT arrhythmia, hematemesis, syncope, dehydration/AKI, severe laxative/diuretic toxicity or suicidality requires urgent medical care.",
    examTraps: "Normal weight does not rule out bulimia and binge-eating disorder is not treated by prescribing a stimulant solely for weight loss.",
    sourceKeys: ["APA_EATING_DISORDERS_CURRENT", "FDA_LISDEXAMFETAMINE_BED_CURRENT"],
  },
  {
    slug: "borderline-personality-disorder",
    title: "Borderline Personality Disorder",
    bodySystem: "Psychiatric",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PMHNP", "ENP"],
    recognize: "Pervasive affective instability, fear of abandonment, unstable relationships/self-image, impulsivity, recurrent self-harm/suicidality, chronic emptiness or transient stress-related paranoia/dissociation suggests BPD. Symptoms are enduring patterns, not simply any patient in crisis.",
    diagnostics: "Use longitudinal history and assess PTSD, bipolar disorder, ADHD, substance use, autism, depression and eating disorders; perform suicide/self-harm assessment at every relevant crisis. Brief mood shifts triggered by interpersonal events differ from sustained hypomanic/manic episodes.",
    priorities: "Structured psychotherapy—especially DBT, mentalization or other evidence-based personality-disorder therapy—is core treatment; create consistent crisis/safety plans and coordinated boundaries. Medications target specific comorbid symptoms, not the personality disorder itself.",
    medicationSafety: "Avoid polypharmacy and long-term benzodiazepines because impulsivity, dependence and overdose risk can worsen. Prescribe limited quantities when overdose risk is high and deprescribe ineffective antipsychotic/mood-stabilizer regimens rather than stacking drugs after each crisis.",
    redFlags: "Active suicidal intent, severe self-injury, intoxication, psychosis or inability to maintain safety requires emergency psychiatric evaluation.",
    examTraps: "Do not diagnose bipolar disorder solely from rapid mood shifts or label understandable distress/manipulation pejoratively. Hospitalization is for acute safety, not a substitute for longitudinal psychotherapy.",
    sourceKeys: ["APA_BPD_CURRENT"],
  },
  {
    slug: "dementia-behavioral-psychological-symptoms",
    title: "Behavioral & Psychological Symptoms of Dementia",
    bodySystem: "Psychiatric",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PMHNP"],
    recognize: "Agitation, wandering, sleep reversal, hallucinations, apathy and aggression in dementia are symptoms with triggers—pain, infection, constipation, environment, caregiver stress, medications or delirium—not automatically a primary psychiatric disorder.",
    diagnostics: "Establish baseline/cognitive syndrome and first exclude delirium, pain, urinary retention/constipation, sleep problems and medication toxicity. Characterize hallucinations/parkinsonism/REM sleep behavior because Lewy-body disease has major antipsychotic sensitivity.",
    priorities: "Use caregiver/environmental and behavioral interventions first, treat medical triggers and consider medications only for severe persistent distress or danger after shared risk discussion. Cholinesterase inhibitors/memantine target cognitive/neuropsychiatric symptoms in selected dementias but do not eliminate safety planning.",
    medicationSafety: "Antipsychotics in dementia carry increased mortality/stroke warnings and should use the lowest effective dose for the shortest justified period with reassessment; avoid strong anticholinergics and routine benzodiazepines that worsen cognition/falls/delirium.",
    redFlags: "Acute fluctuating change, fever, focal deficit, violent behavior with imminent danger or severe neuroleptic sensitivity/NMS requires urgent evaluation.",
    examTraps: "Do not treat delirium as 'worsening dementia' and do not use antipsychotics for routine wandering or caregiver convenience.",
    sourceKeys: ["APA_DEMENTIA_BPSD_CURRENT", "AGS_BEERS_2023_CURRENT"],
  },
  {
    slug: "somatic-symptom-illness-anxiety",
    title: "Somatic Symptom & Illness Anxiety Disorders",
    bodySystem: "Psychiatric",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PMHNP"],
    recognize: "Somatic symptom disorder is excessive distress/behavior around one or more symptoms regardless of whether a medical disease also exists; illness anxiety focuses on fear of serious disease with minimal symptoms. Neither diagnosis means symptoms are fabricated.",
    diagnostics: "Perform an appropriate initial medical evaluation and review records to avoid repeating fragmented workups; assess anxiety/depression/trauma and functional impact. New objective red flags still require fresh medical evaluation even after a functional/somatic diagnosis exists.",
    priorities: "Create one coordinating clinician, scheduled follow-ups, validation of suffering and CBT/related psychotherapy; treat comorbid anxiety/depression and shift goals toward function rather than repeated reassurance/testing after a reasonable workup.",
    medicationSafety: "Avoid escalating opioids, benzodiazepines or repeated invasive testing for persistent medically unexplained symptoms; antidepressants are used for comorbid anxiety/depression or pain syndromes rather than as proof symptoms are psychiatric.",
    redFlags: "Objective neurologic deficit, GI bleeding, weight loss, fever, hemodynamic change or new abnormal labs should never be dismissed because of a prior somatic-symptom diagnosis.",
    examTraps: "The symptoms are not intentionally produced, distinguishing somatic symptom disorder from factitious disorder or malingering. Medical and somatic disorders can coexist.",
    sourceKeys: ["APA_SOMATIC_SYMPTOM_CURRENT"],
  },
  {
    slug: "autism-adult-psychiatric-care",
    title: "Autism in Adult Psychiatric Care",
    bodySystem: "Psychiatric",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PMHNP"],
    recognize: "Autistic adults may present for anxiety, depression, burnout, sensory overload, executive-function difficulty or late diagnostic evaluation. Social-communication style, repetitive interests and sensory differences are lifelong; masking can obscure history, particularly in women and gender-diverse adults.",
    diagnostics: "Use developmental history and collateral information when available and refer for formal diagnostic assessment when needed; distinguish autism from social anxiety, ADHD, personality disorders, trauma and psychosis while recognizing common comorbidity.",
    priorities: "Use neurodiversity-affirming accommodations, predictable communication, sensory/environmental support and treatment of specific comorbid psychiatric conditions. Psychotherapy may need concrete/structured adaptation; occupational and social support can improve function.",
    medicationSafety: "No medication treats core autism traits; psychotropics should target a defined comorbid disorder or severe symptom and be monitored for adverse effects. Avoid polypharmacy to suppress harmless repetitive behavior or sensory differences.",
    redFlags: "Suicidality, severe self-neglect, catatonia, acute regression or new psychosis requires urgent assessment beyond baseline autistic behavior.",
    examTraps: "Do not infer lack of empathy or intellectual disability from autistic communication style and do not rule out autism because an adult maintains eye contact or has a career.",
    sourceKeys: ["APA_AUTISM_CURRENT", "NICE_AUTISM_ADULT_CURRENT"],
  },
  {
    slug: "catatonia",
    title: "Catatonia Recognition & Treatment",
    bodySystem: "Psychiatric",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PMHNP", "ENP"],
    recognize: "Mutism, stupor, negativism, posturing, waxy flexibility, echolalia/echopraxia or purposeless agitation can represent catatonia in mood, psychotic, neurologic or medical illness. Malignant catatonia adds fever/autonomic instability and can resemble neuroleptic malignant syndrome.",
    diagnostics: "Use a structured scale such as Bush-Francis and evaluate medical/neurologic causes, CK/electrolytes, medications and autoimmune/infectious encephalitis when indicated. A lorazepam challenge can support diagnosis but lack of immediate response does not fully exclude it.",
    priorities: "Treat promptly with benzodiazepines—often lorazepam—and use ECT for severe, malignant or benzodiazepine-refractory catatonia. Support hydration/nutrition/DVT prevention and treat the underlying disease.",
    medicationSafety: "Antipsychotics can worsen catatonia or precipitate malignant/NMS-like states, especially before catatonia is controlled; use caution and psychiatric expertise. Benzodiazepines require respiratory/fall monitoring but should not be withheld reflexively in life-threatening catatonia.",
    redFlags: "Fever, autonomic instability, dehydration, rhabdomyolysis, pressure injury, inability to eat/drink or severe immobility/agitation requires urgent inpatient treatment.",
    examTraps: "Do not assume a mute immobile patient is voluntarily refusing care or simply severely depressed, and do not automatically start an antipsychotic before recognizing catatonia.",
    sourceKeys: ["BAP_CATATONIA_CURRENT", "APA_CATATONIA_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
