import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch36 = [
  {
    slug: "vulvodynia",
    title: "Vulvodynia: Peripheral Sensitization",
    slugAliases: ["vulvodynia-np"],
    bodySystem: "Reproductive",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "WHNP"],
    recognize: "Vulvodynia is vulvar pain lasting at least 3 months without a clearly identifiable cause after appropriate evaluation. Localized provoked vestibulodynia is common, but pain may be generalized, spontaneous or mixed and often overlaps pelvic-floor hypertonicity, bladder pain, IBS and other centralized pain conditions.",
    diagnostics: "Take a detailed pain/sexual/dermatologic history, inspect for infection, dermatosis, trauma and neoplasia, and map tenderness gently with a cotton swab. Assess pelvic-floor muscle tone and psychosocial impact. Culture, biopsy or STI testing is targeted to suspected infection/skin disease rather than performed routinely in an otherwise typical pain syndrome.",
    priorities: "Validate the pain and use multimodal care: vulvar irritant avoidance, pelvic-floor physical therapy for muscular dysfunction, sexual/psychological support and individualized topical or systemic neuropathic-pain therapy. Refractory localized provoked vestibulodynia may warrant specialist procedural or surgical options after conservative management.",
    medicationSafety: "Evidence for oral tricyclics, gabapentinoids and compounded topical agents is variable; avoid presenting one drug as universally first-line. Monitor sedation, anticholinergic effects, falls and renal dosing, and avoid chronic opioid therapy for a centralized vulvar pain syndrome.",
    redFlags: "Ulceration, pigment change, bleeding, fixed mass, rapidly progressive pain/swelling, fever/cellulitis or an abnormal vulvar lesion requires disease-specific evaluation/biopsy rather than labeling symptoms vulvodynia.",
    examTraps: "A normal-appearing vulva does not invalidate severe pain, but vulvodynia remains a diagnosis after excluding identifiable causes. Do not repeatedly treat negative cultures as yeast infection or imply the syndrome is purely psychogenic.",
    sourceKeys: ["ACOG_VULVODYNIA_CURRENT", "ISSVD_VULVODYNIA_CURRENT"],
  },
  {
    slug: "bartholin-cyst-abscess",
    title: "Bartholinitis: Glandular Anatomy, Abscess",
    slugAliases: ["bartholinitis-np"],
    bodySystem: "Reproductive",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "WHNP", "ENP"],
    recognize: "A Bartholin duct cyst is usually a painless posterolateral introital mass; abscess produces marked unilateral vulvar pain, tenderness, erythema and fluctuation. In patients over about 40 or postmenopausal, a new persistent or solid Bartholin-area mass deserves malignancy consideration rather than automatic drainage-only treatment.",
    diagnostics: "Diagnosis is usually clinical. Test gonorrhea/chlamydia when STI risk or cervicitis exists and culture purulent material selectively when severe, recurrent or resistant infection is relevant. Biopsy or gynecologic referral is appropriate for new masses in older patients or lesions that are solid, fixed, irregular or recurrent.",
    priorities: "Asymptomatic small cysts can be observed. Symptomatic cyst/abscess is treated by creating durable drainage—commonly Word catheter or marsupialization—rather than simple needle aspiration or incision alone, which recurs more often. Antibiotics are added for cellulitis, systemic illness, STI or selected high-risk hosts rather than given to every drained abscess.",
    medicationSafety: "Choose antibiotics from the actual clinical context—cellulitis/MRSA risk, STI test, allergy, pregnancy and local resistance. TMP-SMX can cause hyperkalemia and severe rash; doxycycline is not first-line in pregnancy; routine metronidazole addition is not required for every Bartholin abscess.",
    redFlags: "Rapidly spreading cellulitis, sepsis, necrotizing infection, deep extension, uncontrolled hemorrhage or a suspicious solid/fixed mass requires urgent gynecologic/surgical evaluation.",
    examTraps: "Do not teach 'biopsy every Bartholin mass >40' as an absolute without clinical judgment, but do not dismiss a new mass in this age group as routine infection. Simple I&D without a drainage tract has higher recurrence.",
    sourceKeys: ["ACOG_VULVAR_CURRENT", "AAFP_BARTHOLIN_CURRENT"],
  },
  {
    slug: "pelvic-organ-prolapse",
    title: "Uterine Prolapse: Connective Tissue Biology",
    slugAliases: ["uterine-prolapse-np"],
    bodySystem: "Reproductive",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "WHNP"],
    recognize: "Pelvic organ prolapse reflects failure of apical, anterior or posterior vaginal support and can cause vaginal bulge/pressure, urinary or bowel dysfunction and sexual symptoms. Degree of anatomic prolapse does not always correlate with symptom burden.",
    diagnostics: "Perform pelvic examination with Valsalva and document compartment/stage using a standardized system such as POP-Q when management decisions depend on it. Evaluate stress incontinence, retention, bowel symptoms and vaginal tissue; imaging is not routine for uncomplicated prolapse.",
    priorities: "Observation is reasonable when symptoms are minimal; pelvic-floor muscle training and pessary therapy are effective nonsurgical options, while surgery is chosen according to compartment, uterine-preservation goals, sexual function, recurrence risk and patient preference.",
    medicationSafety: "Topical vaginal estrogen may improve genitourinary syndrome and tissue comfort in selected peri/postmenopausal pessary users, but it is not automatically required for every pessary. Systemic hormone therapy is not a treatment for connective-tissue prolapse itself.",
    redFlags: "Incarcerated/ulcerated prolapse, significant urinary retention with renal effects, severe bleeding, infection or an unexpected pelvic mass requires prompt specialty evaluation.",
    examTraps: "Do not recommend hysterectomy as the only definitive operation—uterine-sparing repairs exist. Prolapse stage alone does not dictate treatment; bothersome symptoms and patient goals do.",
    sourceKeys: ["ACOG_POP_CURRENT", "AUGS_POP_CURRENT"],
  },
  {
    slug: "benign-ovarian-cysts",
    title: "Ovarian Cysts: Functional vs Neoplastic",
    slugAliases: ["ovarian-cysts-benign-np"],
    bodySystem: "Reproductive",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "WHNP", "ENP"],
    recognize: "Many premenopausal ovarian cysts are physiologic and self-resolve, while complex morphology, solid components, papillary projections, ascites, postmenopausal status, persistent growth or systemic symptoms increase concern for neoplasm. Sudden severe unilateral pain raises torsion or rupture concern regardless of prior benign appearance.",
    diagnostics: "Pregnancy testing and transvaginal ultrasound are first-line for an adnexal mass. Use morphology, size, menopausal status and validated ultrasound-risk systems to determine follow-up versus referral; CA-125 is not a screening test and is nonspecific in premenopausal patients.",
    priorities: "Observe appropriate simple cysts with guideline-based imaging intervals, treat pain supportively and refer persistent, enlarging, suspicious or symptomatic masses. Suspected torsion needs urgent gynecologic surgery; ovarian conservation is preferred when feasible in reproductive-age patients.",
    medicationSafety: "Combined hormonal contraception suppresses formation of future functional cysts but does not reliably accelerate resolution of an existing functional cyst. Avoid repeated opioids for recurrent pain without reassessing torsion/endometriosis/other causes.",
    redFlags: "Sudden severe pain with nausea/vomiting, peritoneal signs, hemodynamic instability, pregnancy with adnexal mass, postmenopausal complex mass or malignant ultrasound features requires urgent/expedited evaluation.",
    examTraps: "Do not use CA-125 alone to decide benign versus malignant and do not assume Doppler flow excludes torsion. A large simple cyst and a small complex vascular nodule do not carry the same risk.",
    sourceKeys: ["ACOG_ADNEXAL_MASS_CURRENT", "SRU_ADNEXAL_CURRENT"],
  },
  {
    slug: "endometrial-polyps",
    title: "Endometrial Polyps: Molecular Pathogenesis",
    slugAliases: ["endometrial-polyp-np"],
    bodySystem: "Reproductive",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "WHNP"],
    recognize: "Endometrial polyps are localized overgrowths of endometrial glands/stroma and commonly present with intermenstrual, heavy or postmenopausal bleeding, infertility or incidental imaging findings. Most are benign, but age, menopause and abnormal bleeding increase malignancy risk.",
    diagnostics: "Transvaginal ultrasound identifies many lesions; saline-infusion sonohysterography improves intracavitary definition and hysteroscopy allows direct visualization/removal. Endometrial sampling strategy depends on age and cancer risk because blind biopsy can miss a focal polyp.",
    priorities: "Observe selected small asymptomatic low-risk polyps, but hysteroscopic polypectomy is preferred for symptomatic bleeding, infertility-related indications, postmenopausal polyps or lesions with concerning risk. Send removed tissue for histopathology.",
    medicationSafety: "Hormonal therapy can control concurrent abnormal bleeding but does not reliably eradicate a structural polyp. Avoid repeated empiric hormone changes in persistent focal bleeding without appropriate cavity evaluation.",
    redFlags: "Postmenopausal bleeding, rapidly recurrent bleeding, severe anemia, atypical endometrial sampling or suspicious vascular/solid features requires expedited gynecologic evaluation.",
    examTraps: "A negative blind endometrial biopsy does not guarantee that a focal intracavitary lesion is absent. Do not assume all AUB in a patient with a small polyp is caused by the polyp without considering other PALM-COEIN causes.",
    sourceKeys: ["ACOG_HYSTEROSCOPY_CURRENT", "ACOG_AUB_CURRENT"],
  },
  {
    slug: "endometriosis-pathophysiology",
    title: "Endometriosis: Ectopic Endometrial Biology",
    slugAliases: ["endometriosis-np"],
    bodySystem: "Reproductive",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "WHNP"],
    recognize: "Endometriosis is estrogen-responsive ectopic endometrial-like tissue associated with chronic inflammation, fibrosis and altered pain processing. Cyclic pelvic pain, dysmenorrhea, deep dyspareunia, dyschezia, infertility or chronic noncyclic pain are common, but symptom severity does not correlate reliably with lesion burden.",
    diagnostics: "A clinical diagnosis can justify empiric treatment; transvaginal ultrasound identifies endometrioma/deep disease but normal imaging does not exclude superficial endometriosis. Laparoscopy is used when diagnosis is uncertain, symptoms are refractory or surgical treatment/fertility planning makes visualization necessary—not as a mandatory first diagnostic step for everyone.",
    priorities: "Use NSAIDs for pain plus hormonal suppression such as continuous combined contraception or progestin therapy when pregnancy is not desired; escalate to GnRH analog/antagonist or surgery based on response, side effects and fertility goals. Infertility management should coordinate reproductive endocrinology rather than suppress ovulation indefinitely when conception is the goal.",
    medicationSafety: "GnRH therapies can reduce bone density and cause hypoestrogenic symptoms and often require duration/add-back planning. Avoid chronic opioid therapy and do not promise that hysterectomy alone cures all endometriosis-associated pain.",
    redFlags: "Acute severe pain with torsion/rupture concern, bowel/urinary obstruction, pregnancy complications, severe anemia or a complex enlarging endometrioma requires urgent/expedited evaluation.",
    examTraps: "Normal ultrasound does not rule out endometriosis and pain severity does not stage disease. Do not require surgical confirmation before offering appropriate empiric medical therapy to a typical patient.",
    sourceKeys: ["ACOG_ENDOMETRIOSIS_CURRENT", "ESHRE_ENDOMETRIOSIS_CURRENT"],
  },
  {
    slug: "infertility-evaluation",
    title: "Infertility: HPO Axis & Diagnostic Workup",
    slugAliases: ["infertility-np"],
    bodySystem: "Reproductive",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "WHNP"],
    recognize: "Infertility reflects failure to achieve pregnancy after an appropriate interval of regular unprotected intercourse, with earlier evaluation when the female partner is older or when known risk factors exist. Ovulatory, tubal/uterine and male factors should be assessed in parallel rather than sequentially blaming one partner.",
    diagnostics: "Confirm ovulation from menstrual history or targeted progesterone when unclear, assess ovarian reserve only to guide treatment response rather than to diagnose spontaneous fertility, evaluate uterine/tubal anatomy when indicated and obtain semen analysis early. Check TSH/prolactin or other endocrine tests when history supports them rather than ordering broad panels automatically.",
    priorities: "Treat reversible endocrine/anatomic factors, optimize preconception health and refer based on age, duration and diagnosis. Letrozole is first-line ovulation induction for anovulatory infertility in PCOS when no other factor changes the plan; IVF/ICSI or surgery depends on tubal, male-factor, ovarian-reserve and patient goals.",
    medicationSafety: "Ovulation-induction drugs increase multifollicular pregnancy/ovarian hyperstimulation risk to varying degrees and require protocol monitoring. Exogenous testosterone suppresses spermatogenesis and should not be used in a male partner seeking fertility.",
    redFlags: "Severe pelvic pain, suspected ectopic pregnancy, ovarian torsion/OHSS, testicular mass or pituitary mass symptoms requires urgent evaluation separate from routine infertility timelines.",
    examTraps: "AMH predicts ovarian response better than natural-fecundity probability and should not be used as a stand-alone 'fertility test.' Do not delay semen analysis while completing months of female-only testing.",
    sourceKeys: ["ASRM_INFERTILITY_EVALUATION_CURRENT", "PCOS_INTERNATIONAL_2023"],
  },
  {
    slug: "galactorrhea-hyperprolactinemia",
    title: "Galactorrhea: Prolactin Regulation & Diagnostic Workup",
    slugAliases: ["galactorrhea-np"],
    bodySystem: "Reproductive",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "WHNP", "PMHNP"],
    recognize: "Milky nipple discharge outside normal lactation suggests galactorrhea and may result from pregnancy, physiologic nipple stimulation, dopamine-blocking medication, hypothyroidism, kidney disease or prolactinoma. Bloody, unilateral, spontaneous single-duct discharge follows a breast-lesion pathway instead.",
    diagnostics: "Confirm pregnancy status and measure prolactin without repeated breast stimulation; review antipsychotics, metoclopramide and other drugs, TSH and renal function. Repeat mild elevations under appropriate conditions and obtain pituitary MRI for persistent unexplained substantial hyperprolactinemia or mass-effect symptoms.",
    priorities: "Treat the cause—correct hypothyroidism, adjust culprit medication collaboratively and use dopamine agonist therapy for symptomatic prolactinoma or clinically important hyperprolactinemia when indicated. Coordinate psychiatry before changing an effective antipsychotic solely to lower prolactin.",
    medicationSafety: "Cabergoline commonly causes nausea and orthostasis and is generally preferred to bromocriptine for many prolactinomas because of efficacy/tolerability. Dopamine agonists can worsen impulse-control or psychiatric symptoms in susceptible patients and require counseling.",
    redFlags: "Visual-field loss, severe headache/ophthalmoplegia, rapidly enlarging pituitary lesion, bloody breast discharge or neurologic deterioration requires urgent specialty evaluation.",
    examTraps: "Do not order pituitary MRI for one mildly elevated prolactin before excluding pregnancy, medications and hypothyroidism. Galactorrhea can occur with a normal prolactin level and does not itself prove pituitary disease.",
    sourceKeys: ["ENDOCRINE_HYPERPROLACTINEMIA_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
