import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch50 = [
  {
    slug: "adult-immunization-primary-care",
    title: "Adult Immunization in Primary Care",
    bodySystem: "Preventive Care",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "WHNP"],
    recognize: "Adult vaccination is risk-, age-, pregnancy-, immune-status- and prior-dose dependent. Every visit is an opportunity to reconcile influenza, COVID-19, Tdap/Td, zoster, pneumococcal, RSV, hepatitis A/B, HPV and travel/occupational vaccines rather than waiting for an annual physical.",
    diagnostics: "Use the current CDC adult immunization schedule and footnotes; verify prior documented doses and true contraindications. Serology is reserved for specific vaccines/hosts and is not required before routine revaccination when records are absent unless the guideline recommends testing.",
    priorities: "Give all due vaccines at the same visit when permitted, prioritize high-risk respiratory and pregnancy vaccines according to season/timing, and use catch-up rather than restarting series after long intervals. Counsel immunocompromised adults that non-live vaccines are safe but response may be reduced.",
    medicationSafety: "Live vaccines are contraindicated in pregnancy and significant immunosuppression but not merely because a patient is older. A prior local reaction, mild illness or antibiotic use usually is not a contraindication; anaphylaxis to a vaccine/component is.",
    redFlags: "Suspected anaphylaxis after vaccination, myocarditis/pericarditis symptoms or serious neurologic adverse event requires urgent evaluation and vaccine-safety reporting/consultation.",
    examTraps: "Do not restart an interrupted vaccine series and do not use outdated pneumococcal sequencing from older schedules; current PCV options and indications change over time, so follow the current CDC schedule.",
    sourceKeys: ["CDC_ADULT_IMMUNIZATION_2026"],
  },
  {
    slug: "cancer-screening-primary-care",
    title: "Cancer Screening in Primary Care",
    bodySystem: "Preventive Care",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "WHNP"],
    recognize: "Screening applies to asymptomatic patients; symptoms such as bleeding, mass, weight loss or persistent focal pain require diagnostic evaluation instead. Breast, colorectal, cervical and lung screening intervals depend on age/risk, while prostate screening uses shared decision-making rather than automatic PSA testing for every man.",
    diagnostics: "Use current USPSTF/ACS/ACOG/ACS lung criteria and identify high-risk family/genetic histories that require earlier or different strategies. Obtain prior colonoscopy/pathology, cervical test history and smoking pack-years before ordering 'routine' tests from age alone.",
    priorities: "Offer high-benefit screening with informed choice, ensure abnormal results complete the diagnostic cascade and stop/individualize screening when life expectancy, prior history or age moves net benefit below harm. Refer hereditary-cancer patterns for genetic counseling rather than merely shortening every screening interval.",
    medicationSafety: "Screening harms include false positives, overdiagnosis, radiation/procedural complications and unnecessary treatment; bowel preparation/contrast/procedural sedation require comorbidity and medication planning.",
    redFlags: "Positive FIT, suspicious mammogram, high-grade cervical result, hemoptysis with lung lesion or cancer-suggestive symptom requires diagnostic—not repeat screening—follow-up.",
    examTraps: "Do not order screening mammography, FIT or low-dose CT to evaluate active symptoms and do not continue screening indefinitely solely because the patient previously participated.",
    sourceKeys: ["USPSTF_CANCER_SCREENING_CURRENT", "ACOG_CERVICAL_CURRENT", "ACS_SCREENING_CURRENT"],
  },
  {
    slug: "osteoporosis-screening-treatment",
    title: "Osteoporosis Screening & Fracture Prevention",
    bodySystem: "Preventive Care",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "WHNP"],
    recognize: "Osteoporosis may be silent until fragility fracture. Age, menopause, low weight, glucocorticoids, prior fracture, parental hip fracture, smoking/alcohol and secondary endocrine/malabsorptive disease increase risk; a low-trauma hip or vertebral fracture establishes high clinical risk even without a T-score below -2.5.",
    diagnostics: "Use DXA in recommended age/risk groups and FRAX or another validated fracture-risk tool when it changes treatment. Evaluate calcium/vitamin D and secondary causes selectively; vertebral imaging is useful for height loss, kyphosis or suspected silent vertebral fracture.",
    priorities: "Use resistance/weight-bearing activity, fall prevention, adequate calcium/vitamin D from diet/supplement and pharmacotherapy for high/very-high fracture risk. Bisphosphonates are common first-line treatment; anabolic therapy is favored for selected very-high-risk patients and must be followed by antiresorptive therapy to preserve gains.",
    medicationSafety: "Oral bisphosphonates can injure the esophagus and require upright fasting administration; IV agents need renal and acute-phase review. Denosumab should not be stopped/delayed without transition therapy because rebound vertebral fractures can occur.",
    redFlags: "Acute suspected hip/vertebral fracture, severe hypercalcemia, pathologic fracture or jaw/femur symptoms during antiresorptive treatment requires prompt evaluation.",
    examTraps: "Do not use a T-score alone in premenopausal women and do not initiate an unplanned 'drug holiday' from denosumab. Osteopenia can still merit treatment when absolute fracture risk is high.",
    sourceKeys: ["USPSTF_OSTEOPOROSIS_CURRENT", "ENDOCRINE_OSTEOPOROSIS_CURRENT"],
  },
  {
    slug: "tobacco-nicotine-cessation",
    title: "Tobacco & Nicotine Cessation",
    bodySystem: "Preventive Care",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PMHNP", "PNP", "WHNP"],
    recognize: "Assess cigarettes, cigars, vaping, smokeless tobacco and nicotine dependence without judgment and identify readiness, prior quit attempts, triggers, withdrawal and coexisting mental-health/substance use. Vaping is not harmless, and dual cigarette/e-cigarette use may preserve substantial risk.",
    diagnostics: "No routine laboratory test is needed; quantify tobacco/nicotine exposure and screen for COPD/lung-cancer eligibility and cardiovascular disease separately. Pregnancy and adolescent use change the counseling/pharmacotherapy evidence and risk discussion.",
    priorities: "Combine behavioral support with FDA-approved pharmacotherapy for nonpregnant adults when appropriate: varenicline or combination nicotine replacement are highly effective, and bupropion is another option. Arrange proactive follow-up rather than a one-time 'quit' instruction.",
    medicationSafety: "Varenicline can cause nausea/vivid dreams; bupropion is contraindicated in seizure/eating disorders and interacts with MAOIs; nicotine replacement is safer than continued smoking for most cardiovascular patients. E-cigarettes are not FDA-approved cessation medications.",
    redFlags: "Acute chest pain, severe respiratory symptoms, suicidality or suspected EVALI/toxic exposure requires urgent disease-specific evaluation.",
    examTraps: "Do not withhold effective cessation medication from stable cardiovascular patients solely because nicotine is involved, and do not present vaping as a proven risk-free medical cessation strategy.",
    sourceKeys: ["USPSTF_TOBACCO_CURRENT", "FDA_SMOKING_CESSATION_CURRENT"],
  },
  {
    slug: "alcohol-use-disorder-primary-care",
    title: "Alcohol Use Disorder: Screening & Treatment",
    bodySystem: "Preventive Care",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PMHNP", "WHNP", "ENP"],
    recognize: "Unhealthy alcohol use ranges from risky consumption to AUD with impaired control, craving, role failure and continued use despite harm. Ask with validated screening rather than waiting for abnormal liver tests; tolerance/withdrawal increase severity but are not required for diagnosis.",
    diagnostics: "Use AUDIT-C or validated single-question screening, then DSM criteria and assess withdrawal history, liver/pancreatic disease, pregnancy, other substances, suicidality and medications. Labs can assess consequences but no liver enzyme pattern diagnoses AUD.",
    priorities: "Use motivational/behavioral treatment plus medications such as naltrexone or acamprosate when appropriate; gabapentin/topiramate are selected alternatives. Patients at risk for severe withdrawal need monitored benzodiazepine-based withdrawal management rather than abrupt unsupported cessation.",
    medicationSafety: "Naltrexone is avoided with current opioid use and severe acute hepatitis and blocks opioid analgesia; acamprosate requires renal dosing and is useful after abstinence. Disulfiram has limited use because adherence and hepatotoxicity/reaction risks are substantial.",
    redFlags: "Prior withdrawal seizure/delirium, severe autonomic hyperactivity, suicidality, pancreatitis/hepatitis with instability or concurrent sedative withdrawal requires urgent monitored treatment.",
    examTraps: "Do not require a patient to hit 'rock bottom' before medication treatment and do not prescribe naltrexone without checking current opioids.",
    sourceKeys: ["USPSTF_ALCOHOL_CURRENT", "ASAM_ALCOHOL_WITHDRAWAL_CURRENT"],
  },
  {
    slug: "hiv-prep-pep",
    title: "HIV PrEP & PEP Prescribing",
    bodySystem: "Preventive Care",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "WHNP", "PNP", "ENP"],
    recognize: "PrEP is indicated for people without HIV who desire protection or have sexual/injection exposure risk; PEP is an emergency 28-day antiretroviral course after a substantial exposure and should begin as soon as possible, ideally within hours and no later than the recommended 72-hour window.",
    diagnostics: "Before PrEP confirm HIV-negative status with current antigen/antibody testing and HIV RNA when acute infection is possible, assess renal function for tenofovir-containing oral regimens, HBV status, pregnancy and STI screening. PEP baseline testing includes source/exposure risk, HIV, hepatitis, pregnancy and renal/hepatic context but should not delay the first dose.",
    priorities: "Offer daily oral F/TDF or F/TAF where approved/appropriate or long-acting injectable cabotegravir based on patient population, renal function, exposure route and preference. Provide three-drug PEP for qualifying exposures and transition ongoing-risk patients directly from PEP to PrEP after appropriate HIV testing.",
    medicationSafety: "F/TDF and F/TAF have different renal/bone profiles and population/route approvals; HBV-active oral PrEP should not be stopped abruptly in chronic HBV without follow-up because hepatitis flare can occur. Long-acting cabotegravir requires reliable HIV testing because resistance can emerge with undiagnosed infection.",
    redFlags: "Symptoms of acute HIV during PrEP/PEP, severe renal/hepatic toxicity or ongoing high-risk exposure with uncertain adherence requires urgent expert testing/regimen review.",
    examTraps: "Do not require a patient to name a specific risk behavior before offering PrEP if they request it and have no contraindication. PEP is not useful when started beyond the evidence-based exposure window; ongoing risk needs PrEP.",
    sourceKeys: ["CDC_PREP_CURRENT", "CDC_PEP_CURRENT"],
  },
  {
    slug: "sti-screening-primary-care",
    title: "STI Screening & Sexual Health Prevention",
    bodySystem: "Preventive Care",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "WHNP", "PNP"],
    recognize: "STI screening is site- and exposure-specific and should be based on anatomy, sexual practices, age, pregnancy and risk rather than identity assumptions. Many gonorrhea/chlamydia infections are asymptomatic and extragenital infection is missed by urine-only testing.",
    diagnostics: "Use NAAT from all exposed sites for gonorrhea/chlamydia, serology for HIV/syphilis and organism-specific testing for hepatitis and other infections according to CDC/USPSTF recommendations. Take a normalizing sexual history using partners/practices/protection/pregnancy goals and prior STI history.",
    priorities: "Screen recommended groups at appropriate intervals, vaccinate for HPV/hepatitis, provide PrEP when eligible, treat positive infections promptly and implement partner services/expedited partner therapy where legally and clinically appropriate.",
    medicationSafety: "Avoid empiric repeat antibiotics for persistent symptoms without reevaluation for reinfection, resistance, M. genitalium or noninfectious causes. Pregnancy changes treatment options for chlamydia, syphilis and other STIs.",
    redFlags: "Pregnancy with syphilis, disseminated gonococcal infection, PID/epididymo-orchitis with systemic illness, neurologic/ocular syphilis or acute HIV syndrome requires urgent specialty treatment.",
    examTraps: "Do not use cervical screening as an STI screen and do not assume monogamous identity means zero exposure risk without a clinical sexual history.",
    sourceKeys: ["CDC_STI_CURRENT", "USPSTF_STI_CURRENT"],
  },
  {
    slug: "falls-prevention-older-adults",
    title: "Falls Prevention in Older Adults",
    bodySystem: "Preventive Care",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "A fall is a syndrome with interacting gait/balance impairment, orthostasis, vision/hearing deficits, sedating/anticholinergic medications, neuropathy, foot problems, environmental hazards and osteoporosis. A patient who says 'I just tripped' still deserves risk assessment after recurrent or injurious falls.",
    diagnostics: "Ask falls/near-falls and fear of falling, check orthostatic BP, gait/balance and lower-extremity strength, vision/feet, cognition and medication burden. Evaluate syncope/arrhythmia/neurologic disease when the event included loss of consciousness or unexplained collapse rather than labeling it a mechanical fall.",
    priorities: "Use multicomponent intervention: deprescribe high-risk drugs where possible, strength/balance exercise, PT/assistive device, home-safety modification, vision/footwear and osteoporosis treatment. Correct vitamin-D deficiency but do not use high-dose vitamin D as a generic falls drug in replete adults.",
    medicationSafety: "Benzodiazepines, sedative-hypnotics, anticholinergics, opioids and some antihypertensives raise falls risk; deprescribe gradually when dependence/withdrawal is possible rather than abruptly stopping them.",
    redFlags: "Fall with head trauma/anticoagulation, focal deficit, syncope, hip pain/inability to bear weight, severe orthostasis or recurrent unexplained falls requires urgent diagnostic evaluation.",
    examTraps: "Do not focus only on a cane or home rug and ignore medications/orthostasis. A negative initial x-ray does not exclude occult hip fracture when the patient cannot bear weight.",
    sourceKeys: ["AGS_FALLS_CURRENT", "USPSTF_FALLS_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
