import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch64 = [
  {
    slug: "febrile-infant-8-60-days",
    title: "Well-Appearing Febrile Infant 8–60 Days",
    bodySystem: "Pediatrics",
    applicableExams: ["PNP", "AANP-FNP", "ANCC-FNP", "ENP"],
    recognize: "A rectal temperature of at least 38.0°C in a term, previously healthy infant 8–60 days old is managed by age-specific invasive-bacterial-infection risk pathways even when the infant looks well. Ill appearance, prematurity, focal infection or major comorbidity falls outside the low-risk guideline pathway and requires broader care.",
    diagnostics: "Follow the AAP age bands: urine testing/culture is central throughout; younger infants require blood culture and inflammatory markers, with CSF evaluation more routinely in the youngest group and selectively in older low-risk infants according to markers/shared decision. Do not use urinalysis alone to rule out bacteremia/meningitis in the youngest infants.",
    priorities: "Infants at highest age/risk require hospitalization and parenteral antibiotics after cultures/CSF when appropriate; carefully selected older low-risk infants can be managed without empiric antibiotics or as outpatients only when reliable 24-hour follow-up and return access exist.",
    medicationSafety: "Empiric antibiotic choice depends on age and meningitis/HSV risk; ceftriaxone has neonatal bilirubin/calcium considerations and should not be substituted blindly across age groups. Add acyclovir only when HSV risk features justify it.",
    redFlags: "Ill appearance, poor perfusion, apnea, seizure, bulging fontanelle, vesicles, maternal HSV concern, marked inflammatory-marker elevation or unreliable follow-up requires hospital-level management.",
    examTraps: "Do not apply the 8–60-day well-infant pathway to a toxic infant or premature/medically complex infant and do not dismiss a parent-measured true rectal fever because the temperature normalizes in clinic.",
    sourceKeys: ["AAP_FEBRILE_INFANT_2021_CURRENT"],
  },
  {
    slug: "neonatal-hyperbilirubinemia",
    title: "Neonatal Hyperbilirubinemia",
    bodySystem: "Pediatrics",
    applicableExams: ["PNP", "AANP-FNP", "ANCC-FNP"],
    recognize: "Newborn jaundice requires bilirubin interpreted by postnatal age in hours, gestational age and neurotoxicity risk factors. Jaundice in the first 24 hours, rapid rise, poor feeding/dehydration or prolonged direct hyperbilirubinemia is not routine physiologic jaundice.",
    diagnostics: "Measure TcB/TSB according to newborn screening protocol and confirm near-treatment transcutaneous values with serum bilirubin. Evaluate hemolysis with blood type/DAT/CBC/reticulocytes/G6PD when suggested and fractionate bilirubin for prolonged jaundice or cholestasis.",
    priorities: "Use the AAP 2022 gestational-age/risk-specific phototherapy and exchange-transfusion thresholds, optimize feeding/hydration and arrange follow-up based on distance from treatment threshold. Escalation-of-care thresholds require urgent intensive phototherapy and preparation for exchange transfusion.",
    medicationSafety: "Do not use sunlight as medical phototherapy and avoid unnecessary formula supplementation when breastfeeding is otherwise adequate; supplementation becomes therapeutic when intake/dehydration contributes to unsafe bilirubin rise. Ceftriaxone has important neonatal bilirubin displacement/calcium concerns.",
    redFlags: "Acute bilirubin encephalopathy—lethargy, poor suck, hypertonia/arching, high-pitched cry—or bilirubin at/near exchange threshold requires emergency neonatal care.",
    examTraps: "Visible jaundice cannot estimate the bilirubin reliably, and old fixed '20 mg/dL' rules ignore gestational age, hours of life and neurotoxicity risk.",
    sourceKeys: ["AAP_HYPERBILIRUBINEMIA_2022_CURRENT"],
  },
  {
    slug: "pediatric-heart-murmur-congenital-heart",
    title: "Pediatric Heart Murmurs & Congenital Heart Disease Triage",
    bodySystem: "Pediatrics",
    applicableExams: ["PNP", "AANP-FNP", "ANCC-FNP", "ENP"],
    recognize: "Most childhood murmurs are innocent, but diastolic/holosystolic harsh murmurs, loud grade, abnormal S2/click, cyanosis, poor feeding, diaphoresis, exercise intolerance, syncope or poor growth raises structural-heart concern. Critical congenital lesions may present with shock as ductal flow closes.",
    diagnostics: "Assess pre/postductal oxygen saturation in newborns, pulses/four-limb perfusion and murmur characteristics; ECG/CXR are not efficient screening tests for every asymptomatic innocent-sounding murmur. Refer suspicious findings to pediatric cardiology for echocardiography rather than ordering indiscriminate echo for every murmur.",
    priorities: "Reassure clearly innocent murmurs with normal growth/exam, but urgently refer cyanosis, abnormal pulses, exertional syncope/chest pain or pathologic murmur. Suspected ductal-dependent neonatal disease requires prostaglandin E1 and neonatal cardiac transfer.",
    medicationSafety: "Prostaglandin E1 can cause apnea/hypotension and requires airway-capable monitoring; do not give endocarditis prophylaxis for innocent murmurs or most repaired/simple congenital lesions outside current AHA high-risk indications.",
    redFlags: "Cyanosis, shock, absent femoral pulses, exertional syncope, severe respiratory distress or neonate with ductal-dependent physiology requires emergency cardiology care.",
    examTraps: "A normal pulse oximetry screen does not exclude all congenital heart disease and an innocent murmur does not require activity restriction or antibiotic prophylaxis.",
    sourceKeys: ["AAP_CONGENITAL_HEART_SCREENING_CURRENT", "AHA_PEDS_CHD_CURRENT"],
  },
  {
    slug: "pediatric-hypertension",
    title: "Pediatric Hypertension Evaluation",
    bodySystem: "Pediatrics",
    applicableExams: ["PNP", "AANP-FNP", "ANCC-FNP"],
    recognize: "Pediatric BP interpretation is age/sex/height percentile-based in younger children and uses adolescent thresholds later. Obesity-associated primary hypertension is increasingly common, but very young age, severe BP, abnormal renal findings or poor growth raises secondary-cause concern.",
    diagnostics: "Confirm elevated automated readings manually with appropriate cuff and repeated visits; ambulatory BP monitoring helps confirm hypertension/white-coat patterns. Evaluate urine/renal function, lipids/metabolic risk and renal ultrasound or endocrine/coarctation testing according to age/severity/phenotype.",
    priorities: "Use DASH-style nutrition, activity, sleep/weight treatment and address OSA; start medication for symptomatic/stage 2 hypertension, target-organ damage, CKD/diabetes or persistent hypertension despite lifestyle therapy, choosing ACEi/ARB, long-acting CCB or thiazide according to comorbidity.",
    medicationSafety: "ACEi/ARBs are teratogenic and require pregnancy counseling in adolescents; all antihypertensives require monitoring for hypotension/electrolyte/renal effects. Avoid stimulant/decongestant contributors when BP is problematic.",
    redFlags: "Severe hypertension with neurologic symptoms, heart failure, AKI, visual symptoms or suspected catecholamine/renal vascular crisis requires emergency treatment.",
    examTraps: "Do not diagnose hypertension from one high reading or use an adult cuff on a small arm. Obesity does not eliminate the need to look for secondary disease when age/severity is atypical.",
    sourceKeys: ["AAP_PEDIATRIC_HYPERTENSION_CURRENT"],
  },
  {
    slug: "sports-preparticipation-cardiac-risk",
    title: "Sports Preparticipation & Sudden Cardiac Risk",
    bodySystem: "Pediatrics",
    applicableExams: ["PNP", "AANP-FNP", "ANCC-FNP"],
    recognize: "Preparticipation evaluation seeks conditions that increase sudden death/injury risk while supporting safe activity. Exertional syncope, chest pain, disproportionate dyspnea, palpitations or family history of sudden unexplained death/cardiomyopathy are high-yield cardiac warning features.",
    diagnostics: "Use focused personal/family cardiac history and physical exam including BP, pulses and murmur with dynamic maneuvers. Routine ECG/echo screening of every asymptomatic U.S. athlete is not universally recommended; obtain cardiac testing when history/exam is concerning or a program follows a validated screening protocol.",
    priorities: "Restrict from intense sport temporarily and refer concerning exertional symptoms, pathologic murmur or inherited-cardiac risk; otherwise encourage activity. Also assess concussion history, heat risk, asthma, sickle-cell trait counseling and musculoskeletal readiness.",
    medicationSafety: "Stimulant therapy for ADHD is not an automatic sports contraindication but requires BP/HR and cardiac-history review; beta-agonist asthma treatment should be optimized rather than hiding uncontrolled disease.",
    redFlags: "Exertional syncope, exertional chest pain, family sudden death, cardiomyopathy/long-QT/Marfan features or abnormal cardiac exam requires cardiology evaluation before clearance.",
    examTraps: "A screening ECG is not a substitute for history/exam, and denying all sports to a child with a benign murmur or well-controlled chronic disease causes unnecessary harm.",
    sourceKeys: ["AHA_AAP_PREPARTICIPATION_CURRENT"],
  },
  {
    slug: "adolescent-substance-use-screening",
    title: "Adolescent Substance Use Screening & Intervention",
    bodySystem: "Pediatrics",
    applicableExams: ["PNP", "AANP-FNP", "ANCC-FNP", "PMHNP"],
    recognize: "Adolescent nicotine/vaping, alcohol, cannabis, opioid and stimulant use may present through school decline, mood/sleep change, injuries or family concern. Confidential developmentally appropriate screening increases disclosure and must distinguish experimentation, risky use and substance-use disorder.",
    diagnostics: "Use a validated tool such as CRAFFT, assess frequency, impairment, driving/riding risk, overdose, mental health, pregnancy/sexual risk and home safety. Explain confidentiality limits before screening; toxicology testing is selective and should not replace history or become punitive.",
    priorities: "Provide brief motivational intervention for lower-risk use, involve family support when appropriate/safe and refer moderate-severe disorders to adolescent addiction treatment. Provide naloxone and medication for opioid-use disorder—including buprenorphine when clinically appropriate—rather than insisting on abstinence-only counseling.",
    medicationSafety: "Avoid benzodiazepine or stimulant prescribing without reassessing misuse/diversion risk while still treating legitimate ADHD/anxiety through safer structured plans. Cannabis is not a benign treatment for adolescent anxiety/sleep.",
    redFlags: "Overdose, withdrawal risk, injection use, suicidal behavior, intoxicated driving, psychosis or unsafe home exposure requires urgent intervention.",
    examTraps: "Do not promise absolute confidentiality before explaining safety limits and do not use a positive urine screen as proof of a substance-use disorder without clinical criteria.",
    sourceKeys: ["AAP_SUBSTANCE_USE_CURRENT", "SAMHSA_ADOLESCENT_SUD_CURRENT"],
  },
  {
    slug: "vaccine-hesitancy-pediatrics",
    title: "Pediatric Vaccine Hesitancy & Catch-Up",
    bodySystem: "Pediatrics",
    applicableExams: ["PNP", "AANP-FNP", "ANCC-FNP"],
    recognize: "Vaccine hesitancy ranges from questions to delayed/refused vaccination and is influenced by trust, misinformation, access and prior experiences. A strong presumptive recommendation from a trusted clinician is one of the most effective interventions.",
    diagnostics: "Review the actual immunization record against the current CDC child/adolescent schedule and catch-up table; identify true contraindications such as severe allergy or selected live-vaccine immune/pregnancy states. Mild illness, antibiotics and most local reactions are not contraindications.",
    priorities: "Use a presumptive recommendation, then motivational interviewing for concerns; give all eligible vaccines at the same visit and use catch-up minimum intervals without restarting series. Address pain/fainting management and schedule the next dose before the family leaves.",
    medicationSafety: "Avoid prophylactic acetaminophen before vaccination solely to prevent fever because it is usually unnecessary; treat post-vaccine discomfort when needed. Live vaccines require immune-status review and some immune products alter timing.",
    redFlags: "Anaphylaxis or serious neurologic/cardiac symptoms after vaccination requires urgent treatment and appropriate reporting, not abandonment of all future vaccination without specialist review.",
    examTraps: "Do not restart a delayed series and do not create extra contraindications from internet myths or family history. Catch-up vaccination can occur even when the child is behind by years.",
    sourceKeys: ["CDC_CHILD_IMMUNIZATION_2026", "AAP_VACCINE_COMMUNICATION_CURRENT"],
  },
  {
    slug: "adolescent-menstrual-disorders",
    title: "Adolescent Menstrual Disorders",
    bodySystem: "Pediatrics",
    applicableExams: ["PNP", "AANP-FNP", "ANCC-FNP", "WHNP"],
    recognize: "Irregular cycles are common soon after menarche, but very heavy bleeding, cycles persistently outside expected adolescent ranges, prolonged amenorrhea or symptoms of anemia/endocrine disease require evaluation. Heavy bleeding at menarche can be the first presentation of von Willebrand disease.",
    diagnostics: "Check pregnancy when biologically possible, CBC/ferritin for heavy bleeding and TSH/coagulation/androgen testing according to phenotype; use a bleeding history to decide vWD evaluation. Pelvic ultrasound is not routine for typical anovulatory adolescent bleeding without structural/red-flag findings.",
    priorities: "Treat acute heavy bleeding based on hemodynamics/anemia using high-dose hormonal or antifibrinolytic strategies, then provide cycle/endometrial control and iron replacement. Evaluate PCOS carefully after enough postmenarchal maturation rather than labeling normal early irregularity as PCOS.",
    medicationSafety: "Estrogen-containing therapy has thrombotic contraindications; tranexamic acid is used with individualized thrombosis context. Avoid routine D&C in adolescents unless bleeding is refractory/life-threatening and specialist-directed.",
    redFlags: "Hemodynamic instability, symptomatic severe anemia, pregnancy-related bleeding, severe pelvic pain/torsion concern or uncontrolled hemorrhage requires emergency gynecologic care.",
    examTraps: "Do not diagnose PCOS from irregular cycles in the first year after menarche alone and do not miss a bleeding disorder in an adolescent with heavy menstrual bleeding since menarche.",
    sourceKeys: ["ACOG_ADOLESCENT_HEAVY_MENSES_CURRENT", "PCOS_INTERNATIONAL_2023"],
  }
] as const satisfies readonly UsNpCramLesson[];
