import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch12 = [
  {
    slug: "stimulant-use-disorder",
    title: "Stimulant Use Disorder",
    bodySystem: "Psychiatric",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGACNP", "PMHNP", "ENP"],
    recognize: "Cocaine or methamphetamine use can present with agitation, chest pain, hypertension, hyperthermia, psychosis, insomnia, weight loss, or crash-phase depression. Ask route, amount, fentanyl contamination risk, co-use, and cardiovascular symptoms.",
    diagnostics: "Diagnosis of stimulant use disorder is clinical. In acute toxicity obtain ECG, temperature, glucose, electrolytes or CK as indicated, troponin for ischemic symptoms, and toxicology only when it changes management.",
    priorities: "Acute management prioritizes cooling, benzodiazepine-based control of severe agitation or sympathetic excess when appropriate, hydration, and treatment of ischemia or complications. Long-term treatment relies on contingency management and evidence-based behavioral care; no medication is universally approved as a stand-alone cure.",
    medicationSafety: "Avoid reflexively adding sedating medications without considering polysubstance exposure and respiratory risk. Review QT-prolonging and serotonergic combinations when treating co-occurring psychiatric disease.",
    redFlags: "Chest pain, severe hypertension, hyperthermia, seizure, rhabdomyolysis, psychosis with danger, or suicidal crash-phase depression requires emergency care.",
    examTraps: "A positive stimulant screen does not prove acute intoxication or impairment. Do not miss fentanyl exposure merely because the patient reports using only stimulants.",
    sourceKeys: ["SAMHSA_STIMULANT_CURRENT", "ASAM_STIMULANT_CURRENT"],
  },
  {
    slug: "tobacco-nicotine-use",
    title: "Tobacco & Nicotine Use Disorder",
    bodySystem: "Psychiatric",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PMHNP", "PNP", "WHNP"],
    recognize: "Ask about cigarettes, vaping, smokeless tobacco, nicotine pouches, secondhand exposure, dependence severity, prior quit attempts, triggers, and readiness. Adolescents and pregnant patients need tailored assessment rather than assuming cigarette-only exposure.",
    diagnostics: "No special laboratory test is required to diagnose nicotine dependence. Quantify use, assess cardiopulmonary disease, pregnancy, mental health, and medication interactions affected by smoking status, especially CYP1A2 substrates.",
    priorities: "Use brief counseling plus pharmacotherapy for nonpregnant adults when appropriate. Combination nicotine replacement, varenicline, or bupropion can improve quit success; provide proactive follow-up and relapse planning.",
    medicationSafety: "Varenicline can cause nausea or vivid dreams; bupropion lowers seizure threshold and has contraindications; nicotine replacement dosing should match baseline use. Stopping tobacco smoke can raise levels of some medications even though nicotine itself is not the main CYP1A2 inducer.",
    redFlags: "Acute chest pain, severe dyspnea, suspected vaping-associated lung injury, nicotine poisoning, or severe psychiatric destabilization needs urgent assessment.",
    examTraps: "Do not wait for perfect readiness before offering treatment. Vaping is not harmless, and dual use does not equal successful smoking cessation.",
    sourceKeys: ["USPSTF_TOBACCO_CURRENT", "CDC_TOBACCO_CURRENT"],
  },
  {
    slug: "bronchiolitis",
    title: "Bronchiolitis",
    bodySystem: "Pediatrics",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PNP", "ENP"],
    recognize: "Infants with viral URI symptoms followed by cough, tachypnea, wheeze or crackles, feeding difficulty, and increased work of breathing commonly have bronchiolitis. Young age, prematurity, congenital heart or lung disease, and immunocompromise increase risk.",
    diagnostics: "Diagnosis is clinical in typical cases. Routine chest x-ray, viral panels, and broad labs are not needed unless the course is atypical, severe, or another diagnosis is suspected.",
    priorities: "Supportive care is the treatment: nasal suction, hydration or feeding support, and oxygen when clinically indicated. Disposition depends on age, oxygenation, work of breathing, feeding, apnea risk, and caregiver reliability.",
    medicationSafety: "Routine bronchodilators, corticosteroids, and antibiotics are not recommended for typical bronchiolitis. If another diagnosis such as asthma or bacterial infection is suspected, treat that condition on its own evidence.",
    redFlags: "Apnea, cyanosis, exhaustion, severe retractions, persistent hypoxemia, dehydration, or inability to feed requires urgent or emergency evaluation.",
    examTraps: "Wheezing does not automatically mean asthma in an infant. A chest x-ray showing nonspecific peribronchial changes should not trigger antibiotics by itself.",
    sourceKeys: ["AAP_BRONCHIOLITIS_CURRENT"],
  },
  {
    slug: "croup",
    title: "Croup",
    bodySystem: "Pediatrics",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PNP", "ENP"],
    recognize: "Barking cough, hoarseness, and inspiratory stridor after a viral prodrome suggest croup. Severity is based on stridor at rest, retractions, air entry, agitation or lethargy, and oxygenation rather than fever alone.",
    diagnostics: "Typical croup is a clinical diagnosis. Consider epiglottitis, bacterial tracheitis, foreign body, anaphylaxis, or airway anomaly when drooling, toxic appearance, abrupt onset, focal findings, or poor response is present.",
    priorities: "Give corticosteroid for croup of any meaningful severity; nebulized epinephrine is used for moderate or severe stridor with observation for recurrence. Keep the child calm and avoid unnecessary upsetting procedures.",
    medicationSafety: "Dexamethasone is commonly used because of long duration. Nebulized epinephrine improves airway edema temporarily but does not replace observation or escalation when symptoms recur.",
    redFlags: "Stridor at rest with fatigue, cyanosis, altered mental status, drooling or tripod posture, severe retractions, or poor air movement requires emergency airway-capable care.",
    examTraps: "Do not inspect the throat aggressively when epiglottitis is a serious possibility. Stridor is upper-airway noise; wheeze is lower-airway noise and points to a different differential.",
    sourceKeys: ["AAP_CROUP_CURRENT"],
  },
  {
    slug: "pediatric-uti",
    title: "Pediatric UTI",
    bodySystem: "Pediatrics",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PNP", "ENP"],
    recognize: "Infants may present with unexplained fever, poor feeding, vomiting, or irritability; older children more often have dysuria, frequency, abdominal or flank pain, or new incontinence. Fever plus urinary findings raises concern for pyelonephritis.",
    diagnostics: "Obtain urine using an age-appropriate low-contamination method before antibiotics when feasible. Diagnosis requires compatible symptoms plus urinalysis or culture evidence; imaging decisions depend on age, recurrence, severity, and current pediatric guidance.",
    priorities: "Treat promptly with an antibiotic appropriate to local resistance, prior cultures, age, allergy, renal function, and illness severity. Ensure follow-up for recurrent febrile infections or structural concerns.",
    medicationSafety: "Nitrofurantoin is not appropriate for febrile pyelonephritis because tissue levels are inadequate. Dose antibiotics by weight and verify concentration and maximum dose.",
    redFlags: "Toxic appearance, young febrile infant, dehydration, vomiting preventing oral therapy, sepsis, or obstructive uropathy concern requires urgent evaluation.",
    examTraps: "A bagged urine culture is prone to contamination and should not be used as definitive proof of UTI. Pyuria without symptoms does not automatically require antibiotics.",
    sourceKeys: ["AAP_PEDS_UTI_CURRENT"],
  },
  {
    slug: "pediatric-eczema",
    title: "Pediatric Atopic Dermatitis",
    bodySystem: "Pediatrics",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PNP"],
    recognize: "Chronic relapsing pruritic eczema with age-typical distribution and xerosis suggests atopic dermatitis. Ask about sleep disruption, infection, food-allergy history, asthma or allergic rhinitis, irritants, and treatment adherence.",
    diagnostics: "Diagnosis is clinical. Routine food-allergy panels are not indicated for every child with eczema; test when the history suggests a reproducible immediate food reaction or specialist-directed evaluation is warranted.",
    priorities: "Daily emollients and trigger or skin-barrier care are foundational. Use topical anti-inflammatory therapy matched to site and severity, treat secondary infection when present, and escalate refractory moderate or severe disease to dermatology or allergy.",
    medicationSafety: "Topical corticosteroid potency and duration should match age and body site; avoid chronic high-potency use on thin skin. Calcineurin inhibitors and newer topical or systemic agents have age-specific indications and counseling needs.",
    redFlags: "Eczema herpeticum, rapidly spreading painful vesicles, fever or toxicity, periorbital involvement, or extensive bacterial infection needs urgent assessment.",
    examTraps: "Do not tell families to avoid multiple foods without evidence; restrictive diets can impair growth. Topical steroids used appropriately are safer than chronically undertreated severe inflammation.",
    sourceKeys: ["AAD_ATOPIC_DERM_CURRENT", "AAP_ECZEMA_CURRENT"],
  },
  {
    slug: "pediatric-obesity",
    title: "Pediatric Obesity",
    bodySystem: "Pediatrics",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PNP"],
    recognize: "Evaluate BMI percentile and growth trajectory in context, while using nonstigmatizing language. Obesity can coexist with hypertension, dyslipidemia, diabetes, fatty liver disease, sleep apnea, orthopedic problems, depression, and disordered eating.",
    diagnostics: "Assess BP, family history, sleep, nutrition, activity, medications, mental health, social determinants, and age-appropriate metabolic screening according to current pediatric guidance. Do not order endocrine testing without clues to an endocrine cause.",
    priorities: "Use intensive family-based health behavior and lifestyle treatment when available. Adolescents with severe disease may qualify for anti-obesity pharmacotherapy or metabolic or bariatric surgery evaluation alongside ongoing behavioral care.",
    medicationSafety: "Weight-management medications have age, pregnancy, adverse-effect, and monitoring considerations. Avoid stimulants or unregulated supplements marketed for weight loss.",
    redFlags: "Severe hypertension, symptomatic hyperglycemia, suicidality or eating disorder, obesity hypoventilation, or acute orthopedic complication needs prompt specialty or emergency evaluation.",
    examTraps: "Do not assume obesity is caused by laziness or poor parenting. Short stature or poor linear growth—not obesity alone—is a stronger clue to some endocrine causes.",
    sourceKeys: ["AAP_OBESITY_2023"],
  },
  {
    slug: "pediatric-type1-diabetes",
    title: "Pediatric Type 1 Diabetes",
    bodySystem: "Pediatrics",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PNP", "ENP"],
    recognize: "Polyuria, polydipsia, nocturia or new enuresis, weight loss, fatigue, and candidiasis can signal new type 1 diabetes. Vomiting, abdominal pain, Kussmaul respirations, fruity breath, or altered mentation suggests DKA.",
    diagnostics: "Confirm hyperglycemia with accepted diagnostic criteria and assess ketones, electrolytes, bicarbonate or venous pH, and hydration when symptomatic. Autoantibodies help classify diabetes after stabilization when the type is uncertain.",
    priorities: "New symptomatic type 1 diabetes requires prompt pediatric diabetes involvement and insulin education. Sick-day rules, ketone testing, hypoglycemia treatment, CGM or technology education, school planning, and family support are essential.",
    medicationSafety: "Insulin dosing is individualized and carries hypoglycemia risk. Never stop basal insulin during intercurrent illness without specialist guidance; pump interruption can lead rapidly to ketosis because no long-acting insulin is present.",
    redFlags: "DKA symptoms, severe hypoglycemia, dehydration, altered mental status, or inability to manage insulin safely requires emergency evaluation.",
    examTraps: "Do not mislabel weight loss and abdominal symptoms as gastroenteritis without checking glucose when diabetes symptoms are present. Type 1 diabetes can occur at any body size.",
    sourceKeys: ["ADA_2026", "ISPAD_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
