import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch63 = [
  {
    slug: "disseminated-intravascular-coagulation",
    title: "Disseminated Intravascular Coagulation",
    bodySystem: "Critical Care",
    applicableExams: ["AGACNP", "ENP", "AANP-FNP", "ANCC-FNP", "WHNP"],
    recognize: "DIC is systemic pathologic coagulation activation with consumption of platelets/factors and secondary fibrinolysis, producing bleeding, microvascular thrombosis and organ dysfunction. Sepsis, trauma, placental abruption/obstetric catastrophe, malignancy and severe shock are common triggers.",
    diagnostics: "Trend platelets, PT/INR, aPTT, fibrinogen, D-dimer/fibrin markers, smear and organ function; use an ISTH-type scoring approach in the correct clinical context. Early sepsis-associated DIC can have a normal or elevated fibrinogen because it is an acute-phase reactant, so a single normal value does not exclude evolving DIC.",
    priorities: "Treat the underlying trigger aggressively and support hemorrhage/organ perfusion. Give platelets, fibrinogen-containing product and plasma for clinically important bleeding or procedures according to deficits rather than transfusing solely to normalize laboratory values in a stable nonbleeding patient.",
    medicationSafety: "Anticoagulation is not routine for actively bleeding DIC but may be appropriate when thrombosis predominates or for standard VTE prophylaxis once bleeding risk permits. Massive blood-product use requires calcium, temperature and volume monitoring.",
    redFlags: "Major bleeding, purpura fulminans, rapidly falling fibrinogen/platelets, limb ischemia, shock or multiorgan failure requires ICU/hematology management.",
    examTraps: "Do not require prolonged PT/aPTT or low fibrinogen early in DIC and do not confuse DIC with TTP, where coagulation tests are often near normal and plasma exchange is lifesaving.",
    sourceKeys: ["ISTH_DIC_CURRENT", "SCCM_SEPSIS_COAGULATION_CURRENT"],
  },
  {
    slug: "massive-transfusion-trauma-coagulopathy",
    title: "Massive Transfusion & Trauma-Induced Coagulopathy",
    bodySystem: "Critical Care",
    applicableExams: ["AGACNP", "ENP"],
    recognize: "Hemorrhagic shock causes tissue hypoperfusion plus dilution, hypothermia, acidosis and hypocalcemia that worsen coagulopathy. A patient can be exsanguinating before hemoglobin falls; physiology and bleeding rate drive activation of a massive-transfusion pathway.",
    diagnostics: "Use serial hemodynamics, lactate/base deficit, temperature, ionized calcium, CBC/coagulation/fibrinogen and viscoelastic testing when available to guide resuscitation. Search for surgically/interventionally controllable bleeding rather than treating coagulopathy as the primary source.",
    priorities: "Activate balanced blood-component or whole-blood resuscitation early, minimize unnecessary crystalloid, warm the patient/products, replace calcium and achieve rapid hemorrhage control. TXA is used for appropriately bleeding trauma patients early within the evidence-based time window, not as a late routine dose.",
    medicationSafety: "Large citrate loads cause hypocalcemia and products can cause hyperkalemia, hypothermia, TACO/TRALI and dilutional abnormalities. Fibrinogen/cryoprecipitate and platelets are guided by bleeding plus laboratory/viscoelastic deficits rather than fixed endless ratios after hemorrhage control.",
    redFlags: "Persistent shock despite blood, ongoing noncompressible hemorrhage, profound hypocalcemia, severe acidosis/hypothermia or transfusion reaction requires immediate trauma/transfusion escalation.",
    examTraps: "Do not wait for a low hemoglobin to activate hemorrhage resuscitation and do not continue massive transfusion once bleeding is controlled without reassessing product needs and complications.",
    sourceKeys: ["ACS_TRAUMA_BLOOD_CURRENT", "AABB_MASSIVE_TRANSFUSION_CURRENT"],
  },
  {
    slug: "abdominal-compartment-syndrome",
    title: "Abdominal Compartment Syndrome",
    bodySystem: "Critical Care",
    applicableExams: ["AGACNP", "ENP"],
    recognize: "Rising intra-abdominal pressure can impair venous return, ventilation, renal perfusion and gut flow after massive resuscitation, pancreatitis, abdominal trauma, ileus or edema. A tense abdomen plus worsening ventilator pressures, oliguria and shock should prompt concern.",
    diagnostics: "Measure intra-abdominal pressure indirectly via standardized bladder-pressure technique when risk and organ dysfunction suggest the syndrome. Imaging can identify contributing fluid/hematoma but the diagnosis is pressure plus new organ dysfunction, not CT appearance alone.",
    priorities: "Improve abdominal-wall compliance, evacuate intraluminal contents, drain appropriate intraperitoneal fluid, optimize sedation/position and avoid ongoing fluid overload; refractory abdominal compartment syndrome with organ failure requires urgent surgical decompression.",
    medicationSafety: "Neuromuscular blockade may temporarily reduce abdominal-wall tone but is a bridge, not definitive therapy. Diuresis/ultrafiltration is only appropriate when perfusion permits and should not delay decompression in a crashing patient.",
    redFlags: "Progressive oliguria/anuria, refractory hypotension, severe ventilatory pressure rise or lactate/ischemia with high intra-abdominal pressure requires immediate surgical/critical-care intervention.",
    examTraps: "A distended abdomen alone is not abdominal compartment syndrome and a normal-looking abdominal CT cannot exclude dangerous pressure physiology.",
    sourceKeys: ["WSACS_ABDOMINAL_COMPARTMENT_CURRENT"],
  },
  {
    slug: "acute-mesenteric-ischemia",
    title: "Acute Mesenteric Ischemia",
    bodySystem: "Critical Care",
    applicableExams: ["AGACNP", "ENP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "Sudden severe abdominal pain out of proportion to early examination—especially with AF, atherosclerosis, low-flow shock or hypercoagulability—raises acute mesenteric ischemia. As bowel infarction advances, tenderness/peritonitis and shock appear.",
    diagnostics: "Obtain urgent CT angiography without delaying for nonspecific lactate results; normal lactate early does not exclude ischemia. Assess embolic versus thrombotic arterial disease, mesenteric venous thrombosis and nonocclusive low-flow ischemia because treatment differs.",
    priorities: "Start resuscitation, broad antibiotics and systemic anticoagulation when not contraindicated, then obtain immediate vascular/general-surgery expertise for revascularization and bowel-viability assessment. Nonocclusive disease requires reversal of low-flow/vasoconstrictive triggers.",
    medicationSafety: "Avoid delays for oral contrast and avoid escalating vasoconstrictors without reassessing mesenteric perfusion in nonocclusive disease. Anticoagulation is central for venous thrombosis and many arterial cases but is individualized with active bleeding/surgery.",
    redFlags: "Peritonitis, pneumatosis/portal venous gas with ischemic context, shock, rising lactate/acidosis or bowel necrosis requires immediate operative management.",
    examTraps: "Do not wait for bloody stool or high lactate and do not dismiss severe pain because the abdomen is initially soft.",
    sourceKeys: ["WSES_MESENTERIC_ISCHEMIA_CURRENT"],
  },
  {
    slug: "acute-limb-compartment-syndrome",
    title: "Acute Limb Compartment Syndrome",
    bodySystem: "Critical Care",
    applicableExams: ["AGACNP", "ENP", "AANP-FNP", "ANCC-FNP"],
    recognize: "Escalating pain out of proportion, pain with passive stretch, tense compartment and progressive sensory/motor deficit after fracture, crush, reperfusion or tight dressing/cast suggests acute compartment syndrome. Pulses can remain present until late because compartment pressure compromises microcirculation first.",
    diagnostics: "Diagnosis is clinical in a reliable classic presentation; measure compartment pressure when exam is equivocal or the patient cannot report symptoms. Trend neurologic findings and remove external constriction immediately while arranging surgery.",
    priorities: "Keep the limb at heart level, remove tight casts/dressings and obtain emergency orthopedic fasciotomy for established syndrome. Treat rhabdomyolysis, hyperkalemia and associated fracture/vascular injury concurrently.",
    medicationSafety: "Analgesia should not delay repeated examination; regional blocks/deep sedation can obscure symptoms and require appropriate monitoring in high-risk patients. Do not elevate the limb far above the heart because it can reduce arterial perfusion.",
    redFlags: "Progressive motor weakness, anesthesia, rapidly rising compartment pressure, severe pain despite analgesia or crush injury with systemic rhabdomyolysis requires immediate surgical intervention.",
    examTraps: "Do not wait for pulselessness—the '6 Ps' late findings are too late for safe diagnosis. A normal x-ray does not exclude compartment syndrome.",
    sourceKeys: ["AAOS_COMPARTMENT_SYNDROME_CURRENT"],
  },
  {
    slug: "tracheostomy-emergency",
    title: "Tracheostomy Emergency Management",
    bodySystem: "Critical Care",
    applicableExams: ["AGACNP", "ENP"],
    recognize: "Acute tracheostomy distress may result from mucus plug, tube displacement/false passage, bleeding, pneumothorax or equipment failure. A fresh surgical tracheostomy has an immature tract and blind reinsertion can create a false passage.",
    diagnostics: "Assess oxygenation/ventilation, ability to pass suction catheter, tube position and capnography when available; remove speaking valve/cap and inner cannula if obstruction is possible. Determine whether the patient has a patent upper airway and how old/mature the tracheostomy tract is.",
    priorities: "Call airway expertise early, oxygenate both face and stoma when anatomy allows, suction/remove obstructed inner cannula and remove a clearly displaced/blocked tube if needed. Ventilate through the stoma or upper airway according to laryngectomy versus tracheostomy anatomy and established emergency algorithms.",
    medicationSafety: "Avoid repeated blind tube reinsertion into a fresh tract; sedation/paralysis can convert partial airway compromise into complete failure and should occur only with a definitive airway plan.",
    redFlags: "Massive tracheostomy bleeding, inability to ventilate, subcutaneous emphysema, fresh-tube displacement or suspected tracheo-innominate fistula requires immediate airway/ENT/thoracic emergency management.",
    examTraps: "A total laryngectomy patient cannot be oxygenated or intubated through the mouth/nose, while many tracheostomy patients can. Do not mistake a blocked speaking valve for primary lung failure.",
    sourceKeys: ["NTSP_TRACHEOSTOMY_EMERGENCY_CURRENT", "AARC_TRACHEOSTOMY_CURRENT"],
  },
  {
    slug: "central-venous-catheter-complications",
    title: "Central Venous Catheter Complications",
    bodySystem: "Critical Care",
    applicableExams: ["AGACNP", "ENP"],
    recognize: "Central-line complications include pneumothorax/hemothorax, arterial placement, air embolism, thrombosis, malposition, catheter-associated bloodstream infection and mechanical fracture/occlusion. Sudden dyspnea/hypotension after insertion or infusion resistance demands immediate assessment.",
    diagnostics: "Confirm tip position using the institution's validated method, use ultrasound/CT for suspected thrombosis or mechanical complication and obtain paired blood cultures for suspected CLABSI according to catheter/host context. Do not culture removed tips or lines routinely without clinical infection concern.",
    priorities: "Stabilize pneumothorax/bleeding/air embolism, remove or exchange infected lines according to organism/severity and maintain strict insertion/maintenance bundles. Use ultrasound guidance for placement and daily necessity review to reduce complications.",
    medicationSafety: "Never use thrombolytic declotting agents before excluding mechanical malposition or catheter damage; line-lock/antimicrobial strategies are indication-specific. Anticoagulation for catheter thrombosis depends on site, symptoms, catheter need and bleeding risk.",
    redFlags: "Tension pneumothorax, arterial cannulation with large-bore catheter, massive hemothorax, air embolism, persistent S. aureus/Candida bacteremia or septic shock requires urgent procedural/specialty action.",
    examTraps: "Do not simply pull a large-bore catheter placed in a major artery—vascular consultation may be required—and do not assume every positive line culture means the catheter is the source.",
    sourceKeys: ["CDC_CLABSI_CURRENT", "SIR_CENTRAL_LINE_CURRENT"],
  },
  {
    slug: "cardiac-tamponade-pericardiocentesis",
    title: "Cardiac Tamponade & Emergency Pericardiocentesis",
    bodySystem: "Critical Care",
    applicableExams: ["AGACNP", "ENP"],
    recognize: "Tamponade is obstructive shock from pericardial pressure impairing filling; tachycardia, elevated JVP, hypotension, pulsus paradoxus and electrical alternans may occur but the full Beck triad is insensitive. Rapid small effusions can tamponade at volumes tolerated by chronic large effusions.",
    diagnostics: "Use bedside echocardiography for effusion, right-atrial/right-ventricular diastolic collapse, respiratory inflow variation and IVC findings interpreted with the clinical picture; ECG/CXR are supportive but cannot rule tamponade out.",
    priorities: "Urgently drain hemodynamically significant tamponade with echo-guided pericardiocentesis or surgical window depending on etiology/anatomy, while providing cautious preload/pressor support as a bridge. Traumatic hemopericardium generally requires surgical trauma management rather than routine needle drainage alone.",
    medicationSafety: "Avoid aggressive positive-pressure ventilation or diuresis before drainage when preload dependence is critical because both can precipitate collapse. Anticoagulation reversal and correction of bleeding risk are balanced against the need for lifesaving drainage.",
    redFlags: "Shock, PEA physiology, rapidly enlarging effusion, post-procedural/traumatic hemopericardium or echocardiographic tamponade with deterioration requires immediate intervention.",
    examTraps: "Do not require Beck triad or electrical alternans and do not call every pericardial effusion tamponade—tamponade is hemodynamic physiology.",
    sourceKeys: ["ESC_PERICARDIAL_CURRENT", "AHA_TAMPONADE_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
