import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch30 = [
  {
    slug: "cerebral-edema-pathophysiology",
    title: "Cerebral Edema: Cytotoxic, Vasogenic & Interstitial Mechanisms",
    slugAliases: ["neuro-patho-cerebral-edema-np"],
    bodySystem: "Neurological",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Cytotoxic edema is intracellular swelling from energy failure, vasogenic edema is extracellular fluid leakage after BBB disruption, and interstitial edema reflects CSF transudation from hydrocephalus. The mechanism determines which therapies help and which can harm.",
    diagnostics: "Noncontrast CT identifies mass effect, hydrocephalus and hemorrhage; MRI diffusion helps distinguish cytotoxic from vasogenic patterns. In critically ill patients, combine imaging with serial neurologic examination, ICP data when indicated, sodium/osmolality and hemodynamics.",
    priorities: "Protect airway and cerebral perfusion, elevate the head with neutral venous drainage, treat fever/seizure, use hyperosmolar therapy for acute intracranial hypertension and obtain CSF diversion or decompression when the mechanism requires it.",
    medicationSafety: "Dexamethasone is useful for selected tumor-associated vasogenic edema but not routine ischemic-stroke cytotoxic edema. Mannitol can worsen hypovolemia/AKI; hypertonic saline can cause major sodium/volume shifts and requires close monitoring.",
    redFlags: "Falling consciousness, unilateral fixed pupil, posturing, refractory ICP, hydrocephalus with deterioration or herniation physiology requires immediate neurocritical/neurosurgical intervention.",
    examTraps: "Do not treat all cerebral edema with steroids. Hyperventilation is a temporary rescue for impending herniation, not sustained routine ICP management because cerebral vasoconstriction can worsen ischemia.",
    sourceKeys: ["BTF_SEVERE_TBI_CURRENT", "AHA_STROKE_CURRENT"],
  },
  {
    slug: "insulin-resistance-metabolic-syndrome",
    title: "Insulin Resistance: Molecular Mechanisms & Metabolic Syndrome",
    slugAliases: ["endo-patho-insulin-resistance-np"],
    bodySystem: "Endocrine",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "WHNP", "PNP"],
    recognize: "Visceral adiposity, acanthosis nigricans, hypertriglyceridemia, low HDL, hypertension, prediabetes, MASLD and PCOS often cluster through insulin resistance. Hyperinsulinemia can compensate for years before glucose crosses a diabetes threshold.",
    diagnostics: "Use validated clinical metabolic measures—A1C or fasting/OGTT glucose, lipids, BP, weight/waist and liver/kidney risk—rather than routine fasting insulin or HOMA-IR, which are not standard diagnostic tests for individual clinical care.",
    priorities: "Reduce cardiometabolic risk with sustainable nutrition, physical activity, sleep, weight management and treatment of BP/lipids/glucose; use metformin in selected high-risk prediabetes and GLP-1/SGLT2-based therapy when obesity, diabetes, CKD or ASCVD indications support them.",
    medicationSafety: "Metformin requires renal-function review and can contribute to B12 deficiency; GLP-1-based drugs have GI, gallbladder and pregnancy considerations; SGLT2 inhibitors can cause genital infections and euglycemic ketoacidosis in susceptible settings.",
    redFlags: "Symptomatic severe hyperglycemia, DKA/HHS, acute pancreatitis, major liver decompensation or cardiovascular ischemic symptoms requires urgent disease-specific care.",
    examTraps: "Do not diagnose insulin resistance from fasting insulin cutoffs or call acanthosis 'pathognomonic.' Metabolic syndrome identifies clustered risk but does not replace direct treatment of each cardiovascular risk factor.",
    sourceKeys: ["ADA_2026", "AHA_METABOLIC_CURRENT"],
  },
  {
    slug: "thyroid-autoimmunity-pathophysiology",
    title: "Thyroid Autoimmunity: Hashimoto & Graves Disease Mechanisms",
    titleAliases: ["Thyroid Autoimmunity: Hashimoto's & Graves' Disease Mechanisms"],
    slugAliases: ["endo-patho-thyroid-autoimmunity-np"],
    bodySystem: "Endocrine",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "WHNP"],
    recognize: "Hashimoto thyroiditis reflects immune-mediated thyroid destruction and commonly causes hypothyroidism; Graves disease results from stimulatory TSH-receptor antibodies causing hyperthyroidism and can produce orbitopathy. Postpartum and other autoimmune clustering are common contexts.",
    diagnostics: "Interpret TSH and free T4 first, then use anti-TPO for autoimmune hypothyroid context and TSH-receptor antibodies when Graves diagnosis is uncertain or pregnancy risk makes antibody status relevant. Radioiodine uptake differentiates active hormone synthesis from thyroiditis when appropriate and not pregnant.",
    priorities: "Replace hormone with levothyroxine for overt hypothyroidism and treat Graves with antithyroid medication, radioactive iodine or surgery according to pregnancy, severity, orbitopathy, goiter and patient preference; involve endocrinology for complex disease.",
    medicationSafety: "Methimazole can cause agranulocytosis and liver injury; PTU is generally reserved for selected first-trimester pregnancy or thyroid storm because of hepatotoxicity risk. Levothyroxine absorption is affected by calcium/iron and overtreatment increases AF/bone risk.",
    redFlags: "Thyroid storm, myxedema coma, compressive goiter/stridor, vision-threatening Graves orbitopathy or antithyroid-drug fever/pharyngitis with agranulocytosis concern requires urgent care.",
    examTraps: "Positive anti-TPO antibodies do not by themselves require thyroid hormone when the patient is euthyroid. Do not use radioactive iodine during pregnancy or lactation.",
    sourceKeys: ["ATA_HYPERTHYROID_CURRENT", "ATA_HYPOTHYROID_CURRENT"],
  },
  {
    slug: "adrenal-insufficiency-pathophysiology",
    title: "Adrenal Insufficiency: Primary, Secondary & Adrenal Crisis Pathways",
    slugAliases: ["endo-patho-adrenal-axis-np"],
    bodySystem: "Endocrine",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Primary adrenal insufficiency causes cortisol and often aldosterone deficiency with high ACTH, hyperpigmentation, salt wasting and hyperkalemia; central adrenal insufficiency lowers ACTH/cortisol while mineralocorticoid function is usually preserved.",
    diagnostics: "Use morning cortisol as an initial screen when appropriate, confirm with ACTH/cosyntropin testing, and measure ACTH to localize primary versus central disease. Electrolytes, renin/aldosterone, autoimmune testing and pituitary/adrenal imaging are selected by phenotype.",
    priorities: "Replace glucocorticoid physiologically, add fludrocortisone for primary mineralocorticoid deficiency, teach sick-day/emergency injection rules and give immediate IV hydrocortisone plus isotonic fluid/dextrose for suspected adrenal crisis without waiting for confirmation.",
    medicationSafety: "Chronic exogenous glucocorticoids suppress the HPA axis and may require tapering after significant exposure; replacement should avoid chronic overexposure. Correct significant cortisol deficiency before starting thyroid hormone when central hypopituitarism is possible.",
    redFlags: "Refractory hypotension, severe vomiting/dehydration, hypoglycemia, hyperkalemia, altered mental status or known adrenal insufficiency with inability to keep down steroids requires emergency stress-dose treatment.",
    examTraps: "Primary and secondary adrenal insufficiency do not share the same potassium/ACTH pattern. Do not delay hydrocortisone for a cosyntropin test when adrenal crisis is clinically suspected.",
    sourceKeys: ["ENDOCRINE_ADRENAL_INSUFFICIENCY_CURRENT"],
  },
  {
    slug: "gfr-autoregulation-pathophysiology",
    title: "GFR Autoregulation: Afferent/Efferent Arteriolar Dynamics",
    slugAliases: ["renal-patho-gfr-autoregulation-np"],
    bodySystem: "Renal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "GFR depends on renal perfusion, afferent/efferent arteriolar tone and glomerular pressure. Prostaglandins help preserve afferent flow during stress, while angiotensin II supports efferent tone; volume depletion, NSAIDs and RAAS blockade can therefore interact to reduce filtration.",
    diagnostics: "Trend creatinine/eGFR and urine output in clinical context, review volume status and medications, and use urinalysis/microscopy and imaging to distinguish hemodynamic AKI from intrinsic or obstructive disease. FENa/FEUrea are adjuncts with important limitations.",
    priorities: "Restore effective circulating volume when depleted, remove avoidable nephrotoxins, treat shock/obstruction and use ACEi/ARB when their long-term renal/cardiovascular indication outweighs short-term hemodynamic risk with monitoring.",
    medicationSafety: "The combination of RAAS blocker, diuretic and NSAID increases hemodynamic AKI risk. A modest creatinine rise after ACEi/ARB may be acceptable, but a large rise requires assessment for volume depletion, bilateral renal artery disease or other pathology.",
    redFlags: "Anuria, severe hyperkalemia, rapidly rising creatinine, flash pulmonary edema, shock or suspected bilateral obstruction requires urgent evaluation.",
    examTraps: "Do not use one FENa cutoff as a definitive etiology test, especially with CKD, diuretics, contrast or sepsis. NSAID-related AKI is not limited to chronic high-dose use in susceptible patients.",
    sourceKeys: ["KDIGO_AKI_CURRENT", "KDIGO_CKD_2024"],
  },
  {
    slug: "proteinuria-pathophysiology",
    title: "Proteinuria: Glomerular vs Tubular Mechanisms & Clinical Significance",
    slugAliases: ["renal-patho-proteinuria-np"],
    bodySystem: "Renal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP"],
    recognize: "Proteinuria can result from glomerular barrier leak, impaired tubular reabsorption or overflow of filtered proteins such as monoclonal light chains. Albumin-predominant persistent proteinuria is both a kidney-disease marker and an independent cardiovascular-risk signal.",
    diagnostics: "Screen/quantify with spot urine albumin-to-creatinine ratio for common CKD risk and confirm persistence when appropriate. Use urine protein electrophoresis/free light chains for suspected overflow disease and urine sediment/serologies/biopsy when glomerulonephritis is suspected.",
    priorities: "Treat the cause and reduce albuminuria with BP control, ACEi/ARB when indicated and SGLT2 therapy in eligible CKD; refer nephrotic-range, active-sediment, rapidly progressive or unexplained substantial proteinuria to nephrology.",
    medicationSafety: "RAAS blockade and SGLT2 inhibitors require kidney, potassium, volume and sick-day monitoring. Do not combine ACEi and ARB for extra proteinuria reduction because adverse renal/hyperkalemia risk outweighs benefit.",
    redFlags: "Nephrotic syndrome with thrombosis/infection, rapidly rising creatinine, RBC casts, pulmonary-renal syndrome, severe edema or profound hypoalbuminemia requires urgent specialty evaluation.",
    examTraps: "A routine dipstick detects albumin better than light chains, so a negative dipstick does not exclude myeloma proteinuria. Transient exercise/fever proteinuria should be confirmed before labeling chronic kidney disease.",
    sourceKeys: ["KDIGO_CKD_2024", "KDIGO_GLOMERULAR_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
