import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch22 = [
  {
    slug: "myasthenia-gravis",
    title: "Myasthenia Gravis",
    bodySystem: "Neurological",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Fluctuating fatigable ocular, bulbar, neck or proximal weakness that worsens with use and improves with rest suggests myasthenia gravis. Sensory loss and abnormal reflexes point toward another diagnosis.",
    diagnostics: "Test acetylcholine-receptor antibodies and, when negative with ongoing suspicion, MuSK/other antibodies plus electrodiagnostic studies. Chest imaging evaluates thymoma. Measure respiratory strength during significant bulbar or generalized weakness.",
    priorities: "Use pyridostigmine for symptomatic treatment and immunotherapy for appropriate generalized disease; thymectomy is indicated in thymoma and selected AChR-positive patients. Myasthenic crisis needs ICU airway/ventilation support plus IVIG or plasma exchange.",
    medicationSafety: "Aminoglycosides, fluoroquinolones, magnesium, beta blockers and several other drugs can worsen neuromuscular transmission. Excess cholinesterase inhibitor can cause muscarinic toxicity and should not be escalated blindly during respiratory decline.",
    redFlags: "Dyspnea, weak cough, inability to handle secretions, rapidly declining vital capacity, aspiration or severe bulbar weakness requires emergency respiratory monitoring and neurology care.",
    examTraps: "Normal pupils are expected; pupillary involvement suggests botulism or another disorder. Do not rely on pulse oximetry alone because ventilation can fail before oxygen saturation drops.",
    sourceKeys: ["AAN_MG_CURRENT", "MGFA_CURRENT"],
  },
  {
    slug: "guillain-barre-syndrome",
    title: "Guillain-Barré Syndrome",
    bodySystem: "Neurological",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Progressive symmetric weakness with reduced or absent reflexes, often after infection, suggests GBS. Paresthesias, facial weakness, autonomic instability and pain are common; bowel/bladder level or marked asymmetry suggests spinal cord disease instead.",
    diagnostics: "Use serial respiratory measurements, ECG/autonomic monitoring, lumbar puncture showing albuminocytologic dissociation after the early phase, and nerve-conduction studies. Image the spine when a compressive or inflammatory cord process remains possible.",
    priorities: "Admit clinically significant progressive disease, monitor respiratory/autonomic function and treat with IVIG or plasma exchange. Provide DVT prevention, pain control, rehabilitation and pressure-injury prevention.",
    medicationSafety: "Corticosteroids do not improve typical GBS outcomes. Sedatives and opioids can mask respiratory decline, and autonomic instability makes aggressive antihypertensive treatment hazardous.",
    redFlags: "Rapidly ascending weakness, bulbar dysfunction, falling vital capacity, arrhythmia, labile BP or inability to ambulate requires urgent inpatient/ICU evaluation.",
    examTraps: "CSF protein can be normal early, so a normal first lumbar puncture does not exclude GBS. Sensory symptoms can occur despite the primarily motor syndrome.",
    sourceKeys: ["AAN_GBS_CURRENT"],
  },
  {
    slug: "trigeminal-neuralgia",
    title: "Trigeminal Neuralgia",
    bodySystem: "Neurological",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "Brief recurrent unilateral electric-shock facial pain triggered by touch, chewing, talking or brushing teeth in a trigeminal distribution suggests trigeminal neuralgia. Constant numb painful neuropathy is a different phenotype.",
    diagnostics: "Perform a complete cranial nerve exam and obtain MRI in younger patients, atypical bilateral pain, sensory deficit or other neurologic findings to exclude MS, tumor or secondary compression.",
    priorities: "Carbamazepine or oxcarbazepine are first-line for classic disease when appropriate. Refer refractory, intolerant or structurally secondary cases to neurology/neurosurgery for procedural options.",
    medicationSafety: "Carbamazepine can cause hyponatremia, marrow/hepatic toxicity, severe cutaneous reactions and interactions; HLA testing is indicated in selected ancestry groups before treatment.",
    redFlags: "Objective sensory loss, bilateral symptoms, hearing change, multiple cranial neuropathies, progressive course or systemic cancer/infection signs requires evaluation for secondary disease.",
    examTraps: "Do not perform repeated dental procedures for classic neuralgic pain without considering trigeminal neuralgia. Continuous aching facial pain alone is not the classic diagnostic pattern.",
    sourceKeys: ["AAN_TRIGEMINAL_CURRENT"],
  },
  {
    slug: "meningitis-encephalitis",
    title: "Meningitis & Encephalitis",
    bodySystem: "Neurological",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PNP", "ENP"],
    recognize: "Fever, severe headache, neck stiffness, photophobia, altered mental status, seizure, petechiae or focal neurologic findings can signal meningitis or encephalitis. Classic triads are insensitive and immunocompromised patients can present subtly.",
    diagnostics: "Obtain blood cultures and lumbar puncture promptly when safe; CT before LP is reserved for defined risk features. CSF cell count, glucose, protein, Gram stain/culture and PCR testing should be tailored to bacterial, viral, fungal or other risk.",
    priorities: "Start empiric antibiotics immediately when bacterial meningitis is suspected and do not delay for imaging or LP; add acyclovir when HSV encephalitis is possible and dexamethasone in appropriate bacterial pathways.",
    medicationSafety: "Empiric regimens vary by age, pregnancy, immune status and healthcare exposure; acyclovir and vancomycin require renal dosing/monitoring. Droplet isolation is required for selected meningococcal disease until adequately treated.",
    redFlags: "Shock, rapidly declining consciousness, status epilepticus, focal deficit, papilledema/herniation concern or purpuric rash requires immediate emergency and critical-care management.",
    examTraps: "Absence of neck stiffness does not rule out meningitis. Antibiotics should not be postponed simply to preserve CSF culture yield in an unstable high-suspicion patient.",
    sourceKeys: ["IDSA_MENINGITIS_CURRENT", "IDSA_ENCEPHALITIS_CURRENT"],
  },
  {
    slug: "alzheimer-major-neurocognitive-disorder",
    title: "Alzheimer Disease & Major Neurocognitive Disorder",
    bodySystem: "Neurological",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PMHNP"],
    recognize: "Progressive decline from prior baseline in memory, language, visuospatial or executive function that interferes with independence suggests major neurocognitive disorder. Establish timeline and separate chronic decline from superimposed delirium, depression or medication effects.",
    diagnostics: "Use cognitive testing plus collateral functional history, medication review, neurologic exam and targeted CBC/CMP/TSH/B12 or imaging to exclude reversible contributors. Biomarker testing is increasingly available but is not required for every primary-care diagnosis.",
    priorities: "Address safety, driving, finances, caregiver support, hearing/vision, vascular risk and advance planning. Cholinesterase inhibitors and memantine offer modest symptomatic benefit in selected stages; disease-modifying anti-amyloid therapy requires specialist biomarker and MRI-risk assessment.",
    medicationSafety: "Cholinesterase inhibitors can cause bradycardia, syncope and GI effects; anticholinergic medications worsen cognition. Anti-amyloid agents carry ARIA risk and require specific MRI/anticoagulation considerations.",
    redFlags: "Rapid decline over weeks, focal deficit, seizure, fever, severe gait/urinary change, new psychosis with safety risk or acute fluctuating attention requires evaluation for alternate or superimposed disease.",
    examTraps: "A low screening score is not the diagnosis without functional decline and context. Do not assume every older adult with memory complaint has Alzheimer disease.",
    sourceKeys: ["AAN_DEMENTIA_CURRENT", "ALZ_ASSOC_CURRENT"],
  },
  {
    slug: "tremor-evaluation",
    title: "Tremor Evaluation",
    bodySystem: "Neurological",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PMHNP"],
    recognize: "Classify tremor by rest versus action/postural, frequency, symmetry, onset and associated neurologic signs. Essential tremor is usually bilateral action tremor; Parkinson tremor is classically rest-predominant with bradykinesia/rigidity.",
    diagnostics: "Review caffeine, stimulants, valproate, lithium, bronchodilators, thyroid disease, alcohol withdrawal and family history. TSH and metabolic testing are targeted; neuroimaging is reserved for abrupt, focal or otherwise atypical tremor.",
    priorities: "Treat the cause when secondary. Propranolol or primidone are common essential-tremor therapies when function is impaired; severe refractory cases can be referred for botulinum toxin, focused ultrasound or DBS evaluation.",
    medicationSafety: "Propranolol can worsen asthma, bradycardia and hypotension; primidone sedates and requires gradual titration. Avoid using benzodiazepines as routine long-term tremor treatment.",
    redFlags: "Abrupt onset with focal neurologic deficit, severe ataxia, toxic/metabolic symptoms, withdrawal or rapidly progressive movement disorder requires urgent evaluation.",
    examTraps: "Do not diagnose Parkinson disease from tremor alone. Improvement with alcohol is not a diagnostic test and should not be used as treatment advice.",
    sourceKeys: ["AAN_ESSENTIAL_TREMOR_CURRENT"],
  },
  {
    slug: "restless-legs-syndrome",
    title: "Restless Legs Syndrome",
    bodySystem: "Neurological",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PMHNP", "WHNP"],
    recognize: "An urge to move the legs with uncomfortable sensations that begins/worsens at rest, improves with movement and is worse in the evening/night is classic RLS. Cramps, neuropathy, akathisia and vascular disease can mimic it.",
    diagnostics: "Check ferritin and iron studies, pregnancy, kidney disease and culprit medications such as some antihistamines, dopamine blockers and antidepressants. Polysomnography is not required for a typical diagnosis.",
    priorities: "Correct iron deficiency when below guideline thresholds, reduce exacerbating substances/medications, improve sleep and use alpha-2-delta ligands or other guideline therapy when symptoms are clinically significant.",
    medicationSafety: "Dopamine agonists can cause augmentation and impulse-control disorders and are no longer the default chronic first choice for many patients. Gabapentinoids can sedate and require renal dosing.",
    redFlags: "New unilateral swelling/pain, objective weakness, severe neuropathy or symptoms caused by medication toxicity requires evaluation for alternate disease.",
    examTraps: "Normal hemoglobin does not exclude iron deficiency contributing to RLS. The key is relief with movement and circadian pattern, not just nighttime leg discomfort.",
    sourceKeys: ["AASM_RLS_CURRENT"],
  },
  {
    slug: "entrapment-neuropathies",
    title: "Carpal Tunnel & Entrapment Neuropathies",
    bodySystem: "Neurological",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "WHNP"],
    recognize: "Median-distribution nocturnal hand numbness, shaking the hand for relief, thenar weakness or provocative symptoms suggests carpal tunnel syndrome. Ulnar and radial entrapments follow different distributions and motor findings.",
    diagnostics: "Diagnosis is often clinical; electrodiagnostic studies are useful for atypical cases, severe weakness, unclear localization or before surgery. Review diabetes, hypothyroidism, pregnancy, inflammatory disease and repetitive compression.",
    priorities: "Use neutral-position night splinting and activity modification initially for mild disease, consider corticosteroid injection for selected patients and refer persistent, severe or motor-deficit cases for decompression.",
    medicationSafety: "Repeated corticosteroid injections have local tissue and glucose effects; oral steroids are not preferred chronic treatment. Neuropathic-pain drugs may reduce symptoms but do not correct mechanical nerve compression.",
    redFlags: "Progressive motor weakness, marked atrophy, acute traumatic nerve injury or signs of cervical myelopathy requires expedited neurologic/hand evaluation.",
    examTraps: "Phalen and Tinel signs are not sufficiently accurate to rule in/out disease alone. Whole-arm numbness or neck-associated symptoms should prompt cervical/radicular evaluation.",
    sourceKeys: ["AAOS_CARPAL_TUNNEL_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
