import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch23 = [
  {
    slug: "systemic-lupus-erythematosus",
    title: "Systemic Lupus Erythematosus",
    bodySystem: "Rheumatology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "WHNP"],
    recognize: "Photosensitive rash, oral ulcers, inflammatory arthritis, serositis, cytopenias, nephritis, neurologic disease or thrombosis in a compatible patient suggests SLE, but no single symptom or ANA result makes the diagnosis.",
    diagnostics: "Use ANA as a sensitive entry test, then disease-specific antibodies, complements, CBC, creatinine and urinalysis/protein quantification according to suspected organ involvement. Persistent proteinuria or active sediment may require kidney biopsy.",
    priorities: "Hydroxychloroquine is foundational for most patients unless contraindicated; minimize chronic glucocorticoid exposure and use organ-directed immunosuppression with rheumatology. Address vaccination, sun protection, cardiovascular risk, fertility and pregnancy planning.",
    medicationSafety: "Hydroxychloroquine requires weight-based dosing and retinal screening; immunosuppressants carry infection, pregnancy, marrow, liver and malignancy risks. Mycophenolate and methotrexate are teratogenic and require pregnancy planning.",
    redFlags: "Rapidly progressive nephritis, pulmonary hemorrhage, CNS lupus, severe cytopenia, myocarditis, catastrophic antiphospholipid syndrome or serious infection requires urgent specialty/inpatient care.",
    examTraps: "A positive ANA is common and does not diagnose lupus. Do not assume every fever in an immunosuppressed lupus patient is a flare before excluding infection.",
    sourceKeys: ["ACR_SLE_2025"],
  },
  {
    slug: "giant-cell-arteritis-polymyalgia-rheumatica",
    title: "Giant Cell Arteritis & Polymyalgia Rheumatica",
    bodySystem: "Rheumatology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "ENP"],
    recognize: "New headache, scalp tenderness, jaw claudication, visual symptoms or constitutional illness in an adult over 50 suggests GCA; bilateral shoulder/hip girdle aching and morning stiffness with elevated inflammation suggests PMR.",
    diagnostics: "Check ESR/CRP, CBC and platelets, then use temporal-artery ultrasound/biopsy or vascular imaging according to local expertise. Normal inflammatory markers reduce but do not completely eliminate GCA probability when classic ischemic symptoms exist.",
    priorities: "Start high-dose glucocorticoid immediately when GCA with visual/ischemic risk is strongly suspected—do not wait for biopsy. PMR uses lower-dose steroid therapy with response monitoring and reassessment for mimics.",
    medicationSafety: "Long-term steroid exposure requires bone, glucose, BP, infection and adrenal-suppression prevention. Tocilizumab can reduce steroid exposure in selected GCA but requires infection/liver/lipid monitoring.",
    redFlags: "Transient or permanent vision loss, diplopia, stroke/TIA symptoms, aortic syndrome symptoms or jaw/tongue ischemia requires immediate emergency ophthalmologic/rheumatologic treatment.",
    examTraps: "PMR does not cause true muscle weakness despite painful movement. Do not delay steroid therapy for suspected vision-threatening GCA until biopsy results return.",
    sourceKeys: ["ACR_VASCULITIS_GCA_CURRENT", "EULAR_PMR_CURRENT"],
  },
  {
    slug: "axial-spondyloarthritis",
    title: "Axial Spondyloarthritis",
    bodySystem: "Rheumatology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "Back pain beginning before age 45 with prolonged morning stiffness, improvement with exercise, night pain, alternating buttock pain, uveitis, psoriasis or IBD suggests axial spondyloarthritis rather than mechanical back pain.",
    diagnostics: "Assess inflammatory features, CRP, HLA-B27 in selected patients and sacroiliac imaging. Plain films can be normal early; MRI can detect active sacroiliitis when radiographs are nondiagnostic and suspicion remains high.",
    priorities: "Exercise/physical therapy and NSAIDs are first-line for many patients, with rheumatology-directed biologic or targeted therapy for persistent active disease. Screen and treat uveitis, psoriasis, IBD, osteoporosis and cardiovascular risk.",
    medicationSafety: "NSAIDs require renal/GI/CV review; biologics require TB/hepatitis screening and vaccination planning. Avoid chronic systemic glucocorticoids as routine axial disease therapy.",
    redFlags: "Acute painful red photophobic eye, severe neurologic deficit, spinal fracture after minor trauma in an ankylosed spine or infection on immunosuppression requires urgent evaluation.",
    examTraps: "Negative HLA-B27 does not exclude disease. Do not require radiographic sacroiliitis before recognizing nonradiographic axial spondyloarthritis.",
    sourceKeys: ["ACR_SPA_CURRENT"],
  },
  {
    slug: "psoriatic-arthritis",
    title: "Psoriatic Arthritis",
    bodySystem: "Rheumatology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "Inflammatory joint pain with psoriasis, nail pitting/onycholysis, dactylitis, enthesitis or axial symptoms suggests psoriatic arthritis; skin disease may be subtle or appear after joint symptoms.",
    diagnostics: "Diagnosis is clinical with targeted inflammatory markers and imaging; RF/anti-CCP can be positive in a minority and do not exclude PsA. Examine nails, scalp, gluteal cleft and entheses when psoriasis history is unclear.",
    priorities: "Refer early for disease-modifying therapy matched to peripheral, axial, enthesitis and skin phenotype. Treat-to-target aims to prevent structural damage while coordinating dermatologic and cardiometabolic care.",
    medicationSafety: "Methotrexate and biologic/targeted agents have pregnancy, liver, marrow and infection risks; screen TB/hepatitis and update vaccines before selected immunosuppression.",
    redFlags: "Hot single joint, severe ocular inflammation, rapidly destructive arthritis or serious infection on immunosuppression requires urgent evaluation.",
    examTraps: "Do not call dactylitis gout solely because a toe is swollen. Normal CRP does not exclude active psoriatic arthritis.",
    sourceKeys: ["ACR_NPF_PSA_CURRENT"],
  },
  {
    slug: "septic-arthritis",
    title: "Septic Arthritis",
    bodySystem: "Rheumatology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PNP", "ENP"],
    recognize: "An acutely hot swollen painful joint with severe limited motion, fever, bacteremia risk, prosthetic joint, injection drug use, immunosuppression or recent procedure is septic arthritis until excluded.",
    diagnostics: "Urgent arthrocentesis for cell count/differential, Gram stain, culture and crystals is central; obtain blood cultures when systemic infection is possible. Serum WBC/ESR/CRP and imaging cannot rule it out alone.",
    priorities: "Drain the joint and start empiric IV antibiotics after cultures when feasible, then tailor to organism and joint/prosthesis context. Orthopedic consultation is urgent for hip, prosthetic or complicated infection.",
    medicationSafety: "Antibiotics require renal dosing and MRSA/gram-negative risk assessment; do not let finding urate crystals stop treatment when bacterial infection remains possible because both can coexist.",
    redFlags: "Sepsis, hip involvement, prosthetic joint infection, rapidly progressive destruction, immunocompromised host or inability to bear weight with systemic illness requires emergency inpatient care.",
    examTraps: "A high synovial WBC supports but does not perfectly define septic arthritis. Do not inject corticosteroid into a joint until infection has been reasonably excluded.",
    sourceKeys: ["IDSA_SEPTIC_ARTHRITIS_CURRENT"],
  },
  {
    slug: "fibromyalgia",
    title: "Fibromyalgia",
    bodySystem: "Rheumatology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PMHNP", "WHNP"],
    recognize: "Chronic widespread pain with fatigue, nonrestorative sleep, cognitive symptoms, headache or IBS-type symptoms suggests fibromyalgia when inflammatory, endocrine, neurologic and medication causes do not better explain the pattern.",
    diagnostics: "Use clinical symptom criteria and focused testing guided by history; routine ANA, RF, extensive imaging and repeated inflammatory panels are not needed without signs of systemic inflammatory disease.",
    priorities: "Education, graded aerobic/strength exercise, sleep treatment, CBT or other behavioral strategies and selected neuromodulating medications are core. Address depression/anxiety and function rather than chasing zero pain.",
    medicationSafety: "Duloxetine, milnacipran and pregabalin can help selected patients but cause nausea, BP, sedation, weight or interaction effects. Opioids are not recommended chronic fibromyalgia treatment.",
    redFlags: "Objective synovitis, progressive weakness, neurologic deficit, fever, weight loss, inflammatory rash or markedly abnormal labs requires evaluation for another diagnosis.",
    examTraps: "Fibromyalgia is not an inflammatory autoimmune disease and does not cause joint destruction. A positive low-titer ANA does not convert the diagnosis to lupus.",
    sourceKeys: ["ACR_FIBROMYALGIA_CURRENT"],
  },
  {
    slug: "osteomyelitis",
    title: "Osteomyelitis",
    bodySystem: "Musculoskeletal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PNP", "ENP"],
    recognize: "Persistent focal bone pain, nonhealing ulcer with exposed/probe-to-bone findings, fever, bacteremia or post-surgical/hardware infection can indicate osteomyelitis. Diabetic foot disease is a common adult presentation.",
    diagnostics: "Use ESR/CRP trends, blood cultures when systemic infection exists, plain radiographs initially and MRI for sensitive anatomic definition. Bone biopsy/culture is preferred for microbiologic diagnosis when feasible before prolonged antibiotics.",
    priorities: "Provide source control/debridement when needed, culture-directed antibiotics for an appropriate duration, offloading/vascular optimization in diabetic feet and orthopedic/infectious-disease collaboration for hardware or chronic infection.",
    medicationSafety: "Long antibiotic courses require renal, hepatic, marrow, C. difficile and line-complication monitoring. Avoid treating a superficial wound swab as definitive bone-culture evidence.",
    redFlags: "Sepsis, epidural extension, spinal cord compression, necrotizing infection, critical limb ischemia or rapidly progressive destruction requires urgent inpatient/surgical care.",
    examTraps: "A normal early x-ray does not exclude osteomyelitis. Diabetic neuropathy can make severe foot infection relatively painless.",
    sourceKeys: ["IDSA_OSTEOMYELITIS_CURRENT", "IWGDF_DFI_CURRENT"],
  },
  {
    slug: "systemic-sclerosis-raynaud",
    title: "Systemic Sclerosis & Raynaud Phenomenon",
    bodySystem: "Rheumatology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "WHNP"],
    recognize: "Triphasic color change with cold/stress can be primary Raynaud, while digital ulcers, puffy/sclerotic fingers, telangiectasia, reflux, ILD or pulmonary hypertension suggests systemic sclerosis or secondary Raynaud.",
    diagnostics: "Assess nailfold capillaries, ANA and disease-specific antibodies when secondary features exist, plus PFT/HRCT, echocardiographic PH screening, renal/BP monitoring and GI assessment in established systemic sclerosis.",
    priorities: "Avoid cold/nicotine/vasoconstrictors, use calcium-channel blockers for significant Raynaud, and refer systemic sclerosis for organ-specific immunosuppressive, vasodilator and surveillance strategies.",
    medicationSafety: "High-dose glucocorticoids can increase scleroderma renal-crisis risk. PDE-5 inhibitors and other vasodilators can cause hypotension; ACE inhibitors are treatment for renal crisis rather than prophylactic routine therapy.",
    redFlags: "Abrupt severe hypertension with AKI, digital ischemia/gangrene, rapidly progressive dyspnea, pulmonary hypertension or severe GI dysmotility/malnutrition requires urgent specialty care.",
    examTraps: "Primary Raynaud should not cause tissue necrosis. Do not use beta blockers casually in severe vasospastic Raynaud when alternatives exist.",
    sourceKeys: ["ACR_SYSTEMIC_SCLEROSIS_CURRENT", "EULAR_SSC_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
