import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch19 = [
  {
    slug: "appendicitis",
    title: "Appendicitis",
    bodySystem: "Gastrointestinal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGACNP", "PNP", "WHNP", "ENP"],
    recognize: "Periumbilical pain migrating to the RLQ, anorexia, nausea, focal tenderness, guarding, or fever suggests appendicitis, but pregnancy, ovarian/testicular pathology, gastroenteritis, IBD, UTI and mesenteric adenitis can mimic it.",
    diagnostics: "Use history/exam plus CBC, urinalysis and pregnancy testing when relevant. Ultrasound is preferred initially in many children and pregnancies; CT is highly accurate in adults when imaging is needed. Clinical scores support but do not replace judgment.",
    priorities: "Keep NPO, provide analgesia/antiemetics, give IV fluids and antibiotics when appendicitis is confirmed or strongly suspected, and obtain surgical consultation. Selected uncomplicated cases may be managed nonoperatively under defined protocols.",
    medicationSafety: "Analgesia does not prevent diagnosis and should not be withheld. Antibiotic choices should cover enteric gram-negative and anaerobic organisms and be allergy/renal adjusted.",
    redFlags: "Diffuse peritonitis, shock, abscess, perforation, severe sepsis, or worsening pain after a transient improvement requires urgent surgical management.",
    examTraps: "Do not exclude appendicitis because diarrhea is present or the WBC is normal. Children, older adults and pregnant patients can have atypical pain location or muted findings.",
    sourceKeys: ["SAGES_APPENDICITIS_CURRENT", "ACR_RLQ_CURRENT"],
  },
  {
    slug: "bowel-obstruction",
    title: "Small & Large Bowel Obstruction",
    bodySystem: "Gastrointestinal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Crampy abdominal pain, vomiting, distention and obstipation suggest obstruction; prior surgery, hernia, malignancy, volvulus and IBD raise risk. Continuous severe pain, fever or toxicity suggests ischemia or perforation.",
    diagnostics: "Use CT abdomen/pelvis in most adults to define transition point, cause and signs of ischemia/closed-loop obstruction. Check CBC, electrolytes, lactate and renal function, but normal lactate does not safely exclude early strangulation.",
    priorities: "NPO, IV fluids, electrolyte correction, NG decompression when indicated, analgesia and early surgical consultation. Complete/closed-loop obstruction, peritonitis, strangulation or perforation requires operative management.",
    medicationSafety: "Avoid laxatives and prokinetics when mechanical obstruction is suspected. Opioids may be necessary but can worsen ileus, so reassess physiology rather than escalating blindly.",
    redFlags: "Peritonitis, severe continuous pain, fever, tachycardia, acidosis, rising lactate, pneumatosis/free air, closed-loop imaging or shock requires emergency surgery-capable care.",
    examTraps: "Passing some stool or flatus does not rule out partial obstruction. Hyperactive bowel sounds are not required and late obstruction may become quiet.",
    sourceKeys: ["EAST_SBO_CURRENT", "ASCRS_OBSTRUCTION_CURRENT"],
  },
  {
    slug: "constipation-adults",
    title: "Chronic Constipation",
    bodySystem: "Gastrointestinal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "Infrequent stool, hard stool, straining, incomplete evacuation, manual maneuvers or blockage sensation suggests constipation; distinguish slow transit, defecatory disorder, medication effect, IBS-C and secondary metabolic or neurologic causes.",
    diagnostics: "Review diet, fluids, activity, medications, alarm symptoms and rectal/pelvic-floor clues. Routine broad labs or colonoscopy are unnecessary without red flags or age-appropriate screening indication; refractory cases may need anorectal testing or transit studies.",
    priorities: "Increase soluble fiber when appropriate, use osmotic laxatives as common first-line pharmacotherapy, address pelvic-floor dysfunction with biofeedback, and escalate to secretagogues/prokinetic agents or GI referral when refractory.",
    medicationSafety: "Magnesium products can accumulate in advanced kidney disease. Chronic stimulant laxative fear is often overstated, but therapy should still be individualized; avoid bulk fiber in severe impaction or obstructive symptoms.",
    redFlags: "Acute severe pain/distention, vomiting, obstipation, GI bleeding, unexplained anemia, weight loss, neurologic deficits, or new severe constipation in an older adult requires further evaluation.",
    examTraps: "Daily bowel movements do not rule out constipation when evacuation is incomplete. Do not repeatedly prescribe stool softener alone for established chronic constipation when more effective agents are needed.",
    sourceKeys: ["AGA_ACG_CONSTIPATION_CURRENT"],
  },
  {
    slug: "chronic-diarrhea",
    title: "Chronic Diarrhea Evaluation",
    bodySystem: "Gastrointestinal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "Diarrhea lasting weeks requires classification as watery, fatty/malabsorptive or inflammatory. Medication effects, infection, celiac disease, microscopic colitis, IBD, bile-acid diarrhea, pancreatic disease and endocrine causes belong in the differential.",
    diagnostics: "Use CBC/CMP, celiac testing, stool inflammatory markers or infection studies selectively based on phenotype and exposure. Colonoscopy with biopsies can be required even with normal-appearing mucosa when microscopic colitis is suspected.",
    priorities: "Correct dehydration and electrolyte loss, stop culprit medications when possible, treat the defined cause and use symptom-directed therapy only after dangerous infection/inflammation is reasonably excluded.",
    medicationSafety: "Avoid antimotility drugs in severe inflammatory or dysenteric illness and suspected toxic megacolon. Metformin, magnesium, PPIs, SSRIs, antibiotics and many other medications can cause or worsen diarrhea.",
    redFlags: "Bloody stool, nocturnal progressive symptoms, fever, severe dehydration, weight loss, anemia, hypoalbuminemia, severe pain or immunocompromise requires expedited evaluation.",
    examTraps: "Do not call chronic diarrhea IBS-D before excluding celiac and inflammatory or medication causes when indicated. Normal colonoscopy without biopsies can miss microscopic colitis.",
    sourceKeys: ["AGA_CHRONIC_DIARRHEA_CURRENT", "ACG_CELIAC_CURRENT"],
  },
  {
    slug: "metabolic-dysfunction-associated-steatotic-liver-disease",
    title: "Metabolic Dysfunction-Associated Steatotic Liver Disease",
    bodySystem: "Gastrointestinal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "Steatosis with obesity, type 2 diabetes, dyslipidemia or metabolic syndrome may represent MASLD; aminotransferases can be normal even with advanced fibrosis.",
    diagnostics: "Exclude significant alcohol and competing liver diseases, then use noninvasive fibrosis risk assessment such as FIB-4 followed by elastography or specialty testing when elevated. Ultrasound can detect steatosis but is insensitive for fibrosis severity.",
    priorities: "Treat cardiometabolic disease aggressively, support sustained weight loss, exercise and diabetes/obesity therapies with liver benefit, vaccinate when appropriate, and refer patients with advanced fibrosis or diagnostic uncertainty.",
    medicationSafety: "Statins are generally safe in stable chronic liver disease and should not be withheld when indicated for ASCVD risk. Weight-loss and diabetes drugs require usual GI, gallbladder, renal and pregnancy precautions.",
    redFlags: "New ascites, encephalopathy, variceal bleeding, jaundice, rapidly falling platelets, or suspected advanced cirrhosis requires hepatology evaluation.",
    examTraps: "Normal ALT does not exclude advanced fibrosis. Do not diagnose MASLD solely from an echogenic liver without reviewing alcohol, medications and other liver disease.",
    sourceKeys: ["AASLD_MASLD_CURRENT"],
  },
  {
    slug: "hepatocellular-carcinoma",
    title: "Hepatocellular Carcinoma Surveillance & Recognition",
    bodySystem: "Oncology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "HCC often arises in cirrhosis or selected chronic HBV patients and may be asymptomatic until advanced; new weight loss, RUQ pain, decompensation or rising AFP can be clues but are not diagnostic.",
    diagnostics: "Use guideline surveillance imaging, commonly ultrasound with or without AFP at defined intervals in eligible high-risk patients. Suspicious lesions require multiphasic CT or MRI; characteristic imaging can diagnose HCC without biopsy in many cirrhotic patients.",
    priorities: "Refer promptly for multidisciplinary staging because curative options include resection, transplantation and ablation in selected early disease; locoregional and systemic therapies depend on stage and liver reserve.",
    medicationSafety: "Systemic and immune therapies require hepatic-function, bleeding, transplant, autoimmune and interaction review. Avoid assuming elevated AFP is cancer without appropriate imaging.",
    redFlags: "Tumor rupture with hemorrhage, acute liver decompensation, portal-vein complications, severe pain or rapidly declining performance status requires urgent specialty management.",
    examTraps: "HCC surveillance is for defined high-risk populations, not every patient with fatty liver. A normal AFP does not exclude HCC.",
    sourceKeys: ["AASLD_HCC_CURRENT"],
  },
  {
    slug: "pancreatic-cancer",
    title: "Pancreatic Cancer Recognition",
    bodySystem: "Oncology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "Painless jaundice, dark urine, pale stools, weight loss, new or worsening diabetes, epigastric/back pain, unexplained pancreatitis or migratory thrombophlebitis should raise concern for pancreatic malignancy.",
    diagnostics: "Use pancreas-protocol CT or MRI and endoscopic ultrasound for diagnosis/staging as appropriate. CA 19-9 is not a screening test and can rise with biliary obstruction; tissue confirmation is usually obtained before systemic therapy.",
    priorities: "Refer quickly to a multidisciplinary pancreatic center to determine resectability, biliary decompression need, chemotherapy and supportive nutrition/pain management. Genetic testing may affect therapy and family counseling.",
    medicationSafety: "Opioid and celiac-plexus strategies may be needed for pain but require bowel and sedation planning. Pancreatic enzyme replacement is indicated for exocrine insufficiency, not just because a pancreatic mass exists.",
    redFlags: "Cholangitis, severe biliary obstruction, gastric outlet obstruction, VTE, severe malnutrition or uncontrolled pain requires urgent supportive/specialty management.",
    examTraps: "Do not use CA 19-9 to screen asymptomatic average-risk adults. New diabetes in an older adult is common and usually not pancreatic cancer, but accompanying weight loss or jaundice changes concern.",
    sourceKeys: ["NCCN_PANCREATIC_CURRENT"],
  },
  {
    slug: "dysphagia-esophageal-disorders",
    title: "Dysphagia & Esophageal Disorders",
    bodySystem: "Gastrointestinal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP"],
    recognize: "Difficulty initiating a swallow with coughing/nasal regurgitation suggests oropharyngeal dysfunction; food sticking after swallowing suggests esophageal disease from stricture, eosinophilic esophagitis, cancer or motility disorder.",
    diagnostics: "Use swallow evaluation for oropharyngeal symptoms and upper endoscopy for most persistent esophageal dysphagia. Barium studies and manometry answer structural or motility questions; obtain biopsies for eosinophilic esophagitis even when mucosa looks near normal if suspicion is high.",
    priorities: "Protect against aspiration, relieve food impaction urgently, treat reflux/eosinophilic inflammation or structural narrowing, and refer progressive or unexplained dysphagia promptly.",
    medicationSafety: "Pills such as bisphosphonates, tetracyclines and potassium can cause esophagitis if taken improperly. Dilation and sedation have perforation/aspiration risks that require appropriate procedural planning.",
    redFlags: "Complete food impaction, inability to handle secretions, aspiration, progressive solid-to-liquid dysphagia, weight loss, anemia or GI bleeding requires urgent or expedited endoscopic evaluation.",
    examTraps: "Do not assume dysphagia is GERD. Achalasia typically affects solids and liquids and may cause regurgitation even when endoscopy is nondiagnostic.",
    sourceKeys: ["ACG_ESOPHAGEAL_PHYSIOLOGY_CURRENT", "ACG_EOE_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
