import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch57 = [
  {
    slug: "mechanical-ventilation-management",
    title: "Mechanical Ventilation: Initial Settings & Lung Protection",
    bodySystem: "Critical Care",
    applicableExams: ["AGACNP", "ENP", "AANP-FNP", "ANCC-FNP"],
    recognize: "Mechanical ventilation supports oxygenation, ventilation and work of breathing while the underlying disease is treated. Interpret the ventilator from the patient's physiology: airway pressure, tidal volume, respiratory rate, PEEP/FiO2, minute ventilation, synchrony and blood gas—not from the mode name alone.",
    diagnostics: "Confirm tube position and obtain ABG/VBG when gas exchange needs clarification; track plateau pressure, driving pressure, static compliance and auto-PEEP when relevant. In ARDS use predicted body weight—not actual body weight—to set lung-protective tidal volume and reassess pressures as compliance changes.",
    priorities: "Use lung-protective ventilation for ARDS, titrate PEEP/FiO2 to oxygenation and hemodynamics, adjust minute ventilation to the acid-base problem and correct dyssynchrony by treating pain, anxiety, flow or trigger mismatch before reflexively deepening sedation. Prone positioning is a key rescue/standard strategy for appropriate moderate-severe ARDS.",
    medicationSafety: "Sedatives and opioids can cause hypotension, delirium and delayed liberation; neuromuscular blockade eliminates clinical seizure/weakness assessment and requires adequate analgesia/sedation. Avoid excessive oxygen exposure and avoid large tidal volumes simply to normalize PaCO2 in stiff lungs.",
    redFlags: "Abrupt desaturation or high pressure requires immediate assessment for DOPE-type problems—displacement, obstruction, pneumothorax and equipment failure—plus severe bronchospasm or mucus plugging. Refractory hypoxemia, severe auto-PEEP shock or rapidly rising plateau pressure requires critical-care escalation.",
    examTraps: "Do not set tidal volume from actual body weight in obesity and do not chase a normal PaCO2 at the expense of lung injury. Peak pressure elevation with stable plateau suggests airway resistance; rising plateau suggests compliance/alveolar pressure problems.",
    sourceKeys: ["ATS_ARDS_CURRENT", "ARDSNET_CURRENT", "SCCM_VENTILATION_CURRENT"],
  },
  {
    slug: "ventilator-liberation-extubation",
    title: "Ventilator Liberation & Extubation Readiness",
    bodySystem: "Critical Care",
    applicableExams: ["AGACNP", "ENP"],
    recognize: "Liberation requires improvement in the cause of respiratory failure, adequate oxygenation/hemodynamics, spontaneous respiratory drive and a realistic airway-protection plan. Passing a spontaneous breathing trial tests ventilatory readiness but does not guarantee extubation success if cough, secretion burden or airway patency is inadequate.",
    diagnostics: "Use daily readiness screening and a spontaneous breathing trial with close assessment of respiratory pattern, gas exchange, distress and hemodynamics. Evaluate cough, mental status, secretion burden and upper-airway edema risk; cuff-leak testing is selective for patients at elevated post-extubation stridor risk rather than a universal pass/fail test.",
    priorities: "Minimize unnecessary sedation, mobilize, perform coordinated awakening/breathing assessments and extubate promptly once ventilation and airway criteria are met. Use preventive post-extubation high-flow oxygen or noninvasive ventilation in selected high-risk patients according to phenotype rather than waiting for overt failure.",
    medicationSafety: "Over-sedation delays weaning and increases delirium/weakness; abrupt withdrawal of chronic sedatives/opioids can also cause agitation and failed trials. Systemic corticosteroid before extubation is reserved for selected patients at high risk for laryngeal edema, timed early enough to have benefit.",
    redFlags: "SBT failure with shock/ischemia, inability to protect airway, copious secretions, rapidly progressive weakness, post-extubation stridor or recurrent hypercapnic/hypoxemic failure requires prompt reassessment and possible reintubation.",
    examTraps: "Do not delay extubation because one traditional index is imperfect when the overall readiness picture is favorable, and do not use noninvasive ventilation to postpone needed reintubation in a deteriorating patient with failed airway protection.",
    sourceKeys: ["ATS_CHEST_VENTILATOR_LIBERATION_CURRENT", "SCCM_ICU_LIBERATION_CURRENT"],
  },
  {
    slug: "icu-analgesia-sedation-delirium",
    title: "ICU Analgesia, Sedation & Delirium",
    bodySystem: "Critical Care",
    applicableExams: ["AGACNP", "ENP", "PMHNP"],
    recognize: "Pain, agitation and delirium overlap but are not interchangeable. ICU delirium is acute fluctuating inattention/cognition and may be hypoactive; agitation can reflect pain, hypoxemia, withdrawal, urinary retention, dyssynchrony or neurologic disease rather than a need for deeper sedation.",
    diagnostics: "Use validated pain scales, a sedation target such as RASS and a delirium tool such as CAM-ICU/ICDSC while investigating reversible causes. Review medication exposure, sleep, infection, metabolic disturbance, hypoxia, withdrawal and new neurologic findings before assigning a psychiatric label.",
    priorities: "Use analgesia-first, goal-directed light sedation when clinically feasible and the ICU liberation bundle: awakening/breathing coordination, delirium prevention/management, early mobility and family engagement. Nonpharmacologic orientation, sleep, sensory aids and mobilization are core delirium interventions.",
    medicationSafety: "Benzodiazepines are generally avoided for routine ICU sedation when alternatives are appropriate because they increase delirium and prolonged ventilation, but remain appropriate for alcohol/benzodiazepine withdrawal and selected seizures. Dexmedetomidine can cause bradycardia/hypotension; propofol can cause hypotension, hypertriglyceridemia and rare infusion syndrome.",
    redFlags: "New focal deficit, seizure, severe hyperthermia/rigidity, profound withdrawal, uncontrolled pain, dangerous self-extubation risk or unexplained depressed consciousness requires urgent cause-specific evaluation.",
    examTraps: "Do not treat delirium with routine antipsychotics as though they shorten its duration; use them selectively for severe dangerous distress after reversible causes are addressed. A quiet ICU patient can still have severe hypoactive delirium.",
    sourceKeys: ["SCCM_PADIS_2025", "SCCM_ICU_LIBERATION_CURRENT"],
  },
  {
    slug: "vasopressors-inotropes-shock",
    title: "Vasopressors & Inotropes in Shock",
    bodySystem: "Critical Care",
    applicableExams: ["AGACNP", "ENP", "AANP-FNP", "ANCC-FNP"],
    recognize: "Choose vasoactive therapy from shock physiology: vasodilatory shock needs vascular tone, cardiogenic shock may need inotropy plus carefully selected vasopressor support, and obstructive/hypovolemic shock requires definitive cause correction. A low BP number alone does not identify the correct drug.",
    diagnostics: "Use exam, lactate trend, urine output, capillary refill, bedside ultrasound/echo and invasive hemodynamics selectively to define preload, contractility and vascular tone. Reassess perfusion after every major intervention rather than titrating pressors to MAP without examining the patient.",
    priorities: "Norepinephrine is first-line vasopressor for septic shock; add vasopressin or epinephrine when escalating support is needed. Use dobutamine or another inotrope when persistent hypoperfusion is driven by low cardiac output despite adequate pressure/volume, while correcting tamponade, PE, hemorrhage or MI when they are the true shock cause.",
    medicationSafety: "Catecholamines can cause tachyarrhythmia, ischemia and hyperglycemia; peripheral initiation can be appropriate to avoid dangerous delays when a proximal well-monitored IV is used, but extravasation must be recognized and treated. Dopamine has more arrhythmia risk and is reserved for selected circumstances.",
    redFlags: "Escalating vasopressor requirement, refractory lactate/perfusion deficit, ventricular arrhythmia, limb/mesenteric ischemia or shock of unclear mechanism requires urgent hemodynamic reassessment and source control/mechanical support consideration.",
    examTraps: "Do not give repeated fluid boluses to every hypotensive patient before pressors when fluid responsiveness is absent or pulmonary edema is developing. A MAP target is a starting point, not the only marker of adequate perfusion.",
    sourceKeys: ["SCCM_SURVIVING_SEPSIS_2021_CURRENT", "AHA_CARDIOGENIC_SHOCK_CURRENT"],
  },
  {
    slug: "continuous-renal-replacement-therapy",
    title: "Continuous Renal Replacement Therapy",
    bodySystem: "Critical Care",
    applicableExams: ["AGACNP", "ENP"],
    recognize: "CRRT provides slower continuous solute and fluid removal and is useful when severe AKI coexists with hemodynamic instability, cerebral edema risk or difficult fluid balance. The indication is the patient's refractory metabolic/volume problem—not a creatinine threshold by itself.",
    diagnostics: "Track potassium, bicarbonate, urea, phosphate, magnesium, calcium, fluid balance and delivered versus prescribed effluent dose. Identify filter clotting, access dysfunction and citrate accumulation when regional citrate anticoagulation is used.",
    priorities: "Start kidney replacement urgently for refractory hyperkalemia, severe acidosis, pulmonary edema/volume overload, selected toxin or uremic complications; choose CRRT versus intermittent therapy from hemodynamics and clinical goals. Set net ultrafiltration to the patient's perfusion and fluid-overload trajectory rather than automatically removing fluid aggressively.",
    medicationSafety: "CRRT increases clearance of many antimicrobials and other drugs; dose to modality/effluent and use drug-level monitoring when available. Regional citrate can cause calcium and acid-base disorders, while systemic heparin increases bleeding risk.",
    redFlags: "Refractory hyperkalemia/acidemia, severe filter/access failure, citrate toxicity, rapidly worsening hemodynamics during ultrafiltration or uncontrolled fluid overload requires urgent nephrology/critical-care adjustment.",
    examTraps: "Do not start dialysis from BUN/creatinine alone and do not assume CRRT is 'gentle' enough to tolerate any ultrafiltration rate. Medication doses cannot simply use standard ESRD tables during CRRT.",
    sourceKeys: ["KDIGO_AKI_CURRENT", "ADQI_CRRT_CURRENT"],
  },
  {
    slug: "critical-care-nutrition",
    title: "Nutrition in the Critically Ill Adult",
    bodySystem: "Critical Care",
    applicableExams: ["AGACNP"],
    recognize: "Critical illness causes catabolism and rapid muscle loss; nutritional strategy must consider pre-illness nutrition, shock, GI function and refeeding risk. Serum albumin/prealbumin are inflammatory markers and should not be used as stand-alone nutritional-status tests.",
    diagnostics: "Screen for malnutrition and refeeding risk, estimate energy/protein needs using indirect calorimetry when available or validated weight-based approaches, and monitor phosphate, potassium, magnesium, glucose and feeding tolerance. Do not use gastric residual volume alone to diagnose feeding intolerance.",
    priorities: "Use enteral nutrition when the gut is functional and the patient is sufficiently hemodynamically stabilized, advancing progressively rather than forcing full calories during uncontrolled shock. Prioritize adequate protein, mobility and refeeding prevention; use parenteral nutrition when enteral feeding is contraindicated or persistently insufficient according to nutrition risk/context.",
    medicationSafety: "Insulin therapy should avoid both severe hyperglycemia and hypoglycemia; propofol contributes meaningful lipid calories. Replace thiamine/electrolytes before and during refeeding in high-risk patients and avoid aggressive calories that precipitate refeeding syndrome.",
    redFlags: "Bowel ischemia, uncontrolled shock with escalating pressors, abdominal compartment syndrome, severe refeeding electrolyte collapse or inability to provide nutrition in a profoundly malnourished patient requires urgent multidisciplinary adjustment.",
    examTraps: "Do not wait for albumin to normalize before calling nutrition adequate and do not automatically feed full goal calories on day one of shock. Enteral feeding is preferred when feasible, not because parenteral nutrition is inherently forbidden.",
    sourceKeys: ["ASPEN_SCCM_CRITICAL_CARE_NUTRITION_CURRENT"],
  },
  {
    slug: "ventilator-associated-pneumonia",
    title: "Ventilator-Associated Pneumonia",
    bodySystem: "Critical Care",
    applicableExams: ["AGACNP", "ENP"],
    recognize: "New/progressive pulmonary infiltrate plus fever, purulent secretions, leukocyte change and worsening oxygenation after mechanical ventilation raises VAP concern, but atelectasis, edema, ARDS, hemorrhage and mucus plugging are common mimics. Colonized endotracheal secretions alone do not equal pneumonia.",
    diagnostics: "Obtain lower-respiratory cultures and blood cultures when appropriate before antibiotics if this does not delay treatment, then use local antibiogram, prior resistant organisms and recent IV antibiotics to estimate MRSA/Pseudomonas risk. Procalcitonin should not replace clinical criteria to decide whether to start antibiotics.",
    priorities: "Begin timely empiric therapy covering likely gram-negative organisms and MRSA only when risk warrants it, then de-escalate promptly to culture results and clinical response. Use prevention bundles—head elevation, oral care, sedation minimization, mobility and ventilator liberation—to reduce exposure duration.",
    medicationSafety: "Avoid unnecessary dual antipseudomonal or MRSA coverage once cultures permit narrowing; aminoglycosides/vancomycin require renal/drug-level monitoring. Shorter evidence-based treatment courses are preferred for improving uncomplicated VAP rather than automatic prolonged therapy.",
    redFlags: "Septic shock, rapid oxygenation decline, necrotizing/cavitary pneumonia, empyema or multidrug-resistant pathogen with inadequate therapy requires urgent ID/critical-care escalation.",
    examTraps: "A positive tracheal aspirate can represent colonization and does not prove VAP. Do not keep broad antibiotics solely because secretions remain colored when the patient is otherwise improving.",
    sourceKeys: ["ATS_IDSA_HAP_VAP_CURRENT", "CDC_VAP_PREVENTION_CURRENT"],
  },
  {
    slug: "ecmo-rescue-critical-care",
    title: "ECMO as Rescue Support",
    bodySystem: "Critical Care",
    applicableExams: ["AGACNP", "ENP"],
    recognize: "ECMO is temporary organ support, not definitive treatment: VV-ECMO supports severe potentially reversible respiratory failure with preserved cardiac function, while VA-ECMO provides circulatory plus oxygenation support for selected refractory cardiogenic shock/arrest states.",
    diagnostics: "Before referral define reversibility, severity/duration of lung or cardiac failure, neurologic status, bleeding risk, comorbidity and whether conventional evidence-based rescue strategies—lung-protective ventilation, proning, revascularization, mechanical circulatory options—have been optimized.",
    priorities: "Contact an ECMO-capable center early for potentially eligible patients before irreversible multiorgan failure develops. During ECMO, continue cause-specific therapy, lung-rest or cardiac unloading strategies, anticoagulation/device monitoring, rehabilitation and daily assessment for recovery, durable support or transplant pathway.",
    medicationSafety: "ECMO alters volume of distribution and clearance of antimicrobials/sedatives and creates major bleeding/thrombosis/hemolysis risks. Anticoagulation is individualized to circuit and patient bleeding risk; routine doses from non-ECMO patients may be inaccurate.",
    redFlags: "Refractory hypoxemia despite proning/optimized ventilation, refractory cardiogenic shock, circuit thrombosis, severe bleeding, limb ischemia or hemolysis requires immediate ECMO/critical-care expertise.",
    examTraps: "Do not wait until irreversible multiorgan failure to call an ECMO center and do not interpret ECMO as a therapy for the underlying pneumonia, myocarditis or MI—it buys time while definitive treatment/recovery occurs.",
    sourceKeys: ["ELSO_RESPIRATORY_ECMO_CURRENT", "ELSO_CARDIAC_ECMO_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
