import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch24 = [
  {
    slug: "hiv-diagnosis-treatment",
    title: "HIV Diagnosis & Treatment",
    bodySystem: "Infectious Disease",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PMHNP", "WHNP", "ENP"],
    recognize: "Acute HIV can resemble mononucleosis with fever, rash, pharyngitis and lymphadenopathy, while chronic infection may be asymptomatic. Ask sexual and injection exposure, prior testing, PrEP use, pregnancy and opportunistic-infection symptoms without stigma.",
    diagnostics: "Use the current antigen/antibody testing algorithm and order HIV RNA when acute infection is suspected despite negative or indeterminate serology. At diagnosis obtain viral load, CD4 count, resistance testing, hepatitis/STI/TB screening and baseline renal/hepatic assessment.",
    priorities: "Start antiretroviral therapy as soon as possible for essentially all people with HIV, link to experienced care, support adherence and address vaccines, reproductive goals, mental health and prevention. Viral suppression prevents sexual transmission.",
    medicationSafety: "ART selection depends on resistance, kidney/liver function, pregnancy, hepatitis B coinfection and drug interactions. Avoid stopping HBV-active ART abruptly in HBV coinfection because hepatitis flares can occur.",
    redFlags: "Severe hypoxemia, meningitis/encephalitis, focal neurologic deficit, sepsis, profound wasting, very low CD4 with opportunistic-infection symptoms or pregnancy complications requires urgent specialty/inpatient care.",
    examTraps: "A negative antibody-only test can miss acute infection. Undetectable equals untransmittable applies to sexual transmission when viral suppression is sustained, but ART does not prevent other STIs.",
    sourceKeys: ["DHHS_HIV_CURRENT", "CDC_HIV_CURRENT"],
  },
  {
    slug: "hiv-prep-pep",
    title: "HIV PrEP & PEP",
    bodySystem: "Infectious Disease",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PMHNP", "PNP", "WHNP", "ENP"],
    recognize: "PrEP is appropriate for people without HIV who want protection from sexual or injection exposure; current CDC guidance supports offering it broadly, including to patients who request it without disclosing a specific risk factor. PEP is time-critical after a substantial recent exposure.",
    diagnostics: "Confirm HIV-negative status with recommended testing before PrEP, assess renal function and hepatitis B status for tenofovir-based regimens, and screen STIs/pregnancy as appropriate. For PEP, test baseline HIV but do not delay the first dose while awaiting results when exposure is qualifying.",
    priorities: "Start PEP as soon as possible and within the current recommended postexposure window, then complete the full regimen and follow-up testing. Offer oral or injectable PrEP options matched to patient preference, adherence and medical eligibility.",
    medicationSafety: "Tenofovir-based PrEP requires renal and hepatitis B considerations; stopping HBV-active PrEP in chronic HBV can trigger flares. Long-acting injectable PrEP requires strict follow-up because subtherapeutic tail concentrations can select resistance if HIV is acquired.",
    redFlags: "Symptoms of acute HIV, a new positive/ambiguous HIV test while on PrEP, severe renal toxicity, or significant exposure in pregnancy requires rapid expert consultation while maintaining timely prophylaxis/treatment.",
    examTraps: "Do not require a patient to prove 'high risk' before discussing PrEP. PEP is not useful as a delayed plan weeks after exposure; timing matters.",
    sourceKeys: ["CDC_PREP_2026", "CDC_PEP_CURRENT"],
  },
  {
    slug: "lyme-tickborne-disease",
    title: "Lyme & Common Tick-Borne Disease",
    bodySystem: "Infectious Disease",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PNP", "ENP"],
    recognize: "Expanding erythema migrans, facial palsy, meningitis/radiculopathy, carditis or migratory arthritis after tick exposure suggests Lyme disease; ehrlichiosis/anaplasmosis more often cause fever, cytopenias and transaminitis without classic EM rash.",
    diagnostics: "Diagnose classic erythema migrans clinically without waiting for serology. Use two-tier Lyme serology for later manifestations and targeted PCR/CSF/cardiac testing when indicated; test coinfections when epidemiology and labs support them.",
    priorities: "Use manifestation-specific antibiotic therapy and treat suspected severe ehrlichiosis/anaplasmosis promptly with doxycycline without waiting for confirmatory tests. Prevention includes prompt tick removal and selected single-dose prophylaxis only when guideline criteria are met.",
    medicationSafety: "Doxycycline is appropriate for many tick-borne infections, including short courses in children when indicated. Ceftriaxone is reserved for selected neuro/cardiac disease and carries biliary/line risks.",
    redFlags: "High-grade AV block, syncope, severe neurologic disease, shock, meningoencephalitis or severe cytopenic systemic illness requires urgent inpatient care.",
    examTraps: "Do not order Lyme serology for a classic EM lesion and delay treatment. Persistent nonspecific fatigue after appropriate therapy is not evidence for indefinite antibiotics.",
    sourceKeys: ["IDSA_LYME_CURRENT", "CDC_TICKBORNE_CURRENT"],
  },
  {
    slug: "adult-immunizations",
    title: "Adult Immunizations",
    bodySystem: "Preventive Care",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PMHNP", "WHNP"],
    recognize: "Vaccine needs depend on age, prior doses, pregnancy, immune status, occupation, travel, asplenia, chronic heart/lung/kidney/liver disease, diabetes and other risk—not simply an annual influenza shot.",
    diagnostics: "Use the current CDC adult schedule by age plus medical-condition notes and contraindication appendix. Accept reliable prior documentation or evidence of immunity where appropriate instead of ordering unnecessary antibody tests for every vaccine.",
    priorities: "Close routine and risk-based gaps at every visit, including influenza, Tdap/Td, zoster, pneumococcal, RSV, hepatitis, HPV and other indicated vaccines according to the current schedule and shared decision-making recommendations.",
    medicationSafety: "Live vaccines are contraindicated in pregnancy and severe immunodeficiency; inactivated/recombinant vaccines generally can be used when indicated. Time selected vaccines around immunosuppressive therapy to maximize response without delaying urgent treatment.",
    redFlags: "Prior anaphylaxis to a vaccine/component is a true contraindication requiring specialist guidance; most local reactions, stable chronic illness and mild acute illness are not reasons to permanently defer vaccination.",
    examTraps: "Do not rely on an outdated memorized schedule—the CDC schedule changes. HPV vaccination is not recommended during pregnancy but inadvertent administration is not an indication for intervention.",
    sourceKeys: ["CDC_ADULT_IMMUNIZATION_2025_CURRENT"],
  },
  {
    slug: "travel-medicine",
    title: "Travel Medicine & Pretravel Counseling",
    bodySystem: "Preventive Care",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "WHNP"],
    recognize: "Travel risk depends on exact itinerary, season, duration, accommodations, activities, altitude, pregnancy, immune status and underlying disease. Country name alone is not enough to choose vaccines or prophylaxis.",
    diagnostics: "Review routine vaccines, destination-specific yellow fever/meningococcal/polio or other requirements, malaria maps, food/water risk, rabies exposure, altitude, VTE risk and medication access. Screen pregnancy and immunosuppression before live vaccines.",
    priorities: "Update routine and destination vaccines, prescribe malaria prophylaxis matched to resistance and patient factors, provide travelers-diarrhea and mosquito-bite counseling, and create a plan for chronic medications and emergency care abroad.",
    medicationSafety: "Atovaquone-proguanil, doxycycline and mefloquine have distinct renal, pregnancy, neuropsychiatric and interaction limitations. Yellow-fever vaccine is live and requires individualized risk-benefit assessment in pregnancy, immune compromise and older age.",
    redFlags: "Fever after travel to a malaria-endemic area is malaria until urgently excluded; severe diarrhea, hemorrhagic symptoms, jaundice, respiratory distress or neurologic illness after travel also requires prompt evaluation.",
    examTraps: "Do not prescribe one malaria drug for every destination. Vaccines given the day before departure may not provide timely protection, so pretravel care should start early when possible.",
    sourceKeys: ["CDC_YELLOW_BOOK_CURRENT"],
  },
  {
    slug: "febrile-neutropenia",
    title: "Febrile Neutropenia",
    bodySystem: "Infectious Disease",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGACNP", "ENP"],
    recognize: "Fever in a patient with significant neutropenia after chemotherapy or marrow disease is a time-sensitive infection even when the exam is benign because inflammation can be minimal.",
    diagnostics: "Obtain CBC with differential, cultures from blood and appropriate catheter/peripheral sites, CMP and source-directed imaging or cultures, but do not delay empiric antibiotics for extensive testing.",
    priorities: "Give prompt empiric antipseudomonal antibiotics, assess hemodynamic stability and use validated risk criteria only to identify carefully selected low-risk outpatient candidates. High-risk patients require admission and broader therapy based on source/resistance.",
    medicationSafety: "Vancomycin is not automatically included for every neutropenic fever; add it for defined indications such as catheter infection, skin/soft-tissue infection, pneumonia or hemodynamic instability. Renally dose broad-spectrum agents.",
    redFlags: "Hypotension, lactate elevation, pneumonia, severe mucositis, abdominal pain/typhlitis, prolonged profound neutropenia or organ dysfunction requires emergency inpatient care.",
    examTraps: "Do not wait for a high fever or elevated WBC. Neutropenic patients may have serious infection without pus, focal redness or marked inflammatory response.",
    sourceKeys: ["IDSA_FEBRILE_NEUTROPENIA_CURRENT", "ASCO_FN_CURRENT"],
  },
  {
    slug: "clostridioides-difficile-infection",
    title: "Clostridioides difficile Infection",
    bodySystem: "Infectious Disease",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "New clinically significant diarrhea after antibiotics, hospitalization or healthcare exposure raises concern for C. difficile, especially with abdominal pain, leukocytosis, AKI or recurrence history.",
    diagnostics: "Test only unformed stool from symptomatic patients using the institution's validated toxin/NAAT algorithm. Do not test asymptomatic patients for cure because colonization can persist after successful treatment.",
    priorities: "Stop unnecessary culprit antibiotics and acid suppression, use guideline-preferred oral therapy according to initial versus recurrent/severe disease, maintain contact precautions and consider fecal microbiota-based prevention strategies for selected recurrences.",
    medicationSafety: "Antimotility drugs are avoided in fulminant colitis. Oral vancomycin/fidaxomicin act in the gut; IV vancomycin does not treat luminal C. difficile colitis.",
    redFlags: "Hypotension, ileus, toxic megacolon, severe abdominal distention, rising lactate, perforation or rapidly worsening AKI/leukocytosis requires urgent surgical/infectious-disease care.",
    examTraps: "A positive NAAT in a patient without meaningful diarrhea may represent colonization. Do not repeat testing just to document a negative result after symptoms resolve.",
    sourceKeys: ["IDSA_SHEA_CDI_CURRENT"],
  },
  {
    slug: "recurrent-infections-immunodeficiency",
    title: "Recurrent Infections & Adult Immunodeficiency Evaluation",
    bodySystem: "Infectious Disease",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "Unusually frequent, severe, persistent, opportunistic or anatomically unusual infections—especially with poor vaccine response, chronic diarrhea, weight loss, autoimmune disease or family history—may indicate immune deficiency rather than simple exposure frequency.",
    diagnostics: "Start with CBC/differential, HIV testing, quantitative immunoglobulins and targeted complement/lymphocyte testing guided by infection pattern. Review diabetes, steroids, biologics, malignancy, asplenia and structural lung/sinus disease before assuming primary immunodeficiency.",
    priorities: "Treat active infection, correct secondary causes when possible, update nonlive or otherwise appropriate vaccines, and refer suspected primary antibody, cellular or complement disorders to clinical immunology.",
    medicationSafety: "Live vaccines can be dangerous in severe cellular immunodeficiency; prophylactic antibiotics or immunoglobulin replacement should follow a defined diagnosis and specialist plan rather than recurrent empiric prescribing.",
    redFlags: "Opportunistic CNS or pulmonary infection, severe sepsis, profound cytopenias, major weight loss or suspected severe combined/secondary immunodeficiency requires urgent evaluation.",
    examTraps: "Repeated uncomplicated viral URIs alone do not prove immunodeficiency. Normal total immunoglobulin levels do not exclude every functional antibody or cellular defect.",
    sourceKeys: ["AAAAI_IMMUNODEFICIENCY_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
