import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch51 = [
  {
    slug: "controlled-substance-prescribing-governance",
    title: "Controlled-Substance Prescribing Governance",
    bodySystem: "Professional Practice",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PMHNP", "PNP", "WHNP", "ENP"],
    recognize: "Controlled-substance prescribing requires a valid clinical indication, informed risk-benefit assessment, patient identity/medication reconciliation and compliance with federal plus state law. Regulations vary by state and drug schedule, so clinical education should not invent one universal refill, telehealth or prescribing-authority rule.",
    diagnostics: "Before chronic controlled therapy assess diagnosis/function, substance-use/overdose history, concurrent sedatives, pregnancy, renal/hepatic function and PDMP data when required/available; toxicology is used selectively to improve safety rather than as punitive surveillance.",
    priorities: "Document goals, alternatives, informed consent and follow-up, prescribe the lowest-risk effective regimen and use naloxone/harm-reduction strategies when opioid overdose risk is elevated. For OUD, buprenorphine prescribing no longer requires the retired federal X-waiver, although DEA/state controlled-substance requirements still apply.",
    medicationSafety: "Avoid abrupt discontinuation of chronically dependent opioids or benzodiazepines without an imminent life-threatening reason. Co-prescribed opioids/benzodiazepines increase overdose risk and warrant coordination, not automatic patient abandonment.",
    redFlags: "Overdose, dangerous intoxication, diversion creating imminent harm, severe withdrawal, suicidal intent or forged/altered prescriptions with safety implications requires urgent clinical and legally appropriate response.",
    examTraps: "Do not teach state-specific NP controlled-substance authority as if it applies nationally and do not equate an unexpected toxicology result with proof of a substance-use disorder.",
    sourceKeys: ["DEA_CONTROLLED_SUBSTANCES_CURRENT", "CDC_OPIOID_2022_CURRENT", "SAMHSA_MAT_ACT_CURRENT"],
  },
  {
    slug: "renal-hepatic-medication-dosing",
    title: "Renal & Hepatic Medication Dose Adjustment",
    bodySystem: "Professional Practice",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PMHNP", "PNP", "WHNP", "ENP"],
    recognize: "Drug exposure changes with kidney filtration/secretion and hepatic metabolism/flow; 'normal creatinine' or mild transaminase elevation does not directly quantify clearance. Dose adjustment is drug-specific and may depend on creatinine clearance, eGFR, Child-Pugh class, dialysis modality and therapeutic index.",
    diagnostics: "Use the renal-function measure specified in the drug evidence/label and reassess with acute kidney injury or weight change; review bilirubin, INR, albumin and clinical hepatic decompensation rather than AST/ALT alone for hepatic synthetic function. Identify dialysis clearance and active metabolites.",
    priorities: "Adjust dose, interval or drug choice based on current organ function and treatment urgency, use therapeutic drug monitoring when available and reassess after AKI recovery or dialysis changes. In unstable renal function, repeated calculation and clinical response matter more than one automated eGFR.",
    medicationSafety: "Avoid dose stacking of renally cleared sedatives, gabapentinoids, opioids and antimicrobials; acetaminophen, anticoagulants and psychotropics each have specific hepatic considerations. Child-Pugh rules are not interchangeable across drugs and should be checked in primary labeling/references.",
    redFlags: "Rapid AKI, severe hepatic failure, encephalopathy, dangerous drug level, recurrent hypoglycemia, oversedation or bleeding from drug accumulation requires urgent dose cessation/reversal and organ-specific care.",
    examTraps: "Do not automatically dose every drug by eGFR shown on the lab if its evidence uses Cockcroft-Gault CrCl, and do not use transaminases alone to classify hepatic drug clearance.",
    sourceKeys: ["FDA_RENAL_IMPAIRMENT_DOSING_CURRENT", "FDA_HEPATIC_IMPAIRMENT_DOSING_CURRENT"],
  },
  {
    slug: "medication-reconciliation-transitions",
    title: "Medication Reconciliation & Transitions of Care",
    bodySystem: "Professional Practice",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PMHNP", "PNP", "WHNP", "ENP"],
    recognize: "Medication discrepancies cluster at admission, transfer and discharge: duplicate therapies, omitted chronic drugs, wrong dose/formulation, stale PRNs, unintended continuation of temporary inpatient medications and misunderstood stop dates are common preventable harms.",
    diagnostics: "Build the best possible medication history from patient/caregiver, bottles, pharmacy fills, specialists and prior records, including OTC drugs, supplements, injections and adherence. Distinguish what was prescribed from what the patient actually takes and why.",
    priorities: "For every transition explicitly decide continue/change/hold/stop/restart for each medication, resolve duplicate indications, document the reason and communicate a clean final list with follow-up/lab monitoring. High-risk drugs—anticoagulants, insulin, opioids, immunosuppressants, antiarrhythmics—receive extra verification.",
    medicationSafety: "Avoid silently restarting ACEi/diuretics/SGLT2 drugs held during acute illness without checking renal/volume status and avoid continuing prophylactic inpatient PPIs, bowel regimens or anticoagulants without a postdischarge indication.",
    redFlags: "Conflicting anticoagulant instructions, duplicate insulin, missing transplant/antiepileptic therapy, opioid/benzodiazepine duplication or absent time-critical antimicrobial plan requires resolution before discharge.",
    examTraps: "An EHR medication list is not medication reconciliation. The correct question is not 'is it on the list?' but 'is the patient taking it, is it still indicated and what changed today?'",
    sourceKeys: ["AHRQ_MED_RECONCILIATION_CURRENT", "TJC_MEDICATION_RECONCILIATION_CURRENT"],
  },
  {
    slug: "deprescribing-polypharmacy",
    title: "Deprescribing & Polypharmacy",
    titleAliases: ["Beers Criteria & Polypharmacy Management in Older Adults"],
    slugAliases: ["geriatrics-beers-polypharmacy-np"],
    bodySystem: "Professional Practice",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PMHNP"],
    recognize: "Polypharmacy risk comes from medication burden, interactions, anticholinergic/sedative load, renal changes and goal mismatch—not from an arbitrary number alone. Falls, confusion, orthostasis, anorexia, incontinence or functional decline may be medication syndromes.",
    diagnostics: "For each drug identify indication, benefit horizon, current dose, adherence, adverse effects, interactions, renal/hepatic fit and patient goals. Use tools such as AGS Beers Criteria as screening prompts, not absolute prohibition lists.",
    priorities: "Prioritize stopping drugs without current indication or with high harm/low benefit, one change at a time when possible, and create taper/monitoring plans. Incorporate life expectancy, frailty and patient priorities—deprescribing preventive therapy may be appropriate when time-to-benefit exceeds goals.",
    medicationSafety: "Benzodiazepines, beta blockers, clonidine, corticosteroids, PPIs, antidepressants and opioids may require tapering or disease-specific monitoring; abrupt cessation can cause withdrawal/rebound. Simplifying regimens should preserve essential disease-modifying treatment.",
    redFlags: "Suspected medication-induced delirium, falls with injury, severe hypotension/bradycardia, hypoglycemia, bleeding or withdrawal requires urgent medication review.",
    examTraps: "Beers Criteria means 'potentially inappropriate in specific contexts,' not 'never prescribe to anyone over 65.' Deprescribing is active monitored care, not simply deleting medications.",
    sourceKeys: ["AGS_BEERS_2023_CURRENT", "DEPRESCRIBING_GUIDELINES_CURRENT"],
  },
  {
    slug: "pharmacogenomics-primary-care",
    title: "Pharmacogenomics in Prescribing",
    bodySystem: "Professional Practice",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PMHNP", "PNP", "WHNP"],
    recognize: "Pharmacogenomics is clinically useful only for gene-drug pairs with actionable evidence: examples include HLA-B*57:01-abacavir, HLA-B*15:02-carbamazepine in relevant ancestry, CYP2C19-clopidogrel and selected antidepressant/thiopurine relationships. It is not a universal prediction of medication success.",
    diagnostics: "Order a validated test only when the result can change a current or foreseeable drug decision and interpret allele function using CPIC/FDA-supported guidance. Consider ancestry carefully but avoid using race as a proxy for genotype when direct testing is indicated.",
    priorities: "Translate genotype to phenotype and a concrete drug/dose alternative, document the durable result in the medical record and educate patients that one result can remain relevant lifelong. Coordinate specialist/pharmacist expertise for complex polygenic or transplant/oncology applications.",
    medicationSafety: "A 'normal metabolizer' genotype does not eliminate interactions, organ dysfunction or adverse effects; phenoconversion from strong enzyme inhibitors can override genotype. Direct-to-consumer panels may not assay all clinically relevant variants.",
    redFlags: "A severe prior hypersensitivity reaction should not be rechallenged merely because genetic testing is negative; treat the clinical allergy/toxicity first.",
    examTraps: "Do not order broad pharmacogenomic panels as screening in every healthy patient and do not change therapy from genotype without confirming that a current evidence-based gene-drug guideline exists.",
    sourceKeys: ["CPIC_CURRENT", "FDA_PHARMACOGENOMICS_CURRENT"],
  },
  {
    slug: "adverse-drug-reaction-assessment",
    title: "Adverse Drug Reaction Assessment & Reporting",
    bodySystem: "Professional Practice",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PMHNP", "PNP", "WHNP", "ENP"],
    recognize: "Adverse drug reactions can be predictable dose-related toxicity, hypersensitivity, idiosyncratic organ injury, withdrawal or interactions. Timing, dechallenge/rechallenge, competing diseases and prior exposure are more informative than simply labeling every symptom an 'allergy.'",
    diagnostics: "Build a timeline of drug starts/stops/dose changes, evaluate disease mimics and obtain organ-specific labs/ECG/imaging when needed. Distinguish IgE-mediated allergy from intolerance and severe delayed reactions because future prescribing implications differ dramatically.",
    priorities: "Stop the suspected drug immediately for severe toxicity/SCAR/anaphylaxis, stabilize the patient, document the exact phenotype and culprit, and report serious/unexpected events through FDA MedWatch or appropriate surveillance. Refer for allergy evaluation when delabeling could restore important beta-lactam or other options.",
    medicationSafety: "Never rechallenge SJS/TEN/DRESS culprit drugs intentionally outside extraordinary specialist circumstances. For benign side effects, unnecessary permanent allergy labels can create downstream harm and broader antibiotic use.",
    redFlags: "Anaphylaxis, SJS/TEN, DRESS with organ injury, agranulocytosis, drug-induced liver failure, torsades or severe bleeding requires emergency treatment.",
    examTraps: "Nausea from amoxicillin is not the same as anaphylaxis and 'sulfa allergy' does not automatically mean cross-reactivity with every nonantibiotic sulfonamide.",
    sourceKeys: ["FDA_MEDWATCH_CURRENT", "AAAAI_DRUG_ALLERGY_CURRENT"],
  },
  {
    slug: "shared-decision-making-prescribing",
    title: "Shared Decision-Making for Preference-Sensitive Prescribing",
    bodySystem: "Professional Practice",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PMHNP", "PNP", "WHNP", "ENP"],
    recognize: "Many prescribing decisions have more than one reasonable option—anticoagulation in borderline risk, menopause therapy, contraception, obesity treatment, statins, prostate screening-related choices and chronic pain therapy. The NP's role is to combine evidence with the patient's values, not present personal preference as a guideline mandate.",
    diagnostics: "Clarify the decision, absolute baseline risk, expected benefit/harm, uncertainty, cost/access and patient goals; verify health literacy and decisional capacity. Use absolute numbers and natural frequencies when possible rather than relative-risk framing alone.",
    priorities: "Present reasonable options including no treatment where appropriate, elicit what matters most, make a collaborative decision and document the rationale/follow-up trigger for revisiting it. Use decision aids when validated and do not convert them into rigid score-driven decisions.",
    medicationSafety: "Shared decision-making does not justify unsafe prescribing or eliminate informed-consent duties; contraindications, public-health requirements and capacity limitations still apply. Conversely, guideline recommendations often allow individualized preference-sensitive exceptions.",
    redFlags: "Impaired capacity, coercion, acute instability or decisions carrying immediate life-threatening risk may require surrogate/emergency pathways rather than routine preference elicitation.",
    examTraps: "Do not confuse shared decision-making with simply asking 'what do you want?' after withholding evidence, and do not present relative-risk reductions without baseline absolute risk.",
    sourceKeys: ["AHRQ_SHARED_DECISION_CURRENT", "USPSTF_SHARED_DECISION_CURRENT"],
  },
  {
    slug: "prescribing-in-pregnancy-lactation",
    title: "Medication Prescribing in Pregnancy & Lactation",
    bodySystem: "Professional Practice",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "WHNP", "PNP", "PMHNP"],
    recognize: "Medication risk in pregnancy depends on trimester, dose, placental transfer, untreated maternal disease and available alternatives; lactation risk depends on milk transfer, infant age/prematurity, oral bioavailability and toxicity. Untreated disease can be more dangerous than the medication.",
    diagnostics: "Confirm pregnancy/lactation timing and indication, then use current product labeling and evidence resources rather than obsolete FDA A/B/C/D/X letter categories. Review contraception/teratogenicity for medications such as isotretinoin, valproate, methotrexate, ACEi/ARB/ARNI and selected immunomodulators.",
    priorities: "Choose medications with the best maternal-fetal evidence for the condition, use the lowest effective exposure while maintaining disease control and coordinate specialists for epilepsy, bipolar disorder, autoimmune disease, hypertension, diabetes or infection where treatment interruption is hazardous.",
    medicationSafety: "Avoid abrupt discontinuation of essential psychiatric/antiepileptic/glucocorticoid therapy without a safer transition. LactMed and specialist resources help assess breastfeeding; 'detected in milk' does not automatically mean breastfeeding is contraindicated.",
    redFlags: "Teratogen exposure with high fetal risk, uncontrolled maternal disease, severe medication toxicity or neonatal sedation/poor feeding from medication exposure requires urgent maternal-fetal/pediatric consultation.",
    examTraps: "Do not use retired FDA pregnancy letter categories and do not assume 'natural' supplements are pregnancy-safe. Risk decisions compare medication risk against the risk of untreated maternal illness.",
    sourceKeys: ["FDA_PLLR_CURRENT", "NIH_LACTMED_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
