import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch61 = [
  {
    slug: "advanced-history-physical-exam",
    title: "Advanced History & Physical Examination",
    bodySystem: "Advanced Practice",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PMHNP", "PNP", "WHNP", "ENP"],
    recognize: "Advanced assessment is hypothesis-driven: start with the patient's concern and stability, then gather discriminating history and examination findings that move probabilities rather than performing every maneuver on every patient. Baseline function, medications, social context and prior data often change interpretation more than one isolated physical sign.",
    diagnostics: "Use focused systems plus general danger-sign assessment, compare bilateral/serial findings and understand sensitivity/specificity limitations of bedside maneuvers. Abnormal findings generate a differential and testing plan; normal findings reduce but rarely eliminate disease probability by themselves.",
    priorities: "Identify threats first, then the leading diagnosis, dangerous alternatives and conditions that cannot be missed; document pertinent positives/negatives that actually support decision-making. Reassess after treatment because trajectory is part of the examination.",
    medicationSafety: "Medication adverse effects can mimic disease—orthostasis, tremor, edema, cough, delirium, bleeding—so medication review belongs in the physical diagnostic process rather than after it.",
    redFlags: "Unstable vital signs, altered consciousness, focal neurologic deficit, respiratory distress, peritoneal signs, active hemorrhage or acute vascular compromise requires immediate stabilization/escalation rather than completion of a routine comprehensive exam.",
    examTraps: "Do not confuse a long review of systems with a high-quality assessment and do not let one 'classic' sign outweigh the entire clinical probability and trajectory.",
    sourceKeys: ["BATES_ADVANCED_ASSESSMENT_CURRENT", "AHRQ_DIAGNOSTIC_REASONING_CURRENT"],
  },
  {
    slug: "differential-diagnosis-construction",
    title: "Differential Diagnosis Construction",
    bodySystem: "Advanced Practice",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PMHNP", "PNP", "WHNP", "ENP"],
    recognize: "A useful differential is prioritized, not encyclopedic: include the most likely diagnosis, dangerous time-sensitive alternatives and a few plausible mimics that would change testing or treatment. Problem representation compresses age, time course, key features and risk into one diagnostic sentence.",
    diagnostics: "For each candidate identify which finding would meaningfully raise/lower probability and which test can cross a treatment or exclusion threshold. Use illness scripts and anatomic/pathophysiologic categories to recover diagnoses when pattern recognition is uncertain.",
    priorities: "Test or treat dangerous alternatives first when delay is costly, choose discriminating rather than repetitive tests and update the differential after each new result. A final plan should explain why the leading diagnosis fits and why the most dangerous alternatives are adequately addressed.",
    medicationSafety: "Empiric therapy can obscure diagnosis or cause harm—antibiotics sterilize cultures, steroids worsen selected infection, anticoagulation increases bleeding—so the threshold for empiric treatment should reflect both disease risk and medication risk.",
    redFlags: "Diagnostic uncertainty in an unstable or rapidly worsening patient requires escalation, serial reassessment and broader consultation rather than outpatient watchful waiting.",
    examTraps: "Do not choose the rarest diagnosis because it explains every detail if a common dangerous diagnosis is more probable, and do not stop at the first plausible label before checking must-not-miss alternatives.",
    sourceKeys: ["AHRQ_DIAGNOSTIC_REASONING_CURRENT"],
  },
  {
    slug: "cognitive-bias-diagnostic-error",
    title: "Cognitive Bias & Diagnostic Error Prevention",
    bodySystem: "Advanced Practice",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PMHNP", "PNP", "WHNP", "ENP"],
    recognize: "Anchoring, premature closure, confirmation bias, availability, framing and diagnostic momentum can produce error even in experienced clinicians. Bias risk rises with fatigue, interruptions, emotionally salient cases and inherited diagnoses from prior notes.",
    diagnostics: "Use diagnostic timeouts for high-risk or discordant cases: restate the problem, ask what else could cause it, identify findings that do not fit and seek disconfirming data. Compare current physiology with prior labels rather than copying the old assessment.",
    priorities: "Build forcing functions around must-not-miss diagnoses, use second opinions/decision support appropriately and create explicit follow-up for uncertain diagnoses. Review near misses for system and reasoning contributors rather than shame.",
    medicationSafety: "Medication anchoring occurs when new symptoms are attributed to disease instead of adverse effects—or vice versa; reconcile timing, dechallenge and objective data before changing high-risk therapy.",
    redFlags: "A patient returning repeatedly with worsening symptoms, abnormal vital signs, unexpected test discordance or failure of appropriate treatment should trigger diagnostic reset/escalation.",
    examTraps: "Knowing the name of a bias does not prevent it; use structured countermeasures. Do not assume a consultant or prior clinician's diagnosis is correct simply because it appears repeatedly in the chart.",
    sourceKeys: ["AHRQ_DIAGNOSTIC_SAFETY_CURRENT", "NASEM_DIAGNOSTIC_ERROR_CURRENT"],
  },
  {
    slug: "test-result-follow-up",
    title: "Abnormal Test Result Follow-Up",
    bodySystem: "Advanced Practice",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PMHNP", "PNP", "WHNP", "ENP"],
    recognize: "The clinician who orders or receives a test needs a defined ownership and escalation process. Incidental imaging, abnormal pathology, positive cultures and overdue surveillance are common sources of preventable delayed diagnosis when results are merely released to a portal.",
    diagnostics: "Classify the result by urgency, reliability and need for confirmation; compare prior trends and verify that the result belongs to the correct patient/specimen. Critical values require direct timely communication and action, while uncertain incidental findings require guideline-based follow-up.",
    priorities: "Communicate the meaning—not just the number—to the patient, document the action plan, place the follow-up order/referral and use a tracking system until the loop closes. Escalate nonresponse for high-risk findings rather than documenting one unanswered phone call.",
    medicationSafety: "Drug-monitoring labs such as potassium, creatinine, INR, lithium, anticonvulsant or immunosuppressant levels require preplanned thresholds for hold/adjust/recheck; prescribing without a result-follow-up process is incomplete care.",
    redFlags: "Critical pathology, severe electrolyte/glucose abnormality, positive blood culture, major imaging finding or repeatedly failed contact for a potentially life-threatening result requires active escalation.",
    examTraps: "Portal auto-release is not closed-loop follow-up and 'no news is good news' is unsafe. A result can be technically noncritical but clinically urgent because of the patient's context.",
    sourceKeys: ["AHRQ_TEST_RESULTS_CURRENT", "TJC_CRITICAL_RESULTS_CURRENT"],
  },
  {
    slug: "motivational-interviewing-behavior-change",
    title: "Motivational Interviewing & Behavior Change",
    bodySystem: "Advanced Practice",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PMHNP", "PNP", "WHNP"],
    recognize: "Behavior change is more likely when the patient articulates their own reasons and confidence than when the clinician lectures. Ambivalence is normal in smoking cessation, substance use, weight, exercise, medication adherence and chronic disease self-management.",
    diagnostics: "Ask open questions, use reflective listening, affirm strengths and elicit change talk; assess importance/confidence/readiness and the structural barriers that make adherence difficult. Distinguish unwillingness from inability due to cost, depression, cognition or access.",
    priorities: "Offer evidence with permission, connect the behavior to the patient's values, negotiate one achievable next step and arrange follow-up. Use pharmacologic/structural support when appropriate rather than expecting counseling alone to overcome addiction or resource barriers.",
    medicationSafety: "Shared behavior goals should not lead to abrupt withdrawal of dependence-producing medications or unsafe self-directed changes; create medically appropriate taper/titration plans.",
    redFlags: "Immediate self-harm, severe withdrawal, medical instability or coercive environment requires direct safety treatment rather than routine motivational interviewing.",
    examTraps: "Do not confront resistance with more argument and do not equate a patient declining today's recommendation with permanent refusal or lack of concern for health.",
    sourceKeys: ["SAMHSA_MOTIVATIONAL_INTERVIEWING_CURRENT"],
  },
  {
    slug: "clinical-documentation-coding",
    title: "Clinical Documentation & Coding Principles",
    bodySystem: "Advanced Practice",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PMHNP", "PNP", "WHNP", "ENP"],
    recognize: "Documentation should communicate the patient's condition, reasoning, risk and plan; coding follows the service actually performed and documented. Copy-forward and template bloat can hide change and create false findings.",
    diagnostics: "Document relevant history/exam, data reviewed/interpreted, differential/assessment, medication decisions, procedures and disposition. For E/M services use current CPT/CMS rules based on medical decision-making or qualifying total time when applicable rather than obsolete mandatory history/exam bullet counts.",
    priorities: "Make the note clinically useful first, specify problem status and risk, link tests/medications to indications and document shared decisions/return precautions. Query or correct errors rather than deleting audit trails improperly.",
    medicationSafety: "Record dose, route, frequency, indication and meaningful changes; controlled substances and high-risk medication plans should include monitoring and rationale without copying inaccurate historical data.",
    redFlags: "Falsified exam findings, upcoding, cloned documentation that misrepresents care or missing critical-result/disposition documentation requires correction and compliance/safety escalation.",
    examTraps: "More words do not equal higher complexity and a comprehensive physical exam is no longer required solely to support higher office E/M levels under current rules.",
    sourceKeys: ["CMS_EM_CURRENT", "AMA_CPT_EM_CURRENT"],
  },
  {
    slug: "np-scope-regulation-credentialing",
    title: "NP Scope, Regulation & Credentialing in the United States",
    bodySystem: "Advanced Practice",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PMHNP", "PNP", "WHNP", "ENP"],
    recognize: "NP authority is determined by education/certification population focus plus state nurse-practice law, board rules, institutional credentialing/privileging, payer rules and federal law. Full, reduced and restricted practice environments differ and can change over time.",
    diagnostics: "Before performing a procedure, prescribing a controlled substance or practicing across state lines, verify the current state's law/board rule and employer privileges; do not infer authority from another state's model or from what a collaborating physician can do.",
    priorities: "Practice within population focus and documented competence, maintain licensure/certification/DEA requirements when needed and escalate/consult beyond scope or competence. Use current official board resources for state-specific requirements.",
    medicationSafety: "Prescriptive authority—including schedules and collaboration requirements—varies by jurisdiction; the safest educational rule is to verify current law rather than memorize a national fiction.",
    redFlags: "Requested care outside certification population/competence, expired credentials, unclear controlled-substance authority or conflict between law and employer policy requires clarification before proceeding.",
    examTraps: "National certification does not itself grant an identical scope in every state and a facility privilege cannot expand statutory scope beyond law.",
    sourceKeys: ["AANP_STATE_PRACTICE_ENVIRONMENT_CURRENT", "NCSBN_APRN_CONSENSUS_CURRENT"],
  },
  {
    slug: "evidence-appraisal-nnt-harm",
    title: "Evidence Appraisal: Absolute Benefit, NNT & Harm",
    bodySystem: "Advanced Practice",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PMHNP", "PNP", "WHNP", "ENP"],
    recognize: "Relative risk can exaggerate the apparent importance of a treatment when baseline risk is low. Absolute risk reduction, number needed to treat, absolute harm and time-to-benefit make trial results clinically interpretable for an individual patient.",
    diagnostics: "Assess study population, randomization/blinding, attrition, outcome definition, confidence intervals, subgroup credibility and whether the comparator reflects current care. Distinguish surrogate outcomes from patient-important outcomes and statistical significance from clinically meaningful effect.",
    priorities: "Translate evidence into the patient's baseline risk and preferences, then decide whether benefit exceeds harm/cost/burden. Use systematic reviews/guidelines critically and update decisions when stronger evidence changes standards.",
    medicationSafety: "Rare serious harms may not be fully detected in premarketing trials, so postmarketing evidence and pharmacovigilance matter. Avoid extrapolating benefit to populations excluded from the trial without acknowledging uncertainty.",
    redFlags: "A dramatic relative benefit from a tiny underpowered or biased trial, implausible subgroup effect or surrogate-only endpoint should not drive high-risk treatment without corroborating evidence.",
    examTraps: "A 50% relative-risk reduction can be only a 1% absolute reduction, and NNT is meaningless without a time horizon and baseline population.",
    sourceKeys: ["JAMA_USERS_GUIDES_CURRENT", "GRADE_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
