import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch11 = [
  {
    slug: "hypertensive-disorders-pregnancy",
    title: "Hypertensive Disorders of Pregnancy",
    bodySystem: "Reproductive",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "WHNP", "ENP"],
    recognize: "New hypertension after 20 weeks, severe-range blood pressure, headache, visual symptoms, RUQ or epigastric pain, pulmonary symptoms, thrombocytopenia, or fetal-growth concerns should raise concern for gestational hypertension or preeclampsia rather than being dismissed as normal pregnancy discomfort.",
    diagnostics: "Confirm blood pressure with correct technique and assess urine protein, CBC or platelets, creatinine, liver enzymes, symptoms, gestational age, and fetal status. Proteinuria supports preeclampsia but severe features can establish the diagnosis even without it.",
    priorities: "Severe-range blood pressure needs prompt treatment and obstetric escalation. Management depends on gestational age, severe features, maternal or fetal stability, and delivery timing; magnesium sulfate is used for seizure prophylaxis in appropriate severe disease.",
    medicationSafety: "Use pregnancy-compatible antihypertensives such as labetalol, nifedipine, or hydralazine in acute protocols as appropriate. ACE inhibitors and ARBs are avoided in pregnancy. Magnesium requires respiratory, reflex, urine-output, and toxicity awareness.",
    redFlags: "Severe persistent headache, visual change, seizure, severe-range hypertension, pulmonary edema, RUQ pain with abnormal labs, placental abruption concern, or maternal or fetal instability is an obstetric emergency.",
    examTraps: "Do not require proteinuria for preeclampsia with severe features. Postpartum patients remain at risk for preeclampsia or eclampsia even after an uncomplicated delivery.",
    sourceKeys: ["ACOG_HYPERTENSION_PREG_CURRENT"],
  },
  {
    slug: "gestational-diabetes",
    title: "Gestational Diabetes",
    bodySystem: "Reproductive",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "WHNP"],
    recognize: "Gestational diabetes is often asymptomatic and discovered through pregnancy screening. Risk is higher with prior GDM, obesity, family history, prior macrosomic infant, PCOS, and some higher-risk population backgrounds, but broad screening strategies are standard because risk factors miss cases.",
    diagnostics: "Screen at the recommended gestational window using the accepted one-step or two-step approach used by the practice system, with earlier testing when overt diabetes is suspected. After diagnosis, monitor glucose and fetal growth according to obstetric risk.",
    priorities: "Start with nutrition, activity, and glucose monitoring; add medication when targets are not met. Coordinate obstetric care, delivery planning, and postpartum diabetes screening because GDM predicts future type 2 diabetes.",
    medicationSafety: "Insulin is the preferred pharmacologic option in many U.S. pregnancy guidelines when medication is needed because it does not cross the placenta. Oral agents may be used in selected settings, but counseling should reflect placental transfer and local guideline preference.",
    redFlags: "Marked hyperglycemia with ketosis, severe vomiting or dehydration, hypertensive disease, decreased fetal movement, or other maternal or fetal instability needs urgent obstetric assessment.",
    examTraps: "Do not assume GDM ends all future risk at delivery. A normal postpartum glucose test does not eliminate the need for lifelong periodic diabetes screening.",
    sourceKeys: ["ADA_2026", "ACOG_GDM_CURRENT"],
  },
  {
    slug: "postpartum-complications",
    title: "Postpartum Complications",
    bodySystem: "Reproductive",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "WHNP", "ENP"],
    recognize: "Postpartum danger signs include heavy bleeding, severe headache or hypertension, fever, dyspnea or chest pain, unilateral leg swelling, wound pain or drainage, severe abdominal pain, and new severe mood or psychotic symptoms. The postpartum period remains medically high risk after discharge.",
    diagnostics: "Assess vitals, bleeding pattern, uterine tone or tenderness, incision or perineum, cardiopulmonary status, neurologic symptoms, and mental health. Testing follows the suspected complication: CBC, cultures, imaging, BP or preeclampsia labs, ECG, or VTE evaluation as indicated.",
    priorities: "Stabilize first and route rapidly to obstetric or emergency care for hemorrhage, sepsis, preeclampsia, cardiomyopathy, VTE, or acute psychiatric risk. Routine care should also address lactation, contraception, mood, sleep, social support, and chronic disease follow-up.",
    medicationSafety: "Medication choice must consider breastfeeding, hemorrhage risk, hypertension, renal or hepatic function, and drug interactions. Do not withhold necessary treatment solely because a patient is lactating when compatible alternatives exist.",
    redFlags: "Soaking bleeding with dizziness or syncope, severe headache or visual symptoms with high BP, chest pain or dyspnea, seizure, fever with toxicity, or suicidal or psychotic symptoms requires emergency evaluation.",
    examTraps: "Do not call severe postpartum symptoms 'normal recovery.' Postpartum preeclampsia, cardiomyopathy, VTE, and psychiatric emergencies can first present days to weeks after birth.",
    sourceKeys: ["ACOG_POSTPARTUM_CURRENT"],
  },
  {
    slug: "obsessive-compulsive-disorder",
    title: "Obsessive-Compulsive Disorder",
    bodySystem: "Psychiatric",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PMHNP", "PNP"],
    recognize: "OCD features intrusive, unwanted obsessions and/or repetitive compulsions performed to reduce distress or prevent feared outcomes, with significant time burden or impairment. Distinguish compulsions from pleasurable habits, psychosis, autism-related routines, and generalized worry.",
    diagnostics: "Diagnosis is clinical; quantify severity with a validated scale such as the Y-BOCS when useful. Assess insight, tic disorders, depression, suicide risk, substance use, and whether symptoms are better explained by another psychiatric or medical condition.",
    priorities: "Exposure and response prevention is first-line psychotherapy. SSRIs are common first-line medications and often require adequate dose and duration; refractory disease warrants specialty strategies rather than repeated short medication trials.",
    medicationSafety: "SSRIs carry activation, GI, sexual, interaction, and discontinuation risks. Clomipramine can be effective but has anticholinergic, cardiac, and overdose-toxicity concerns and is generally not the simplest first medication choice.",
    redFlags: "Severe self-neglect, inability to eat or drink because of compulsions, suicidality, psychosis, or dangerous compulsive behavior requires urgent psychiatric evaluation.",
    examTraps: "Do not reassure away obsessions or participate in compulsions as treatment. Intrusive violent or sexual thoughts in OCD are ego-dystonic and do not automatically mean intent to act.",
    sourceKeys: ["APA_OCD_CURRENT"],
  },
  {
    slug: "delirium-dementia",
    title: "Delirium vs Dementia",
    bodySystem: "Neurological",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PMHNP", "ENP"],
    recognize: "Delirium is acute, fluctuating inattention with altered cognition; dementia is usually chronic and progressive. A sudden behavior change in an older adult is delirium until a cause such as infection, medication toxicity, metabolic disturbance, pain, retention, hypoxia, or withdrawal is addressed.",
    diagnostics: "Use a bedside delirium tool plus collateral baseline history and focused neurologic or medical evaluation. Check medication changes, oxygenation, glucose, CBC or CMP or urinalysis only when clinically indicated, and investigate focal deficits or trauma appropriately.",
    priorities: "Treat the underlying cause, reorient, mobilize, normalize sleep or wake cues, provide glasses or hearing aids, manage pain, hydration, constipation, and urinary retention, and minimize restraints or catheters when possible.",
    medicationSafety: "Antipsychotics do not treat the cause of delirium and are reserved for selected severe agitation threatening safety after nonpharmacologic strategies. Avoid anticholinergic and sedative burden when possible.",
    redFlags: "New focal deficit, severe hypoxia, sepsis, hypoglycemia, head injury, seizure, meningismus, or dangerous agitation requires emergency evaluation.",
    examTraps: "Do not diagnose a UTI from asymptomatic bacteriuria just because an older adult is confused. A patient with dementia can still develop superimposed delirium.",
    sourceKeys: ["AGS_DELIRIUM_CURRENT", "APA_NEUROCOGNITIVE_CURRENT"],
  },
  {
    slug: "psychiatric-medication-emergencies",
    title: "Psychiatric Medication Emergencies",
    bodySystem: "Psychiatric",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGACNP", "PMHNP", "ENP"],
    recognize: "Think serotonin syndrome with clonus or hyperreflexia, autonomic instability, and serotonergic exposure; neuroleptic malignant syndrome with severe rigidity, fever, autonomic instability, and dopamine blockade; lithium toxicity with GI symptoms, tremor, ataxia, confusion, or seizures.",
    diagnostics: "Stop the suspected offending agent and assess ABCs, temperature, ECG, CK, renal function, electrolytes, drug levels when relevant, and co-ingestants. The diagnosis is clinical and treatment should not wait for every laboratory result.",
    priorities: "Provide emergency supportive care, aggressive temperature management when hyperthermic, IV fluids when indicated, and syndrome-specific therapy or toxicology consultation. Severe lithium toxicity may require hemodialysis based on level and clinical findings.",
    medicationSafety: "Avoid adding serotonergic drugs across multiple prescribers without interaction review. Lithium levels rise with dehydration and several common drugs including NSAIDs, ACEi or ARBs, and thiazides; antipsychotic dose changes can precipitate NMS.",
    redFlags: "Hyperthermia, severe rigidity, seizures, coma, marked autonomic instability, wide-complex arrhythmia, severe AKI, or rapidly worsening mental status requires emergency or critical care.",
    examTraps: "Do not confuse serotonin syndrome with NMS: clonus and hyperreflexia favor serotonin toxicity, while lead-pipe rigidity and slower evolution more strongly suggest NMS.",
    sourceKeys: ["APA_PSYCH_MED_EMERGENCIES_CURRENT", "ACMT_TOX_CURRENT"],
  },
  {
    slug: "personality-disorders",
    title: "Personality Disorders",
    bodySystem: "Psychiatric",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PMHNP"],
    recognize: "Personality disorders are enduring, inflexible patterns of inner experience and behavior that deviate from cultural expectations and cause impairment across contexts. Diagnose longitudinal patterns rather than labeling a patient during one crisis encounter.",
    diagnostics: "Assess trauma history, mood or anxiety disorders, substance use, neurodevelopmental conditions, psychosis, medical contributors, interpersonal patterns, self-harm history, and functional impairment. Collateral information can clarify chronicity.",
    priorities: "Psychotherapy is the core treatment. For borderline personality disorder, structured therapies such as DBT can reduce self-harm and improve function; medications target specific comorbid symptoms rather than 'curing' the personality disorder.",
    medicationSafety: "Avoid polypharmacy driven by rapidly shifting symptoms. Benzodiazepines may worsen disinhibition in some high-risk patients, and overdose lethality should influence dispensing decisions when self-harm risk is present.",
    redFlags: "Acute suicidal intent, severe self-injury, violence risk, psychosis, intoxication, or inability to maintain safety requires emergency assessment regardless of personality diagnosis.",
    examTraps: "Do not use stigmatizing labels to explain away genuine medical or psychiatric symptoms. A personality disorder does not make a patient's report unreliable by definition.",
    sourceKeys: ["APA_PERSONALITY_CURRENT"],
  },
  {
    slug: "perinatal-mental-health",
    title: "Perinatal Mood & Anxiety Disorders",
    bodySystem: "Psychiatric",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PMHNP", "WHNP"],
    recognize: "Depression, anxiety, OCD symptoms, trauma symptoms, and bipolar illness can emerge or worsen during pregnancy or postpartum. New decreased need for sleep, grandiosity, agitation, psychosis, or bizarre beliefs postpartum is a psychiatric emergency, not routine 'baby blues.'",
    diagnostics: "Screen during pregnancy and postpartum with validated tools, but follow positive screens with diagnostic assessment. Always ask about bipolar history, suicidality, intrusive thoughts, psychosis, substance use, sleep, supports, and infant safety.",
    priorities: "Mild to moderate illness may respond to psychotherapy; moderate to severe illness often needs medication plus therapy. Balance the known risks of untreated illness against medication risks and coordinate obstetric, psychiatric, and pediatric considerations.",
    medicationSafety: "Do not abruptly stop an effective psychiatric medication solely because pregnancy is discovered. Medication selection should use reproductive-safety data, prior response, illness severity, breastfeeding plans, and relapse risk.",
    redFlags: "Suicidal intent, psychosis, mania, inability to care for self or infant, command hallucinations, or thoughts of harming the infant with intent requires immediate emergency psychiatric care.",
    examTraps: "Postpartum psychosis is not postpartum depression with 'extra anxiety.' It is a time-sensitive emergency strongly associated with bipolar-spectrum illness and requires urgent specialist care.",
    sourceKeys: ["ACOG_PERINATAL_MH_CURRENT", "APA_PERINATAL_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
