import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch17 = [
  {
    slug: "epididymitis-orchitis",
    title: "Epididymitis & Orchitis",
    bodySystem: "Genitourinary",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PNP", "ENP"],
    recognize: "Gradual unilateral scrotal pain, epididymal tenderness/swelling, dysuria, urethral symptoms, or fever suggests epididymitis, but testicular torsion must be excluded first when pain is acute or the diagnosis is uncertain.",
    diagnostics: "Use focused genital exam, urinalysis/culture, and gonorrhea/chlamydia NAAT according to age and sexual risk. Scrotal Doppler ultrasound is most useful when torsion cannot be confidently excluded or the diagnosis is atypical.",
    priorities: "Treat likely STI-associated or enteric pathogens according to current guidance, provide scrotal support and analgesia, manage partners when STI is involved, and arrange follow-up if symptoms do not improve promptly.",
    medicationSafety: "Antibiotic selection changes with STI risk, urinary instrumentation, insertive anal sex, allergy, renal function and local resistance. Avoid fluoroquinolone monotherapy when gonorrhea remains plausible.",
    redFlags: "Sudden severe pain, high-riding testis, absent cremasteric reflex, severe systemic illness, abscess, Fournier gangrene, or failure to improve requires urgent urologic evaluation.",
    examTraps: "A positive Prehn sign does not safely rule out torsion. Do not delay surgical consultation for imaging when torsion is strongly suspected.",
    sourceKeys: ["CDC_STI_CURRENT", "AUA_SCROTAL_CURRENT"],
  },
  {
    slug: "testicular-torsion",
    title: "Testicular Torsion",
    bodySystem: "Genitourinary",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PNP", "ENP"],
    recognize: "Sudden severe unilateral scrotal pain, nausea or vomiting, high-riding or transverse testis, and absent cremasteric reflex is torsion until proven otherwise, especially in adolescents and young adults.",
    diagnostics: "Torsion is primarily a clinical emergency. Doppler ultrasound can confirm reduced flow when diagnosis is uncertain and imaging does not delay surgery; urinalysis or STI testing should not postpone urgent urologic action.",
    priorities: "Obtain immediate urologic consultation for detorsion and bilateral orchiopexy. Manual detorsion can be attempted while awaiting surgery when expertise is available, but successful pain relief does not eliminate the need for operative fixation.",
    medicationSafety: "Analgesia and antiemetics should be given without delaying definitive care. Antibiotics are not treatment for torsion unless a separate infection exists.",
    redFlags: "Any high-probability torsion presentation is itself a time-critical emergency because testicular viability falls as ischemia continues.",
    examTraps: "Do not wait for ultrasound when the exam is classic and surgical access is available. Epididymitis is more gradual and inflammatory, but age alone cannot safely distinguish the two.",
    sourceKeys: ["AUA_TORSION_CURRENT"],
  },
  {
    slug: "testicular-cancer",
    title: "Testicular Cancer",
    bodySystem: "Oncology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "A painless firm intratesticular mass, heaviness, dull ache, gynecomastia, or persistent testicular enlargement in a young or middle-aged adult should be considered malignant until evaluated.",
    diagnostics: "Order scrotal ultrasound and serum AFP, beta-hCG and LDH when cancer is suspected. Do not perform transscrotal needle biopsy; urologic radical inguinal orchiectomy provides diagnosis and local treatment.",
    priorities: "Refer urgently to urology, complete staging imaging and tumor markers, discuss fertility preservation before chemotherapy or radiation when relevant, and coordinate surveillance or adjuvant therapy by tumor type and stage.",
    medicationSafety: "Bleomycin, cisplatin and other chemotherapy agents have pulmonary, renal, ototoxic, marrow and fertility implications. Document baseline risks before oncology therapy.",
    redFlags: "Acute dyspnea or neurologic symptoms from metastatic disease, severe tumor-related pain, or a rapidly enlarging mass requires expedited oncology/urology evaluation.",
    examTraps: "Do not treat a persistent solid intratesticular mass as epididymitis without imaging. Testicular cancer often presents without pain and is highly curable when managed promptly.",
    sourceKeys: ["NCCN_TESTICULAR_CURRENT", "AUA_TESTICULAR_CURRENT"],
  },
  {
    slug: "male-hypogonadism",
    title: "Male Hypogonadism",
    bodySystem: "Endocrine",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "Low libido, erectile dysfunction, infertility, reduced spontaneous erections, low bone density, anemia, decreased body hair, or loss of muscle mass may reflect testosterone deficiency but are nonspecific.",
    diagnostics: "Diagnose only when compatible symptoms coexist with consistently low morning testosterone on repeat testing. Use LH/FSH, prolactin and targeted pituitary or genetic evaluation to distinguish primary from secondary causes.",
    priorities: "Treat reversible contributors such as obesity, severe sleep apnea, opioids or hyperprolactinemia when possible. Testosterone therapy is for selected symptomatic patients after fertility goals, prostate risk, hematocrit and cardiovascular context are reviewed.",
    medicationSafety: "Exogenous testosterone suppresses spermatogenesis and can raise hematocrit, worsen acne/edema and complicate untreated severe sleep apnea. Monitor testosterone response, hematocrit and prostate-related parameters according to age and risk.",
    redFlags: "Pituitary mass symptoms, severe headache/visual field loss, markedly elevated prolactin, testicular mass, or symptomatic polycythemia requires prompt specialty evaluation.",
    examTraps: "Do not prescribe testosterone for one low afternoon value or nonspecific fatigue. Testosterone is inappropriate when the patient is actively trying to preserve fertility.",
    sourceKeys: ["ENDOCRINE_TESTOSTERONE_CURRENT", "AUA_TESTOSTERONE_CURRENT"],
  },
  {
    slug: "overactive-bladder",
    title: "Overactive Bladder",
    bodySystem: "Genitourinary",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "WHNP"],
    recognize: "Urinary urgency with or without urge incontinence, usually with frequency and nocturia, suggests overactive bladder after infection, retention, polyuria and structural causes are excluded.",
    diagnostics: "Use history, voiding diary, urinalysis and focused pelvic or neurologic exam. Measure post-void residual when retention risk exists; urodynamics, cystoscopy and imaging are not routine in uncomplicated initial evaluation.",
    priorities: "Start bladder training, timed voiding, fluid/caffeine modification and pelvic-floor therapy; add medication when symptoms remain bothersome and consider specialist procedures for refractory disease.",
    medicationSafety: "Antimuscarinics can worsen constipation, dry mouth, cognitive burden and retention; beta-3 agonists can raise BP in some patients and have interaction considerations. Review total anticholinergic load in older adults.",
    redFlags: "Gross hematuria, recurrent febrile UTI, neurologic deficit, high residuals, pelvic mass, severe pain, or renal dysfunction requires further evaluation rather than routine OAB treatment.",
    examTraps: "Do not prescribe anticholinergic therapy before checking for retention when symptoms suggest incomplete emptying. Urgency alone is not a UTI.",
    sourceKeys: ["AUA_SUFU_OAB_CURRENT"],
  },
  {
    slug: "urinary-incontinence",
    title: "Urinary Incontinence",
    bodySystem: "Genitourinary",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "WHNP"],
    recognize: "Stress leakage occurs with cough/exertion, urge leakage follows sudden urgency, overflow is associated with incomplete emptying, and functional incontinence reflects mobility or cognitive barriers. Mixed patterns are common.",
    diagnostics: "Use history, bladder diary, urinalysis, medication review, pelvic/neurologic exam and post-void residual when overflow is possible. Cough stress testing and specialist urodynamics are selective.",
    priorities: "Treat reversible contributors, use pelvic-floor muscle therapy for stress/mixed disease, bladder training for urgency, and refer for pessary or surgical options when symptoms remain bothersome or anatomy is complex.",
    medicationSafety: "Antimuscarinics are not treatment for pure stress incontinence and can worsen cognitive burden/retention. SNRIs are not universally used or approved for stress incontinence in the U.S.; match therapy to subtype.",
    redFlags: "New saddle anesthesia, leg weakness, severe retention, gross hematuria, recurrent upper-tract infection, or pelvic mass requires urgent or specialty evaluation.",
    examTraps: "Do not label overflow leakage as overactive bladder without measuring residual when retention is plausible. Pads alone are not a treatment plan when reversible causes exist.",
    sourceKeys: ["AUA_SUFU_INCONTINENCE_CURRENT"],
  },
  {
    slug: "bladder-cancer",
    title: "Bladder Cancer Recognition",
    bodySystem: "Oncology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "Painless gross hematuria is the classic warning sign; persistent microscopic hematuria, irritative urinary symptoms without infection, smoking, aromatic-amine exposure, or prior pelvic radiation increases concern.",
    diagnostics: "Risk-stratify hematuria and use cystoscopy plus appropriate upper-tract imaging when indicated. Urine cytology is selective and does not replace cystoscopy for most high-risk evaluations.",
    priorities: "Refer promptly to urology for suspicious hematuria or lesions. Treatment and surveillance depend on non-muscle-invasive versus muscle-invasive stage, grade, CIS and recurrence risk.",
    medicationSafety: "Intravesical BCG and systemic cancer therapies have infectious, immune and organ-specific risks that require oncology/urology protocols. Anticoagulants can exacerbate visible bleeding but should not be accepted as the sole explanation.",
    redFlags: "Clot retention, obstructive renal failure, severe ongoing bleeding, symptomatic anemia, or metastatic bone/neurologic symptoms requires urgent care.",
    examTraps: "Do not assume painless blood is benign or a UTI in a smoker. A single negative urine cytology does not rule out bladder malignancy.",
    sourceKeys: ["AUA_BLADDER_CANCER_CURRENT", "AUA_MICROHEMATURIA_CURRENT"],
  },
  {
    slug: "male-infertility",
    title: "Male Infertility Evaluation",
    bodySystem: "Reproductive",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "Male factors contribute substantially to infertility and should be assessed in parallel with the female partner. Ask puberty, infections, cryptorchidism, testicular trauma, surgery, heat/toxin exposure, anabolic steroids, testosterone, medications and sexual function.",
    diagnostics: "Obtain semen analysis early and repeat abnormal results according to guideline strategy. Hormonal testing is targeted to abnormal semen parameters, low libido, erectile symptoms, small testes or endocrine clues; genetic testing is indicated in selected severe oligospermia/azoospermia.",
    priorities: "Correct reversible exposures and medication causes, treat selected endocrine or anatomic disease, and refer abnormal semen studies or azoospermia to male-reproductive urology for assisted-reproduction planning.",
    medicationSafety: "Exogenous testosterone suppresses LH/FSH and sperm production and should not be prescribed to men seeking fertility. Avoid unproven supplements that delay definitive evaluation.",
    redFlags: "Testicular mass, severe endocrine symptoms, pituitary visual symptoms, or acute scrotal pain requires expedited evaluation unrelated to routine infertility timelines.",
    examTraps: "Do not complete months of female-only testing before obtaining a semen analysis. A normal testosterone level does not prove normal spermatogenesis.",
    sourceKeys: ["AUA_ASRM_MALE_INFERTILITY_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
