import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch55 = [
  {
    slug: "secondary-amenorrhea-evaluation",
    title: "Secondary Amenorrhea Evaluation",
    bodySystem: "Reproductive",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "WHNP"],
    recognize: "Loss of previously established menses can result from pregnancy, hypothalamic energy/stress suppression, PCOS, hyperprolactinemia, thyroid disease, primary ovarian insufficiency, intrauterine adhesions or other endocrine disease. Weight change, exercise, galactorrhea, androgen symptoms, hot flashes and medication history localize the cause.",
    diagnostics: "Check pregnancy first, then TSH, prolactin and FSH/estradiol or androgen testing according to phenotype; pelvic ultrasound evaluates anatomy/ovaries/endometrium when indicated. Avoid using an old 'progestin challenge' as a stand-alone diagnostic algorithm when direct hormone and imaging data are available.",
    priorities: "Treat the cause and protect bone/endometrium/fertility: restore energy availability for hypothalamic amenorrhea, provide cycle/endometrial protection for chronic anovulation, manage prolactinoma/thyroid disease and evaluate premature ovarian insufficiency for hormone-replacement and genetic/autoimmune implications.",
    medicationSafety: "Combined hormonal therapy can provide endometrial protection but may mask return of spontaneous hypothalamic cycles; estrogen is not a substitute for nutritional recovery in functional hypothalamic amenorrhea. Dopamine agonists and hormone therapy have pregnancy/interaction risks.",
    redFlags: "Positive pregnancy with pain/bleeding, severe headache/visual change, rapid virilization, severe eating disorder/bradycardia or ovarian failure at a very young age requires urgent/expedited evaluation.",
    examTraps: "Do not diagnose PCOS simply because a patient has amenorrhea and acne, and do not forget pregnancy even when contraception is reportedly used.",
    sourceKeys: ["ASRM_AMENORRHEA_CURRENT", "ENDOCRINE_FHA_CURRENT"],
  },
  {
    slug: "hirsutism-virilization-evaluation",
    title: "Hirsutism & Virilization Evaluation",
    bodySystem: "Reproductive",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "WHNP"],
    recognize: "Gradual terminal hair growth with irregular menses commonly reflects PCOS or idiopathic hirsutism; rapid progression, deepening voice, clitoromegaly, severe temporal balding or marked muscle change suggests a high-androgen ovarian/adrenal source that needs urgent evaluation.",
    diagnostics: "Measure total testosterone with a reliable assay and add free testosterone, DHEAS, 17-hydroxyprogesterone or cortisol testing according to severity/phenotype; evaluate pregnancy/TSH/prolactin when cycles are abnormal. Image ovaries/adrenals when biochemical or clinical virilization suggests tumor rather than ordering imaging for mild stable hirsutism.",
    priorities: "Treat the cause, use combined hormonal contraception as common first-line pharmacologic treatment when pregnancy is not desired, then add an antiandrogen such as spironolactone after adequate contraception if response is insufficient; cosmetic hair removal is an important parallel treatment.",
    medicationSafety: "Spironolactone can cause hyperkalemia and is antiandrogenic to a male fetus, so effective contraception is essential. Finasteride also requires pregnancy avoidance; antiandrogens take months to change hair growth and do not remove existing hair.",
    redFlags: "Rapid virilization, very high testosterone/DHEAS, pelvic/adrenal mass symptoms or Cushing syndrome features requires expedited endocrine/gynecologic evaluation.",
    examTraps: "Hair removal does not treat androgen excess and a normal ovarian ultrasound does not exclude PCOS. Do not delay tumor evaluation because the patient is young.",
    sourceKeys: ["ENDOCRINE_HIRSUTISM_CURRENT", "PCOS_INTERNATIONAL_2023"],
  },
  {
    slug: "breast-mass-evaluation",
    title: "Breast Mass & Nipple Discharge Evaluation",
    bodySystem: "Reproductive",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "WHNP"],
    recognize: "A new palpable breast mass, focal skin/nipple retraction, spontaneous unilateral bloody/serous single-duct discharge or inflammatory breast change requires diagnostic evaluation. Cyclic diffuse tenderness and bilateral multiduct milky discharge follow different pathways.",
    diagnostics: "Use age- and presentation-appropriate diagnostic mammography and/or ultrasound rather than screening mammography for an active mass. Ensure triple concordance among clinical exam, imaging and pathology; persistent clinically suspicious findings may need biopsy even when initial imaging is benign.",
    priorities: "Biopsy BI-RADS suspicious lesions with image-guided core technique when feasible and refer cancer-suspicious or discordant findings promptly. Evaluate physiologic galactorrhea separately with pregnancy/prolactin/thyroid/medication review.",
    medicationSafety: "Do not stop necessary anticoagulation automatically before percutaneous biopsy without procedural risk review; avoid repeated empiric antibiotics for an inflammatory mass that fails to resolve because inflammatory breast cancer can mimic mastitis.",
    redFlags: "Peau d'orange, fixed hard mass, bloody spontaneous discharge, rapidly progressive inflammatory breast change, palpable nodes or nonlactational 'mastitis' not improving requires expedited breast-specialist evaluation.",
    examTraps: "A normal screening mammogram does not close the evaluation of a persistent palpable mass and pain alone is rarely the only presentation of breast cancer but still requires focal assessment when persistent.",
    sourceKeys: ["ACR_PALPABLE_BREAST_MASS_CURRENT", "NCCN_BREAST_DIAGNOSIS_CURRENT"],
  },
  {
    slug: "cervical-screening-abnormal-results",
    title: "Cervical Cancer Screening & Abnormal Result Management",
    bodySystem: "Reproductive",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "WHNP"],
    recognize: "Cervical screening applies to asymptomatic patients with a cervix; abnormal bleeding, visible cervical lesion or symptoms require diagnostic evaluation regardless of routine screening interval. HPV persistence, immunocompromise and prior high-grade disease alter risk and follow-up.",
    diagnostics: "Use current age/risk-appropriate primary HPV, cotesting or cytology strategies and manage abnormal results with ASCCP risk-based thresholds based on current result plus prior history—not memorized one-result algorithms. Pregnancy and immunosuppression modify management.",
    priorities: "Ensure abnormal results complete the colposcopy/surveillance/treatment pathway, use excisional treatment for appropriate high-risk precancer and continue prolonged surveillance after CIN2/3/AIS treatment according to current guidance. Vaccinate against HPV even after prior infection when age/indication supports benefit.",
    medicationSafety: "No medication clears HPV. Avoid unnecessary antibiotics or 'immune supplements'; excisional procedures carry bleeding, cervical stenosis and future obstetric risks that must be balanced against cancer prevention.",
    redFlags: "Visible friable cervical mass, postcoital/postmenopausal bleeding, high-grade cytology with poor follow-up or invasive-cancer concern requires expedited gynecologic oncology evaluation.",
    examTraps: "A normal Pap does not explain symptomatic bleeding, and prior hysterectomy does not automatically end screening if the cervix remains or there is relevant high-grade history.",
    sourceKeys: ["ASCCP_RISK_BASED_CURRENT", "ACOG_CERVICAL_CURRENT"],
  },
  {
    slug: "female-urinary-incontinence",
    title: "Female Urinary Incontinence",
    bodySystem: "Reproductive",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "WHNP"],
    recognize: "Stress incontinence leaks with cough/exertion, urgency incontinence follows sudden compelling urge, mixed combines both and overflow suggests retention. Vaginal prolapse, UTI, constipation, diabetes, neurologic disease, diuretics and genitourinary syndrome can contribute.",
    diagnostics: "Use bladder history/diary, urinalysis, pelvic exam and cough stress test; measure post-void residual when retention/overflow or voiding dysfunction is possible. Urodynamics and imaging are reserved for complex/refractory or preoperative cases rather than routine uncomplicated evaluation.",
    priorities: "Pelvic-floor muscle training and bladder strategies are first-line; treat GSM/constipation and adjust contributors. Use beta-3 agonist or antimuscarinic for overactive bladder according to risk, and consider pessary/urethral bulking/sling surgery for bothersome stress incontinence after counseling.",
    medicationSafety: "Antimuscarinics increase dry mouth, constipation, retention and cognitive burden; beta-3 agonists can raise BP depending on agent. Vaginal estrogen improves GSM-related urinary symptoms in selected patients but is not systemic estrogen therapy.",
    redFlags: "Gross hematuria, recurrent febrile UTI, high residual/renal dysfunction, new neurologic deficit or pelvic mass requires expanded evaluation.",
    examTraps: "Do not prescribe antimuscarinic therapy before checking retention risk when voiding is difficult, and do not assume every older woman's leakage is 'normal aging.'",
    sourceKeys: ["AUA_SUO_OAB_CURRENT", "AUGS_SUI_CURRENT"],
  },
  {
    slug: "genitourinary-syndrome-menopause",
    title: "Genitourinary Syndrome of Menopause",
    bodySystem: "Reproductive",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "WHNP"],
    recognize: "Low estrogen after menopause can cause vaginal dryness/burning, dyspareunia, urinary urgency/dysuria and recurrent UTI with pale thin tissue and elevated vaginal pH. Symptoms are chronic/progressive without treatment and can be mistaken for repeated infection.",
    diagnostics: "Diagnosis is usually clinical after excluding infection, dermatosis, vulvodynia and malignancy; obtain UA/culture or vaginal testing when symptoms make infection plausible. Postmenopausal bleeding is not a routine GSM symptom and requires separate endometrial/cervical evaluation.",
    priorities: "Use moisturizers/lubricants for mild symptoms and low-dose vaginal estrogen, vaginal DHEA or other approved therapy for persistent GSM according to patient preference/risk. Vaginal estrogen can also reduce recurrent UTI in appropriate hypoestrogenic patients.",
    medicationSafety: "Low-dose vaginal estrogen has minimal systemic absorption and usually does not require a progestogen for endometrial protection, but patients with estrogen-sensitive cancer require individualized shared decision with oncology. Systemic estrogen is unnecessary when symptoms are isolated to GSM.",
    redFlags: "Postmenopausal bleeding, vulvar lesion, recurrent culture-negative severe pain or pelvic mass requires diagnostic evaluation rather than escalating vaginal hormone blindly.",
    examTraps: "Do not repeatedly treat GSM dysuria as UTI without cultures, and do not assume vaginal estrogen has the same systemic risk profile as full-dose systemic MHT.",
    sourceKeys: ["NAMS_GSM_CURRENT", "ACOG_GSM_BREAST_CANCER_CURRENT"],
  },
  {
    slug: "chronic-pelvic-pain",
    title: "Chronic Pelvic Pain",
    bodySystem: "Reproductive",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "WHNP"],
    recognize: "Chronic pelvic pain is often multifactorial and may combine endometriosis, pelvic-floor myalgia, bladder pain syndrome, IBS, adhesions, neuropathic pain and trauma/central sensitization. A normal ultrasound does not mean the pain is psychogenic.",
    diagnostics: "Map pain timing/triggers, bowel/bladder/sexual symptoms, trauma and prior surgery; perform targeted abdominal/pelvic and pelvic-floor exam. Use pregnancy/STI testing, ultrasound, GI/urologic studies or laparoscopy only when the phenotype indicates them rather than ordering serial low-yield imaging.",
    priorities: "Treat identified contributors with pelvic-floor PT, endometriosis suppression, bladder/GI therapy and behavioral/neuropathic pain strategies; coordinate multidisciplinary care and functional goals. Surgery is reserved for a defined structural target and should not be promised as a universal cure.",
    medicationSafety: "Avoid chronic opioids as a primary chronic-pelvic-pain strategy; gabapentinoids/antidepressants have sedation and other adverse effects and should be continued only when functional benefit is clear. Hormonal therapy follows contraception/thrombotic risks.",
    redFlags: "Pregnancy with pain, acute torsion/rupture pattern, fever/peritonitis, rapidly growing mass, postmenopausal bleeding or severe unexplained weight loss requires urgent evaluation.",
    examTraps: "Do not repeat antibiotics for culture-negative pain or perform hysterectomy solely because pain is chronic without a clear uterine pain generator and informed counseling.",
    sourceKeys: ["ACOG_CHRONIC_PELVIC_PAIN_CURRENT"],
  },
  {
    slug: "female-sexual-dysfunction",
    title: "Female Sexual Dysfunction & Dyspareunia",
    bodySystem: "Reproductive",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "WHNP", "PMHNP"],
    recognize: "Low desire, arousal/orgasm difficulty and pain can arise from GSM, pelvic-floor dysfunction, vulvodynia, endometriosis, relationship/trauma factors, depression/anxiety, medications and chronic disease. Distress and patient-defined impairment are essential; low desire without distress is not automatically a disorder.",
    diagnostics: "Use a sensitive biopsychosocial/sexual history and targeted genital/pelvic exam for pain; review SSRIs, antihypertensives, hormonal changes and partner/context. Test infection/endocrine disease only when indicated—routine testosterone levels do not diagnose hypoactive sexual desire disorder.",
    priorities: "Treat pain/GSM/pelvic-floor disease, optimize relationship/psychological factors and adjust culprit drugs when safe; sex therapy/CBT and pelvic-floor PT are often high-value. FDA-approved desire medications apply to specific populations and require careful contraindication counseling.",
    medicationSafety: "Flibanserin and bremelanotide have significant hypotension/nausea and interaction/administration considerations; compounded testosterone products are not automatically appropriate. When testosterone is considered for selected postmenopausal HSDD, use specialist evidence-based dosing and monitor for androgen excess.",
    redFlags: "Genital lesion, bleeding, severe trauma-related distress, coercion/violence, acute pelvic infection or new neurologic sensory loss requires targeted urgent evaluation.",
    examTraps: "Do not reduce sexual symptoms to hormone levels or prescribe testosterone for every low-libido complaint. Pain with intercourse requires physical as well as psychological assessment.",
    sourceKeys: ["ISSWSH_HSDD_CURRENT", "ACOG_SEXUAL_HEALTH_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
