import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch27 = [
  {
    slug: "increased-intracranial-pressure",
    title: "Increased Intracranial Pressure",
    titleAliases: ["ICP: Cerebral Perfusion Pressure"],
    slugAliases: ["increased-icp-np"],
    bodySystem: "Neurological",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Headache, vomiting, declining consciousness, pupillary asymmetry, focal deficit, seizures or posturing in a patient with trauma, hemorrhage, tumor, hydrocephalus or CNS infection suggests intracranial hypertension; Cushing physiology is late and ominous.",
    diagnostics: "Obtain urgent neuroimaging and serial neurologic exams; use invasive ICP monitoring in selected severe brain injury or neurocritical disease. Track oxygenation, ventilation, sodium/osmolality and hemodynamics because cerebral perfusion depends on both ICP and MAP.",
    priorities: "Secure airway/oxygenation, elevate the head about 30 degrees with neutral neck alignment, treat fever/seizure/agitation, use hyperosmolar therapy for acute crises, drain CSF when indicated and involve neurosurgery/neurocritical care early.",
    medicationSafety: "Hypertonic saline can cause hypernatremia/volume issues; mannitol can worsen hypotension and renal injury. Prolonged prophylactic hyperventilation can reduce cerebral blood flow and is reserved as a temporary bridge for impending herniation.",
    redFlags: "Rapid GCS decline, unilateral fixed pupil, extensor posturing, refractory ICP, apnea, Cushing response or imaging evidence of herniation requires immediate neurocritical/neurosurgical intervention.",
    examTraps: "Do not wait for papilledema or Cushing triad before acting. A normal early CT does not eliminate evolving intracranial pathology after high-risk injury.",
    sourceKeys: ["BTF_SEVERE_TBI_CURRENT", "AHA_NEUROCRITICAL_CURRENT"],
  },
  {
    slug: "tumor-lysis-syndrome",
    title: "Tumor Lysis Syndrome",
    titleAliases: ["Tumor Lysis Syndrome: Uric Acid Crisis"],
    slugAliases: ["tumor-lysis-np"],
    bodySystem: "Oncology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Rapid malignant-cell breakdown can produce hyperkalemia, hyperphosphatemia, secondary hypocalcemia, hyperuricemia and AKI, especially after treatment of high-burden hematologic malignancy; spontaneous TLS also occurs.",
    diagnostics: "Risk-stratify before cytotoxic therapy and serially monitor potassium, phosphate, calcium, uric acid, creatinine, LDH and ECG during the high-risk window. Clinical TLS includes metabolic abnormalities plus kidney, seizure, arrhythmic or other end-organ complications.",
    priorities: "Start vigorous IV hydration when appropriate, use allopurinol for prevention in selected risk and rasburicase for high-risk or established hyperuricemia, treat hyperkalemia urgently and involve nephrology early when kidney failure or severe electrolyte burden emerges.",
    medicationSafety: "Rasburicase is contraindicated in G6PD deficiency because of hemolysis/methemoglobinemia risk. Do not routinely alkalinize urine because calcium-phosphate precipitation can worsen renal injury.",
    redFlags: "ECG changes, severe hyperkalemia, seizure, symptomatic hypocalcemia, oliguric AKI, severe hyperphosphatemia or arrhythmia requires emergency monitored management and possible dialysis.",
    examTraps: "Allopurinol prevents new uric acid formation but does not rapidly remove existing uric acid. A normal pretreatment uric acid does not eliminate TLS risk in a high-burden rapidly responsive tumor.",
    sourceKeys: ["ASCO_TLS_CURRENT", "NCCN_TLS_CURRENT"],
  },
  {
    slug: "hellp-syndrome",
    title: "HELLP Syndrome",
    titleAliases: ["HELLP Syndrome: Hepatic Cascade"],
    slugAliases: ["hellp-syndrome-np"],
    bodySystem: "Reproductive",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "WHNP", "AGACNP", "ENP"],
    recognize: "Hemolysis, elevated liver enzymes and thrombocytopenia in pregnancy or postpartum—often with RUQ/epigastric pain, nausea, headache or hypertension—suggests HELLP, which can occur even when classic proteinuria or severe hypertension is not prominent.",
    diagnostics: "Trend CBC/platelets, peripheral smear or hemolysis markers, AST/ALT, bilirubin, creatinine and coagulation/fibrinogen when DIC is possible. Persistent severe RUQ pain or hemodynamic change warrants hepatic imaging for hematoma/rupture.",
    priorities: "Stabilize maternal BP, give magnesium sulfate for seizure prophylaxis when indicated, manage blood products/coagulopathy, involve maternal-fetal medicine and proceed with delivery according to maternal stabilization and gestational context because definitive treatment is delivery.",
    medicationSafety: "Magnesium toxicity risk increases with renal impairment and requires respiratory/reflex/urine-output monitoring. Corticosteroids for fetal maturation are distinct from unproven routine high-dose steroid use solely to normalize maternal platelets.",
    redFlags: "DIC, hepatic hematoma/rupture, severe hypertension, eclampsia, pulmonary edema, AKI, placental abruption or hemodynamic instability requires emergency obstetric critical care.",
    examTraps: "Do not require all three laboratory components to be profoundly abnormal before recognizing evolving HELLP. Postpartum deterioration can occur after delivery and still requires close monitoring.",
    sourceKeys: ["ACOG_PREECLAMPSIA_CURRENT", "SMFM_HELLP_CURRENT"],
  },
  {
    slug: "amniotic-fluid-embolism",
    title: "Amniotic Fluid Embolism",
    titleAliases: ["Amniotic Fluid Embolism: DIC Pathway"],
    slugAliases: ["amniotic-fluid-embolism-np"],
    bodySystem: "Reproductive",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "WHNP", "AGACNP", "ENP"],
    recognize: "Sudden hypoxemia, hypotension/cardiovascular collapse, seizure or cardiac arrest during labor or shortly after delivery followed by severe coagulopathy should trigger concern for amniotic fluid embolism after other causes are rapidly considered.",
    diagnostics: "AFE is a clinical diagnosis of exclusion without a definitive bedside test. Use ECG/echo, ABG, CBC, coagulation/fibrinogen, lactate and targeted imaging to assess cardiopulmonary failure and DIC while evaluating PE, hemorrhage, anaphylaxis, sepsis and eclampsia.",
    priorities: "Initiate immediate high-quality maternal resuscitation, oxygenation/ventilation, vasopressor/inotropic support and aggressive hemorrhage/DIC treatment; activate obstetric, anesthesia, critical-care, transfusion and neonatal teams simultaneously.",
    medicationSafety: "Treat cardiac arrest and shock with standard evidence-based resuscitation drugs; replace fibrinogen/blood components based on hemorrhage and coagulation needs. Do not substitute anecdotal drug bundles for established resuscitation and hemorrhage care.",
    redFlags: "Cardiac arrest, refractory hypoxemia, right- or left-heart failure, massive hemorrhage, DIC or multiorgan failure requires immediate ICU/ECMO-capable tertiary care when available.",
    examTraps: "AFE is not diagnosed by finding fetal cells in maternal blood and not every intrapartum collapse is AFE. Management is supportive resuscitation—there is no specific antidote.",
    sourceKeys: ["SMFM_AFE_CURRENT", "ACOG_OBSTETRIC_EMERGENCY_CURRENT"],
  },
  {
    slug: "obstetric-hemorrhage",
    title: "Obstetric Hemorrhage",
    titleAliases: ["Obstetric Hemorrhage: Massive Transfusion"],
    slugAliases: ["obstetric-hemorrhage-np"],
    bodySystem: "Reproductive",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "WHNP", "AGACNP", "ENP"],
    recognize: "Postpartum hemorrhage is cumulative blood loss of at least 1000 mL or blood loss with hypovolemia within 24 hours; uterine atony, trauma, retained tissue and coagulopathy are the major mechanisms, and vital signs can lag behind major loss.",
    diagnostics: "Quantify blood loss, repeatedly assess uterine tone and genital tract, and trend CBC, fibrinogen/coagulation, type/cross, lactate and hemodynamics. Ultrasound can help identify retained tissue but treatment should not wait in unstable hemorrhage.",
    priorities: "Activate hemorrhage protocol, uterine massage and oxytocin for atony, add cause-appropriate uterotonics, give tranexamic acid early when indicated, replace blood/fibrinogen and escalate to tamponade, embolization or surgery when bleeding persists.",
    medicationSafety: "Methylergonovine is avoided in severe hypertension; carboprost is avoided or used with extreme caution in asthma; tranexamic acid is most useful early and requires thrombosis-context review without delaying lifesaving treatment.",
    redFlags: "Shock, rapidly ongoing blood loss, fibrinogen depletion/DIC, uterine inversion/rupture, placenta accreta spectrum or failure of medical/tamponade control requires immediate operative/interventional escalation.",
    examTraps: "Do not depend on visual estimation or wait for hypotension before activating a hemorrhage response. A firm uterus with continued bleeding should redirect the differential toward trauma/coagulopathy rather than more uterotonics alone.",
    sourceKeys: ["ACOG_PPH_CURRENT", "ACOG_PPH_UPDATE_2025"],
  },
  {
    slug: "neonatal-respiratory-distress-syndrome",
    title: "Neonatal Respiratory Distress Syndrome",
    titleAliases: ["RDS: Surfactant Physiology"],
    slugAliases: ["neonatal-rds-np"],
    bodySystem: "Pediatrics",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PNP", "ENP"],
    recognize: "Premature infants with early grunting, retractions, tachypnea, oxygen need and diffuse low-volume ground-glass lung disease may have surfactant-deficient RDS; infection, TTN, pneumothorax and congenital heart disease remain competing diagnoses.",
    diagnostics: "Use gestational age/risk plus respiratory exam, pulse oximetry/ABG and chest radiography while screening for infection and structural disease as indicated. Escalating oxygen/ventilation need helps determine surfactant and respiratory-support strategy.",
    priorities: "Use antenatal corticosteroid prevention when preterm delivery is expected, early CPAP for appropriate spontaneously breathing preterm infants, rescue surfactant when indicated and lung-protective ventilation if noninvasive support fails.",
    medicationSafety: "Surfactant administration can transiently obstruct the airway or cause desaturation/bradycardia and requires experienced neonatal staff. Avoid excessive oxygen exposure because hyperoxia contributes to retinopathy and lung injury.",
    redFlags: "Rapid oxygen escalation, severe apnea, pneumothorax/air leak, shock, severe respiratory acidosis or failure of noninvasive support requires NICU-level escalation.",
    examTraps: "Do not intubate every preterm infant solely to give prophylactic surfactant when effective noninvasive pathways are appropriate. RDS typically presents early after birth rather than as a late isolated oxygen requirement.",
    sourceKeys: ["AAP_SURFACTANT_CURRENT", "NRP_CURRENT"],
  },
  {
    slug: "neonatal-hypoxic-ischemic-encephalopathy",
    title: "Neonatal Hypoxic-Ischemic Encephalopathy",
    titleAliases: ["HIE: Therapeutic Hypothermia"],
    slugAliases: ["neonatal-hie-np"],
    bodySystem: "Pediatrics",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PNP", "ENP"],
    recognize: "Following significant perinatal hypoxia-ischemia, altered consciousness, abnormal tone/reflexes, poor feeding, respiratory depression or seizures may indicate HIE; metabolic, infectious, stroke and genetic causes of neonatal encephalopathy must also be considered.",
    diagnostics: "Assess cord/early blood gas and resuscitation history, standardized neurologic exam, continuous or amplitude-integrated EEG for seizures, multiorgan labs and MRI for injury pattern/prognosis. Determine eligibility for therapeutic hypothermia immediately.",
    priorities: "For eligible infants with moderate-to-severe HIE born at appropriate gestation, initiate whole-body cooling to protocol targets as soon as possible within 6 hours and continue 72 hours, with controlled rewarming and NICU neurologic/supportive care.",
    medicationSafety: "Cooling alters drug clearance and can cause bradycardia, coagulopathy and electrolyte disturbances; antiseizure and sedative therapy requires neonatal dosing and monitoring. Passive uncontrolled overcooling during transport is unsafe.",
    redFlags: "Refractory seizures, severe encephalopathy, persistent pulmonary hypertension, shock, multiorgan failure or inability to initiate indicated cooling within the therapeutic window requires urgent tertiary neonatal transfer.",
    examTraps: "Therapeutic hypothermia is not for every infant with low Apgar scores; eligibility includes gestational, biochemical/resuscitation and neurologic criteria. Cooling after a missed window should not be improvised outside specialist protocols.",
    sourceKeys: ["AAP_HIE_2026"],
  },
  {
    slug: "persistent-pulmonary-hypertension-newborn",
    title: "Persistent Pulmonary Hypertension of the Newborn",
    titleAliases: ["PPHN: Pulmonary Vascular Resistance"],
    slugAliases: ["pphn-np"],
    bodySystem: "Pediatrics",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PNP", "ENP"],
    recognize: "Severe hypoxemia with labile oxygen saturation and preductal-postductal differences in a term/late-preterm newborn can reflect failure of normal pulmonary vascular transition with right-to-left shunting.",
    diagnostics: "Use pre/postductal oximetry, ABG, chest imaging and urgent echocardiography to confirm pulmonary hypertension/shunt direction and exclude congenital heart disease, ventricular dysfunction and pulmonary venous hypertension before targeted vasodilation.",
    priorities: "Optimize lung recruitment, oxygenation, temperature, acid-base status and systemic perfusion; treat underlying lung disease, use inhaled nitric oxide in appropriate near-term/term hypoxic respiratory failure and escalate to ECMO-capable care when refractory.",
    medicationSafety: "Inhaled nitric oxide must be weaned gradually to avoid rebound pulmonary hypertension and can cause methemoglobinemia. Pulmonary vasodilators can worsen physiology when LV dysfunction or ductal-dependent systemic circulation is present.",
    redFlags: "Refractory hypoxemia, shock, severe RV failure, rising oxygenation index or congenital-heart physiology that makes pulmonary vasodilation hazardous requires immediate neonatology/cardiology/ECMO evaluation.",
    examTraps: "Do not diagnose PPHN from hypoxemia alone; echocardiography is essential to define shunting and exclude structural heart disease. Routine iNO for very preterm respiratory failure is not equivalent to term PPHN treatment.",
    sourceKeys: ["AAP_PPHN_CURRENT", "AAP_INO_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
