import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch28 = [
  {
    slug: "neonatal-opioid-withdrawal-syndrome",
    title: "Neonatal Opioid Withdrawal Syndrome",
    titleAliases: ["NAS: Opioid Withdrawal Scoring"],
    slugAliases: ["neonatal-abstinence-np"],
    bodySystem: "Pediatrics",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PNP", "PMHNP", "WHNP"],
    recognize: "Prenatal opioid exposure can produce tremor, hypertonia, high-pitched cry, poor feeding, sleep difficulty, diarrhea or autonomic dysregulation after birth. Timing varies with the opioid and coexposures, and jitteriness, sepsis, hypoglycemia and neurologic disease are mimics.",
    diagnostics: "Diagnosis is clinical using functional assessment such as Eat-Sleep-Console or a validated local scoring pathway plus exposure history. Toxicology can document exposure but does not grade withdrawal; check glucose, infection or neurologic studies only when the presentation suggests another cause.",
    priorities: "Use nonpharmacologic care first: rooming-in, low-stimulation environment, skin-to-skin, swaddling, feeding support and caregiver engagement. Add protocol-based opioid therapy when severe symptoms prevent adequate eating, sleep or consolability despite optimized supportive care.",
    medicationSafety: "Morphine or methadone treatment requires neonatal dosing and respiratory/feeding monitoring; clonidine or phenobarbital are selected adjuncts rather than routine first-line monotherapy. Breastfeeding decisions depend on maternal treatment stability and specific contraindications.",
    redFlags: "Seizure, respiratory depression, severe dehydration/weight loss, inability to feed, fever, marked lethargy or an unsafe caregiving/discharge environment requires urgent neonatal evaluation.",
    examTraps: "Do not medicate solely to lower a symptom score when the infant can function with supportive care. NOWS is specifically opioid-related withdrawal; polysubstance exposure can modify symptoms and management.",
    sourceKeys: ["AAP_NOWS_CURRENT"],
  },
  {
    slug: "eclampsia",
    title: "Eclampsia",
    titleAliases: ["Eclampsia: Endothelial Dysfunction"],
    slugAliases: ["eclampsia-np"],
    bodySystem: "Reproductive",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "WHNP", "AGACNP", "ENP"],
    recognize: "New generalized seizure in a pregnant or postpartum patient with preeclampsia features is eclampsia until another cause is established; seizures may occur without previously documented severe hypertension or proteinuria.",
    diagnostics: "Stabilize first, then assess BP, CBC/platelets, creatinine, AST/ALT, hemolysis/coagulation and fetal status while considering stroke, hemorrhage, epilepsy, metabolic disease or cerebral venous thrombosis when presentation is atypical.",
    priorities: "Protect airway and maternal safety, give magnesium sulfate to stop/prevent recurrent eclamptic seizures, urgently treat persistent severe-range hypertension and coordinate delivery after maternal stabilization with obstetric/anesthesia teams.",
    medicationSafety: "Magnesium sulfate is preferred over benzodiazepines or phenytoin for typical eclampsia; monitor respirations, reflexes and renal clearance and keep calcium gluconate available for toxicity. Labetalol, hydralazine or immediate-release oral nifedipine are accepted acute severe-BP options.",
    redFlags: "Persistent/recurrent seizure despite magnesium, focal deficit, severe headache with altered consciousness, pulmonary edema, HELLP/DIC, severe renal failure or refractory severe hypertension requires critical-care and neurologic evaluation.",
    examTraps: "Delivery is definitive for the pregnancy disease but seizure/BP stabilization comes first. Do not use sublingual nifedipine or delay magnesium while waiting for a serum magnesium level in a typical emergency.",
    sourceKeys: ["ACOG_PREECLAMPSIA_CURRENT", "ACOG_SEVERE_HTN_CURRENT"],
  },
  {
    slug: "transfusion-reactions",
    title: "Transfusion Reactions",
    titleAliases: ["Transfusion Reactions: Hemolytic vs Febrile"],
    slugAliases: ["transfusion-reactions-np"],
    bodySystem: "Hematology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Fever/chills, back or chest pain, dyspnea, hives, wheeze, hypotension, hemoglobinuria or new pulmonary edema during or after transfusion can represent hemolytic, febrile, allergic/anaphylactic, septic, TRALI or TACO reactions.",
    diagnostics: "Stop and classify the reaction with immediate clerical/product verification, repeat type/compatibility testing and DAT/hemolysis studies when appropriate; blood cultures, BNP/echo, chest imaging and oxygenation assessment depend on suspected septic, TACO or TRALI physiology.",
    priorities: "Stop the transfusion immediately, keep IV access with compatible crystalloid using new tubing, notify the blood bank and treating team, recheck identifiers, send required specimens/product and provide reaction-specific resuscitation.",
    medicationSafety: "Epinephrine is first-line for transfusion anaphylaxis; diuretics treat TACO but not TRALI. Acetaminophen or antihistamine premedication does not prevent serious hemolytic, septic, TRALI or TACO reactions and should not create false reassurance.",
    redFlags: "Shock, respiratory failure, hemoglobinuria/DIC, suspected bacterial contamination, severe anaphylaxis, TRALI or TACO requires emergency resuscitation and transfusion-medicine involvement.",
    examTraps: "Do not simply slow a transfusion when a serious reaction is possible—stop it. Fever alone does not prove a benign febrile nonhemolytic reaction until hemolysis and bacterial contamination are considered.",
    sourceKeys: ["AABB_TRANSFUSION_REACTIONS_CURRENT", "AABB_HEMOVIGILANCE_CURRENT"],
  },
  {
    slug: "negative-pressure-wound-therapy",
    title: "Negative Pressure Wound Therapy",
    slugAliases: ["wound-vac-np"],
    bodySystem: "Integumentary",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP"],
    recognize: "NPWT can support selected complex open wounds by removing exudate, reducing edema and promoting granulation, but success depends on perfusion, source control, debridement, nutrition and offloading rather than the device alone.",
    diagnostics: "Assess wound dimensions/depth, tunneling, tissue, exposed structures, perfusion, infection and bleeding risk before application. Culture only clinically infected wounds and evaluate arterial supply in ischemic-appearing lower-extremity wounds.",
    priorities: "Debride appropriate devitalized tissue, protect exposed structures, choose foam/interface and pressure settings for wound type, maintain an airtight seal and coordinate dressing changes, offloading and nutrition with wound specialists.",
    medicationSafety: "Systemic antibiotics are for invasive infection, not colonization. Anticoagulation and friable vessels increase bleeding risk; analgesia should be planned before painful dressing changes without oversedating frail patients.",
    redFlags: "Frank bleeding into the device, exposed unprotected vessel/organ, untreated osteomyelitis with inadequate source control, necrotizing infection, critical ischemia or rapidly worsening sepsis requires stopping routine NPWT and urgent escalation.",
    examTraps: "NPWT is not placed over untreated necrotic eschar as a shortcut for debridement. A machine alarm is not just equipment noise—loss of seal or blockage can eliminate therapeutic pressure.",
    sourceKeys: ["NPIAP_CURRENT", "WOUND_NPWT_CURRENT"],
  },
  {
    slug: "lumbar-puncture-csf-analysis",
    title: "Lumbar Puncture & CSF Analysis",
    slugAliases: ["lumbar-puncture-np"],
    bodySystem: "Procedures",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PNP", "ENP"],
    recognize: "Lumbar puncture is used for meningitis/encephalitis, subarachnoid hemorrhage after nondiagnostic initial pathways, inflammatory/demyelinating disease, malignancy and opening-pressure disorders; the indication determines which CSF studies matter.",
    diagnostics: "Before LP assess focal deficit, papilledema, severe immunocompromise, new seizure, depressed consciousness, coagulopathy and local infection to decide whether imaging or correction is needed first. Measure opening pressure correctly in lateral decubitus when clinically relevant.",
    priorities: "Use sterile technique at a lumbar interspace below the conus, collect enough properly labeled tubes for cell count, glucose/protein, culture/PCR and targeted tests, and give empiric antimicrobials before LP when bacterial meningitis is suspected and delay would be unsafe.",
    medicationSafety: "Review anticoagulants/antiplatelets and platelet/coagulation status against procedural risk and current guidance. Local anesthetic toxicity is uncommon with appropriate dosing; routine prolonged bed rest does not reliably prevent post-dural puncture headache.",
    redFlags: "Signs of impending herniation, severe coagulopathy, unstable respiratory/hemodynamic status, spinal epidural infection or new neurologic deterioration after LP requires urgent escalation.",
    examTraps: "Do not reflexively CT every patient before LP. A traumatic tap can complicate RBC interpretation, and xanthochromia/timing plus the overall SAH pathway matter more than a simplistic tube-1-to-tube-4 rule.",
    sourceKeys: ["IDSA_MENINGITIS_CURRENT", "AHA_SAH_CURRENT"],
  },
  {
    slug: "arterial-blood-gas-interpretation",
    title: "Arterial Blood Gas Interpretation",
    titleAliases: ["ABG Sampling & Interpretation"],
    slugAliases: ["abg-sampling-np"],
    bodySystem: "Diagnostics",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Interpret ABGs in order: pH, PaCO2, bicarbonate, expected compensation and oxygenation, then calculate anion gap and delta relationships when metabolic acidosis is present. Mixed disorders are common in critical illness.",
    diagnostics: "Pair ABG with electrolytes, lactate, glucose/ketones, renal function, toxicology and clinical ventilation/FiO2. Use expected-compensation formulas to detect a second acid-base process rather than labeling every abnormal pair 'partially compensated.'",
    priorities: "Treat the underlying physiology—ventilation for acute hypercapnic failure, perfusion/source control for lactic acidosis, insulin/fluids/electrolytes for DKA, toxin-specific therapy when indicated—rather than treating the pH number alone.",
    medicationSafety: "Sodium bicarbonate is not routine for most metabolic acidoses and can worsen sodium load, CO2 generation and ionized hypocalcemia; reserve it for selected severe acidemia/toxicologic indications. Oxygen targets should match the patient's disease rather than a universal 100% saturation goal.",
    redFlags: "Severe acidemia with shock, rapidly rising PaCO2 with altered mental status, refractory hypoxemia, toxic alcohol/salicylate pattern or potassium-related ECG changes requires emergency monitored management.",
    examTraps: "ROME is a mnemonic, not a complete mixed-disorder analysis. Venous gas can estimate pH/CO2 in many situations but does not substitute for arterial oxygenation assessment when precise PaO2 is required.",
    sourceKeys: ["ATS_ABG_CURRENT", "CRITICAL_CARE_ACID_BASE_CURRENT"],
  },
  {
    slug: "neonatal-sepsis",
    title: "Neonatal Sepsis",
    bodySystem: "Pediatrics",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PNP", "ENP"],
    recognize: "Neonatal sepsis can present with temperature instability, respiratory distress/apnea, poor feeding, lethargy, glucose instability, hypotension or subtle behavior change; absence of fever does not reassure in a newborn.",
    diagnostics: "Obtain blood culture before antibiotics when this does not delay treatment, CBC and other biomarkers as adjuncts, and lumbar puncture when meningitis is suspected or bacteremia/high clinical concern warrants it. Maternal GBS, fever, membrane rupture and gestational age shape early-onset risk.",
    priorities: "Stabilize airway/perfusion, start prompt empiric neonatal antibiotics matched to early- versus late-onset risk and local resistance, then narrow to cultures. Follow current neonatal early-onset sepsis algorithms rather than treating every risk factor identically.",
    medicationSafety: "Ampicillin plus gentamicin is a common early-onset regimen but aminoglycosides require renal/level monitoring. Ceftriaxone is generally avoided in neonates with hyperbilirubinemia or calcium-containing IV therapy concerns.",
    redFlags: "Apnea, shock, severe respiratory distress, seizure, meningitis concern, persistent hypoglycemia or rapidly progressive lethargy requires immediate NICU-level care.",
    examTraps: "A single normal CBC does not rule out neonatal sepsis. Do not prolong antibiotics solely because of nonspecific risk factors when cultures remain negative and the infant meets a validated stop pathway.",
    sourceKeys: ["AAP_EOS_CURRENT", "AAP_RED_BOOK_CURRENT"],
  },
  {
    slug: "meconium-aspiration-syndrome",
    title: "Meconium Aspiration Syndrome",
    bodySystem: "Pediatrics",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PNP", "ENP"],
    recognize: "A term/post-term infant born through meconium-stained fluid with early respiratory distress, coarse breath sounds, hypoxemia and patchy hyperinflation/atelectasis may have meconium aspiration; PPHN and air leak are important complications.",
    diagnostics: "Use clinical history, pulse oximetry/ABG and chest radiography, while excluding pneumonia, TTN, RDS and structural heart disease. Echocardiography is needed when severe hypoxemia suggests PPHN or cardiac disease.",
    priorities: "Follow neonatal resuscitation principles; routine intrapartum or tracheal suctioning solely for meconium is not recommended. Provide oxygen/CPAP or ventilation as needed, treat PPHN physiology and consider surfactant in severe secondary surfactant dysfunction.",
    medicationSafety: "Antibiotics are used when bacterial infection is suspected, not automatically because meconium is present. High oxygen and aggressive ventilation increase air-leak and oxidative injury risks.",
    redFlags: "Refractory hypoxemia, PPHN, pneumothorax, severe acidosis, shock or escalating ventilation requirement requires immediate NICU/ECMO-capable evaluation.",
    examTraps: "Meconium-stained fluid alone is not meconium aspiration syndrome. Vigorous and nonvigorous infants are no longer routinely suctioned simply because meconium is present; resuscitate based on breathing and heart rate.",
    sourceKeys: ["ACOG_MECONIUM_CURRENT", "NRP_CURRENT", "AAP_SURFACTANT_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
