import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch41 = [
  {
    slug: "alpha-1-antitrypsin-deficiency",
    title: "Alpha-1 Antitrypsin Deficiency",
    bodySystem: "Respiratory",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Think alpha-1 antitrypsin deficiency in emphysema/COPD at an unusually young age, basilar-predominant emphysema, minimal smoking exposure, unexplained bronchiectasis, panniculitis or family history of early lung or liver disease. AAT deficiency can also cause neonatal or adult liver disease through abnormal protein accumulation.",
    diagnostics: "Current COPD guidance supports testing all patients with COPD at least once for AAT deficiency. Start with serum AAT concentration and confirm abnormal/borderline results with genotype or phenotype testing because inflammation can raise serum levels and conceal deficiency; evaluate liver disease and counsel family testing when a pathogenic genotype is confirmed.",
    priorities: "Eliminate smoking/vaping and occupational inhalational exposure, use standard COPD inhaled therapy and pulmonary rehabilitation according to symptoms, vaccinate appropriately and refer confirmed severe deficiency for pulmonary/hepatology expertise. IV AAT augmentation is considered for selected adults with severe deficiency and airflow obstruction, not for every low level or isolated liver disease.",
    medicationSafety: "Augmentation therapy is IV human plasma-derived AAT with infusion/cost/access considerations and does not reverse established emphysema or treat hepatic accumulation. Avoid unnecessary hepatotoxins and review alcohol because liver disease can progress independently of lung symptoms.",
    redFlags: "Rapidly progressive hypoxemia, severe early-onset emphysema, decompensated cirrhosis, hepatocellular-carcinoma concern or unexplained severe bronchiectasis requires specialty evaluation.",
    examTraps: "Do not exclude AAT deficiency because the patient smoked; smoking accelerates disease. A normal-looking serum AAT during acute inflammation does not fully exclude a pathogenic genotype when suspicion is high.",
    sourceKeys: ["GOLD_2026", "COPD_FOUNDATION_AAT_CURRENT"],
  },
  {
    slug: "interstitial-lung-disease-evaluation",
    title: "Interstitial Lung Disease Evaluation",
    bodySystem: "Respiratory",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP"],
    recognize: "Progressive exertional dyspnea, dry cough, fine inspiratory crackles, clubbing or restrictive physiology raises concern for ILD. The differential includes idiopathic pulmonary fibrosis, connective-tissue disease, hypersensitivity pneumonitis, occupational exposure, drug toxicity and sarcoidosis.",
    diagnostics: "Obtain detailed medication, autoimmune and occupational/environmental exposure history, PFTs with DLCO and high-resolution CT. Autoimmune serologies are selected by phenotype, and multidisciplinary review of imaging/clinical data often determines whether bronchoscopy or lung biopsy is necessary rather than performing biopsy routinely.",
    priorities: "Remove offending exposures/drugs, treat a defined inflammatory/autoimmune disease when appropriate and refer fibrotic/progressive disease early to pulmonology/ILD specialists for antifibrotic eligibility, oxygen assessment, rehabilitation and transplant consideration.",
    medicationSafety: "Systemic steroids can help selected inflammatory ILDs but are not routine treatment for idiopathic pulmonary fibrosis and can be harmful when used chronically without an inflammatory indication. Antifibrotics have hepatic/GI and bleeding or interaction considerations and require monitoring.",
    redFlags: "Rapidly progressive hypoxemia, acute diffuse ground-glass change, new pneumothorax, pulmonary hypertension/right-heart failure or suspected acute ILD exacerbation requires urgent inpatient/specialty care.",
    examTraps: "Do not call every bilateral interstitial pattern 'pulmonary fibrosis' and prescribe prednisone. HRCT pattern, exposures and connective-tissue features determine the next step.",
    sourceKeys: ["ATS_ILD_DIAGNOSIS_CURRENT", "ATS_IPF_CURRENT"],
  },
  {
    slug: "idiopathic-pulmonary-fibrosis",
    title: "Idiopathic Pulmonary Fibrosis",
    bodySystem: "Respiratory",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP"],
    recognize: "IPF is a chronic progressive fibrotic interstitial pneumonia, typically in older adults, characterized by exertional dyspnea, dry cough, bibasilar 'Velcro' crackles and a usual interstitial pneumonia pattern after other causes of fibrosis are excluded.",
    diagnostics: "Use HRCT to identify UIP/probable UIP and exclude exposure, drug and connective-tissue causes. PFTs track restrictive physiology/DLCO decline; multidisciplinary discussion can establish diagnosis without surgical lung biopsy when the clinical-radiographic pattern is sufficiently characteristic.",
    priorities: "Refer early for antifibrotic therapy with nintedanib or pirfenidone, pulmonary rehabilitation, oxygen when indicated, symptom/palliative support and timely lung-transplant evaluation. Manage comorbid reflux/OSA/CAD by their own indications rather than as unproven antifibrotic treatment.",
    medicationSafety: "Nintedanib commonly causes diarrhea and can elevate liver enzymes or increase bleeding risk; pirfenidone causes GI effects, photosensitivity and liver toxicity. Chronic immunosuppressive prednisone/azathioprine-based therapy is not recommended for stable IPF.",
    redFlags: "Acute unexplained respiratory worsening, new bilateral ground-glass opacities, severe resting hypoxemia, pneumothorax or right-heart failure suggests acute exacerbation/complication requiring urgent care.",
    examTraps: "Do not use chronic corticosteroid monotherapy for stable IPF. IPF is a diagnosis of exclusion within the UIP-pattern differential, not simply 'fibrosis on CT.'",
    sourceKeys: ["ATS_IPF_CURRENT"],
  },
  {
    slug: "bronchiectasis-adults",
    title: "Adult Bronchiectasis",
    bodySystem: "Respiratory",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Chronic daily productive cough, recurrent bacterial exacerbations, hemoptysis, coarse crackles and repeated focal infections suggest bronchiectasis. Causes include prior infection, immune deficiency, aspiration, ABPA, cystic fibrosis/CFTR disease, ciliary disorders and autoimmune disease.",
    diagnostics: "Confirm with thin-section CT, obtain sputum cultures including mycobacterial testing when indicated, and evaluate etiologies such as immunoglobulins, ABPA and CF/PCD according to phenotype. Spirometry defines airflow limitation but does not diagnose bronchiectasis.",
    priorities: "Airway-clearance therapy is foundational; treat exacerbations with culture-informed antibiotics, vaccinate and manage the underlying cause. Long-term macrolide therapy is reserved for selected frequent exacerbators after excluding nontuberculous mycobacterial infection and reviewing QT/hearing risk.",
    medicationSafety: "Inhaled corticosteroids are not routine bronchiectasis treatment unless asthma/COPD or another indication exists. Chronic macrolides select resistance and can prolong QT; aminoglycoside/inhaled antibiotic strategies require specialist monitoring.",
    redFlags: "Massive/significant hemoptysis, severe hypoxemia, sepsis, rapid clinical decline or suspected pulmonary embolization-worthy bleeding requires emergency/inpatient care.",
    examTraps: "Do not repeatedly prescribe empiric antibiotics without sputum microbiology in recurrent disease. Bronchiectasis is not the same as chronic bronchitis despite chronic sputum production.",
    sourceKeys: ["ERS_BRONCHIECTASIS_CURRENT", "ATS_NTM_CURRENT"],
  },
  {
    slug: "pulmonary-sarcoidosis",
    title: "Pulmonary Sarcoidosis",
    bodySystem: "Respiratory",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "Sarcoidosis is a multisystem granulomatous disease that often presents with bilateral hilar adenopathy, pulmonary infiltrates, cough/dyspnea, erythema nodosum, uveitis or constitutional symptoms. Cardiac and neurologic sarcoidosis are less common but high-risk.",
    diagnostics: "Diagnosis requires a compatible syndrome, non-necrotizing granulomatous inflammation when tissue is needed and exclusion of infections/exposures such as TB, fungal disease and berylliosis. Baseline evaluation includes chest imaging/PFTs plus eye, cardiac, calcium, renal and liver assessment based on current recommendations.",
    priorities: "Observe asymptomatic stable disease when organ function is preserved; treat clinically significant pulmonary, ocular, cardiac, neurologic or other organ-threatening disease with corticosteroids and steroid-sparing therapy when prolonged treatment is needed.",
    medicationSafety: "Glucocorticoids cause cumulative metabolic, bone and infection toxicity; methotrexate and other steroid-sparing agents require hepatic/marrow/infection monitoring. Avoid vitamin-D/calcium supplementation reflexively because sarcoid macrophages can cause hypercalcemia/hypercalciuria.",
    redFlags: "Syncope/arrhythmia, high-grade AV block, heart failure, vision change, neurologic deficit, severe hypercalcemia or progressive hypoxemia requires urgent specialty evaluation.",
    examTraps: "ACE level is neither sensitive nor specific enough to diagnose sarcoidosis. Do not treat asymptomatic hilar adenopathy solely because granulomas are present.",
    sourceKeys: ["ATS_SARCOIDOSIS_CURRENT"],
  },
  {
    slug: "pulmonary-hypertension-adults",
    title: "Pulmonary Hypertension in Adults",
    bodySystem: "Respiratory",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Progressive exertional dyspnea, fatigue, chest pressure, syncope, edema, elevated JVP or loud P2 can reflect pulmonary hypertension. Classify the cause: pulmonary arterial hypertension, left-heart disease, lung/hypoxia, chronic thromboembolic disease or multifactorial mechanisms.",
    diagnostics: "Echocardiography estimates probability and RV effects but right-heart catheterization is required to define hemodynamics before PAH-specific treatment. Evaluate ECG/CXR, BNP, PFTs, sleep/hypoxia, V/Q scan for CTEPH, connective-tissue disease and left-heart disease according to phenotype.",
    priorities: "Treat the underlying group-specific cause and refer suspected PAH/CTEPH to an expert center. PAH uses risk-stratified combination vasodilator therapy; CTEPH may be surgically curable with pulmonary endarterectomy or treated with balloon angioplasty/medication in specialized programs.",
    medicationSafety: "PAH vasodilators can cause hypotension and may worsen pulmonary edema or V/Q mismatch if used in the wrong PH group. Endothelin-receptor antagonists have fetal/hepatic considerations; PDE-5 inhibitors cannot be combined with nitrates.",
    redFlags: "Syncope, severe RV failure, hypotension, rapidly increasing oxygen requirement, chest pain or pregnancy in severe PAH requires urgent expert management.",
    examTraps: "Do not prescribe PAH-specific vasodilators from an echocardiographic pressure estimate alone. Most PH encountered in general practice is due to left-heart or lung disease, not group 1 PAH.",
    sourceKeys: ["ESC_ERS_PH_2022_CURRENT", "CHEST_PH_CURRENT"],
  },
  {
    slug: "obstructive-sleep-apnea-adults",
    title: "Obstructive Sleep Apnea in Adults",
    bodySystem: "Respiratory",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PMHNP"],
    recognize: "Loud snoring, witnessed apneas, gasping, unrefreshing sleep, nocturia, morning headache, resistant hypertension or daytime sleepiness raises concern for OSA. Normal BMI does not exclude it; craniofacial anatomy, menopause, alcohol/sedatives and upper-airway disease also matter.",
    diagnostics: "Use a validated screen such as STOP-BANG to estimate risk, not diagnose disease. Confirm with home sleep apnea testing in appropriate uncomplicated adults or in-lab polysomnography when cardiopulmonary disease, neuromuscular weakness, hypoventilation, opioid use or another sleep disorder makes home testing inadequate.",
    priorities: "Treat with positive airway pressure when indicated, weight management, exercise, positional or oral-appliance therapy in selected patients and surgical/ENT evaluation when anatomy or PAP intolerance justifies it. Address driving risk and sedative/alcohol exposure.",
    medicationSafety: "Benzodiazepines, opioids and other respiratory depressants can worsen sleep-disordered breathing; review them before simply adding wake-promoting medication for daytime sleepiness. PAP adherence should be optimized before stimulant-like wake-promoting agents are considered.",
    redFlags: "Severe daytime sleepiness with driving risk, suspected obesity hypoventilation, resting hypoxemia/hypercapnia, right-heart failure or perioperative airway risk requires expedited sleep/pulmonary evaluation.",
    examTraps: "STOP-BANG does not diagnose OSA and nocturnal oxygen alone does not treat upper-airway obstruction. A negative home test in a high-suspicion patient may require in-lab polysomnography.",
    sourceKeys: ["AASM_OSA_DIAGNOSIS_CURRENT", "AASM_PAP_CURRENT"],
  },
  {
    slug: "pulmonary-nodule-lung-cancer-evaluation",
    title: "Pulmonary Nodules & Lung Cancer Evaluation",
    bodySystem: "Respiratory",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP"],
    recognize: "Pulmonary nodules are common and most are benign, but malignancy risk rises with age, smoking, size, spiculation, upper-lobe location, growth and prior cancer. Lung cancer can present with persistent cough, hemoptysis, weight loss, recurrent focal pneumonia, hoarseness or paraneoplastic syndromes.",
    diagnostics: "Apply current screening criteria separately from incidental-nodule management. For incidental nodules use size/morphology and clinical risk to choose CT surveillance, PET/CT, nonsurgical biopsy or surgical evaluation; compare all prior imaging because growth changes risk substantially.",
    priorities: "Refer suspicious or growing nodules to a multidisciplinary lung-nodule/thoracic program; obtain tissue in a way that also supports staging and molecular testing when cancer is likely. Ensure eligible high-risk asymptomatic adults receive annual low-dose CT screening rather than chest x-ray screening.",
    medicationSafety: "Do not repeatedly expose low-risk nodules to unnecessary contrast/PET/biopsy. Anticoagulants/antiplatelets, emphysema and pulmonary reserve affect biopsy choice and procedural risk; smoking-cessation pharmacotherapy should be offered regardless of screening result.",
    redFlags: "Massive hemoptysis, superior vena cava syndrome, acute airway obstruction, spinal cord compression or severe hypercalcemia/neurologic paraneoplastic complication requires urgent oncologic/emergency care.",
    examTraps: "A stable tiny nodule and a spiculated enlarging nodule do not use the same follow-up. Lung-cancer screening is for asymptomatic eligible patients; symptoms require diagnostic evaluation, not a screening-order shortcut.",
    sourceKeys: ["USPSTF_LUNG_CANCER_CURRENT", "FLEISCHNER_NODULE_CURRENT", "NCCN_LUNG_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
