import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch18 = [
  {
    slug: "irritable-bowel-syndrome",
    title: "Irritable Bowel Syndrome",
    bodySystem: "Gastrointestinal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "Recurrent abdominal pain related to defecation plus a change in stool frequency or form suggests IBS when the pattern is chronic and no alarm features suggest inflammatory, malignant, infectious, or malabsorptive disease.",
    diagnostics: "Use a positive symptom-based diagnosis with limited targeted testing. CBC, celiac serology or inflammatory markers may be appropriate by phenotype; colonoscopy is not routine in younger low-risk patients without alarm features or separate screening indication.",
    priorities: "Match treatment to constipation, diarrhea, pain and bloating phenotype using diet, soluble fiber, gut-brain behavioral therapy and selected medications. Build a longitudinal plan rather than serial exclusionary testing.",
    medicationSafety: "Avoid chronic opioid therapy because it worsens GI function and pain syndromes. Antispasmodics, secretagogues, antidiarrheals and neuromodulators have anticholinergic, cardiac, pregnancy and interaction considerations.",
    redFlags: "GI bleeding, unintentional weight loss, iron-deficiency anemia, nocturnal progressive symptoms, family history of IBD/CRC, fever, or new onset at an older age requires broader evaluation.",
    examTraps: "IBS is not a diagnosis of 'nothing found'; it has defined symptom criteria. Do not order repeated CT scans for a stable chronic IBS pattern without new red flags.",
    sourceKeys: ["ACG_IBS_CURRENT"],
  },
  {
    slug: "inflammatory-bowel-disease",
    title: "Inflammatory Bowel Disease",
    bodySystem: "Gastrointestinal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP"],
    recognize: "Chronic diarrhea, hematochezia, urgency, nocturnal stooling, weight loss, anemia, abdominal pain, perianal disease, or extraintestinal arthritis, skin and eye findings suggest Crohn disease or ulcerative colitis rather than IBS.",
    diagnostics: "Use CBC/CMP, CRP, stool infection testing and fecal calprotectin when appropriate, followed by colonoscopy with biopsies and small-bowel imaging for suspected Crohn disease. Exclude infection before labeling a severe flare.",
    priorities: "Induce and maintain remission with disease-appropriate anti-inflammatory, immunomodulator, biologic or small-molecule therapy under GI guidance. Address nutrition, vaccination, VTE risk, bone health, cancer surveillance and smoking.",
    medicationSafety: "Steroids are for induction, not maintenance. Immunosuppressive and biologic therapy requires infection screening, vaccination planning, pregnancy counseling, malignancy-risk discussion and lab monitoring.",
    redFlags: "Toxic megacolon, severe bleeding, perforation, obstruction, abscess, high fever with severe flare, or dehydration with AKI requires urgent inpatient/surgical evaluation.",
    examTraps: "Do not call bloody diarrhea IBS. Normal CRP does not completely exclude active IBD, particularly limited disease.",
    sourceKeys: ["ACG_UC_CURRENT", "ACG_CROHN_CURRENT", "ACG_IBD_PREVENTIVE_2025"],
  },
  {
    slug: "celiac-disease",
    title: "Celiac Disease",
    bodySystem: "Gastrointestinal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PNP"],
    recognize: "Chronic diarrhea, bloating, weight loss, iron deficiency, osteoporosis, dermatitis herpetiformis, elevated liver enzymes, infertility, neuropathy, or type 1 diabetes can be manifestations of celiac disease even without classic diarrhea.",
    diagnostics: "Test tissue-transglutaminase IgA with total IgA while the patient is eating gluten; use IgG-based testing when IgA deficient. Confirmatory upper-endoscopy biopsy is standard for most adults and selected pediatric pathways use strict nonbiopsy criteria.",
    priorities: "Use a lifelong gluten-free diet with dietitian support, assess iron/folate/B12/vitamin D and bone health, vaccinate as indicated, and confirm serologic/symptom response. Reconsider diagnosis or hidden gluten when symptoms persist.",
    medicationSafety: "Do not start a gluten-free diet before diagnostic testing when the patient is stable, because serology and biopsy sensitivity fall. Review medications and supplements for hidden gluten only when clinically relevant rather than creating unnecessary restrictions.",
    redFlags: "Severe malnutrition, refractory symptoms, GI bleeding, marked weight loss, severe electrolyte disturbance, or concern for lymphoma/refractory celiac disease requires specialist evaluation.",
    examTraps: "A negative tTG-IgA can be falsely reassuring in IgA deficiency or low gluten intake. Food intolerance testing panels do not diagnose celiac disease.",
    sourceKeys: ["ACG_CELIAC_CURRENT"],
  },
  {
    slug: "diverticulitis",
    title: "Acute Diverticulitis",
    bodySystem: "Gastrointestinal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Left lower-quadrant pain, fever and bowel change in an adult suggests diverticulitis, but urinary, gynecologic, colorectal cancer, ischemic and other abdominal causes remain in the differential.",
    diagnostics: "CT abdomen/pelvis is useful for first or severe/atypical episodes and to identify abscess, perforation or alternative disease. Colonoscopy is not performed during acute severe inflammation and follow-up need depends on prior colon evaluation and episode features.",
    priorities: "Selected uncomplicated immunocompetent patients can be managed without antibiotics using analgesia, diet advancement and follow-up. Use antibiotics, admission, drainage or surgery for systemic illness, immunocompromise or complicated disease.",
    medicationSafety: "Avoid routine fluoroquinolone exposure when safer effective regimens are available. NSAIDs may increase GI complication risk in susceptible patients; opioids worsen constipation and can obscure clinical deterioration.",
    redFlags: "Peritonitis, sepsis, free perforation, large abscess, fistula/obstruction, uncontrolled pain or inability to hydrate requires urgent hospital/surgical evaluation.",
    examTraps: "Do not automatically prescribe antibiotics for every mild uncomplicated case. Nuts, seeds and popcorn are not proven causes that require permanent avoidance.",
    sourceKeys: ["ACG_DIVERTICULITIS_2026", "AGA_DIVERTICULITIS_CURRENT"],
  },
  {
    slug: "cholelithiasis-cholecystitis",
    title: "Biliary Colic & Acute Cholecystitis",
    bodySystem: "Gastrointestinal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Postprandial episodic RUQ or epigastric pain lasting minutes to hours suggests biliary colic; persistent pain, fever, Murphy sign and inflammatory findings raise concern for acute cholecystitis.",
    diagnostics: "RUQ ultrasound is first-line to assess gallstones, wall thickening, pericholecystic fluid and duct dilation. CBC/CMP/lipase and bilirubin/liver enzymes help detect infection, pancreatitis or common-duct obstruction; HIDA is useful when ultrasound is equivocal.",
    priorities: "Provide analgesia, hydration and antiemetics, use antibiotics for infected/complicated disease, and arrange early surgical evaluation for acute cholecystitis. Symptomatic gallstones generally merit elective cholecystectomy discussion.",
    medicationSafety: "NSAIDs are effective biliary analgesics for many patients but require kidney/GI risk review. Opioids may be needed for severe pain but are not definitive treatment and can worsen nausea or constipation.",
    redFlags: "Sepsis, jaundice with fever, hypotension, pancreatitis, gallbladder perforation, emphysematous disease or persistent obstruction requires urgent inpatient care.",
    examTraps: "Biliary colic should resolve between attacks and does not usually produce marked inflammatory signs. A normal lipase does not rule out cholecystitis.",
    sourceKeys: ["SAGES_GALLBLADDER_CURRENT", "ACR_RUQ_CURRENT"],
  },
  {
    slug: "cholangitis-choledocholithiasis",
    title: "Cholangitis & Choledocholithiasis",
    bodySystem: "Gastrointestinal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Jaundice, RUQ pain, fever, cholestatic labs or duct dilation suggests common-bile-duct obstruction; hypotension or altered mentation with infection signals severe ascending cholangitis.",
    diagnostics: "Check bilirubin, alkaline phosphatase/transaminases, CBC, renal function, blood cultures when febrile, and ultrasound. MRCP/EUS refine intermediate-risk duct stones; ERCP is therapeutic and should not be used as a low-risk screening test.",
    priorities: "Cholangitis requires prompt IV antibiotics, resuscitation and urgent biliary decompression—usually ERCP—based on severity. After duct clearance, address the gallbladder to reduce recurrence when appropriate.",
    medicationSafety: "Antibiotics must cover likely enteric gram-negative/anaerobic organisms and be renal-adjusted. ERCP carries pancreatitis, bleeding, perforation and sedation risks.",
    redFlags: "Hypotension, confusion, rising lactate, organ dysfunction, persistent obstruction or sepsis requires emergency drainage-capable care.",
    examTraps: "Charcot triad is not required and may be absent. Do not send every suspected duct stone directly to diagnostic ERCP when noninvasive risk stratification is appropriate.",
    sourceKeys: ["ASGE_CHOLeDOCHOLITHIASIS_CURRENT", "TOKYO_CHOLANGITIS_CURRENT"],
  },
  {
    slug: "viral-hepatitis",
    title: "Viral Hepatitis B & C",
    bodySystem: "Gastrointestinal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "WHNP"],
    recognize: "Chronic HBV/HCV may be asymptomatic for years; risk includes birth or residence in endemic areas, injection exposure, transfusion before modern screening, sexual/perinatal exposure and unexplained liver-enzyme abnormalities.",
    diagnostics: "Use the correct HBV serologic panel to distinguish immunity, susceptibility and active infection; confirm HCV with RNA after a reactive antibody. Stage fibrosis and assess HIV, HAV/HBV immunity, pregnancy and hepatocellular-cancer risk.",
    priorities: "Link chronic HBV to treatment/monitoring based on viral load, ALT, fibrosis and special populations; treat nearly all chronic HCV with guideline-directed direct-acting antivirals. Vaccinate nonimmune patients against hepatitis A/B as appropriate.",
    medicationSafety: "HBV can reactivate during immunosuppression, so screen before biologic/chemotherapy therapy. HCV direct-acting antivirals have important drug interactions; HBV antivirals require renal/bone considerations depending on agent.",
    redFlags: "Acute liver failure, encephalopathy, severe coagulopathy, decompensated cirrhosis, variceal bleeding or rapidly worsening jaundice requires urgent hepatology/inpatient care.",
    examTraps: "A reactive HCV antibody does not prove current infection; RNA does. A positive hepatitis B surface antibody means different things depending on surface antigen and core-antibody results.",
    sourceKeys: ["AASLD_HBV_CURRENT", "AASLD_IDSA_HCV_CURRENT", "CDC_HEPATITIS_CURRENT"],
  },
  {
    slug: "colorectal-cancer-screening",
    title: "Colorectal Cancer Screening",
    bodySystem: "Oncology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "Screen asymptomatic average-risk adults according to age and life-expectancy guidance, while recognizing that iron-deficiency anemia, rectal bleeding, weight loss or bowel-change symptoms require diagnostic evaluation rather than screening.",
    diagnostics: "Choose among stool-based tests, colonoscopy, CT colonography or other accepted strategies according to interval, patient preference and access. Any positive noncolonoscopy screening test requires diagnostic colonoscopy.",
    priorities: "Begin average-risk screening at the current recommended age, continue through the age range with clear net benefit, and individualize later screening by prior results, comorbidity and life expectancy. High-risk family/genetic history changes start age and interval.",
    medicationSafety: "Bowel-prep selection should consider renal, heart-failure and electrolyte risk. Anticoagulant or antiplatelet management around colonoscopy depends on procedure bleeding risk and thrombotic indication.",
    redFlags: "Obstruction symptoms, significant GI bleeding, severe iron-deficiency anemia, unexplained weight loss or suspected metastatic disease requires expedited diagnostic evaluation.",
    examTraps: "A negative FIT does not evaluate symptomatic rectal bleeding. Do not repeat a stool test to 'confirm' a positive screening result instead of arranging colonoscopy.",
    sourceKeys: ["USPSTF_CRC_CURRENT", "USMSTF_CRC_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
