import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch34 = [
  {
    slug: "erectile-dysfunction",
    title: "Erectile Dysfunction",
    titleAliases: ["Erectile Dysfunction: Vascular Pathophysiology & PDE5 Inhibitors"],
    slugAliases: ["np-clinical-erectile-dysfunction"],
    bodySystem: "Genitourinary",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "ED is persistent difficulty achieving or maintaining an erection sufficient for sexual activity. Treat it as both a quality-of-life concern and a potential marker of vascular/metabolic disease; assess libido, spontaneous erections, relationship/psychological factors, medications and cardiovascular symptoms.",
    diagnostics: "Use focused sexual/medical history, genital/vascular exam and cardiometabolic assessment including BP, diabetes and lipids. Measure morning total testosterone when hypogonadal symptoms, low libido or other clinical clues exist; specialized penile testing is reserved for selected refractory or pre-procedural cases.",
    priorities: "Address smoking, diabetes, obesity, medication contributors and relationship/psychological factors, then offer an FDA-approved PDE5 inhibitor unless contraindicated. Refer men with penile deformity, severe hypogonadal disease, fertility issues or failure/intolerance of first-line therapy for injections, devices or prosthetic options.",
    medicationSafety: "PDE5 inhibitors are contraindicated with nitrates because of potentially profound hypotension and require caution with alpha blockers/hypotension. Counsel on correct timing, sexual stimulation and agent-specific food effects before declaring treatment failure.",
    redFlags: "Priapism lasting about 4 hours, unstable angina/exertional cardiac symptoms, severe hypotension, acute testicular pain or a suspicious genital mass requires urgent evaluation.",
    examTraps: "Do not prescribe testosterone for ED solely because the patient asks or has one low nonmorning level. ED can precede overt cardiovascular disease and should not be dismissed as 'just aging' or psychogenic without assessment.",
    sourceKeys: ["AUA_ED_CURRENT", "ACC_SEXUAL_CVD_CURRENT"],
  },
  {
    slug: "bph-lower-urinary-tract-symptoms",
    title: "Benign Prostatic Hyperplasia & Lower Urinary Tract Symptoms",
    titleAliases: ["BPH: DHT Pathway & Pharmacotherapy"],
    slugAliases: ["np-clinical-bph"],
    bodySystem: "Genitourinary",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "BPH can cause weak stream, hesitancy, intermittency, incomplete emptying, frequency, urgency and nocturia, but LUTS also arise from overactive bladder, infection, urethral stricture, neurologic disease, medications, diabetes and prostate cancer.",
    diagnostics: "Use symptom severity/bother, urinalysis and focused exam; assess post-void residual when retention is possible and PSA when results would affect management or cancer evaluation. Imaging, cystoscopy and urodynamics are selective rather than routine in uncomplicated initial care.",
    priorities: "Use watchful waiting for mild/nonbothersome symptoms, alpha blockers for rapid symptom relief, and 5-alpha-reductase inhibitors when demonstrable prostatic enlargement makes disease-progression reduction relevant. Combination therapy and surgical/minimally invasive options depend on severity, anatomy, complications and sexual priorities.",
    medicationSafety: "Alpha blockers can cause orthostasis and ejaculatory dysfunction; 5-alpha-reductase inhibitors take months to work and lower PSA by roughly half after sustained treatment, requiring adjusted interpretation. Tadalafil can help LUTS/ED but cannot be combined with nitrates.",
    redFlags: "Acute retention, recurrent gross hematuria, recurrent UTI, bladder stones, hydronephrosis/renal dysfunction or suspicion for prostate cancer requires urologic evaluation rather than indefinite medication escalation.",
    examTraps: "Do not equate every male LUTS presentation with prostate enlargement and do not use a 5-alpha-reductase inhibitor for rapid relief in a small prostate. A normal DRE does not exclude clinically important prostate disease.",
    sourceKeys: ["AUA_BPH_2026"],
  },
  {
    slug: "stroke-pathophysiology-ischemic-hemorrhagic",
    title: "Stroke: Ischemic & Hemorrhagic Pathophysiology",
    slugAliases: ["np-clinical-stroke-pathophysiology"],
    bodySystem: "Neurological",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Ischemic stroke results from arterial occlusion with an infarct core surrounded by potentially salvageable penumbra; hemorrhagic stroke causes direct tissue injury, mass effect and secondary edema. Both present with sudden focal neurologic deficits and cannot be safely distinguished by symptoms alone.",
    diagnostics: "Activate stroke imaging immediately: noncontrast CT rapidly identifies hemorrhage, while CTA/perfusion or MRI helps define large-vessel occlusion, ischemic core/penumbra and selected extended-window reperfusion eligibility. Glucose is checked immediately because hypoglycemia can mimic stroke.",
    priorities: "For ischemic stroke, restore blood flow with IV thrombolysis and/or endovascular thrombectomy in eligible patients under the 2026 AHA/ASA pathway. For intracerebral hemorrhage, reverse anticoagulation, control BP appropriately and manage mass effect/hydrocephalus with neurocritical/neurosurgical input.",
    medicationSafety: "Do not give antiplatelet, anticoagulant or thrombolytic therapy until intracranial hemorrhage has been excluded. After reperfusion, overly intensive SBP reduction below 140 mm Hg is not recommended simply because complete recanalization was achieved.",
    redFlags: "Any persistent disabling focal deficit, depressed consciousness, posterior-circulation syndrome, seizure with focal findings, anticoagulant-associated deficit or rapidly worsening headache/neurologic status requires emergency stroke-center care.",
    examTraps: "A negative early noncontrast CT rules out much acute hemorrhage but does not rule out ischemic stroke. The old age-only concept of thrombolysis candidacy is obsolete; eligibility is based on current timing, imaging and contraindication criteria.",
    sourceKeys: ["AHA_AIS_2026", "AHA_ICH_CURRENT"],
  },
  {
    slug: "diabetes-type1-type2-pathophysiology",
    title: "Diabetes Mellitus: Type 1 & Type 2 Pathophysiology",
    slugAliases: ["np-clinical-diabetes-pathophysiology"],
    bodySystem: "Endocrine",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PNP", "WHNP"],
    recognize: "Type 1 diabetes is autoimmune beta-cell destruction with absent/near-absent insulin secretion; type 2 diabetes combines insulin resistance with progressive inadequate beta-cell secretion. Either type can occur at almost any age, and adults with autoimmune diabetes are commonly misclassified as type 2.",
    diagnostics: "Diagnose diabetes with accepted A1C/plasma-glucose criteria and confirm when hyperglycemia is not unequivocal. When diabetes type is unclear—particularly younger adults, weight loss, ketosis or rapid insulin need—use standardized islet autoantibodies; C-peptide can help classification in insulin-treated people but should not be measured within 2 weeks of a hyperglycemic emergency.",
    priorities: "Type 1 diabetes requires insulin replacement, typically pump therapy or basal-bolus insulin plus CGM and carbohydrate/correction education. Type 2 treatment is individualized around glucose, obesity, ASCVD, HF, CKD and patient goals, with GLP-1/SGLT2 therapies often selected for organ protection independent of simple A1C ranking.",
    medicationSafety: "Never stop basal insulin in true type 1 diabetes because DKA can develop rapidly. SGLT2 inhibitors carry euglycemic DKA risk; sulfonylureas/insulin can cause hypoglycemia; metformin and many other therapies require renal or other patient-specific review.",
    redFlags: "DKA/HHS, severe hypoglycemia, ketosis with uncertain diabetes type, pregnancy with poor control or rapidly progressive weight loss/polyuria/polydipsia requires urgent treatment and classification reassessment.",
    examTraps: "Do not teach that type 1 is a childhood disease and type 2 an adult disease. Obesity does not exclude type 1 diabetes, and DKA can occasionally occur in ketosis-prone type 2 disease.",
    sourceKeys: ["ADA_2026_DIAGNOSIS", "ADA_2026_PHARM"],
  },
  {
    slug: "hpa-axis-stress-response",
    title: "Stress Response & HPA Axis",
    slugAliases: ["np-clinical-stress-response"],
    bodySystem: "Endocrine",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PMHNP"],
    recognize: "Physiologic stress activates hypothalamic CRH, pituitary ACTH and adrenal cortisol plus sympathetic catecholamines, increasing glucose availability, vascular tone and alertness while modulating immunity. Chronic activation and exogenous glucocorticoids can produce metabolic, psychiatric, bone and immune consequences.",
    diagnostics: "Cortisol testing is not a general 'stress level' test. Use validated endocrine testing only when Cushing syndrome or adrenal insufficiency is clinically suspected, accounting for circadian timing, critical illness, estrogen exposure and exogenous steroid use.",
    priorities: "Treat the underlying acute illness while ensuring known/suspected adrenal-insufficient patients receive stress-dose glucocorticoids when indicated. In chronic disease, reduce unnecessary glucocorticoid exposure and address sleep, trauma, depression/anxiety, substance use and cardiometabolic effects rather than attempting to pharmacologically suppress normal stress physiology.",
    medicationSafety: "Chronic systemic glucocorticoids can suppress the HPA axis and should not be stopped abruptly after significant exposure; tapering depends on dose/duration and disease control. Steroids increase glucose, infection, osteoporosis, mood and GI risks.",
    redFlags: "Refractory hypotension, severe vomiting/dehydration, hypoglycemia, hyperkalemia or collapse after steroid withdrawal suggests adrenal crisis and requires immediate hydrocortisone/fluids.",
    examTraps: "Do not diagnose 'adrenal fatigue' from nonspecific symptoms or commercial salivary panels; it is not a recognized medical diagnosis. Random cortisol values during illness are not interpreted like outpatient screening tests.",
    sourceKeys: ["ENDOCRINE_ADRENAL_INSUFFICIENCY_CURRENT", "ENDOCRINE_CUSHING_CURRENT"],
  },
  {
    slug: "osteoarthritis-vs-gout",
    title: "Osteoarthritis vs Gout: Pathophysiology & Treatment",
    slugAliases: ["np-clinical-oa-gout-comparison"],
    bodySystem: "Musculoskeletal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Osteoarthritis is chronic mechanical/degenerative joint disease with activity-related pain and brief stiffness; gout is episodic crystal-driven inflammatory arthritis with rapid severe pain, warmth and swelling. Either can involve older adults and both can coexist.",
    diagnostics: "OA is usually clinical with selective radiographs when diagnosis is uncertain or surgery is considered. When acute inflammatory monoarthritis could be gout or septic arthritis, aspirate the joint for cell count, culture and crystal analysis; serum urate can be normal during a flare.",
    priorities: "OA management emphasizes exercise/strengthening, weight reduction when applicable, topical/oral NSAIDs according to risk, injections selectively and joint replacement for severe refractory disease. Acute gout uses anti-inflammatory therapy; recurrent/high-risk gout uses treat-to-target urate lowering with prophylaxis during initiation.",
    medicationSafety: "NSAID risk rises with CKD, GI bleeding and cardiovascular disease; colchicine needs renal/hepatic and interaction review. Continue established allopurinol during a flare and use HLA-B*58:01 testing in ancestry groups at higher allopurinol-hypersensitivity risk per guideline.",
    redFlags: "Hot swollen joint with fever, prosthesis, immunosuppression or bacteremia risk is septic arthritis until excluded; do not let known gout history prevent urgent aspiration when infection is plausible.",
    examTraps: "Do not diagnose gout from uric acid alone and do not call every painful radiographic OA joint the source of acute inflammatory symptoms. OA does not produce the dramatic inflammatory synovitis typical of a crystal flare.",
    sourceKeys: ["ACR_OA_CURRENT", "ACR_GOUT_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
