import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch8 = [
  {
    slug: "iron-deficiency-anemia",
    title: "Iron Deficiency Anemia",
    bodySystem: "Hematology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PMHNP", "PNP", "WHNP", "ENP"],
    recognize: "Microcytic anemia with fatigue, pallor, pica, restless legs, or exertional symptoms suggests iron deficiency, but the NP task is to identify why iron was lost or not absorbed—not merely prescribe iron.",
    diagnostics: "Order CBC with indices, ferritin, and iron studies when needed; interpret ferritin in the context of inflammation. Evaluate menstrual, GI, dietary, pregnancy, malabsorption, and bleeding history; unexplained iron deficiency in appropriate adults requires GI evaluation.",
    priorities: "Replace iron and treat the source. Oral iron is appropriate for many patients; IV iron is useful when oral therapy fails, is not tolerated, absorption is poor, or rapid repletion is clinically important. Confirm hematologic response.",
    medicationSafety: "Oral iron commonly causes GI upset and dark stools and interacts with several drugs; separate from selected medications when needed. IV formulations can cause infusion reactions. Avoid endless iron therapy without proving ongoing need.",
    redFlags: "Syncope, angina, heart-failure symptoms, hemodynamic bleeding, profound symptomatic anemia, or suspected malignancy requires urgent escalation or expedited workup.",
    examTraps: "Ferritin can be falsely normal/high during inflammation. Do not assume menstruation explains all iron deficiency, especially when bleeding is heavy, new, postmenopausal, or accompanied by GI symptoms.",
    sourceKeys: ["ASH_IRON_CURRENT", "AGA_IDA_CURRENT"],
  },
  {
    slug: "b12-folate-anemia",
    title: "Vitamin B12 & Folate Deficiency",
    bodySystem: "Hematology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PMHNP", "PNP", "WHNP", "ENP"],
    recognize: "Macrocytosis, glossitis, paresthesias, gait difficulty, cognitive change, or unexplained cytopenias raise concern for B12/folate deficiency; neurologic findings specifically heighten concern for B12 deficiency.",
    diagnostics: "Check CBC/smear, B12 and folate status, and consider methylmalonic acid/homocysteine when results are borderline or discordant. Review diet, bariatric surgery, malabsorption, metformin, acid suppression, alcohol, and pernicious anemia risk.",
    priorities: "Replace the deficient vitamin and treat the cause. Severe neurologic B12 deficiency deserves prompt treatment; do not wait for every confirmatory test when clinical concern is high.",
    medicationSafety: "Folate can correct the anemia of B12 deficiency while neurologic injury progresses, so exclude/treat B12 deficiency before giving folate alone. Route of B12 replacement depends on severity and absorption.",
    redFlags: "Progressive neurologic deficit, severe pancytopenia, hemolysis-like laboratory pattern, or severe symptomatic anemia requires urgent evaluation.",
    examTraps: "Macrocytosis is not synonymous with folate deficiency; alcohol, liver disease, hypothyroidism, marrow disease, reticulocytosis, and medications belong in the differential.",
    sourceKeys: ["ASH_B12_FOLATE_CURRENT"],
  },
  {
    slug: "anticoagulation-management",
    title: "Anticoagulation Management",
    bodySystem: "Hematology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Anticoagulation decisions start with indication, thrombotic risk, bleeding risk, renal/hepatic function, age, weight, interactions, adherence, upcoming procedures, and pregnancy—not with a favorite drug.",
    diagnostics: "Confirm the indication and dose criteria; trend CBC and renal/hepatic function at clinically appropriate intervals. For bleeding, identify site/severity, last dose, interacting drugs, and available drug-specific reversal strategy.",
    priorities: "Use the right agent and duration for AF, VTE, mechanical valves, or other indications. Periprocedural interruption depends on drug half-life, renal function, procedure bleeding risk, and thrombosis risk; bridging is selective.",
    medicationSafety: "DOACs are not interchangeable by milligram dose. Warfarin has many food/drug interactions and requires INR monitoring. Mechanical valves and pregnancy have special anticoagulant rules.",
    redFlags: "Intracranial bleeding, hemodynamic GI bleeding, compartment syndrome, major trauma, or bleeding with shock requires immediate reversal/resuscitation pathways.",
    examTraps: "Do not stop anticoagulation permanently after every minor bleed. Also do not 'renal-dose' from memory without checking the specific indication and product criteria.",
    sourceKeys: ["ACC_ANTICOAG_CURRENT", "CHEST_ANTITHROMBOTIC_CURRENT"],
  },
  {
    slug: "osteoporosis",
    title: "Osteoporosis",
    bodySystem: "Musculoskeletal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "WHNP"],
    recognize: "Fragility fracture, height loss, vertebral compression, low bone density, or strong medication/secondary-risk history should trigger osteoporosis assessment; many patients are asymptomatic until fracture.",
    diagnostics: "Use age/risk-appropriate DXA and fracture-risk assessment. Check for secondary causes when indicated: calcium/vitamin D status, renal function, thyroid/parathyroid disease, hypogonadism, malabsorption, glucocorticoids, and other medications.",
    priorities: "Prioritize fall prevention, resistance/weight-bearing activity, adequate calcium/vitamin D intake, smoking/alcohol risk reduction, and pharmacotherapy for patients at sufficient fracture risk.",
    medicationSafety: "Bisphosphonates require administration counseling and renal/GI considerations; denosumab should not be stopped without a transition plan because rebound vertebral fractures can occur. Anabolic therapy is reserved for selected very-high-risk patients.",
    redFlags: "New severe back pain with neurologic deficit, hip fracture, or suspected pathologic fracture requires urgent evaluation.",
    examTraps: "Do not use a T-score alone in every premenopausal patient. A drug holiday is not appropriate for every osteoporosis medication—especially not denosumab.",
    sourceKeys: ["BHOF_OSTEOPOROSIS_CURRENT", "USPSTF_OSTEOPOROSIS_CURRENT"],
  },
  {
    slug: "osteoarthritis",
    title: "Osteoarthritis",
    bodySystem: "Musculoskeletal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "Activity-related joint pain, brief morning stiffness, crepitus, and bony enlargement in typical joints suggest OA. Inflammatory morning stiffness lasting a long time, systemic symptoms, or a hot swollen joint suggests another diagnosis.",
    diagnostics: "Diagnosis is often clinical. Obtain plain radiographs when diagnosis is uncertain, symptoms are atypical, trauma is relevant, or procedural/surgical planning is needed; routine MRI is rarely first-line.",
    priorities: "Exercise, strength training, weight management when relevant, topical/oral analgesic strategies, and function-focused self-management are foundational. Injection or orthopedic referral depends on severity and response.",
    medicationSafety: "Topical NSAIDs reduce systemic exposure; oral NSAIDs require GI, renal, cardiovascular, anticoagulant, and BP risk assessment. Avoid chronic opioid therapy for routine OA.",
    redFlags: "Hot acutely swollen joint, fever, inability to bear weight after trauma, or neurovascular compromise requires urgent evaluation.",
    examTraps: "Do not call every joint pain 'arthritis' or order autoimmune panels for classic OA. X-ray severity and pain severity often do not match.",
    sourceKeys: ["ACR_OA_CURRENT"],
  },
  {
    slug: "rheumatoid-arthritis",
    title: "Rheumatoid Arthritis",
    bodySystem: "Musculoskeletal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "Symmetric inflammatory small-joint pain/swelling with prolonged morning stiffness, reduced grip, and systemic features suggests RA. Early disease can have normal radiographs and negative serologies.",
    diagnostics: "Check inflammatory markers, rheumatoid factor and anti-CCP when the pattern supports RA, plus baseline CBC/CMP and infection screening guided by potential therapy. Diagnosis is clinical; serology supports but does not replace it.",
    priorities: "Refer early to rheumatology because disease-modifying therapy should not be delayed. Treat-to-target aims for remission/low disease activity while protecting function and vaccination/infection prevention.",
    medicationSafety: "DMARDs and biologics have marrow, hepatic, infection, pregnancy, and vaccination implications. Methotrexate is teratogenic and requires folate plus laboratory monitoring.",
    redFlags: "Septic arthritis, atlantoaxial instability symptoms, vasculitis, severe ocular inflammation, or major pulmonary involvement requires urgent evaluation.",
    examTraps: "Negative rheumatoid factor does not exclude RA. Chronic glucocorticoid monotherapy is not adequate disease-modifying treatment.",
    sourceKeys: ["ACR_RA_CURRENT"],
  },
  {
    slug: "low-back-pain-cauda-equina",
    title: "Low Back Pain & Cauda Equina Red Flags",
    bodySystem: "Musculoskeletal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Most acute low back pain is mechanical, but screen for cancer, infection, fracture, AAA, renal disease, progressive neurologic deficit, and cauda equina syndrome before reassuring.",
    diagnostics: "Routine imaging is not indicated for uncomplicated acute mechanical pain. Obtain urgent MRI when cauda equina, spinal infection, malignancy with cord compromise, or progressive neurologic deficit is suspected.",
    priorities: "Keep patients moving as tolerated, use nonpharmacologic measures and selective analgesics, and arrange follow-up. Radicular symptoms without major deficit often start with conservative care.",
    medicationSafety: "NSAIDs require renal/GI/CV review; muscle relaxants can sedate; opioids are rarely appropriate for routine acute low back pain and should not substitute for diagnostic escalation.",
    redFlags: "New urinary retention/overflow, saddle anesthesia, bilateral severe/progressive weakness, loss of anal tone, fever with spine pain, or major trauma requires emergency evaluation.",
    examTraps: "Do not use isolated back pain plus urinary frequency as 'cauda equina.' Conversely, do not wait for complete paralysis or incontinence before escalating true neurologic red flags.",
    sourceKeys: ["ACP_LOW_BACK_CURRENT", "AANS_CAUDA_EQUINA_CURRENT"],
  },
  {
    slug: "cellulitis-abscess",
    title: "Cellulitis & Skin Abscess",
    bodySystem: "Dermatology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PNP", "ENP"],
    recognize: "Cellulitis causes diffuse warmth, erythema, edema, and tenderness; abscess causes a focal purulent collection. Bilateral lower-leg redness is often not bacterial cellulitis.",
    diagnostics: "Diagnosis is usually clinical. Ultrasound can distinguish occult abscess from cellulitis. Culture purulent material in selected recurrent, severe, treatment-failure, or high-risk cases rather than swabbing intact skin.",
    priorities: "Drain a drainable abscess. Use antibiotics based on purulence, systemic signs, host factors, local resistance, and likely streptococcal/MRSA coverage; address tinea, edema, wounds, and recurrence risks.",
    medicationSafety: "Avoid unnecessary dual/overly broad antibiotics. Dose by renal function and allergy history; counsel about C. difficile and severe cutaneous reactions when relevant.",
    redFlags: "Pain out of proportion, bullae, crepitus, anesthesia, rapidly spreading edema, systemic toxicity, orbital involvement, or immunocompromised deterioration suggests necrotizing/deep infection and requires emergency care.",
    examTraps: "Incision and drainage—not antibiotics alone—is the primary therapy for many uncomplicated abscesses. Marked bilateral edema/erythema should prompt venous/stasis differential.",
    sourceKeys: ["IDSA_SSTI_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
