import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch65 = [
  {
    slug: "preconception-medication-optimization",
    title: "Preconception Counseling & Medication Optimization",
    bodySystem: "Women's Health",
    applicableExams: ["WHNP", "AANP-FNP", "ANCC-FNP", "PMHNP"],
    recognize: "Preconception care should begin before pregnancy is confirmed because organogenesis occurs early. Review chronic disease control, teratogens, folate needs, vaccines, genetic/family history, substance exposure, occupational risk and reproductive goals at routine visits.",
    diagnostics: "Confirm medication indication and safer alternatives, screen diabetes/BP/thyroid and immunity/infection risks according to history and offer carrier screening/genetic counseling based on current guidance and patient preference. Do not order broad panels without informed interpretation plans.",
    priorities: "Optimize diabetes, hypertension, epilepsy, psychiatric and autoimmune disease before conception, start folic acid at risk-appropriate dose, update non-live vaccines and transition known teratogens such as ACEi/ARB, methotrexate, valproate or isotretinoin when clinically feasible before pregnancy.",
    medicationSafety: "Do not abruptly stop essential antiseizure, psychiatric or immunosuppressive therapy without a safer plan; uncontrolled maternal disease also harms pregnancy. Use current pregnancy/lactation evidence rather than obsolete FDA letter categories.",
    redFlags: "Pregnancy while taking a high-risk teratogen, severe uncontrolled chronic disease or prior catastrophic pregnancy complication requires prompt maternal-fetal/specialist consultation.",
    examTraps: "Do not wait for a positive pregnancy test to review teratogenic medications in a patient who could become pregnant, and do not assume every medication must be stopped because pregnancy is desired.",
    sourceKeys: ["ACOG_PREPREGNANCY_CURRENT", "FDA_PLLR_CURRENT"],
  },
  {
    slug: "prenatal-genetic-screening-diagnostic-testing",
    title: "Prenatal Genetic Screening & Diagnostic Testing",
    bodySystem: "Women's Health",
    applicableExams: ["WHNP", "AANP-FNP", "ANCC-FNP"],
    recognize: "All pregnant patients should be offered prenatal screening and diagnostic-testing options regardless of age or baseline risk. Screening estimates probability; chorionic-villus sampling and amniocentesis can provide diagnostic information but are invasive.",
    diagnostics: "Discuss cell-free DNA/NIPT, first-/second-trimester serum/ultrasound approaches and anatomic ultrasound without stacking multiple independent aneuploidy screens. A positive cfDNA result requires diagnostic confirmation before irreversible pregnancy decisions because positive predictive value depends on pretest risk.",
    priorities: "Use nondirective counseling about conditions screened, limitations, possible results and follow-up; refer abnormal ultrasound/screening to genetics/MFM and offer CVS or amniocentesis according to gestational age and patient preference.",
    medicationSafety: "Screening tests do not themselves create medication risk, but invasive procedures and Rh status require procedure-specific planning; Rh(D)-negative patients may need anti-D prophylaxis depending on procedure/current recommendations.",
    redFlags: "Major fetal structural anomaly, strongly positive screen, hydrops or maternal condition with urgent fetal implications requires expedited MFM/genetic evaluation.",
    examTraps: "cfDNA is a screening test, not diagnostic, and a negative screen does not guarantee an unaffected fetus. Do not perform multiple simultaneous aneuploidy screening strategies that increase false positives.",
    sourceKeys: ["ACOG_PRENATAL_GENETIC_SCREENING_CURRENT", "SMFM_CF_DNA_CURRENT"],
  },
  {
    slug: "early-pregnancy-loss-management",
    title: "Early Pregnancy Loss Management",
    bodySystem: "Women's Health",
    applicableExams: ["WHNP", "AANP-FNP", "ANCC-FNP", "ENP"],
    recognize: "Vaginal bleeding/cramping in early pregnancy may be viable intrauterine pregnancy, early loss, ectopic pregnancy or pregnancy of unknown location. Do not diagnose nonviability from one borderline ultrasound measurement or a single hCG value when criteria are not definitive.",
    diagnostics: "Use transvaginal ultrasound plus serial quantitative hCG when location/viability is uncertain; apply conservative validated ultrasound criteria for nonviability. Check Rh status and CBC/hemodynamics as indicated and continue ectopic precautions until an intrauterine pregnancy or resolved hCG trajectory is established.",
    priorities: "For confirmed uncomplicated loss, expectant, medication and uterine-aspiration management are all effective options; choose based on stability, gestational age, bleeding, patient preference and access. Mifepristone followed by misoprostol improves medication-management success when available.",
    medicationSafety: "Misoprostol causes expected cramping/bleeding/GI effects; counsel when bleeding exceeds expected limits and provide analgesia. Rh(D) immune-globulin recommendations for very early loss have evolved and should follow current ACOG/local guidance rather than outdated universal rules.",
    redFlags: "Hemodynamic instability, peritoneal pain, very heavy bleeding, fever/sepsis or pregnancy of unknown location with worsening symptoms requires emergency ectopic/hemorrhage evaluation.",
    examTraps: "Do not declare miscarriage from hCG failing to 'double' exactly and do not call a pregnancy loss complete until ectopic risk is resolved when no prior definite IUP was seen.",
    sourceKeys: ["ACOG_EARLY_PREGNANCY_LOSS_CURRENT"],
  },
  {
    slug: "ectopic-pregnancy-diagnosis-management",
    title: "Ectopic Pregnancy Diagnosis & Management",
    bodySystem: "Women's Health",
    applicableExams: ["WHNP", "AANP-FNP", "ANCC-FNP", "ENP"],
    recognize: "Any patient who can be pregnant with pelvic/abdominal pain, vaginal bleeding, syncope or shoulder pain requires ectopic pregnancy consideration. Risk factors increase probability but many ectopic pregnancies occur without known risk.",
    diagnostics: "Use pregnancy testing, quantitative hCG and transvaginal ultrasound; interpret the discriminatory concept cautiously and use serial trends when stable because viable IUPs can occasionally be missed at higher-than-expected hCG. Evaluate hemodynamics and hemoperitoneum rather than relying on hCG alone.",
    priorities: "Ruptured/unstable ectopic pregnancy requires emergency surgery. Stable unruptured disease can be treated with methotrexate when diagnostic certainty and selection criteria are met or surgery based on hCG, mass, fetal cardiac activity, follow-up reliability and patient preference.",
    medicationSafety: "Methotrexate is contraindicated with significant hepatic/renal/hematologic disease, breastfeeding and several other conditions and requires serial hCG until resolution; avoid folic acid, alcohol and pregnancy until the advised interval. Failure to follow hCG can miss rupture despite treatment.",
    redFlags: "Shock, peritoneal signs, significant free fluid, falling hemoglobin, severe pain/syncope or suspected rupture requires immediate operative care.",
    examTraps: "A falling hCG does not eliminate ectopic rupture risk until resolution and absence of an IUP above a single hCG cutoff is not by itself definitive ectopic pregnancy.",
    sourceKeys: ["ACOG_ECTOPIC_CURRENT"],
  },
  {
    slug: "recurrent-pregnancy-loss",
    title: "Recurrent Pregnancy Loss Evaluation",
    bodySystem: "Women's Health",
    applicableExams: ["WHNP", "AANP-FNP", "ANCC-FNP"],
    recognize: "Repeated clinically recognized pregnancy losses warrant evaluation for uterine anatomy, antiphospholipid syndrome, parental chromosomal factors and selected endocrine disease, while many losses still result from sporadic embryonic aneuploidy. Avoid blaming stress or routine activity.",
    diagnostics: "Confirm prior pregnancy documentation when possible, evaluate uterine cavity/anatomy, antiphospholipid antibodies using accepted laboratory criteria and parental karyotype selectively; check TSH and diabetes based on context. Routine inherited-thrombophilia panels, infection panels and broad immune testing are not recommended without specific indications.",
    priorities: "Treat a defined cause—uterine septum, uncontrolled endocrine disease or antiphospholipid syndrome—and provide early supportive pregnancy follow-up. Genetic counseling helps interpret parental rearrangements or products-of-conception testing and clarify recurrence risk.",
    medicationSafety: "Heparin plus low-dose aspirin benefits obstetric antiphospholipid syndrome but should not be prescribed empirically to every recurrent-loss patient. Progesterone benefit is phenotype-specific and not a universal treatment for unexplained loss.",
    redFlags: "Current pregnancy with bleeding/pain, severe APS thrombosis history or major uterine anomaly requires specialist/high-risk pregnancy management.",
    examTraps: "Do not order MTHFR testing or inherited-thrombophilia panels routinely for recurrent pregnancy loss and do not tell patients that normal evaluation means the losses were psychological.",
    sourceKeys: ["ASRM_RECURRENT_PREGNANCY_LOSS_CURRENT", "ACOG_APS_CURRENT"],
  },
  {
    slug: "hypertensive-disorders-pregnancy-risk-management",
    title: "Hypertensive Disorders of Pregnancy: Risk & Outpatient Management",
    bodySystem: "Women's Health",
    applicableExams: ["WHNP", "AANP-FNP", "ANCC-FNP", "AGACNP", "ENP"],
    recognize: "Chronic hypertension predates pregnancy/20 weeks; gestational hypertension begins after 20 weeks without preeclampsia features; preeclampsia can occur with severe BP or organ dysfunction even without proteinuria. Headache, visual symptoms, RUQ/epigastric pain and dyspnea are warning symptoms.",
    diagnostics: "Confirm BP correctly and assess CBC/platelets, creatinine, AST/ALT and urine protein using quantitative ratio/collection as appropriate; evaluate fetal growth/well-being and distinguish chronic baseline proteinuria from superimposed preeclampsia by change and organ features.",
    priorities: "Use aspirin prophylaxis for patients meeting current risk criteria beginning in the recommended gestational window, treat chronic hypertension with pregnancy-compatible agents and transfer severe-range BP or preeclampsia with severe features for obstetric management/delivery planning. Long-term postpartum cardiovascular follow-up matters.",
    medicationSafety: "ACE inhibitors/ARBs/ARNI and renin inhibitors are avoided in pregnancy; labetalol, nifedipine and methyldopa are commonly used according to context. Magnesium sulfate prevents/treats eclamptic seizures in severe disease but requires renal/respiratory monitoring.",
    redFlags: "Persistent severe-range BP, neurologic symptoms, pulmonary edema, severe thrombocytopenia/liver injury, eclampsia or fetal compromise requires emergency obstetric care.",
    examTraps: "Proteinuria is not required for preeclampsia with severe organ features and edema alone does not diagnose it. Postpartum preeclampsia can occur after discharge.",
    sourceKeys: ["ACOG_HYPERTENSION_PREGNANCY_CURRENT"],
  },
  {
    slug: "postpartum-contraception-lactation",
    title: "Postpartum Contraception & Lactation-Safe Prescribing",
    bodySystem: "Women's Health",
    applicableExams: ["WHNP", "AANP-FNP", "ANCC-FNP", "PNP"],
    recognize: "Ovulation can return before the first postpartum menses and lactational amenorrhea is effective contraception only when strict breastfeeding, amenorrhea and infant-age criteria are all met. Thrombosis risk and milk supply influence method timing.",
    diagnostics: "Clarify delivery date, breastfeeding intensity, VTE risk, BP, uterine infection/hemorrhage and reproductive goals; use CDC MEC/SPR postpartum categories rather than a universal waiting period for all methods.",
    priorities: "Offer immediate postpartum IUD/implant when desired and feasible, progestin-only and nonhormonal options broadly, and time estrogen-containing contraception according to postpartum VTE/breastfeeding risk. Use LactMed/current evidence to preserve breastfeeding while treating maternal disease.",
    medicationSafety: "Combined estrogen methods are contraindicated in the highest early-postpartum VTE-risk window and may affect milk supply; depot medroxyprogesterone and progestin methods have distinct bleeding/fertility-return profiles. Most antibiotics/analgesics are compatible with breastfeeding, while high-risk drugs require infant-specific assessment.",
    redFlags: "Postpartum chest pain/dyspnea, severe headache/BP, heavy bleeding, mastitis with sepsis or infant sedation/poor feeding from maternal medication requires urgent evaluation.",
    examTraps: "Breastfeeding alone is not reliable contraception unless all lactational-amenorrhea criteria are met and 'present in breast milk' does not automatically mean a medication is contraindicated.",
    sourceKeys: ["CDC_US_MEC_2024", "CDC_US_SPR_2024", "NIH_LACTMED_CURRENT"],
  },
  {
    slug: "lactational-mastitis-spectrum",
    title: "Lactational Mastitis & Abscess",
    bodySystem: "Women's Health",
    applicableExams: ["WHNP", "AANP-FNP", "ANCC-FNP", "PNP"],
    recognize: "The lactational mastitis spectrum begins with ductal inflammation/edema and can progress to bacterial mastitis, phlegmon or abscess. Focal breast pain/erythema with systemic symptoms suggests bacterial disease, while repeated aggressive massage/pumping can worsen inflammatory injury.",
    diagnostics: "Uncomplicated early mastitis is clinical; culture milk for severe/recurrent disease, hospital exposure, treatment failure or MRSA risk. Use ultrasound for persistent focal mass or abscess concern and investigate nonlactational/refractory inflammatory breast changes for malignancy.",
    priorities: "Continue physiologic breastfeeding/emptying without over-pumping, use ice/NSAID/supportive care for inflammation and add appropriate anti-staphylococcal antibiotics for bacterial mastitis. Drain abscess by image-guided aspiration/drainage while usually continuing breastfeeding.",
    medicationSafety: "Avoid deep tissue massage, excessive heat and repeated complete breast emptying that drive oversupply/inflammation. Choose antibiotics compatible with breastfeeding and local MRSA risk; probiotics/other adjuncts have evolving evidence and should not replace indicated therapy.",
    redFlags: "Sepsis, rapidly progressive erythema/necrosis, large abscess, immunocompromise or inflammatory changes not resolving with appropriate therapy requires urgent breast/surgical evaluation.",
    examTraps: "Do not instruct patients to stop breastfeeding routinely during mastitis and do not treat every plugged sensation with forceful massage or prophylactic antibiotics.",
    sourceKeys: ["ABM_MASTITIS_PROTOCOL_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
