import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch58 = [
  {
    slug: "trauma-primary-survey",
    title: "Trauma Primary Survey & Initial Resuscitation",
    bodySystem: "Emergency",
    applicableExams: ["ENP", "AGACNP", "AANP-FNP", "ANCC-FNP"],
    recognize: "Major trauma is managed by immediately identifying reversible threats in sequence while treatment occurs in parallel: catastrophic external hemorrhage, airway with cervical-spine protection, breathing, circulation/hemorrhage, disability and exposure/environment. Mechanism helps anticipate injury but never replaces physiology and examination.",
    diagnostics: "Use bedside exam, eFAST and immediately necessary x-rays/labs while resuscitation proceeds; obtain whole-body CT only when the patient is sufficiently stable for transport/imaging. Trend lactate/base deficit, temperature, ionized calcium and coagulation in major hemorrhage rather than waiting for hemoglobin to fall.",
    priorities: "Control massive external bleeding with direct pressure/tourniquet, secure a threatened airway, decompress tension pneumothorax without waiting for imaging and use balanced blood-component or whole-blood resuscitation for hemorrhagic shock with rapid operative/interventional source control. Prevent hypothermia and consider TXA early in appropriately bleeding trauma patients within the evidence-based time window.",
    medicationSafety: "Avoid large-volume crystalloid resuscitation that worsens dilutional coagulopathy, edema and hypothermia. TXA is not a routine drug for every injured patient and should not be started late outside evidence-based timing; analgesia/sedation must account for hypotension and neurologic assessment.",
    redFlags: "Airway compromise, tension pneumothorax, massive hemothorax, unstable pelvic injury, uncontrolled hemorrhage, tamponade, open skull/spine injury or persistent shock requires immediate trauma-team operative/interventional escalation.",
    examTraps: "Do not delay lifesaving treatment for imaging and do not let a normal initial hemoglobin reassure you during acute hemorrhage. Cervical collars do not substitute for proper spinal-motion restriction and repeated neurologic assessment.",
    sourceKeys: ["ACS_ATLS_CURRENT", "ACS_TRAUMA_BLOOD_CURRENT"],
  },
  {
    slug: "major-burn-resuscitation",
    title: "Major Burn Assessment & Resuscitation",
    bodySystem: "Emergency",
    applicableExams: ["ENP", "AGACNP", "AANP-FNP", "ANCC-FNP", "PNP"],
    recognize: "Assess burn depth, total body surface area and special locations while immediately identifying inhalation injury, circumferential compromise, electrical/chemical injury and associated trauma. Only partial- and full-thickness burns are included in formal resuscitation TBSA calculations; superficial erythema is not.",
    diagnostics: "Estimate TBSA with Lund-Browder or rule-of-nines approaches and obtain carboxyhemoglobin/co-oximetry when smoke/CO exposure is plausible; pulse oximetry can appear normal in carbon-monoxide poisoning. Check ECG/CK/electrolytes/urinalysis for significant electrical injury and consider cyanide toxicity in severe enclosed-space smoke exposure with profound lactic acidosis.",
    priorities: "Stop the burning process, cool briefly with running tap water when appropriate without inducing hypothermia, cover wounds, give strong analgesia, update tetanus and refer according to current burn-center criteria. For adults with large burns requiring formal fluid resuscitation, current ABA guidance starts crystalloid at a lower initial formula than classic 4 mL/kg/%TBSA and titrates hourly to physiologic response rather than blindly delivering a calculated total.",
    medicationSafety: "Avoid ice directly on major burns and avoid prophylactic systemic antibiotics in uncomplicated acute burns. Opioid requirements can be substantial but require respiratory/hemodynamic monitoring; escharotomy is a perfusion/ventilation procedure, not analgesic management.",
    redFlags: "Facial burns with soot/hoarseness/stridor, enclosed-space smoke injury, circumferential chest/limb compromise, electrical burn, major TBSA, chemical eye injury or pediatric/complex burn meeting referral criteria requires early burn-center consultation.",
    examTraps: "Do not use the classic Parkland 4 mL/kg/%TBSA as an inflexible adult rule and do not count first-degree erythema in resuscitation TBSA. Normal SpO2 does not rule out carbon-monoxide poisoning.",
    sourceKeys: ["ABA_BURN_SHOCK_2024", "ABA_REFERRAL_CURRENT"],
  },
  {
    slug: "toxic-alcohol-poisoning",
    title: "Toxic Alcohol Poisoning",
    bodySystem: "Emergency",
    applicableExams: ["ENP", "AGACNP"],
    recognize: "Methanol and ethylene glycol can initially resemble ethanol intoxication then produce severe high-anion-gap metabolic acidosis, visual toxicity with methanol or renal/hypocalcemic injury with ethylene glycol. Isopropanol typically causes ketosis without high-anion-gap acidosis.",
    diagnostics: "Obtain blood gas, electrolytes/anion gap, measured osmolality/osmol gap, ethanol level, renal function, calcium and specific toxic-alcohol levels when available. A normal osmol gap later in poisoning does not exclude methanol/ethylene glycol because parent alcohol has already been metabolized to toxic acids.",
    priorities: "Contact poison control/toxicology early and give fomepizole promptly when methanol/ethylene glycol exposure is strongly suspected rather than waiting for a send-out level. Correct severe acidosis, provide folate for methanol or thiamine/pyridoxine for ethylene glycol as adjuncts and initiate hemodialysis for severe acidosis, end-organ toxicity, high concentration or other guideline indications.",
    medicationSafety: "Fomepizole dosing changes during dialysis because the drug is removed; ethanol is an alternative antidote only when fomepizole is unavailable and requires intensive level/glucose monitoring. Bicarbonate is supportive for severe acidemia but does not replace alcohol-dehydrogenase blockade or dialysis.",
    redFlags: "Visual symptoms, coma/seizure, severe acidemia, AKI/oliguria, refractory electrolyte abnormality or cardiovascular collapse requires emergency dialysis/toxicology care.",
    examTraps: "Do not rule out toxic alcohols because the osmol gap is normal and do not call every high osmol gap toxic-alcohol poisoning when ethanol, ketoacidosis or critical illness can contribute.",
    sourceKeys: ["ACMT_TOXIC_ALCOHOL_CURRENT", "AACT_TOXIC_ALCOHOL_CURRENT"],
  },
  {
    slug: "salicylate-poisoning",
    title: "Salicylate Poisoning",
    bodySystem: "Emergency",
    applicableExams: ["ENP", "AGACNP", "AANP-FNP", "ANCC-FNP"],
    recognize: "Tinnitus, tachypnea, diaphoresis, nausea/vomiting, fever and altered mental status with a mixed respiratory alkalosis plus anion-gap metabolic acidosis suggests salicylate toxicity. Chronic toxicity in older adults can present with delirium, pulmonary edema and only modest serum levels.",
    diagnostics: "Obtain serial salicylate concentrations, blood gas, electrolytes, glucose, renal function and ECG; interpret level against timing, acid-base status and symptoms. Falling serum concentration does not guarantee improvement if acidemia drives salicylate into CNS tissue.",
    priorities: "Give activated charcoal when appropriate and airway-protected, correct potassium and alkalinize serum/urine with IV sodium bicarbonate to reduce CNS penetration and enhance renal elimination. Start hemodialysis for severe neurologic/pulmonary toxicity, major acidemia, renal failure, inability to alkalinize or other toxicology criteria.",
    medicationSafety: "Intubation is high-risk because loss of compensatory hyperventilation can abruptly acidify the patient and increase brain salicylate; if unavoidable, maintain very high minute ventilation and alkalemia around the procedure. Avoid acetazolamide because systemic acidosis can worsen tissue toxicity.",
    redFlags: "Altered mental status, pulmonary edema, severe acidemia, renal failure, seizure or rapidly rising level requires urgent toxicology/dialysis management.",
    examTraps: "Do not use one numeric salicylate level as the dialysis decision and do not casually intubate a tachypneic salicylate-poisoned patient without preserving their compensatory ventilation.",
    sourceKeys: ["ACMT_SALICYLATE_CURRENT"],
  },
  {
    slug: "opioid-overdose-resuscitation",
    title: "Opioid Overdose Resuscitation",
    bodySystem: "Emergency",
    applicableExams: ["ENP", "AGACNP", "AANP-FNP", "ANCC-FNP", "PMHNP", "PNP"],
    recognize: "Respiratory depression with reduced consciousness and often miosis suggests opioid toxicity, but mixed ingestions, hypoglycemia, stroke and clonidine/sedative poisoning can mimic it. Fentanyl-era overdoses may require repeated naloxone because potency/duration exceed the first dose.",
    diagnostics: "Diagnosis is primarily clinical; check glucose and use targeted ECG/labs/imaging for coingestion, trauma or persistent altered mental status. Standard urine opioid immunoassays may miss fentanyl and many synthetic opioids and should not determine whether naloxone is given.",
    priorities: "Open/ventilate the airway first and administer titrated naloxone to restore adequate spontaneous ventilation rather than necessarily full alertness; repeat dosing or infusion is used for recurrent respiratory depression. Observe for renarcotization based on the opioid, response and coingestants and offer take-home naloxone plus evidence-based OUD treatment after recovery.",
    medicationSafety: "Large abrupt naloxone doses can precipitate severe withdrawal, vomiting/agitation and rare pulmonary complications, but adequate ventilation takes priority in apnea. Buprenorphine treatment can be started from the ED using an appropriate withdrawal/low-dose strategy; no federal X-waiver is required.",
    redFlags: "Persistent apnea/hypoxia, recurrent sedation, aspiration, pulmonary edema, body-packer exposure, long-acting opioid or severe polysubstance poisoning requires monitored inpatient care.",
    examTraps: "A negative routine opioid screen does not exclude fentanyl and naloxone response does not rule out dangerous coingestants. The endpoint is breathing, not necessarily complete reversal of analgesia/dependence.",
    sourceKeys: ["AHA_OPIOID_OVERDOSE_CURRENT", "SAMHSA_NALOXONE_CURRENT", "SAMHSA_MAT_ACT_CURRENT"],
  },
  {
    slug: "heat-stroke",
    title: "Heat Stroke & Severe Heat Illness",
    bodySystem: "Emergency",
    applicableExams: ["ENP", "AGACNP", "AANP-FNP", "ANCC-FNP", "PNP"],
    recognize: "Heat stroke is life-threatening hyperthermia with central nervous system dysfunction—confusion, ataxia, seizure or coma—after environmental/exertional heat exposure. Sweating may be present, especially in exertional heat stroke; dry skin is not required.",
    diagnostics: "Measure core temperature rectally when possible and assess glucose, electrolytes, kidney/liver function, CK, coagulation and lactate for organ injury/rhabdomyolysis/DIC. Do not delay cooling while waiting for laboratory confirmation.",
    priorities: "Start immediate rapid cooling; cold-water immersion is preferred for exertional heat stroke when feasible, while evaporative/other external cooling is used when immersion is impractical. Remove clothing, support ABCs and stop active cooling as core temperature approaches a safe range to avoid overshoot hypothermia.",
    medicationSafety: "Antipyretics such as acetaminophen do not treat heat stroke because the hypothalamic set point is not the problem and can add liver injury. Benzodiazepines can control shivering/seizures when needed; avoid vasoconstricting strategies that impair heat loss.",
    redFlags: "CNS dysfunction with hyperthermia, shock, DIC, rhabdomyolysis, AKI, hepatic failure or persistent temperature elevation requires emergency/ICU care.",
    examTraps: "Do not require an exact temperature cutoff after prehospital cooling and do not withhold the diagnosis because the patient is sweating. Cooling is the treatment—antipyretics are not.",
    sourceKeys: ["CDC_HEAT_STROKE_CURRENT", "WMS_HEAT_ILLNESS_CURRENT"],
  },
  {
    slug: "accidental-hypothermia",
    title: "Accidental Hypothermia",
    bodySystem: "Emergency",
    applicableExams: ["ENP", "AGACNP", "AANP-FNP", "ANCC-FNP", "PNP"],
    recognize: "Core hypothermia can progress from shivering and impaired judgment to bradycardia, hypoventilation, arrhythmia and coma. Intoxication, endocrine disease, sepsis, older age and wet/windy exposure can cause hypothermia even without extreme ambient cold.",
    diagnostics: "Measure core temperature with a low-reading probe when possible, obtain ECG/glucose/electrolytes/renal/CK and evaluate trauma, intoxication, sepsis and endocrine causes. Handle severely hypothermic patients gently because the myocardium is irritable.",
    priorities: "Remove wet clothing, insulate and use active external warming for moderate disease and warmed IV fluids/airway gases when indicated; severe unstable hypothermia may require invasive/internal rewarming or extracorporeal support. Continue resuscitation according to hypothermia-specific algorithms because profound cold can mimic death.",
    medicationSafety: "Avoid rough movement and unnecessary central-line manipulation that can trigger dysrhythmia. Drug metabolism is reduced in severe hypothermia and standard resuscitation-medication intervals may need hypothermia-specific adjustment.",
    redFlags: "Cardiac arrest, ventricular arrhythmia, severe bradycardia with instability, core temperature in the severe range, major trauma or failure to rewarm requires expert/ECMO-capable consultation.",
    examTraps: "Do not assume absence of shivering means improvement—it can mark severe hypothermia. 'No one is dead until warm and dead' is not absolute, but it reflects the need for prolonged resuscitative consideration absent clearly unsurvivable injury.",
    sourceKeys: ["AHA_HYPOTHERMIA_CURRENT", "WMS_HYPOTHERMIA_CURRENT"],
  },
  {
    slug: "drowning-resuscitation",
    title: "Drowning & Submersion Injury",
    bodySystem: "Emergency",
    applicableExams: ["ENP", "AGACNP", "AANP-FNP", "ANCC-FNP", "PNP"],
    recognize: "Drowning is respiratory impairment from submersion/immersion; hypoxemia is the primary injury and can progress to cardiac arrest, aspiration-related lung injury, cerebral hypoxia and later respiratory deterioration. Freshwater versus saltwater does not meaningfully change the initial resuscitation algorithm.",
    diagnostics: "Assess oxygenation, ventilation, temperature, neurologic status and trauma risk; chest x-ray and labs are reserved for symptomatic/moderate-severe cases rather than mandatory in every minimally symptomatic survivor. Cervical-spine precautions are used only when trauma mechanism is plausible.",
    priorities: "Provide immediate rescue breathing/CPR emphasizing oxygenation and ventilation, use high-concentration oxygen and escalate ventilatory support as needed. Rewarm hypothermic patients, observe symptomatic survivors for respiratory deterioration and use standard ARDS principles when lung injury develops.",
    medicationSafety: "Prophylactic antibiotics are not recommended after routine drowning unless grossly contaminated water or clinical infection justifies them; corticosteroids are not routine. Diuretics do not treat noncardiogenic aspiration lung injury.",
    redFlags: "Persistent hypoxemia, respiratory distress, altered mental status, cardiac arrest, severe hypothermia or significant trauma requires emergency/ICU care.",
    examTraps: "Do not perform abdominal thrusts to 'remove water' before ventilation and do not distinguish treatment by freshwater versus saltwater. A patient who initially feels well can still require observation when respiratory symptoms occurred.",
    sourceKeys: ["AHA_DROWNING_2024", "ILCOR_DROWNING_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
