import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch43 = [
  {
    slug: "atopic-dermatitis-management",
    title: "Atopic Dermatitis: Diagnosis & Stepwise Management",
    bodySystem: "Integumentary",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PNP"],
    recognize: "Atopic dermatitis is a chronic relapsing pruritic eczematous disease with age-dependent distribution and impaired skin barrier. Flexural eczema, xerosis and personal/family atopy support the diagnosis, but contact dermatitis, scabies, psoriasis, immunodeficiency and cutaneous infection can mimic it.",
    diagnostics: "Diagnosis is clinical; routine IgE or food-allergy panels do not diagnose AD and can create unnecessary dietary restriction. Patch testing is considered for suspected allergic contact dermatitis, and bacterial/viral testing is reserved for superinfection or eczema herpeticum concern.",
    priorities: "Use daily emollients, trigger/irritant reduction and adequate topical anti-inflammatory therapy during flares; choose topical corticosteroid potency to site/age/severity and add calcineurin/PDE4/JAK topical options when appropriate. Moderate-severe refractory disease warrants dermatology evaluation for phototherapy, biologic or oral targeted therapy.",
    medicationSafety: "Potent topical corticosteroids can cause atrophy/striae when overused on thin skin; topical calcineurin inhibitors are steroid-sparing for face/folds. Systemic JAK inhibitors carry serious infection, thrombosis, malignancy and laboratory-monitoring warnings and are not casual first-line therapy.",
    redFlags: "Painful monomorphic vesicles/erosions, fever, rapidly spreading infection, ocular involvement or toxic appearance suggests eczema herpeticum or invasive infection and requires urgent antiviral/infectious evaluation.",
    examTraps: "Do not prescribe elimination diets from nonspecific food IgE results and do not under-treat inflammation because of generalized 'steroid fear.' Moisturizer alone is not adequate for an active moderate flare.",
    sourceKeys: ["AAD_ATOPIC_DERMATITIS_CURRENT"],
  },
  {
    slug: "psoriasis-systemic-management",
    title: "Psoriasis: Systemic & Biologic Management",
    bodySystem: "Integumentary",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "Well-demarcated erythematous plaques with scale on extensor surfaces/scalp, nail pitting or inverse/intertriginous disease suggests psoriasis; ask about morning stiffness, dactylitis and enthesitis because psoriatic arthritis can precede or accompany skin disease.",
    diagnostics: "Diagnosis is usually clinical; biopsy is reserved for uncertainty. Assess body-surface area plus high-impact sites and quality-of-life burden, screen for psoriatic arthritis and cardiometabolic disease, and obtain TB/hepatitis/lab testing appropriate to the planned systemic agent.",
    priorities: "Use topical corticosteroid/vitamin-D or other topical therapy for limited disease and escalate moderate-severe/high-impact disease to phototherapy, conventional systemic therapy or targeted biologic/oral agents through shared decision-making. Treat psoriatic arthritis early to prevent structural damage.",
    medicationSafety: "Methotrexate carries hepatic, marrow and pregnancy toxicity; cyclosporine causes nephrotoxicity/hypertension; biologics/targeted agents have class-specific infection and immune risks. Live vaccines may be inappropriate during significant immunosuppression.",
    redFlags: "Generalized pustular psoriasis with systemic illness, erythroderma, severe infection on immunosuppression or rapidly destructive arthritis requires urgent specialist/inpatient care.",
    examTraps: "Do not use systemic corticosteroid bursts routinely for plaque psoriasis because withdrawal can destabilize disease, and do not judge severity only by BSA when palms, soles, genitals, face or joints are involved.",
    sourceKeys: ["AAD_NPF_PSORIASIS_CURRENT"],
  },
  {
    slug: "acne-rosacea-management",
    title: "Acne & Rosacea: Treatment Selection",
    bodySystem: "Integumentary",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PNP", "WHNP"],
    recognize: "Acne has comedones with inflammatory papules/pustules or nodules; rosacea causes central facial erythema, flushing, telangiectasia and inflammatory lesions without comedones. Sudden severe acne in a hyperandrogenic patient can signal PCOS or another endocrine cause.",
    diagnostics: "Both are usually clinical. Assess scarring, psychosocial burden, pregnancy potential, medication/cosmetic exposures and androgen symptoms; eye irritation or blepharitis suggests ocular rosacea and may need ophthalmology involvement.",
    priorities: "Use topical retinoid plus benzoyl peroxide and/or topical antimicrobial strategies for acne, adding limited-duration oral doxycycline for moderate-severe inflammatory disease and isotretinoin for severe scarring/refractory disease. Rosacea therapy is phenotype-directed with topical agents, oral doxycycline and vascular laser/light options when appropriate.",
    medicationSafety: "Avoid antibiotic monotherapy for acne and combine topical/oral antibiotics with benzoyl peroxide to reduce resistance. Isotretinoin is highly teratogenic and requires current pregnancy-prevention program requirements; tetracyclines are avoided in pregnancy and can cause photosensitivity/esophagitis.",
    redFlags: "Fulminant acne with systemic symptoms, severe ocular pain/vision change, rapidly progressive facial infection or severe isotretinoin adverse effects requires urgent specialty reassessment.",
    examTraps: "Rosacea has no comedones, and acne antibiotics should not be continued indefinitely. Do not prescribe topical retinoids during pregnancy.",
    sourceKeys: ["AAD_ACNE_CURRENT", "AAD_ROSACEA_CURRENT"],
  },
  {
    slug: "hidradenitis-suppurativa",
    title: "Hidradenitis Suppurativa",
    bodySystem: "Integumentary",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "WHNP"],
    recognize: "Recurrent painful deep nodules, abscesses, draining tunnels and scarring in axillae, groin, inframammary or other intertriginous sites strongly suggests hidradenitis suppurativa. It is a follicular inflammatory disease—not poor hygiene or repeated simple infection.",
    diagnostics: "Diagnosis is clinical from typical lesions, locations and recurrence. Culture only when secondary infection is suspected; assess Hurley severity, obesity, smoking, depression, metabolic disease, inflammatory bowel disease and inflammatory arthritis.",
    priorities: "Reduce friction/smoking, address weight and pain, use topical clindamycin or systemic tetracycline-class therapy for selected mild-moderate disease, and refer moderate-severe disease for biologic therapy, deroofing or wide excision. Incision and drainage alone gives temporary relief but high recurrence.",
    medicationSafety: "Long antibiotic courses require resistance/GI/C. difficile consideration; biologics require TB/hepatitis and infection screening. Avoid repeated short opioid courses as the primary chronic pain strategy.",
    redFlags: "Rapidly spreading cellulitis, sepsis, necrotizing infection, severe perineal disease or concern for squamous-cell carcinoma in a chronic scar/tunnel requires urgent evaluation.",
    examTraps: "Do not repeatedly label HS lesions as isolated MRSA abscesses and miss the chronic inflammatory diagnosis. Surgical drainage alone does not modify the underlying disease.",
    sourceKeys: ["AAD_HS_CURRENT"],
  },
  {
    slug: "skin-cancer-lesion-triage",
    title: "Melanoma, BCC & SCC Lesion Triage",
    bodySystem: "Integumentary",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "Melanoma concern rises with asymmetry, border irregularity, color variation, diameter/evolution or an 'ugly duckling'; BCC often appears pearly/telangiectatic and SCC can be scaly, keratotic, ulcerated or rapidly growing. Any changing or nonhealing lesion deserves morphology-based assessment rather than color alone.",
    diagnostics: "Perform complete lesion history/exam and dermoscopy when trained. Suspected melanoma should be sampled with an excisional-type biopsy including full lesion depth whenever feasible; avoid superficial shave sampling that prevents accurate Breslow depth when melanoma is strongly suspected.",
    priorities: "Refer melanoma and high-risk SCC promptly for definitive excision/staging; treat BCC/SCC according to size, site, histologic risk and immune status. Counsel high-risk patients on sun protection and skin surveillance.",
    medicationSafety: "Topical field therapies are reserved for selected superficial/precancerous disease and should not be substituted for biopsy of a potentially invasive melanoma or SCC. Immunosuppressed transplant patients need lower thresholds for dermatology referral.",
    redFlags: "Rapid growth, spontaneous bleeding/ulceration, neurologic symptoms near a lesion, palpable nodes, high-risk lip/ear lesion or changing pigmented lesion with melanoma features requires expedited dermatologic evaluation.",
    examTraps: "Diameter below 6 mm does not exclude melanoma and amelanotic melanoma may be pink/red. Do not freeze or empirically treat a suspicious lesion before obtaining diagnostic tissue.",
    sourceKeys: ["AAD_MELANOMA_CURRENT", "AAD_NMSC_CURRENT"],
  },
  {
    slug: "severe-cutaneous-drug-reactions",
    title: "Severe Cutaneous Adverse Drug Reactions",
    bodySystem: "Integumentary",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "SJS/TEN causes painful dusky targetoid lesions, epidermal detachment and mucosal erosions; DRESS causes delayed rash with fever, facial edema, eosinophilia and organ injury; AGEP causes acute pustular eruption. Timing and culprit drugs differ, but systemic symptoms separate these from a benign morbilliform rash.",
    diagnostics: "Stop nonessential suspect medications immediately and obtain CBC/differential, CMP/liver/kidney tests and disease-specific studies; calculate severity tools such as SCORTEN in SJS/TEN and involve dermatology for biopsy when diagnosis is uncertain.",
    priorities: "SJS/TEN needs burn/ICU-level supportive care, fluid/electrolyte/wound/ocular/genital management and specialist-directed immunomodulatory therapy. DRESS needs culprit withdrawal plus organ-directed therapy and prolonged follow-up because hepatitis, nephritis, myocarditis and late autoimmune sequelae can occur.",
    medicationSafety: "Never rechallenge the culprit in SJS/TEN. High-risk HLA testing before carbamazepine/allopurinol is ancestry- and guideline-specific; do not use negative testing to guarantee zero risk from unrelated mechanisms.",
    redFlags: "Skin pain, mucosal erosion, blistering/detachment, fever with organ injury, facial edema/eosinophilia, hypotension or ocular involvement requires emergency evaluation.",
    examTraps: "A widespread rash after a new medication is not automatically 'allergy'; distinguish benign exanthem from SCAR. SJS/TEN is defined by epidermal necrosis/detachment, not simply any rash with a mouth sore.",
    sourceKeys: ["AAD_SCAR_CURRENT", "FDA_SCAR_CURRENT"],
  },
  {
    slug: "chronic-urticaria-angioedema",
    title: "Chronic Urticaria & Angioedema",
    bodySystem: "Integumentary",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PNP", "ENP"],
    recognize: "Urticaria produces transient pruritic wheals that individually resolve within 24 hours; angioedema causes deeper swelling. Chronic spontaneous urticaria lasts more than 6 weeks and is often autoimmune/idiopathic rather than a persistent food allergy.",
    diagnostics: "Diagnosis is clinical with limited targeted testing; broad allergy panels, infection screens and food restriction are low yield without a specific exposure history. Angioedema without hives—especially recurrent abdominal/laryngeal episodes or ACE-inhibitor exposure—requires bradykinin-mediated causes in the differential.",
    priorities: "Use daily second-generation H1 antihistamines first and up-dose within guideline limits when needed; persistent chronic spontaneous urticaria may require omalizumab and specialist therapy. Anaphylaxis is treated immediately with IM epinephrine, while bradykinin angioedema requires cause-specific airway and targeted therapy.",
    medicationSafety: "First-generation antihistamines cause anticholinergic/sedating harms and are poor chronic daytime therapy. Steroid bursts do not treat the chronic disease mechanism and should not become repetitive maintenance; ACE inhibitor angioedema requires permanent ACEi avoidance.",
    redFlags: "Tongue/laryngeal swelling, voice change, stridor, hypotension, bronchospasm or rapidly progressive facial/oral swelling requires emergency airway/anaphylaxis management.",
    examTraps: "Chronic spontaneous urticaria is usually not caused by a single hidden food, and antihistamines do not reliably treat bradykinin-mediated angioedema. Hives lasting days in the same spot with bruising suggest urticarial vasculitis instead.",
    sourceKeys: ["AAAAI_URTICARIA_CURRENT", "AAAAI_ANGIOEDEMA_CURRENT"],
  },
  {
    slug: "herpes-zoster-postherpetic-neuralgia",
    title: "Herpes Zoster & Postherpetic Neuralgia",
    bodySystem: "Integumentary",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PNP", "ENP"],
    recognize: "Pain, burning or dysesthesia followed by a unilateral dermatomal vesicular eruption suggests herpes zoster. Disseminated lesions, cranial-nerve involvement, ophthalmic distribution or immunocompromise increase complication risk; persistent neuropathic pain after rash resolution is postherpetic neuralgia.",
    diagnostics: "Typical zoster is clinical; PCR from lesion material is used when presentation is atypical or confirmation matters. Ophthalmic zoster with eye symptoms needs urgent slit-lamp/ophthalmology evaluation; disseminated disease warrants immune-status and systemic assessment.",
    priorities: "Start oral antiviral therapy promptly—ideally within 72 hours, and later when new lesions or high-risk complications continue—using IV acyclovir for severe/disseminated/immunocompromised or CNS disease. Treat neuropathic pain with evidence-based agents and prevent disease with recombinant zoster vaccination according to current CDC recommendations.",
    medicationSafety: "Acyclovir/valacyclovir require renal dose adjustment and hydration awareness; gabapentinoids cause sedation/edema and require renal dosing. Systemic corticosteroids are not routine standalone zoster treatment and do not prevent postherpetic neuralgia.",
    redFlags: "Eye pain/vision change, facial paralysis with ear lesions, disseminated rash, meningitis/encephalitis, motor weakness or severe immunocompromise requires urgent specialty/inpatient care.",
    examTraps: "Do not withhold recombinant zoster vaccine because a patient had prior shingles once recovery timing is appropriate. Zoster can occur without a classic rash, but 'zoster sine herpete' is a diagnosis requiring caution rather than a label for every dermatomal pain.",
    sourceKeys: ["CDC_SHINGLES_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
