import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch20 = [
  {
    slug: "adult-obesity-management",
    title: "Adult Obesity Management",
    bodySystem: "Endocrine",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "WHNP"],
    recognize: "Obesity is a chronic relapsing disease defined by excess adiposity and health impact, not a character flaw. Assess weight trajectory, waist/adiposity pattern, medications, sleep, eating disorder symptoms, mental health and obesity-related complications.",
    diagnostics: "Use BMI as a screening measure while evaluating BP, diabetes, lipids, MASLD, sleep apnea, osteoarthritis, reproductive issues and other complications. Endocrine testing is targeted to clinical clues rather than ordered routinely for every patient.",
    priorities: "Offer intensive nutrition, activity, sleep and behavioral support plus anti-obesity pharmacotherapy when criteria are met; consider metabolic/bariatric surgery for appropriate severe disease. Treatment goals include cardiometabolic and functional improvement, not only scale weight.",
    medicationSafety: "GLP-1 or dual incretin therapies can cause GI effects, gallbladder disease and rare pancreatitis concerns and have pregnancy restrictions; sympathomimetic agents affect BP/HR and have contraindications. Weight regain after medication withdrawal is common.",
    redFlags: "Severe hyperglycemia, obesity hypoventilation, unstable cardiovascular disease, suicidality/eating disorder, or acute gallbladder/pancreatitis symptoms requires targeted urgent care.",
    examTraps: "Do not withhold evidence-based pharmacotherapy until lifestyle has 'failed' for years. Short stature or poor linear growth—not obesity alone—is the classic clue to many endocrine causes.",
    sourceKeys: ["AACE_OBESITY_CURRENT", "AGA_OBESITY_PHARM_CURRENT"],
  },
  {
    slug: "thyroid-nodules-cancer",
    title: "Thyroid Nodules & Thyroid Cancer",
    bodySystem: "Endocrine",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "A palpable or incidental thyroid nodule is common; concern rises with radiation exposure, family history, rapid growth, fixation, cervical nodes, hoarseness, dysphagia, or suspicious ultrasound features.",
    diagnostics: "Check TSH first; a suppressed TSH usually prompts radionuclide evaluation, while normal/high TSH proceeds through risk-stratified ultrasound and FNA thresholds. Ultrasound pattern and size—not palpability alone—drive biopsy decisions.",
    priorities: "Refer suspicious cytology, compressive disease, high-risk nodules or thyroid cancer to endocrinology/surgery. Low-risk nodules can be followed with interval ultrasound according to sonographic category and prior cytology.",
    medicationSafety: "Do not use suppressive levothyroxine routinely for benign nodules because atrial fibrillation and bone risks can outweigh benefit. Radioactive iodine is contraindicated during pregnancy and lactation.",
    redFlags: "Airway compromise, rapidly enlarging painful neck mass, vocal-cord dysfunction, bulky nodes, or severe compressive symptoms requires urgent evaluation.",
    examTraps: "A 'cold' nodule is not automatically cancer and a 'hot' autonomous nodule is rarely malignant but causes thyroid-function issues. Do not biopsy solely because a nodule exceeds one universal size threshold.",
    sourceKeys: ["ATA_THYROID_NODULE_CURRENT"],
  },
  {
    slug: "hyperparathyroidism-hypercalcemia",
    title: "Hyperparathyroidism & Hypercalcemia",
    bodySystem: "Endocrine",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Hypercalcemia may cause constipation, polyuria, stones, weakness, cognitive change or arrhythmia but is often incidental. Primary hyperparathyroidism usually shows inappropriately high or nonsuppressed PTH; malignancy and medications are key alternatives.",
    diagnostics: "Confirm corrected or ionized calcium, then measure PTH, creatinine/eGFR, phosphate and vitamin D. Low-PTH hypercalcemia triggers malignancy, vitamin D excess, granulomatous and medication evaluation; urine calcium helps distinguish selected familial syndromes.",
    priorities: "Severe symptomatic hypercalcemia needs IV isotonic fluid and cause-directed therapy; primary hyperparathyroidism is referred for parathyroidectomy when guideline criteria are met. Monitor kidney and bone complications when managed conservatively.",
    medicationSafety: "Thiazides and lithium can worsen or reveal hypercalcemia. Bisphosphonates act slowly and require renal awareness; calcitonin works rapidly but tachyphylaxis limits duration.",
    redFlags: "Marked hypercalcemia with altered mental status, dehydration, severe AKI, arrhythmia, pancreatitis, or malignancy-associated crisis requires emergency management.",
    examTraps: "Do not interpret PTH as 'normal' when calcium is high; it should be suppressed. A neck ultrasound localizes a known parathyroid lesion but does not diagnose primary hyperparathyroidism.",
    sourceKeys: ["ENDOCRINE_HYPERPARATHYROID_CURRENT"],
  },
  {
    slug: "pituitary-adenoma-prolactinoma",
    title: "Pituitary Adenoma & Prolactinoma",
    bodySystem: "Endocrine",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "WHNP"],
    recognize: "Headache, visual-field loss, amenorrhea/galactorrhea, infertility, hypogonadism, acromegalic change or cortisol excess may indicate a pituitary lesion. Medication-induced hyperprolactinemia is common and must be separated from tumor disease.",
    diagnostics: "Measure prolactin and other pituitary axes according to symptoms, review pregnancy and dopamine-antagonist medications, and obtain pituitary MRI when indicated. Very large tumors with only modest prolactin can reflect assay hook effect or stalk compression.",
    priorities: "Dopamine agonists are first-line for most prolactinomas, while other functional or compressive adenomas often need endocrine/neurosurgical management. Replace deficient adrenal/thyroid hormones in the correct sequence.",
    medicationSafety: "Cabergoline can cause nausea, orthostasis and rarely valvular issues at high cumulative doses. Starting thyroid hormone before treating significant secondary adrenal insufficiency can precipitate adrenal crisis.",
    redFlags: "Sudden severe headache, visual loss, ophthalmoplegia, hypotension or altered mental status suggests pituitary apoplexy and requires emergency endocrine/neurosurgical care.",
    examTraps: "Do not order pituitary MRI for a mildly elevated prolactin before checking pregnancy, hypothyroidism and medications. Antipsychotic-related hyperprolactinemia should not be managed by abruptly stopping necessary therapy without psychiatric coordination.",
    sourceKeys: ["ENDOCRINE_PITUITARY_CURRENT"],
  },
  {
    slug: "siadh-diabetes-insipidus",
    title: "SIADH & Diabetes Insipidus",
    titleAliases: ["Sodium Disorders: Osmoregulation"],
    slugAliases: ["siadh-di-np"],
    bodySystem: "Endocrine",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "SIADH causes hypotonic euvolemic hyponatremia with inappropriately concentrated urine; diabetes insipidus causes polyuria with dilute urine and often hypernatremia when water access is inadequate. Both require exclusion of mimics.",
    diagnostics: "Pair serum sodium/osmolality with urine osmolality and urine sodium, review glucose, adrenal and thyroid status, kidney function and medications. DI subtype may require supervised water-deprivation or copeptin-based testing rather than casual fluid restriction.",
    priorities: "Treat severe symptomatic hyponatremia with carefully monitored hypertonic saline, then address SIADH cause and fluid strategy. Central DI uses desmopressin and water replacement; nephrogenic disease requires cause-specific treatment.",
    medicationSafety: "Overrapid chronic hyponatremia correction risks osmotic demyelination; excess desmopressin plus free water can cause dangerous hyponatremia. Lithium is a classic cause of nephrogenic DI.",
    redFlags: "Seizure, coma, severe sodium abnormality, rapid sodium change, profound dehydration, or neurologic deterioration requires emergency monitoring and correction.",
    examTraps: "Do not diagnose SIADH before excluding adrenal insufficiency and hypothyroidism. Polyuria from uncontrolled diabetes mellitus is osmotic diuresis, not diabetes insipidus.",
    sourceKeys: ["ENDOCRINE_HYPONATREMIA_CURRENT", "ENDOCRINE_DI_CURRENT"],
  },
  {
    slug: "diabetic-neuropathy-foot-care",
    title: "Diabetic Neuropathy & Foot Disease",
    bodySystem: "Endocrine",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PNP"],
    recognize: "Distal symmetric burning, numbness or loss of protective sensation plus callus, deformity, ulcer or infection risk suggests diabetic neuropathy/foot disease. Autonomic neuropathy may cause orthostasis, gastroparesis, bladder or sexual dysfunction.",
    diagnostics: "Perform annual or indicated monofilament plus another neurologic modality, inspect skin/nails/pulses/deformity, and assess PAD. Evaluate B12, thyroid, alcohol, medications or other neuropathy causes when the pattern is atypical.",
    priorities: "Optimize glycemia and cardiovascular risk, provide daily foot-care education, podiatry/offloading for high-risk feet, wound care and vascular assessment for ulcers, and evidence-based neuropathic pain therapy.",
    medicationSafety: "Gabapentinoids require renal dosing and can sedate; duloxetine has hepatic and interaction considerations; tricyclics increase anticholinergic/cardiac risk. Avoid opioids as routine chronic neuropathic-pain therapy.",
    redFlags: "Deep infected ulcer, systemic infection, ischemic rest pain, gangrene, rapidly spreading cellulitis or suspected osteomyelitis requires urgent multidisciplinary care.",
    examTraps: "A painless ulcer can be more dangerous because neuropathy masks injury. Do not attribute asymmetric motor-predominant neuropathy automatically to diabetes.",
    sourceKeys: ["ADA_2026", "IWGDF_CURRENT"],
  },
  {
    slug: "diabetic-kidney-disease",
    title: "Diabetic Kidney Disease",
    bodySystem: "Endocrine",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "Persistent albuminuria and/or reduced eGFR in diabetes commonly reflects DKD, but hematuria, rapid eGFR loss, abrupt nephrotic syndrome, short diabetes duration or systemic findings should trigger alternative renal diagnoses.",
    diagnostics: "Screen with urine albumin-to-creatinine ratio and eGFR at guideline intervals, confirm persistent abnormal albuminuria, and monitor potassium/BP. Consider nephrology when progression is rapid, etiology is uncertain or kidney function is advanced.",
    priorities: "Use BP control, ACEi/ARB for appropriate albuminuric hypertension, SGLT2 inhibitors for kidney/cardiovascular protection when eligible, glycemic optimization and selected finerenone/GLP-1-based therapy according to current risk and contraindications.",
    medicationSafety: "Expect a modest initial eGFR dip with SGLT2 or RAAS therapy but monitor for excessive decline, hyperkalemia and volume depletion. Hold SGLT2 inhibitors around major fasting/illness situations that raise ketoacidosis risk.",
    redFlags: "Rapid kidney decline, refractory hyperkalemia, pulmonary edema, nephritic sediment, severe nephrotic syndrome or uremic symptoms requires urgent nephrology evaluation.",
    examTraps: "Do not wait for reduced eGFR before recognizing albuminuric DKD. A normal dipstick can miss moderately increased albuminuria; use UACR.",
    sourceKeys: ["ADA_2026", "KDIGO_CKD_2024"],
  },
  {
    slug: "endocrine-secondary-hypertension",
    title: "Endocrine Causes of Secondary Hypertension",
    bodySystem: "Endocrine",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "Resistant or abrupt hypertension, hypokalemia, episodic headache/palpitations/diaphoresis, cushingoid features, adrenal mass or young onset should prompt secondary endocrine evaluation rather than endless medication escalation.",
    diagnostics: "Use aldosterone-renin ratio for appropriate primary aldosteronism screening, plasma or urine metanephrines for pheochromocytoma when indicated, and validated cortisol-excess testing rather than random cortisol. Review medications that distort testing.",
    priorities: "Confirm abnormal screens with specialty-guided testing, localize only after biochemical evidence, and treat primary aldosteronism, pheochromocytoma or cortisol excess with disease-specific medical and surgical pathways.",
    medicationSafety: "Spironolactone/eplerenone can cause hyperkalemia and affect sex hormones; alpha blockade precedes beta blockade in pheochromocytoma to avoid unopposed alpha vasoconstriction. Many antihypertensives alter aldosterone-renin interpretation.",
    redFlags: "Hypertensive crisis with catecholamine symptoms, severe hypokalemia/arrhythmia, adrenal crisis after cortisol-blocking therapy or acute cardiovascular complications requires emergency care.",
    examTraps: "Do not image adrenal glands before biochemical testing for a suspected functional tumor unless another urgent indication exists. Normal potassium does not exclude primary aldosteronism.",
    sourceKeys: ["ENDOCRINE_PRIMARY_ALDO_CURRENT", "ENDOCRINE_PHEO_CURRENT", "ENDOCRINE_CUSHING_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
