import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch54 = [
  {
    slug: "developmental-delay-autism-evaluation",
    title: "Developmental Delay & Autism Evaluation",
    bodySystem: "Pediatrics",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PNP"],
    recognize: "Concern may arise from missed milestones, loss of skills, language/social-communication difference, restricted/repetitive behavior, abnormal tone or parent/teacher concern. Regression is particularly important and should not be dismissed because a child previously screened normally.",
    diagnostics: "Use developmental surveillance at every well visit and validated developmental/autism screening at recommended ages, then refer abnormal results for formal developmental evaluation and early-intervention services without waiting for a final diagnosis. Hearing/vision testing and targeted genetic/metabolic/neurologic evaluation depend on phenotype.",
    priorities: "Start early-intervention speech/OT/PT/behavioral supports based on functional needs, coordinate school services and family support and address sleep, feeding, constipation, anxiety/ADHD and safety. Autism treatment is individualized and focuses on communication/function rather than 'curing' neurodivergence.",
    medicationSafety: "No medication treats core autism social-communication differences; risperidone/aripiprazole are reserved for severe irritability/aggression in selected patients and require metabolic/movement monitoring. Avoid unproven chelation, restrictive diets or supplements as substitute treatment.",
    redFlags: "Loss of acquired skills, seizures, focal neurologic findings, severe self-injury, feeding failure or suspicion of a progressive neurologic/metabolic disease requires expedited specialist evaluation.",
    examTraps: "A normal M-CHAT or office interaction does not overrule persistent caregiver concern, and speech delay should not be attributed to bilingual exposure without hearing/developmental assessment.",
    sourceKeys: ["AAP_AUTISM_CURRENT", "AAP_DEVELOPMENTAL_SURVEILLANCE_CURRENT"],
  },
  {
    slug: "adolescent-depression-suicide",
    title: "Adolescent Depression & Suicide Risk",
    bodySystem: "Pediatrics",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PNP", "PMHNP"],
    recognize: "Adolescent depression may present as irritability, withdrawal, falling grades, sleep/appetite change, somatic complaints, substance use or self-harm rather than verbalized sadness. Suicide risk must be assessed directly whenever depression, self-harm or major behavioral change is present.",
    diagnostics: "Use validated screening beginning in the recommended adolescent age range with a system for diagnosis/treatment follow-up; a positive screen requires clinical interview including bipolar symptoms, trauma, substances, psychosis, abuse and suicide plan/intent/access to lethal means.",
    priorities: "Mild depression may start with active support/psychotherapy and close monitoring; moderate-severe disease often needs evidence-based psychotherapy plus an SSRI such as fluoxetine/escitalopram according to age and clinical context. Build a collaborative safety plan, lethal-means counseling and rapid follow-up.",
    medicationSafety: "Antidepressants carry a boxed warning for increased suicidal thoughts/behaviors in children/adolescents and require early monitoring, but untreated depression also carries major suicide risk. Screen for mania before SSRI treatment and avoid abrupt discontinuation.",
    redFlags: "Current suicidal intent/plan, recent attempt, command hallucinations, severe self-neglect, mania, intoxication or inability to maintain safety requires emergency psychiatric evaluation.",
    examTraps: "Do not use a 'no-suicide contract' instead of a safety plan and do not avoid necessary antidepressant treatment solely because of the boxed warning—monitoring and appropriate treatment reduce overall risk.",
    sourceKeys: ["AAP_GLDPC_DEPRESSION_CURRENT", "AAP_SUICIDE_PREVENTION_CURRENT"],
  },
  {
    slug: "pediatric-obesity-management",
    title: "Pediatric Obesity Management",
    bodySystem: "Pediatrics",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PNP"],
    recognize: "Pediatric obesity is a chronic disease assessed with age/sex BMI percentile and health impact, not appearance or blame. Screen for hypertension, dyslipidemia, diabetes, MASLD, sleep apnea, orthopedic disease and psychosocial/eating-disorder complications according to age/severity.",
    diagnostics: "Use growth trajectory and family/social context; endocrine causes are uncommon and more likely when linear growth is impaired. Obtain lipid, glucose/A1C and liver testing at guideline-recommended ages/risk and assess sleep, menstruation/PCOS and mental health.",
    priorities: "Offer intensive family-centered health-behavior/lifestyle treatment early, using enough contact hours to be effective; adolescents meeting criteria can also receive evidence-based anti-obesity medication and selected severe cases may be referred for metabolic/bariatric surgery evaluation rather than waiting until adulthood.",
    medicationSafety: "Anti-obesity drugs have age approvals, GI/gallbladder/pregnancy and other class risks and require chronic-disease follow-up; avoid stigmatizing or highly restrictive diets that worsen disordered eating or growth.",
    redFlags: "Severe hyperglycemia, obesity hypoventilation, major depression/eating disorder, rapid weight gain with Cushing/hypothyroid growth failure or advanced MASLD requires expedited evaluation.",
    examTraps: "Do not order extensive endocrine testing for an otherwise normally growing child solely because of obesity, and do not delay pharmacotherapy/surgery until lifestyle treatment has 'failed' for years when guideline criteria are met.",
    sourceKeys: ["AAP_OBESITY_2023_CURRENT"],
  },
  {
    slug: "pediatric-constipation",
    title: "Functional Constipation in Children",
    bodySystem: "Pediatrics",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PNP"],
    recognize: "Functional constipation commonly follows painful stool/withholding and produces hard/infrequent stools, fecal mass, abdominal pain and overflow encopresis. Red flags such as delayed meconium, poor growth, bilious vomiting, abnormal anus/spine or neurologic deficits suggest organic disease.",
    diagnostics: "Diagnosis is clinical using age-appropriate Rome criteria; routine abdominal radiographs, thyroid/celiac testing or rectal examination are unnecessary in a typical presentation without red flags. Assess diet/toilet behavior, painful fissures and psychosocial stressors.",
    priorities: "Disimpact when needed—oral polyethylene glycol is preferred for many children—then use daily maintenance osmotic laxative, scheduled relaxed toilet sitting after meals and long-enough therapy to break the withholding cycle. Reassure families that months of maintenance may be necessary.",
    medicationSafety: "PEG is generally safe for maintenance; stimulant laxatives are useful adjuncts rather than automatically 'habit-forming.' Avoid mineral oil in aspiration-risk children and avoid repeated enemas as chronic routine care.",
    redFlags: "Bilious vomiting/distention, severe abdominal tenderness, failure to thrive, neurologic deficit, very early neonatal onset or refractory disease despite adequate therapy requires specialist evaluation.",
    examTraps: "Overflow soiling is usually constipation, not deliberate behavior or diarrhea. Do not stop maintenance laxative immediately after the first normal stool.",
    sourceKeys: ["NASPGHAN_CONSTIPATION_CURRENT"],
  },
  {
    slug: "nocturnal-enuresis",
    title: "Nocturnal Enuresis",
    bodySystem: "Pediatrics",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PNP"],
    recognize: "Primary monosymptomatic nocturnal enuresis is nighttime wetting in a child old enough for continence without daytime urinary symptoms. Secondary enuresis or daytime urgency, dysuria, constipation, polydipsia, snoring or neurologic symptoms suggests a different underlying problem.",
    diagnostics: "Use history, exam and urinalysis for most children; assess constipation, diabetes symptoms, sleep-disordered breathing and psychosocial stress. Imaging/urodynamics are not routine for uncomplicated monosymptomatic enuresis.",
    priorities: "Education and bladder/toileting habits come first; enuresis alarms provide the best long-term cure likelihood when family engagement is feasible, while desmopressin gives rapid situational dryness and can be combined with alarm therapy.",
    medicationSafety: "Desmopressin requires strict evening fluid restriction because hyponatremia/water intoxication can cause seizure; avoid during vomiting/diarrhea or conditions with excess fluid intake. Imipramine is not first-line because cardiac/toxic-overdose risk is substantial.",
    redFlags: "New polyuria/polydipsia/weight loss, recurrent febrile UTI, neurologic/spinal findings, severe snoring/apnea or secondary enuresis after a long dry interval requires targeted evaluation.",
    examTraps: "Do not punish or restrict daytime fluids excessively and do not order renal ultrasound for every bedwetting child. Alarm therapy works slowly and requires consistent use.",
    sourceKeys: ["ICCS_ENURESIS_CURRENT", "AAP_ENURESIS_CURRENT"],
  },
  {
    slug: "kawasaki-disease",
    title: "Kawasaki Disease",
    bodySystem: "Pediatrics",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PNP", "ENP"],
    recognize: "Kawasaki disease is persistent fever with mucocutaneous inflammation—bilateral nonexudative conjunctivitis, oral changes, polymorphous rash, extremity change and usually unilateral cervical node. Incomplete disease is common in infants and still carries coronary-aneurysm risk.",
    diagnostics: "Use clinical criteria plus inflammatory markers and supportive labs; obtain echocardiography promptly but a normal early echo does not exclude Kawasaki disease. Follow current AHA incomplete-KD algorithm when fewer classic criteria are present.",
    priorities: "Treat promptly with IVIG plus aspirin and involve pediatric cardiology; high-risk or IVIG-resistant disease may need corticosteroid or other anti-inflammatory escalation. Repeat echocardiography tracks coronary involvement.",
    medicationSafety: "High-dose aspirin during acute treatment is a specialist exception to the usual pediatric aspirin avoidance; after influenza/varicella exposure counsel regarding Reye risk and vaccination. Live vaccines such as MMR/varicella may need timing adjustment after IVIG.",
    redFlags: "Shock, myocarditis, arrhythmia, coronary aneurysm/thrombosis, infant with prolonged unexplained fever or recurrent fever after IVIG requires urgent hospital/cardiology care.",
    examTraps: "Do not require all five classic signs before considering incomplete Kawasaki disease and do not rule it out because the initial echocardiogram is normal.",
    sourceKeys: ["AHA_KAWASAKI_CURRENT"],
  },
  {
    slug: "pediatric-headache-evaluation",
    title: "Headache Evaluation in Children & Adolescents",
    bodySystem: "Pediatrics",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PNP", "ENP"],
    recognize: "Migraine and tension-type headache are common in children, but morning vomiting, progressive pattern, focal deficit, papilledema, seizure, personality change, immunocompromise or sudden thunderclap onset raises secondary-cause concern.",
    diagnostics: "Use headache pattern, family history, school/sleep/hydration, medication/caffeine and full neurologic/funduscopic examination. Routine neuroimaging or EEG is unnecessary for recurrent typical migraine with a normal neurologic exam; MRI is preferred for most nonemergent red-flag workups.",
    priorities: "Treat pediatric migraine early with weight/age-appropriate NSAID/acetaminophen and selected triptan in adolescents/eligible children; address sleep, hydration, meals, activity and medication overuse. Preventive therapy is considered for frequent disabling attacks and includes behavioral strategies plus selected medications.",
    medicationSafety: "Avoid opioids; limit acute analgesic frequency to prevent medication-overuse headache. Preventives such as topiramate have cognitive, weight, kidney-stone and fetal risks and require individualized counseling in adolescents.",
    redFlags: "Thunderclap headache, papilledema, focal deficit, meningismus, severe hypertension, cancer/immunosuppression or acute headache after trauma requires urgent imaging/evaluation.",
    examTraps: "Do not image every child with headache simply because vomiting occurs during migraine, but do not dismiss progressive morning vomiting with abnormal neuro exam as migraine.",
    sourceKeys: ["AAN_PEDIATRIC_MIGRAINE_CURRENT", "AAP_HEADACHE_CURRENT"],
  },
  {
    slug: "child-maltreatment-recognition",
    title: "Child Maltreatment Recognition & Mandatory Response",
    bodySystem: "Pediatrics",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PNP", "ENP"],
    recognize: "Injuries inconsistent with developmental ability or mechanism, patterned bruising/burns, bruising in protected areas, multiple injuries of different ages, sentinel injuries in nonmobile infants, concerning sexualized findings or caregiver delay/inconsistent history raises concern for maltreatment.",
    diagnostics: "Use a trauma-informed separate history when possible, complete skin/oral/genital/neurologic examination and photograph/document objectively. Testing is age/injury-specific—skeletal survey, neuroimaging, abdominal labs and STI testing follow child-abuse protocols rather than one universal battery.",
    priorities: "Ensure immediate safety and medical stabilization, involve child-abuse specialists/social work and make the legally required report to child protective services/law enforcement according to jurisdiction. The clinician reports reasonable suspicion; proof is not required before reporting.",
    medicationSafety: "Do not sedate or repeatedly examine a child for forensic completeness when specialized exam can be coordinated; pain control and medical treatment should not be withheld for investigation.",
    redFlags: "Nonmobile infant with unexplained bruise, abusive head-trauma signs, strangulation, sexual assault, internal injury or immediate unsafe discharge environment requires urgent multidisciplinary protection.",
    examTraps: "Do not confront caregivers as an investigator or wait for certainty before a mandated report. Normal external genital examination does not exclude sexual abuse.",
    sourceKeys: ["AAP_CHILD_ABUSE_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
