import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch29 = [
  {
    slug: "atherosclerosis-pathophysiology",
    title: "Atherosclerosis: Endothelial Injury & Plaque Formation",
    slugAliases: ["cv-patho-atherosclerosis-np"],
    bodySystem: "Cardiovascular",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Atherosclerosis begins with endothelial dysfunction and retention of atherogenic lipoproteins, followed by inflammatory-cell recruitment, foam-cell formation and fibrous-plaque development. Clinical events often result from plaque disruption and thrombosis rather than slow stenosis alone.",
    diagnostics: "Translate mechanism into risk assessment: lipid profile, BP, diabetes and smoking status define modifiable burden; CAC can refine selected primary-prevention decisions, while ABI or vascular imaging is reserved for suspected PAD or symptomatic disease rather than screening every patient.",
    priorities: "Reduce future plaque progression and rupture risk with smoking cessation, BP and diabetes control, statin-based lipid lowering, exercise/nutrition and antithrombotic therapy only when a prevention indication exists. Acute ischemic symptoms require event-specific emergency pathways.",
    medicationSafety: "High-intensity statins are standard in established ASCVD when tolerated; monitor symptoms and interactions rather than routinely checking CK. Aspirin is established for secondary prevention but should not be prescribed reflexively for primary prevention because bleeding can outweigh benefit.",
    redFlags: "Acute chest pain, focal neurologic deficit, rest pain with threatened limb, sudden aortic symptoms or other acute arterial ischemia signals plaque/thrombotic complication and requires emergency evaluation.",
    examTraps: "Do not equate the most severe fixed stenosis with the plaque most likely to rupture. Atherosclerosis is systemic, so disease in one vascular bed should trigger risk assessment in others without indiscriminate imaging.",
    sourceKeys: ["ACC_PREVENTION_CURRENT", "ACC_CCD_2023", "ACC_AHA_PAD_2024"],
  },
  {
    slug: "raas-dysregulation-pathophysiology",
    title: "RAAS Dysregulation: Pathological Activation in Heart Failure & Hypertension",
    slugAliases: ["cv-patho-raas-pathology-np"],
    bodySystem: "Cardiovascular",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP"],
    recognize: "Renin release from reduced renal perfusion or sodium delivery drives angiotensin II and aldosterone, increasing vasoconstriction and sodium retention. In chronic heart failure and some hypertension states, persistent RAAS activation becomes maladaptive through afterload, congestion, fibrosis and remodeling.",
    diagnostics: "Use the mechanism to interpret creatinine/potassium after RAAS blockade, volume status and HF phenotype. Aldosterone-renin testing is reserved for suspected primary aldosteronism and must be interpreted around medications, potassium and collection conditions.",
    priorities: "Interrupt maladaptive RAAS when evidence supports it—ACEi/ARB/ARNI and mineralocorticoid-receptor blockade are disease-modifying in selected HF/CKD/hypertension phenotypes while treating volume, BP and the precipitating disease.",
    medicationSafety: "ACEi/ARB/ARNI can raise creatinine and potassium; a modest early creatinine increase can be expected, but marked deterioration, hyperkalemia or hypotension requires reassessment. Never combine ACE inhibitor with ARNI; observe the required washout to reduce angioedema risk.",
    redFlags: "Severe hyperkalemia, angioedema, flash pulmonary edema with suspected bilateral renal artery disease, rapidly progressive AKI or cardiogenic shock requires urgent escalation.",
    examTraps: "Do not label every creatinine rise on RAAS blockade as nephrotoxicity. Conversely, do not ignore a large abrupt rise that suggests volume depletion, renal artery disease or another hemodynamic problem.",
    sourceKeys: ["HF_ACC_AHA_CURRENT", "AHA_BP_2025", "KDIGO_CKD_2024"],
  },
  {
    slug: "gas-exchange-vq-shunt-dead-space",
    title: "Gas Exchange Physiology: V/Q Mismatch, Shunt & Dead Space",
    slugAliases: ["resp-patho-gas-exchange-np"],
    bodySystem: "Respiratory",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Hypoxemia arises from different mechanisms: V/Q mismatch is common in obstructive and parenchymal disease, shunt routes blood past nonventilated alveoli, and dead space ventilates lung that receives little or no perfusion as in pulmonary embolism.",
    diagnostics: "Interpret oxygenation alongside PaCO2, FiO2, imaging and disease context. A raised A-a gradient supports V/Q mismatch, diffusion impairment or shunt; a near-normal gradient with hypoxemia points more toward global hypoventilation or low inspired oxygen.",
    priorities: "Treat the mechanism: recruit/treat diseased alveoli for shunt/VQ disease, anticoagulate appropriate PE, reverse hypoventilation or support ventilation, and use oxygen as a bridge while correcting the underlying problem.",
    medicationSafety: "Do not use oxygen targets or ventilatory support mechanically without accounting for hypercapnic failure, work of breathing and trajectory. Sedatives/opioids can worsen hypoventilation; pulmonary vasodilators can worsen V/Q matching in the wrong physiology.",
    redFlags: "Refractory hypoxemia, rising PaCO2 with fatigue or altered mental status, shock, severe pulmonary embolism or inability to maintain ventilation requires emergency respiratory/critical-care support.",
    examTraps: "A patient can have severe V/Q mismatch with a normal chest x-ray, and supplemental oxygen response alone does not precisely classify every mechanism. Dead space and shunt are physiologic concepts, not diagnoses by themselves.",
    sourceKeys: ["ATS_RESPIRATORY_FAILURE_CURRENT", "ATS_ARDS_CURRENT"],
  },
  {
    slug: "airway-remodeling-pathophysiology",
    title: "Airway Remodeling: Chronic Asthma & COPD Structural Changes",
    slugAliases: ["resp-patho-airway-remodeling-np"],
    bodySystem: "Respiratory",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Chronic airway inflammation can produce structural change: asthma may develop smooth-muscle hypertrophy, mucus-cell change and subepithelial fibrosis, while COPD combines small-airway fibrosis, mucus hypersecretion and emphysematous destruction with loss of elastic recoil.",
    diagnostics: "Use spirometry to distinguish variable from persistent obstruction and evaluate symptom/exacerbation phenotype. In selected asthma assess type-2 biomarkers for biologic eligibility; in COPD consider diffusion capacity, CT or alpha-1 antitrypsin testing when the presentation is atypical or severe.",
    priorities: "Prevent ongoing injury: use ICS-containing therapy in asthma, stop tobacco/exposure in COPD, optimize bronchodilation, vaccinations, rehabilitation and phenotype-specific biologics or other specialist therapy for severe disease.",
    medicationSafety: "LABA should not be used without ICS for asthma; ICS in COPD is phenotype-dependent and can increase pneumonia risk. Biologic therapy requires confirmation of severe disease, adherence/technique and the relevant inflammatory phenotype before selection.",
    redFlags: "Rapid loss of lung function, recurrent severe exacerbations, chronic hypoxemia/hypercapnia, bullous pneumothorax or failure despite maximal inhaled therapy requires pulmonary specialty evaluation.",
    examTraps: "Asthma can develop partially fixed airflow limitation, and bronchodilator reversibility is not an all-or-none lifetime property. Do not diagnose COPD from smoking history without post-bronchodilator spirometry.",
    sourceKeys: ["GINA_2026", "GOLD_2026"],
  },
  {
    slug: "surfactant-alveolar-collapse-pathophysiology",
    title: "Surfactant Deficiency & Alveolar Collapse: ARDS and Neonatal RDS",
    slugAliases: ["resp-patho-surfactant-alveolar-np"],
    bodySystem: "Respiratory",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGACNP", "PNP", "ENP"],
    recognize: "Surfactant lowers alveolar surface tension and prevents end-expiratory collapse. Premature infants may lack sufficient surfactant, whereas adult ARDS causes secondary surfactant dysfunction plus diffuse alveolar-capillary injury and protein-rich edema.",
    diagnostics: "In neonatal RDS use gestational context, respiratory findings and imaging; in ARDS use acute timing, bilateral opacities, oxygenation impairment and exclusion of hydrostatic edema. Severity is based on oxygenation under defined respiratory support rather than chest x-ray appearance alone.",
    priorities: "Prevent neonatal RDS with antenatal corticosteroids when preterm birth risk meets criteria and use CPAP/surfactant according to neonatal respiratory status. Adult ARDS management centers on cause treatment, lung-protective ventilation, PEEP and prone positioning for appropriate moderate-severe disease.",
    medicationSafety: "Surfactant administration can cause transient bradycardia/desaturation and requires neonatal airway expertise. In adults, avoid routine pharmacologic 'surfactant replacement'; ventilator strategy and cause treatment have the established role.",
    redFlags: "Escalating oxygen need, air leak, severe neonatal apnea, refractory adult hypoxemia, shock or high ventilator pressures requires NICU/critical-care escalation.",
    examTraps: "Neonatal RDS and adult ARDS share alveolar-collapse physiology but are not the same disease. Do not apply neonatal surfactant treatment logic to routine adult ARDS.",
    sourceKeys: ["AAP_SURFACTANT_CURRENT", "AAP_HIE_2026", "ATS_ARDS_CURRENT"],
  },
  {
    slug: "blood-brain-barrier-disruption",
    title: "Blood-Brain Barrier Disruption: Mechanisms & Clinical Consequences",
    slugAliases: ["neuro-patho-bbb-disruption-np"],
    bodySystem: "Neurological",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "The BBB depends on endothelial tight junctions, basement membrane, pericytes and astrocytic support. Ischemia, infection, inflammation, trauma, tumor and severe autoregulatory failure can increase permeability and produce vasogenic edema, seizures and encephalopathy.",
    diagnostics: "Use neurologic exam and imaging to identify the disease causing barrier failure. Contrast enhancement can reflect BBB disruption, but MRI pattern, diffusion characteristics, BP, CSF findings and clinical context determine whether the mechanism is tumor, infection, ischemia, PRES or another process.",
    priorities: "Treat the cause while protecting cerebral perfusion: prompt antimicrobials for CNS infection, controlled BP reduction for hypertensive encephalopathy/PRES, tumor-directed edema therapy when appropriate and neurocritical ICP management for mass effect.",
    medicationSafety: "Dexamethasone can reduce tumor-associated vasogenic edema but is not treatment for cytotoxic edema from ischemic stroke. Overrapid chronic hyponatremia correction can produce osmotic demyelination even though that injury is not simply 'BBB edema.'",
    redFlags: "Falling consciousness, seizure, focal deficit, papilledema with mass effect, fixed pupil or herniation physiology requires emergency neuroimaging and neurocritical/neurosurgical care.",
    examTraps: "Gadolinium enhancement is not synonymous with one disease and an intact-looking CT does not exclude functional BBB injury. Choose treatment by the underlying pathology, not the phrase 'brain edema.'",
    sourceKeys: ["AHA_STROKE_CURRENT", "IDSA_MENINGITIS_CURRENT", "BTF_SEVERE_TBI_CURRENT"],
  },
  {
    slug: "demyelination-cns-pns",
    title: "Demyelination Pathophysiology: MS, GBS & Central vs Peripheral Patterns",
    slugAliases: ["neuro-patho-demyelination-np"],
    bodySystem: "Neurological",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "CNS demyelination produces upper-motor-neuron, optic, cerebellar or spinal-cord syndromes as in MS; peripheral demyelination produces areflexic weakness and sensory/autonomic features as in GBS. Localization should precede disease labeling.",
    diagnostics: "MS evaluation uses MRI distribution in space/time plus CSF oligoclonal bands when needed; GBS uses clinical progression, nerve-conduction studies and CSF albuminocytologic dissociation while serial respiratory testing tracks impending ventilatory failure.",
    priorities: "Treat significant MS relapse with corticosteroids when indicated and initiate disease-modifying therapy for long-term disease; treat GBS with IVIG or plasma exchange and aggressive respiratory/autonomic monitoring plus rehabilitation.",
    medicationSafety: "Corticosteroids are useful for MS relapse but do not improve typical GBS outcomes. MS disease-modifying therapies carry infection, pregnancy and organ-specific risks; IVIG carries thrombosis, renal and infusion considerations.",
    redFlags: "Rapid ascending weakness, bulbar dysfunction, falling vital capacity, acute transverse myelitis, severe optic loss or life-threatening autonomic instability requires urgent neurology/inpatient care.",
    examTraps: "Do not confuse hyperreflexic spastic weakness with a peripheral demyelinating neuropathy. Normal early CSF protein does not exclude GBS, and nonspecific MRI white-matter lesions do not diagnose MS.",
    sourceKeys: ["AAN_MS_CURRENT", "AAN_GBS_CURRENT"],
  },
  {
    slug: "neurotransmitter-pathophysiology",
    title: "Neurotransmitter Imbalances: Dopamine, Serotonin, GABA & Glutamate",
    slugAliases: ["neuro-patho-neurotransmitter-np"],
    bodySystem: "Neurological",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PMHNP", "ENP"],
    recognize: "Dopamine, serotonin, GABA and glutamate systems are useful pharmacologic frameworks, but psychiatric and neurologic disorders are network diseases rather than simple one-neurotransmitter deficiencies. Recognize syndromes caused by excess or blockade, especially serotonin syndrome, withdrawal and medication-induced movement disorders.",
    diagnostics: "Most neurotransmitter disorders are diagnosed clinically using symptom pattern, medication/substance exposure and neurologic exam rather than serum neurotransmitter levels. Use ECG, CK, metabolic tests, toxicology, EEG or imaging when the syndrome requires them.",
    priorities: "Treat the clinical syndrome: stop serotonergic agents and provide supportive care for serotonin toxicity, restore GABAergic tone for dangerous alcohol/benzodiazepine withdrawal, use disease-specific dopaminergic or antiseizure therapy, and treat the underlying cause of excitotoxic CNS injury.",
    medicationSafety: "Combining serotonergic drugs can trigger serotonin toxicity; dopamine-blocking antipsychotics can cause EPS, hyperprolactinemia and NMS; benzodiazepines/opioids/alcohol produce additive respiratory depression. Medication lists matter more than simplistic transmitter diagrams.",
    redFlags: "Hyperthermia with clonus, severe rigidity with autonomic instability, status epilepticus, severe withdrawal delirium, respiratory depression or malignant arrhythmia requires emergency care.",
    examTraps: "Do not explain depression as proven 'low serotonin' or schizophrenia as simply 'too much dopamine.' Neurotransmitter models guide pharmacology but are not definitive diagnostic laboratory mechanisms.",
    sourceKeys: ["APA_PSYCHOPHARM_CURRENT", "AAN_EPILEPSY_CURRENT", "ASAM_WITHDRAWAL_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
