import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch5 = [
  {
    slug: "acute-otitis-media",
    title: "Acute Otitis Media",
    bodySystem: "Pediatrics",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PNP"],
    recognize: "True AOM needs middle-ear effusion plus acute inflammatory findings—bulging tympanic membrane is more persuasive than nonspecific redness.",
    diagnostics: "Pneumatic otoscopy/tympanometry can help when the exam is uncertain. Distinguish AOM from otitis externa and otitis media with effusion.",
    priorities: "Pain control is essential. Use observation in selected low-risk children and antibiotics when age, severity, bilateral disease, otorrhea, or follow-up reliability warrants treatment.",
    medicationSafety: "Amoxicillin is a common first-line option when appropriate; recent amoxicillin, conjunctivitis, allergy pattern, and treatment failure change the choice.",
    redFlags: "Mastoid swelling/tenderness, facial weakness, toxic appearance, severe headache, or neurologic signs requires urgent escalation.",
    examTraps: "A red TM after crying is not AOM. Persistent effusion after infection does not automatically require another antibiotic.",
    sourceKeys: ["AAP_AOM_CURRENT"],
  },
  {
    slug: "pediatric-asthma",
    title: "Pediatric Asthma",
    bodySystem: "Pediatrics",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PNP", "ENP"],
    recognize: "Recurrent wheeze/cough triggered by viral illness, exercise, allergens, or nighttime patterns suggests asthma, but preschool wheeze has a broad differential.",
    diagnostics: "Use age-appropriate objective lung-function testing when feasible and assess control, exacerbation history, school/activity limitation, technique, adherence, smoke/vape exposure, and allergic disease.",
    priorities: "Use an ICS-containing plan tailored to age and severity. Every family needs a written action plan, spacer/device teaching, trigger reduction, and clear thresholds for urgent care.",
    medicationSafety: "Check device and dose before escalating. Repeated oral-steroid bursts signal uncontrolled disease and cumulative harm.",
    redFlags: "Retractions, inability to speak/feed, silent chest, cyanosis, exhaustion, or poor response to bronchodilator therapy is an emergency.",
    examTraps: "Do not rely on a rescue inhaler alone as long-term asthma care. 'No wheeze' in a tiring child can be worse, not better.",
    sourceKeys: ["GINA_2026"],
  },
  {
    slug: "pediatric-dehydration",
    title: "Pediatric Dehydration",
    bodySystem: "Pediatrics",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PNP", "ENP"],
    recognize: "Reduced intake, vomiting/diarrhea, fewer wet diapers/urination, dry mucosa, tachycardia, poor tears, delayed capillary refill, and lethargy suggest dehydration; severity is clinical.",
    diagnostics: "Assess weight change when available, perfusion, mental status, urine output, and ongoing losses. Labs are not mandatory in every mild case but are important with severe dehydration, electrolyte concern, or IV therapy.",
    priorities: "Use oral rehydration for mild/moderate dehydration when the child can drink; small frequent volumes work better than large boluses. Severe shock needs rapid isotonic IV/IO resuscitation and reassessment.",
    medicationSafety: "Antidiarrheals are often inappropriate in young children. Recheck sodium/glucose when clinically indicated and avoid hypotonic resuscitation fluids for shock.",
    redFlags: "Shock, bilious emesis, bloody stool with toxicity, severe abdominal pain, altered mental status, or inability to maintain oral intake requires escalation.",
    examTraps: "Capillary refill alone is imperfect; combine signs. Juice/soda are not equivalent to balanced oral rehydration solution for significant gastroenteritis.",
    sourceKeys: ["AAP_GASTRO_CURRENT"],
  },
  {
    slug: "child-maltreatment",
    title: "Child Maltreatment Recognition",
    bodySystem: "Pediatrics",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PNP", "ENP"],
    recognize: "Concern rises when injury pattern does not match developmental ability or history, explanations change, care is delayed, patterned injuries are present, or there are high-risk bruising locations.",
    diagnostics: "Perform a complete skin/oral/neuro exam and document objectively. Testing for occult injury depends on age and suspected mechanism; follow jurisdictional child-protection protocols.",
    priorities: "Stabilize immediate medical needs, preserve forensic integrity when relevant, involve child-abuse specialists/child protective services as required, and make mandated reports based on reasonable suspicion—not proof.",
    medicationSafety: "Do not sedate a concerning history with casual reassurance. Analgesia should still be provided; treating pain does not compromise the evaluation.",
    redFlags: "Suspected abusive head trauma, strangulation, abdominal injury, sexual assault with acute safety concern, or unsafe discharge environment requires urgent multidisciplinary action.",
    examTraps: "Clinicians report suspicion; they do not investigate guilt. Normal behavior in clinic does not exclude abuse.",
    sourceKeys: ["AAP_CHILD_ABUSE_CURRENT"],
  },
  {
    slug: "contraception",
    title: "Contraception Selection",
    bodySystem: "Reproductive",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "WHNP"],
    recognize: "Choose contraception by pregnancy goals, efficacy preference, bleeding profile, medical eligibility, drug interactions, STI risk, privacy, and ability to adhere—not by age alone.",
    diagnostics: "Exclude pregnancy reasonably, measure BP before estrogen-containing methods, and review migraine aura, VTE history, smoking, postpartum status, breast cancer, liver disease, and interacting medications.",
    priorities: "Offer the full range, including LARC, using shared decision-making. Emergency contraception choice depends on timing, weight/BMI considerations for some methods, interactions, and desire for ongoing contraception.",
    medicationSafety: "Estrogen-containing methods increase thrombosis risk and are contraindicated in several high-risk conditions. Enzyme-inducing drugs can reduce effectiveness of some hormonal methods.",
    redFlags: "Severe pelvic pain/pregnancy concern with an IUD, thromboembolic symptoms on estrogen, or postpartum severe headache/neurologic symptoms requires urgent evaluation.",
    examTraps: "Nulliparity and adolescence are not contraindications to IUDs. Do not require a pelvic exam for methods that do not need one.",
    sourceKeys: ["CDC_USMEC_2024", "CDC_USSPR_2024"],
  },
  {
    slug: "abnormal-uterine-bleeding",
    title: "Abnormal Uterine Bleeding",
    bodySystem: "Reproductive",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "WHNP", "ENP"],
    recognize: "Classify AUB by pregnancy status, hemodynamic stability, age, bleeding pattern, medications, and structural/nonstructural causes. Heavy bleeding plus anemia symptoms can be clinically significant even with normal vital signs.",
    diagnostics: "Pregnancy test is foundational in reproductive-age patients. CBC and targeted TSH/coagulation testing, pelvic exam, ultrasound, and endometrial sampling depend on age, risk factors, and presentation.",
    priorities: "Stabilize acute heavy bleeding first, then use hormonal or nonhormonal therapy according to contraindications and cause. Persistent or high-risk bleeding needs gynecology evaluation.",
    medicationSafety: "Estrogen is inappropriate in significant thrombotic risk; tranexamic acid also requires thrombosis-risk consideration. NSAIDs can reduce ovulatory heavy bleeding but are unsuitable in some renal/GI/bleeding-risk patients.",
    redFlags: "Hemodynamic instability, soaking bleeding with syncope, severe anemia symptoms, ectopic-pregnancy concern, or postmenopausal bleeding with instability requires urgent care.",
    examTraps: "Do not attribute AUB to perimenopause without evaluating malignancy risk. A normal ultrasound does not rule out all endometrial pathology.",
    sourceKeys: ["ACOG_AUB_CURRENT"],
  },
  {
    slug: "pregnancy-red-flags",
    title: "Pregnancy Red Flags",
    bodySystem: "Reproductive",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "WHNP", "ENP"],
    recognize: "Pregnancy changes the threshold for concern: bleeding, severe abdominal pain, severe headache/visual symptoms, dyspnea, chest pain, fever, decreased fetal movement, gush of fluid, or persistent vomiting may represent time-sensitive disease.",
    diagnostics: "Confirm gestational age and pregnancy location when relevant, check BP/urine protein for hypertensive symptoms, and use targeted labs/imaging with pregnancy-safe protocols. Do not avoid necessary imaging solely because of pregnancy.",
    priorities: "Stabilize the mother first. Arrange obstetric/emergency evaluation for suspected ectopic pregnancy, preeclampsia, hemorrhage, thromboembolism, sepsis, or preterm labor.",
    medicationSafety: "ACEi/ARBs, valproate, isotretinoin, methotrexate, and other teratogens require immediate medication reconciliation. Many commonly needed drugs can still be used safely—avoid undertreatment from medication fear.",
    redFlags: "Hemodynamic instability, shoulder pain/syncope with bleeding, severe-range hypertension with neurologic symptoms, seizure, significant dyspnea/chest pain, or heavy bleeding is an emergency.",
    examTraps: "Pregnancy does not protect against ACS, PE, stroke, or appendicitis. Do not dismiss severe symptoms as 'normal pregnancy.'",
    sourceKeys: ["ACOG_PREGNANCY_CURRENT"],
  },
  {
    slug: "menopause",
    title: "Menopause & Genitourinary Syndrome",
    bodySystem: "Reproductive",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "WHNP"],
    recognize: "Vasomotor symptoms, sleep disruption, mood change, vaginal dryness, dyspareunia, and urinary symptoms can occur during the menopause transition; rule out mimics when the pattern is atypical.",
    diagnostics: "Diagnosis is usually clinical in patients at the expected age; routine FSH testing is often unnecessary. Evaluate abnormal bleeding, osteoporosis risk, cardiovascular risk, and contraindications before hormone therapy.",
    priorities: "Use individualized shared decision-making for hormone therapy when appropriate; local vaginal therapy is highly effective for genitourinary symptoms. Nonhormonal options exist for vasomotor symptoms.",
    medicationSafety: "Systemic estrogen requires endometrial protection with a progestogen when the uterus is present unless using a regimen/product that provides another accepted protection strategy. Route and risk profile matter for VTE and other risks.",
    redFlags: "Postmenopausal bleeding, new breast mass, VTE symptoms, or neurologic/cardiac symptoms requires prompt evaluation.",
    examTraps: "Do not use systemic hormone therapy to prevent cardiovascular disease or dementia. Menopause symptoms can persist longer than older teaching suggested.",
    sourceKeys: ["NAMS_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
