import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch47 = [
  {
    slug: "chronic-kidney-disease-staging-referral",
    title: "Chronic Kidney Disease: Staging, Risk & Referral",
    bodySystem: "Renal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP"],
    recognize: "CKD is abnormal kidney structure/function present for at least 3 months and is classified by cause, GFR category and albuminuria category. A normal creatinine does not exclude CKD in low-muscle-mass patients, and albuminuria can confer high kidney/cardiovascular risk before eGFR falls.",
    diagnostics: "Confirm chronicity, calculate eGFR and urine albumin-to-creatinine ratio, review urinalysis/sediment, BP, diabetes, medications and structural risk. KDIGO 2024 encourages validated kidney-failure risk equations in appropriate CKD to guide referral and kidney-replacement planning rather than relying on an eGFR threshold alone.",
    priorities: "Treat the cause and slow progression with BP control, ACEi/ARB for appropriate albuminuria, SGLT2 inhibition when eligible, diabetes/lipid management, smoking cessation and nephrotoxin avoidance. Refer uncertain etiology, rapid progression, significant albuminuria/active sediment, refractory complications or high kidney-failure risk to nephrology.",
    medicationSafety: "Dose renally cleared medications to current kidney function and remember that creatinine-based estimates are imperfect in extremes of muscle mass. Avoid chronic NSAIDs when possible; metformin, SGLT2 inhibitors, anticoagulants and many antimicrobials have kidney-specific thresholds or dose changes.",
    redFlags: "Refractory hyperkalemia/acidosis, pulmonary edema, uremic symptoms, rapidly falling eGFR, nephritic syndrome or obstructive uropathy requires urgent nephrology/inpatient evaluation.",
    examTraps: "Do not diagnose CKD from one abnormal creatinine or UACR without chronicity unless there is established structural disease. G3aA1 and G3aA3 do not carry the same risk despite identical eGFR.",
    sourceKeys: ["KDIGO_CKD_2024"],
  },
  {
    slug: "nephrotic-syndrome",
    title: "Nephrotic Syndrome",
    bodySystem: "Renal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PNP"],
    recognize: "Nephrotic syndrome combines heavy proteinuria, hypoalbuminemia and edema, often with hyperlipidemia and increased thrombotic/infectious risk. Diabetes, membranous nephropathy, FSGS, minimal-change disease and systemic diseases are common causes depending on age/context.",
    diagnostics: "Quantify proteinuria with UACR/PCR or timed collection, check albumin, creatinine/eGFR, lipids and urine sediment and investigate secondary causes such as diabetes, lupus, infections, medications and monoclonal disease. Kidney biopsy is often needed in adults when the cause is not established clinically.",
    priorities: "Treat the underlying glomerular disease, control edema with sodium restriction/diuretics, use RAAS/SGLT2 kidney-protective therapy when indicated and manage lipids/BP. Anticoagulation is individualized to albumin level, diagnosis, bleeding risk and other thrombotic factors rather than given automatically to every patient.",
    medicationSafety: "Aggressive diuresis can cause intravascular depletion/AKI even while edema persists. Immunosuppressive therapy is pathology-specific and should not be started empirically before adequate diagnostic classification except in selected pediatric/specialist contexts.",
    redFlags: "Renal-vein/other thrombosis, severe infection, rapidly rising creatinine, pulmonary edema or profound hypoalbuminemia with hemodynamic compromise requires urgent nephrology care.",
    examTraps: "Proteinuria plus edema is not automatically nephrotic syndrome without quantification/albumin context, and RBC casts or substantial hematuria should redirect toward a nephritic or mixed process.",
    sourceKeys: ["KDIGO_GLOMERULAR_CURRENT", "KDIGO_CKD_2024"],
  },
  {
    slug: "glomerulonephritis-nephritic-syndrome",
    title: "Glomerulonephritis & Nephritic Syndrome",
    bodySystem: "Renal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PNP", "ENP"],
    recognize: "Hematuria with dysmorphic RBCs/RBC casts, variable proteinuria, hypertension, edema and kidney-function decline suggests glomerular inflammation. Rapidly progressive disease can result from ANCA vasculitis, anti-GBM disease, lupus or immune-complex GN and may cause irreversible failure within days to weeks.",
    diagnostics: "Obtain urinalysis/microscopy, creatinine, protein quantification, complements, ANA/dsDNA, ANCA, anti-GBM and infection/monoclonal testing according to phenotype; kidney biopsy usually defines rapidly progressive or unexplained significant GN. Pulmonary symptoms require chest imaging and hemoglobin/oxygen assessment for pulmonary-renal syndrome.",
    priorities: "Arrange urgent nephrology when kidney function is worsening or active sediment is substantial and start cause-specific immunosuppression/plasma exchange only through evidence-based disease pathways. Control BP/volume and treat infection triggers without delaying biopsy-critical decisions.",
    medicationSafety: "High-dose steroids/cyclophosphamide/rituximab cause major infection, marrow, fertility and metabolic toxicity and require prophylaxis/screening. Plasmapheresis is not universal for every ANCA-positive patient and is reserved for defined severe contexts.",
    redFlags: "Rapid creatinine rise, oliguria, pulmonary hemorrhage/hemoptysis, severe hypertension, hyperkalemia or anti-GBM/ANCA syndrome with organ threat requires urgent inpatient nephrology/rheumatology care.",
    examTraps: "Dipstick blood without urine microscopy can reflect myoglobin rather than GN; RBC casts are highly suggestive but their absence does not exclude glomerular disease.",
    sourceKeys: ["KDIGO_GLOMERULAR_CURRENT"],
  },
  {
    slug: "acute-pyelonephritis-complicated-uti",
    title: "Acute Pyelonephritis & Complicated UTI",
    bodySystem: "Renal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PNP", "WHNP", "ENP"],
    recognize: "Fever, flank pain/CVA tenderness, nausea and urinary symptoms suggest pyelonephritis, but older adults and immunocompromised patients may present atypically. Male sex, pregnancy, obstruction/stones, instrumentation, transplant or severe systemic illness makes infection more complicated.",
    diagnostics: "Obtain urinalysis and urine culture before antibiotics when possible; pregnancy testing matters when relevant. Image when obstruction, stone, abscess, emphysematous infection, recurrent failure or severe sepsis is suspected—not routinely in every first uncomplicated pyelonephritis case.",
    priorities: "Treat stable uncomplicated disease with an oral agent guided by local resistance/culture and use initial parenteral therapy when resistance or severity warrants it; hospitalize sepsis, inability to tolerate PO, pregnancy with significant disease or obstructed infected systems. Drain obstruction urgently.",
    medicationSafety: "Nitrofurantoin and fosfomycin do not achieve adequate renal-parenchymal concentrations for pyelonephritis. Fluoroquinolones have serious adverse effects/resistance concerns; TMP-SMX needs susceptibility and renal/potassium review; pregnancy changes drug choices.",
    redFlags: "Sepsis/shock, obstructed infected kidney, emphysematous pyelonephritis, renal/perinephric abscess or pregnancy with clinical deterioration requires emergency inpatient/urologic management.",
    examTraps: "Pyuria alone is not pyelonephritis and asymptomatic bacteriuria is not treated outside defined populations. Do not use bladder-only agents for kidney infection.",
    sourceKeys: ["IDSA_UTI_CURRENT", "ACOG_UTI_PREGNANCY_CURRENT"],
  },
  {
    slug: "recurrent-urinary-tract-infection",
    title: "Recurrent Urinary Tract Infection",
    bodySystem: "Renal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "WHNP"],
    recognize: "Recurrent uncomplicated UTI is repeated symptomatic culture-supported cystitis episodes; distinguish reinfection from persistent infection and from bladder pain syndrome, vaginitis, STI, overactive bladder or genitourinary syndrome of menopause.",
    diagnostics: "Obtain urine culture with symptomatic episodes before repeated empiric courses when feasible; routine cystoscopy/upper-tract imaging is unnecessary in a typical otherwise healthy patient but indicated for hematuria, stones, obstruction, unusual organisms or relapsing same-organism infection.",
    priorities: "Use short-course culture-directed treatment, hydration/behavioral strategies without blame, vaginal estrogen for appropriate peri/postmenopausal GSM, and patient-initiated or postcoital/continuous antibiotic prophylaxis for selected recurrent cases after shared decision-making.",
    medicationSafety: "Repeated antibiotics drive resistance and C. difficile; nitrofurantoin prophylaxis has pulmonary/hepatic/neuropathy toxicity with long exposure, and TMP-SMX can cause hyperkalemia and severe rash. Methenamine may be an antibiotic-sparing option in selected patients with appropriate renal/urinary conditions.",
    redFlags: "Fever/flank pain, pregnancy, gross hematuria, stone/obstruction, resistant organism with systemic illness or repeated relapse requires broader evaluation.",
    examTraps: "Do not treat positive cultures between symptomatic episodes in nonpregnant patients simply to 'clear the urine,' and do not send a chronic patient for routine CT/cystoscopy without a red flag.",
    sourceKeys: ["AUA_RECURRENT_UTI_CURRENT"],
  },
  {
    slug: "nephrolithiasis",
    title: "Nephrolithiasis Evaluation & Prevention",
    bodySystem: "Renal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "ENP"],
    recognize: "Sudden colicky flank pain radiating to groin with hematuria/nausea suggests ureteral stone; pyelonephritis, AAA, ectopic pregnancy, ovarian/testicular torsion and other abdominal emergencies can mimic renal colic. Infection plus obstruction is the dangerous combination.",
    diagnostics: "Use pregnancy testing when relevant and urinalysis, creatinine and CBC selectively; noncontrast CT is highly sensitive, while ultrasound is favored in pregnancy and can reduce radiation in selected patients. Analyze passed/removed stones and perform metabolic evaluation for recurrent/high-risk stone formers.",
    priorities: "Provide NSAID-first analgesia when safe, hydration to normal euvolemia rather than forced fluids and alpha-blocker medical expulsive therapy selectively for appropriate distal ureteral stones. Urgently decompress an infected obstructed collecting system and refer large, refractory or renal-threatening stones.",
    medicationSafety: "NSAIDs can worsen AKI/GI bleeding; tamsulosin causes orthostasis. Prevention is stone-specific—thiazides for recurrent hypercalciuria, citrate for hypocitraturia/uric-acid disease and allopurinol for selected hyperuricosuric calcium stones rather than one universal supplement plan.",
    redFlags: "Fever/sepsis with obstruction, anuria/bilateral obstruction, solitary kidney with obstruction, uncontrolled pain/vomiting or progressive AKI requires urgent urologic care.",
    examTraps: "Do not give liters of fluid to 'flush out' an obstructing stone and do not dismiss AAA/ectopic/torsion because microscopic hematuria is present.",
    sourceKeys: ["AUA_STONE_CURRENT", "EAU_STONE_CURRENT"],
  },
  {
    slug: "hematuria-evaluation",
    title: "Microscopic & Gross Hematuria Evaluation",
    bodySystem: "Renal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "Hematuria can arise from glomerular disease, infection, stones, BPH, malignancy, trauma or medications. Dipstick 'blood' must be confirmed with microscopy because myoglobin/hemoglobin can produce a positive dipstick without RBCs.",
    diagnostics: "After excluding transient benign causes and treating UTI when present, use current AUA risk stratification for microscopic hematuria to decide repeat urinalysis, cystoscopy and upper-tract imaging. Gross hematuria generally warrants comprehensive urologic evaluation unless a clearly transient benign explanation is established.",
    priorities: "Refer risk-appropriate patients for cystoscopy/imaging and evaluate proteinuria, casts or kidney dysfunction through a nephrologic pathway. Anticoagulation does not remove the need for malignancy evaluation because it may unmask bleeding from an underlying lesion.",
    medicationSafety: "Contrast imaging requires kidney/allergy context; do not stop necessary anticoagulation without assessing indication and bleeding severity. Avoid repeated empiric antibiotics for culture-negative hematuria.",
    redFlags: "Gross hematuria with clot retention, severe anemia, flank mass/pain, AKI/obstruction or active nephritic urine requires urgent evaluation.",
    examTraps: "Do not refer every low-risk young patient to CT urography and cystoscopy automatically; modern evaluation is risk-stratified. A positive dipstick alone is not the definition of microscopic hematuria.",
    sourceKeys: ["AUA_MICROHEMATURIA_CURRENT"],
  },
  {
    slug: "acute-urinary-retention",
    title: "Acute Urinary Retention",
    bodySystem: "Renal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "ENP"],
    recognize: "Painful inability to void with bladder distention suggests acute retention; older men with BPH are common, but medications with anticholinergic/sympathomimetic effects, constipation, infection, postoperative states and neurologic/spinal disease are important causes. Painless overflow can occur with chronic neurogenic retention.",
    diagnostics: "Confirm bladder volume with catheterization or bladder scan, obtain urinalysis/creatinine and examine prostate/neurologic function as indicated. New saddle anesthesia, leg weakness or bowel dysfunction mandates an emergency spinal evaluation rather than labeling the problem BPH.",
    priorities: "Promptly decompress the bladder with urethral catheter unless urethral injury/obstruction requires urologic approach, monitor significant postobstructive diuresis when large chronic volumes are released and treat the cause; alpha blocker plus planned voiding trial is appropriate for many BPH-related episodes.",
    medicationSafety: "Avoid rapidly refilling volume with excessive fluids during postobstructive diuresis; replace based on hemodynamics/electrolytes. Review anticholinergics, antihistamines, decongestants, opioids and other contributors before adding chronic BPH drugs.",
    redFlags: "Suspected cauda equina, urosepsis, AKI/hydronephrosis, traumatic urethral injury, gross hematuria/clot retention or inability to catheterize requires urgent specialty/emergency care.",
    examTraps: "Do not clamp a catheter repeatedly to 'gradually decompress' routine retention; prompt complete drainage is accepted. A large prostate is not the only cause of retention.",
    sourceKeys: ["AUA_BPH_2026", "AUA_RETENTION_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
