import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch59 = [
  {
    slug: "thyroid-nodule-evaluation",
    title: "Thyroid Nodule Evaluation",
    bodySystem: "Endocrine",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "Most thyroid nodules are benign; cancer risk is driven by ultrasound morphology, cervical nodes, radiation/family history and growth rather than size alone. Hoarseness, fixation, rapid growth or suspicious nodes increase concern.",
    diagnostics: "Check TSH first and obtain high-quality thyroid/neck ultrasound with risk-stratified pattern classification. A suppressed TSH generally leads to radionuclide evaluation for an autonomous nodule before FNA, while euthyroid/hypothyroid nodules use ultrasound-pattern and size thresholds to decide biopsy; molecular testing is selective for indeterminate cytology.",
    priorities: "Refer suspicious cytology, compressive symptoms, concerning nodes or clinically significant autonomous nodules for endocrine/surgical management; observe low-risk nodules using guideline-based ultrasound intervals rather than repeated early scans.",
    medicationSafety: "Routine levothyroxine suppression therapy for benign nodules is not recommended because iatrogenic hyperthyroidism increases atrial-fibrillation and bone risk. Radioiodine and surgery require pregnancy and thyroid-function planning.",
    redFlags: "Stridor, rapidly progressive neck mass, vocal-cord dysfunction, invasive nodes or medullary-thyroid-cancer syndrome features requires expedited specialty evaluation.",
    examTraps: "Do not FNA every nodule over 1 cm and do not biopsy a clearly hyperfunctioning 'hot' nodule before evaluating its autonomous physiology. Serum thyroglobulin is not a screening test for thyroid-cancer diagnosis.",
    sourceKeys: ["ATA_THYROID_NODULE_CURRENT", "ACR_TIRADS_CURRENT"],
  },
  {
    slug: "primary-aldosteronism",
    title: "Primary Aldosteronism: Screening & Confirmation",
    bodySystem: "Endocrine",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "Primary aldosteronism should be considered in resistant/severe hypertension, hypertension with spontaneous or diuretic-induced hypokalemia, adrenal incidentaloma, sleep apnea or early cardiovascular disease/family history. Normal potassium does not exclude it.",
    diagnostics: "Screen with paired aldosterone and renin interpreted as an aldosterone-to-renin pattern under appropriate medication, potassium and sodium conditions; the 2025 Endocrine Society guideline broadens case detection and emphasizes standardized testing. Confirm autonomous aldosterone secretion when needed, then use adrenal CT plus adrenal-vein sampling for subtype when surgery is contemplated, with selected exceptions.",
    priorities: "Treat unilateral surgically curable disease with adrenalectomy when appropriate and bilateral/nonoperative disease with a mineralocorticoid-receptor antagonist, titrating BP/potassium and—where used—renin response. Address overall cardiovascular risk because PA carries excess risk beyond BP alone.",
    medicationSafety: "Spironolactone can cause hyperkalemia, renal dysfunction, gynecomastia and sexual/endocrine effects; eplerenone has fewer sex-hormone effects but is often costlier and may require twice-daily dosing. Correct hypokalemia before interpreting aldosterone because low potassium can suppress secretion.",
    redFlags: "Severe hypertension with acute organ injury, profound hypokalemia/arrhythmia or rapidly worsening renal function after MRA/RAAS treatment requires urgent evaluation.",
    examTraps: "Do not require hypokalemia before screening and do not choose adrenalectomy from CT alone in most adults because nonfunctioning nodules and bilateral disease are common.",
    sourceKeys: ["ENDOCRINE_PRIMARY_ALDOSTERONISM_2025"],
  },
  {
    slug: "pheochromocytoma-paraganglioma",
    title: "Pheochromocytoma & Paraganglioma",
    bodySystem: "Endocrine",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "ENP"],
    recognize: "Paroxysmal or sustained hypertension with episodic headache, palpitations, diaphoresis, tremor or panic-like spells—especially with an adrenal mass or hereditary syndrome—raises concern for catecholamine-producing pheochromocytoma/paraganglioma. Symptoms are variable and the classic triad is not required.",
    diagnostics: "Use plasma free metanephrines or 24-hour urinary fractionated metanephrines with careful preanalytic conditions; biochemical confirmation generally precedes localization imaging. Evaluate hereditary risk because a substantial proportion of PPGL is germline-associated and genetic testing is commonly recommended.",
    priorities: "Refer confirmed disease to endocrine/surgical expertise; preoperative alpha-adrenergic blockade with adequate salt/fluid expansion precedes beta blockade when tachycardia requires treatment. Surgery is definitive for resectable localized disease.",
    medicationSafety: "Never start a pure beta blocker before adequate alpha blockade in a catecholamine-secreting tumor because unopposed alpha vasoconstriction can precipitate hypertensive crisis. Several medications, stress and sampling conditions can cause false-positive metanephrine results.",
    redFlags: "Hypertensive crisis, cardiomyopathy, pulmonary edema, arrhythmia, stroke symptoms or multisystem shock from catecholamine crisis requires ICU/endocrine management.",
    examTraps: "Do not image first and call every adrenal nodule a pheochromocytoma; biochemical testing establishes secretion. A normal single random catecholamine level is not an appropriate exclusion test.",
    sourceKeys: ["ENDOCRINE_PPGL_CURRENT"],
  },
  {
    slug: "adrenal-incidentaloma",
    title: "Adrenal Incidentaloma Evaluation",
    bodySystem: "Endocrine",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "An incidental adrenal mass requires two questions: is it hormonally active and is it radiographically suspicious for malignancy? Size alone is not the entire risk assessment, and benign lipid-rich adenomas often need no repeated lifelong imaging.",
    diagnostics: "Review noncontrast CT attenuation and morphology, test for autonomous cortisol secretion with an overnight dexamethasone-suppression strategy, screen metanephrines when imaging is not clearly benign or clinical guidance indicates, and test aldosterone/renin in hypertension/hypokalemia. Androgen/precursor testing is selective for suspected adrenocortical carcinoma.",
    priorities: "Refer hormonally active, enlarging or imaging-suspicious lesions for endocrine/surgical review; manage mild autonomous cortisol secretion based on comorbidity burden and patient preference. Clearly benign nonfunctioning lesions can often avoid serial biochemical/imaging surveillance under current guidance.",
    medicationSafety: "Do not biopsy an adrenal mass until pheochromocytoma has been excluded; biopsy cannot reliably distinguish benign adenoma from adrenocortical carcinoma and is used mainly when metastatic disease would alter management.",
    redFlags: "Rapid growth, invasive imaging features, severe hormone excess or suspected adrenal carcinoma requires expedited specialty evaluation.",
    examTraps: "Do not biopsy first and do not order every adrenal hormone test indiscriminately. A benign-appearing lipid-rich adenoma with no hormone excess is not automatically a surgical lesion because it is large enough to notice.",
    sourceKeys: ["ESE_ADRENAL_INCIDENTALOMA_2023_CURRENT"],
  },
  {
    slug: "cushing-syndrome-diagnostic-algorithm",
    title: "Cushing Syndrome: Diagnostic Algorithm & Dexamethasone Suppression",
    titleAliases: ["Cushing Syndrome: Diagnostic Algorithm & Dexamethasone Suppression"],
    slugAliases: ["cushing-syndrome-diagnostic-np"],
    bodySystem: "Endocrine",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "Progressive proximal weakness, easy bruising, facial plethora, wide violaceous striae, early osteoporosis, difficult hypertension/diabetes or unusual infections are more discriminatory for Cushing syndrome than obesity alone. Exogenous glucocorticoids are the most common cause and must be identified first.",
    diagnostics: "After excluding exogenous steroids, use one of the recommended first-line screens—late-night salivary cortisol, 24-hour urinary free cortisol or 1-mg overnight dexamethasone suppression—usually with repeat/confirmatory testing before etiologic localization. Once endogenous hypercortisolism is established, ACTH separates ACTH-dependent from adrenal causes; imaging comes after biochemical classification.",
    priorities: "Refer confirmed endogenous Cushing syndrome to endocrinology for cause-specific surgery and medical therapy when needed, while aggressively treating hypertension, diabetes, osteoporosis, infection and thrombosis risk. Perioperative steroid replacement is planned because chronic hypercortisolism suppresses the normal HPA axis.",
    medicationSafety: "CYP3A inducers/inhibitors, estrogen and altered dexamethasone metabolism can distort suppression testing. Cortisol-lowering drugs can precipitate adrenal insufficiency and have agent-specific hepatic, electrolyte, QT and fetal risks.",
    redFlags: "Severe infection, psychosis, hypokalemic hypertension, thromboembolism, heart failure or adrenal crisis after treatment requires urgent care.",
    examTraps: "Do not order pituitary/adrenal imaging before biochemically confirming hypercortisolism, and do not screen every patient with common obesity/diabetes absent additional discriminatory features.",
    sourceKeys: ["ENDOCRINE_CUSHING_DIAGNOSIS_CURRENT", "ENDOCRINE_CUSHING_TREATMENT_CURRENT"],
  },
  {
    slug: "acromegaly",
    title: "Acromegaly: Diagnosis & Management",
    bodySystem: "Endocrine",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "Progressive enlargement of hands/feet, coarse facial features, jaw/tooth spacing, sweating, carpal tunnel, sleep apnea, headaches, diabetes, hypertension or cardiomyopathy suggests acromegaly. Changes develop slowly and comparison with old photographs can be revealing.",
    diagnostics: "Screen with age-adjusted IGF-1; confirm equivocal biochemical disease with growth-hormone suppression testing using an oral glucose challenge when appropriate, then obtain pituitary MRI. Evaluate visual fields and associated sleep, cardiac, metabolic and colon-neoplasia risks.",
    priorities: "Transsphenoidal surgery is first-line for most resectable pituitary adenomas; persistent disease uses somatostatin-receptor ligands, pegvisomant or cabergoline according to tumor/biochemical features, with radiotherapy selectively.",
    medicationSafety: "Somatostatin analogues can cause gallstones, GI effects and glucose disturbance; pegvisomant requires liver monitoring and does not shrink every tumor; cabergoline can cause nausea/orthostasis and impulse-control effects.",
    redFlags: "Acute visual loss/ophthalmoplegia, severe headache suggesting pituitary apoplexy, decompensated cardiomyopathy or airway compromise requires urgent care.",
    examTraps: "Random GH is not a good screening test because secretion is pulsatile. A normal pituitary MRI before biochemical confirmation does not exclude ectopic or microscopic disease.",
    sourceKeys: ["ENDOCRINE_ACROMEGALY_CURRENT"],
  },
  {
    slug: "primary-hyperparathyroidism",
    title: "Primary Hyperparathyroidism",
    bodySystem: "Endocrine",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "Primary hyperparathyroidism causes elevated calcium with an inappropriately high or nonsuppressed PTH and may present with nephrolithiasis, osteoporosis/fracture, kidney dysfunction or neurocognitive symptoms; many patients are detected incidentally.",
    diagnostics: "Confirm corrected or ionized calcium and PTH, assess 25-OH vitamin D, renal function, 24-hour urine calcium/stone risk and DXA including cortical sites. Distinguish familial hypocalciuric hypercalcemia using urinary calcium context before surgery; localization imaging is for operative planning, not diagnosis.",
    priorities: "Parathyroidectomy is definitive and recommended for symptomatic disease and guideline-defined asymptomatic criteria; otherwise monitor calcium, kidney and bone status. Correct vitamin-D deficiency cautiously and maintain normal—not restricted—dietary calcium unless another reason exists.",
    medicationSafety: "Cinacalcet lowers calcium but does not reliably improve bone density; bisphosphonates improve bone density but do not cure PTH excess. Severe hypercalcemia treatment uses IV fluids and cause-specific antiresorptive/calcitonin strategies rather than cinacalcet alone in crisis.",
    redFlags: "Severe symptomatic hypercalcemia, arrhythmia, dehydration/AKI, pancreatitis or altered mental status requires emergency management.",
    examTraps: "Do not order sestamibi/ultrasound to diagnose PHPT and do not assume an elevated PTH with low/normal calcium is primary disease before excluding vitamin-D deficiency, CKD and malabsorption.",
    sourceKeys: ["INTERNATIONAL_PHPT_2022_CURRENT"],
  },
  {
    slug: "pituitary-mass-evaluation",
    title: "Pituitary Mass & Hypopituitarism Evaluation",
    bodySystem: "Endocrine",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PMHNP", "WHNP"],
    recognize: "Pituitary lesions can cause mass effect—headache, bitemporal visual loss, ophthalmoplegia—or hormone excess/deficiency. Fatigue, amenorrhea, low libido, hyponatremia, secondary hypothyroidism and adrenal insufficiency may reflect hypopituitarism rather than primary end-organ disease.",
    diagnostics: "For a pituitary incidentaloma or suspected mass, assess prolactin, IGF-1 and pituitary target axes including morning cortisol and free T4 with TSH interpreted in context; obtain dedicated pituitary MRI and formal visual fields when the lesion abuts/compresses the optic apparatus. Avoid hook-effect error by requesting dilution for a very large mass with unexpectedly modest prolactin.",
    priorities: "Urgently treat ACTH deficiency before thyroid replacement when both are present, refer visual/mass-effect lesions and hormone-secreting tumors to endocrinology/neurosurgery and monitor small nonfunctioning lesions according to size and growth risk.",
    medicationSafety: "Starting levothyroxine before glucocorticoid replacement in combined central adrenal/thyroid deficiency can precipitate adrenal crisis. Dopamine agonists are first-line for most prolactinomas and can markedly shrink tumors, but require psychiatric/orthostatic counseling.",
    redFlags: "Sudden severe headache, visual loss/ophthalmoplegia, hypotension, hyponatremia/hypoglycemia or acute pituitary apoplexy requires emergency endocrine/neurosurgical treatment.",
    examTraps: "A normal TSH does not exclude central hypothyroidism when free T4 is low, and a very large prolactinoma can have a falsely modest prolactin result from assay hook effect.",
    sourceKeys: ["ENDOCRINE_PITUITARY_INCIDENTALOMA_CURRENT", "ENDOCRINE_HYPOPITUITARY_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
