import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch40 = [
  {
    slug: "antidepressant-prescribing",
    title: "Antidepressant Prescribing",
    bodySystem: "Pharmacology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PMHNP", "PNP", "WHNP"],
    recognize: "Antidepressant selection starts with the diagnosis and symptom profile rather than a favorite drug: screen for bipolar disorder, substance use, suicide risk, pregnancy/reproductive goals, sexual adverse effects, sleep/appetite symptoms, pain, prior response and interacting medications before treating presumed unipolar depression or anxiety.",
    diagnostics: "Establish baseline severity and function with clinical assessment plus a validated scale when useful; order TSH, CBC, B12 or other tests only when history/exam suggests a medical contributor. Review QT risk, sodium risk, bleeding medications and CYP interactions when the candidate antidepressant makes them clinically relevant.",
    priorities: "SSRIs and SNRIs are common first-line options for depressive and anxiety disorders, with bupropion, mirtazapine or other agents chosen according to comorbidity and adverse-effect priorities. Reassess early for activation/suicidality and again after an adequate therapeutic trial before declaring nonresponse; optimize dose, adherence, psychotherapy and diagnosis before serial switching.",
    medicationSafety: "SSRIs/SNRIs can cause GI symptoms, sexual dysfunction, bleeding risk, hyponatremia and discontinuation syndromes; bupropion lowers seizure threshold and is avoided in eating disorders/seizure disorders; mirtazapine can increase appetite/weight and sedation. Serotonergic combinations and MAOIs require strict interaction/washout awareness because serotonin syndrome can be life-threatening.",
    redFlags: "New mania/hypomania, severe agitation, suicidal intent, serotonin syndrome, severe hyponatremia, seizure or dangerous medication interaction requires urgent reassessment rather than simple dose escalation.",
    examTraps: "Do not treat a positive PHQ-9 as proof of unipolar depression without screening for past mania/hypomania. Do not stop paroxetine or venlafaxine abruptly after chronic use and mistake discontinuation symptoms for relapse.",
    sourceKeys: ["APA_MDD_CURRENT", "APA_ANXIETY_CURRENT", "FDA_ANTIDEPRESSANT_CURRENT"],
  },
  {
    slug: "antipsychotic-prescribing",
    title: "Antipsychotic Prescribing & Monitoring",
    bodySystem: "Pharmacology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PMHNP", "ENP"],
    recognize: "Antipsychotic choice depends on target syndrome, prior response, metabolic risk, EPS/tardive-dyskinesia vulnerability, prolactin effects, QT/conduction risk, sedation, pregnancy and adherence. First-generation versus second-generation labels do not predict every adverse effect; compare the actual agent profile.",
    diagnostics: "Before and during therapy monitor weight/BMI, BP, glucose/A1C and lipids, and perform structured movement-disorder assessment such as AIMS at appropriate intervals. Obtain ECG, prolactin, CBC or other tests when the agent, symptoms or patient risk makes them relevant rather than ordering one universal panel for every drug.",
    priorities: "Use the lowest effective dose for the defined target, reassess response and adverse effects, and offer a long-acting injectable when it fits patient preference or adherence needs. Clozapine is a key treatment for treatment-resistant schizophrenia and persistent suicide risk when appropriate, with ongoing ANC monitoring despite removal of the federal REMS requirement.",
    medicationSafety: "Antipsychotics can cause metabolic disease, akathisia/EPS, tardive dyskinesia, orthostasis, QT prolongation and hyperprolactinemia. Clozapine adds severe neutropenia, myocarditis, seizure and potentially fatal constipation/ileus risk; the FDA removed mandatory Clozapine REMS participation in 2025, so do not teach enrollment as current U.S. law.",
    redFlags: "Neuroleptic malignant syndrome, severe dystonia affecting airway, syncope/QT arrhythmia, clozapine myocarditis symptoms, severe constipation/ileus, serious infection with neutropenia or dangerous psychosis requires urgent evaluation.",
    examTraps: "Do not use antipsychotics as routine long-term treatment for uncomplicated insomnia or behavioral symptoms of dementia without a defined severe indication/risk discussion. Do not teach the retired Clozapine REMS as a current prescribing barrier.",
    sourceKeys: ["APA_SCHIZOPHRENIA_CURRENT", "FDA_CLOZAPINE_REMS_REMOVED_2025"],
  },
  {
    slug: "mood-stabilizer-prescribing",
    title: "Lithium, Valproate & Mood-Stabilizer Prescribing",
    bodySystem: "Pharmacology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PMHNP", "WHNP", "ENP"],
    recognize: "Mood stabilizers are selected by acute mania versus bipolar depression versus maintenance, suicidality, kidney/liver function, weight/metabolic priorities, pregnancy potential and prior response. Lithium, valproate, lamotrigine and carbamazepine have distinct roles and cannot be substituted solely because they share a 'mood stabilizer' label.",
    diagnostics: "Before lithium obtain renal function, thyroid status, calcium, pregnancy status when relevant and a trough level plan; ECG is appropriate with cardiac risk. Before valproate assess liver/CBC/pregnancy context; before lamotrigine review interacting valproate and rash history; carbamazepine requires CBC, liver, sodium and ancestry-specific HLA risk assessment when indicated.",
    priorities: "Use lithium or guideline-supported antimanic therapy for appropriate acute/maintenance disease; use lamotrigine primarily for bipolar-depression/maintenance prevention rather than acute mania. Build a lab-level and symptom follow-up plan and teach hydration, illness and interaction precautions before the first prescription.",
    medicationSafety: "Lithium has a narrow therapeutic index and levels rise with dehydration, NSAIDs, ACEi/ARBs and thiazides; toxicity can cause tremor, ataxia, confusion, GI symptoms and renal/neurotoxicity. Valproate has major fetal, hepatic and platelet risks and should be avoided in pregnancy when possible; lamotrigine must be titrated slowly because serious rash risk rises with rapid titration or valproate.",
    redFlags: "Lithium neurotoxicity, severe dehydration with elevated level, valproate hepatitis/pancreatitis, severe thrombocytopenia, or mucosal/blistering rash on lamotrigine/carbamazepine requires immediate medication cessation and urgent evaluation.",
    examTraps: "Do not use lamotrigine as rapid acute-mania treatment and do not interpret one lithium concentration without verifying timing relative to the last dose. A patient stable on lithium still needs ongoing renal/thyroid and interaction surveillance.",
    sourceKeys: ["APA_BIPOLAR_CURRENT", "FDA_LITHIUM_CURRENT", "FDA_VALPROATE_CURRENT"],
  },
  {
    slug: "adhd-medication-prescribing",
    title: "ADHD Stimulant & Nonstimulant Prescribing",
    bodySystem: "Pharmacology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PMHNP", "PNP"],
    recognize: "Medication is used for a confirmed impairing ADHD diagnosis after evaluating sleep, anxiety/depression, trauma, bipolar symptoms, substance use, learning disorders and cardiovascular history. Stimulants are highly effective for many patients, while atomoxetine, guanfacine/clonidine ER and selected other nonstimulants fit different risk and preference profiles.",
    diagnostics: "Document baseline BP/HR, weight and height/growth in children, appetite/sleep, tics, substance/diversion risk and personal/family cardiac history. Routine ECG is not required for every healthy patient, but syncope, concerning murmur/history or known heart disease warrants appropriate cardiovascular evaluation.",
    priorities: "Choose a long-acting formulation when it improves adherence, school/work coverage or lowers misuse risk, titrate to functional benefit rather than a numeric rating-scale target alone and combine with behavioral/environmental interventions. Reassess growth, BP/HR, sleep, appetite, mood and diversion at follow-up.",
    medicationSafety: "Stimulants can cause appetite/weight loss, insomnia, BP/HR elevation, anxiety or misuse and can precipitate/worsen mania or psychosis in susceptible patients. Atomoxetine carries a suicidality warning in younger patients and CYP2D6 considerations; alpha-2 agonists cause sedation/hypotension and should be tapered to avoid rebound hypertension.",
    redFlags: "Chest pain/syncope, new psychosis/mania, severe hypertension, suicidal deterioration, significant diversion or dangerous stimulant misuse requires urgent reassessment.",
    examTraps: "Do not diagnose ADHD from medication response and do not require routine cardiac testing in every asymptomatic child with a normal history/exam. Controlled-substance monitoring laws vary by jurisdiction and should not be replaced with invented universal refill rules.",
    sourceKeys: ["AAP_ADHD_CURRENT", "FDA_STIMULANT_CURRENT"],
  },
  {
    slug: "benzodiazepine-sedative-prescribing",
    title: "Benzodiazepine & Sedative-Hypnotic Prescribing",
    bodySystem: "Pharmacology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PMHNP", "ENP"],
    recognize: "Benzodiazepines can be useful for selected acute anxiety, catatonia, seizure, alcohol-withdrawal and procedural indications but carry tolerance, physiologic dependence, cognitive/fall and overdose risks. Chronic insomnia/anxiety usually has safer first-line behavioral and nonbenzodiazepine strategies.",
    diagnostics: "Before prescribing review age/falls, sleep apnea/COPD, pregnancy, alcohol/opioid use, substance-use disorder, other sedatives and prior withdrawal. Reassess actual benefit, escalating dose/early refills and daytime impairment during chronic therapy.",
    priorities: "Use the lowest effective dose for the shortest reasonable duration when a benzodiazepine is indicated and pair with definitive therapy such as CBT/SSRI or withdrawal treatment. For long-term users whose risks exceed benefits, use an individualized gradual taper with shared planning rather than abrupt discontinuation.",
    medicationSafety: "Benzodiazepines plus opioids/alcohol markedly increase respiratory-depression/overdose risk. Abrupt cessation after dependence can cause severe anxiety, delirium and seizures; the 2025 ASAM-led taper guideline emphasizes patient-specific gradual reduction rather than a single forced schedule.",
    redFlags: "Respiratory depression, severe intoxication, withdrawal seizure/delirium, falls with head injury, pregnancy with high-dose dependence or concurrent opioid overdose risk requires urgent monitored care.",
    examTraps: "Do not equate physiologic dependence with addiction, but do not dismiss misuse because a benzodiazepine was prescribed. Never abruptly stop a chronically dependent patient simply because the medication appears on a high-risk-drug list.",
    sourceKeys: ["ASAM_BENZODIAZEPINE_TAPER_CURRENT", "FDA_BENZODIAZEPINE_CURRENT"],
  },
  {
    slug: "opioid-analgesic-prescribing",
    title: "Opioid Analgesic Prescribing & Risk Mitigation",
    bodySystem: "Pharmacology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PMHNP", "ENP"],
    recognize: "Opioids can be appropriate for severe acute pain, cancer/palliative pain and selected chronic pain when expected functional benefit outweighs risk. The goal is meaningful improvement in pain-related function and quality of life, not elimination of all pain or adherence to one rigid morphine-equivalent ceiling.",
    diagnostics: "Before chronic therapy define diagnosis and functional goals, review PDMP where required/available, overdose/SUD history, sleep apnea, kidney/liver disease, pregnancy and concurrent benzodiazepines/alcohol; use toxicology selectively as a clinical tool, not punishment. Reassess benefit, adverse effects and risky use at follow-up.",
    priorities: "Prefer nonopioid and nonpharmacologic treatments for most subacute/chronic pain, use immediate-release opioids and the lowest effective dose when starting, prescribe no greater quantity than needed for the expected severe-pain duration and offer naloxone when overdose risk is elevated. If long-term risks outweigh benefit, taper collaboratively and gradually unless an imminent life-threatening issue requires faster action.",
    medicationSafety: "Respiratory depression risk rises with dose, sleep-disordered breathing and sedative co-use. Methadone has QT and delayed accumulation risk; tramadol adds serotonergic/seizure risk. CDC 2022 uses dosage guideposts rather than inflexible thresholds—avoid turning 50 or 90 MME/day into automatic forced-discontinuation rules.",
    redFlags: "Overdose, respiratory depression, severe sedation, diversion with imminent danger, opioid-induced hyperalgesia with escalating harm or acute suicidality requires urgent intervention and OUD assessment when appropriate.",
    examTraps: "Do not abruptly discontinue stable chronic opioids because a patient crosses a numeric MME threshold and do not use toxicology results to dismiss a patient from care. Naloxone prescribing is harm reduction, not evidence of misuse.",
    sourceKeys: ["CDC_OPIOID_2022_CURRENT", "FDA_OPIOID_CURRENT"],
  },
  {
    slug: "hormonal-contraception-prescribing",
    title: "Hormonal Contraception Prescribing",
    bodySystem: "Pharmacology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "WHNP", "PNP"],
    recognize: "Contraceptive choice should follow efficacy preference, bleeding profile, dysmenorrhea/acne goals, adherence, privacy, reversibility, STI risk, postpartum/breastfeeding context and medical eligibility. Long-acting reversible methods are highly effective but should be offered without coercion.",
    diagnostics: "Use the CDC U.S. Medical Eligibility Criteria 2024 and Selected Practice Recommendations rather than memorized blanket contraindication lists. Measure BP before combined hormonal contraception and assess migraine with aura, smoking/age, VTE/thrombophilia, severe hypertension, postpartum timing, liver disease and breast-cancer history; routine pelvic exam or thrombophilia testing is not required for most contraceptive starts.",
    priorities: "Use shared decision-making across IUD, implant, pill, patch, ring and injection options; start promptly when pregnancy can be reasonably excluded and provide backup contraception according to method/timing. Offer condoms/STI prevention separately because hormonal/LARC methods do not prevent infection.",
    medicationSafety: "Estrogen-containing methods increase thrombotic/stroke risk and are contraindicated or generally avoided in several high-risk conditions such as migraine with aura and certain VTE/hypertension states. Enzyme-inducing antiseizure drugs reduce effectiveness of some hormonal methods; DMPA affects bone density and can delay return to fertility.",
    redFlags: "Suspected pregnancy complication, acute VTE/PE/stroke symptoms, severe new neurologic aura, severe hypertension or serious method complication requires urgent evaluation and method reassessment.",
    examTraps: "Do not require a pelvic exam or Pap test before starting most contraception and do not impose one 'best' method based on age/parity. Smoking alone is not an estrogen contraindication in every young patient, but smoking at age 35+ changes MEC category by amount.",
    sourceKeys: ["CDC_US_MEC_2024", "CDC_US_SPR_2024"],
  },
  {
    slug: "menopausal-hormone-therapy-prescribing",
    title: "Menopausal Hormone Therapy Prescribing",
    titleAliases: ["Menopause & Hormone Replacement Therapy"],
    slugAliases: ["np-clinical-menopause-hrt"],
    bodySystem: "Pharmacology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "WHNP"],
    recognize: "Menopausal hormone therapy is the most effective treatment for bothersome vasomotor symptoms and treats genitourinary syndrome with local therapy when appropriate. Benefit-risk is generally most favorable for healthy symptomatic patients younger than 60 or within about 10 years of menopause onset who lack major contraindications; therapy is individualized rather than stopped at an arbitrary age.",
    diagnostics: "In typical midlife menopause, diagnosis is clinical and routine FSH testing is unnecessary. Before systemic therapy assess unexplained bleeding, breast/endometrial cancer history, prior VTE/stroke/MI, liver disease, migraine and cardiovascular risk; investigate abnormal uterine bleeding before attributing it to menopause.",
    priorities: "Use estrogen alone after hysterectomy and add adequate endometrial protection with a progestogen when the uterus is present. Prefer local low-dose vaginal estrogen or other GSM-directed therapy when symptoms are isolated to vaginal/urinary tissues; systemic route and dose should be individualized to risk and symptom burden.",
    medicationSafety: "Systemic estrogen can increase VTE/stroke risk, with route and baseline risk affecting the magnitude; unopposed systemic estrogen increases endometrial-cancer risk in patients with a uterus. Transdermal estrogen may offer a more favorable thrombotic/metabolic profile in selected patients, but no route is risk-free.",
    redFlags: "Postmenopausal bleeding, new VTE/stroke symptoms, breast mass, severe liver disease or acute coronary event requires prompt evaluation and reconsideration of systemic therapy.",
    examTraps: "Do not prescribe systemic hormone therapy solely to prevent cardiovascular disease or dementia and do not require every patient to stop at age 65. Vaginal estrogen has substantially lower systemic exposure than systemic MHT and follows a different risk discussion.",
    sourceKeys: ["NAMS_HT_2022_CURRENT", "ACOG_MENOPAUSE_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
