import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch62 = [
  {
    slug: "mild-cognitive-impairment-dementia-evaluation",
    title: "Mild Cognitive Impairment & Dementia Evaluation",
    bodySystem: "Gerontology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PMHNP"],
    recognize: "Cognitive decline becomes a neurocognitive disorder when objective decline affects function; mild cognitive impairment preserves basic independence better than dementia. Collateral history is essential because patients may underrecognize change, while depression, delirium, hearing loss and medication effects can mimic impairment.",
    diagnostics: "Use a validated cognitive instrument plus functional/IADL assessment, neurologic exam and collateral history; evaluate reversible contributors with targeted CBC/CMP/TSH/B12 and medication/sleep/mood review. Brain imaging is indicated for atypical, rapid, focal or otherwise guideline-supported presentations rather than as a screening substitute.",
    priorities: "Identify likely subtype, address vascular/hearing/sleep/depression contributors, review driving/medication/financial safety and support caregivers. Cholinesterase inhibitors and memantine are used in selected Alzheimer/Lewy-body phenotypes; disease-modifying anti-amyloid treatment requires specialist biomarker, MRI and risk selection.",
    medicationSafety: "Cholinesterase inhibitors can cause bradycardia, syncope and weight loss; anticholinergics and sedative-hypnotics worsen cognition. Anti-amyloid monoclonal antibodies carry ARIA/bleeding risks and are not general dementia therapy.",
    redFlags: "Rapid progression over weeks-months, focal deficit, seizure, gait/urinary triad suggesting NPH, severe behavior change or delirium requires expedited neurologic/medical evaluation.",
    examTraps: "Do not diagnose dementia from one low screening score and do not call delirium a new baseline. Education or language differences affect screening performance and require appropriate interpretation.",
    sourceKeys: ["AAN_DEMENTIA_CURRENT", "NIA_ADRD_CURRENT"],
  },
  {
    slug: "frailty-sarcopenia",
    title: "Frailty & Sarcopenia",
    bodySystem: "Gerontology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "Frailty is reduced physiologic reserve and vulnerability to stressors; sarcopenia is low muscle strength/mass/performance. Weight loss, exhaustion, slow gait, weak grip, recurrent falls and prolonged recovery after minor illness are clues but neither condition is synonymous with chronological age.",
    diagnostics: "Use a validated frailty or gait/strength assessment and evaluate reversible contributors—malnutrition, depression, anemia, endocrine disease, cardiopulmonary disease, medication burden and inactivity. Screen protein/calorie access and oral/dental barriers rather than relying on serum albumin.",
    priorities: "Use progressive resistance/aerobic activity, adequate protein/energy, vitamin-D correction when deficient, medication simplification and treatment of contributing disease. Frailty should inform surgical/oncologic/procedural shared decision-making and prehabilitation, not automatically exclude treatment.",
    medicationSafety: "Sedatives, anticholinergics and overly aggressive BP/glucose regimens can magnify frailty harms; deprescribe based on goals and time-to-benefit. Appetite stimulants such as megestrol have thrombotic/adrenal harms and are not routine frailty therapy.",
    redFlags: "Rapid unexplained weight loss, severe functional decline, recurrent falls/syncope, dysphagia or inability to meet nutritional needs requires urgent cause-directed evaluation.",
    examTraps: "Low BMI alone does not define frailty and obesity does not exclude sarcopenia. Frailty is potentially modifiable and should not be used as shorthand for 'do not treat.'",
    sourceKeys: ["AGS_FRAILTY_CURRENT", "ICFSR_FRAILTY_CURRENT"],
  },
  {
    slug: "older-driver-safety",
    title: "Driving Safety in Older Adults",
    bodySystem: "Gerontology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "Driving risk can rise with cognitive impairment, visual-field loss, neuropathy, Parkinsonism, syncope, sleepiness and sedating medications, but age alone does not determine fitness to drive. Recent crashes, getting lost and caregiver concern are high-value history.",
    diagnostics: "Assess vision, cognition, motor function, neck mobility, reaction/attention, medication effects and episodes of loss of consciousness; office tools identify risk but do not perfectly predict on-road performance. Refer for occupational-therapy/comprehensive driving evaluation when uncertainty remains.",
    priorities: "Treat reversible contributors, simplify sedating medications, discuss transportation alternatives early and use collaborative restriction/retirement planning. Follow state-specific clinician reporting requirements because mandatory/permissive reporting varies.",
    medicationSafety: "Benzodiazepines, Z-drugs, opioids, sedating antihistamines, antipsychotics and some anticonvulsants impair driving; warn during initiation/dose changes and address alcohol/cannabis co-use.",
    redFlags: "Recent unexplained syncope, seizure, recurrent crashes, severe visuospatial impairment or inability to follow traffic rules requires immediate driving cessation pending evaluation.",
    examTraps: "Do not use MMSE/MoCA score alone as a legal driving cutoff and do not assume every state has the same physician-reporting law.",
    sourceKeys: ["AGS_NHTSA_OLDER_DRIVER_CURRENT"],
  },
  {
    slug: "orthostatic-hypotension-older-adults",
    title: "Orthostatic Hypotension in Older Adults",
    bodySystem: "Gerontology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "Lightheadedness, falls, weakness, blurred vision or syncope after standing may reflect orthostatic hypotension from volume depletion, medications, autonomic neuropathy or neurodegenerative disease. Older adults may report falls rather than classic dizziness.",
    diagnostics: "Measure BP/HR after supine rest and during standing using standardized timing, review volume status, anemia, glucose, ECG and culprit medications and assess whether heart-rate response suggests neurogenic versus non-neurogenic physiology.",
    priorities: "Treat reversible causes first, adjust antihypertensive/diuretic/vasodilating drugs, increase fluids/salt when safe, use compression/counterpressure and slow position changes and prescribe midodrine/droxidopa selectively for persistent neurogenic symptoms.",
    medicationSafety: "Midodrine causes supine hypertension/urinary retention and should be timed away from bedtime; fludrocortisone can cause edema, hypokalemia and heart-failure worsening. Do not reflexively abandon all BP treatment when seated/supine hypertension remains dangerous.",
    redFlags: "Syncope during exertion, chest pain, major arrhythmia, GI bleeding/anemia, severe dehydration or focal neurologic deficit requires urgent alternative-cause evaluation.",
    examTraps: "Orthostatic symptoms can occur even when a single office measurement is negative; repeat under typical conditions when suspicion is high. Falls are a possible presenting symptom.",
    sourceKeys: ["AHA_ORTHOSTATIC_HYPOTENSION_CURRENT", "AAN_AUTONOMIC_CURRENT"],
  },
  {
    slug: "pressure-injury-prevention-management",
    title: "Pressure Injury Prevention & Management",
    bodySystem: "Gerontology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP"],
    recognize: "Pressure injury results from sustained pressure/shear over bony prominences or devices and risk rises with immobility, moisture, malnutrition, poor perfusion and sensory loss. Deep-tissue injury may appear as persistent deep discoloration before skin opens.",
    diagnostics: "Stage using current NPIAP definitions only after cleansing and adequate visualization; unstageable injury has obscuring slough/eschar, while deep-tissue injury has characteristic deep discoloration. Assess perfusion, infection/osteomyelitis risk, nutrition and device-related pressure.",
    priorities: "Offload/reposition with individualized schedule, use pressure-redistribution surfaces, manage moisture/incontinence, optimize nutrition/perfusion and debride devitalized tissue when indicated. Use dressings that maintain appropriate moisture and involve wound specialists for deep/complex injury.",
    medicationSafety: "Systemic antibiotics are for cellulitis, osteomyelitis or systemic infection—not colonization of a chronic wound. Stable dry heel eschar without infection/ischemia complications is often left intact rather than debrided reflexively.",
    redFlags: "Spreading cellulitis, crepitus, sepsis, exposed/infected bone, rapidly expanding necrosis or ischemic limb requires urgent surgical/wound/infectious evaluation.",
    examTraps: "Do not reverse-stage a healing wound and do not call moisture-associated dermatitis a pressure injury solely because it is near the sacrum.",
    sourceKeys: ["NPIAP_PRESSURE_INJURY_CURRENT"],
  },
  {
    slug: "constipation-older-adults",
    title: "Constipation in Older Adults",
    bodySystem: "Gerontology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "Constipation can reflect slow transit, pelvic-floor dysfunction, low mobility/fluid/fiber, opioid or anticholinergic medication, metabolic disease or obstruction. New change in bowel habit, anemia, weight loss or blood is not simply age-related constipation.",
    diagnostics: "Review stool frequency/form/straining, medications, diet, mobility, rectal evacuation and alarm features; perform abdominal/rectal exam when indicated and reserve colonoscopy/imaging for age-appropriate screening or red flags rather than routine uncomplicated constipation.",
    priorities: "Address drugs and toileting/activity, use soluble fiber when appropriate and osmotic laxatives such as PEG as common first-line medication; add stimulant laxative when needed. Opioid-induced constipation often needs scheduled prophylaxis and may require a peripheral mu-opioid antagonist when standard regimens fail.",
    medicationSafety: "Magnesium/phosphate laxatives can cause dangerous electrolyte accumulation in CKD; mineral oil increases aspiration risk; chronic stimulant use is not automatically harmful but should be purposeful. Avoid bulk fiber in obstruction/impaction.",
    redFlags: "Obstipation with vomiting/distention, GI bleeding, severe pain, weight loss/anemia or fecal impaction with delirium/urinary retention requires urgent evaluation.",
    examTraps: "Overflow diarrhea can be fecal impaction and adding loperamide can worsen it. Do not prescribe fiber blindly to a patient with impaction or obstruction symptoms.",
    sourceKeys: ["AGA_CONSTIPATION_CURRENT", "AGS_CONSTIPATION_CURRENT"],
  },
  {
    slug: "insomnia-older-adults",
    title: "Insomnia in Older Adults",
    bodySystem: "Gerontology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PMHNP"],
    recognize: "Chronic insomnia is difficulty initiating/maintaining sleep or early awakening with daytime impairment despite adequate opportunity. Older adults often have earlier circadian timing and lighter sleep, but persistent impairment is not an inevitable part of aging.",
    diagnostics: "Assess sleep schedule, naps, pain, nocturia, depression/anxiety, restless legs, sleep apnea, substances and medications; use sleep diary and screen for OSA/RLS. Polysomnography is not routine for uncomplicated insomnia unless another sleep disorder is suspected.",
    priorities: "CBT-I is first-line and includes stimulus control, sleep restriction/compression, cognitive work and sleep scheduling. Treat underlying OSA/pain/depression and use medication only when benefits justify falls/cognition risks, with a deprescribing plan.",
    medicationSafety: "Benzodiazepines and Z-drugs increase falls, delirium and cognitive impairment and are generally avoided or minimized in older adults; diphenhydramine/doxylamine add anticholinergic burden. Low-dose doxepin, ramelteon or orexin antagonists may fit selected patients but still require interaction/fall review.",
    redFlags: "Severe daytime sleepiness with driving risk, mania, suicidality, suspected sleep apnea/hypoventilation or complex sleep behavior on hypnotics requires urgent reassessment.",
    examTraps: "Do not prescribe sedatives before evaluating sleep apnea and do not tell older adults they need less sleep simply because sleep becomes fragmented.",
    sourceKeys: ["AASM_INSOMNIA_CURRENT", "AGS_BEERS_2023_CURRENT"],
  },
  {
    slug: "functional-decline-iatrogenesis",
    title: "Functional Decline & Iatrogenesis in Older Adults",
    bodySystem: "Gerontology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP"],
    recognize: "A sudden loss of mobility, ADLs or cognition in an older adult often signals acute illness, delirium, medication toxicity, deconditioning or environmental change rather than irreversible aging. Hospital bedrest can produce rapid muscle loss and dependency.",
    diagnostics: "Establish pre-illness baseline from patient/caregiver, assess ADLs/IADLs, gait, cognition, nutrition, pain and medication changes and look for occult infection, heart/lung disease, anemia, endocrine disease and neurologic injury.",
    priorities: "Treat the cause while mobilizing early, protecting sleep/nutrition/orientation, minimizing catheters/restraints/sedatives and arranging PT/OT plus safe discharge support. Recovery goals should be based on prior function and patient priorities.",
    medicationSafety: "New opioids, anticholinergics, benzodiazepines, antihypertensive intensification and hypoglycemia-prone regimens commonly precipitate functional decline; review timing before assuming disease progression.",
    redFlags: "Acute focal deficit, inability to stand after fall, new delirium, severe orthostasis, rapid weight loss or unsafe discharge without support requires urgent evaluation/planning.",
    examTraps: "Do not document 'failure to thrive' as an endpoint without identifying causes and do not assume a hospitalized older adult's current function is their baseline.",
    sourceKeys: ["AGS_HOSPITAL_CARE_CURRENT", "AHRQ_MOBILITY_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
