import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch52 = [
  {
    slug: "ecg-interpretation-primary-care",
    title: "12-Lead ECG Interpretation for NPs",
    bodySystem: "Diagnostics",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Read ECGs systematically: rate, rhythm, axis, intervals, chamber/voltage clues, QRS morphology and ST-T changes. The clinical question matters—palpitations, syncope, chest pain, electrolyte disease and medication monitoring change which subtle findings become urgent.",
    diagnostics: "Verify calibration/lead placement and compare prior tracings; measure PR, QRS and QTc with awareness that automated interpretation can misclassify rhythm and QT. Localize ischemic changes anatomically and distinguish STEMI mimics such as LVH, LBBB/pacing, pericarditis and early repolarization using clinical context and serial ECGs.",
    priorities: "Activate emergency pathways for acute ischemic patterns with compatible symptoms, unstable brady/tachyarrhythmia, high-grade block or dangerous QT-related ventricular ectopy. Stable incidental abnormalities should lead to cause-directed follow-up—electrolytes, echo, ambulatory monitoring or cardiology—not automatic ED transfer.",
    medicationSafety: "Before QT-prolonging or AV-nodal drugs, review baseline conduction/QTc and interacting medications; correct potassium/magnesium when indicated. Do not use flecainide/class Ic drugs in unassessed structural/ischemic disease.",
    redFlags: "ST-elevation/ischemic equivalent, ventricular tachycardia, torsades, complete/high-grade AV block, Brugada-like pattern with syncope or hyperkalemic ECG toxicity requires urgent intervention.",
    examTraps: "Do not trust the machine-read rhythm or QTc without checking the tracing, and do not diagnose MI from isolated Q waves/ST-T change without symptoms, prior ECGs and appropriate biomarkers.",
    sourceKeys: ["AHA_ECG_INTERPRETATION_CURRENT", "ACS_2025"],
  },
  {
    slug: "spirometry-pft-interpretation",
    title: "Spirometry & Pulmonary Function Test Interpretation",
    bodySystem: "Diagnostics",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP"],
    recognize: "Obstruction is defined by a reduced FEV1/FVC relative to the appropriate lower limit or disease-specific post-bronchodilator criterion; restriction cannot be confirmed by low FVC alone and requires lung volumes. DLCO helps separate emphysema/ILD/pulmonary vascular disease from asthma/chest-wall patterns.",
    diagnostics: "First confirm acceptable/repeatable spirometry and reference values, then classify obstruction, bronchodilator responsiveness and possible restriction; use TLC to confirm restriction and DLCO/KCO plus clinical context to refine cause. Flow-volume loops can reveal upper-airway obstruction or poor effort.",
    priorities: "Use objective results to confirm/redirect asthma/COPD/ILD evaluation, then treat symptoms/risk rather than chasing FEV1 alone. Refer unexplained mixed patterns, severe restriction, rapidly declining function or discordant symptoms for full PFT/pulmonology review.",
    medicationSafety: "Withhold bronchodilators only according to test protocol when diagnostic reversibility is being assessed; do not stop needed inhalers for days without instructions. Oxygen/bronchodilator prescriptions follow clinical criteria, not a single spirometry percentage.",
    redFlags: "Severe hypoxemia, rapidly falling vital capacity, neuromuscular weakness, stridor/fixed upper-airway loop or severe unexplained restriction requires urgent specialty evaluation.",
    examTraps: "Low FVC on office spirometry does not prove restriction and a negative bronchodilator test does not rule out asthma. Fixed FEV1/FVC <0.70 can overdiagnose obstruction in older adults if used without context, except where disease-specific guidelines intentionally use it.",
    sourceKeys: ["ATS_ERS_PFT_CURRENT", "GINA_2026", "GOLD_2026"],
  },
  {
    slug: "chest-xray-interpretation",
    title: "Chest X-Ray Interpretation for NPs",
    bodySystem: "Diagnostics",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Use a consistent approach: image quality/rotation/inspiration, airway, bones/soft tissue, cardiac/mediastinum, diaphragms/pleura and lung fields. Pattern recognition must be tied to symptoms—opacity may be pneumonia, atelectasis, edema, hemorrhage, malignancy or infarct.",
    diagnostics: "Confirm AP versus PA and supine versus upright because heart size, pleural air/fluid and device position change. Compare old films and use CT/ultrasound when x-ray cannot answer the clinical question; a normal chest x-ray does not exclude PE, early pneumonia, asthma or many causes of dyspnea.",
    priorities: "Escalate immediately for tension pneumothorax physiology, large new pneumothorax, severe pulmonary edema, major device malposition or free subdiaphragmatic air; otherwise use the image to guide cause-specific testing rather than treating the report in isolation.",
    medicationSafety: "Radiography itself has low radiation burden, but avoid cascades of repeated imaging without a clinical question. Contrast CT decisions require kidney/allergy and pregnancy context when follow-up imaging is indicated.",
    redFlags: "Mediastinal widening with acute aortic syndrome, large pneumothorax, diffuse edema with hypoxia, free air, cavitary disease with hemoptysis or suspicious mass with SVC/airway symptoms requires urgent evaluation.",
    examTraps: "Do not diagnose cardiomegaly from an AP portable film without accounting for magnification and do not rule out serious cardiopulmonary disease because the CXR is 'normal.'",
    sourceKeys: ["ACR_CHEST_IMAGING_CURRENT"],
  },
  {
    slug: "cbc-differential-interpretation",
    title: "CBC & Differential Interpretation",
    bodySystem: "Diagnostics",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PMHNP", "PNP", "WHNP", "ENP"],
    recognize: "Interpret hemoglobin/indices, platelets and WBC differential together and against prior trend. Neutrophilia can reflect infection, steroids or stress; lymphocytosis can be viral or clonal; eosinophilia can reflect allergy, drug reaction, parasites or hematologic disease.",
    diagnostics: "Use MCV/RDW/reticulocyte count and smear to classify anemia, absolute—not percentage—neutrophil/eosinophil/lymphocyte counts for leukocyte disorders and platelet smear review for clumping. Repeat unexpected critical values and investigate multi-lineage cytopenia more urgently than a stable isolated mild abnormality.",
    priorities: "Treat the cause and risk: severe neutropenia with fever, hemolysis, acute leukemia pattern or dangerous thrombocytopenia is time-sensitive; stable mild abnormalities often need trend plus focused nutritional, infection, medication or marrow evaluation.",
    medicationSafety: "Many drugs cause cytopenias—chemotherapy, antithyroid drugs, clozapine, linezolid, TMP-SMX, valproate and others—so connect the CBC change to medication timing and monitoring requirements rather than automatically attributing it to disease.",
    redFlags: "Blasts, pancytopenia with illness, ANC profound with fever, platelets with major bleeding or rapid hemoglobin drop requires urgent hematology/emergency action.",
    examTraps: "A high WBC is not synonymous with bacterial infection and a normal total WBC can conceal severe neutropenia. Percentage eosinophils without the absolute count can mislead.",
    sourceKeys: ["ASH_CBC_INTERPRETATION_CURRENT"],
  },
  {
    slug: "liver-test-interpretation",
    title: "Liver Chemistry & Synthetic-Function Interpretation",
    bodySystem: "Diagnostics",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "AST/ALT reflect hepatocellular injury, alkaline phosphatase with GGT/bilirubin helps identify cholestasis and albumin/INR reflect synthetic function in context. 'Liver function tests' is an imprecise phrase because aminotransferases can be very high while synthetic function remains intact or normal in advanced cirrhosis.",
    diagnostics: "Classify hepatocellular versus cholestatic versus mixed injury using relative enzyme elevations, then evaluate medications/supplements, alcohol, viral hepatitis, MASLD, autoimmune disease and biliary obstruction. Repeat and fractionate alkaline phosphatase when bone versus hepatic source is uncertain.",
    priorities: "Stop potentially severe hepatotoxic agents, image suspected obstruction and urgently refer acute liver failure or significant synthetic decline. Mild stable transaminase elevation should trigger cause-directed workup rather than indiscriminate viral/autoimmune panels in every patient.",
    medicationSafety: "Acetaminophen toxicity can cause extreme aminotransferases before bilirubin rises; statins rarely cause severe hepatotoxicity and mild stable transaminase elevation is not an automatic reason to stop an indicated statin.",
    redFlags: "INR elevation with encephalopathy, rapidly rising bilirubin, severe RUQ pain/fever/jaundice, hypoglycemia or very high aminotransferases with systemic illness requires urgent evaluation.",
    examTraps: "Normal AST/ALT does not rule out cirrhosis and a high alkaline phosphatase does not prove biliary obstruction until the source is confirmed.",
    sourceKeys: ["ACG_ABNORMAL_LIVER_CHEMISTRIES_CURRENT", "AASLD_DILI_CURRENT"],
  },
  {
    slug: "thyroid-test-interpretation",
    title: "Thyroid Function Test Interpretation",
    bodySystem: "Diagnostics",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PMHNP", "WHNP"],
    recognize: "In primary thyroid disease, TSH and free T4 move predictably; central hypothyroidism can show low free T4 with low/normal/inappropriately modest TSH, and nonthyroidal illness/medications can distort results. Pregnancy uses trimester/laboratory-specific reference considerations.",
    diagnostics: "Start with TSH for most ambulatory screening and add free T4 when abnormal or central disease is suspected; use T3 selectively for suspected T3-toxicosis. Check antibodies to define autoimmune etiology, not to monitor dose response, and review biotin/amiodarone/lithium/glucocorticoid effects.",
    priorities: "Treat the clinical thyroid disorder rather than the lab pattern in isolation and repeat borderline abnormalities after appropriate interval when acute illness or assay interference is plausible. In central hypothyroidism, titrate levothyroxine to free T4/clinical status after adrenal sufficiency is addressed.",
    medicationSafety: "Biotin supplements can falsely lower TSH and raise thyroid hormone immunoassays; amiodarone creates complex thyroid abnormalities and long half-life effects. Starting thyroid hormone before treating significant adrenal insufficiency can precipitate crisis.",
    redFlags: "Thyroid storm, myxedema coma, severe arrhythmia, pituitary mass symptoms or adrenal-crisis concern requires urgent endocrine/emergency care.",
    examTraps: "Do not diagnose central hypothyroidism by TSH alone and do not repeat thyroid antibodies to titrate levothyroxine. Mild TSH fluctuation during acute illness often should be rechecked after recovery.",
    sourceKeys: ["ATA_THYROID_TESTING_CURRENT", "ENDOCRINE_CENTRAL_HYPOTHYROID_CURRENT"],
  },
  {
    slug: "urinalysis-interpretation",
    title: "Urinalysis & Urine Microscopy Interpretation",
    bodySystem: "Diagnostics",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PNP", "WHNP", "ENP"],
    recognize: "Urinalysis is a pattern tool: leukocyte esterase/nitrite plus symptoms support UTI, dysmorphic RBC/RBC casts suggest glomerular bleeding, WBC casts suggest pyelonephritis/interstitial inflammation and granular 'muddy brown' casts support tubular injury. Dipstick protein primarily detects albumin.",
    diagnostics: "Confirm dipstick blood/protein with microscopy and quantitative UACR/PCR when chronic kidney disease is suspected. Culture symptomatic suspected infection appropriately; epithelial contamination reduces confidence and asymptomatic pyuria/bacteriuria should not trigger automatic treatment.",
    priorities: "Use the urine pattern to select the next test—culture for infection, kidney serologies/nephrology for active sediment, imaging for obstruction/stone and UACR for albuminuria. Repeat transient abnormalities after exercise/fever/menses when clinically safe.",
    medicationSafety: "Phenazopyridine and some drugs alter urine color/dipstick interpretation; SGLT2 inhibitors produce expected glycosuria. Anticoagulants can unmask hematuria but do not explain away the need for malignancy/renal evaluation.",
    redFlags: "RBC casts with rising creatinine, obstructed infected urine, gross hematuria with clot retention or severe pyelonephritis requires urgent evaluation.",
    examTraps: "Pyuria is not synonymous with bacterial UTI and dipstick protein can miss light-chain proteinuria. Nitrite negativity does not rule out UTI.",
    sourceKeys: ["KDIGO_CKD_2024", "IDSA_UTI_CURRENT", "AUA_MICROHEMATURIA_CURRENT"],
  },
  {
    slug: "coagulation-test-interpretation",
    title: "PT/INR, aPTT & Coagulation Test Interpretation",
    bodySystem: "Diagnostics",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "WHNP", "ENP"],
    recognize: "PT/INR and aPTT are pathway-sensitive clotting assays, not generic 'bleeding risk' numbers. Isolated PT prolongation suggests warfarin/vitamin-K or factor VII issues; isolated aPTT suggests heparin, inhibitors or intrinsic factor deficiency; both prolonged raises liver disease, DIC, severe deficiency or high anticoagulant exposure.",
    diagnostics: "Confirm medication timing and specimen quality, then use mixing studies when unexplained prolongation persists to distinguish factor deficiency from inhibitor. Fibrinogen/D-dimer/platelets help identify DIC, while anti-Xa or drug-specific assays may be more useful than PT/aPTT for selected anticoagulants.",
    priorities: "Treat the cause and reverse anticoagulation only when bleeding/procedure severity justifies it; consult hematology for factor inhibitors/rare disorders. Do not transfuse plasma merely to normalize mildly abnormal coagulation tests in nonbleeding patients.",
    medicationSafety: "INR monitors warfarin, not DOAC intensity; aPTT is not a reliable universal measure of LMWH/DOAC effect. Vitamin K, PCC, idarucizumab/andexanet or other reversal strategies are agent- and scenario-specific.",
    redFlags: "Major bleeding with anticoagulant effect, rapidly falling fibrinogen/platelets, suspected acquired factor inhibitor or intracranial hemorrhage requires emergency reversal/hematology management.",
    examTraps: "A prolonged INR in cirrhosis does not mean the patient is 'auto-anticoagulated,' and normal PT/aPTT does not exclude platelet/von Willebrand disorders.",
    sourceKeys: ["ASH_COAGULATION_TESTING_CURRENT", "ACC_ANTICOAGULATION_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
