import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch66 = [
  {
    slug: "first-episode-psychosis",
    title: "First-Episode Psychosis Evaluation",
    bodySystem: "Psychiatric",
    applicableExams: ["PMHNP", "AANP-FNP", "ANCC-FNP", "ENP"],
    recognize: "New hallucinations, delusions, disorganization, catatonia or marked functional decline requires a first-episode differential that includes primary psychosis, bipolar/depressive illness, substances, medications, delirium, seizures, autoimmune encephalitis and endocrine/metabolic disease. Abrupt onset or fluctuating attention is especially atypical for schizophrenia.",
    diagnostics: "Obtain collateral timeline, neurologic and mental-status exam, substance/medication review and targeted CBC/CMP/TSH/pregnancy/toxicology/infection testing; add imaging, EEG, autoimmune or other studies when focal neurologic signs, seizures, catatonia, rapid onset or atypical age/course is present. Baseline metabolic/weight/BP and movement assessment precedes antipsychotic treatment.",
    priorities: "Address safety and medical causes first, use coordinated specialty care with family/education/vocational support and start an antipsychotic at an effective tolerable dose when primary psychosis is likely. Minimize duration of untreated psychosis while avoiding unnecessary polypharmacy.",
    medicationSafety: "Choose antipsychotic by metabolic, EPS, prolactin, QT, sedation and adherence profile and monitor from the first prescription. Avoid routine antipsychotic polypharmacy and prolonged benzodiazepines; consider long-acting injectable through shared decision when adherence benefit is meaningful.",
    redFlags: "Catatonia, severe agitation/violence, suicidality, inability to eat/drink, delirium, seizure or neurologic/autonomic signs suggesting encephalitis requires urgent inpatient evaluation.",
    examTraps: "Do not diagnose schizophrenia before duration/medical/substance criteria are established and do not assume a positive cannabis screen proves cannabis-induced psychosis when symptoms precede use or persist beyond intoxication.",
    sourceKeys: ["APA_SCHIZOPHRENIA_CURRENT", "SAMHSA_FIRST_EPISODE_PSYCHOSIS_CURRENT"],
  },
  {
    slug: "bipolar-mania-mixed-features",
    title: "Bipolar Mania, Hypomania & Mixed Features",
    bodySystem: "Psychiatric",
    applicableExams: ["PMHNP", "AANP-FNP", "ANCC-FNP", "ENP"],
    recognize: "Mania is a distinct period of elevated/irritable mood and increased energy with decreased sleep need, pressured speech, grandiosity, racing thoughts, distractibility and risky behavior causing marked impairment/hospitalization/psychosis; hypomania is shorter/less impairing and has no psychosis. Mixed depressive symptoms increase suicide risk.",
    diagnostics: "Establish episodic change from baseline and duration/impairment, obtain collateral history and assess substances, steroids, thyroid disease, ADHD and personality/trauma patterns. Before treating 'depression,' ask past decreased sleep need and activation to avoid missing bipolar disorder.",
    priorities: "Acute mania requires an evidence-based antimanic agent—lithium, valproate and/or an effective antipsychotic depending on severity/contraindications—and hospitalization when safety or judgment is severely compromised. Stop antidepressant monotherapy in clear mania and restore sleep/routine.",
    medicationSafety: "Lithium, valproate and antipsychotics have major renal/thyroid, hepatic/teratogenic, metabolic/EPS risks respectively. Valproate is particularly problematic in pregnancy potential; antidepressant monotherapy can destabilize bipolar I illness.",
    redFlags: "Psychosis, severe agitation, suicidality, no sleep with exhaustion, dangerous spending/sexual behavior, inability to care for self or postpartum mania requires urgent psychiatric care.",
    examTraps: "Mood swings within hours after interpersonal stress are not automatically bipolar disorder, and irritability alone is not mania without increased energy/associated symptoms.",
    sourceKeys: ["APA_BIPOLAR_CURRENT", "CANMAT_ISBD_BIPOLAR_CURRENT"],
  },
  {
    slug: "bipolar-depression",
    title: "Bipolar Depression",
    bodySystem: "Psychiatric",
    applicableExams: ["PMHNP", "AANP-FNP", "ANCC-FNP"],
    recognize: "Bipolar depression can look identical to unipolar depression, but past hypomania/mania, antidepressant activation, early/recurrent episodes, family bipolar history and episodic decreased sleep need raise suspicion. Suicide risk is high, especially with mixed features.",
    diagnostics: "Take a lifetime mood history with collateral when possible and screen—but do not diagnose solely from a screening questionnaire. Assess psychosis, mixed/manic symptoms, substances, thyroid disease and medication-induced mood changes before selecting treatment.",
    priorities: "Use evidence-based bipolar-depression treatments such as selected atypical antipsychotics, lithium, lamotrigine or other guideline-supported agents according to bipolar subtype and patient risks; psychotherapy, sleep/rhythm stabilization and suicide prevention are integral.",
    medicationSafety: "Avoid antidepressant monotherapy in bipolar I depression; if an antidepressant is used in selected bipolar depression, combine/monitor according to guideline and stop if activation emerges. Lamotrigine requires slow titration because of serious-rash risk and is not an acute antimanic drug.",
    redFlags: "Suicidal plan/intent, psychotic depression, catatonia, severe mixed agitation or inability to maintain nutrition/hydration requires urgent hospitalization/ECT consideration.",
    examTraps: "A history of depression plus irritability is not enough for bipolar diagnosis, but repeated antidepressant-induced activation should trigger a careful bipolar history rather than another antidepressant switch.",
    sourceKeys: ["APA_BIPOLAR_CURRENT", "CANMAT_ISBD_BIPOLAR_CURRENT"],
  },
  {
    slug: "panic-disorder-agoraphobia",
    title: "Panic Disorder & Agoraphobia",
    bodySystem: "Psychiatric",
    applicableExams: ["PMHNP", "AANP-FNP", "ANCC-FNP", "ENP"],
    recognize: "Panic attacks are abrupt surges of intense fear with autonomic/cognitive symptoms; panic disorder requires recurrent unexpected attacks plus persistent concern/behavior change. Agoraphobia is fear/avoidance of situations where escape/help may be difficult and can occur with or without panic disorder.",
    diagnostics: "First episodes require medical/substance review based on presentation—arrhythmia, hyperthyroidism, asthma, hypoglycemia, stimulant/cannabis use and PE can mimic panic. Once medically appropriate, diagnose from unexpected recurrence and anticipatory avoidance rather than one isolated attack.",
    priorities: "CBT with interoceptive/exposure work and SSRIs/SNRIs are first-line; educate about the benign but uncomfortable physiology and reduce avoidance gradually. Benzodiazepines are limited short-term/selective tools because dependence and avoidance reinforcement can undermine recovery.",
    medicationSafety: "SSRIs can initially activate anxiety, so start low/titrate; benzodiazepines interact dangerously with opioids/alcohol and require taper after dependence. Beta blockers may reduce performance-anxiety symptoms but do not treat panic disorder's core fear/avoidance cycle.",
    redFlags: "First panic-like episode with chest pain/syncope/hypoxia, suicidality, severe substance intoxication/withdrawal or new neurologic findings requires acute medical evaluation.",
    examTraps: "Do not diagnose panic disorder from one emergency-department panic attack and do not repeatedly perform broad medical testing after an appropriate negative evaluation unless symptoms change.",
    sourceKeys: ["APA_PANIC_CURRENT"],
  },
  {
    slug: "generalized-anxiety-disorder",
    title: "Generalized Anxiety Disorder",
    bodySystem: "Psychiatric",
    applicableExams: ["PMHNP", "AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "GAD is excessive difficult-to-control worry across multiple domains for at least six months with restlessness, fatigue, concentration problems, irritability, muscle tension or sleep disturbance. Anxiety limited to panic, trauma, obsessions, social scrutiny or substances may represent another disorder.",
    diagnostics: "Use GAD-7 to quantify rather than diagnose alone, assess depression/suicide risk and review thyroid disease, arrhythmia, stimulant/caffeine use, corticosteroids, withdrawal and other mimics. Ask bipolar history before antidepressant therapy.",
    priorities: "CBT and SSRI/SNRI treatment are first-line for clinically significant GAD; buspirone is another nondependence-forming option, with sleep/exercise and reduction of caffeine/substances as adjuncts. Continue effective therapy long enough after remission to reduce relapse.",
    medicationSafety: "Benzodiazepines are not preferred long-term therapy because dependence, falls and overdose risk increase; SSRI/SNRI discontinuation should be tapered. Hydroxyzine adds sedation/anticholinergic burden and is not ideal chronic treatment in older adults.",
    redFlags: "Suicidality, mania, severe substance withdrawal, inability to function/eat/sleep or new cardiopulmonary/endocrine symptoms inconsistent with baseline anxiety requires urgent reassessment.",
    examTraps: "Do not diagnose GAD solely from a high GAD-7 and do not use chronic benzodiazepines as first-line maintenance because they work quickly.",
    sourceKeys: ["APA_ANXIETY_CURRENT"],
  },
  {
    slug: "prolonged-grief-disorder",
    title: "Prolonged Grief Disorder",
    bodySystem: "Psychiatric",
    applicableExams: ["PMHNP", "AANP-FNP", "ANCC-FNP"],
    recognize: "Prolonged grief disorder is persistent intense yearning/preoccupation and associated identity, disbelief, avoidance, emotional pain or reintegration difficulty lasting beyond the expected diagnostic time threshold and causing impairment. Normal acute grief can be intense and is not a disorder simply because the person is sad.",
    diagnostics: "Assess duration, cultural/religious context, function, depression, PTSD, substance use and suicide risk. Distinguish grief's loss-focused waves and preserved capacity for positive emotion from pervasive depressive anhedonia/self-worth symptoms, while recognizing coexistence.",
    priorities: "Use grief-focused psychotherapy as the core treatment and treat comorbid major depression/anxiety separately when present. Support rituals, social connection and practical loss adaptation rather than medicalizing normal bereavement.",
    medicationSafety: "Antidepressants may treat comorbid depression but do not replace grief-focused therapy for core prolonged-grief symptoms; avoid benzodiazepine sedation as a routine response to acute bereavement.",
    redFlags: "Suicidal intent, psychotic symptoms beyond culturally congruent bereavement experiences, severe self-neglect or substance escalation requires urgent psychiatric care.",
    examTraps: "Do not diagnose prolonged grief before the required duration and do not assume all bereaved patients with sleep/appetite changes have major depression.",
    sourceKeys: ["APA_DSM5TR_PGD_CURRENT"],
  },
  {
    slug: "adult-adhd-evaluation",
    title: "Adult ADHD Evaluation",
    bodySystem: "Psychiatric",
    applicableExams: ["PMHNP", "AANP-FNP", "ANCC-FNP"],
    recognize: "Adult ADHD reflects persistent developmentally inappropriate inattention and/or hyperactivity-impulsivity beginning in childhood and impairing more than one setting. Depression/anxiety, trauma, bipolar disorder, sleep apnea, substance use, autism and high digital distraction can mimic symptoms.",
    diagnostics: "Use a structured developmental history, school/family collateral when available and validated rating scales as support; establish childhood onset and functional impairment rather than diagnosing from a self-report checklist alone. Evaluate sleep, substances, mood and medical contributors.",
    priorities: "Use evidence-based stimulant or nonstimulant medication plus organization/CBT/coaching strategies according to symptoms, cardiovascular/substance risk and patient preference. Define measurable functional targets and reassess whether treatment improves them.",
    medicationSafety: "Before stimulants review BP/HR, cardiac history, psychosis/mania and misuse/diversion; monitor appetite, sleep and BP/HR. Atomoxetine and alpha-2 agonists have different suicidality, sedation/BP and withdrawal considerations.",
    redFlags: "New mania/psychosis, stimulant misuse/diversion, uncontrolled hypertension, severe insomnia or suicidality requires treatment reassessment.",
    examTraps: "A stimulant response does not diagnose ADHD and adult-onset attention complaints without childhood evidence require a broader differential.",
    sourceKeys: ["APA_ADHD_CURRENT", "AAPS_ADULT_ADHD_CURRENT"],
  },
  {
    slug: "psychiatric-emergency-disposition",
    title: "Psychiatric Emergency, Involuntary Evaluation & Disposition",
    bodySystem: "Psychiatric",
    applicableExams: ["PMHNP", "ENP", "AANP-FNP", "ANCC-FNP"],
    recognize: "Emergency psychiatric disposition is driven by imminent self-harm/other-harm, grave disability, severe psychosis/mania, intoxication/withdrawal, medical instability and ability to participate in a safe plan. Involuntary-hold criteria and timelines are state-specific.",
    diagnostics: "Perform suicide/violence and mental-status assessment while excluding delirium, hypoglycemia, intoxication, withdrawal, neurologic disease and other medical causes; use collateral and access-to-means information. 'Medical clearance' should be targeted to history/exam rather than mandatory universal test panels.",
    priorities: "Use the least restrictive safe setting, collaborative safety planning and lethal-means counseling; hospitalize voluntarily when possible and use involuntary evaluation only when current jurisdictional criteria are met. Document risk, protective factors, capacity and why the chosen setting can manage foreseeable risk.",
    medicationSafety: "Acute agitation medication is chosen by suspected cause, QT/respiratory risk and intoxication; physical restraint is a last resort with monitoring. Do not sedate a medically unstable delirious patient simply to facilitate psychiatric transfer.",
    redFlags: "Active suicide plan/intent, command hallucinations, severe mania/psychosis, delirium, violent behavior, catatonia, severe intoxication/withdrawal or inability to meet basic needs requires emergency evaluation.",
    examTraps: "Do not memorize one state's involuntary-hold rule as a national standard and do not use a 'contract for safety' as evidence that a high-risk patient can be discharged.",
    sourceKeys: ["ACEP_PSYCHIATRIC_EMERGENCY_CURRENT", "APA_SUICIDE_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
