import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch38 = [
  {
    slug: "raas-blocker-prescribing",
    title: "ACE Inhibitor, ARB & ARNI Prescribing",
    bodySystem: "Pharmacology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP"],
    recognize: "ACE inhibitors and ARBs reduce angiotensin-II/aldosterone effects and are high-value therapies for selected hypertension, albuminuric CKD and heart-failure phenotypes; sacubitril/valsartan adds neprilysin inhibition for HFrEF. Choose them because an indication exists, not because every hypertensive patient needs RAAS blockade.",
    diagnostics: "Before initiation review BP, creatinine/eGFR, potassium, pregnancy potential, volume status, NSAIDs and renal-artery disease clues. Recheck renal function and potassium after initiation or material dose change, especially in CKD, older adults or concomitant MRA use.",
    priorities: "Use an ACEi or ARB for appropriate albuminuric CKD/hypertension and guideline-directed HF; use ARNI in eligible symptomatic HFrEF when tolerated. A modest early creatinine rise can be hemodynamic and acceptable, but marked deterioration, hyperkalemia or hypotension requires reassessment rather than automatic dose escalation.",
    medicationSafety: "ACE inhibitors can cause cough and angioedema; ACEi/ARB/ARNI can cause hyperkalemia and fetal toxicity. Never combine ACE inhibitor with ARNI without the required washout, and avoid routine ACEi+ARB dual blockade because renal/hyperkalemia harm exceeds benefit.",
    redFlags: "Tongue/laryngeal angioedema, severe hyperkalemia, syncope/hypotension, rapidly worsening AKI or pregnancy exposure requires immediate medication action and appropriate urgent care.",
    examTraps: "Do not stop RAAS blockade for every small creatinine increase, and do not ignore a large rise that may signal volume depletion or bilateral renal-artery disease. ACEi cough does not predict ARB angioedema-free safety with absolute certainty.",
    sourceKeys: ["AHA_BP_2025", "HF_ACC_AHA_CURRENT", "KDIGO_CKD_2024"],
  },
  {
    slug: "beta-blocker-prescribing",
    title: "Beta-Blocker Prescribing",
    bodySystem: "Pharmacology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Beta blockers are not interchangeable: specific agents improve survival in HFrEF, others are used for rate control, ischemic disease, tremor, migraine or selected hypertension. Cardioselectivity is relative and diminishes at higher doses.",
    diagnostics: "Review resting HR, BP, conduction disease, decompensated HF, asthma/COPD severity, diabetes hypoglycemia awareness and interacting AV-nodal drugs before prescribing. ECG is appropriate when bradycardia/conduction disease or antiarrhythmic use is a concern.",
    priorities: "Use evidence-based HFrEF agents only when the patient is hemodynamically stable and titrate gradually; use rate-control beta blockers according to AF/SVT context and treat ischemic indications when benefit exists. Choose the agent to the disease rather than assuming a class effect.",
    medicationSafety: "Beta blockers can cause bradycardia, hypotension, fatigue and sexual dysfunction and can mask adrenergic hypoglycemia symptoms. Avoid abrupt withdrawal after chronic therapy because rebound tachycardia/ischemia can occur; avoid new aggressive titration during shock or severe acute decompensated HF.",
    redFlags: "Symptomatic bradycardia, high-grade AV block, shock, severe bronchospasm or acute decompensated HF with hypoperfusion requires urgent reassessment and treatment.",
    examTraps: "Do not teach beta blockers as universal first-line uncomplicated hypertension therapy and do not assume all beta blockers have HFrEF mortality data. Asthma is not an automatic absolute prohibition to every cardioselective beta blocker when a strong cardiac indication exists, but risk must be assessed.",
    sourceKeys: ["HF_ACC_AHA_CURRENT", "AF_2023", "AHA_BP_2025"],
  },
  {
    slug: "calcium-channel-blocker-prescribing",
    title: "Calcium Channel Blocker Prescribing",
    bodySystem: "Pharmacology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Dihydropyridine CCBs such as amlodipine primarily vasodilate and treat hypertension/angina; nondihydropyridines such as diltiazem/verapamil also slow AV-nodal conduction. Their adverse effects and heart-failure implications differ enough that 'CCB' is not one prescribing decision.",
    diagnostics: "Check BP and edema risk for dihydropyridines and HR/ECG/conduction status for nondihydropyridines. Review HFrEF, constipation, CYP3A interactions and concurrent beta blockers/digoxin before AV-nodal CCB therapy.",
    priorities: "Use long-acting dihydropyridines for hypertension when indicated; use diltiazem/verapamil selectively for rate control or angina when LV systolic function and conduction allow. Manage ankle edema by reassessing dose/class and overall regimen rather than automatically adding a loop diuretic.",
    medicationSafety: "Verapamil/diltiazem can cause bradycardia, AV block and worsen HFrEF; combining them with beta blockers increases conduction risk. Dihydropyridines commonly cause dose-related peripheral edema and headache without representing volume-overload HF by default.",
    redFlags: "Syncope, high-grade AV block, profound hypotension, acute HFrEF deterioration or severe drug-interaction toxicity requires urgent evaluation.",
    examTraps: "Do not treat amlodipine edema as proof of HF and do not use verapamil/diltiazem indiscriminately in HFrEF. Immediate-release nifedipine is not appropriate for rapid unmonitored BP reduction.",
    sourceKeys: ["AHA_BP_2025", "AF_2023", "HF_ACC_AHA_CURRENT"],
  },
  {
    slug: "oral-anticoagulant-prescribing",
    title: "Oral Anticoagulant Prescribing: DOACs & Warfarin",
    bodySystem: "Pharmacology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Anticoagulation is indication-specific: AF stroke prevention, acute VTE treatment, extended VTE prevention and mechanical valves use different agents, doses and durations. DOACs are preferred in many nonvalvular AF/VTE settings but are not substitutes for warfarin in mechanical heart valves.",
    diagnostics: "Before prescribing document indication, weight, CBC, creatinine/eGFR or CrCl as appropriate, liver function, pregnancy, bleeding history, interacting drugs and valve/antiphospholipid context. Reassess renal function periodically because DOAC exposure changes with kidney function.",
    priorities: "Use the evidence-based dose for the exact indication and patient characteristics; do not reduce DOAC doses simply because a patient is old or bruises. Determine anticoagulation duration from thromboembolic risk, provoking factors and bleeding risk and create peri-procedural interruption plans based on procedure and drug clearance.",
    medicationSafety: "Apixaban/rivaroxaban and other DOACs have P-gp/CYP interaction issues and different renal dependence. Warfarin requires INR monitoring and has many food/drug interactions; pregnancy generally favors heparin-based strategies rather than warfarin/DOAC exposure outside specialized indications.",
    redFlags: "Intracranial/GI major bleeding, hemodynamic instability, acute neurologic deficit, suspected spinal/retroperitoneal bleed or severe overdose requires emergency reversal/supportive management using agent-specific protocols.",
    examTraps: "Do not use a single 'renal cutoff' for all DOACs or indications and do not bridge every warfarin interruption. Aspirin is not an adequate substitute for anticoagulation in AF when anticoagulation is indicated.",
    sourceKeys: ["AF_2023", "CHEST_VTE_CURRENT", "ACC_ANTICOAGULATION_CURRENT"],
  },
  {
    slug: "antiplatelet-prescribing",
    title: "Antiplatelet Prescribing",
    bodySystem: "Pharmacology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Aspirin and P2Y12 inhibitors prevent platelet-rich arterial thrombosis and are central after ACS/PCI and in selected atherosclerotic disease, but they are not interchangeable with anticoagulants and are not harmless primary-prevention vitamins.",
    diagnostics: "Clarify the vascular indication, stent/ACS date, prior stroke/TIA, bleeding history, anemia/platelets, GI risk and concurrent anticoagulation/NSAID use. Before surgery or invasive procedures, determine thrombotic risk from recent PCI/ACS before stopping therapy.",
    priorities: "Use dual antiplatelet therapy for the guideline-directed period after ACS/PCI, then simplify according to ischemic and bleeding risk; use antiplatelet monotherapy for appropriate secondary prevention and reserve primary-prevention aspirin for carefully selected adults after shared risk discussion.",
    medicationSafety: "Aspirin/clopidogrel increase bleeding and GI injury; ticagrelor can cause dyspnea/bradyarrhythmia and has CYP interactions. Combining anticoagulation with dual antiplatelet therapy sharply raises bleeding risk and should be limited to evidence-based indications/durations.",
    redFlags: "Major GI bleeding, intracranial hemorrhage, severe thrombocytopenia, acute stent thrombosis or ischemic symptoms after premature discontinuation requires urgent specialist/emergency care.",
    examTraps: "Do not stop DAPT casually for elective procedures soon after PCI and do not add aspirin to every anticoagulated AF patient without a separate indication. Primary-prevention aspirin benefit is modest and bleeding-sensitive.",
    sourceKeys: ["ACS_2025", "ACC_CCD_2023", "USPSTF_ASPIRIN_CURRENT"],
  },
  {
    slug: "lipid-lowering-prescribing",
    title: "Statin & Nonstatin Lipid-Lowering Prescribing",
    bodySystem: "Pharmacology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "Lipid therapy follows ASCVD risk and LDL burden rather than one universal target. High-intensity statins are foundational in established ASCVD and severe hypercholesterolemia; ezetimibe, PCSK9-directed drugs, bempedoic acid and other agents are added according to residual risk, LDL response and tolerance.",
    diagnostics: "Obtain baseline lipid profile and evaluate secondary causes/interaction risk; measure liver enzymes when clinically indicated and CK only for muscle symptoms or high-risk contexts rather than routine surveillance. Recheck lipids after initiation/titration to assess expected percentage response and adherence.",
    priorities: "Use the maximally tolerated evidence-based statin first when indicated, then add nonstatin therapy if the patient remains above a guideline threshold or has true intolerance. Address familial hypercholesterolemia and elevated Lp(a) risk when clinically relevant rather than repeatedly cycling weak statin doses.",
    medicationSafety: "Statins can cause myalgia and rare myopathy/rhabdomyolysis; interactions vary by agent. Pregnancy planning matters because routine statin use is generally stopped during pregnancy, while severe familial disease requires specialist individualized assessment; bempedoic acid can raise uric acid and tendon risk.",
    redFlags: "Severe muscle pain/weakness with dark urine, marked CK elevation, acute liver injury or serious drug interaction requires urgent medication reassessment.",
    examTraps: "Do not label every ache statin intolerance and permanently abandon therapy without dechallenge/rechallenge or alternate dosing/agent when safe. Normal liver enzymes do not make statins unnecessary in high-risk ASCVD.",
    sourceKeys: ["ACC_PREVENTION_CURRENT", "ACC_NONSTATIN_CURRENT"],
  },
  {
    slug: "heart-failure-four-pillar-prescribing",
    title: "HFrEF Four-Pillar Pharmacotherapy",
    bodySystem: "Pharmacology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP"],
    recognize: "Modern HFrEF therapy is built around complementary disease-modifying classes—ARNI/ACEi/ARB, an evidence-based beta blocker, MRA and SGLT2 inhibitor—rather than slow sequential monotherapy focused only on symptoms. Diuretics control congestion but are not one of the four mortality/morbidity pillars.",
    diagnostics: "Confirm EF/phenotype and review BP, HR, renal function, potassium, volume status and comorbidity before initiation. Monitor after each material change, but use low starting doses and rapid thoughtful sequencing when stable rather than waiting months between every class.",
    priorities: "Initiate the four foundational therapies early in stable eligible patients and titrate toward evidence-based doses as tolerated, while using loop diuretics for euvolemia and addressing iron deficiency, AF, ischemia and devices when indicated.",
    medicationSafety: "MRA/RAAS therapy can cause hyperkalemia/renal change; SGLT2 inhibitors cause genital infection/volume and ketoacidosis risks; beta blockers worsen shock if initiated/up-titrated during hypoperfusion. ARNI requires ACEi washout and pregnancy avoidance.",
    redFlags: "Cardiogenic shock, severe hypotension, refractory hyperkalemia, worsening renal failure with congestion, acute pulmonary edema or syncope/bradyarrhythmia requires urgent HF reassessment rather than routine outpatient titration.",
    examTraps: "Do not maximize one class before introducing all other pillars if the patient can tolerate multidrug initiation, and do not mistake symptom relief from diuresis for complete guideline-directed disease modification.",
    sourceKeys: ["HF_ACC_AHA_CURRENT"],
  },
  {
    slug: "antiarrhythmic-prescribing",
    title: "Antiarrhythmic Drug Prescribing",
    bodySystem: "Pharmacology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Antiarrhythmic drugs have narrow indication and toxicity margins: rhythm-control selection depends on arrhythmia type, structural heart disease, EF, CAD, renal/hepatic function and QT/conduction status. Treating the ECG without defining the rhythm and substrate is unsafe.",
    diagnostics: "Obtain/interpret ECG including QRS/QT, electrolytes, kidney/liver function and structural-heart assessment before class I/III therapy; review interactions and other QT-prolonging drugs. Some agents require monitored inpatient initiation or serial ECG/drug-level surveillance.",
    priorities: "Use guideline-directed rhythm-control agents only in patients whose substrate permits them, combine AF rhythm strategy with anticoagulation assessment and refer complex ventricular arrhythmia or ablation candidates to electrophysiology.",
    medicationSafety: "Flecainide/propafenone are avoided in significant structural/ischemic heart disease; sotalol and dofetilide prolong QT and require renal dosing/monitoring; amiodarone has thyroid, pulmonary, hepatic, ocular, neurologic and interaction toxicity despite lower torsades risk.",
    redFlags: "Syncope with QT prolongation, torsades, wide-complex tachycardia, high-grade block, severe bradycardia or amiodarone pulmonary/hepatic toxicity requires urgent evaluation.",
    examTraps: "Do not choose flecainide for AF solely because the patient is young without first excluding structural/CAD disease, and do not use amiodarone casually for benign ectopy because it is 'effective.'",
    sourceKeys: ["AF_2023", "AHA_VA_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
