import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch2 = [
  {
    slug: "community-acquired-pneumonia",
    title: "Community-Acquired Pneumonia",
    bodySystem: "Respiratory",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PNP", "ENP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP"],
    recognize: "Fever, cough, sputum, pleuritic pain, dyspnea, tachypnea, or focal lung findings suggest pneumonia, but older adults may present with weakness or confusion.",
    diagnostics: "Confirm infiltrate with chest imaging when the diagnosis or severity requires it. Assess oxygenation and severity; targeted microbiologic testing is reserved for selected severe, resistant-risk, or epidemiologic situations.",
    priorities: "Choose outpatient vs inpatient care from physiologic stability, comorbidity, oral tolerance, support, and validated severity tools. Select empiric antibiotics according to age, comorbidity, local resistance, allergies, and recent antibiotic exposure.",
    medicationSafety: "Review QT risk, renal dosing, interactions, pregnancy status, and C. difficile risk. Do not extend antibiotics automatically when the patient is clinically stable and has met an evidence-based minimum course.",
    redFlags: "Hypoxemia, hypotension, altered mentation, respiratory failure, sepsis, rapidly progressive infiltrates, or inability to maintain hydration warrants escalation.",
    examTraps: "Purulent sputum does not prove bacterial pneumonia. A normal early chest radiograph does not always exclude pneumonia in a dehydrated or very early presentation.",
    sourceKeys: ["IDSA_CAP_CURRENT"],
  },
  {
    slug: "obstructive-sleep-apnea",
    title: "Obstructive Sleep Apnea",
    bodySystem: "Respiratory",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PNP"],
    recognize: "Loud snoring, witnessed apneas, nocturnal gasping, morning headaches, resistant hypertension, and daytime sleepiness suggest OSA; children may show hyperactivity or school/behavior problems instead of sleepiness.",
    diagnostics: "Use a validated screening tool to estimate risk, but diagnosis requires appropriate sleep testing. Examine airway/tonsils, obesity, craniofacial factors, BP, and cardiometabolic comorbidity.",
    priorities: "Treat contributing weight and airway factors, use PAP for appropriate adults, and refer for ENT/sleep evaluation when anatomy or pediatric disease warrants it.",
    medicationSafety: "Sedatives, alcohol, and opioids can worsen airway obstruction and hypoventilation. Warn about driving or safety-sensitive work when sleepiness is uncontrolled.",
    redFlags: "Severe hypoxemia, suspected obesity hypoventilation, pulmonary hypertension, dangerous daytime somnolence, or perioperative risk needs expedited evaluation.",
    examTraps: "A high STOP-BANG score is not the diagnosis. CPAP adherence and mask fit are part of treatment efficacy, not afterthoughts.",
    sourceKeys: ["AASM_CURRENT"],
  },
  {
    slug: "tuberculosis",
    title: "Tuberculosis",
    bodySystem: "Respiratory",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PNP", "ENP"],
    recognize: "Think TB with chronic cough, fevers, night sweats, weight loss, hemoptysis, exposure, birth/travel in high-prevalence settings, homelessness, incarceration, or immunosuppression.",
    diagnostics: "Separate latent infection from active disease. Suspected pulmonary TB needs chest imaging plus microbiologic testing of respiratory specimens; use airborne precautions and involve public health early.",
    priorities: "Active TB requires multidrug therapy coordinated with public health and susceptibility data. Latent TB treatment depends on regimen suitability, drug interactions, pregnancy status, and liver risk.",
    medicationSafety: "Rifamycins have major drug interactions and can reduce hormonal contraceptive effectiveness. Isoniazid carries hepatotoxicity and neuropathy risk; monitor according to patient risk and regimen.",
    redFlags: "Respiratory compromise, massive hemoptysis, CNS TB, or disseminated disease in an unstable patient requires urgent escalation.",
    examTraps: "A positive IGRA/TST does not distinguish latent from active TB. BCG vaccination does not cause a false-positive IGRA.",
    sourceKeys: ["CDC_TB_CURRENT"],
  },
  {
    slug: "pulmonary-nodule-lung-cancer",
    title: "Pulmonary Nodule & Lung Cancer",
    bodySystem: "Respiratory",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP"],
    recognize: "Persistent cough, hemoptysis, unexplained weight loss, recurrent focal pneumonia, hoarseness, or a suspicious incidental nodule warrants risk-based evaluation, especially with tobacco exposure.",
    diagnostics: "Characterize nodule size, morphology, growth, prior imaging, and patient cancer risk. Use current lung-cancer screening criteria separately from incidental-nodule follow-up algorithms.",
    priorities: "Arrange surveillance imaging, PET/CT, pulmonology, or tissue diagnosis according to malignancy probability. Support smoking cessation at every stage.",
    medicationSafety: "Do not delay evaluation by repeatedly treating unexplained hemoptysis with antibiotics. Medication review matters before biopsy or surgery, especially anticoagulants/antiplatelets.",
    redFlags: "Massive hemoptysis, SVC syndrome, spinal cord compression, airway compromise, or severe hypercalcemia is urgent/emergent.",
    examTraps: "Screening eligibility is not the same as nodule management. A never-smoker can still develop lung cancer.",
    sourceKeys: ["USPSTF_LUNG_CURRENT"],
  },
  {
    slug: "type-2-diabetes",
    title: "Type 2 Diabetes",
    bodySystem: "Endocrine",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "WHNP"],
    recognize: "Polyuria, polydipsia, weight loss, recurrent infections, neuropathic symptoms, or incidental hyperglycemia may reveal diabetes, but many patients are asymptomatic.",
    diagnostics: "Confirm diagnosis with accepted glucose/A1C criteria unless unequivocal symptomatic hyperglycemia is present. At diagnosis assess kidney disease, albuminuria, BP, lipids, eye/foot risk, cardiovascular disease, medications, and social barriers.",
    priorities: "Choose therapy based on glycemic needs plus ASCVD, heart failure, CKD, weight goals, hypoglycemia risk, cost, and preference—not A1C alone. Lifestyle, education, and complication prevention remain core.",
    medicationSafety: "Metformin requires renal-function awareness; SGLT2 inhibitors can cause genital infections and euglycemic ketoacidosis; GLP-1–based drugs have GI effects and specific contraindication/precaution profiles; insulin can cause hypoglycemia.",
    redFlags: "DKA/HHS features, severe dehydration, altered mental status, persistent vomiting, or marked catabolic symptoms require urgent/emergency management.",
    examTraps: "Do not reflexively stop metformin for every contrast study. Do not choose a glucose-lowering drug without considering cardiac and kidney benefit.",
    sourceKeys: ["ADA_2026"],
  },
  {
    slug: "dka-hhs",
    title: "DKA & Hyperglycemic Crisis",
    bodySystem: "Endocrine",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGACNP", "PNP", "ENP"],
    recognize: "DKA often presents with polyuria, dehydration, abdominal pain, vomiting, tachypnea/Kussmaul breathing, and altered mentation; HHS usually has more profound hyperosmolar dehydration and less ketosis.",
    diagnostics: "Check glucose, electrolytes, bicarbonate/venous pH, beta-hydroxybutyrate or ketones, renal function, and osmolality as appropriate. Calculate corrected sodium and monitor potassium closely; search for infection, missed insulin, ischemia, drugs, or other precipitant.",
    priorities: "Priorities are isotonic fluid, potassium-aware insulin therapy, electrolyte replacement, and treatment of the trigger. Transition off IV insulin only after crisis resolution and overlap with subcutaneous insulin.",
    medicationSafety: "Never start insulin in severe hypokalemia until potassium is being corrected. SGLT2 inhibitors can produce euglycemic DKA, so a near-normal glucose does not exclude ketoacidosis.",
    redFlags: "Shock, severe acidosis, cerebral edema concern, coma, dangerous potassium abnormality, or inability to monitor closely requires critical-care management.",
    examTraps: "Do not use urine ketones alone to judge resolution. Bicarbonate is not routine therapy for most DKA.",
    sourceKeys: ["ADA_2026"],
  },
  {
    slug: "thyroid-dysfunction",
    title: "Hypothyroidism & Hyperthyroidism",
    bodySystem: "Endocrine",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PNP", "WHNP", "ENP"],
    recognize: "Fatigue, weight change, temperature intolerance, bowel changes, tremor, palpitations, menstrual change, neck symptoms, or unexplained AF may be thyroid disease—but symptoms are nonspecific.",
    diagnostics: "TSH is the usual first test for primary thyroid dysfunction, paired with free T4 when abnormal or when pituitary disease is possible. Antibody testing, ultrasound, or uptake studies answer specific etiologic questions rather than serving as universal screening.",
    priorities: "Treat overt hypothyroidism with levothyroxine; manage hyperthyroidism according to cause, severity, pregnancy status, and definitive-treatment options. Recheck labs after meaningful dose changes at an appropriate interval.",
    medicationSafety: "Separate levothyroxine from interfering supplements/medications such as iron or calcium. Antithyroid drugs can cause agranulocytosis and hepatotoxicity; fever or sore throat on therapy needs prompt CBC evaluation.",
    redFlags: "Thyroid storm, myxedema coma, severe compressive symptoms, or thyrotoxic arrhythmia/hemodynamic instability is an emergency.",
    examTraps: "Do not order thyroid ultrasound for isolated abnormal thyroid labs without a structural indication. Biotin can interfere with some thyroid assays.",
    sourceKeys: ["ATA_CURRENT"],
  },
  {
    slug: "adrenal-disorders",
    title: "Adrenal Insufficiency & Cortisol Excess",
    bodySystem: "Endocrine",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Adrenal insufficiency can cause fatigue, weight loss, hypotension, GI symptoms, hyponatremia and hyperkalemia; exogenous steroid withdrawal is a common secondary cause. Cortisol excess suggests central obesity, bruising, proximal weakness, diabetes, hypertension, and osteoporosis.",
    diagnostics: "Use morning cortisol/ACTH and dynamic testing when indicated; do not diagnose Cushing syndrome from one random cortisol. Review all glucocorticoid exposures, including injections, inhaled/high-potency topical therapy, and supplements.",
    priorities: "Suspected adrenal crisis: give stress-dose glucocorticoid promptly with IV fluids and treat precipitant—do not wait for confirmatory testing when unstable. Chronic disease needs sick-day rules and medical alert planning.",
    medicationSafety: "Long-term glucocorticoids require taper planning when the HPA axis may be suppressed. Fludrocortisone is used for mineralocorticoid replacement in primary adrenal insufficiency, not most secondary disease.",
    redFlags: "Refractory hypotension, severe vomiting/dehydration, hypoglycemia, hyperkalemia, or altered mentation suggests adrenal crisis.",
    examTraps: "Hyperpigmentation points toward primary, not secondary, adrenal insufficiency. Chronic steroid use can suppress the axis even when the patient does not look cushingoid.",
    sourceKeys: ["ENDOCRINE_SOCIETY_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
