import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch39 = [
  {
    slug: "insulin-prescribing",
    title: "Insulin Prescribing & Titration",
    bodySystem: "Pharmacology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PNP", "WHNP"],
    recognize: "Insulin therapy replaces basal hepatic insulin needs and meal/correction requirements; type 1 diabetes always requires basal insulin even when not eating. In type 2 diabetes, insulin is appropriate for symptomatic marked hyperglycemia, catabolism, pregnancy-related needs or failure/contraindication of other therapy.",
    diagnostics: "Review glucose pattern/CGM rather than reacting to isolated values. Before titration assess meals, missed doses, injection technique/sites, renal function, steroids, illness and hypoglycemia; A1C does not reveal nocturnal or postprandial patterns by itself.",
    priorities: "Match basal adjustments to fasting trends and prandial/correction adjustments to meal-related patterns, using individualized targets. Teach carb counting or consistent carbohydrate strategy, hypoglycemia treatment, sick-day ketone rules and device backup plans for pump users.",
    medicationSafety: "Insulin is a high-alert medication; concentration, device and units must be explicit. Renal decline reduces insulin requirements, stacking rapid-acting correction doses causes delayed hypoglycemia, and basal insulin should not be stopped in type 1 diabetes during illness.",
    redFlags: "Severe hypoglycemia, recurrent nocturnal lows, DKA/ketosis, pump failure with hyperglycemia or inability to self-manage insulin safely requires urgent intervention.",
    examTraps: "Do not increase basal insulin to fix post-meal hyperglycemia and create overnight lows. Sliding-scale-only insulin without basal coverage is not appropriate chronic therapy for insulin-dependent diabetes.",
    sourceKeys: ["ADA_2026_PHARM", "ADA_2026_TECHNOLOGY"],
  },
  {
    slug: "incretin-prescribing",
    title: "GLP-1 & Dual Incretin Prescribing",
    bodySystem: "Pharmacology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "WHNP"],
    recognize: "GLP-1 receptor agonists and dual GIP/GLP-1 agonists improve glucose and weight and selected agents reduce cardiovascular/renal risk. Choose therapy by obesity, diabetes, ASCVD/CKD risk and patient goals rather than treating them as interchangeable cosmetic weight-loss drugs.",
    diagnostics: "Review diabetes status/A1C, kidney function, pregnancy plans, prior pancreatitis/gallbladder disease, severe GI motility symptoms and interacting glucose-lowering therapies. Monitor weight, glucose and tolerability; routine amylase/lipase surveillance in asymptomatic patients is not required.",
    priorities: "Start low and titrate according to the specific product schedule and tolerance; pair therapy with nutrition/protein, resistance activity and chronic weight-management planning. Reduce insulin/sulfonylurea doses when needed to prevent hypoglycemia as glucose improves.",
    medicationSafety: "Common adverse effects are nausea, vomiting, diarrhea/constipation; risks include gallbladder disease and rare pancreatitis. Avoid during pregnancy and respect product-specific boxed thyroid C-cell tumor contraindications; significant vomiting can cause dehydration/AKI.",
    redFlags: "Persistent severe abdominal pain, repeated vomiting/dehydration, suspected pancreatitis, acute gallbladder disease or severe hypoglycemia from combination therapy requires prompt evaluation.",
    examTraps: "Do not promise permanent weight loss after discontinuation—weight regain is common. Do not use multiple GLP-1/incretin products together or titrate faster than the product schedule to chase weight loss.",
    sourceKeys: ["ADA_2026_PHARM", "ADA_2026_OBESITY"],
  },
  {
    slug: "thyroid-medication-prescribing",
    title: "Levothyroxine & Antithyroid Drug Prescribing",
    bodySystem: "Pharmacology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "WHNP"],
    recognize: "Levothyroxine replaces deficient T4; methimazole/PTU block thyroid-hormone synthesis for Graves/hyperthyroidism. Medication choice and dose depend on biochemical disease, age, cardiac status, pregnancy and whether the problem is primary thyroid disease or central pituitary disease.",
    diagnostics: "Use TSH and free T4 appropriately; TSH guides most primary hypothyroid titration but not central hypothyroidism. Before antithyroid therapy obtain baseline CBC/liver context and establish pregnancy status when relevant; monitor free T4/T3 early because TSH can remain suppressed for months.",
    priorities: "Dose levothyroxine to age/cardiac status and recheck after steady state, counseling on consistent administration away from calcium/iron. Methimazole is preferred for most Graves disease, while PTU is used in selected first-trimester pregnancy and thyroid storm contexts.",
    medicationSafety: "Antithyroid drugs can cause agranulocytosis and severe liver injury; fever or sore throat requires immediate medication hold and CBC evaluation. Excess levothyroxine increases AF and bone risk; biotin can distort thyroid immunoassays.",
    redFlags: "Thyroid storm, myxedema coma, antithyroid-drug agranulocytosis/hepatitis or severe angina/arrhythmia during replacement requires urgent care.",
    examTraps: "Do not use TSH to titrate central hypothyroidism and do not prescribe desiccated thyroid as routine first-line replacement. A low TSH shortly after starting Graves therapy does not necessarily mean the antithyroid dose is inadequate.",
    sourceKeys: ["ATA_HYPOTHYROID_CURRENT", "ATA_HYPERTHYROID_CURRENT"],
  },
  {
    slug: "systemic-corticosteroid-prescribing",
    title: "Systemic Corticosteroid Prescribing & Tapering",
    bodySystem: "Pharmacology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PNP", "WHNP", "ENP"],
    recognize: "Systemic glucocorticoids are powerful anti-inflammatory/immunosuppressive drugs with indication- and duration-dependent benefit. Risk rises with cumulative exposure: hyperglycemia, infection, mood/psychosis, GI effects, osteoporosis, cataract/glaucoma, myopathy and HPA-axis suppression.",
    diagnostics: "Before prolonged therapy review diabetes/BP, infection/TB risk, bone health, vaccination, eye disease and psychiatric history; monitor glucose, BP, weight and bone-protection needs. HPA-axis testing is reserved for selected patients at risk during taper, not every short steroid course.",
    priorities: "Use the lowest effective dose for the shortest necessary duration and steroid-sparing therapy for chronic inflammatory disease. Taper when duration/dose creates adrenal-suppression risk and when the underlying disease allows; stress-dose planning is required for proven/suspected adrenal suppression during major illness/procedures.",
    medicationSafety: "Abrupt discontinuation after substantial chronic exposure can precipitate adrenal insufficiency. Short courses usually do not need elaborate tapers; repeated bursts still accumulate harms. Live vaccines may be contraindicated during sufficiently immunosuppressive dosing.",
    redFlags: "Adrenal crisis, severe infection, steroid psychosis with danger, GI bleeding, severe hyperglycemia/DKA or acute visual symptoms requires urgent reassessment.",
    examTraps: "Do not teach one taper schedule for every patient. A patient can have normal appearance and still have HPA suppression after prolonged exogenous steroids.",
    sourceKeys: ["ENDOCRINE_GLUCORTICOID_INDUCED_AI_CURRENT", "CDC_IMMUNIZATION_CURRENT"],
  },
  {
    slug: "inhaled-pulmonary-medication-prescribing",
    title: "Asthma & COPD Inhaler Prescribing",
    bodySystem: "Pharmacology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PNP", "ENP"],
    recognize: "Inhaler prescribing depends on diagnosis and phenotype: asthma requires ICS-containing treatment, whereas COPD treatment centers on long-acting bronchodilation with ICS added selectively for exacerbation/eosinophil phenotype. Device technique and adherence can matter as much as the molecule.",
    diagnostics: "Confirm asthma/COPD objectively where feasible, then assess symptoms, exacerbations, eosinophils when relevant, inspiratory flow/device ability, cognition/dexterity, cost and technique. Reassess before stepping up because an empty or misused inhaler is treatment failure, not severe disease.",
    priorities: "Use GINA 2026 ICS-containing tracks for asthma and GOLD 2026 LABA/LAMA-centered therapy for symptomatic COPD, escalating to triple therapy when phenotype supports it. Demonstrate technique and prescribe spacer/nebulizer only when the device and patient need justify it.",
    medicationSafety: "SABA overuse signals risk; LABA must not be used without ICS in asthma. LAMA can worsen urinary retention/narrow-angle glaucoma symptoms; ICS can cause thrush/dysphonia and in COPD increases pneumonia risk in susceptible patients.",
    redFlags: "Silent chest, severe hypoxemia/hypercapnia, inability to use inhaled therapy because of exhaustion, paradoxical bronchospasm or recurrent severe exacerbations despite verified treatment requires urgent/specialty care.",
    examTraps: "Do not apply an asthma ICS rule to COPD automatically or a COPD bronchodilator-only rule to asthma. Nebulizers are not inherently 'stronger' than correctly delivered inhalers.",
    sourceKeys: ["GINA_2026", "GOLD_2026"],
  },
  {
    slug: "antibacterial-prescribing-stewardship",
    title: "Antibacterial Prescribing & Stewardship",
    bodySystem: "Pharmacology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PNP", "WHNP", "ENP"],
    recognize: "Good antibiotic prescribing starts by deciding whether bacterial infection is likely, where the infection is, and whether source control is required. Drug spectrum, tissue penetration, host immune status, prior cultures, allergies, pregnancy, renal function and local resistance all matter.",
    diagnostics: "Obtain cultures before antibiotics when yield will change care and delay is safe, but never delay sepsis treatment for perfect specimens. Verify allergy history, renal/hepatic function and prior resistant organisms; use procalcitonin or other biomarkers only in validated contexts rather than as a universal 'antibiotics yes/no' test.",
    priorities: "Choose the narrowest effective empiric regimen for the severity/site, then de-escalate to culture-directed therapy and shortest evidence-based duration after source control. Use delayed prescribing or no antibiotics for self-limited viral syndromes when appropriate and communicate expected course/return precautions.",
    medicationSafety: "Beta-lactams can cause allergy, cytopenia or neurotoxicity at high exposure; fluoroquinolones have tendon, neuropathy, CNS, QT and aortic warnings; TMP-SMX causes hyperkalemia/renal and severe skin risks; clindamycin and broad-spectrum exposure increase C. difficile risk.",
    redFlags: "Septic shock, meningitis, neutropenic fever, necrotizing infection, endocarditis or rapidly progressive organ infection requires immediate broad empiric therapy and inpatient/specialty care.",
    examTraps: "Do not treat asymptomatic bacteriuria except in defined groups and do not equate green sputum with bacterial infection. 'Broadest antibiotic' is not synonymous with best treatment.",
    sourceKeys: ["CDC_ANTIBIOTIC_STEWARDSHIP_CURRENT", "IDSA_AMR_2024"],
  },
  {
    slug: "systemic-antifungal-prescribing",
    title: "Systemic Antifungal Prescribing",
    bodySystem: "Pharmacology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Antifungal selection depends on organism/site and host: azoles inhibit ergosterol synthesis, echinocandins inhibit beta-glucan cell-wall synthesis and amphotericin binds ergosterol. Candida bloodstream disease, endemic dimorphic fungi, aspergillosis and cryptococcosis require different first-line strategies.",
    diagnostics: "Use cultures, histopathology, antigen/serology and susceptibility testing appropriate to the fungus/site, plus renal/hepatic baseline and medication-interaction review. In candidemia obtain source-control evaluation and follow blood cultures; CNS/eye involvement changes drug penetration requirements.",
    priorities: "Use guideline-directed therapy—often echinocandin for initial candidemia, triazole for selected endemic mycoses/aspergillosis and amphotericin-based induction for severe or CNS disease—then step down only when organism, susceptibility, site and stability support it.",
    medicationSafety: "Azoles have major CYP/QT and hepatic interactions; amphotericin causes renal/electrolyte toxicity; echinocandins are generally well tolerated but IV-only and may interact with selected drugs. Pregnancy substantially changes systemic antifungal choice.",
    redFlags: "Fungal meningitis, candidemia with shock, invasive aspergillosis in neutropenia/transplant, disseminated endemic mycosis or severe amphotericin toxicity requires infectious-disease/inpatient management.",
    examTraps: "Do not use fluconazole for every Candida species/site and do not assume a positive fungal antigen identifies a single organism when cross-reactivity exists. Topical therapy is not adequate for systemic invasive disease.",
    sourceKeys: ["IDSA_CANDIDA_CURRENT", "IDSA_ASPERGILLUS_CURRENT", "CDC_FUNGAL_CURRENT"],
  },
  {
    slug: "antiviral-prescribing",
    title: "Antiviral Prescribing",
    bodySystem: "Pharmacology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PNP", "WHNP", "ENP"],
    recognize: "Antiviral efficacy is often timing- and virus-specific: influenza antivirals benefit high-risk/severe patients even after 48 hours, COVID outpatient therapy is time-limited and interaction-sensitive, HSV/VZV therapy is most effective early, and chronic HIV/HBV/HCV require sustained or curative specialist regimens rather than episodic treatment.",
    diagnostics: "Confirm the relevant virus with the appropriate test when results change treatment and assess kidney/liver function, pregnancy and interactions. Do not wait for influenza testing in a severely ill high-risk patient when empiric therapy is indicated during circulation.",
    priorities: "Use oseltamivir or other current influenza agents by risk/context, nirmatrelvir/ritonavir or alternative COVID therapy for eligible high-risk patients within the treatment window, acyclovir-family drugs for HSV/VZV and guideline ART/DAA strategies for HIV/HCV/HBV.",
    medicationSafety: "Ritonavir has major CYP3A interactions that can be dangerous; acyclovir/valacyclovir require renal dosing and hydration awareness; oseltamivir is renal-adjusted. HBV-active antivirals should not be stopped abruptly in chronic HBV because severe flares can occur.",
    redFlags: "HSV encephalitis, severe influenza/COVID respiratory failure, disseminated zoster in immunocompromise, acute HIV syndrome with complications or antiviral drug-interaction toxicity requires urgent care.",
    examTraps: "Do not use antibiotics for uncomplicated viral respiratory infection and do not miss treatment windows by waiting for unnecessary confirmatory testing. Antiviral class names do not imply activity against unrelated viruses.",
    sourceKeys: ["CDC_FLU_2026", "NIH_COVID_CURRENT", "DHHS_HIV_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
