import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch25 = [
  {
    slug: "falls-frailty-older-adults",
    title: "Falls & Frailty in Older Adults",
    bodySystem: "Gerontology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PMHNP"],
    recognize: "A fall is often a syndrome rather than an accident: gait or balance impairment, orthostasis, vision, neuropathy, cognition, sedating medications, environmental hazards and frailty frequently interact. Recurrent falls can be the first sign of acute illness.",
    diagnostics: "Ask circumstances and prodrome, review orthostatic BP, gait/strength, feet/footwear, vision, cognition, medications, alcohol and home hazards. ECG, labs or imaging are targeted to syncope, injury or specific medical clues rather than ordered universally.",
    priorities: "Use multifactorial intervention: strength/balance exercise, medication reduction, vision/foot care, assistive-device optimization, home safety and osteoporosis/fracture prevention. Frailty assessment should inform goals and procedural risk without denying care based on age alone.",
    medicationSafety: "Benzodiazepines, sedative hypnotics, anticholinergics, opioids and intensive BP regimens can increase fall risk. Deprescribe thoughtfully; abrupt withdrawal of benzodiazepines or other dependence-forming drugs can be dangerous.",
    redFlags: "Head trauma on anticoagulation, new neurologic deficit, hip pain/inability to bear weight, syncope with cardiac features, severe orthostasis or repeated unexplained falls requires urgent evaluation.",
    examTraps: "Do not treat falls with a cane alone while ignoring medications and orthostasis. Frailty is not synonymous with chronological age or disability.",
    sourceKeys: ["AGS_FALLS_CURRENT", "AGS_FRAILTY_CURRENT"],
  },
  {
    slug: "polypharmacy-deprescribing",
    title: "Polypharmacy & Deprescribing",
    bodySystem: "Gerontology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PMHNP"],
    recognize: "Multiple medications increase risk for falls, delirium, bleeding, hypotension, hypoglycemia, kidney injury and nonadherence, but the key problem is inappropriate medication burden rather than a specific pill count.",
    diagnostics: "Perform complete medication reconciliation including OTC products, supplements and duplicate prescribers. For each drug confirm indication, expected time-to-benefit, renal/hepatic dose, interaction, adverse effects, adherence and alignment with current goals.",
    priorities: "Stop medications without an indication, reduce high-risk drugs where harms exceed benefits, simplify regimens and taper drugs with withdrawal risk. Prioritize the medications most likely to cause immediate harm while preserving high-value preventive or symptom therapy.",
    medicationSafety: "Use current Beers and disease-specific criteria as decision supports, not automatic stop lists. Benzodiazepines, beta blockers, clonidine, PPIs, antidepressants, antipsychotics and corticosteroids may require tapering rather than abrupt discontinuation.",
    redFlags: "Recurrent syncope/falls, severe hypoglycemia, bleeding, delirium, bradycardia, serotonin toxicity, withdrawal or acute kidney injury from medication burden requires prompt intervention.",
    examTraps: "A Beers-listed medication is not absolutely contraindicated in every older adult. Deprescribing should account for indication, alternatives, withdrawal and patient goals rather than simply lowering the medication count.",
    sourceKeys: ["AGS_BEERS_2023_CURRENT", "DEPRESCRIBING_ORG_CURRENT"],
  },
  {
    slug: "pressure-injury",
    title: "Pressure Injury Prevention & Management",
    bodySystem: "Gerontology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "Immobility, moisture, poor perfusion, malnutrition, sensory loss and medical devices increase pressure-injury risk. Staging is based on tissue depth and visibility; deep-tissue injury and unstageable wounds are not equivalent to stage 1 or 2 disease.",
    diagnostics: "Document location, dimensions, tissue, drainage, odor, surrounding skin, undermining/tunneling, pain and pressure source. Assess perfusion, nutrition and infection; wound cultures are reserved for clinically infected wounds rather than colonization.",
    priorities: "Offload pressure, reposition using an individualized schedule, control moisture, optimize nutrition/perfusion, choose appropriate support surfaces and wound dressings, and debride devitalized tissue when indicated.",
    medicationSafety: "Systemic antibiotics are for cellulitis, osteomyelitis or systemic infection—not routine colonization. Avoid cytotoxic topical agents that delay healing unless a wound specialist identifies a specific role.",
    redFlags: "Rapidly spreading erythema, crepitus, sepsis, exposed/infected bone, necrotizing infection, critical limb ischemia or deep device-related injury requires urgent specialty care.",
    examTraps: "Do not reverse-stage a healing pressure injury; document it as healing from its deepest known stage. Skin breakdown from moisture alone is not automatically a pressure injury.",
    sourceKeys: ["NPIAP_CURRENT"],
  },
  {
    slug: "comprehensive-geriatric-assessment",
    title: "Comprehensive Geriatric Assessment & Functional Decline",
    bodySystem: "Gerontology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PMHNP"],
    recognize: "New difficulty with ADLs/IADLs, weight loss, falls, cognition, mood, incontinence, sensory loss, caregiver strain or social isolation often predicts outcomes more strongly than a single disease diagnosis.",
    diagnostics: "Assess ADLs/IADLs, gait/mobility, cognition, mood, nutrition, hearing/vision, continence, medication burden, pain, social support, finances, transportation and goals. Investigate acute decline for delirium, infection, medication toxicity and other reversible causes.",
    priorities: "Build a problem list around function and patient goals, coordinate PT/OT/social work/home supports, simplify care and align preventive or disease treatments with expected benefit, burden and life expectancy.",
    medicationSafety: "Functional decline may be medication-related even when doses are 'normal.' Review anticholinergic load, hypotensive therapy, sedatives, hypoglycemics and renal dosing before adding new drugs for each symptom.",
    redFlags: "Rapid functional loss, acute confusion, unsafe living situation, inability to obtain food/medications, repeated falls or caregiver collapse requires urgent multidisciplinary assessment.",
    examTraps: "Do not equate dependence in one ADL with lack of decision-making capacity. Functional assessment is not optional background information in geriatric care.",
    sourceKeys: ["AGS_CGA_CURRENT"],
  },
  {
    slug: "palliative-symptom-management",
    title: "Palliative Symptom Management",
    bodySystem: "Palliative Care",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PMHNP"],
    recognize: "Palliative care is appropriate alongside disease-directed treatment for serious illness and focuses on symptom burden, communication, caregiver needs and quality of life; it is not limited to the final days of life.",
    diagnostics: "Assess pain, dyspnea, nausea, constipation, anxiety, delirium, secretions, sleep, function and caregiver burden using the patient's goals and likely cause of symptoms. Testing should be proportional to whether results will change comfort-focused management.",
    priorities: "Treat reversible distress when consistent with goals, use multimodal symptom therapy, anticipate opioid constipation and nausea, support family/caregivers, and involve specialist palliative care for refractory symptoms or complex decisions.",
    medicationSafety: "Opioids can safely treat serious pain and refractory dyspnea when titrated to symptoms and renal/hepatic status; morphine metabolites accumulate in significant renal failure. Benzodiazepines are not first-line for all dyspnea and increase delirium/fall risk.",
    redFlags: "Uncontrolled pain/dyspnea, catastrophic bleeding, severe agitation, opioid toxicity or symptoms inconsistent with the documented goals require rapid reassessment and possible inpatient/hospice support.",
    examTraps: "Appropriate opioid titration for comfort is not euthanasia. Hospice eligibility and palliative-care eligibility are not the same thing.",
    sourceKeys: ["AAHPM_SYMPTOM_CURRENT", "NCCN_PALLIATIVE_CURRENT"],
  },
  {
    slug: "goals-of-care-advance-care-planning",
    title: "Goals of Care & Advance Care Planning",
    bodySystem: "Palliative Care",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PMHNP"],
    recognize: "Serious illness, progressive frailty, repeated hospitalization, major procedure planning or a mismatch between treatment burden and patient priorities should prompt a goals-of-care conversation before a crisis.",
    diagnostics: "Clarify the patient's understanding, values, acceptable function, surrogate decision-maker, decision-specific capacity and prognosis. Capacity is assessed for the specific decision and can fluctuate; it is not determined by diagnosis or age alone.",
    priorities: "Translate values into actionable treatment recommendations and document code status, surrogate, advance directive and portable medical orders when appropriate. Revisit decisions when health status or goals change.",
    medicationSafety: "Medication plans should follow the same goal alignment: preventive drugs with long time-to-benefit may be deprescribed while symptom-relieving drugs are prioritized. Do not withdraw medications simply because a DNR order exists.",
    redFlags: "Conflict about an incapacitated patient's wishes, no available surrogate, suspected coercion, severe untreated symptoms or an imminent high-risk decision may require ethics, legal or palliative-care support.",
    examTraps: "DNR means no CPR after arrest; it does not mean 'do not treat.' Family preference does not override a capacitated patient's informed decision.",
    sourceKeys: ["AGS_ADVANCE_CARE_CURRENT", "AAHPM_GOALS_CURRENT"],
  },
  {
    slug: "elder-abuse-neglect",
    title: "Elder Abuse & Neglect",
    bodySystem: "Gerontology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PMHNP", "ENP"],
    recognize: "Unexplained or patterned injuries, repeated delays in care, poor hygiene, malnutrition, medication withholding, financial exploitation, fearful behavior or a caregiver who controls the interview can signal elder mistreatment.",
    diagnostics: "Interview the patient privately when safe, assess cognition and decision-making capacity, document objective findings, review medication/financial inconsistencies and distinguish pressure injury, falls, disease and neglect while maintaining suspicion when the history does not fit.",
    priorities: "Treat immediate medical needs, create a safe discharge plan, involve social work/forensic teams and follow state mandatory-reporting laws and adult-protective-service pathways. Respect a capacitated adult's autonomy while offering resources and safety planning.",
    medicationSafety: "Medication discrepancies may represent error, neglect or intentional misuse; reconcile before assuming nonadherence. Avoid sedating a distressed patient simply to facilitate an unsafe return home.",
    redFlags: "Immediate danger, serious injury, sexual assault, starvation/dehydration, medication poisoning, unsafe dependent adult or violent caregiver requires emergency protection and reporting.",
    examTraps: "Clinicians do not need courtroom-level proof before making a mandated report when the legal threshold is reasonable suspicion. Cognitive impairment does not automatically mean every caregiver decision is abusive.",
    sourceKeys: ["NCEA_CURRENT", "AGS_ELDER_ABUSE_CURRENT"],
  },
  {
    slug: "malnutrition-older-adults",
    title: "Malnutrition in Older Adults",
    bodySystem: "Gerontology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "Unintentional weight loss, reduced intake, muscle loss, weakness, poor wound healing or loose clothing may indicate malnutrition despite a normal or high BMI. Dental disease, dysphagia, depression, dementia, medications, poverty and malignancy are common contributors.",
    diagnostics: "Document weight trajectory and intake, use a validated nutrition screen, examine oral/dental and swallowing function, and order targeted CBC/CMP/TSH or disease-specific testing rather than relying on albumin as a nutrition marker.",
    priorities: "Treat the cause, improve calorie/protein density, address swallowing and oral health, provide feeding assistance and social supports, and use dietitian/SLP consultation when needed. Exercise helps rebuild function when medically safe.",
    medicationSafety: "Appetite stimulants have limited benefit and can cause thrombotic, delirium or fluid-retention harms; they are not routine first-line therapy. Review medications causing nausea, dry mouth, taste change or early satiety.",
    redFlags: "Severe dehydration, unsafe swallowing/aspiration, profound weight loss, electrolyte disturbance, suspected neglect or refeeding risk requires urgent multidisciplinary care.",
    examTraps: "Albumin falls with inflammation and is not a stand-alone diagnostic nutrition test. Obesity does not exclude sarcopenia or protein-calorie malnutrition.",
    sourceKeys: ["ASPEN_GERIATRIC_NUTRITION_CURRENT", "AGS_NUTRITION_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
