import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch16 = [
  {
    slug: "hematuria-proteinuria",
    title: "Hematuria & Proteinuria Evaluation",
    bodySystem: "Renal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Visible blood, persistent microscopic hematuria, foamy urine, edema, hypertension, or incidental albuminuria can signal glomerular, urologic, infectious, stone, medication, or malignant disease. Confirm true RBCs rather than assuming a positive dipstick equals hematuria.",
    diagnostics: "Repeat urinalysis with microscopy when appropriate, quantify albumin or protein, assess creatinine/eGFR, BP, urine sediment, culture when symptomatic, and risk-stratify hematuria for imaging and cystoscopy. Dysmorphic RBCs, casts, and significant protein favor glomerular disease.",
    priorities: "Treat reversible infection or transient causes, but refer persistent glomerular features to nephrology and risk-based unexplained hematuria to urology. Heavy proteinuria warrants kidney-protective therapy and a search for systemic disease.",
    medicationSafety: "ACEi or ARB therapy can reduce albuminuria when indicated but requires potassium and renal monitoring. Anticoagulation may reveal bleeding but does not eliminate the need to evaluate significant hematuria.",
    redFlags: "Gross hematuria with clots and retention, rapidly rising creatinine, RBC casts, severe hypertension, pulmonary-renal syndrome, or nephritic edema requires urgent evaluation.",
    examTraps: "Menstruation and exercise can contaminate urine, so repeat properly collected testing when appropriate. Do not blame microscopic hematuria on anticoagulants without evaluating malignancy and renal causes.",
    sourceKeys: ["AUA_MICROHEMATURIA_CURRENT", "KDIGO_CKD_2024"],
  },
  {
    slug: "nephrotic-syndrome",
    title: "Nephrotic Syndrome",
    bodySystem: "Renal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP"],
    recognize: "Heavy proteinuria, hypoalbuminemia, edema, hyperlipidemia, and increased thrombosis or infection risk suggest nephrotic syndrome. Diabetes is common, but primary glomerular, autoimmune, medication, malignancy, and infectious causes must be considered.",
    diagnostics: "Quantify urine protein or albumin, check serum albumin, creatinine/eGFR, lipids and urine sediment, then test for diabetes, hepatitis, HIV, autoimmune or paraprotein disease when indicated. Kidney biopsy is often needed when cause is unclear or atypical.",
    priorities: "Control edema and BP, reduce proteinuria, address lipids and thrombosis risk, vaccinate appropriately, and refer for nephrology-directed disease-specific therapy. Sodium restriction and careful diuretic strategy are common supportive measures.",
    medicationSafety: "Aggressive diuresis can cause intravascular depletion and AKI despite marked edema. Immunosuppression requires infection, bone, glucose, reproductive and vaccination planning and should follow a defined diagnosis.",
    redFlags: "Renal vein thrombosis or PE, severe infection, rapidly worsening kidney function, refractory anasarca, or pulmonary edema requires urgent evaluation.",
    examTraps: "Edema does not prove heart failure. Nephrotic urine sediment may be relatively bland despite severe glomerular disease.",
    sourceKeys: ["KDIGO_GLOMERULAR_CURRENT"],
  },
  {
    slug: "nephritic-glomerulonephritis",
    title: "Nephritic Syndrome & Glomerulonephritis",
    bodySystem: "Renal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Hematuria with dysmorphic RBCs or casts, hypertension, edema, reduced kidney function and moderate proteinuria suggests nephritic glomerular inflammation. Consider postinfectious disease, IgA nephropathy, lupus, ANCA vasculitis and anti-GBM disease.",
    diagnostics: "Trend creatinine, urinalysis and protein, complement, CBC and targeted ANA, ANCA, anti-GBM, hepatitis or streptococcal studies according to the phenotype. Kidney biopsy often establishes the exact diagnosis and guides immunosuppression.",
    priorities: "Control BP and volume, stop nephrotoxins, involve nephrology early, and urgently treat rapidly progressive or pulmonary-renal syndromes with disease-specific immunosuppression or plasma exchange when indicated.",
    medicationSafety: "Immunosuppressive therapy carries major infection, fertility, pregnancy, marrow and metabolic risks. Do not start high-dose steroids reflexively before excluding important infections when the patient is stable enough for evaluation.",
    redFlags: "Rapid creatinine rise, oliguria, severe hypertension, pulmonary hemorrhage, hyperkalemia, or crescentic disease concern requires urgent nephrology or inpatient care.",
    examTraps: "A normal complement level does not exclude glomerulonephritis. Gross cola-colored urine after an infection is not automatically a UTI or stone.",
    sourceKeys: ["KDIGO_GLOMERULAR_CURRENT"],
  },
  {
    slug: "renal-artery-stenosis",
    title: "Renovascular Hypertension & Renal Artery Stenosis",
    bodySystem: "Renal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "Abrupt or resistant hypertension, recurrent flash pulmonary edema, asymmetric kidneys, abdominal bruit, diffuse atherosclerosis, or a marked creatinine rise after RAAS blockade can suggest renovascular disease.",
    diagnostics: "First confirm true resistant hypertension and adherence, then use duplex ultrasound, CTA, or MRA based on renal function, anatomy and local expertise when suspicion is meaningful. Screen for fibromuscular dysplasia patterns in younger patients.",
    priorities: "Optimize BP, lipid, diabetes and smoking risk first. Revascularization is selective rather than routine and is considered for specific high-risk syndromes such as recurrent pulmonary edema, progressive renal dysfunction, or refractory hypertension.",
    medicationSafety: "ACEi/ARBs are useful in many unilateral cases but can precipitate AKI in bilateral severe stenosis or a solitary functioning kidney; monitor creatinine and potassium after initiation or titration.",
    redFlags: "Flash pulmonary edema, rapidly progressive renal failure, hypertensive emergency, or severe refractory hypertension requires expedited nephrology/vascular evaluation.",
    examTraps: "An abdominal bruit alone is not a diagnosis. Do not stent every atherosclerotic renal artery lesion found incidentally.",
    sourceKeys: ["AHA_RENOVASCULAR_CURRENT"],
  },
  {
    slug: "ckd-complications",
    title: "CKD Anemia & Mineral-Bone Complications",
    bodySystem: "Renal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP"],
    recognize: "Progressive CKD can cause normocytic anemia, iron deficiency, secondary hyperparathyroidism, hyperphosphatemia, vitamin D disturbances, bone disease and vascular calcification. Symptoms may be subtle until advanced stages.",
    diagnostics: "For anemia check CBC, ferritin and transferrin saturation before attributing low hemoglobin solely to CKD. For CKD-MBD trend calcium, phosphate, PTH and alkaline phosphatase according to stage and clinical context.",
    priorities: "Correct iron deficiency, manage CKD-MBD drivers and consider erythropoiesis-stimulating therapy in selected patients after reversible causes are addressed. Coordinate treatment targets with nephrology rather than normalizing every lab aggressively.",
    medicationSafety: "ESAs increase thrombosis and cardiovascular risk when hemoglobin is pushed too high. Phosphate binders and vitamin D analogues can alter calcium/phosphate balance; iron therapy has GI or infusion risks.",
    redFlags: "Severe symptomatic anemia, refractory hyperkalemia, severe symptomatic hypocalcemia, calciphylaxis, or advanced uremic symptoms requires urgent specialty care.",
    examTraps: "Do not diagnose anemia of CKD without checking iron and other causes. PTH in CKD should be interpreted as a trend within the renal context rather than compared simplistically with a healthy-person target.",
    sourceKeys: ["KDIGO_ANEMIA_CURRENT", "KDIGO_CKD_MBD_CURRENT"],
  },
  {
    slug: "esrd-dialysis",
    title: "End-Stage Kidney Disease & Dialysis",
    bodySystem: "Renal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Advanced kidney failure may cause uremic symptoms, refractory volume overload, hyperkalemia, acidosis, pruritus, anorexia, cognitive change, pericarditis, or access-related complications. Dialysis need is based on clinical indications, not eGFR alone.",
    diagnostics: "Trend electrolytes, bicarbonate, volume, nutrition, anemia and access status. In dialysis patients investigate fever, hypotension, missed treatments, catheter or fistula problems, peritonitis symptoms, and medication accumulation promptly.",
    priorities: "Coordinate modality and access planning early, preserve veins, optimize vaccination and transplant evaluation, and urgently dialyze for refractory electrolyte/acid-base, pulmonary edema, selected toxins, or uremic complications.",
    medicationSafety: "Many drugs require dialysis-specific dosing and timing. Avoid unnecessary PICC placement in advanced CKD when future vascular access is important; NSAIDs and magnesium/aluminum-containing products can create additional toxicity.",
    redFlags: "Severe hyperkalemia, pulmonary edema, uremic pericarditis or encephalopathy, infected dialysis access with sepsis, or peritoneal dialysis peritonitis requires urgent care.",
    examTraps: "Do not start dialysis solely because creatinine is high or eGFR crosses one number. A functioning AV fistula should have a thrill/bruit; absence is an urgent access problem.",
    sourceKeys: ["KDIGO_KRT_CURRENT", "KDOQI_VASCULAR_ACCESS_CURRENT"],
  },
  {
    slug: "acute-urinary-retention",
    title: "Acute Urinary Retention",
    bodySystem: "Genitourinary",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Painful inability to void, suprapubic fullness, overflow dribbling, agitation or unexplained AKI can reflect acute retention. Causes include BPH, constipation, anticholinergics, opioids, infection, postoperative states, neurologic disease and urethral obstruction.",
    diagnostics: "Confirm bladder distention with exam or bladder scan and assess urinalysis, creatinine and neurologic findings. Evaluate for cauda equina, severe constipation, prostate disease, clot retention or urethral trauma based on history.",
    priorities: "Prompt bladder decompression is usually required, followed by treatment of the cause and trial-of-void planning. Use urology consultation when catheterization is difficult, obstruction is complex, or recurrent retention persists.",
    medicationSafety: "Alpha blockers can improve trial-of-void success in BPH but may cause orthostasis. Avoid repeated traumatic catheter attempts when urethral injury or stricture is suspected.",
    redFlags: "Retention with saddle anesthesia or leg weakness, gross hematuria with clots, sepsis, severe AKI, anuria, or suspected urethral injury requires urgent specialty or emergency evaluation.",
    examTraps: "Overflow incontinence can be urinary retention, not overactive bladder. Large post-void residuals should not be treated with anticholinergics before defining obstruction.",
    sourceKeys: ["AUA_RETENTION_CURRENT"],
  },
  {
    slug: "acute-chronic-prostatitis",
    title: "Acute & Chronic Prostatitis",
    bodySystem: "Genitourinary",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "ENP"],
    recognize: "Fever, dysuria, pelvic or perineal pain, obstructive symptoms and a tender prostate suggest acute bacterial prostatitis. Chronic pelvic pain syndromes often lack fever and positive cultures and require a broader pain/urologic differential.",
    diagnostics: "Obtain urinalysis and urine culture before antibiotics when feasible. Avoid vigorous prostatic massage in acute bacterial disease; image when abscess, obstruction, sepsis, or failure to improve is suspected.",
    priorities: "Treat acute bacterial prostatitis with antibiotics that penetrate prostatic tissue and tailor to cultures, duration and severity. Hospitalize unstable patients and address retention without traumatic urethral instrumentation when possible.",
    medicationSafety: "Fluoroquinolones and TMP-SMX have interaction, renal, QT, tendon, potassium and other adverse-effect considerations. Antibiotics do not routinely benefit chronic pelvic pain without evidence of infection.",
    redFlags: "Sepsis, urinary retention, suspected prostatic abscess, severe immunocompromise, or inability to tolerate oral therapy requires urgent urologic/inpatient management.",
    examTraps: "A high PSA during acute prostatitis does not diagnose prostate cancer. Do not repeatedly prescribe antibiotics for chronic pelvic pain with persistently negative infection evaluation.",
    sourceKeys: ["AUA_PROSTATITIS_CURRENT", "EAU_UROINFECTIONS_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
