import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch48 = [
  {
    slug: "iron-deficiency-anemia-evaluation",
    title: "Iron Deficiency Anemia Evaluation",
    bodySystem: "Hematology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "WHNP", "PNP"],
    recognize: "Iron deficiency commonly causes microcytosis, high RDW, fatigue, pica, restless legs or hair/nail changes, but early deficiency can be normocytic. In adults it is a diagnosis plus a cause-search: menstrual blood loss, GI bleeding, pregnancy, malabsorption, dietary deficit and frequent blood donation are common drivers.",
    diagnostics: "Use ferritin plus transferrin saturation/iron studies in context; inflammation can falsely elevate ferritin, so a 'normal' ferritin does not always exclude deficiency. Evaluate GI blood loss according to age/sex/risk, test for celiac/H. pylori when appropriate and assess heavy menstrual bleeding rather than simply prescribing indefinite iron.",
    priorities: "Treat the source and replace iron orally using a tolerable elemental-iron regimen—often once daily or every other day—or IV when oral therapy fails, absorption is poor, rapid replacement is needed or CKD/IBD context supports it. Recheck hemoglobin and iron stores to confirm response and repletion.",
    medicationSafety: "Oral iron causes GI upset/constipation and interacts with several drugs; taking it with calcium, antacids or some foods can reduce absorption. IV iron can cause infusion reactions and transient hypophosphatemia depending on formulation; severe anaphylaxis is rare with modern products.",
    redFlags: "Hemodynamic bleeding, severe symptomatic anemia, rapidly falling hemoglobin, melena/hematochezia, postmenopausal or male unexplained iron deficiency or failure to respond despite adherence requires urgent/expedited evaluation.",
    examTraps: "Do not accept iron deficiency in an adult as an endpoint without asking why. A normal MCV does not exclude early or mixed iron deficiency.",
    sourceKeys: ["AGA_IRON_DEFICIENCY_CURRENT", "ASH_IRON_CURRENT"],
  },
  {
    slug: "macrocytic-anemia",
    title: "Macrocytic Anemia: B12, Folate & Nonmegaloblastic Causes",
    bodySystem: "Hematology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PNP"],
    recognize: "Macrocytosis may reflect B12/folate deficiency with megaloblastic marrow changes, but alcohol, liver disease, hypothyroidism, medications, reticulocytosis and myelodysplasia are common nonmegaloblastic causes. B12 deficiency can cause neuropathy, gait/cognitive change or glossitis before severe anemia.",
    diagnostics: "Review smear and reticulocyte count plus B12, folate and TSH/liver context; methylmalonic acid helps clarify borderline B12 results. Test intrinsic-factor antibodies for suspected pernicious anemia and evaluate marrow disease when cytopenias/dysplasia persist without nutritional/endocrine cause.",
    priorities: "Replace B12 promptly when deficiency with neurologic findings is likely—parenteral therapy is appropriate for severe neurologic/malabsorptive disease—and replace folate only after B12 deficiency has been considered. Treat alcohol, thyroid, liver or marrow causes separately.",
    medicationSafety: "Folate can correct the anemia of B12 deficiency while neurologic injury progresses, so do not give folate alone before assessing B12 in a compatible syndrome. Metformin and acid-suppressive therapy can contribute to B12 deficiency over time.",
    redFlags: "Progressive neurologic deficit, severe pancytopenia, hemolysis, profound symptomatic anemia or suspected acute leukemia/myelodysplasia requires urgent evaluation.",
    examTraps: "A high MCV is not synonymous with folate deficiency and serum B12 alone can be equivocal. Neurologic B12 disease may occur without dramatic macrocytosis.",
    sourceKeys: ["ASH_B12_FOLATE_CURRENT"],
  },
  {
    slug: "hemolytic-anemia-workup",
    title: "Hemolytic Anemia Workup",
    bodySystem: "Hematology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PNP", "ENP"],
    recognize: "Hemolysis causes anemia with reticulocytosis, indirect hyperbilirubinemia, LDH elevation and low haptoglobin; jaundice, dark urine, splenomegaly or gallstones can occur. Differentiate immune hemolysis, microangiopathic destruction, membrane/enzyme disorders, infection, mechanical valves and hemoglobinopathies.",
    diagnostics: "Confirm hemolysis with CBC/reticulocytes, bilirubin, LDH, haptoglobin and smear; direct antiglobulin testing separates many immune from nonimmune causes. Schistocytes plus thrombocytopenia/organ injury raises TMA/DIC concern, while bite cells/Heinz bodies suggest oxidative injury such as G6PD deficiency.",
    priorities: "Treat the cause and stabilize severe anemia; warm autoimmune hemolytic anemia often receives glucocorticoids with hematology follow-up, whereas TTP needs immediate plasma exchange/caplacizumab-based emergency therapy and G6PD hemolysis requires removal of the oxidant trigger.",
    medicationSafety: "Do not give oxidative drugs such as certain sulfonamides/dapsone to known severe G6PD deficiency without risk review; transfusion decisions depend on symptoms/hemodynamics rather than waiting for perfect crossmatch in life-threatening immune hemolysis.",
    redFlags: "Schistocytes with thrombocytopenia/neurologic or renal dysfunction, severe intravascular hemolysis, hemodynamic instability or transfusion reaction requires emergency hematology care.",
    examTraps: "Reticulocytosis can raise the MCV and mimic macrocytic anemia. A positive DAT supports immune hemolysis but can be positive without active clinically important hemolysis.",
    sourceKeys: ["ASH_HEMOLYTIC_ANEMIA_CURRENT", "ASH_TTP_CURRENT"],
  },
  {
    slug: "immune-thrombocytopenia",
    title: "Immune Thrombocytopenia",
    bodySystem: "Hematology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "WHNP", "PNP", "ENP"],
    recognize: "ITP typically causes isolated thrombocytopenia with mucocutaneous bleeding/petechiae and otherwise preserved CBC/smear. Pseudothrombocytopenia, medications, infection, liver/splenic disease, TMA/DIC, leukemia and pregnancy-related disorders must be excluded before labeling it immune.",
    diagnostics: "Repeat count in citrate/heparin tube when platelet clumping is possible, review smear, HIV/HCV and medication/pregnancy context and use additional testing only when atypical findings suggest marrow/systemic disease. Bone marrow biopsy is not routine for a typical isolated ITP presentation.",
    priorities: "Observe selected adults with mild thrombocytopenia/no bleeding and treat based on bleeding, platelet level, procedures, comorbidity and patient factors. Corticosteroids or IVIG are first-line for many significant cases; thrombopoietin-receptor agonists, rituximab or splenectomy are second-line choices.",
    medicationSafety: "Avoid prolonged high-dose steroids because toxicity outweighs benefit; TPO receptor agonists increase thrombosis risk and require ongoing platelet/liver monitoring depending on agent. Platelet transfusion is reserved mainly for life-threatening bleeding or urgent procedures because immune destruction can rapidly consume transfused platelets.",
    redFlags: "Intracranial/GI major bleeding, severe headache/neuro deficit, rapidly falling platelets with hemolysis/renal failure or pregnancy with HELLP/TTP concern requires emergency care.",
    examTraps: "Do not diagnose ITP when anemia/schistocytes/renal injury suggest TMA and do not treat a number alone when the patient is stable and bleeding risk is low.",
    sourceKeys: ["ASH_ITP_CURRENT"],
  },
  {
    slug: "thrombotic-thrombocytopenic-purpura",
    title: "Thrombotic Thrombocytopenic Purpura",
    bodySystem: "Hematology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "WHNP", "ENP"],
    recognize: "TTP is severe ADAMTS13 deficiency causing platelet-rich microthrombi, thrombocytopenia and microangiopathic hemolytic anemia; neurologic, renal, fever and other organ findings vary. The classic pentad is uncommon and should never be required before treatment.",
    diagnostics: "Look for schistocytes, elevated LDH/indirect bilirubin, low haptoglobin, thrombocytopenia and relatively normal coagulation tests; send ADAMTS13 activity/inhibitor before plasma exchange if possible but do not delay therapy. PLASMIC score can estimate severe ADAMTS13 deficiency while results are pending.",
    priorities: "Start urgent plasma exchange plus corticosteroid and caplacizumab-based therapy when immune TTP is strongly suspected, with hematology involvement; rituximab is often added for immune suppression. Support organs while avoiding platelet transfusion unless life-threatening bleeding exists.",
    medicationSafety: "Caplacizumab increases bleeding risk and continues until disease activity/ADAMTS13 recovery criteria are met; plasma exchange has line/reaction risks. Platelet transfusion can fuel microvascular thrombosis and is avoided routinely.",
    redFlags: "Any suspected TTP with neuro symptoms, cardiac ischemia, severe hemolysis or rapid platelet fall is a hematologic emergency requiring immediate treatment before confirmatory ADAMTS13 results.",
    examTraps: "Do not wait for renal failure/fever or the full pentad and do not confuse TTP with DIC—PT/aPTT are often near normal in TTP.",
    sourceKeys: ["ISTH_TTP_CURRENT", "ASH_TTP_CURRENT"],
  },
  {
    slug: "febrile-neutropenia",
    title: "Febrile Neutropenia",
    bodySystem: "Oncology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Fever in a patient with severe treatment-related neutropenia can be the only sign of life-threatening infection because inflammation is blunted. Assess chemotherapy timing, ANC trend, central lines, mucositis, pulmonary/GI/urinary symptoms and hemodynamic instability immediately.",
    diagnostics: "Obtain CBC/differential, CMP/lactate as indicated and at least two sets of blood cultures including each central-line lumen plus peripheral culture when feasible; culture/image symptom-specific sites. Do not delay empiric antibiotics for imaging or culture perfection.",
    priorities: "Give prompt antipseudomonal empiric antibiotic therapy to high-risk or unstable patients and admit; use a validated MASCC/CISNE-style risk pathway for carefully selected stable low-risk patients eligible for outpatient oral therapy and reliable rapid follow-up.",
    medicationSafety: "Avoid routine vancomycin unless catheter, skin/soft-tissue, pneumonia, hemodynamic instability or resistant gram-positive indications exist. Renally dose beta-lactams and narrow therapy with cultures/clinical recovery; G-CSF use is primarily prophylactic and selected therapeutic rather than automatic in every episode.",
    redFlags: "Hypotension, lactate elevation, pneumonia, abdominal pain/typhlitis, line infection, altered mentation or prolonged profound neutropenia requires emergency inpatient oncology/infectious care.",
    examTraps: "A normal chest exam and low inflammatory markers do not reassure in neutropenia, and do not wait for ANC confirmation before treating a recently chemotherapy-exposed unstable febrile patient.",
    sourceKeys: ["ASCO_IDSA_FEBRILE_NEUTROPENIA_CURRENT", "NCCN_INFECTIONS_CURRENT"],
  },
  {
    slug: "multiple-myeloma-evaluation",
    title: "Multiple Myeloma Evaluation",
    bodySystem: "Oncology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP"],
    recognize: "Unexplained anemia, kidney dysfunction, hypercalcemia, bone/back pain, pathologic fracture or recurrent infections can signal plasma-cell myeloma. MGUS is common and must be distinguished from smoldering and symptomatic myeloma using burden plus myeloma-defining events.",
    diagnostics: "Order SPEP with immunofixation, serum free light chains and quantitative immunoglobulins plus CBC/CMP/calcium/creatinine; urine studies and bone marrow biopsy complete classification. Whole-body low-dose CT/PET-CT or MRI is preferred over an old skeletal survey alone for many modern evaluations.",
    priorities: "Refer suspected myeloma urgently to hematology for marrow, cytogenetics/staging and multi-agent therapy; treat hypercalcemia, kidney injury and bone disease, avoid nephrotoxins and use bone-modifying agents when indicated.",
    medicationSafety: "Bisphosphonates/denosumab require dental, calcium/vitamin-D and renal considerations; immunomodulatory drugs are highly teratogenic and thrombogenic and require mandated pregnancy/risk programs. NSAIDs can worsen myeloma kidney injury.",
    redFlags: "Spinal cord compression, severe hypercalcemia, rapidly worsening AKI, symptomatic hyperviscosity or pathologic fracture requires urgent specialty/inpatient management.",
    examTraps: "A monoclonal protein does not automatically mean symptomatic myeloma, and a normal total protein does not exclude light-chain disease.",
    sourceKeys: ["NCCN_MYELOMA_CURRENT", "IMWG_CURRENT"],
  },
  {
    slug: "oncologic-emergencies",
    title: "Oncologic Emergencies: Hypercalcemia, SVC & Leukostasis",
    bodySystem: "Oncology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Cancer patients with confusion/dehydration may have severe hypercalcemia; facial/upper-extremity swelling and venous distention suggests SVC syndrome; marked leukocytosis with respiratory or neurologic symptoms suggests leukostasis. These require mechanism-specific action rather than generic 'cancer progression' labeling.",
    diagnostics: "Check corrected/ionized calcium, kidney function and ECG for hypercalcemia; obtain contrast chest imaging for stable SVC syndrome and tissue diagnosis when feasible before therapy; CBC/smear plus leukemia classification and organ assessment guide leukostasis. Do not use the WBC number alone to define leukostasis.",
    priorities: "Severe hypercalcemia receives IV fluids when tolerated plus rapid calcitonin and longer-acting antiresorptive therapy; SVC treatment targets the cause and may require urgent endovascular stenting when airway/cerebral compromise is present; leukostasis needs emergent hematology cytoreduction, tumor-lysis prevention and supportive care.",
    medicationSafety: "Bisphosphonates need renal awareness; denosumab can cause profound hypocalcemia. Steroids can obscure lymphoma histology and should not precede biopsy automatically in stable SVC syndrome; leukapheresis is selective and does not replace definitive leukemia therapy.",
    redFlags: "Airway/cerebral edema from SVC obstruction, severe symptomatic hypercalcemia, respiratory failure/neuro deficit from leukostasis or tumor-lysis physiology requires immediate inpatient oncology care.",
    examTraps: "Do not treat every SVC syndrome with empiric radiation before obtaining diagnosis if the patient is stable, and do not confuse hyperleukocytosis with symptomatic leukostasis.",
    sourceKeys: ["NCCN_ONCOLOGIC_EMERGENCIES_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
