import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch60 = [
  {
    slug: "decision-making-capacity-informed-consent",
    title: "Decision-Making Capacity & Informed Consent",
    bodySystem: "Professional Practice",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PMHNP", "PNP", "WHNP", "ENP"],
    recognize: "Clinical decision-making capacity is task- and time-specific and requires the patient to understand relevant information, appreciate how it applies personally, reason about options and communicate a stable choice. Dementia, psychiatric diagnosis, intoxication or disagreement with the clinician does not automatically eliminate capacity.",
    diagnostics: "Correct reversible barriers such as delirium, pain, hearing/language difficulty or medication effects, use a qualified interpreter when needed and document the four capacity abilities for the specific decision. Formal psychiatric or neuropsychologic consultation is helpful for complex cases but the treating clinician can assess capacity.",
    priorities: "Provide material risks, benefits, alternatives—including no treatment—and check comprehension without coercion. If capacity is absent, identify the legally authorized surrogate and use substituted judgment or best-interest standards while involving the patient to the greatest extent possible.",
    medicationSafety: "Consent for medication includes high-impact adverse effects, monitoring and alternatives; emergency treatment may proceed without prior consent only when legal emergency criteria are met and no appropriate surrogate is available in time.",
    redFlags: "Unexplained fluctuating capacity, suspected coercion/abuse, refusal during a life-threatening emergency with unclear capacity or conflict among surrogates requires urgent ethics/legal/clinical escalation.",
    examTraps: "Do not equate orientation to person/place/time with capacity and do not assume a court-appointed guardian removes all patient participation. Capacity is clinical; competency is a legal determination.",
    sourceKeys: ["AMA_CAPACITY_CONSENT_CURRENT", "AHRQ_INFORMED_CONSENT_CURRENT"],
  },
  {
    slug: "advance-care-planning-goals-of-care",
    title: "Advance Care Planning & Goals of Care",
    bodySystem: "Professional Practice",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PMHNP", "PNP", "WHNP", "ENP"],
    recognize: "Goals-of-care conversations are appropriate before crisis in serious chronic illness and whenever prognosis, function or treatment burden changes. Code status is only one decision; it does not define preferences about ICU care, hospitalization, artificial nutrition, dialysis or symptom-focused treatment.",
    diagnostics: "Assess the patient's understanding, information preference, values, unacceptable health states and surrogate decision-maker, then give a clear prognosis range with uncertainty. Review existing advance directives/POLST-type medical orders and confirm they still reflect current wishes.",
    priorities: "Make a recommendation that connects treatments to stated goals, document the conversation and ensure portable medical orders are completed when appropriate. Palliative care can be integrated alongside disease-directed treatment and is not limited to the final days of life.",
    medicationSafety: "Deprescribe treatments whose time-to-benefit no longer matches goals while preserving high-value symptom medications and disease therapy that supports function. Opioids for serious-illness symptom relief are titrated to comfort with monitoring and are not equivalent to euthanasia.",
    redFlags: "Conflict about life-sustaining treatment, uncertain surrogate hierarchy, possible coercion, uncontrolled suffering or rapidly changing capacity warrants ethics/palliative/legal support.",
    examTraps: "DNR means no CPR after arrest—not 'do not treat.' Hospice and palliative care are not synonyms, and patients can receive palliative care while pursuing curative or life-prolonging therapy.",
    sourceKeys: ["CAPC_GOALS_OF_CARE_CURRENT", "AMA_ADVANCE_DIRECTIVES_CURRENT"],
  },
  {
    slug: "elder-abuse-neglect-exploitation",
    title: "Elder Abuse, Neglect & Financial Exploitation",
    bodySystem: "Professional Practice",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PMHNP", "ENP"],
    recognize: "Unexplained injuries, poor hygiene/nutrition, medication withholding, fearful interaction, sudden financial changes, caregiver domination or inconsistent stories can indicate physical, emotional, sexual, neglectful or financial abuse. Cognitive impairment and dependency increase vulnerability but do not prove maltreatment.",
    diagnostics: "Interview the older adult privately when safe, assess capacity/cognition, document objective findings and medication/financial/social context and evaluate injuries or medical consequences. Use validated screening when feasible and involve social work/forensic experts for complex cases.",
    priorities: "Address immediate safety and medical needs and follow state-specific mandatory-reporting law to Adult Protective Services or other authorities; requirements vary across U.S. jurisdictions, so education should not invent one national reporting threshold or agency pathway.",
    medicationSafety: "Medication mismanagement can be a form of neglect/exploitation; reconcile actual administration and access. Avoid sedating a patient merely to make caregiving easier and assess whether a caregiver is controlling controlled substances or finances.",
    redFlags: "Immediate danger, sexual assault, serious injury, abandonment, dangerous neglect or financial coercion impairing basic care requires urgent protective intervention.",
    examTraps: "Do not confront a suspected abuser in a way that increases patient danger and do not wait for proof beyond the jurisdiction's reporting threshold before making a required report.",
    sourceKeys: ["ACL_ELDER_JUSTICE_CURRENT", "AMA_ELDER_ABUSE_CURRENT"],
  },
  {
    slug: "telehealth-clinical-governance",
    title: "Telehealth Clinical Governance",
    bodySystem: "Professional Practice",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PMHNP", "PNP", "WHNP", "ENP"],
    recognize: "Telehealth is a care modality, not a lower standard of care. The clinician must know the patient's physical location, identity, emergency plan and whether the clinical question can be answered safely without hands-on examination or onsite testing.",
    diagnostics: "Use reliable home measurements, patient-assisted examination and appropriate video/audio assessment while recognizing limitations; convert to in-person/emergency evaluation when vital signs, neurologic, abdominal, cardiopulmonary or procedural findings cannot be assessed adequately.",
    priorities: "Confirm consent/privacy, document modality/limitations and patient location, arrange tests/referrals and give specific escalation instructions. Licensure, prescribing and telehealth rules depend on the patient's state and current federal/state law rather than the clinician's home location alone.",
    medicationSafety: "Controlled-substance tele-prescribing requirements can change and vary; verify current DEA/federal and state rules before prescribing rather than relying on pandemic-era assumptions. Avoid antibiotics or high-risk drugs solely because physical exam is inconvenient.",
    redFlags: "Chest pain, focal neurologic deficit, severe dyspnea, suicidal intent, acute abdomen, unstable pregnancy symptoms or any condition requiring immediate physical intervention should move out of routine telehealth.",
    examTraps: "Do not assume a video visit permits practice across every state line and do not document a normal physical exam that was not actually possible remotely.",
    sourceKeys: ["HHS_TELEHEALTH_CURRENT", "DEA_TELEMEDICINE_CURRENT"],
  },
  {
    slug: "diagnostic-test-probability-bayes",
    title: "Pretest Probability, Likelihood Ratios & Diagnostic Testing",
    bodySystem: "Professional Practice",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PMHNP", "PNP", "WHNP", "ENP"],
    recognize: "A test result changes probability; it does not exist independently of pretest risk. When pretest probability is extremely low, false positives can dominate; when very high, a negative screening test may be insufficient to exclude dangerous disease.",
    diagnostics: "Estimate pretest probability from prevalence plus patient-specific features, then apply sensitivity/specificity or likelihood ratios to move toward a test or treatment threshold. Use validated clinical decision rules only in the populations and contexts where they were derived.",
    priorities: "Choose tests that can change management and avoid redundant low-yield panels. Use high-sensitivity tests to rule out at appropriate low-intermediate probability and high-specificity confirmatory tests when false-positive harm matters.",
    medicationSafety: "Diagnostic uncertainty should not trigger empiric high-risk medication automatically; balance the treatment threshold against medication harm, delay harm and test characteristics—for example anticoagulation, antibiotics or steroids.",
    redFlags: "A high-risk clinical syndrome with a negative low-sensitivity or mistimed test requires escalation/alternative testing rather than reassurance.",
    examTraps: "A '95% accurate' test is meaningless without defining sensitivity, specificity and prevalence. Positive predictive value falls as prevalence/pretest probability falls.",
    sourceKeys: ["JAMA_EVIDENCE_BASED_DIAGNOSIS_CURRENT", "AHRQ_DIAGNOSTIC_SAFETY_CURRENT"],
  },
  {
    slug: "health-equity-cultural-humility",
    title: "Health Equity, Cultural Humility & Structural Risk",
    bodySystem: "Professional Practice",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PMHNP", "PNP", "WHNP", "ENP"],
    recognize: "Health differences may reflect access, discrimination, language, disability, income, geography, immigration stress and historical/systemic inequity rather than intrinsic biological race categories. Cultural humility means curiosity and self-reflection rather than memorizing stereotypes about groups.",
    diagnostics: "Ask the individual about language, health beliefs, cost, transportation, food/housing safety, literacy, disability accommodations and treatment preferences; use qualified interpreters rather than family members for important communication whenever possible.",
    priorities: "Adapt the care plan to structural barriers, connect resources, use inclusive anatomy/identity-based screening and advocate for equitable access while preserving evidence-based standards. Examine whether algorithms or race corrections create inequitable decisions and use current race-neutral equations where standards have changed.",
    medicationSafety: "Cost and formulary access are medication-safety issues because unaffordable prescriptions cause nonadherence; choose feasible regimens without assuming poor adherence is a character trait. Avoid race as a proxy for pharmacogenomic testing.",
    redFlags: "Inability to obtain lifesaving medication, unsafe housing/violence, trafficking, food insecurity affecting insulin or dialysis care or communication failure around a high-risk decision requires urgent systems intervention.",
    examTraps: "Do not stereotype based on culture or race and do not use a child/family member as the default interpreter for consent or sensitive discussions.",
    sourceKeys: ["HHS_CLAS_CURRENT", "AHRQ_HEALTH_EQUITY_CURRENT"],
  },
  {
    slug: "consultation-referral-closed-loop",
    title: "Consultation, Referral & Closed-Loop Follow-Up",
    bodySystem: "Professional Practice",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PMHNP", "PNP", "WHNP", "ENP"],
    recognize: "A referral is not complete when an order is placed. High-quality consultation defines the clinical question, urgency, relevant results, what has already been tried and who owns care while the patient waits; abnormal tests and referrals are common points for diagnostic loss-to-follow-up.",
    diagnostics: "Risk-stratify urgency from red flags and disease trajectory and verify that the receiving service has the information needed. Track whether the referral was scheduled/completed and whether recommendations/results returned to the ordering clinician.",
    priorities: "Use direct clinician-to-clinician communication for emergency/rapid deterioration, provide an interim management plan and return precautions and establish closed-loop tracking for critical results, biopsies, imaging and specialist recommendations.",
    medicationSafety: "Clarify who will monitor specialty medications, labs and refills; avoid duplicated or conflicting prescriptions from multiple clinicians and reconcile changes after consultation.",
    redFlags: "Suspected cancer, unstable cardiac/neurologic disease, organ-threatening autoimmune disease, critical lab/pathology or failed urgent referral requires active escalation rather than another routine referral message.",
    examTraps: "Do not tell a patient 'the specialist will handle it' without interim responsibility and do not assume no news means a normal result.",
    sourceKeys: ["AHRQ_CLOSED_LOOP_REFERRAL_CURRENT", "TJC_CRITICAL_RESULTS_CURRENT"],
  },
  {
    slug: "quality-improvement-patient-safety",
    title: "Quality Improvement & Patient Safety for NPs",
    bodySystem: "Professional Practice",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PMHNP", "PNP", "WHNP", "ENP"],
    recognize: "Safety events often result from system design, communication, workload and process failures rather than one careless person. Near misses, medication errors, diagnostic delays, falls and handoff failures are data for improvement and require a just-culture response.",
    diagnostics: "Define the problem with process/outcome/balancing measures and use root-cause analysis for serious events and PDSA or other improvement methods for iterative change. Distinguish common-cause from special-cause variation before assuming every data fluctuation proves improvement.",
    priorities: "Implement high-leverage system fixes such as standardization, forcing functions, medication reconciliation, checklists and closed-loop communication, then measure whether the change improves outcomes without creating new harm.",
    medicationSafety: "High-alert drugs benefit from standardized concentrations, independent double-checks where evidence supports them, smart pump/decision support and clear reconciliation; overrides and workarounds are signals for system redesign rather than automatic punishment.",
    redFlags: "Sentinel events, wrong-patient/procedure errors, major medication injury, retained critical results or recurring near misses requires formal reporting and leadership/safety investigation.",
    examTraps: "Education alone is a weak fix for a system defect and root-cause analysis should not end by naming the person who made the last visible error.",
    sourceKeys: ["AHRQ_PATIENT_SAFETY_CURRENT", "IHI_QI_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
