import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch53 = [
  {
    slug: "laceration-repair",
    title: "Laceration Evaluation & Repair",
    bodySystem: "Procedures",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "ENP", "PNP"],
    recognize: "Before closing a laceration, define mechanism/time, contamination, foreign body, bite, tetanus status and neurovascular/tendon injury. Wounds over joints, hands, face or near major nerves/vessels require anatomy-specific examination before local anesthetic obscures findings.",
    diagnostics: "Explore through full range of motion when tendon injury is possible and use x-ray/ultrasound for radiopaque or suspected retained foreign body/fracture when indicated. Routine wound cultures or x-rays are unnecessary for simple clean superficial lacerations.",
    priorities: "Provide adequate anesthesia, copious irrigation and debridement of devitalized contamination, then choose primary closure, delayed closure or secondary healing based on infection risk and tissue viability. Align wound edges without strangulating tissue and give clear return/suture-removal/scar instructions.",
    medicationSafety: "Local anesthetic maximum dose depends on agent, concentration, weight and epinephrine use; calculate it explicitly for large repairs. Prophylactic systemic antibiotics are not routine for clean uncomplicated lacerations but are used for selected bites, heavily contaminated wounds, cartilage/joint involvement or high-risk hosts.",
    redFlags: "Uncontrolled bleeding, ischemia, tendon/nerve deficit, open fracture, joint penetration, deep bite to hand, retained deep foreign body or necrotizing infection concern requires urgent specialty/emergency care.",
    examTraps: "Do not close before documenting distal neurovascular/tendon function and do not use hydrogen peroxide/povidone inside tissue as a substitute for irrigation. Epinephrine-containing local anesthetic is not categorically forbidden in all digits when perfusion is normal and dosing is appropriate.",
    sourceKeys: ["ACEP_WOUND_CURRENT", "CDC_TETANUS_CURRENT"],
  },
  {
    slug: "cutaneous-abscess-incision-drainage",
    title: "Cutaneous Abscess Incision & Drainage",
    bodySystem: "Procedures",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "ENP", "PNP"],
    recognize: "A fluctuant tender collection is an abscess; cellulitis without collection does not benefit from incision. Ultrasound helps when the exam is equivocal or the lesion is deep, obese, near vessels or previously treated.",
    diagnostics: "Assess size/location, systemic illness, immune status, recurrence and anatomic danger zones; culture pus in severe/recurrent disease, treatment failure or high-risk hosts rather than necessarily every first uncomplicated abscess.",
    priorities: "Incision and adequate drainage are primary therapy for a drainable abscess; break loculations gently, irrigate selectively and use packing only when cavity characteristics justify it. Add MRSA-active antibiotics when systemic illness, extensive cellulitis, immune compromise, difficult location, recurrence or other guideline factors support benefit.",
    medicationSafety: "TMP-SMX, doxycycline and clindamycin have renal, pregnancy, interaction, GI/C. difficile and resistance considerations. Avoid routine opioid prescriptions for minor I&D when NSAID/acetaminophen and local care are sufficient.",
    redFlags: "Perineal/Fournier distribution, facial danger triangle/orbital extension, hand deep-space infection, sepsis, rapidly spreading pain or crepitus requires urgent surgical/inpatient care.",
    examTraps: "Antibiotics alone often fail a true drainable abscess and I&D does not help nonpurulent cellulitis without a collection. Recurrent 'abscesses' in intertriginous sites may be hidradenitis.",
    sourceKeys: ["IDSA_SSTI_CURRENT"],
  },
  {
    slug: "arthrocentesis-joint-injection",
    title: "Arthrocentesis & Joint Injection",
    bodySystem: "Procedures",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "ENP"],
    recognize: "Arthrocentesis is diagnostic and therapeutic for an acutely swollen joint when septic arthritis, crystal disease or hemarthrosis is possible. Intra-articular corticosteroid injection is a separate decision and should not occur until infection has been reasonably excluded.",
    diagnostics: "Send synovial fluid for cell count/differential, Gram stain/culture and crystal analysis when acute monoarthritis is unexplained; use ultrasound to improve access for difficult/deep joints. Serum urate, ESR/CRP and imaging support but do not replace aspiration when infection is plausible.",
    priorities: "Use sterile technique, choose an anatomic or ultrasound-guided approach, aspirate as much diagnostic fluid as feasible and treat the cause. Corticosteroid injection can reduce OA/inflammatory pain in selected joints after infection is excluded, with frequency and structural risks considered.",
    medicationSafety: "Local anesthetic and steroid doses are joint/agent-specific; injection can cause transient hyperglycemia, post-injection flare, skin atrophy/depigmentation and rare infection. Anticoagulation is not an automatic contraindication to every arthrocentesis but bleeding risk must be individualized.",
    redFlags: "Purulent fluid, systemic sepsis, prosthetic joint, rapidly destructive hip/shoulder infection or neurovascular compromise requires urgent orthopedic/ID management.",
    examTraps: "Crystals do not exclude concurrent septic arthritis and do not inject steroids into an undiagnosed hot joint simply because the patient has a history of gout.",
    sourceKeys: ["ACR_JOINT_INJECTION_CURRENT", "IDSA_SEPTIC_ARTHRITIS_CURRENT"],
  },
  {
    slug: "skin-biopsy-techniques",
    title: "Skin Biopsy Technique Selection",
    bodySystem: "Procedures",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "Choose biopsy technique to answer the pathologic question: shave/saucerization for many epidermal/superficial lesions, punch for full-thickness inflammatory disease or small lesions and excisional biopsy for lesions where complete architecture/depth matters, particularly suspected melanoma when feasible.",
    diagnostics: "Document lesion size/location/morphology, photograph when helpful and communicate the clinical differential to pathology. Biopsy the active edge of many inflammatory lesions and avoid necrotic/eroded centers unless that is the target pathology.",
    priorities: "Use adequate local anesthesia and hemostasis, obtain sufficient depth/diameter and orient/label multiple specimens precisely. Suspected melanoma should be sampled to permit accurate Breslow depth and high-risk vasculitic/blistering disease may need paired specimens including direct immunofluorescence.",
    medicationSafety: "Review anticoagulants, allergy and local anesthetic dose but do not stop anticoagulation reflexively for small low-bleeding-risk biopsies without balancing thrombosis risk. Epinephrine can improve hemostasis when appropriate.",
    redFlags: "Uncontrolled bleeding, suspected melanoma inadequately sampled, vasculitis with systemic organ involvement or rapidly progressive blistering/SCAR requires expedited dermatology/specialty care.",
    examTraps: "Do not superficial-shave a deeply suspicious melanoma and do not put a direct-immunofluorescence specimen in routine formalin.",
    sourceKeys: ["AAD_BIOPSY_CURRENT"],
  },
  {
    slug: "foreign-body-removal",
    title: "Soft-Tissue Foreign Body Evaluation & Removal",
    bodySystem: "Procedures",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "ENP", "PNP"],
    recognize: "Persistent focal pain, foreign-body sensation, puncture mechanism, nonhealing wound or infection after glass/wood/metal exposure raises concern for retained material. Wood/organic material is more inflammatory and often radiolucent.",
    diagnostics: "Explore only when anatomy permits and use x-ray for radiopaque material, ultrasound for many radiolucent superficial objects and CT for deep/complex high-risk locations. Assess neurovascular/tendon injury and tetanus status before removal.",
    priorities: "Remove symptomatic, contaminated, toxic, intra-articular, neurovascular-threatening or readily accessible material using adequate anesthesia and visualization; stop blind probing when removal risks greater damage and refer hand/ophthalmic/surgical specialists for deep critical structures.",
    medicationSafety: "Antibiotic prophylaxis is not routine for every retained foreign body but is considered for contaminated/bite/high-risk wounds; local anesthetic dosing and digital perfusion matter. Organic foreign bodies left behind may cause chronic inflammation/infection.",
    redFlags: "Eye penetration, vascular proximity, compartment/deep hand-space infection, open fracture/joint penetration or neurovascular deficit requires urgent specialty care.",
    examTraps: "A negative x-ray does not rule out wood/plastic and repeated blind probing can injure nerves/vessels. Tiny inert deeply embedded fragments may be safer to leave than remove.",
    sourceKeys: ["ACEP_FOREIGN_BODY_CURRENT"],
  },
  {
    slug: "fracture-splinting-initial-care",
    title: "Fracture Immobilization & Initial Splinting",
    bodySystem: "Procedures",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "ENP", "PNP"],
    recognize: "Suspected fracture or significant ligament injury requires deformity, open wound, compartment and neurovascular assessment before and after immobilization. High-risk occult fractures—scaphoid, hip, growth plate—can have initially normal x-rays.",
    diagnostics: "Obtain appropriate views and image adjacent joints when the mechanism/exam warrants it; use CT/MRI/repeat imaging for occult high-risk injuries. Document distal pulse, capillary refill, motor and sensory findings explicitly.",
    priorities: "Reduce grossly deformed limbs urgently when skin or neurovascular structures are threatened, then apply a well-padded splint that accommodates swelling and immobilizes appropriately; arrange fracture-specific orthopedic follow-up and weight-bearing restrictions.",
    medicationSafety: "Analgesia/sedation for reduction requires monitoring and dose adjustment; avoid circumferential casts acutely when swelling risk is high. NSAID use after fracture is individualized rather than universally prohibited.",
    redFlags: "Open fracture, absent pulse, compartment syndrome, skin tenting, unstable pelvic/spine injury or neurovascular decline after splinting requires emergency orthopedic management.",
    examTraps: "A splint is not finished until neurovascular status is rechecked and documented. Normal initial scaphoid/hip x-rays do not end evaluation when clinical suspicion remains high.",
    sourceKeys: ["AAOS_FRACTURE_CURRENT", "ACEP_ORTHO_CURRENT"],
  },
  {
    slug: "diagnostic-paracentesis",
    title: "Diagnostic & Therapeutic Paracentesis",
    bodySystem: "Procedures",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "New, worsening or hospitalized ascites often requires paracentesis to distinguish portal hypertension, infection, malignancy and other causes; abdominal tenderness/fever may be absent in SBP. Therapeutic drainage can rapidly improve tense ascites-related pain/dyspnea.",
    diagnostics: "Use ultrasound to select a safe fluid pocket and send cell count/differential, albumin and total protein for initial diagnostic studies, adding culture inoculated bedside into blood-culture bottles when infection is possible and cytology/amylase/other tests selectively.",
    priorities: "Perform prompt diagnostic paracentesis before antibiotics in stable suspected SBP and large-volume therapeutic paracentesis for tense ascites, giving albumin replacement after removal above the guideline volume threshold in cirrhosis to reduce circulatory dysfunction.",
    medicationSafety: "Routine prophylactic plasma/platelet correction before low-risk paracentesis in cirrhosis is usually unnecessary; anticoagulation decisions are individualized. Avoid removing large volumes without indicated albumin in cirrhosis and monitor renal/hemodynamic response.",
    redFlags: "Severe coagulopathic bleeding from another cause, abdominal wall infection at the site, unstable shock without resuscitation or bowel/bladder interposition requires modified/specialist technique.",
    examTraps: "Cirrhotic INR elevation does not predict procedural bleeding well enough to justify routine FFP before paracentesis. Do not delay SBP diagnosis because the patient has no fever.",
    sourceKeys: ["AASLD_ASCITES_CURRENT"],
  },
  {
    slug: "pelvic-exam-cervical-sampling",
    title: "Pelvic Examination & Cervical Sampling",
    bodySystem: "Procedures",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "WHNP", "PNP"],
    recognize: "A pelvic exam should answer a clinical question—bleeding, discharge, pain, mass, cervical screening or contraceptive procedure—and should be trauma-informed, consent-based and anatomically targeted rather than performed automatically at every preventive visit.",
    diagnostics: "Use speculum examination for vaginal/cervical visualization and sampling, bimanual exam for selected pelvic pain/mass questions and NAAT swabs from the appropriate exposed sites for STI testing. Cervical-cancer screening can often use clinician- or, under current approved pathways, selected self-collected HPV sampling according to guideline and setting.",
    priorities: "Explain each step, use the smallest appropriate speculum/position adaptations, stop when consent is withdrawn and collect samples without contaminating or using the wrong transport medium. Refer abnormal masses, cervical lesions or persistent unexplained bleeding for imaging/gynecology.",
    medicationSafety: "Routine prophylactic antibiotics are not needed for a diagnostic pelvic exam/Pap. Topical anesthetic or anxiolysis is selective; avoid sedating a patient simply to complete a nonurgent exam without addressing trauma/pain and consent.",
    redFlags: "Hemodynamic bleeding, peritonitis, pregnancy with severe pain/bleeding, cervical/vaginal malignancy concern or sexual-assault forensic needs requires urgent/specialized pathways.",
    examTraps: "A Pap test is not a bimanual exam and neither is an STI screen. Routine annual pelvic examination is not required solely because a patient has a uterus when there is no indication and screening is up to date.",
    sourceKeys: ["ACOG_PELVIC_EXAM_CURRENT", "USPSTF_CERVICAL_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
