import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch32 = [
  {
    slug: "severe-asthma-biologic-prescribing",
    title: "Biologic Therapy for Severe Asthma: Selection & Monitoring",
    slugAliases: ["pulmonary-rx-biologic-therapy-np"],
    bodySystem: "Respiratory",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Severe asthma is asthma that remains uncontrolled despite optimized high-dose ICS-containing therapy, adherence, inhaler technique, comorbidity management and trigger reduction—or that worsens when this treatment is reduced. Biologic selection follows inflammatory phenotype and exacerbation burden, not one universal biomarker cutoff.",
    diagnostics: "Before labeling severe disease, reconfirm asthma objectively and assess adherence/technique, smoking or vaping, occupational exposure, obesity, rhinosinusitis/polyps, GERD, sleep apnea and dysfunctional breathing. Then characterize type-2 inflammation with eosinophils, FeNO, allergic sensitization/IgE and oral-steroid/exacerbation history using the eligibility criteria for the specific biologic and payer.",
    priorities: "Refer difficult-to-treat or severe asthma for phenotype-directed therapy. Choose among anti-IgE, anti-IL-5/5R, anti-IL-4Rα and anti-TSLP options based on phenotype, comorbidity, dosing preference, age approval and expected benefit; reassess exacerbations, symptoms, lung function and steroid burden after an adequate trial.",
    medicationSafety: "Biologics can cause hypersensitivity and injection reactions; omalizumab carries anaphylaxis precautions. Do not abruptly stop maintenance oral corticosteroids after biologic response—taper carefully because adrenal suppression and recurrent asthma can occur.",
    redFlags: "Life-threatening exacerbation, silent chest, rising CO2, exhaustion, altered mental status or severe anaphylaxis requires emergency care; a biologic is not rescue treatment for an acute attack.",
    examTraps: "Do not select a biologic from one isolated eosinophil or IgE number and do not skip the basics of diagnosis, adherence and inhaler technique. Dupilumab/tezepelumab and other agents have distinct phenotypes and eligibility rather than being interchangeable 'stronger inhalers.'",
    sourceKeys: ["GINA_2026", "GINA_SEVERE_ASTHMA_2026"],
  },
  {
    slug: "sglt2-cardiorenal-prescribing",
    title: "SGLT2 Inhibitors: Diabetes, Heart Failure & CKD Prescribing",
    slugAliases: ["pulmonary-rx-sglt2-cardiopulmonary-np"],
    bodySystem: "Endocrine",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "SGLT2 inhibitors now have cardiorenal indications that extend beyond glucose lowering: selected patients with type 2 diabetes, CKD and/or heart failure benefit even when A1C lowering is modest. The prescribing question is indication, kidney function, volume status and ketoacidosis risk—not simply 'is the A1C high?'",
    diagnostics: "Review eGFR, electrolytes, BP/volume status, diabetes type, recent DKA, genital-infection history and interacting diuretics before initiation. Use the current product/guideline eGFR threshold for the intended HF/CKD/diabetes indication because glycemic and organ-protection thresholds are not identical.",
    priorities: "Start an evidence-based agent when HF or CKD/diabetes criteria are met, counsel on genital hygiene and sick-day/perioperative management, and reassess renal function, volume and symptoms. A small early eGFR dip can be hemodynamic and does not automatically require discontinuation.",
    medicationSafety: "SGLT2 inhibitors can cause genital mycotic infection, volume depletion and euglycemic DKA. Hold them before scheduled surgery—generally 3 days for most agents and 4 days for ertugliflozin—and during prolonged fasting or critical illness when ketosis risk is high.",
    redFlags: "Nausea, abdominal pain, tachypnea or malaise with an anion-gap acidosis can be euglycemic DKA even if glucose is not markedly elevated; severe dehydration, Fournier gangrene or shock requires urgent care.",
    examTraps: "Do not discontinue a cardiorenal-indicated SGLT2 drug solely because the A1C is already at goal, and do not rule out DKA because glucose is below the classic hyperglycemic range.",
    sourceKeys: ["ADA_2026", "KDIGO_CKD_2024", "HF_ACC_AHA_CURRENT"],
  },
  {
    slug: "potassium-disorders-prescribing",
    title: "Potassium Disorders: Replacement & Hyperkalemia Pharmacotherapy",
    slugAliases: ["renal-rx-potassium-disorders-np"],
    bodySystem: "Renal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Potassium risk depends on severity, rate of change, ECG, kidney function and cause. Hypomagnesemia can make hypokalemia refractory; hyperkalemia may result from kidney failure, RAAS/MRA therapy, tissue breakdown, acidosis or laboratory hemolysis.",
    diagnostics: "Repeat a suspicious nonurgent potassium when pseudohyperkalemia is plausible, but obtain ECG and treat immediately when severe hyperkalemia or compatible ECG change is present. Review magnesium, creatinine/eGFR, bicarbonate/glucose, medications and ongoing GI/renal losses.",
    priorities: "For dangerous hyperkalemia, stabilize the myocardium with IV calcium when ECG toxicity is present, shift potassium intracellularly with insulin/dextrose and other indicated therapies, and remove potassium with diuresis, binders or dialysis according to urgency. Replace potassium orally when feasible and IV only with appropriate pump/monitoring when necessary.",
    medicationSafety: "Never give IV potassium as a bolus. Potassium binders lower total-body potassium but are not substitutes for immediate membrane stabilization and intracellular shifting in an unstable hyperkalemic emergency; insulin therapy requires glucose surveillance for hypoglycemia.",
    redFlags: "Widened QRS, bradyarrhythmia, ventricular arrhythmia, severe weakness/paralysis, potassium that is rapidly rising or refractory, or severe hypokalemia with arrhythmia requires monitored emergency treatment.",
    examTraps: "A normal ECG does not guarantee severe hyperkalemia is safe, and calcium does not lower serum potassium—it buys time by stabilizing cardiac membranes. Avoid universal replacement-rate rules divorced from access type, monitoring and institutional protocol.",
    sourceKeys: ["AHA_HYPERKALEMIA_CURRENT", "KDIGO_POTASSIUM_CURRENT"],
  },
  {
    slug: "diuretic-prescribing",
    title: "Diuretic Therapy: Loop vs Thiazide Selection, Dosing & Monitoring",
    slugAliases: ["renal-rx-diuretic-management-np"],
    bodySystem: "Renal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Match the diuretic to the goal: thiazide/thiazide-like agents are effective antihypertensives, loops are more potent for substantial congestion, and mineralocorticoid antagonists have disease-modifying roles in selected HF/resistant-hypertension states beyond simple diuresis.",
    diagnostics: "Before and after meaningful initiation/titration, assess BP/orthostasis, weight and volume status, sodium, potassium, magnesium and renal function. In congestion, response is judged by symptoms, urine output, weight and perfusion rather than a fixed BUN/creatinine ratio.",
    priorities: "Use adequate loop dosing for congestion and escalate route/dose or add sequential nephron blockade when response is inadequate. Thiazide-like drugs such as chlorthalidone can still lower BP in advanced CKD; the old rule that thiazides are categorically ineffective below eGFR 30 is obsolete.",
    medicationSafety: "Loops/thiazides can cause hypokalemia, hypomagnesemia, hyponatremia, gout and volume depletion; MRAs can cause hyperkalemia. Do not prescribe potassium supplements automatically to every diuretic user—base replacement on measured trend, kidney function and concomitant RAAS/MRA therapy.",
    redFlags: "Severe symptomatic hyponatremia, malignant arrhythmia from electrolyte loss, shock, anuria, severe AKI or pulmonary edema despite escalating diuresis requires urgent/inpatient management.",
    examTraps: "Do not stop effective decongestion merely because creatinine rises modestly if the patient remains congested and perfused; interpret renal changes clinically. Avoid memorized IV:PO conversion as an exact law—bioavailability and response are patient-specific.",
    sourceKeys: ["AHA_BP_2025", "HF_ACC_AHA_CURRENT", "KDIGO_CKD_2024"],
  },
  {
    slug: "ckd-mineral-bone-prescribing",
    title: "CKD-MBD: Phosphate Binders, Vitamin D & Calcimimetic Prescribing",
    slugAliases: ["renal-rx-ckd-mbd-np", "renal-rx-phosphate-binders-np"],
    bodySystem: "Renal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP"],
    recognize: "CKD-MBD reflects interacting phosphate retention, altered vitamin-D metabolism, hypocalcemia signals, secondary hyperparathyroidism and bone/vascular disease. Treatment follows serial trends in calcium, phosphate and PTH—not one calcium-phosphate product or one isolated PTH value.",
    diagnostics: "Trend calcium, phosphate, PTH and alkaline phosphatase according to CKD stage and rate of change; assess 25-OH vitamin D and bone disease when clinically relevant. Before escalating PTH therapy, correct modifiable factors such as hyperphosphatemia, high phosphate intake, hypocalcemia and vitamin-D deficiency.",
    priorities: "Lower persistently elevated phosphate toward the normal range with diet/dialysis and binders when indicated, limiting calcium-based binder exposure when calcium load is undesirable. In nondialysis CKD, calcitriol/vitamin-D analogues are not used routinely and are generally reserved for severe, progressive hyperparathyroidism; dialysis patients may need calcimimetic and/or vitamin-D therapy.",
    medicationSafety: "Sevelamer and other binders must be taken with food; calcium binders can worsen hypercalcemia/calcium load. Cinacalcet can cause hypocalcemia and nausea; active vitamin-D compounds can increase calcium and phosphate.",
    redFlags: "Calciphylaxis, severe symptomatic hypocalcemia, refractory severe hyperparathyroidism, pathologic fracture or rapidly progressive vascular/soft-tissue calcification requires nephrology-level management.",
    examTraps: "Do not use a rigid calcium×phosphate product target as the central treatment rule and do not routinely prescribe calcitriol to every nondialysis patient with elevated PTH. Follow trends and CKD stage.",
    sourceKeys: ["KDIGO_CKD_MBD_CURRENT", "KDIGO_CKD_2024"],
  },
  {
    slug: "ckd-anemia-prescribing",
    title: "CKD Anemia: ESA & Iron Management",
    titleAliases: ["CKD Anemia: Erythropoiesis-Stimulating Agents & Iron Management"],
    slugAliases: ["renal-rx-ckd-anemia-epo-np"],
    bodySystem: "Renal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP"],
    recognize: "CKD anemia is commonly normocytic from inadequate erythropoietin plus absolute/functional iron restriction, inflammation and blood loss, but B12/folate deficiency, hemolysis, occult bleeding and marrow disease still require consideration. Treatment aims to improve symptoms and reduce transfusion burden without normalizing hemoglobin at all costs.",
    diagnostics: "Use CBC/reticulocyte context plus ferritin and transferrin saturation, and investigate other causes when anemia is disproportionate or atypical. The 2026 KDIGO guideline uses population-specific iron and ESA algorithms rather than one universal ferritin/TSAT or hemoglobin trigger for every CKD setting.",
    priorities: "Correct treatable iron deficiency/iron-restricted erythropoiesis first using oral or IV iron based on dialysis status, severity, tolerance and response. ESA initiation is individualized using symptoms, transfusion risk, cardiovascular/thrombotic risk, Hb trend and CKD context; use the lowest effective strategy rather than targeting normal hemoglobin.",
    medicationSafety: "ESAs increase hypertension and thromboembolic/stroke risk when used aggressively. KDIGO 2026 suggests withholding routine iron when ferritin is very high or TSAT is high rather than chasing fixed legacy targets; IV iron requires hypersensitivity and infection-context assessment.",
    redFlags: "Rapid hemoglobin fall, active bleeding, severe symptomatic anemia, ESA hyporesponsiveness with concerning systemic findings, severe hypertension or thrombosis requires urgent reassessment rather than automatic ESA escalation.",
    examTraps: "Do not use the old rigid 'ESA when Hb <10 and target 10-11.5' rule as a universal prescription. Do not interpret ferritin alone— inflammation can raise ferritin despite limited available iron.",
    sourceKeys: ["KDIGO_ANEMIA_2026"],
  },
  {
    slug: "ckd-metabolic-acidosis-prescribing",
    title: "Metabolic Acidosis in CKD: Alkali Therapy & Acid-Base Prescribing",
    titleAliases: ["Metabolic Acidosis in CKD: Bicarbonate Therapy & Acid-Base Prescribing"],
    slugAliases: ["renal-rx-acid-base-correction-np"],
    bodySystem: "Renal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "As CKD advances, reduced ammonium generation and net acid excretion can produce chronic metabolic acidosis, contributing to muscle/bone effects and possibly kidney progression. First confirm the acid-base disorder and exclude diarrhea, ketoacidosis, lactic acidosis, RTA, toxins and other causes.",
    diagnostics: "Trend serum bicarbonate in context and obtain blood gas/anion-gap analysis when the disorder is significant or mixed. The 2024 KDIGO CKD guideline no longer gives a blanket recommendation to start bicarbonate at every value below 22; it suggests considering treatment to avoid clinically important acidosis, with an example threshold below about 18 mmol/L in adults.",
    priorities: "Treat the underlying cause and consider dietary/base-producing strategies or pharmacologic alkali for persistent clinically meaningful CKD acidosis. Individualize dose to improve acidosis while monitoring BP, potassium and fluid status rather than forcing every patient into a narrow bicarbonate target.",
    medicationSafety: "Sodium bicarbonate can worsen edema or hypertension through sodium load and can cause alkalosis; sodium citrate increases aluminum absorption and should not be combined with aluminum-containing products. IV bicarbonate is reserved for selected severe acute acidemia/toxicologic indications, not routine chronic CKD.",
    redFlags: "Severe acidemia with shock, dangerous hyperkalemia, rapidly rising lactate, suspected toxic alcohol/salicylate poisoning, respiratory failure or refractory CKD acidosis requiring dialysis assessment requires emergency care.",
    examTraps: "Do not teach the legacy rule 'bicarbonate <22 = automatically start 650 mg TID.' CKD acidosis treatment is now framed around clinically important acidosis, underlying cause and treatment harms.",
    sourceKeys: ["KDIGO_CKD_2024"],
  },
  {
    slug: "ppi-stewardship-prescribing",
    title: "PPI Prescribing: Indications, Deprescribing & Long-Term Stewardship",
    titleAliases: ["PPI Prescribing: Indications, Deprescribing & Long-Term Risks"],
    slugAliases: ["gi-rx-ppi-stewardship-np"],
    bodySystem: "Gastrointestinal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "WHNP"],
    recognize: "PPIs are highly effective and generally safe when there is a valid indication such as erosive GERD, ulcer treatment/prevention in selected high-risk patients, Barrett-related acid control, eosinophilic esophagitis or hypersecretory disease. Stewardship means documenting indication and dose—not stopping useful therapy because of observational risk headlines.",
    diagnostics: "Review ongoing indication, symptom phenotype, GI-bleeding risk and alarm symptoms. Endoscopy/testing is driven by dysphagia, bleeding, weight loss, refractory symptoms and other guideline indications; routine magnesium, B12 or bone-density testing is not required solely because every patient takes a long-term PPI.",
    priorities: "Use the lowest effective regimen that controls a documented indication. Patients without a definitive chronic indication should be considered for deprescribing; most chronic twice-daily users should be considered for step-down to once daily, while severe erosive disease, peptic stricture, Barrett esophagus and other strong indications often warrant ongoing therapy.",
    medicationSafety: "Counsel that transient rebound symptoms can occur after discontinuation. AGA guidance permits either tapering or abrupt discontinuation; do not invent a mandatory taper schedule. Decisions to stop should be based on absence of indication, not fear of unproven causal links to every reported association.",
    redFlags: "GI bleeding, progressive dysphagia/odynophagia, persistent vomiting, unexplained weight loss, anemia or severe recurrent symptoms despite appropriate therapy requires diagnostic evaluation rather than endless empiric escalation.",
    examTraps: "Do not label PPIs 'dangerous long term' and stop them in a high-GI-bleed-risk patient. Do not require annual magnesium/B12/DEXA screening in every chronic user without separate risk factors.",
    sourceKeys: ["AGA_PPI_DEPRESCRIBING_2022", "AGA_GERD_PERSONALIZED_CURRENT"],
  },
  {
    slug: "h-pylori-eradication-prescribing",
    title: "H. pylori Eradication: Regimen Selection & Resistance Patterns",
    slugAliases: ["gi-rx-h-pylori-eradication-np"],
    bodySystem: "Gastrointestinal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP"],
    recognize: "H. pylori causes chronic gastritis, peptic ulcer disease and increased gastric-cancer risk. Treatment failure is increasingly driven by antibiotic resistance, so current U.S. regimens should not default to the old clarithromycin triple therapy without susceptibility evidence.",
    diagnostics: "Use urea breath or stool antigen testing for most noninvasive diagnosis and test of cure; hold PPIs/PCABs long enough before eradication testing to reduce false negatives and avoid testing while suppressive antibiotics/bismuth are still active. Endoscopic biopsy is used when endoscopy is otherwise indicated.",
    priorities: "For treatment-naïve adults when susceptibility is unknown, the 2024 ACG guideline recommends optimized bismuth quadruple therapy for 14 days; rifabutin-based triple therapy and vonoprazan-amoxicillin dual therapy are alternatives in selected patients. Confirm eradication in every treated patient.",
    medicationSafety: "Avoid empiric clarithromycin- or levofloxacin-based regimens unless susceptibility supports them. Tetracycline, metronidazole, bismuth, amoxicillin, rifabutin and acid suppression each have allergy, pregnancy, interaction and adverse-effect considerations that shape regimen choice.",
    redFlags: "Active GI bleeding, perforation, gastric-outlet obstruction, severe anemia or alarm features suggesting malignancy require urgent/endoscopic evaluation in addition to eradication therapy.",
    examTraps: "Do not repeat clarithromycin triple therapy after failure and do not assume symptom resolution means eradication. Every treated patient needs a test of cure.",
    sourceKeys: ["ACG_HPYLORI_2024"],
  },
  {
    slug: "antiemetic-selection-prescribing",
    title: "Antiemetic Selection: Mechanism, Safety & Cause-Directed Prescribing",
    slugAliases: ["gi-rx-antiemetic-selection-np", "gi-rx-nausea-vomiting-np"],
    bodySystem: "Gastrointestinal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "WHNP", "ENP"],
    recognize: "Nausea/vomiting treatment starts by identifying cause and physiology: pregnancy, gastroenteritis, obstruction, gastroparesis, vestibular disease, migraine, medication/toxin, chemotherapy or postoperative nausea require different strategies. Persistent vomiting also creates dehydration, hypokalemia and metabolic alkalosis.",
    diagnostics: "Check pregnancy status when relevant, hydration/electrolytes/renal function for significant or prolonged symptoms, ECG/QT risk when using QT-prolonging agents and targeted imaging/labs for obstruction, intracranial disease, toxicity or other red flags. A gastric-emptying study is reserved for suspected gastroparesis after mechanical obstruction is excluded.",
    priorities: "Correct the cause and volume/electrolyte deficit first, then select antiemetic class to the mechanism. Pregnancy commonly starts with pyridoxine/doxylamine; gastroparesis may use metoclopramide for the shortest effective course; chemotherapy prophylaxis follows current emetogenic-risk regimens rather than a single fixed three-drug recipe.",
    medicationSafety: "Ondansetron can prolong QT, metoclopramide carries a boxed tardive-dyskinesia warning with risk increasing with cumulative exposure, anticholinergic/antihistamine agents sedate, and dopamine antagonists can cause dystonia/EPS. The old FDA pregnancy letter categories such as 'Category A' are obsolete and should not be used for counseling.",
    redFlags: "Hematemesis, severe dehydration/AKI, bilious or feculent vomiting, peritonitis, neurologic deficit/increased ICP, pregnancy with severe weight/electrolyte loss, or toxic ingestion requires urgent cause-directed evaluation.",
    examTraps: "Do not treat every vomiting syndrome with ondansetron and miss obstruction or intracranial disease. Do not teach obsolete pregnancy letter categories or rigid chemotherapy regimens without checking the current emetogenic protocol.",
    sourceKeys: ["ACOG_NVP_CURRENT", "FDA_METOCLOPRAMIDE_CURRENT", "ASCO_ANTIEMETIC_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
