import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch49 = [
  {
    slug: "infective-endocarditis",
    title: "Infective Endocarditis",
    bodySystem: "Infectious Disease",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Persistent fever/bacteremia, new regurgitant murmur, embolic stroke/infarcts, Janeway/Osler findings, vertebral pain or unexplained systemic illness in a patient with prosthetic valve, prior IE, intracardiac device or injection drug use raises concern for infective endocarditis. Absence of a murmur does not exclude early disease.",
    diagnostics: "Obtain at least three appropriately timed blood-culture sets before antibiotics when the patient is stable and use transthoracic echo first, escalating to TEE when prosthetic valve/device, high suspicion or nondiagnostic TTE exists. Apply current Duke-ISCVID criteria while evaluating embolic/metastatic infection.",
    priorities: "Start empiric IV antibiotics after cultures in unstable/high-risk disease and tailor to organism, valve type and susceptibility for a prolonged course; involve infectious disease and cardiac surgery early for heart failure, uncontrolled infection, abscess, prosthetic complications or high embolic-risk vegetations.",
    medicationSafety: "Vancomycin/aminoglycoside strategies require renal/drug-level awareness and modern regimens minimize unnecessary aminoglycoside toxicity. Do not use oral outpatient therapy until the organism, complication profile and evidence-based transition criteria support it.",
    redFlags: "Acute valve failure/pulmonary edema, heart block/abscess, persistent bacteremia, prosthetic-valve dehiscence, recurrent emboli, stroke with hemorrhage or sepsis requires urgent inpatient surgical/ID care.",
    examTraps: "Do not start antibiotics before cultures in a stable patient and sterilize the diagnostic yield, but do not delay therapy in shock. A negative first TTE does not end evaluation when pretest probability is high.",
    sourceKeys: ["AHA_IE_CURRENT", "ESC_IE_CURRENT"],
  },
  {
    slug: "vertebral-osteomyelitis",
    title: "Vertebral Osteomyelitis & Discitis",
    bodySystem: "Infectious Disease",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Persistent focal back pain—often without fever—in a patient with bacteremia, injection drug use, diabetes, immunosuppression, dialysis or recent spinal procedure suggests vertebral osteomyelitis/discitis. New neurologic symptoms raise concern for epidural extension.",
    diagnostics: "Check ESR/CRP and blood cultures and obtain contrast MRI; when blood cultures do not identify the organism and the patient is stable, image-guided biopsy can establish microbiology before antibiotics. Evaluate endocarditis or another source when S. aureus bacteremia is present.",
    priorities: "Use culture-directed prolonged antimicrobial therapy and spinal surgery consultation for instability, neurologic deficit, large abscess, deformity or failure of medical therapy. In a stable patient without neuro compromise, delaying empiric antibiotics until cultures/biopsy can improve diagnostic yield.",
    medicationSafety: "Long antibiotic courses require renal/hepatic and drug-interaction monitoring; rifampin-based biofilm regimens are reserved for specific hardware/pathogen contexts and should not be added casually.",
    redFlags: "Neurologic deficit, bowel/bladder dysfunction, epidural abscess, sepsis, spinal instability or rapidly progressive pain requires urgent inpatient spine/ID management.",
    examTraps: "Normal WBC and absence of fever do not exclude spinal infection. Degenerative changes on a prior x-ray do not explain away new persistent severe focal pain in a bacteremia-risk patient.",
    sourceKeys: ["IDSA_VERTEBRAL_OSTEOMYELITIS_CURRENT"],
  },
  {
    slug: "bacterial-meningitis-adults",
    title: "Acute Bacterial Meningitis in Adults",
    bodySystem: "Infectious Disease",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Fever, severe headache, meningismus, photophobia or altered mental status suggests meningitis, but the classic triad is insensitive. Older adults/immunocompromised patients may present with confusion and little neck stiffness; petechiae/purpura suggests invasive meningococcal disease.",
    diagnostics: "Obtain blood cultures and perform LP promptly unless specific features require head imaging first—such as focal deficit, papilledema, severe immunocompromise, new seizure or markedly depressed consciousness. Do not delay antibiotics for CT/LP when bacterial meningitis is strongly suspected.",
    priorities: "Give prompt age/risk-appropriate empiric IV antibiotics and dexamethasone before or with the first antibiotic dose when pneumococcal meningitis is a concern; add ampicillin for Listeria-risk groups and implement droplet precautions/close-contact prophylaxis for meningococcal disease.",
    medicationSafety: "Vancomycin/cephalosporins require renal/allergy review and dosing for CNS penetration; dexamethasone benefit is timing- and pathogen-dependent. Rifampin/ciprofloxacin/ceftriaxone prophylaxis selection depends on contact, pregnancy and contraindications.",
    redFlags: "Shock, purpura fulminans, seizure/status, focal deficit, rapidly falling consciousness or raised-ICP/herniation signs requires ICU-level care.",
    examTraps: "Do not CT every patient before LP and do not wait for CSF Gram stain before starting therapy in a high-probability unstable case.",
    sourceKeys: ["IDSA_MENINGITIS_CURRENT", "CDC_MENINGOCOCCAL_CURRENT"],
  },
  {
    slug: "encephalitis-hsv",
    title: "Encephalitis & HSV Encephalitis",
    bodySystem: "Infectious Disease",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PNP", "ENP"],
    recognize: "Encephalitis is brain dysfunction with altered mental status plus fever, seizure, focal deficit or inflammatory evidence. HSV often affects temporal lobes and can cause bizarre behavior, aphasia, seizures or memory change; autoimmune encephalitis is an important mimic.",
    diagnostics: "Obtain MRI brain and CSF cell count/protein/glucose plus HSV PCR and other infectious tests according to epidemiology; EEG identifies temporal abnormalities or nonconvulsive seizures. If early HSV PCR is negative but suspicion remains high, continue acyclovir and repeat CSF testing rather than stopping solely on one early result.",
    priorities: "Start IV acyclovir immediately when HSV encephalitis is possible, treat seizures/airway/ICP, and expand antimicrobial/autoimmune testing according to presentation. Infection-control and public-health actions depend on the organism.",
    medicationSafety: "IV acyclovir causes crystal nephropathy/neurotoxicity when accumulation occurs; dose by renal function, hydrate appropriately and monitor creatinine. Empiric antibacterial therapy is added when meningitis cannot initially be distinguished.",
    redFlags: "Status epilepticus, rapidly declining consciousness, severe cerebral edema, autonomic instability or inability to protect airway requires neurocritical care.",
    examTraps: "Psychiatric-appearing behavior does not exclude encephalitis, and a normal CT does not rule it out. Do not delay acyclovir until MRI/LP results return.",
    sourceKeys: ["IDSA_ENCEPHALITIS_CURRENT"],
  },
  {
    slug: "hiv-primary-care",
    title: "HIV Diagnosis & Longitudinal Primary Care",
    bodySystem: "Infectious Disease",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "WHNP"],
    recognize: "Acute HIV may resemble mononucleosis with fever, rash, pharyngitis, diarrhea or lymphadenopathy; chronic infection may be asymptomatic. Screen all adolescents/adults according to CDC/USPSTF guidance and repeat based on ongoing exposure rather than relying on risk disclosure alone.",
    diagnostics: "Use a laboratory HIV-1/2 antigen-antibody test followed by differentiation assay and HIV RNA when acute/discordant infection is possible. At diagnosis obtain viral load, CD4, resistance genotype, hepatitis/TB/STI screening, renal/hepatic baseline and pregnancy status as appropriate.",
    priorities: "Start antiretroviral therapy rapidly for essentially all people with HIV, choosing a recommended high-barrier regimen based on resistance, HBV status, kidney function, interactions and pregnancy potential. Maintain vaccinations, cancer/STI screening, cardiovascular care and U=U counseling when viral suppression is sustained.",
    medicationSafety: "Integrase-based regimens have cation interactions and selected weight/metabolic issues; tenofovir formulations differ in renal/bone effects. Never use a two-drug regimen when HBV coinfection or other exclusion makes it inadequate, and verify interactions before adding common drugs/supplements.",
    redFlags: "Suspected opportunistic CNS/pulmonary infection, severe acute retroviral syndrome, advanced immunosuppression with fever or ART hypersensitivity/toxicity requires urgent specialty care.",
    examTraps: "A negative antibody-only test can miss acute HIV; use RNA when acute infection is suspected. A virally suppressed person does not transmit HIV sexually (U=U), but still needs longitudinal preventive care.",
    sourceKeys: ["DHHS_HIV_CURRENT", "CDC_HIV_TESTING_CURRENT"],
  },
  {
    slug: "hepatitis-b-management",
    title: "Chronic Hepatitis B Management",
    bodySystem: "Infectious Disease",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "WHNP"],
    recognize: "Chronic HBV can be asymptomatic despite ongoing fibrosis/cancer risk. Interpret HBsAg, anti-HBs and total/IgM anti-HBc together; distinguish immune, susceptible, acute, chronic and isolated-core patterns rather than calling one positive marker 'hepatitis B.'",
    diagnostics: "For chronic HBsAg positivity assess HBV DNA, ALT, HBeAg/anti-HBe, fibrosis stage, HIV/HCV/HDV coinfection and family history; screen for HCC with ultrasound ± AFP in guideline-defined high-risk groups even when cirrhosis is absent in selected populations.",
    priorities: "Treat eligible chronic HBV with high-barrier nucleos(t)ide therapy such as tenofovir or entecavir according to viral activity, ALT, fibrosis/cirrhosis, pregnancy and immunosuppression context; monitor untreated patients longitudinally because phase/activity can change.",
    medicationSafety: "Stopping HBV-active therapy can trigger severe hepatitis flare; tenofovir formulations differ in renal/bone effects. Screen HBV before major immunosuppression and provide antiviral prophylaxis for high reactivation-risk regimens rather than waiting for hepatitis.",
    redFlags: "Acute liver failure, decompensated cirrhosis, severe hepatitis flare, pregnancy with high viral load near delivery or HBV reactivation on immunosuppression requires urgent specialist care.",
    examTraps: "Anti-HBc alone does not prove active infection and HBsAg positivity does not automatically mean immediate treatment is required; treatment is based on disease phase, fibrosis and risk.",
    sourceKeys: ["AASLD_HBV_CURRENT", "CDC_HBV_CURRENT"],
  },
  {
    slug: "tuberculosis-latent-active",
    title: "Latent & Active Tuberculosis",
    bodySystem: "Infectious Disease",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PNP", "WHNP"],
    recognize: "Active pulmonary TB may cause chronic cough, fever, night sweats, weight loss or hemoptysis but can be subtle; latent infection is asymptomatic with no evidence of active disease. Exposure, birth/travel in high-incidence regions, congregate settings and immunosuppression change pretest probability.",
    diagnostics: "Use IGRA or TST for latent-infection testing in risk-based screening, then exclude active TB with symptom review/chest imaging before preventive therapy. Suspected active disease requires airborne isolation and respiratory specimens for NAAT, smear and culture with susceptibility testing.",
    priorities: "Treat latent infection with a preferred short-course rifamycin-based regimen when eligible; active TB requires multidrug therapy and public-health coordination using current CDC/ATS/IDSA recommendations and susceptibility data.",
    medicationSafety: "Rifamycins induce many CYP enzymes and interact with anticoagulants, hormonal contraception, ART and other drugs; isoniazid causes hepatotoxicity/neuropathy and needs pyridoxine in at-risk patients. Baseline/follow-up liver testing is risk-based.",
    redFlags: "Suspected contagious active TB, hemoptysis, respiratory failure, CNS TB or immunocompromised disseminated disease requires urgent isolation/infectious/public-health management.",
    examTraps: "A positive IGRA does not distinguish active from latent TB and BCG vaccination does not cause a positive IGRA. Never start 'latent TB' monotherapy before excluding active disease.",
    sourceKeys: ["CDC_TB_CURRENT", "ATS_IDSA_TB_CURRENT"],
  },
  {
    slug: "tickborne-infections",
    title: "Lyme & Severe Tickborne Infections",
    bodySystem: "Infectious Disease",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PNP", "ENP"],
    recognize: "Erythema migrans with compatible tick exposure is Lyme disease and is diagnosed clinically; fever/headache with thrombocytopenia, leukopenia/transaminitis or hyponatremia after tick exposure raises ehrlichiosis/anaplasmosis or RMSF concern. Absence of remembered tick bite or rash does not exclude severe rickettsial disease.",
    diagnostics: "Do not serologically test classic early erythema migrans because antibodies may still be negative; use standard two-tier Lyme serology for later manifestations. Severe ehrlichiosis/RMSF testing can confirm later, but treatment should begin empirically when suspected because early tests can be negative.",
    priorities: "Treat Lyme manifestations with guideline-directed doxycycline/amoxicillin/cefuroxime or IV ceftriaxone depending on organ involvement. Give doxycycline immediately for suspected RMSF/ehrlichiosis/anaplasmosis in adults and children regardless of age; delay increases mortality.",
    medicationSafety: "Short doxycycline courses are recommended in children for rickettsial disease and do not warrant delay over old tooth-staining fears. Avoid unnecessary prolonged antibiotics for persistent nonspecific symptoms after appropriately treated Lyme disease.",
    redFlags: "Meningitis/encephalitis, high-grade AV block, shock, severe thrombocytopenia/hepatitis or RMSF-compatible toxic illness requires urgent inpatient care.",
    examTraps: "Do not wait for a positive RMSF/ehrlichiosis test and do not order Lyme tests for nonspecific fatigue without compatible exposure/manifestation. A classic erythema migrans rash does not require serologic confirmation.",
    sourceKeys: ["CDC_RMSF_CURRENT", "CDC_EHRLICHIOSIS_CURRENT", "IDSA_LYME_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
