import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch1 = [
  {
    slug: "hypertension-adults",
    title: "Hypertension in Adults",
    bodySystem: "Cardiovascular",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Confirm persistent hypertension with correct technique and out-of-office readings when appropriate. Think secondary cause when onset is abrupt, severe, resistant, or accompanied by hypokalemia, renal disease, episodic symptoms, or an unusual age pattern.",
    diagnostics: "Assess global cardiovascular risk, target-organ injury, kidney function/electrolytes, diabetes and lipid status, and medication/substance contributors. The 2025 U.S. guideline uses PREVENT-CVD risk to help decide when stage 1 hypertension warrants medication.",
    priorities: "Treat the patient, not one number: address lifestyle, start evidence-based first-line therapy when indicated, and reassess for control and adverse effects. Stage 2 hypertension usually needs two complementary first-line agents unless a patient-specific reason argues otherwise.",
    medicationSafety: "ACE inhibitors/ARBs require potassium and renal-function monitoring and are avoided in pregnancy. Thiazide-type diuretics can alter sodium, potassium, uric acid, and glucose; dihydropyridine CCBs commonly cause edema.",
    redFlags: "BP >180/120 mm Hg plus acute neurologic, cardiac, renal, retinal, or aortic injury is a hypertensive emergency. Do not rapidly lower asymptomatic severe BP with IV therapy.",
    examTraps: "Do not diagnose from a rushed single office reading. The usual treatment goal is <130/80 mm Hg for most adults, but frailty, pregnancy, institutional care, and limited life expectancy change the plan.",
    sourceKeys: ["AHA_BP_2025"],
  },
  {
    slug: "dyslipidemia-prevention",
    title: "Dyslipidemia & ASCVD Prevention",
    bodySystem: "Cardiovascular",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP"],
    recognize: "Frame lipids as risk, not just an LDL value. Identify established ASCVD, severe hypercholesterolemia, diabetes, CKD, smoking, family history, and risk-enhancing conditions before choosing intensity.",
    diagnostics: "Obtain a lipid profile and calculate current U.S. cardiovascular risk when primary prevention decisions are uncertain. Consider familial hypercholesterolemia when LDL is markedly elevated or premature ASCVD clusters in a family.",
    priorities: "Use lifestyle plus statin therapy according to ASCVD status and risk; add nonstatin therapy when LDL remains above a guideline-directed threshold despite maximally tolerated statin or when statins are not tolerated.",
    medicationSafety: "Check for drug interactions and pregnancy potential before prescribing statins. New muscle symptoms warrant history, medication review, and selective CK testing rather than automatic permanent statin discontinuation.",
    redFlags: "New focal neurologic symptoms, ACS symptoms, or limb ischemia are not a lipid follow-up problem—they are acute vascular emergencies.",
    examTraps: "Do not treat triglycerides and LDL as interchangeable targets. A mildly abnormal liver enzyme value alone is not an automatic reason to avoid statin therapy.",
    sourceKeys: ["ACC_PREVENTION_CURRENT"],
  },
  {
    slug: "acute-coronary-syndrome",
    title: "Acute Coronary Syndrome",
    titleAliases: ["STEMI: Molecular & Pharmacology"],
    slugAliases: ["mi-management-np"],
    bodySystem: "Cardiovascular",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Pressure, heaviness, dyspnea, diaphoresis, nausea, or atypical ischemic symptoms in older adults and women should trigger ACS thinking. A normal first ECG does not rule it out.",
    diagnostics: "Obtain a 12-lead ECG rapidly and use serial high-sensitivity troponin with a validated pathway. Risk stratify and look for STEMI equivalents, dynamic ischemic change, shock, heart failure, and dangerous alternative diagnoses.",
    priorities: "Stabilize, give antiplatelet therapy when appropriate, control ischemia, and activate reperfusion/invasive pathways based on ECG, troponin, instability, and risk. Do not delay emergency transfer for outpatient testing.",
    medicationSafety: "Nitrates can cause dangerous hypotension with recent PDE-5 inhibitor use and are not a substitute for reperfusion. Anticoagulant and antiplatelet choices must account for bleeding risk, kidney function, and planned procedures.",
    redFlags: "Shock, refractory chest pain, malignant arrhythmia, acute pulmonary edema, mechanical complication, or ongoing ST-elevation demands immediate escalation.",
    examTraps: "Do not give oxygen routinely to a patient who is not hypoxemic. Relief with nitroglycerin does not prove that pain is cardiac.",
    sourceKeys: ["ACS_2025"],
  },
  {
    slug: "heart-failure",
    title: "Heart Failure",
    bodySystem: "Cardiovascular",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Think heart failure when dyspnea, orthopnea, edema, fatigue, elevated JVP, crackles, or rapid weight change fit a congestion/low-output pattern. Distinguish chronic stable symptoms from acute decompensation.",
    diagnostics: "Use ECG, chest imaging when indicated, natriuretic peptide testing, CMP/CBC, and echocardiography to define phenotype and precipitant. Search for ischemia, arrhythmia, infection, anemia, medication nonadherence, renal injury, and uncontrolled BP.",
    priorities: "Decongest the overloaded patient and initiate/optimize guideline-directed therapy for the heart-failure phenotype once hemodynamically appropriate. Address precipitating cause, volume plan, follow-up, and self-monitoring.",
    medicationSafety: "Loop diuretics improve congestion but do not replace disease-modifying therapy. RAAS-modifying drugs, MRAs, and SGLT2 inhibitors require renal/electrolyte awareness; beta-blockers are not newly up-titrated during shock or severe acute decompensation.",
    redFlags: "New hypoxia, hypotension, altered mentation, chest pain, oliguria, cool extremities, or rapidly worsening respiratory distress suggests acute decompensation or cardiogenic shock.",
    examTraps: "Peripheral edema alone does not diagnose heart failure. A preserved EF does not exclude clinically important heart failure.",
    sourceKeys: ["HF_ACC_AHA_CURRENT"],
  },
  {
    slug: "atrial-fibrillation",
    title: "Atrial Fibrillation",
    bodySystem: "Cardiovascular",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Irregularly irregular rhythm plus palpitations, fatigue, dyspnea, dizziness, or an incidental ECG finding suggests AF. First decide whether the patient is unstable, then address stroke risk and rate/rhythm strategy.",
    diagnostics: "Confirm with ECG and evaluate precipitating illness, electrolytes, thyroid disease, structural heart disease, ischemia, and alcohol/substance triggers as clinically indicated. Use a validated thromboembolic-risk framework.",
    priorities: "Unstable AF requires urgent synchronized cardioversion. Stable AF management balances ventricular rate, rhythm-control candidacy, anticoagulation, symptom burden, comorbidity, and patient preference.",
    medicationSafety: "DOAC dosing depends on indication, renal function, age/weight criteria, and interactions. Do not use AV-nodal blockers indiscriminately in pre-excited AF.",
    redFlags: "Hypotension, ischemic chest pain, acute pulmonary edema, shock, or severe altered mental status = unstable tachyarrhythmia.",
    examTraps: "Rate control does not remove embolic risk. A patient who converts to sinus rhythm may still need anticoagulation based on stroke risk.",
    sourceKeys: ["AF_2023"],
  },
  {
    slug: "venous-thromboembolism",
    title: "DVT & Pulmonary Embolism",
    bodySystem: "Cardiovascular",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Unilateral leg swelling/pain suggests DVT; unexplained dyspnea, pleuritic pain, tachycardia, syncope, or hypoxemia raises PE concern. Start with pretest probability, not a blanket D-dimer.",
    diagnostics: "Use a validated clinical probability pathway. D-dimer is useful mainly when pretest probability is low/intermediate; definitive imaging depends on the suspected site, probability, contraindications, and pregnancy context.",
    priorities: "Anticoagulate confirmed VTE unless contraindicated; consider empiric anticoagulation when suspicion is high and imaging is delayed if bleeding risk is acceptable. Determine provoked vs unprovoked status and follow-up duration strategy.",
    medicationSafety: "Anticoagulants differ in renal clearance, interactions, pregnancy safety, reversibility, and initial-treatment requirements. Estrogen-containing contraception is generally avoided in patients with significant VTE risk/history.",
    redFlags: "Shock, syncope with hypotension, severe hypoxemia, RV strain with deterioration, phlegmasia, or threatened limb requires emergency escalation.",
    examTraps: "A positive D-dimer does not diagnose PE. A normal pulse oximetry reading does not exclude PE.",
    sourceKeys: ["CHEST_VTE_CURRENT"],
  },
  {
    slug: "asthma",
    title: "Asthma",
    bodySystem: "Respiratory",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PNP", "ENP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP"],
    recognize: "Variable wheeze, cough, dyspnea, and chest tightness—especially with triggers or nocturnal variation—suggest asthma. Objective variable expiratory airflow limitation strengthens the diagnosis.",
    diagnostics: "Use spirometry with bronchodilator response when feasible; repeat or use alternative objective testing if symptoms are suggestive but spirometry is nondiagnostic. Assess control, exacerbation history, inhaler technique, adherence, exposures, and comorbidity.",
    priorities: "Use an ICS-containing strategy; current GINA guidance does not recommend SABA-only treatment for asthma. Step therapy up or down only after checking diagnosis, adherence, technique, and modifiable triggers.",
    medicationSafety: "Teach device technique. Excess SABA use signals poor control; systemic corticosteroids carry cumulative toxicity, and LABA should not be used without ICS in asthma.",
    redFlags: "Silent chest, exhaustion, cyanosis, altered mental status, inability to speak, rising CO2, or poor response to initial bronchodilator therapy suggests life-threatening asthma.",
    examTraps: "Do not label every recurrent cough as asthma. Normal spirometry between episodes does not automatically exclude asthma.",
    sourceKeys: ["GINA_2026"],
  },
  {
    slug: "copd",
    title: "COPD",
    titleAliases: ["COPD: Cellular Mechanisms"],
    slugAliases: ["copd-exacerbation-np"],
    bodySystem: "Respiratory",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Progressive dyspnea, chronic cough/sputum, exposure history, and recurrent lower-respiratory events suggest COPD, but symptoms alone are not diagnostic.",
    diagnostics: "Confirm persistent airflow obstruction with post-bronchodilator spirometry. Then assess symptom burden, exacerbation history, eosinophils when relevant to inhaled-corticosteroid decisions, smoking/exposure, oxygenation, and comorbidity.",
    priorities: "Smoking cessation, vaccination, pulmonary rehabilitation, and long-acting bronchodilator therapy are foundational. Exacerbations need severity assessment, bronchodilators, short systemic steroids when indicated, and selective antibiotics.",
    medicationSafety: "ICS is not automatically first-line monotherapy in COPD and increases pneumonia risk in some patients. Check inhaler technique and avoid duplicative long-acting drug classes.",
    redFlags: "New severe hypoxemia, hypercapnic encephalopathy, hemodynamic instability, inability to protect airway, or suspected pneumothorax/PE requires emergency care.",
    examTraps: "Do not diagnose COPD without spirometry. Chronic dyspnea can also be heart failure, anemia, ILD, PE, deconditioning, or medication effect.",
    sourceKeys: ["GOLD_2026"],
  }
] as const satisfies readonly UsNpCramLesson[];
