import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch15 = [
  {
    slug: "interstitial-lung-disease",
    title: "Interstitial Lung Disease",
    bodySystem: "Respiratory",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP"],
    recognize: "Progressive exertional dyspnea, dry cough, fine inspiratory crackles, clubbing, restrictive physiology, autoimmune disease, occupational exposure, or culprit medication should raise concern for ILD rather than recurrent bronchitis.",
    diagnostics: "Use high-resolution CT, pulmonary function tests with diffusion capacity, oxygen assessment, exposure and medication history, and autoimmune testing when clinically suggested. Multidisciplinary pulmonary-radiology-pathology review can avoid unnecessary biopsy.",
    priorities: "Remove offending exposures or drugs, treat the specific inflammatory or fibrotic phenotype, use pulmonary rehabilitation and oxygen when indicated, vaccinate appropriately, and refer early for progressive fibrotic disease or transplant consideration.",
    medicationSafety: "Antifibrotic and immunosuppressive therapies have hepatic, GI, bleeding, infection, pregnancy, and interaction risks and are not interchangeable across ILD subtypes. Avoid prolonged empiric steroids in unclassified fibrotic disease without specialist reasoning.",
    redFlags: "Rapidly worsening hypoxemia, new diffuse infiltrates, pneumothorax, acute exacerbation, or severe pulmonary hypertension requires urgent hospital or specialty management.",
    examTraps: "Do not diagnose idiopathic pulmonary fibrosis before excluding exposure, autoimmune, medication, and other causes. A normal chest x-ray does not exclude early ILD.",
    sourceKeys: ["ATS_ERS_ILD_CURRENT"],
  },
  {
    slug: "pulmonary-hypertension",
    title: "Pulmonary Hypertension",
    bodySystem: "Respiratory",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Progressive exertional dyspnea, fatigue, exertional presyncope or syncope, chest pressure, loud P2, RV heave, edema, or unexplained hypoxemia may indicate pulmonary hypertension, but the cause can be left-heart, lung, thromboembolic, or pulmonary arterial disease.",
    diagnostics: "Echocardiography estimates probability and RV impact; definitive classification often requires right-heart catheterization. Evaluate PFTs, sleep-disordered breathing, VTE history, V/Q imaging for chronic thromboembolic disease, autoimmune disease, HIV, liver disease, and left-heart disease.",
    priorities: "Treat the underlying group-specific cause, optimize oxygenation and volume, and refer suspected pulmonary arterial or chronic thromboembolic disease to an experienced center before starting targeted vasodilator therapy.",
    medicationSafety: "Pulmonary vasodilators can worsen pulmonary edema or V/Q mismatch when used in the wrong PH group. Endothelin-receptor antagonists and several agents carry hepatic, hypotension, pregnancy, and interaction precautions.",
    redFlags: "Syncope, hypotension, severe hypoxemia, escalating edema with RV failure, chest pain, or rapid functional decline requires urgent specialty or inpatient evaluation.",
    examTraps: "Elevated pulmonary pressure on echo is not the final diagnosis or WHO group. Do not start PAH-specific medication before defining the mechanism.",
    sourceKeys: ["ESC_ERS_PH_CURRENT", "CHEST_PH_CURRENT"],
  },
  {
    slug: "pneumothorax",
    title: "Pneumothorax",
    bodySystem: "Respiratory",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Sudden pleuritic chest pain and dyspnea with unilateral reduced breath sounds suggests pneumothorax; risk rises with tall thin young patients, COPD, cystic lung disease, trauma, procedures, or mechanical ventilation.",
    diagnostics: "Bedside ultrasound or chest radiography confirms most stable cases; CT is reserved for uncertainty or complex disease. In suspected tension physiology, treatment should not wait for imaging.",
    priorities: "Observe selected small stable pneumothoraces with appropriate follow-up, aspirate or drain when size, symptoms or secondary disease warrants, and immediately decompress tension pneumothorax before definitive chest drainage.",
    medicationSafety: "High-flow oxygen is not automatically benign in all COPD or hypercapnic patients; titrate to physiology. Positive-pressure ventilation can rapidly convert an existing pneumothorax to tension physiology.",
    redFlags: "Hypotension, severe respiratory distress, tracheal shift, distended neck veins, worsening hypoxemia, or pneumothorax on positive-pressure ventilation requires immediate decompression.",
    examTraps: "Do not wait for mediastinal shift on x-ray to diagnose tension pneumothorax. A small primary pneumothorax and a similar-sized secondary pneumothorax do not carry the same risk.",
    sourceKeys: ["BTS_PNEUMOTHORAX_CURRENT", "ACEP_PNEUMOTHORAX_CURRENT"],
  },
  {
    slug: "pleural-effusion",
    title: "Pleural Effusion",
    bodySystem: "Respiratory",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP"],
    recognize: "Dyspnea, pleuritic discomfort, reduced breath sounds, dullness to percussion, or an incidental fluid layer can represent transudative or exudative effusion from heart failure, infection, malignancy, PE, liver disease, or other causes.",
    diagnostics: "Use chest imaging and ultrasound to define size and loculation. Diagnostic thoracentesis is indicated for many new unexplained effusions; analyze protein, LDH, cell count, pH/glucose, Gram stain/culture, cytology, and targeted studies according to context.",
    priorities: "Treat the cause, drain symptomatic large effusions and complicated parapneumonic collections, and refer recurrent malignant or unexplained effusions for pulmonary evaluation and definitive management.",
    medicationSafety: "Anticoagulation and platelet status affect procedural planning but should be individualized rather than applying arbitrary absolute cutoffs. Avoid overly rapid large-volume drainage when re-expansion risk is high.",
    redFlags: "Empyema, respiratory compromise, rapidly enlarging fluid, tension hydrothorax, or malignancy-associated recurrent severe dyspnea requires urgent drainage-capable care.",
    examTraps: "Do not assume every bilateral effusion in heart failure needs thoracentesis; atypical features change the threshold. A normal BNP does not alone classify pleural fluid.",
    sourceKeys: ["ATS_PLEURAL_CURRENT", "BTS_PLEURAL_CURRENT"],
  },
  {
    slug: "bronchiectasis",
    title: "Bronchiectasis",
    bodySystem: "Respiratory",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP"],
    recognize: "Chronic productive cough with daily sputum, recurrent pneumonia, hemoptysis, crackles, or resistant airway organisms suggests bronchiectasis. Consider cystic fibrosis, immune deficiency, aspiration, NTM, autoimmune disease, and prior severe infection.",
    diagnostics: "High-resolution CT confirms bronchial dilation. Obtain sputum cultures during stable disease and exacerbations, PFTs, and targeted testing for underlying causes such as immunoglobulins, ABPA, CF, ciliary disease, or aspiration.",
    priorities: "Airway-clearance therapy is foundational, with culture-directed antibiotics for exacerbations and specialist consideration of long-term macrolide or inhaled antibiotic strategies in selected frequent exacerbators.",
    medicationSafety: "Long-term macrolides require QT, hearing, interaction, and NTM screening awareness. Routine inhaled corticosteroids are not indicated unless another condition such as asthma or COPD supports them.",
    redFlags: "Massive hemoptysis, severe hypoxemia, sepsis, rapidly worsening respiratory failure, or recurrent focal infection suggesting obstruction requires urgent evaluation.",
    examTraps: "Do not repeatedly treat chronic sputum as simple acute bronchitis without imaging when the pattern is recurrent. A negative routine culture does not exclude NTM disease.",
    sourceKeys: ["ERS_BRONCHIECTASIS_CURRENT", "CHEST_BRONCHIECTASIS_CURRENT"],
  },
  {
    slug: "alpha1-antitrypsin-deficiency",
    title: "Alpha-1 Antitrypsin Deficiency",
    bodySystem: "Respiratory",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP"],
    recognize: "Early or disproportionate emphysema, basilar-predominant disease, minimal smoking exposure, unexplained liver disease, necrotizing panniculitis, or family history should trigger alpha-1 antitrypsin deficiency testing.",
    diagnostics: "Measure serum alpha-1 antitrypsin level and confirm abnormal or discordant results with genotype or phenotype testing. Assess spirometry, diffusion, liver disease, smoking exposure, and family implications.",
    priorities: "Eliminate smoking and inhalational exposures, use standard COPD therapy when obstructive disease exists, vaccinate against respiratory and liver infections as indicated, and refer appropriate severe deficient phenotypes for augmentation-therapy evaluation.",
    medicationSafety: "Augmentation therapy is not a substitute for smoking cessation and is not indicated for every genotype or liver-predominant presentation. Review alcohol and hepatotoxic medication exposure in liver disease.",
    redFlags: "Rapid respiratory decline, severe hypoxemia, decompensated liver disease, variceal bleeding, or acute hepatic failure requires urgent specialty care.",
    examTraps: "Do not limit testing to young nonsmokers; guidelines support testing adults with persistent COPD and other suggestive disease. A serum level alone can be misleading during acute inflammation.",
    sourceKeys: ["COPD_FOUNDATION_A1AT_CURRENT", "ATS_A1AT_CURRENT"],
  },
  {
    slug: "sarcoidosis",
    title: "Sarcoidosis",
    bodySystem: "Respiratory",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP"],
    recognize: "Bilateral hilar adenopathy, pulmonary symptoms, erythema nodosum, uveitis, hypercalcemia, cranial neuropathy, conduction disease, or unexplained multisystem granulomatous findings can suggest sarcoidosis after infection and malignancy are considered.",
    diagnostics: "Use chest imaging, PFTs, ECG, eye assessment, calcium and organ-specific testing. Tissue showing noncaseating granulomas supports diagnosis when needed, but biopsy site and necessity depend on classic presentation and exclusion of mimics such as TB, fungi and lymphoma.",
    priorities: "Observe asymptomatic stable disease when appropriate; treat organ-threatening, progressive pulmonary, ocular, neurologic, cardiac or significant symptomatic disease with corticosteroids or steroid-sparing specialist therapy.",
    medicationSafety: "Long-term glucocorticoids require bone, glucose, infection and adrenal-suppression planning. Vitamin D or calcium supplementation can worsen hypercalcemia in susceptible sarcoidosis and should not be prescribed reflexively.",
    redFlags: "Syncope or heart block, ventricular arrhythmia, vision-threatening uveitis, severe hypercalcemia, neurosarcoidosis, or respiratory failure requires urgent specialty evaluation.",
    examTraps: "An elevated ACE level is neither sensitive nor specific enough to diagnose sarcoidosis. Noncaseating granulomas are not unique to sarcoidosis.",
    sourceKeys: ["ATS_SARCOIDOSIS_CURRENT"],
  },
  {
    slug: "hemoptysis",
    title: "Hemoptysis",
    bodySystem: "Respiratory",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Confirm true lower-airway blood versus epistaxis or hematemesis, then assess volume, respiratory reserve and cause. Infection, malignancy, bronchiectasis, PE, TB, anticoagulation, vascular lesions and autoimmune pulmonary hemorrhage are key differentials.",
    diagnostics: "Assess CBC, coagulation, renal function, chest imaging and CT angiography or bronchoscopy according to severity and suspected source. Consider urinalysis and autoimmune testing when pulmonary-renal syndrome is possible.",
    priorities: "Protect the airway, position significant unilateral bleeding with the bleeding lung dependent when known, reverse major coagulopathy when appropriate, and involve interventional radiology/pulmonology for significant or recurrent bleeding.",
    medicationSafety: "Anticoagulants and antiplatelets require individualized interruption or reversal based on bleed severity and thrombosis risk. Avoid suppressing cough aggressively when airway clearance of blood is needed.",
    redFlags: "Airway compromise, hypoxemia, hemodynamic instability, rapid ongoing bleeding, falling hemoglobin, or significant blood with limited cardiopulmonary reserve requires emergency care.",
    examTraps: "Severity is defined by physiologic threat, not a memorized milliliter cutoff alone. A normal chest x-ray does not exclude lung cancer, bronchiectasis, PE, or other important causes.",
    sourceKeys: ["CHEST_HEMOPTYSIS_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
