import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch21 = [
  {
    slug: "adult-seizure-epilepsy",
    title: "Adult Seizure & Epilepsy",
    bodySystem: "Neurological",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PMHNP", "ENP"],
    recognize: "Determine whether the event was epileptic versus syncope, psychogenic nonepileptic event, metabolic spell or movement disorder. Focal onset, tongue bite, witnessed tonic-clonic activity, postictal confusion and stereotyped recurrence support seizure.",
    diagnostics: "Check glucose and provoking causes acutely, obtain ECG, electrolytes and pregnancy testing when relevant, and arrange EEG plus brain MRI for a first unprovoked seizure when indicated. Toxicology or lumbar puncture is targeted to exposure or infection concern.",
    priorities: "Treat prolonged seizure promptly, correct reversible causes, counsel on driving and safety, and refer first unprovoked or recurrent seizures to neurology. Chronic antiseizure therapy depends on recurrence risk, seizure type and patient preferences.",
    medicationSafety: "Antiseizure drugs differ in pregnancy teratogenicity, mood effects, hepatic/renal handling and interactions. Valproate has major reproductive risk; abrupt withdrawal of chronic therapy can precipitate seizures.",
    redFlags: "Status epilepticus, persistent focal deficit, meningismus, pregnancy with seizure, major trauma, severe metabolic abnormality or prolonged failure to recover requires emergency care.",
    examTraps: "A normal EEG does not exclude epilepsy. Do not prescribe lifelong antiseizure therapy automatically after every single provoked seizure.",
    sourceKeys: ["AAN_EPILEPSY_CURRENT", "AES_CURRENT"],
  },
  {
    slug: "intracerebral-hemorrhage",
    title: "Spontaneous Intracerebral Hemorrhage",
    bodySystem: "Neurological",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Sudden focal deficit, severe headache, vomiting, depressed consciousness or very high BP can represent intracerebral hemorrhage. Anticoagulant use, hypertension, cerebral amyloid angiopathy and vascular malformation increase risk.",
    diagnostics: "Obtain emergent noncontrast head CT, then vascular imaging when aneurysm/AVM or atypical location/age is suspected. Check CBC, coagulation, renal function, glucose and medication timing without delaying reversal or neurocritical care.",
    priorities: "Stabilize airway, manage BP using guideline targets, reverse anticoagulation rapidly, control ICP or hydrocephalus when present and obtain neurosurgical/neurocritical consultation for eligible hematomas.",
    medicationSafety: "Use agent-specific anticoagulant reversal when available; platelet transfusion is not routine for spontaneous antiplatelet-associated ICH absent a specific indication. Avoid hypotension from overly aggressive BP reduction.",
    redFlags: "Declining GCS, brainstem/cerebellar hemorrhage, hydrocephalus, herniation, rapidly expanding hematoma or refractory hypertension requires immediate neurocritical/neurosurgical care.",
    examTraps: "Do not give thrombolysis for presumed ischemic stroke before imaging excludes hemorrhage. Headache may be absent, so focal deficit alone still requires emergent imaging.",
    sourceKeys: ["AHA_ICH_CURRENT"],
  },
  {
    slug: "subarachnoid-hemorrhage",
    title: "Subarachnoid Hemorrhage",
    bodySystem: "Neurological",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Thunderclap headache reaching maximal intensity within seconds to minutes, especially with vomiting, neck stiffness, syncope or neurologic deficit, is SAH until excluded even when the patient looks better later.",
    diagnostics: "Use emergent noncontrast CT; if negative and suspicion remains, proceed according to timing and local pathway with lumbar puncture and/or CT angiography. Identify aneurysm anatomy with vascular imaging after hemorrhage is diagnosed.",
    priorities: "Stabilize, control BP without causing ischemia, give nimodipine after aneurysmal SAH, secure the aneurysm promptly and monitor for hydrocephalus, vasospasm/delayed cerebral ischemia and sodium abnormalities.",
    medicationSafety: "Anticoagulants require urgent reversal. Nimodipine can cause hypotension but is continued when feasible because it reduces delayed ischemic complications; avoid routine prophylactic hypervolemia.",
    redFlags: "Declining consciousness, recurrent sudden headache, focal deficit, hydrocephalus, seizure, arrhythmia or hemodynamic instability requires immediate neurocritical care.",
    examTraps: "A normal neurologic exam does not make thunderclap headache benign. Migraine history should not stop a first or worst sudden headache workup.",
    sourceKeys: ["AHA_ASAH_CURRENT"],
  },
  {
    slug: "parkinson-disease",
    title: "Parkinson Disease",
    bodySystem: "Neurological",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PMHNP"],
    recognize: "Bradykinesia plus rest tremor or rigidity, reduced arm swing, shuffling gait and nonmotor constipation, anosmia, REM sleep behavior, depression or autonomic symptoms suggests parkinsonism. Early falls, gaze palsy or symmetric onset suggests atypical disease.",
    diagnostics: "Diagnosis is clinical; MRI or dopamine-transporter imaging is selective when the phenotype is atypical or uncertain. Review dopamine-blocking drugs and vascular or normal-pressure-hydrocephalus mimics.",
    priorities: "Use exercise, PT/OT/speech support and dopaminergic therapy matched to symptom burden, age and function. Address orthostasis, constipation, swallowing, mood, cognition and driving while coordinating neurology care.",
    medicationSafety: "Levodopa can cause nausea, orthostasis, dyskinesia and hallucinations; dopamine agonists can cause impulse-control disorders and sleep attacks. Abrupt dopaminergic withdrawal can trigger a malignant syndrome.",
    redFlags: "Acute inability to swallow medication, severe aspiration, psychosis with danger, recurrent syncope, sudden marked decline or hyperpyrexia/rigidity after medication interruption requires urgent evaluation.",
    examTraps: "Tremor is not required for Parkinson disease. Antipsychotics that strongly block dopamine can dramatically worsen motor symptoms.",
    sourceKeys: ["AAN_PARKINSON_CURRENT"],
  },
  {
    slug: "multiple-sclerosis",
    title: "Multiple Sclerosis",
    bodySystem: "Neurological",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "WHNP"],
    recognize: "Episodes of optic neuritis, sensory loss, weakness, diplopia, ataxia, bladder dysfunction or other CNS deficits separated in time and space suggest MS, especially in younger adults. Peripheral neuropathy alone is not typical.",
    diagnostics: "Use brain/spinal MRI with characteristic lesions and CSF oligoclonal bands when needed to meet current diagnostic criteria and exclude mimics such as B12 deficiency, NMOSD, MOG disease, infection and vascular disease.",
    priorities: "Treat significant acute relapses with high-dose corticosteroids when indicated and initiate disease-modifying therapy early through neurology based on phenotype, pregnancy plans, risk tolerance and monitoring requirements.",
    medicationSafety: "Disease-modifying agents vary in infection, malignancy, liver, marrow, cardiac and fetal risk; vaccination and latent-infection screening should occur before selected immunosuppressive therapies.",
    redFlags: "Severe new weakness, respiratory compromise, acute vision loss, transverse myelitis, urinary retention with neurologic deficit or serious infection on immunotherapy requires urgent evaluation.",
    examTraps: "Heat-related temporary worsening is not automatically a new inflammatory relapse. MRI white-matter lesions in migraine or aging are not sufficient by themselves for MS.",
    sourceKeys: ["AAN_MS_CURRENT"],
  },
  {
    slug: "peripheral-neuropathy",
    title: "Peripheral Neuropathy Evaluation",
    bodySystem: "Neurological",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PMHNP"],
    recognize: "Length-dependent numbness, burning, paresthesias and reduced ankle reflexes suggest distal polyneuropathy; asymmetric, motor-predominant, rapidly progressive or proximal patterns raise concern for vasculitis, inflammatory neuropathy, entrapment or other neurologic disease.",
    diagnostics: "Check diabetes/A1C, B12, SPEP with immunofixation and other targeted labs based on pattern; medication, alcohol, chemotherapy and family history matter. EMG/NCS is useful for atypical, motor, rapidly progressive or diagnostically uncertain cases.",
    priorities: "Treat the cause, optimize foot/fall safety and use evidence-based neuropathic pain therapies. Refer rapidly progressive, motor-predominant, autonomic or demyelinating patterns to neurology.",
    medicationSafety: "Gabapentinoids require renal dosing and increase sedation/falls; duloxetine has hepatic/interaction considerations; TCAs carry anticholinergic and conduction risks. Chronic opioids are generally poor long-term neuropathy therapy.",
    redFlags: "Rapid ascending weakness, respiratory symptoms, new bowel/bladder dysfunction, severe autonomic instability, foot infection or acute asymmetric vasculitic neuropathy requires urgent evaluation.",
    examTraps: "Do not attribute every neuropathy in a patient with diabetes to diabetes. Small-fiber neuropathy can have normal routine nerve-conduction studies.",
    sourceKeys: ["AAN_POLYNEUROPATHY_CURRENT"],
  },
  {
    slug: "bell-palsy",
    title: "Bell Palsy",
    bodySystem: "Neurological",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PNP", "ENP"],
    recognize: "Acute unilateral lower motor neuron facial weakness involving forehead and lower face suggests Bell palsy when no other neurologic deficit exists. Forehead sparing raises concern for central lesion such as stroke.",
    diagnostics: "Diagnosis is clinical after checking ear/vesicle findings, Lyme exposure, parotid mass, trauma and neurologic exam. Routine imaging and labs are unnecessary in typical cases but required for atypical, recurrent or progressive patterns.",
    priorities: "Start oral corticosteroid promptly, protect the cornea with lubrication/taping when eye closure is impaired, and consider antiviral therapy in selected severe cases. Arrange follow-up for incomplete recovery.",
    medicationSafety: "Steroids require diabetes, infection and pregnancy-context review. Antivirals are adjunctive rather than a substitute for steroids in typical adult Bell palsy.",
    redFlags: "Other focal neurologic deficits, severe headache, altered mental status, vesicular ear rash with hearing/vestibular symptoms, recurrent bilateral disease or progressive weakness requires urgent alternate-diagnosis evaluation.",
    examTraps: "Do not call forehead-sparing facial weakness Bell palsy. Lyme-associated facial palsy can be bilateral and may require disease-specific treatment.",
    sourceKeys: ["AAO_HNS_BELL_CURRENT", "AAN_BELL_CURRENT"],
  },
  {
    slug: "vertigo-bppv-vestibular-neuritis",
    title: "Vertigo, BPPV & Vestibular Neuritis",
    bodySystem: "Neurological",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "ENP"],
    recognize: "Brief position-triggered spinning suggests BPPV; continuous acute vertigo over hours-days with nausea and gait imbalance suggests vestibular neuritis, but posterior-circulation stroke can mimic peripheral vestibular disease.",
    diagnostics: "Use timing/triggers, neurologic exam and positional testing such as Dix-Hallpike for posterior-canal BPPV. HINTS is useful only in the correct continuous acute vestibular syndrome and when performed by trained clinicians; image central red flags.",
    priorities: "Treat BPPV with canalith-repositioning maneuvers, minimize prolonged vestibular suppressants, and use short-term symptom control/vestibular rehabilitation for neuritis. Escalate possible central vertigo immediately.",
    medicationSafety: "Meclizine and benzodiazepines can sedate, worsen falls and delay vestibular compensation when used chronically. Steroids for neuritis have uncertain/selected benefit and require patient-specific risk review.",
    redFlags: "New focal deficit, severe truncal ataxia, inability to walk, new severe headache/neck pain, vertical or direction-changing nystagmus, hearing loss with neurologic signs or vascular high risk requires stroke evaluation.",
    examTraps: "Do not diagnose BPPV from the word dizziness alone. A normal head CT is poor at excluding early posterior-fossa ischemic stroke.",
    sourceKeys: ["AAO_HNS_BPPV_CURRENT", "AHA_POSTERIOR_STROKE_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
