import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch10 = [
  {
    slug: "bph-luts",
    title: "Benign Prostatic Hyperplasia & LUTS",
    bodySystem: "Genitourinary",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "Hesitancy, weak stream, incomplete emptying, nocturia, frequency, and urgency suggest lower urinary tract symptoms from BPH, but infection, medications, neurologic disease, prostate cancer, and urethral stricture belong in the differential.",
    diagnostics: "Use symptom severity, medication review, urinalysis, focused exam, and selective post-void residual/PSA based on clinical context and shared decision-making. Creatinine/imaging are not routine unless retention or renal risk exists.",
    priorities: "Use behavioral measures for mild symptoms; alpha blockers improve flow quickly, while 5-alpha-reductase inhibitors are useful for appropriately enlarged prostates and reduce progression over time. Refer for retention, recurrent complications, or refractory symptoms.",
    medicationSafety: "Alpha blockers can cause orthostasis and interact with other BP-lowering drugs; 5-alpha-reductase inhibitors reduce PSA and change interpretation. Sexual adverse effects should be discussed before treatment.",
    redFlags: "Acute urinary retention, fever with obstruction, gross hematuria with clots, hydronephrosis/renal injury, or neurologic retention requires urgent evaluation.",
    examTraps: "Do not assume every older man with frequency has BPH. Anticholinergics, decongestants, diuretics, diabetes, sleep apnea, and overactive bladder can mimic or worsen symptoms.",
    sourceKeys: ["AUA_BPH_CURRENT"],
  },
  {
    slug: "erectile-dysfunction",
    title: "Erectile Dysfunction",
    bodySystem: "Genitourinary",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "Persistent difficulty achieving or maintaining an erection can be vascular, neurologic, hormonal, medication-related, psychogenic, or mixed. ED may be an early marker of cardiovascular disease.",
    diagnostics: "Assess morning/nocturnal erections, libido, relationship factors, diabetes/CVD risk, medications, substance use, and genital exam. Morning testosterone is appropriate when hypogonadism is suspected; broad hormone panels are not routine.",
    priorities: "Address reversible causes and cardiovascular risk, then use PDE-5 inhibitors when appropriate. Refer for penile deformity, refractory ED, complex endocrine disease, or consideration of devices, injections, or surgery.",
    medicationSafety: "PDE-5 inhibitors are contraindicated with nitrates and require caution with significant hypotension and alpha blockers. CYP interactions and renal/hepatic function can affect dosing.",
    redFlags: "Priapism, penile fracture, or ED accompanied by unstable cardiac symptoms requires urgent care; new ED with severe exertional symptoms warrants cardiovascular evaluation before sexual activity.",
    examTraps: "Do not prescribe testosterone for ED without evidence of hypogonadism. Nitrate use is an absolute board-style safety issue with PDE-5 inhibitors.",
    sourceKeys: ["AUA_ED_CURRENT"],
  },
  {
    slug: "prostate-cancer-screening",
    title: "Prostate Cancer Screening",
    bodySystem: "Oncology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "Prostate cancer screening is preference-sensitive: balance age, life expectancy, family history, ancestry, prior PSA, comorbidity, and the downstream risks of biopsy and overtreatment.",
    diagnostics: "Use shared decision-making for PSA screening in eligible patients. Repeat an unexpected elevation before invasive workup when clinically appropriate and review infection, instrumentation, urinary retention, ejaculation, and medications that affect PSA.",
    priorities: "Refer persistent or risk-adjusted PSA abnormalities or concerning exam findings to urology; use risk calculators, MRI, biomarkers, and biopsy selectively within contemporary pathways.",
    medicationSafety: "5-alpha-reductase inhibitors lower PSA and change interpretation. Do not treat an elevated PSA with empiric antibiotics in an asymptomatic patient simply to see whether it falls.",
    redFlags: "Spinal cord compression symptoms, pathologic fracture, urinary obstruction with renal injury, or severe metastatic pain requires urgent evaluation.",
    examTraps: "PSA is not a cancer diagnosis, and a normal PSA does not absolutely exclude cancer. Screening benefit falls when life expectancy is limited.",
    sourceKeys: ["AUA_PROSTATE_EARLY_DETECTION_CURRENT", "USPSTF_PROSTATE_CURRENT"],
  },
  {
    slug: "breast-mass-screening",
    title: "Breast Mass & Screening",
    bodySystem: "Reproductive",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "WHNP"],
    recognize: "A new breast lump, focal thickening, spontaneous unilateral bloody or serous nipple discharge, skin dimpling, or persistent focal change requires diagnostic evaluation regardless of recent screening.",
    diagnostics: "Distinguish screening from diagnostic imaging. Use age- and risk-appropriate mammography or ultrasound, and refer for biopsy when imaging or exam is suspicious. Perform formal risk assessment when strong family history or high-risk features exist.",
    priorities: "Keep average-risk screening current and use enhanced MRI or genetic pathways for selected high-risk patients. A palpable abnormality with negative initial imaging may still need specialist follow-up.",
    medicationSafety: "Review exogenous hormones and medications associated with breast symptoms, but do not stop necessary therapy without assessing the actual lesion and risk.",
    redFlags: "Inflammatory breast changes not responding quickly to appropriate treatment, fixed mass, peau d'orange, suspicious nodes, or pregnancy-associated concerning mass needs expedited breast evaluation.",
    examTraps: "Do not reassure a new palpable mass because last year's mammogram was normal. Screening mammography is not the correct workup for a symptomatic lump.",
    sourceKeys: ["USPSTF_BREAST_2024", "ACR_BREAST_CURRENT"],
  },
  {
    slug: "cervical-cancer-screening",
    title: "Cervical Cancer Screening & Abnormal Results",
    bodySystem: "Reproductive",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "WHNP"],
    recognize: "Screening strategy depends on age, prior results, HPV testing method, immunosuppression, DES exposure, and history of high-grade disease; hysterectomy status alone is not enough information.",
    diagnostics: "Use current cervical screening intervals and risk-based management for abnormal HPV or cytology rather than memorizing one follow-up for every result. Verify whether the cervix remains after hysterectomy.",
    priorities: "Ensure HPV vaccination, smoking cessation, and appropriate colposcopy or surveillance after abnormalities. Patients treated for high-grade precancer require prolonged surveillance.",
    medicationSafety: "HPV vaccine prevents new infection but does not treat existing dysplasia. Pregnancy changes some diagnostic and treatment steps but does not eliminate indicated evaluation.",
    redFlags: "Gross cervical lesion, unexplained postcoital bleeding, persistent abnormal bleeding, or invasive cancer concern requires diagnostic gynecologic evaluation rather than routine screening.",
    examTraps: "Do not perform screening in a patient with symptoms and call it adequate evaluation. Prior CIN2+ changes when screening can stop.",
    sourceKeys: ["ASCCP_CURRENT", "USPSTF_CERVICAL_CURRENT", "CDC_HPV_CURRENT"],
  },
  {
    slug: "polycystic-ovary-syndrome",
    title: "Polycystic Ovary Syndrome",
    bodySystem: "Reproductive",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "WHNP"],
    recognize: "Irregular ovulation, clinical or biochemical hyperandrogenism, acne or hirsutism, and polycystic ovarian morphology can support PCOS after excluding important mimics. Obesity is common but not required.",
    diagnostics: "Exclude pregnancy, thyroid disease, hyperprolactinemia, nonclassic CAH, and other androgen-excess causes when appropriate. Screen BP, glucose tolerance or diabetes risk, lipids, sleep apnea, mood, and endometrial risk.",
    priorities: "Match treatment to goals: cycle or endometrial protection, hirsutism and acne control, metabolic health, and fertility. Lifestyle support is useful at any weight; fertility treatment should be evidence-based rather than delaying care indefinitely for weight loss.",
    medicationSafety: "Combined hormonal contraception is useful when eligible; antiandrogens require reliable contraception because of fetal risk. Metformin is particularly useful for metabolic indications and selected ovulatory goals.",
    redFlags: "Rapid virilization, very high androgen levels, severe pelvic pain, or prolonged amenorrhea with heavy bleeding or endometrial risk requires expedited evaluation.",
    examTraps: "An ultrasound is not mandatory to diagnose every adult with PCOS, and 'cysts' are not the same as ovarian cyst disease. Do not diagnose PCOS in adolescents from irregular cycles alone.",
    sourceKeys: ["PCOS_INTERNATIONAL_2023", "ACOG_PCOS_CURRENT"],
  },
  {
    slug: "endometriosis",
    title: "Endometriosis",
    bodySystem: "Reproductive",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "WHNP"],
    recognize: "Cyclic pelvic pain, dysmenorrhea, dyspareunia, dyschezia, infertility, or chronic pelvic pain raises suspicion for endometriosis; severity of pain does not predict lesion burden.",
    diagnostics: "Diagnosis is increasingly clinical with targeted pelvic exam and ultrasound for endometrioma or deep disease; normal ultrasound does not exclude superficial endometriosis. Surgical diagnosis is not mandatory before all treatment.",
    priorities: "Offer NSAIDs and hormonal suppression when appropriate, address fertility goals early, and refer for refractory pain, complex masses, organ involvement, or infertility management.",
    medicationSafety: "Combined or progestin therapy has thrombotic and bleeding-profile considerations; GnRH-based therapy requires counseling about hypoestrogenic effects and bone-protection strategies.",
    redFlags: "Acute severe pain with pregnancy possibility, torsion concern, hemorrhagic cyst, infection, or bowel or urinary obstruction requires urgent evaluation.",
    examTraps: "Do not tell a patient normal imaging means endometriosis is impossible. Hysterectomy does not guarantee cure when extrauterine disease remains.",
    sourceKeys: ["ACOG_ENDOMETRIOSIS_CURRENT", "ESHRE_ENDOMETRIOSIS_CURRENT"],
  },
  {
    slug: "infertility-evaluation",
    title: "Infertility Evaluation",
    bodySystem: "Reproductive",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "WHNP"],
    recognize: "Infertility evaluation is couple-based and time-sensitive: initiate after an appropriate duration of unprotected intercourse based on age, or sooner with irregular cycles, known tubal or male-factor risk, endometriosis, or diminished ovarian reserve concerns.",
    diagnostics: "Assess ovulation, uterine or tubal factors, and semen analysis early rather than completing an exhaustive female workup first. Review pregnancy history, cycle pattern, sexual timing, medications, substance use, genetics, and preconception health.",
    priorities: "Correct reversible causes, optimize preconception conditions, and refer to reproductive endocrinology when age, duration, abnormal testing, or need for assisted reproduction warrants it.",
    medicationSafety: "Fertility drugs can cause multiple gestation and ovarian hyperstimulation; medication choices should be specialist-guided when ovulation induction is needed.",
    redFlags: "Ectopic-pregnancy symptoms after fertility treatment, severe ovarian hyperstimulation, or acute torsion symptoms require urgent care.",
    examTraps: "Do not delay semen analysis. A single AMH value is not a stand-alone test of natural fertility and should not be used to promise or deny future pregnancy.",
    sourceKeys: ["ASRM_INFERTILITY_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
