import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch9 = [
  {
    slug: "atopic-dermatitis",
    title: "Atopic Dermatitis",
    bodySystem: "Dermatology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PNP"],
    recognize: "Pruritic chronic relapsing eczema with age-typical distribution, xerosis, and personal/family atopy suggests atopic dermatitis. Sudden pain, punched-out erosions, or systemic illness suggests superinfection rather than a simple flare.",
    diagnostics: "Diagnosis is clinical. Look for infection, contact triggers, scabies, psoriasis, and immunodeficiency clues; allergy testing is targeted rather than routine for every child with eczema.",
    priorities: "Daily emollients, trigger reduction, and appropriately potent topical anti-inflammatory therapy are first-line. Escalate to dermatology/allergy for severe, refractory, widespread, or biologic-eligible disease.",
    medicationSafety: "Match topical steroid potency to site, age, severity, and duration; avoid unnecessary fear that leads to undertreatment. Topical calcineurin inhibitors are useful steroid-sparing agents in selected areas.",
    redFlags: "Fever with rapidly spreading painful vesicles/erosions (eczema herpeticum), extensive bacterial infection, ocular involvement, or dehydration requires urgent treatment.",
    examTraps: "Do not treat every flare with antibiotics. Food elimination without a documented allergy can harm nutrition and rarely fixes eczema by itself.",
    sourceKeys: ["AAD_ATOPIC_DERM_CURRENT"],
  },
  {
    slug: "psoriasis",
    title: "Psoriasis",
    bodySystem: "Dermatology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "Well-demarcated erythematous plaques with scale on extensor surfaces/scalp, nail pitting, or inverse/genital disease suggest psoriasis. Ask about inflammatory joint pain because psoriatic arthritis changes urgency and therapy.",
    diagnostics: "Diagnosis is usually clinical; biopsy is selective. Screen severity, body-surface/special-site involvement, psoriatic arthritis, cardiometabolic risk, mood, smoking/alcohol, and medication triggers.",
    priorities: "Use topical therapy for limited disease and refer/escalate for extensive, special-site, refractory, or arthritic disease. Phototherapy, systemic agents, and biologics require phenotype and comorbidity selection.",
    medicationSafety: "Systemic immunomodulators require infection screening, vaccination planning, pregnancy counseling, and laboratory monitoring. Avoid abrupt systemic corticosteroid use as a routine psoriasis strategy.",
    redFlags: "Erythroderma, generalized pustular psoriasis with systemic illness, severe infection, or acute inflammatory arthritis with major disability requires urgent specialist care.",
    examTraps: "Do not mistake fungal infection for psoriasis without reconsidering atypical annular lesions. Nail psoriasis plus joint symptoms is a clue to psoriatic arthritis.",
    sourceKeys: ["AAD_PSO_CURRENT"],
  },
  {
    slug: "acne",
    title: "Acne Vulgaris",
    bodySystem: "Dermatology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PNP", "WHNP"],
    recognize: "Comedones define acne; inflammatory papules/pustules, nodules, scarring, and post-inflammatory pigment changes determine severity. Sudden severe acne, hirsutism, or menstrual irregularity may signal androgen excess.",
    diagnostics: "Diagnosis is clinical. Evaluate medications, pregnancy potential, endocrine clues, scarring, psychosocial impact, and skin-care practices; hormone tests are targeted to hyperandrogenism features.",
    priorities: "Use combination topical therapy and avoid antibiotic monotherapy. Add oral antibiotics for selected moderate-severe inflammatory disease with a plan to limit duration; isotretinoin is appropriate for severe/scarring/refractory acne under required safeguards.",
    medicationSafety: "Topical retinoids irritate and are avoided in pregnancy. Tetracyclines have pregnancy/age considerations; isotretinoin is highly teratogenic and requires mandated pregnancy-prevention processes.",
    redFlags: "Fulminant acne with systemic symptoms, severe depression/suicidality, or rapidly progressive scarring warrants expedited specialty evaluation.",
    examTraps: "Do not use topical or oral antibiotics alone. Acne improvement takes weeks; changing regimens every few days guarantees apparent failure.",
    sourceKeys: ["AAD_ACNE_CURRENT"],
  },
  {
    slug: "herpes-zoster",
    title: "Herpes Zoster",
    bodySystem: "Dermatology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Pain, burning, or allodynia followed by a unilateral dermatomal vesicular eruption suggests shingles. Disseminated lesions, cranial nerve involvement, or immunosuppression raise complication risk.",
    diagnostics: "Diagnosis is usually clinical; PCR from a lesion is useful when atypical. Assess eye/ear involvement, neurologic deficits, dissemination, pregnancy exposure contacts, and immune status.",
    priorities: "Start antiviral therapy promptly when indicated, provide multimodal pain control, keep lesions covered, and counsel susceptible contacts. Vaccination prevents future zoster but does not treat the acute episode.",
    medicationSafety: "Antivirals require renal dosing. Avoid routine antibiotics unless bacterial superinfection exists; neuropathic pain agents have sedation/fall considerations.",
    redFlags: "Ophthalmic distribution with eye symptoms, Ramsay Hunt syndrome, disseminated zoster, meningitis/encephalitis, motor weakness, or severe immunocompromised disease requires urgent care.",
    examTraps: "A past episode does not eliminate the need for recommended zoster vaccination. A few vesicles crossing midline do not automatically mean dissemination, but widespread lesions do.",
    sourceKeys: ["CDC_ZOSTER_CURRENT"],
  },
  {
    slug: "sinusitis-pharyngitis",
    title: "Acute Sinusitis & Pharyngitis",
    bodySystem: "HEENT",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PNP", "ENP"],
    recognize: "Most acute rhinosinusitis and sore throat is viral. Bacterial sinusitis is more likely with persistent symptoms without improvement, severe onset, or double-worsening; GAS pharyngitis is suggested by compatible features but requires testing in most patients.",
    diagnostics: "Use rapid antigen or molecular testing/culture according to age and guideline strategy for suspected GAS; do not test when clear viral features dominate. Sinus imaging is not routine unless complication or alternate diagnosis is suspected.",
    priorities: "Supportive care is first-line for viral disease. Treat confirmed GAS and guideline-defined bacterial sinusitis with appropriate antibiotics; provide return precautions for deep-neck/orbital complications.",
    medicationSafety: "Penicillin/amoxicillin remain first-line for many GAS cases absent allergy. Avoid macrolides when resistance or allergy phenotype argues against them; avoid broad antibiotics for uncomplicated viral URI.",
    redFlags: "Trismus, drooling, muffled voice, neck swelling, respiratory distress, periorbital edema/vision change, severe unilateral headache, or neurologic signs requires urgent evaluation.",
    examTraps: "Green mucus does not prove bacterial sinusitis. Do not use Centor-type features alone to diagnose GAS in a child when testing is recommended.",
    sourceKeys: ["IDSA_SINUSITIS_CURRENT", "IDSA_GAS_CURRENT"],
  },
  {
    slug: "acute-bronchitis",
    title: "Acute Bronchitis",
    bodySystem: "Respiratory",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "Cough after an upper respiratory infection—often lasting several weeks—with normal oxygenation and no focal pneumonia signs usually represents acute bronchitis, which is most often viral.",
    diagnostics: "Focus on ruling out pneumonia, asthma/COPD exacerbation, pertussis, heart failure, and PE when history or vitals suggest them. Chest radiography is selective rather than routine.",
    priorities: "Provide hydration, symptom relief, reassurance about expected cough duration, and safety-netting. Test/treat pertussis or influenza/COVID when epidemiology and timing make results actionable.",
    medicationSafety: "Antibiotics do not shorten routine viral bronchitis and cause adverse effects/resistance. Avoid routine bronchodilators unless wheeze/airflow obstruction is present.",
    redFlags: "Hypoxemia, tachypnea, high fever, focal consolidation, hemoptysis, chest pain, severe dyspnea, or high-risk frailty/immunosuppression needs further evaluation.",
    examTraps: "Purulent sputum is not a bacterial marker. A cough lasting 2–3 weeks can still be uncomplicated bronchitis.",
    sourceKeys: ["CDC_BRONCHITIS_CURRENT"],
  },
  {
    slug: "influenza-covid-outpatient",
    title: "Influenza & COVID-19 Outpatient Management",
    bodySystem: "Infectious Disease",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PMHNP", "PNP", "WHNP", "ENP"],
    recognize: "Acute fever, myalgias, cough, sore throat, and fatigue may be influenza or COVID-19; clinical overlap is substantial, and high-risk patients benefit most from early recognition because antiviral windows matter.",
    diagnostics: "Use current local viral testing when it will change treatment, isolation, or disposition. Assess oxygenation, hydration, pregnancy, age, immune status, cardiopulmonary disease, and drug interactions.",
    priorities: "Offer guideline-authorized antiviral therapy promptly to eligible high-risk patients; supportive care is appropriate for low-risk uncomplicated illness. Give current vaccination counseling after recovery when applicable.",
    medicationSafety: "Influenza antivirals and COVID antivirals have timing, renal/hepatic, pregnancy, and interaction considerations. Nirmatrelvir/ritonavir has major CYP-mediated interactions that require a medication reconciliation.",
    redFlags: "New hypoxemia, respiratory distress, chest pain, confusion, dehydration, or rapid deterioration requires emergency evaluation.",
    examTraps: "A negative early antigen test may not fully exclude infection. Do not give antibiotics unless there is evidence of bacterial coinfection.",
    sourceKeys: ["CDC_FLU_CURRENT", "CDC_COVID_CURRENT"],
  },
  {
    slug: "nephrolithiasis",
    title: "Nephrolithiasis",
    bodySystem: "Renal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Sudden colicky flank pain radiating to groin with hematuria, nausea, and restlessness suggests ureteral stone, but AAA, ectopic pregnancy, pyelonephritis, torsion, and other abdominal emergencies must remain in the differential.",
    diagnostics: "Urinalysis and pregnancy testing when relevant are foundational. Use noncontrast CT for many adults when imaging is needed; ultrasound is preferred in pregnancy and often useful as an initial study in younger patients.",
    priorities: "Control pain/nausea, hydrate to euvolemia, and determine size/location, infection, kidney function, solitary kidney, and likelihood of passage. Arrange urology follow-up; select patients benefit from medical expulsive therapy.",
    medicationSafety: "NSAIDs are effective first-line analgesics for many patients but require renal/GI/CV review. Alpha-blocker therapy can cause orthostasis and is not necessary for every stone.",
    redFlags: "Obstructed infected collecting system, anuria, solitary kidney obstruction, uncontrolled pain/vomiting, AKI, or sepsis requires urgent urologic decompression.",
    examTraps: "Do not force liters of fluid during acute obstruction. Hematuria may be absent, so a negative dipstick does not completely exclude a stone.",
    sourceKeys: ["AUA_STONES_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
