import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch46 = [
  {
    slug: "upper-gi-bleeding",
    title: "Upper Gastrointestinal Bleeding",
    bodySystem: "Gastrointestinal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Hematemesis, coffee-ground emesis or melena suggests upper-GI bleeding; brisk upper bleeding can cause hematochezia. First assess hemodynamic stability, cirrhosis/portal hypertension, NSAID/anticoagulant use and comorbidity rather than trying to identify the lesion from stool color alone.",
    diagnostics: "Obtain CBC, CMP/BUN/creatinine, coagulation and type/cross as severity warrants; use a validated pre-endoscopy score such as Glasgow-Blatchford to identify very-low-risk patients. Urgent endoscopy is both diagnostic and therapeutic after initial resuscitation, typically within 24 hours for hospitalized nonvariceal bleeding and sooner for unstable/high-risk presentations.",
    priorities: "Resuscitate with IV access, blood products using a generally restrictive transfusion strategy unless patient context dictates otherwise, hold/reverse anticoagulation when clinically necessary, start IV PPI for suspected high-risk nonvariceal bleeding and use octreotide plus antibiotic prophylaxis when variceal bleeding is suspected.",
    medicationSafety: "Avoid reflexive plasma correction of mild INR elevation in cirrhosis; reversal decisions depend on active bleeding and agent. Long-term PPI should be tied to ulcer/bleeding indication, and NSAIDs should be discontinued or minimized after ulcer bleeding.",
    redFlags: "Shock, ongoing hematemesis, syncope, rapidly falling hemoglobin, variceal bleed, severe comorbidity or inability to protect airway requires emergency endoscopic/inpatient management.",
    examTraps: "BUN elevation can support upper bleeding but is not diagnostic. A normal initial hemoglobin does not exclude major acute hemorrhage before equilibration.",
    sourceKeys: ["ACG_UGIB_CURRENT", "AASLD_VARICEAL_CURRENT"],
  },
  {
    slug: "lower-gi-bleeding",
    title: "Acute Lower Gastrointestinal Bleeding",
    bodySystem: "Gastrointestinal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Hematochezia most often arises below the ligament of Treitz but can reflect brisk upper bleeding. Diverticular hemorrhage, angioectasia, hemorrhoids, colitis, cancer and ischemia are common causes; pain, diarrhea, anticoagulation and hemodynamics narrow the differential.",
    diagnostics: "Stabilize first, obtain CBC/type/coagulation and risk-stratify; CT angiography is useful for ongoing hemodynamically significant bleeding and can guide embolization, while colonoscopy follows adequate preparation when the patient is stable enough and the timing fits the bleeding pattern.",
    priorities: "Resuscitate with a restrictive transfusion strategy for most stable adults, correct clinically important coagulopathy/antithrombotic effect selectively and coordinate GI/interventional radiology/surgery when bleeding persists. Treat the identified source rather than attributing major hematochezia to hemorrhoids without evaluation.",
    medicationSafety: "Antithrombotic interruption/restart balances rebleeding versus cardiovascular/thrombotic risk; secondary-prevention aspirin is often resumed promptly after hemostasis rather than stopped indefinitely. Avoid NSAIDs after diverticular/angioectatic bleeding when possible.",
    redFlags: "Shock, ongoing large-volume bleeding, syncope, ischemic chest symptoms, severe anemia or positive CTA with active extravasation requires emergency inpatient management.",
    examTraps: "Do not assume bright red blood means a benign distal source and do not use urgent unprepped colonoscopy as the default for an unstable active bleed when CTA/interventional pathways are more appropriate.",
    sourceKeys: ["ACG_LGIB_CURRENT"],
  },
  {
    slug: "cirrhosis-ascites-management",
    title: "Cirrhosis, Ascites & Decompensation",
    bodySystem: "Gastrointestinal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Ascites, variceal bleeding, hepatic encephalopathy, jaundice or hepatorenal dysfunction marks decompensated cirrhosis and substantially worsens prognosis. Peripheral edema/ascites in known liver disease should trigger evaluation for infection, renal injury, portal-vein thrombosis and medication/diet contributors.",
    diagnostics: "New-onset or hospitalized/worsening ascites warrants diagnostic paracentesis with cell count/differential, albumin and total protein; calculate SAAG to identify portal-hypertensive physiology. Track creatinine, sodium, bilirubin, INR and albumin and calculate MELD-Na/MELD 3.0 for prognosis/transplant referral.",
    priorities: "Use sodium moderation plus spironolactone/furosemide in appropriate ratios for uncomplicated portal-hypertensive ascites, therapeutic paracentesis with albumin for large-volume removal and early transplant evaluation after decompensation. Avoid nephrotoxins and treat precipitating infection/bleeding promptly.",
    medicationSafety: "Diuretics can cause AKI, hyponatremia and potassium disorders and should be held/reduced in severe renal/electrolyte complications. NSAIDs are generally avoided in ascites; ACEi/ARBs can worsen effective renal perfusion in advanced decompensated cirrhosis.",
    redFlags: "Tense ascites with respiratory compromise, suspected SBP, AKI, severe hyponatremia, variceal hemorrhage or encephalopathy with airway risk requires urgent inpatient care.",
    examTraps: "Do not delay paracentesis because INR/platelets look abnormal in typical cirrhosis and do not diagnose SBP from abdominal tenderness alone—cell count is essential.",
    sourceKeys: ["AASLD_ASCITES_CURRENT", "AASLD_CIRRHOSIS_CURRENT"],
  },
  {
    slug: "spontaneous-bacterial-peritonitis",
    title: "Spontaneous Bacterial Peritonitis",
    bodySystem: "Gastrointestinal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "SBP can present with fever, abdominal pain, encephalopathy, ileus, hypotension or renal deterioration—but cirrhotic patients may be minimally symptomatic. Any hospitalized patient with cirrhosis and ascites should have a low threshold for diagnostic paracentesis.",
    diagnostics: "Ascitic polymorphonuclear neutrophils ≥250 cells/mm³ establishes neutrocytic ascites requiring treatment; inoculate ascitic fluid into blood-culture bottles at bedside to improve yield. Evaluate for secondary peritonitis when polymicrobial culture, very high protein/LDH, low glucose or poor response suggests a surgically treatable source.",
    priorities: "Start a third-generation cephalosporin or current local guideline therapy promptly and give IV albumin in patients meeting renal-risk criteria to reduce hepatorenal failure/mortality. Long-term antibiotic prophylaxis is indicated after an SBP episode and in selected high-risk patients.",
    medicationSafety: "Prophylactic antibiotics drive resistance and are reserved for guideline-defined risk; quinolone choice depends on local resistance and adverse-effect profile. Avoid nephrotoxic drugs and unnecessary diuresis during active renal hypoperfusion.",
    redFlags: "Shock, AKI, severe encephalopathy, rising lactate, polymicrobial infection or failure to improve after appropriate therapy suggests severe or secondary peritonitis and requires urgent escalation.",
    examTraps: "A patient can have SBP without fever or rebound tenderness. Do not wait for a positive culture when the PMN count meets treatment criteria.",
    sourceKeys: ["AASLD_SBP_CURRENT"],
  },
  {
    slug: "esophageal-gastric-varices",
    title: "Esophageal & Gastric Varices",
    bodySystem: "Gastrointestinal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Portal hypertension produces gastroesophageal varices that may remain silent until massive bleeding. Cirrhosis with thrombocytopenia/splenomegaly, prior decompensation or clinically significant portal hypertension should prompt evidence-based primary prophylaxis rather than waiting for hemorrhage.",
    diagnostics: "Use noninvasive portal-hypertension criteria and/or upper endoscopy according to current cirrhosis guidance. During acute bleeding perform urgent EGD after resuscitation; gastric varices require different endoscopic/interventional strategies from routine esophageal banding.",
    priorities: "Use nonselective beta blocker therapy for appropriate primary prevention of decompensation/variceal bleeding or endoscopic band ligation when indicated. Acute suspected variceal bleeding requires vasoactive therapy, prophylactic antibiotics and urgent endoscopic therapy, with early TIPS in selected high-risk patients.",
    medicationSafety: "Carvedilol/propranolol can cause hypotension/bradycardia and may need adjustment in refractory ascites, AKI or shock. Octreotide is an acute bridge, not chronic prophylaxis; avoid unnecessary PPI continuation after variceal banding unless another indication exists.",
    redFlags: "Hematemesis, shock, encephalopathy/aspiration risk or recurrent bleeding after endoscopic therapy requires ICU/GI/interventional management.",
    examTraps: "Do not treat a cirrhotic GI bleed with PPI alone and do not use beta blockers during active shock. Primary prophylaxis is not based on variceal size alone when noninvasive evidence of clinically significant portal hypertension supports NSBB therapy.",
    sourceKeys: ["AASLD_PORTAL_HTN_CURRENT"],
  },
  {
    slug: "acute-diverticulitis",
    title: "Acute Diverticulitis",
    bodySystem: "Gastrointestinal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "ENP"],
    recognize: "Steady left-lower-quadrant pain, fever and bowel change suggests diverticulitis, but appendicitis, colorectal cancer, IBD, gynecologic disease and ischemic colitis remain alternatives. Prior diverticulitis does not make every recurrence clinically uncomplicated.",
    diagnostics: "CT abdomen/pelvis with contrast is used when diagnosis is uncertain, disease is severe or complication is suspected; classic mild recurrent disease may be managed without imaging in selected patients. Colonoscopy is delayed until recovery and used according to complicated status, prior high-quality colonoscopy and cancer risk.",
    priorities: "Use oral hydration/diet advancement and analgesia for uncomplicated stable disease; antibiotics are selective rather than routine in immunocompetent mild uncomplicated diverticulitis, but are indicated in immunocompromise, systemic illness or complicated disease. Abscess, perforation or obstruction requires procedural/surgical input.",
    medicationSafety: "Avoid routine fluoroquinolone exposure when effective alternatives exist because of serious adverse effects and resistance. NSAIDs may increase diverticular complication/bleeding risk and should not become chronic analgesia in susceptible patients.",
    redFlags: "Peritonitis, sepsis, free perforation, obstruction, fistula, large abscess or immunocompromised patient with worsening symptoms requires inpatient/surgical management.",
    examTraps: "Do not prescribe antibiotics automatically for every mild uncomplicated case and do not perform colonoscopy during the acute inflamed phase unless another emergency indication exists.",
    sourceKeys: ["AGA_DIVERTICULITIS_CURRENT", "ASCRS_DIVERTICULITIS_CURRENT"],
  },
  {
    slug: "acute-cholecystitis-cholangitis",
    title: "Acute Cholecystitis & Ascending Cholangitis",
    bodySystem: "Gastrointestinal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Persistent RUQ pain/tenderness after cystic-duct obstruction suggests acute cholecystitis; fever/jaundice with biliary obstruction suggests cholangitis and can progress rapidly to sepsis. Pancreatitis, hepatitis, peptic disease and right-lower-lung pathology can mimic biliary pain.",
    diagnostics: "Use RUQ ultrasound first for gallstones/cholecystitis; HIDA clarifies equivocal cases. For cholangitis obtain CBC/CMP/bilirubin, blood cultures if septic and ultrasound/CT/MRCP to identify obstruction, but do not delay urgent ERCP in an unstable patient with clear obstructive sepsis.",
    priorities: "Acute cholecystitis generally receives fluids/analgesia, appropriate antibiotics and early laparoscopic cholecystectomy. Cholangitis requires broad antibiotics plus urgent biliary drainage—usually ERCP—because antibiotics alone cannot reliably control an obstructed infected system.",
    medicationSafety: "Adjust antibiotic choice for severity, prior healthcare exposure and local resistance and de-escalate after source control. NSAID/opioid choice depends on kidney/GI/respiratory status; avoid meperidine myths—there is no need to prefer it for biliary pain.",
    redFlags: "Hypotension, altered mental status, rising bilirubin/lactate, organ dysfunction, perforation/gangrene or emphysematous cholecystitis requires emergency source control.",
    examTraps: "Charcot triad is insensitive and absence of jaundice does not exclude cholangitis. Antibiotics without drainage are inadequate when obstruction and sepsis persist.",
    sourceKeys: ["TOKYO_CHOLANGITIS_CURRENT", "SAGES_CHOLECYSTITIS_CURRENT"],
  },
  {
    slug: "celiac-disease-evaluation",
    title: "Celiac Disease Evaluation & Management",
    bodySystem: "Gastrointestinal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PNP"],
    recognize: "Celiac disease can present with chronic diarrhea, bloating, iron deficiency, weight loss, osteoporosis, transaminitis, infertility or minimal GI symptoms. Type 1 diabetes, autoimmune thyroid disease, Down syndrome and first-degree family history increase risk.",
    diagnostics: "While the patient is eating gluten, obtain tTG-IgA plus total IgA; use IgG-based testing when IgA deficient. Adults generally require upper endoscopy with duodenal biopsies for confirmation; do not start a gluten-free diet before testing unless medically necessary because serology/histology can normalize.",
    priorities: "Use a strict lifelong gluten-free diet with dietitian support, correct iron/folate/B12/vitamin-D or bone deficits and reassess symptoms/serology. Screen selected first-degree relatives and evaluate persistent symptoms for ongoing exposure, refractory disease or another diagnosis.",
    medicationSafety: "There is no routine pharmacologic replacement for a gluten-free diet; avoid unnecessary steroid/immunosuppressive therapy unless refractory celiac disease is confirmed by specialists. Review medication/supplement gluten exposure only when clinically plausible rather than creating excessive restriction.",
    redFlags: "Severe malnutrition, dehydration, GI bleeding, refractory symptoms/weight loss despite verified diet or lymphoma concern requires urgent gastroenterology evaluation.",
    examTraps: "Do not diagnose celiac disease from antigliadin antibodies or one positive tTG after the patient has already stopped gluten without a confirmation plan. Nonceliac gluten sensitivity is a different diagnosis.",
    sourceKeys: ["ACG_CELIAC_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
