import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch13 = [
  {
    slug: "pediatric-seizures",
    title: "Pediatric Seizures",
    bodySystem: "Pediatrics",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PNP", "ENP"],
    recognize: "Clarify whether the event was truly a seizure: duration, focality, fever, developmental history, provoking factors, recovery, family history, and video or collateral description. Simple febrile seizure differs from unprovoked epilepsy.",
    diagnostics: "Check glucose in acute altered events; further labs, EEG, imaging, and lumbar puncture depend on age, focality, neurologic exam, recurrence, fever source, and suspected cause. A normal interictal EEG does not exclude epilepsy.",
    priorities: "Protect airway and prevent injury during the event; prolonged seizures need rescue benzodiazepine therapy per protocol. First unprovoked seizure follow-up should address recurrence risk, safety, and neurology referral when indicated.",
    medicationSafety: "Rescue benzodiazepines can depress respiration; caregivers need exact route or dose and when to call EMS. Chronic antiseizure medication choice depends on seizure type, age, comorbidity, interactions, and reproductive considerations in adolescents.",
    redFlags: "Seizure lasting about 5 minutes or longer, repeated seizures without recovery, focal deficit, meningismus, trauma, toxic ingestion, or persistent altered mental status requires emergency care.",
    examTraps: "Do not put objects in the mouth or restrain a seizing child. A simple febrile seizure does not automatically require EEG, neuroimaging, or chronic antiseizure medication.",
    sourceKeys: ["AAN_PEDS_SEIZURE_CURRENT", "AAP_FEBRILE_SEIZURE_CURRENT"],
  },
  {
    slug: "failure-to-thrive",
    title: "Growth Faltering / Failure to Thrive",
    bodySystem: "Pediatrics",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PNP"],
    recognize: "Growth faltering is a concerning downward weight or weight-for-length or BMI trajectory rather than one low percentile. Feeding mechanics, intake, vomiting or diarrhea, chronic disease, developmental issues, food insecurity, and caregiver-child interaction all matter.",
    diagnostics: "Verify accurate measurements and plot serial growth. Use detailed diet or feeding history and physical exam to guide targeted tests; broad laboratory panels have low yield when history and exam do not suggest an organic disease.",
    priorities: "Correct caloric or nutrient deficits, feeding problems, and underlying disease while supporting caregivers and addressing social needs. Dietitian, feeding therapy, GI, developmental, or child-protection referral depends on the pattern.",
    medicationSafety: "Concentrated formulas or supplements must be prepared safely to avoid electrolyte or renal-solute problems. Do not prescribe appetite stimulants routinely without a clear indication and specialist plan.",
    redFlags: "Severe malnutrition, dehydration, electrolyte abnormality, cardiorespiratory compromise, suspected abuse or neglect, or inability to feed safely requires urgent evaluation.",
    examTraps: "Do not equate small parental stature with reassurance when the child is crossing percentiles. Normal screening labs do not replace a detailed feeding assessment.",
    sourceKeys: ["AAP_GROWTH_FALTERING_CURRENT"],
  },
  {
    slug: "acute-respiratory-failure-ards",
    title: "Acute Respiratory Failure & ARDS",
    bodySystem: "Respiratory",
    applicableExams: ["AGACNP", "ENP", "AANP-FNP", "ANCC-FNP"],
    recognize: "Escalating work of breathing, hypoxemia, hypercapnia, altered mentation, exhaustion, or inability to protect the airway signals respiratory failure. ARDS is acute noncardiogenic pulmonary edema with bilateral opacities and impaired oxygenation in the setting of a known insult.",
    diagnostics: "Use ABG or VBG as appropriate, pulse oximetry, chest imaging, ECG, labs for cause, and bedside ultrasound or echo when cardiogenic edema or PE is possible. Track oxygen requirement and ventilatory mechanics rather than one saturation value.",
    priorities: "Treat the cause, support oxygenation or ventilation, and escalate from conventional oxygen to high-flow or NIV or intubation based on physiology and trajectory. Ventilated ARDS care uses lung-protective low tidal-volume strategies and appropriate PEEP.",
    medicationSafety: "Sedatives, opioids, and neuromuscular blockers can worsen hypotension and obscure exam; use only with clear critical-care indications. Avoid excessive fluid after initial resuscitation when pulmonary edema predominates.",
    redFlags: "Refractory hypoxemia, rising CO2 with fatigue, altered mental status, shock, silent chest, or inability to protect the airway requires immediate critical-care intervention.",
    examTraps: "A normal-looking chest x-ray early does not rule out evolving respiratory failure. Do not delay intubation until a crashing patient is peri-arrest when trajectory clearly shows failure.",
    sourceKeys: ["ATS_ARDS_CURRENT", "ESICM_ARDS_CURRENT"],
  },
  {
    slug: "acute-kidney-injury",
    title: "Acute Kidney Injury",
    titleAliases: ["AKI: RIFLE Criteria & Dialysis"],
    slugAliases: ["aki-management-np"],
    bodySystem: "Renal",
    applicableExams: ["AGACNP", "ENP", "AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "AKI is an acute creatinine rise and/or reduced urine output. Think prerenal hypoperfusion, intrinsic renal injury, and postrenal obstruction while reviewing sepsis, volume loss, nephrotoxins, urinary retention, and recent procedures.",
    diagnostics: "Trend creatinine and urine output, review urinalysis or microscopy, electrolytes, medication exposures, volume status, and bladder or renal imaging when obstruction is possible. Fractional excretion indices can mislead and should not replace the clinical picture.",
    priorities: "Restore perfusion when volume depleted, stop or adjust nephrotoxins, treat sepsis or obstruction, dose medications for current kidney function, and monitor potassium, acid-base status, and volume closely.",
    medicationSafety: "NSAIDs, ACEi or ARBs, diuretics, contrast, antimicrobials, and many other drugs can contribute depending on context. Do not reflexively give large fluid boluses to a volume-overloaded patient with AKI.",
    redFlags: "Refractory hyperkalemia, severe acidosis, pulmonary edema, uremic complications, anuria or obstruction, or rapidly progressive renal failure needs urgent nephrology or critical care.",
    examTraps: "A 'normal' creatinine may still represent AKI in a low-muscle-mass patient. Urine output can decline before creatinine rises.",
    sourceKeys: ["KDIGO_AKI_CURRENT"],
  },
  {
    slug: "electrolyte-emergencies",
    title: "Electrolyte Emergencies",
    bodySystem: "Renal",
    applicableExams: ["AGACNP", "ENP", "AANP-FNP", "ANCC-FNP"],
    recognize: "Severe sodium, potassium, calcium, or magnesium disturbances can present with weakness, confusion, seizure, arrhythmia, ileus, or nonspecific symptoms. Confirm the value, review ECG when relevant, and look for medications and underlying cause.",
    diagnostics: "Repeat suspicious results to exclude hemolysis or lab error when the patient is stable, but do not delay treatment of clinically dangerous abnormalities. Assess glucose or osmolality for sodium disorders and renal function or acid-base status for potassium problems.",
    priorities: "Treat life-threatening physiology first: membrane stabilization and intracellular shift for dangerous hyperkalemia, cautious correction of symptomatic sodium disorders, and targeted calcium or magnesium replacement when indicated.",
    medicationSafety: "Overly rapid correction of chronic hyponatremia risks osmotic demyelination; overly rapid correction of chronic hypernatremia can cause cerebral edema. Potassium replacement route or rate requires cardiac and renal monitoring.",
    redFlags: "ECG changes with hyperkalemia, seizure or coma from sodium disturbance, tetany or arrhythmia from severe calcium or magnesium abnormality, or rapidly changing values requires emergency care.",
    examTraps: "Do not use ECG absence to rule out dangerous hyperkalemia. A single sodium value cannot be interpreted without duration, symptoms, glucose, and volume status.",
    sourceKeys: ["AHA_ELECTROLYTE_CURRENT", "KDIGO_ELECTROLYTE_CURRENT"],
  },
  {
    slug: "status-epilepticus",
    title: "Status Epilepticus",
    bodySystem: "Neurological",
    applicableExams: ["AGACNP", "ENP", "AANP-FNP", "ANCC-FNP", "PNP"],
    recognize: "A convulsive seizure lasting about 5 minutes or repeated seizures without recovery should be treated as status epilepticus. Consider hypoglycemia, medication nonadherence, stroke, infection, alcohol withdrawal, pregnancy or eclampsia, toxin, and electrolyte disturbance.",
    diagnostics: "Check glucose immediately, secure monitoring or IV or IO access, and obtain electrolytes, pregnancy test when relevant, antiseizure drug levels selectively, toxicology or infectious studies, and urgent imaging after stabilization based on cause.",
    priorities: "Give an adequate benzodiazepine dose promptly, then a guideline-supported second-line antiseizure medication if seizures persist. Refractory status requires airway control, continuous EEG, anesthetic therapy, and neurocritical care.",
    medicationSafety: "Underdosing benzodiazepines because of fear of respiratory depression can prolong status and worsen outcomes. Account for renal or hepatic function and interactions when selecting second-line therapy.",
    redFlags: "Ongoing convulsions, persistent coma, recurrent seizure without recovery, pregnancy with seizure, focal deficit, trauma, meningismus, or refractory status requires immediate emergency or critical care.",
    examTraps: "Do not wait 30 minutes to call it status epilepticus. After motor activity stops, persistent unresponsiveness may represent nonconvulsive status and can require EEG.",
    sourceKeys: ["AES_STATUS_CURRENT", "AAN_STATUS_CURRENT"],
  },
  {
    slug: "hypertensive-emergency",
    title: "Hypertensive Emergency",
    bodySystem: "Cardiovascular",
    applicableExams: ["AGACNP", "ENP", "AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "Hypertensive emergency is severe blood pressure elevation with acute target-organ injury—encephalopathy, stroke, ACS, pulmonary edema, aortic syndrome, AKI, retinal injury, or pregnancy-related severe disease. The BP number alone does not define the emergency.",
    diagnostics: "Repeat BP correctly, perform focused neurologic, cardiac, renal, and funduscopic assessment, ECG, creatinine or electrolytes, urinalysis, troponin or imaging when indicated, and tailor testing to suspected organ injury.",
    priorities: "Use monitored IV antihypertensive therapy and a controlled reduction strategy specific to the organ injury. Aortic dissection, ischemic stroke, intracranial hemorrhage, and pregnancy each have different BP targets and timelines.",
    medicationSafety: "Choose IV agents according to comorbidity and emergency type; avoid rapid unmonitored oral stacking. Nitroglycerin is useful in selected pulmonary edema or ACS contexts, while beta-blockade precedes vasodilation in acute aortic syndrome.",
    redFlags: "Neurologic deficit, chest or back pain, pulmonary edema, severe AKI, retinal hemorrhage or papilledema, seizure, or pregnancy with severe features requires emergency care.",
    examTraps: "Do not treat asymptomatic severe hypertension like hypertensive emergency. Rapidly normalizing BP can cause ischemia when autoregulation has adapted to chronic hypertension.",
    sourceKeys: ["AHA_BP_2025"],
  },
  {
    slug: "acute-pancreatitis",
    title: "Acute Pancreatitis",
    bodySystem: "Gastrointestinal",
    applicableExams: ["AGACNP", "ENP", "AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC"],
    recognize: "Acute epigastric pain often radiating to the back with nausea or vomiting suggests pancreatitis, especially with gallstones, alcohol use, hypertriglyceridemia, or culprit medications. Diagnosis generally requires two of three: characteristic pain, enzyme elevation, or imaging.",
    diagnostics: "Check lipase, CBC or CMP, liver tests, calcium, triglycerides when indicated, and RUQ ultrasound for biliary cause. CT is not automatically needed on day one when the diagnosis is clear and the patient is improving.",
    priorities: "Provide early goal-directed IV crystalloid based on volume status, analgesia, antiemetics, and early oral or enteral nutrition as tolerated. Treat biliary obstruction or cholangitis and other causes; monitor for organ failure and necrosis.",
    medicationSafety: "Avoid routine prophylactic antibiotics in sterile pancreatitis. Opioids may be needed for severe pain but require respiratory and ileus awareness; fluid therapy should be reassessed to avoid overload.",
    redFlags: "Persistent organ failure, shock, hypoxemia, severe AKI, cholangitis, abdominal compartment concern, or infected necrosis needs urgent specialty or critical-care management.",
    examTraps: "Do not trend lipase to decide whether pancreatitis has resolved. Markedly elevated lipase is not a severity score, and early routine CT can add little when the diagnosis is already established.",
    sourceKeys: ["ACG_PANCREATITIS_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
