import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch3 = [
  {
    slug: "chronic-kidney-disease",
    title: "Chronic Kidney Disease",
    bodySystem: "Renal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP"],
    recognize: "CKD is kidney abnormality present for >3 months, often silent until advanced. Diabetes, hypertension, albuminuria, structural disease, and recurrent AKI are major clues.",
    diagnostics: "Stage with both eGFR and urine albumin-to-creatinine ratio, then trend over time. Review urinalysis, electrolytes, anemia/mineral-bone complications, nephrotoxins, medication doses, and reversible causes of decline.",
    priorities: "Slow progression by controlling BP/diabetes, using kidney-protective therapy when indicated, avoiding nephrotoxins, and managing complications. Refer based on advanced stage, rapid progression, heavy albuminuria, resistant hypertension, or diagnostic uncertainty.",
    medicationSafety: "ACEi/ARB and SGLT2 therapy can cause an expected small initial eGFR change; monitor rather than reflexively stopping. Renally clear medications and NSAIDs require special attention.",
    redFlags: "Refractory hyperkalemia, severe acidosis, pulmonary edema, uremic complications, or rapidly falling kidney function needs urgent nephrology/emergency evaluation.",
    examTraps: "Do not stage CKD from one low eGFR during acute illness. Creatinine can look deceptively normal in low-muscle-mass older adults.",
    sourceKeys: ["KDIGO_CKD_2024"],
  },
  {
    slug: "uti-pyelonephritis",
    title: "UTI & Pyelonephritis",
    bodySystem: "Renal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PNP", "WHNP", "ENP"],
    recognize: "Dysuria, frequency, urgency, and suprapubic discomfort suggest cystitis. Fever, flank pain, CVA tenderness, vomiting, or systemic illness shifts concern to pyelonephritis/complicated infection.",
    diagnostics: "Urinalysis supports the diagnosis; culture is especially important in pyelonephritis, pregnancy, recurrent/complicated disease, resistant-risk patients, or treatment failure. Do not culture and treat asymptomatic bacteriuria except in specific indications such as pregnancy or before certain urologic procedures.",
    priorities: "Choose antibiotics based on syndrome, local resistance, allergy, pregnancy, renal function, prior cultures, and severity. Pyelonephritis needs tissue-active therapy and close follow-up; obstructed infected systems need urgent drainage.",
    medicationSafety: "Nitrofurantoin is for lower UTI, not pyelonephritis. Fluoroquinolone use requires resistance and adverse-effect awareness; TMP-SMX has renal, potassium, and interaction considerations.",
    redFlags: "Sepsis, pregnancy with pyelonephritis, obstruction/stone plus infection, inability to hydrate, or worsening despite therapy requires escalation.",
    examTraps: "Pyuria alone does not equal symptomatic UTI. Foul-smelling urine in an older adult without urinary/systemic symptoms is not enough to diagnose infection.",
    sourceKeys: ["IDSA_UTI_CURRENT"],
  },
  {
    slug: "gerd-peptic-ulcer",
    title: "GERD & Peptic Ulcer Disease",
    bodySystem: "Gastrointestinal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "ENP"],
    recognize: "Typical GERD is heartburn/regurgitation; ulcer disease may cause epigastric pain, nausea, occult blood loss, or overt bleeding. Dysphagia, weight loss, anemia, recurrent vomiting, or GI bleeding are alarm features.",
    diagnostics: "Uncomplicated typical GERD can often be treated empirically. Test for H. pylori when ulcer disease or other accepted indication is present; endoscopy is driven by alarm features, refractory symptoms, bleeding risk, or diagnostic uncertainty.",
    priorities: "Use lifestyle measures selectively and acid suppression at the lowest effective long-term intensity. Eradicate H. pylori with a guideline-concordant regimen and confirm eradication when indicated.",
    medicationSafety: "Long-term PPI use should have a valid indication and periodic review, but fear of rare associations is not a reason to stop necessary therapy. NSAIDs increase ulcer/bleeding risk, especially with anticoagulants or steroids.",
    redFlags: "Hematemesis, melena with instability, perforation signs, progressive dysphagia, or severe anemia needs urgent evaluation.",
    examTraps: "Do not assume chest pain is reflux before assessing cardiac risk. Symptom relief with antacid does not exclude ACS.",
    sourceKeys: ["ACG_GERD_PUD_CURRENT"],
  },
  {
    slug: "upper-lower-gi-bleeding",
    title: "GI Bleeding",
    bodySystem: "Gastrointestinal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Hematemesis/melena usually suggests upper GI bleeding; hematochezia can be lower GI bleeding or brisk upper bleeding. Orthostasis, syncope, tachycardia, pallor, or confusion may reveal significant blood loss.",
    diagnostics: "Assess hemodynamics first, then CBC, CMP, coagulation studies, type and screen/crossmatch, medication history, and source-specific testing. Risk scores can support—not replace—clinical judgment.",
    priorities: "Resuscitate, stop/reverse contributing anticoagulation when appropriate, start source-directed therapy, and obtain urgent endoscopic/specialty management according to stability and suspected source.",
    medicationSafety: "NSAIDs, antiplatelets, anticoagulants, steroids, SSRIs, and alcohol may influence bleeding risk. Reversal decisions balance severity of bleeding against thrombosis risk.",
    redFlags: "Shock, ongoing large-volume bleeding, syncope, severe anemia with ischemia, variceal concern, or peritoneal signs requires emergency care.",
    examTraps: "A normal initial hemoglobin does not exclude acute major bleeding. Bright red blood per rectum is not automatically hemorrhoids.",
    sourceKeys: ["ACG_GI_BLEED_CURRENT"],
  },
  {
    slug: "cirrhosis-decompensation",
    title: "Cirrhosis & Decompensation",
    bodySystem: "Gastrointestinal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Ascites, jaundice, thrombocytopenia, splenomegaly, encephalopathy, variceal bleeding, muscle wasting, or stigmata of chronic liver disease suggest advanced cirrhosis.",
    diagnostics: "Assess CBC/CMP/INR, renal function/electrolytes, ultrasound-based HCC surveillance, variceal risk, ascites, encephalopathy, nutrition, alcohol/substance use, and etiology. New ascites should be sampled when appropriate.",
    priorities: "Treat the cause, prevent decompensation, manage ascites/encephalopathy/varices, vaccinate appropriately, and refer for hepatology/transplant evaluation when decompensation or high risk develops.",
    medicationSafety: "Avoid unnecessary NSAIDs and sedatives. Lactulose is titrated to clinical effect in hepatic encephalopathy; diuretic therapy requires renal/electrolyte monitoring.",
    redFlags: "Hematemesis, spontaneous bacterial peritonitis concern, hepatorenal syndrome, severe encephalopathy, sepsis, or acute-on-chronic liver failure requires urgent care.",
    examTraps: "Ammonia level does not diagnose or grade hepatic encephalopathy by itself. Do not fluid-restrict every patient with ascites unless a specific indication exists.",
    sourceKeys: ["AASLD_CIRRHOSIS_CURRENT"],
  },
  {
    slug: "headache-migraine",
    title: "Headache & Migraine",
    bodySystem: "Neurological",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PNP", "WHNP", "ENP"],
    recognize: "Migraine is usually episodic, often unilateral/pulsating with nausea and sensory sensitivity, but the key exam move is screening every headache for secondary red flags.",
    diagnostics: "Use history and neurologic exam to decide if imaging or lumbar puncture is needed. Red flags include sudden maximal onset, new neurologic deficit, papilledema, pregnancy/postpartum risk, cancer/immunosuppression, fever/meningismus, trauma, and a major pattern change.",
    priorities: "Treat acute migraine early and match preventive therapy to frequency, disability, comorbidity, pregnancy potential, and patient preference. Address medication-overuse headache.",
    medicationSafety: "Triptans are inappropriate in certain vascular disease settings; valproate and several other preventives have major pregnancy risks. Frequent analgesic use can perpetuate headache.",
    redFlags: "Thunderclap headache, focal deficit, meningismus, altered mental status, acute glaucoma symptoms, or severe pregnancy/postpartum headache requires emergency evaluation.",
    examTraps: "Normal neurologic exam does not make thunderclap headache benign. Do not image every stable recurrent migraine with a typical pattern and normal exam.",
    sourceKeys: ["AHS_CURRENT"],
  },
  {
    slug: "tia-ischemic-stroke",
    title: "TIA & Ischemic Stroke",
    bodySystem: "Neurological",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Sudden unilateral weakness/numbness, aphasia, visual loss, neglect, ataxia, or other focal deficit is stroke until proven otherwise—even if symptoms resolve.",
    diagnostics: "Document last-known-well time, glucose, NIHSS-type deficit assessment, noncontrast head CT, vascular imaging when indicated, ECG/telemetry, and targeted labs without delaying reperfusion decisions.",
    priorities: "Activate stroke pathway immediately. Reperfusion eligibility depends on time, imaging, anatomy, contraindications, and local capability; secondary prevention depends on mechanism such as AF, carotid disease, small-vessel disease, or atherosclerosis.",
    medicationSafety: "Antiplatelet and anticoagulant therapy are not interchangeable. Do not give anticoagulation acutely just because AF is present without considering hemorrhage and timing.",
    redFlags: "Any persistent focal deficit, disabling transient symptoms, posterior-circulation signs, or suspected hemorrhage requires emergency evaluation.",
    examTraps: "TIA is not a benign outpatient diagnosis. A negative early CT rules out many hemorrhages but does not rule out acute ischemic stroke.",
    sourceKeys: ["AHA_STROKE_CURRENT"],
  },
  {
    slug: "gout",
    title: "Gout",
    bodySystem: "Musculoskeletal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Rapid severe monoarthritis—classically first MTP but also ankle/knee—suggests gout, especially with hyperuricemia risk, CKD, diuretics, alcohol, or prior flares.",
    diagnostics: "Joint aspiration with crystal analysis is the gold standard when diagnosis is uncertain or septic arthritis is possible. Serum urate can be normal during an acute flare.",
    priorities: "Treat the acute flare with an anti-inflammatory appropriate to kidney/GI/cardiovascular status. Long-term urate lowering is for appropriate recurrent/high-risk disease and should be titrated to a target with flare prophylaxis when initiated.",
    medicationSafety: "Colchicine requires renal/hepatic and interaction awareness. NSAIDs may be unsafe in CKD/GI bleeding; allopurinol hypersensitivity risk is higher in selected genetic-risk populations.",
    redFlags: "Fever, toxic appearance, prosthetic joint, immunosuppression, bacteremia risk, or inability to bear weight with diagnostic uncertainty = rule out septic arthritis urgently.",
    examTraps: "Do not withhold allopurinol during an acute flare if the patient is already taking it. Do not diagnose gout from uric acid alone.",
    sourceKeys: ["ACR_GOUT_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
