import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch6 = [
  {
    slug: "vaginitis-sti",
    title: "Vaginitis & STI Syndromes",
    bodySystem: "Reproductive",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "WHNP", "PNP", "ENP"],
    recognize: "Discharge, odor, pruritus, dysuria, dyspareunia, lesions, or pelvic pain require a syndrome-based differential: BV, candidiasis, trichomoniasis, cervicitis, herpes, PID, UTI, dermatitis, and physiologic discharge.",
    diagnostics: "Use history plus exam and point-of-care/molecular testing as appropriate. Pregnancy testing matters when pelvic pain or pregnancy possibility exists; test for gonorrhea/chlamydia and other STIs according to risk and syndrome.",
    priorities: "Treat the identified syndrome, address partner management when indicated, counsel on abstinence until treatment criteria are met, and offer HIV/syphilis screening based on risk/current recommendations.",
    medicationSafety: "Metronidazole, azoles, antivirals, and antibiotics have pregnancy/interaction considerations. Avoid empiric fluconazole in pregnancy when safer recommended options exist.",
    redFlags: "Severe pelvic pain, fever, peritoneal signs, pregnancy with pain/bleeding, tubo-ovarian abscess concern, or disseminated infection needs urgent evaluation.",
    examTraps: "Symptoms alone cannot reliably distinguish BV, candidiasis, and trichomoniasis. Treating every discharge as yeast causes missed STIs/PID.",
    sourceKeys: ["CDC_STI_CURRENT"],
  },
  {
    slug: "sepsis",
    title: "Sepsis",
    titleAliases: ["Sepsis: Cytokine Storm & SOFA"],
    slugAliases: ["sepsis-mastery-np"],
    bodySystem: "Emergency",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGACNP", "ENP", "PNP"],
    recognize: "Suspected infection plus acute organ dysfunction is sepsis. Look for altered mentation, hypotension, tachypnea, hypoxemia, oliguria, mottling, lactate elevation, or rapidly worsening clinical status.",
    diagnostics: "Obtain cultures when they will not meaningfully delay antibiotics, measure lactate when indicated, and evaluate source with targeted labs/imaging. Reassess perfusion repeatedly rather than relying on one score.",
    priorities: "Give timely appropriate antimicrobials, IV crystalloid for hypoperfusion, source control, oxygen/ventilatory support as needed, and vasopressors for persistent hypotension after adequate fluid assessment.",
    medicationSafety: "Antibiotic choice must reflect source, host factors, recent healthcare exposure, local resistance, allergies, renal function, and de-escalation once data return.",
    redFlags: "Persistent hypotension, rising lactate, respiratory failure, altered mentation, or rapidly progressive organ dysfunction = emergency/critical care.",
    examTraps: "Do not wait for fever or leukocytosis; older/immunocompromised patients may be afebrile. qSOFA is not a rule-out test.",
    sourceKeys: ["SURVIVING_SEPSIS_CURRENT"],
  },
  {
    slug: "anaphylaxis",
    title: "Anaphylaxis",
    bodySystem: "Emergency",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGACNP", "PNP", "WHNP", "ENP"],
    recognize: "Rapid multisystem allergic symptoms, airway swelling, bronchospasm, hypotension, or severe GI symptoms after likely exposure can be anaphylaxis—even without hives.",
    diagnostics: "Diagnosis is clinical. Do not delay treatment for tryptase, labs, or imaging; monitor airway, breathing, circulation, oxygenation, and response.",
    priorities: "Give IM epinephrine promptly in the lateral thigh, repeat as needed, position appropriately, provide airway/oxygen/fluids, and transfer/observe based on severity and recurrence risk.",
    medicationSafety: "Antihistamines and corticosteroids are adjuncts, not substitutes for epinephrine. Beta-blockers may complicate treatment; glucagon can be considered in refractory cases under emergency protocols.",
    redFlags: "Stridor, hypotension, severe wheeze, tongue/laryngeal swelling, collapse, or refractory symptoms requires immediate emergency treatment.",
    examTraps: "Skin findings are not required. Do not give antihistamine first while waiting to see if epinephrine becomes necessary.",
    sourceKeys: ["AAAAI_ANAPHYLAXIS_CURRENT"],
  },
  {
    slug: "head-injury-trauma",
    title: "Head Injury & Concussion",
    bodySystem: "Emergency",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGACNP", "PNP", "ENP"],
    recognize: "After head trauma, assess mechanism, loss of consciousness/amnesia, vomiting, anticoagulation, seizure, headache trajectory, neurologic deficit, and cervical-spine risk.",
    diagnostics: "Use validated age-appropriate CT decision rules rather than scanning everyone. Serial neurologic exams matter; concussion diagnosis can exist with normal imaging.",
    priorities: "Stabilize ABCs and c-spine when indicated, image high-risk patients, and give graded return-to-activity guidance after concussion with close follow-up.",
    medicationSafety: "Anticoagulants/antiplatelets increase intracranial-bleeding concern. Avoid routine opioids or sedatives that obscure neurologic reassessment when alternatives are appropriate.",
    redFlags: "Deteriorating GCS, focal deficit, repeated vomiting, seizure, signs of skull fracture, anticoagulation plus concerning injury, or severe worsening headache needs emergency imaging/escalation.",
    examTraps: "A normal CT does not rule out concussion. Loss of consciousness is not required for significant intracranial injury.",
    sourceKeys: ["ACEP_MILD_TBI_CURRENT", "PECARN_CURRENT"],
  },
  {
    slug: "acute-abdominal-pain",
    title: "Acute Abdominal Pain",
    bodySystem: "Emergency",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGACNP", "ENP", "WHNP", "PNP"],
    recognize: "Location and time course guide the differential, but dangerous causes can start vaguely. Pregnancy, age, immunosuppression, vascular risk, prior surgery, and pain out of proportion change the stakes.",
    diagnostics: "Pregnancy test in reproductive-age patients when pregnancy is possible. Use targeted CBC/CMP/lipase/urinalysis and ultrasound/CT based on suspected diagnosis; do not order every test for every abdomen.",
    priorities: "Stabilize first, treat pain/nausea, keep NPO when surgical disease is possible, and obtain urgent surgical/OB/urology consultation when indicated.",
    medicationSafety: "Analgesia does not 'mask' a surgical abdomen. NSAIDs may be useful for renal colic but are not appropriate for every patient; review kidney function, pregnancy, and bleeding risk.",
    redFlags: "Peritonitis, shock, pulsatile mass, GI bleeding with instability, ectopic concern, testicular torsion, bowel ischemia, or severe pain out of proportion requires emergency action.",
    examTraps: "Do not rule out appendicitis because pain is not yet in the RLQ. Older adults may have deceptively mild tenderness despite serious pathology.",
    sourceKeys: ["ACEP_ABDOMEN_CURRENT"],
  },
  {
    slug: "toxicology-overdose",
    title: "Toxicology & Overdose",
    bodySystem: "Emergency",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGACNP", "PNP", "PMHNP", "ENP"],
    recognize: "Start with toxidrome and ABCs: altered mental status, pupil size, temperature, bowel sounds, secretions, skin, ECG, glucose, and collateral history. Assume mixed ingestion until proven otherwise.",
    diagnostics: "Check bedside glucose and ECG early; targeted acetaminophen level is important in many intentional/unknown ingestions because early toxicity may be silent. Additional labs depend on agent and physiology.",
    priorities: "Stabilize airway/ventilation/circulation, give agent-specific antidotes when indicated, use poison control/toxicology, and consider decontamination only in selected circumstances.",
    medicationSafety: "Naloxone treats opioid-induced respiratory depression, not 'wakefulness.' N-acetylcysteine is time-sensitive for acetaminophen toxicity; sodium bicarbonate is central in sodium-channel blocker cardiotoxicity.",
    redFlags: "Respiratory depression, seizures, dysrhythmia/wide QRS, severe acidosis, hyperthermia, shock, or suicidal intent requires emergency care.",
    examTraps: "A normal early exam does not clear an extended-release or delayed-toxicity ingestion. Do not induce emesis.",
    sourceKeys: ["ACMT_AACT_CURRENT"],
  },
  {
    slug: "shock",
    title: "Shock Recognition",
    titleAliases: ["Shock: Hemodynamic Monitoring"],
    slugAliases: ["shock-syndromes-np"],
    bodySystem: "Emergency",
    applicableExams: ["AGACNP", "ENP", "AANP-FNP", "ANCC-FNP"],
    recognize: "Shock is inadequate tissue perfusion; BP can be normal early. Use skin temperature, mentation, urine output, capillary refill, pulse pressure, lactate, and bedside ultrasound patterns to separate distributive, hypovolemic, cardiogenic, and obstructive causes.",
    diagnostics: "Trend lactate and organ function, obtain ECG, bedside echo/POCUS when available, and source-specific testing without delaying resuscitation. Reassess after every major intervention.",
    priorities: "Treat the physiology: fluids/blood for appropriate volume loss, vasopressors for distributive shock after fluid assessment, reperfusion/inotropes/mechanical support for selected cardiogenic shock, and immediate relief of obstructive causes.",
    medicationSafety: "Large indiscriminate fluid loads can worsen cardiogenic/obstructive shock. Vasopressors require safe access and close monitoring; medication choice follows shock type and rhythm.",
    redFlags: "Persistent hypotension, altered mentation, oliguria, rising lactate, severe acidosis, or signs of tamponade/tension pneumothorax/massive PE is critical illness.",
    examTraps: "Do not wait for systolic BP <90 to call shock. 'Warm' extremities do not exclude severe distributive shock.",
    sourceKeys: ["SURVIVING_SEPSIS_CURRENT", "AHA_SHOCK_CURRENT"],
  },
  {
    slug: "anxiety-panic",
    title: "Anxiety & Panic Disorders",
    bodySystem: "Psychiatric",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PMHNP", "ENP"],
    recognize: "Excessive difficult-to-control worry suggests GAD; abrupt surges of intense fear with autonomic symptoms suggest panic attacks. Always consider thyroid disease, arrhythmia, asthma, stimulant/caffeine use, withdrawal, and medication effects.",
    diagnostics: "Diagnosis is clinical after assessing duration, impairment, triggers, avoidance, substances, and medical mimics. Use validated scales to track severity, not as stand-alone diagnostic tests.",
    priorities: "CBT and SSRIs/SNRIs are first-line for many anxiety disorders. Teach paced breathing/exposure principles when appropriate and schedule follow-up to assess activation, adherence, function, and comorbidity.",
    medicationSafety: "Benzodiazepines can cause dependence, falls, cognitive impairment, and dangerous respiratory depression with opioids/alcohol; they are not preferred long-term treatment for most anxiety disorders.",
    redFlags: "Chest pain with ischemic features, syncope, severe dyspnea, suicidality, intoxication/withdrawal, or new neurologic symptoms requires medical/emergency assessment rather than assuming panic.",
    examTraps: "Do not diagnose panic disorder from one panic attack. Anxiety can be the presenting symptom of serious cardiopulmonary or endocrine disease.",
    sourceKeys: ["APA_ANXIETY_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
