import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch44 = [
  {
    slug: "acute-angle-closure-glaucoma",
    title: "Acute Angle-Closure Glaucoma",
    bodySystem: "HEENT",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "ENP"],
    recognize: "Sudden severe unilateral eye pain, headache, nausea/vomiting, blurred vision/halos, red eye, mid-dilated poorly reactive pupil and a firm globe suggests acute angle closure. It is a vision-threatening emergency and can be mistaken for migraine or gastroenteritis.",
    diagnostics: "Check visual acuity and urgent intraocular pressure when equipment/expertise is available, but do not delay ophthalmology transfer for elaborate office testing. Slit-lamp/gonioscopy confirms the closed angle; examine the fellow eye because anatomic risk is often bilateral.",
    priorities: "Begin rapid pressure-lowering therapy under emergency/ophthalmology guidance—typically topical beta blocker, alpha agonist and carbonic-anhydrase inhibitor with additional systemic therapy as needed—then definitive laser peripheral iridotomy once pressure/corneal clarity permits.",
    medicationSafety: "Pilocarpine is less effective at extremely high pressure until iris perfusion improves and is not a stand-alone first step. Acetazolamide has sulfonamide-related, renal/electrolyte and acid-base considerations; topical beta blockers can worsen bradycardia/asthma.",
    redFlags: "Any acute painful red eye with vision loss, fixed/mid-dilated pupil, very high IOP or severe nausea/vomiting requires immediate ophthalmology/emergency treatment.",
    examTraps: "Do not diagnose conjunctivitis in a painful eye with reduced vision and do not wait for optic-nerve damage before referral. Mydriatic/anticholinergic drugs can precipitate angle closure in susceptible anatomy.",
    sourceKeys: ["AAO_ANGLE_CLOSURE_CURRENT"],
  },
  {
    slug: "retinal-detachment",
    title: "Retinal Detachment & Acute Flashes/Floaters",
    bodySystem: "HEENT",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "ENP"],
    recognize: "New monocular flashes, sudden increase in floaters, a curtain/shadow or peripheral-to-central field loss suggests retinal tear/detachment, especially with high myopia, trauma, prior cataract surgery or retinal disease. Posterior vitreous detachment is common but can cause a retinal tear.",
    diagnostics: "Check visual acuity, pupils and confrontation fields, then arrange urgent dilated retinal examination; bedside ocular ultrasound can support diagnosis when the fundus cannot be visualized but does not replace ophthalmology when symptoms are high-risk.",
    priorities: "Retinal tear requires prompt laser/cryo treatment and established detachment needs urgent vitreoretinal repair; macula-on detachment is especially time-sensitive. Protect the eye and follow positioning/travel instructions from retina specialists when intraocular gas is used.",
    medicationSafety: "Do not place patients with intraocular gas on nitrous oxide anesthesia or high-altitude/air travel until cleared because gas expansion can cause dangerous IOP elevation. Anticoagulation decisions are individualized to the retinal procedure and thrombotic indication.",
    redFlags: "Curtain-like field loss, central vision change, afferent pupillary defect, trauma with suspected globe injury or acute flashes/floaters plus reduced vision requires same-day/emergency ophthalmology.",
    examTraps: "Do not reassure a patient with new flashes/floaters solely because visual acuity is still 20/20; peripheral tear/detachment may preserve central acuity initially.",
    sourceKeys: ["AAO_RETINAL_BREAKS_CURRENT"],
  },
  {
    slug: "red-eye-keratitis-conjunctivitis",
    title: "Red Eye: Conjunctivitis vs Keratitis/Uveitis",
    bodySystem: "HEENT",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PNP", "ENP"],
    recognize: "Conjunctivitis usually causes irritation/discharge with preserved vision and minimal photophobia; corneal abrasion/keratitis causes pain, foreign-body sensation and fluorescein staining; anterior uveitis causes consensual photophobia and ciliary flush. Severe pain or reduced vision is never routine 'pink eye.'",
    diagnostics: "Always check visual acuity before treatment, then pupils, photophobia, fluorescein staining and contact-lens use. Slit-lamp and ophthalmology evaluation are required for corneal ulcer/infiltrate, uveitis, herpes, trauma or diagnostic uncertainty.",
    priorities: "Use supportive care for most viral conjunctivitis, targeted topical antibiotic only for appropriate bacterial disease, and urgent antipseudomonal ophthalmic therapy/ophthalmology for contact-lens keratitis. Remove contact lenses and avoid sharing eye products.",
    medicationSafety: "Never prescribe topical anesthetics for unsupervised home use because they delay healing and can damage the cornea. Topical ocular corticosteroids should not be started in an undifferentiated red eye because herpes keratitis and infection can worsen.",
    redFlags: "Vision loss, severe pain, marked photophobia, corneal opacity/ulcer, fixed pupil, proptosis, painful EOM or contact-lens wearer with corneal defect requires urgent ophthalmic care.",
    examTraps: "Purulent discharge is not the only determinant of bacterial disease and antibiotics do not shorten uncomplicated viral conjunctivitis meaningfully. A contact-lens wearer with pain is keratitis until safely excluded.",
    sourceKeys: ["AAO_RED_EYE_CURRENT", "AAO_KERATITIS_CURRENT"],
  },
  {
    slug: "sudden-sensorineural-hearing-loss",
    title: "Sudden Sensorineural Hearing Loss",
    bodySystem: "HEENT",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "ENP"],
    recognize: "Sudden unilateral hearing loss developing over hours to a few days—often with tinnitus or fullness—may be sensorineural and time-sensitive. Patients often assume earwax or 'a blocked ear'; bedside Weber/Rinne can rapidly distinguish conductive from sensorineural patterns.",
    diagnostics: "Perform otoscopy and tuning-fork testing immediately, obtain urgent audiometry and evaluate focal neurologic/vestibular features. MRI of the internal auditory canals/brain is used to assess retrocochlear causes; routine head CT is low yield for uncomplicated SSNHL.",
    priorities: "Arrange urgent ENT/audiology and offer corticosteroid treatment within the recommended early treatment window when idiopathic SSNHL is suspected and contraindications permit; intratympanic steroid therapy is used as initial or salvage therapy in selected patients.",
    medicationSafety: "Systemic steroids worsen glucose, mood, infection and BP and should be individualized; intratympanic therapy reduces systemic exposure but has tympanic discomfort/perforation risk. Avoid empiric antivirals or vasodilators without another indication.",
    redFlags: "Sudden hearing loss plus focal neurologic deficit, severe vertigo with central signs, bilateral loss or meningitis/trauma symptoms requires emergency neurologic evaluation.",
    examTraps: "Do not delay treatment for weeks waiting on routine referral or label sudden unilateral hearing loss cerumen when the canal is clear. A normal otoscopic exam does not mean the hearing loss is benign.",
    sourceKeys: ["AAO_SSNHL_CURRENT"],
  },
  {
    slug: "acute-bacterial-rhinosinusitis",
    title: "Acute Bacterial Rhinosinusitis",
    bodySystem: "HEENT",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PNP"],
    recognize: "Most acute sinus symptoms are viral. Bacterial rhinosinusitis is more likely with persistent symptoms without improvement for about 10 days, severe fever/purulent discharge or facial pain for several days, or 'double worsening' after initial viral improvement.",
    diagnostics: "Diagnosis is clinical in uncomplicated cases; routine sinus radiographs/CT and nasal cultures are not needed. Image urgently only when orbital/intracranial complication, invasive fungal disease or another diagnosis is suspected.",
    priorities: "Use symptomatic saline/intranasal corticosteroid strategies and either watchful waiting with reliable follow-up or guideline-directed antibiotics when bacterial criteria and patient context support treatment. Amoxicillin-clavulanate is a common first-line choice when antibiotics are indicated.",
    medicationSafety: "Avoid routine macrolide empiric therapy because pneumococcal resistance is high. Oral decongestants can worsen hypertension/arrhythmia and topical decongestants used too long cause rhinitis medicamentosa.",
    redFlags: "Periorbital edema, painful/restricted EOM, vision change, proptosis, severe frontal headache, meningismus, altered mental status or immunocompromised patient with necrotic nasal findings requires emergency imaging/specialty care.",
    examTraps: "Green/yellow mucus alone does not diagnose bacterial sinusitis and antibiotics are not indicated simply because symptoms lasted 3-5 days.",
    sourceKeys: ["IDSA_ABRS_CURRENT", "AAO_SINUSITIS_CURRENT"],
  },
  {
    slug: "otitis-externa-necrotizing",
    title: "Otitis Externa & Necrotizing Otitis Externa",
    bodySystem: "HEENT",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PNP", "ENP"],
    recognize: "Acute otitis externa causes ear-canal pain, pruritus and discharge with tragal/pinna tenderness. Severe deep otalgia—often worse at night—in an older adult with diabetes/immunocompromise, granulation tissue or cranial neuropathy suggests necrotizing otitis externa/skull-base osteomyelitis.",
    diagnostics: "Uncomplicated OE is clinical. Culture severe/refractory disease and obtain inflammatory markers plus CT/MRI/nuclear imaging as guided by ENT when necrotizing infection is suspected; assess glucose/immune risk.",
    priorities: "Use topical antibiotic with or without steroid and aural toilet/wick for uncomplicated disease while keeping the ear dry; systemic antipseudomonal therapy and urgent ENT/infectious-disease care are required for necrotizing disease.",
    medicationSafety: "Avoid ototoxic aminoglycoside-containing drops when tympanic-membrane perforation is known or suspected unless specialist-directed; fluoroquinolone drops are generally safer for an open middle ear. Systemic fluoroquinolones have significant tendon/CNS/QT/aortic adverse-effect warnings.",
    redFlags: "Cranial nerve deficit, severe disproportionate nocturnal pain, granulation tissue, fever/systemic illness or diabetes/immunosuppression with refractory OE requires urgent evaluation for skull-base osteomyelitis.",
    examTraps: "Do not prescribe oral antibiotics routinely for uncomplicated swimmer's ear and do not miss necrotizing disease because the external canal findings seem modest.",
    sourceKeys: ["AAO_OTITIS_EXTERNA_CURRENT"],
  },
  {
    slug: "acute-otitis-media",
    title: "Acute Otitis Media Across the Lifespan",
    bodySystem: "HEENT",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PNP"],
    recognize: "AOM requires acute symptoms plus middle-ear effusion and inflammatory tympanic-membrane findings—moderate/severe bulging or new otorrhea, or mild bulging with recent ear pain/intense erythema. A red tympanic membrane alone after crying or viral URI is not diagnostic.",
    diagnostics: "Use pneumatic otoscopy/tympanometry when uncertain; imaging is unnecessary for uncomplicated AOM. Recurrent disease, persistent effusion with hearing/language concern or adult unilateral effusion may require ENT evaluation for underlying obstruction.",
    priorities: "Provide analgesia to every symptomatic patient; use observation in selected lower-risk children with reliable follow-up and amoxicillin or guideline-directed alternative when antibiotics are indicated. Recurrent AOM/effusion management is based on episode frequency, effusion and developmental/hearing impact.",
    medicationSafety: "High-dose amoxicillin is used for many children but choice changes with recent amoxicillin, purulent conjunctivitis, allergy or treatment failure. Avoid unnecessary broad-spectrum antibiotics and prophylactic chronic antibiotics.",
    redFlags: "Mastoid swelling/tenderness, facial weakness, severe systemic illness, meningismus, vertigo/neurologic symptoms or immunocompromised host with refractory disease requires urgent specialty evaluation.",
    examTraps: "Otitis media with effusion is not acute bacterial AOM and does not need antibiotics. Ear pulling in an afebrile infant without bulging/effusion is not enough for diagnosis.",
    sourceKeys: ["AAP_AOM_CURRENT", "AAO_OME_CURRENT"],
  },
  {
    slug: "epistaxis-management",
    title: "Epistaxis: Office & Emergency Management",
    bodySystem: "HEENT",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "ENP"],
    recognize: "Most epistaxis is anterior and responds to direct compression; posterior bleeding is more common in older/hypertensive/anticoagulated patients and can cause brisk bilateral nasal/oropharyngeal bleeding without a visible anterior source.",
    diagnostics: "Assess airway/hemodynamics first, medication/anticoagulant use and recurrent unilateral symptoms; visualize after suction/clot removal when safe. CBC/coagulation/type-and-screen are selective for significant/recurrent bleeding rather than routine for a brief anterior nosebleed.",
    priorities: "Have the patient lean forward and compress the soft nose continuously, add topical vasoconstrictor/anesthetic, then cautery or packing when a source persists. Posterior/uncontrolled bleeding requires ENT and monitored admission/interventional management.",
    medicationSafety: "Avoid bilateral caustic septal cautery that increases perforation risk; topical vasoconstrictors need caution in severe cardiovascular disease but local benefit may outweigh risk in active bleeding. Anticoagulant reversal is reserved for significant bleeding and balanced against thrombotic indication.",
    redFlags: "Airway compromise, hemodynamic instability, posterior bleeding, major anemia, bleeding disorder or persistent bleeding despite packing requires emergency/ENT care.",
    examTraps: "Do not tilt the head backward—it promotes swallowing/aspiration of blood. Hypertension may accompany epistaxis but rapidly lowering asymptomatic BP does not replace local hemorrhage control.",
    sourceKeys: ["AAO_EPISTAXIS_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
