import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch31 = [
  {
    slug: "hepatic-encephalopathy-pathophysiology",
    title: "Hepatic Encephalopathy: Ammonia Neurotoxicity & Astrocyte Swelling",
    slugAliases: ["gi-patho-hepatic-encephalopathy-np"],
    bodySystem: "Gastrointestinal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Hepatic encephalopathy is a clinical neuropsychiatric syndrome in advanced liver disease or portosystemic shunting. Ammonia contributes to astrocyte dysfunction and swelling, but inflammation, altered neurotransmission and precipitating illness also matter; the serum ammonia value does not grade clinical severity reliably.",
    diagnostics: "Diagnose HE clinically after excluding common mimics such as hypoglycemia, intoxication, medication effect, stroke, CNS infection and severe electrolyte disturbance. Search for precipitating infection, GI bleeding, constipation, dehydration, kidney injury and sedatives; serial ammonia levels should not guide routine response to therapy.",
    priorities: "Identify and reverse the precipitant, start lactulose for overt HE and titrate to roughly 2-3 soft bowel movements daily, then add rifaximin for recurrent/persistent episodes when indicated. Maintain nutrition and avoid unnecessary protein restriction while addressing transplant candidacy in recurrent decompensation.",
    medicationSafety: "Excess lactulose can cause diarrhea, hypovolemia, hypernatremia and recurrent HE; titrate rather than pursuing maximal stool frequency. Benzodiazepines, opioids and other CNS depressants can worsen mental status and should be minimized when possible.",
    redFlags: "Rapidly declining consciousness, inability to protect the airway, focal neurologic deficit, seizure, severe GI bleeding, sepsis or acute liver failure with encephalopathy requires urgent inpatient/critical-care evaluation.",
    examTraps: "Do not diagnose or trend HE by ammonia concentration alone. A normal or low ammonia should prompt reconsideration of the diagnosis, while an elevated value without compatible clinical findings does not prove HE.",
    sourceKeys: ["AASLD_HE_CURRENT", "AASLD_CIRRHOSIS_CURRENT"],
  },
  {
    slug: "ibd-mucosal-immune-pathophysiology",
    title: "Inflammatory Bowel Disease: Mucosal Immune Dysregulation in Crohn's vs UC",
    slugAliases: ["gi-patho-ibd-mucosal-immune-np"],
    bodySystem: "Gastrointestinal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP"],
    recognize: "IBD reflects dysregulated mucosal immune responses in genetically susceptible hosts interacting with the microbiome and epithelial barrier. Crohn disease can involve any GI segment with transmural, discontinuous inflammation; ulcerative colitis is limited to the colon with continuous mucosal inflammation beginning at the rectum.",
    diagnostics: "Use symptoms, CBC/CMP/CRP, stool infection testing and fecal calprotectin as appropriate, then confirm disease with endoscopy and histology; cross-sectional small-bowel imaging is important for Crohn disease extent and complications. No single cytokine, antibody or calprotectin cutoff independently defines the diagnosis.",
    priorities: "Choose induction and maintenance therapy by severity, location, complications and prognostic risk, with early effective biologic/targeted therapy for appropriate moderate-severe disease. Treat-to-target emphasizes symptom control plus objective inflammatory improvement and mucosal healing where appropriate.",
    medicationSafety: "Systemic corticosteroids are for induction, not chronic maintenance. Before biologic or targeted immunosuppression, assess infection risk, TB/hepatitis status and vaccines; JAK inhibitors, anti-TNF and other agents have distinct thrombosis, infection, malignancy and pregnancy considerations.",
    redFlags: "Toxic megacolon, perforation, major bleeding, obstruction, abscess/fistula sepsis, severe dehydration or systemic toxicity requires urgent inpatient GI/surgical management.",
    examTraps: "Do not reduce Crohn versus UC to one cytokine pathway or assume granulomas are required for Crohn disease. Smoking worsens Crohn disease, but nicotine is not prescribed as UC therapy despite epidemiologic associations.",
    sourceKeys: ["ACG_CROHN_CURRENT", "ACG_UC_CURRENT", "AGA_IBD_CURRENT"],
  },
  {
    slug: "acute-liver-failure-acetaminophen-pathophysiology",
    title: "Acute Liver Failure: Acetaminophen Toxicity & Coagulopathy Cascade",
    slugAliases: ["gi-patho-acute-liver-failure-np"],
    bodySystem: "Gastrointestinal",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Acute liver failure is acute hepatic injury with coagulopathy and encephalopathy in a patient without established cirrhosis. Acetaminophen toxicity causes NAPQI-mediated centrilobular necrosis after glutathione depletion, but ischemia, viral hepatitis, autoimmune hepatitis, Wilson disease and idiosyncratic drug injury are critical alternatives.",
    diagnostics: "Immediately obtain acetaminophen concentration and ingestion timing when possible, INR, glucose, lactate, creatinine, bilirubin and aminotransferases while evaluating other ALF causes. The Rumack-Matthew nomogram applies only to a known single acute ingestion with a timed level, not repeated supratherapeutic or unknown-time exposure.",
    priorities: "Start N-acetylcysteine promptly when a potentially toxic acetaminophen exposure is suspected or ALF may be acetaminophen-related; do not wait for evolving hepatotoxicity. Admit ALF with encephalopathy to intensive care and contact a transplant center early because deterioration and cerebral edema can be rapid.",
    medicationSafety: "NAC remains beneficial even when presentation is delayed and is generally safe; anaphylactoid infusion reactions are usually managed without permanently abandoning necessary therapy. Do not give prophylactic plasma simply to normalize INR when there is no bleeding/procedure because it obscures prognostic synthetic-function trends.",
    redFlags: "Worsening encephalopathy, severe acidosis/lactate elevation, hypoglycemia, progressive INR, AKI, cerebral edema, shock or Wilson-associated ALF requires urgent transplant-center management.",
    examTraps: "Do not apply the Rumack-Matthew nomogram to chronic repeated dosing or unknown ingestion time. Extremely high aminotransferases with relatively low bilirubin suggest acetaminophen or ischemic injury but do not alone prove the cause.",
    sourceKeys: ["AASLD_ACUTE_LIVER_FAILURE_CURRENT", "TOX_ACETAMINOPHEN_CURRENT"],
  },
  {
    slug: "dic-pathophysiology",
    title: "DIC: Simultaneous Thrombosis & Hemorrhage Pathogenesis",
    slugAliases: ["heme-patho-dic-pathogenesis-np"],
    bodySystem: "Hematology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "WHNP", "ENP"],
    recognize: "Disseminated intravascular coagulation is systemic pathologic coagulation activation with fibrin formation, platelet/factor consumption and secondary fibrinolysis, producing the paradox of microvascular thrombosis plus bleeding. Sepsis, obstetric catastrophe, major trauma and malignancy are classic triggers.",
    diagnostics: "Trend platelet count, PT, fibrinogen and D-dimer/fibrin-related markers in clinical context and use a validated DIC score when appropriate. A falling fibrinogen may be important even before it becomes frankly low because fibrinogen is an acute-phase reactant; schistocytes can occur but are not specific.",
    priorities: "Treat the underlying trigger immediately. Give platelets, fibrinogen replacement or plasma when clinically indicated for active bleeding, procedures or severe deficits; use anticoagulation selectively when thrombosis predominates and bleeding risk permits rather than as routine therapy for acute bleeding DIC.",
    medicationSafety: "Blood products should be targeted to clinical bleeding/procedural risk and laboratory deficits, not given automatically to normalize every test. In acute promyelocytic leukemia, urgent disease-specific therapy is central; avoid delaying hematology treatment while repeatedly correcting labs alone.",
    redFlags: "Shock, uncontrolled hemorrhage, digital/limb ischemia, rapidly progressive organ failure, intracranial bleeding or obstetric DIC requires emergency critical-care and cause-specific management.",
    examTraps: "Do not diagnose DIC from an elevated D-dimer alone. TTP can also produce thrombocytopenia and schistocytes but typically does not consume coagulation factors in the same pattern, so PT/fibrinogen context is crucial.",
    sourceKeys: ["ISTH_DIC_CURRENT", "ASH_DIC_CURRENT"],
  },
  {
    slug: "sickle-cell-vaso-occlusion-pathophysiology",
    title: "Sickle Cell Disease: Vaso-Occlusive Crisis & Hydroxyurea Mechanism",
    slugAliases: ["heme-patho-sickle-cell-vasocclusion-np"],
    bodySystem: "Hematology",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PNP", "WHNP", "ENP"],
    recognize: "Deoxygenated HbS polymerizes, making erythrocytes rigid and adhesive; vaso-occlusion, hemolysis, endothelial dysfunction and chronic inflammation drive pain, acute chest syndrome, stroke, splenic dysfunction, kidney disease and other organ damage. Genotype and HbF level modify severity but do not eliminate risk.",
    diagnostics: "Confirm genotype with hemoglobin analysis and use CBC/reticulocytes, bilirubin/LDH and organ-specific testing to evaluate complications. In children with HbSS/HbSβ0, transcranial Doppler screening identifies high stroke risk; a sudden hemoglobin drop with low reticulocytes suggests aplastic crisis.",
    priorities: "Use hydroxyurea as foundational disease-modifying therapy for eligible patients because higher fetal hemoglobin reduces HbS polymerization and clinical events. During vaso-occlusive pain give prompt individualized analgesia, hydration only to euvolemia, and actively prevent/detect acute chest syndrome; use transfusion/exchange transfusion for defined complications.",
    medicationSafety: "Hydroxyurea requires blood-count monitoring and reproductive counseling but should not be withheld because of outdated cancer fears. Voxelotor/Oxbryta should not be prescribed—it was withdrawn from the U.S. market in 2024 because emerging safety data changed its benefit-risk profile.",
    redFlags: "Fever in functional asplenia, acute chest syndrome, stroke symptoms, priapism, severe anemia with reticulocytopenia, splenic sequestration, hypoxemia or multiorgan failure requires urgent/emergency care.",
    examTraps: "Do not give oxygen routinely for uncomplicated pain crisis when the patient is not hypoxemic, and do not use aggressive excess IV fluid as routine treatment. Hydroxyurea reduces complications but does not eliminate the need for age-specific stroke and infection prevention.",
    sourceKeys: ["ASH_SCD_CURRENT", "ASH_HYDROXYUREA_CURRENT", "FDA_VOXELOTOR_WITHDRAWAL_2024"],
  },
  {
    slug: "antimicrobial-resistance-mechanisms",
    title: "Antimicrobial Resistance: MRSA, ESBL & Carbapenem-Resistant Organisms",
    slugAliases: ["infectious-patho-antibiotic-resistance-np"],
    bodySystem: "Infectious Disease",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PNP", "ENP"],
    recognize: "Resistance mechanisms include altered drug targets, drug-inactivating enzymes, reduced permeability/efflux and target protection. MRSA uses altered PBP2a; ESBL-producing Enterobacterales hydrolyze many penicillins/cephalosporins; CRE may use carbapenemases or combined permeability and beta-lactamase mechanisms.",
    diagnostics: "Obtain cultures from the true infection site before antibiotics when feasible and use organism identification, MIC/susceptibility plus local antibiogram and prior colonization history. Molecular resistance markers help but must be interpreted with phenotype and infection site.",
    priorities: "Use the narrowest active agent that achieves adequate exposure at the infection site, de-escalate when culture data return and use current IDSA organism-specific guidance for ESBL, CRE, difficult-to-treat Pseudomonas, CRAB and other resistant gram-negatives.",
    medicationSafety: "Do not assume MRSA means resistance to every beta-lactam—selected anti-MRSA cephalosporins retain activity. For ESBL bloodstream/serious extra-urinary infection, carbapenems remain important; avoid nephrotoxic salvage agents when a safer active newer beta-lactam is available.",
    redFlags: "Septic shock, rapidly progressive infection, neutropenia, CNS infection, endocarditis, prosthetic infection or an isolate resistant to standard active options requires urgent infectious-disease and inpatient management.",
    examTraps: "Colonization is not infection and a resistant organism on a superficial culture should not trigger broad therapy automatically. Susceptibility and site matter more than memorizing one drug for each acronym.",
    sourceKeys: ["IDSA_AMR_2024", "IDSA_MRSA_CURRENT"],
  },
  {
    slug: "viral-replication-antiviral-targets",
    title: "Viral Pathogenesis: Replication Cycles & Antiviral Drug Targets",
    slugAliases: ["infectious-patho-viral-replication-np"],
    bodySystem: "Infectious Disease",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "PNP", "WHNP", "ENP"],
    recognize: "Antivirals work by interrupting virus-specific steps such as entry, genome replication, protease-mediated maturation or virion release. Understanding the viral target explains why therapy differs among HIV, HBV/HCV, herpesviruses, influenza and SARS-CoV-2 and why resistance emerges with incomplete suppression.",
    diagnostics: "Use pathogen-appropriate antigen/antibody, nucleic-acid or viral-load testing rather than one generic 'viral panel.' HIV requires current antigen/antibody plus RNA strategies for acute infection; HCV antibody must be followed by RNA to confirm current infection; HBV requires a full serologic pattern plus DNA when active disease is present.",
    priorities: "Start rapid combination ART for HIV, curative direct-acting antivirals for nearly all chronic HCV, suppressive nucleos(t)ide therapy for eligible chronic HBV, prompt acyclovir for HSV encephalitis and timely influenza/COVID antivirals for high-risk patients according to current criteria.",
    medicationSafety: "Antiviral prescribing is interaction-heavy: ritonavir-boosted regimens inhibit CYP3A, tenofovir formulations differ in renal/bone effects, acyclovir requires renal dose awareness, and stopping HBV-active therapy can cause hepatitis flare. Verify current interaction resources rather than relying on class memory.",
    redFlags: "HSV encephalitis, severe influenza/COVID respiratory failure, acute HIV with severe systemic illness, HBV flare with liver failure or opportunistic infection in advanced HIV requires urgent specialty/inpatient care.",
    examTraps: "Do not teach obsolete population screening such as the old baby-boomer-only HCV strategy; U.S. screening is now universal for adults with repeat testing for ongoing risk. Viral replication models explain drug targets but do not determine treatment without current guideline eligibility.",
    sourceKeys: ["DHHS_HIV_CURRENT", "CDC_HCV_CURRENT", "CDC_FLU_2026", "AASLD_IDSA_HCV_CURRENT"],
  },
  {
    slug: "schizophrenia-neurobiology",
    title: "Schizophrenia Neurobiology: Dopamine Hypothesis & Glutamate Theory",
    slugAliases: ["psych-patho-schizophrenia-dopamine-np"],
    bodySystem: "Psychiatric",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PMHNP"],
    recognize: "Schizophrenia is a neurodevelopmental syndrome with positive, negative and cognitive symptoms. Dopamine-pathway and glutamate/NMDA models help explain drug effects, but the illness is not a proven simple 'dopamine excess' and no neurotransmitter blood test diagnoses it.",
    diagnostics: "Confirm persistent psychotic symptoms and functional decline while excluding substance/medication effects, mood disorders with psychosis, delirium and selected neurologic/endocrine/infectious causes. Baseline weight/BMI, BP, glucose/A1C, lipids and movement-disorder assessment support safe antipsychotic treatment.",
    priorities: "Use a person-centered antipsychotic plus coordinated psychosocial treatment; offer long-acting injectable formulations based on patient preference or adherence needs. Clozapine is recommended for treatment-resistant schizophrenia and for substantial persistent suicide risk when clinically appropriate.",
    medicationSafety: "Monitor antipsychotics for metabolic effects, EPS/tardive dyskinesia, prolactin and QT/orthostasis according to agent. Clozapine still requires ANC monitoring because severe neutropenia remains a risk, but the FDA removed the mandatory U.S. Clozapine REMS in June 2025.",
    redFlags: "Command hallucinations with danger, catatonia, severe agitation, suicide risk, neuroleptic malignant syndrome, clozapine-associated myocarditis symptoms or severe neutropenia/infection requires urgent evaluation.",
    examTraps: "Do not teach mandatory REMS enrollment for clozapine in the U.S.; it is obsolete. Negative and cognitive symptoms are major drivers of disability and are not simply the inverse of mesolimbic dopamine activity.",
    sourceKeys: ["APA_SCHIZOPHRENIA_CURRENT", "FDA_CLOZAPINE_REMS_REMOVED_2025"],
  },
  {
    slug: "substance-use-reward-circuitry",
    title: "Substance Use Disorders: Reward Circuitry & Medications for Addiction Treatment",
    titleAliases: ["Substance Use Disorders: Reward Circuitry & Medication-Assisted Treatment"],
    slugAliases: ["psych-patho-substance-use-neuroscience-np"],
    bodySystem: "Psychiatric",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PMHNP", "WHNP", "ENP"],
    recognize: "Substance use disorder is a chronic relapsing condition involving reward, learning, stress and executive-control circuitry—not a moral failure. Tolerance/withdrawal can occur with prescribed exposure and do not alone establish SUD; diagnosis depends on impaired control, risky use and continued use despite harm.",
    diagnostics: "Use validated screening plus DSM criteria, define exact substances and last use, and assess overdose/withdrawal risk, pregnancy, infection, psychiatric comorbidity and prescribed controlled substances. Toxicology can support exposure but does not diagnose addiction or prove current impairment.",
    priorities: "For OUD, offer buprenorphine or methadone as first-line mortality-reducing treatment and extended-release naltrexone when an opioid-free interval and patient preference make it appropriate. Treat alcohol/tobacco disorders with evidence-based medications and pair pharmacotherapy with harm reduction and psychosocial support.",
    medicationSafety: "The federal X-waiver is gone; practitioners with appropriate DEA authority can prescribe buprenorphine for OUD subject to current controlled-substance requirements. Benzodiazepines/alcohol plus opioids increase overdose risk, but concurrent benzodiazepine use is not a reason to withhold lifesaving OUD medication without careful management.",
    redFlags: "Opioid respiratory depression, severe alcohol/benzodiazepine withdrawal, seizure, delirium, stimulant hyperthermia/chest pain, suicidality or pregnancy with severe withdrawal risk requires urgent monitored care.",
    examTraps: "Do not call physiologic dependence addiction by itself and do not teach the obsolete X-waiver. Naloxone reverses opioid respiratory depression but does not replace definitive OUD treatment after overdose.",
    sourceKeys: ["SAMHSA_MAT_ACT_CURRENT", "ASAM_OUD_CURRENT", "ASAM_ALCOHOL_WITHDRAWAL_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
