import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch42 = [
  {
    slug: "cauda-equina-syndrome",
    title: "Cauda Equina Syndrome",
    bodySystem: "Neurological",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Severe low-back/radicular pain plus new urinary retention or overflow, saddle anesthesia, bilateral leg symptoms, reduced anal tone or progressive lower-extremity weakness is cauda equina syndrome until excluded. Complete painless retention is late; earlier bladder sensory change or altered urinary stream can precede it.",
    diagnostics: "Perform a focused motor, sensory, reflex, perineal/saddle and bladder assessment and obtain urgent MRI of the lumbosacral spine. Post-void residual can support concern but neither a low value nor absence of one classic symptom safely excludes CES when the neurologic pattern is concerning.",
    priorities: "Arrange emergency spinal surgical/neurosurgical consultation and decompression for compressive CES as soon as possible after diagnosis; treat the cause, catheterize significant retention when needed and preserve hemodynamic/neurologic stability during transfer.",
    medicationSafety: "Analgesia should not delay imaging or neurologic reassessment; steroids are disease-specific and are not a universal treatment for every disc-related CES. Anticoagulant use raises concern for spinal hematoma and affects urgent procedural planning.",
    redFlags: "New saddle anesthesia, urinary retention/incontinence, rapidly progressive bilateral weakness, loss of rectal tone or severe back pain in cancer/infection/anticoagulation context requires emergency MRI and spine consultation.",
    examTraps: "Do not wait for the full triad or complete bladder paralysis. Sciatica alone is common; the high-risk change is new sacral/bladder/bowel dysfunction or progressive bilateral neurologic deficit.",
    sourceKeys: ["AANS_CAuda_EQUINA_CURRENT", "NASS_SPINE_EMERGENCY_CURRENT"],
  },
  {
    slug: "spinal-epidural-abscess",
    title: "Spinal Epidural Abscess",
    bodySystem: "Neurological",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Spinal epidural abscess can begin with severe focal back pain and progress to radicular pain, weakness, sensory change and bowel/bladder dysfunction. Fever is often absent; bacteremia, injection drug use, diabetes, immunosuppression, spinal procedure or indwelling infection raise risk.",
    diagnostics: "Check CBC, ESR/CRP and blood cultures but obtain urgent contrast-enhanced MRI of the involved spine when suspicion is meaningful; image more extensive levels when symptoms/localization are unclear. Do not use a normal WBC count or lack of fever to rule it out.",
    priorities: "Obtain urgent neurosurgical/spine and infectious-disease input, start empiric IV antibiotics after blood cultures when feasible—without delaying therapy in sepsis or neurologic compromise—and pursue decompression/source control for progressive deficit, instability or selected abscess characteristics.",
    medicationSafety: "Empiric therapy should cover S. aureus including MRSA plus gram-negative organisms according to host/exposure until cultures return; renal dosing matters. Steroids are not routine treatment and can worsen infection when given reflexively for back pain.",
    redFlags: "New weakness, bowel/bladder dysfunction, saddle anesthesia, sepsis, rapidly progressive pain or cord/cauda-equina compression on imaging requires immediate inpatient surgical management.",
    examTraps: "The classic back-pain/fever/neurologic-deficit triad is insensitive. Do not dismiss a high-risk patient with severe focal pain because the initial neurologic exam is normal.",
    sourceKeys: ["IDSA_VERTEBRAL_OSTEOMYELITIS_CURRENT", "NEUROSURGERY_SEA_CURRENT"],
  },
  {
    slug: "malignant-spinal-cord-compression",
    title: "Malignant Spinal Cord Compression",
    bodySystem: "Neurological",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "New severe focal back pain—especially nocturnal, progressive or movement-related—in a patient with cancer can precede weakness, sensory level, gait dysfunction and sphincter changes from epidural metastatic spinal cord compression. Neurologic preservation depends on treating before paralysis is established.",
    diagnostics: "Perform a complete neurologic exam and obtain urgent contrast MRI of the whole spine when metastatic compression is suspected because multifocal disease is common. Plain radiographs do not exclude epidural disease.",
    priorities: "Give corticosteroid therapy promptly when significant neurologic compression is suspected unless a contraindication or lymphoma-specific diagnostic issue changes the plan, and urgently coordinate radiation oncology and spine surgery to choose decompression/stabilization and/or radiotherapy based on prognosis, stability and tumor sensitivity.",
    medicationSafety: "Dexamethasone can cause hyperglycemia, delirium, infection and GI complications and should not be continued indefinitely after definitive treatment. Anticoagulation and thrombocytopenia affect surgical/biopsy planning.",
    redFlags: "New motor weakness, sensory level, urinary retention/incontinence, saddle anesthesia, unstable vertebral collapse or rapidly progressive pain in a cancer patient is an oncologic emergency.",
    examTraps: "Do not wait for bowel/bladder dysfunction before imaging. A patient with known cancer and new mechanical/night back pain needs a lower threshold for MRI than routine nonspecific low-back pain.",
    sourceKeys: ["NCCN_SPINAL_CORD_COMPRESSION_CURRENT"],
  },
  {
    slug: "transient-ischemic-attack",
    title: "Transient Ischemic Attack",
    bodySystem: "Neurological",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Transient focal neurologic dysfunction from cerebral or retinal ischemia can precede completed stroke; symptom resolution does not make the event benign. Sudden unilateral weakness/numbness, aphasia, monocular vision loss or posterior-circulation symptoms need urgent vascular evaluation.",
    diagnostics: "Use urgent brain imaging—MRI with diffusion is preferred when rapidly available—plus vascular imaging of relevant cerebral/cervical arteries, ECG/rhythm evaluation and labs. Risk scores can support disposition but should not replace imaging and etiologic evaluation or be used alone to declare a patient safe.",
    priorities: "Treat as an emergency stroke-prevention opportunity: start antithrombotic therapy when hemorrhage/contraindications are addressed, use short-course dual antiplatelet therapy for selected high-risk noncardioembolic TIA/minor stroke, manage BP/lipids/diabetes and rapidly treat carotid or AF sources when found.",
    medicationSafety: "Anticoagulation is for cardioembolic indications such as AF, not added to antiplatelet therapy for every TIA. DAPT duration is short and indication-specific because longer combination therapy increases bleeding without proportional benefit.",
    redFlags: "Persistent deficit, recurrent/crescendo events, symptomatic carotid stenosis, AF with ongoing symptoms, severe headache or posterior-circulation instability requires emergency stroke-center care.",
    examTraps: "Do not reassure because symptoms resolved and do not diagnose TIA from nonspecific dizziness or generalized weakness without focal ischemic features. ABCD2 is not a substitute for urgent etiologic workup.",
    sourceKeys: ["AHA_TIA_CURRENT", "AHA_STROKE_PREVENTION_CURRENT"],
  },
  {
    slug: "carotid-artery-stenosis",
    title: "Carotid Artery Stenosis",
    bodySystem: "Neurological",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP"],
    recognize: "Atherosclerotic carotid stenosis is clinically important when it causes ipsilateral retinal or hemispheric TIA/stroke; a bruit is neither sensitive nor specific for severe disease. Asymptomatic stenosis follows a different benefit-risk calculus from recently symptomatic disease.",
    diagnostics: "Use carotid duplex for initial noninvasive assessment and CTA/MRA when anatomy/severity needs confirmation for intervention. Brain imaging defines infarct burden; evaluate competing stroke mechanisms such as AF rather than attributing every event to an incidental stenosis.",
    priorities: "Provide intensive medical therapy—statin, BP/smoking/diabetes management and antiplatelet therapy as indicated. Recently symptomatic high-grade stenosis may benefit from timely carotid endarterectomy in suitable patients; asymptomatic intervention is selective and depends on contemporary medical therapy, procedural risk and life expectancy.",
    medicationSafety: "Antiplatelet/statin therapy carries bleeding and interaction risks but is foundational; do not combine chronic anticoagulation and antiplatelets without a separate indication. Periprocedural BP and antithrombotic strategy requires the vascular team.",
    redFlags: "New TIA/stroke, amaurosis fugax, crescendo events or neurologic deterioration after carotid procedure requires emergency stroke evaluation.",
    examTraps: "Do not screen the general asymptomatic adult population routinely for carotid stenosis and do not refer every bruit for surgery. Degree of stenosis plus symptoms and procedural risk determine benefit.",
    sourceKeys: ["AHA_CAROTID_CURRENT", "SVS_CAROTID_CURRENT", "USPSTF_CAROTID_CURRENT"],
  },
  {
    slug: "migraine",
    title: "Migraine Diagnosis & Management",
    bodySystem: "Neurological",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "PMHNP", "WHNP", "ENP"],
    recognize: "Migraine typically causes recurrent moderate-severe headache with nausea and/or photophobia/phonophobia and may include reversible visual, sensory, language or other aura. A stable recurring phenotype supports migraine, but first/worst, abrupt or changing headaches require secondary-cause assessment.",
    diagnostics: "Diagnosis is clinical in a typical patient with normal neurologic examination; routine neuroimaging is unnecessary. Image/evaluate red flags such as thunderclap onset, focal deficit, papilledema, cancer/immunosuppression, pregnancy/postpartum high-risk features or major change in pattern.",
    priorities: "Treat acute attacks early with NSAID/acetaminophen or a migraine-specific agent such as triptan/gepant when appropriate; add preventive therapy for frequent/disabling attacks using CGRP-targeted therapy, traditional preventives or onabotulinumtoxinA for chronic migraine according to phenotype and preference.",
    medicationSafety: "Triptans are avoided in significant ischemic vascular disease and uncontrolled hypertension; gepants lack vasoconstriction but have drug interactions. Limit acute medication frequency to reduce medication-overuse headache and consider pregnancy safety for every preventive/acute drug in reproductive-age patients.",
    redFlags: "Thunderclap headache, new persistent focal deficit, meningismus, papilledema, severe pregnancy/postpartum headache, altered consciousness or headache after major trauma requires urgent evaluation.",
    examTraps: "Aura is not required for migraine and a normal CT does not complete a thunderclap-headache workup when residual SAH risk remains. Opioids are poor routine migraine treatment.",
    sourceKeys: ["AHS_MIGRAINE_CURRENT", "AAN_MIGRAINE_CURRENT"],
  },
  {
    slug: "cluster-headache",
    title: "Cluster Headache & Trigeminal Autonomic Cephalalgias",
    bodySystem: "Neurological",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "ENP"],
    recognize: "Cluster headache causes excruciating strictly unilateral orbital/supraorbital/temporal pain lasting roughly 15-180 minutes with ipsilateral autonomic features such as lacrimation, conjunctival injection, rhinorrhea or ptosis and marked restlessness, occurring in bouts with circadian pattern.",
    diagnostics: "Diagnosis is clinical when the phenotype is classic, but obtain brain MRI in a first presentation or atypical trigeminal autonomic cephalalgia to exclude structural mimics. Differentiate from migraine, trigeminal neuralgia, glaucoma, carotid dissection and cavernous-sinus disease.",
    priorities: "Abort attacks with high-flow 100% oxygen through a nonrebreather and/or rapid subcutaneous/intranasal triptan when appropriate; verapamil is a common preventive with ECG monitoring, and specialist transitional/alternative therapies are used for frequent bouts.",
    medicationSafety: "Triptans have vascular contraindications and daily-use limits; verapamil can cause bradycardia/heart block and needs ECG surveillance during escalation. Oral opioids and slow oral triptans are poor choices because attacks peak rapidly.",
    redFlags: "First severe unilateral headache with Horner syndrome, persistent neurologic deficit, painful red eye/vision loss, fever or an atypical continuous pattern requires urgent secondary-cause evaluation.",
    examTraps: "Cluster patients are often restless rather than lying still in a dark room like many migraine patients. Oxygen must be delivered at adequate flow/mask technique to be an effective abortive treatment.",
    sourceKeys: ["AHS_CLUSTER_CURRENT"],
  },
  {
    slug: "traumatic-intracranial-hematomas",
    title: "Epidural & Subdural Hematomas",
    bodySystem: "Neurological",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "AGPCNP-AANP", "AGPCNP-ANCC", "AGACNP", "ENP"],
    recognize: "Epidural hematoma classically follows arterial injury between skull and dura and may deteriorate rapidly; subdural hematoma results from bridging-vein bleeding and is common in older adults, anticoagulated patients and abusive head trauma. A lucid interval is possible but not required for epidural hematoma.",
    diagnostics: "Obtain urgent noncontrast head CT for concerning trauma/neurologic change; epidural collections are typically biconvex and limited by sutures, while subdural collections are crescentic and can cross sutures. Check anticoagulant use/coagulation and repeat imaging when clinical deterioration or lesion risk warrants it.",
    priorities: "Stabilize airway/cervical spine, prevent hypotension/hypoxia, reverse anticoagulation when indicated and involve neurosurgery urgently for significant mass effect, neurologic decline or lesions meeting operative criteria. Chronic subdural hematoma may require drainage even after seemingly minor trauma.",
    medicationSafety: "Avoid sedatives that obscure neurologic decline unless needed for airway/critical care; use agent-specific anticoagulant reversal. Seizure prophylaxis is indication-specific and not a substitute for decompression of mass effect.",
    redFlags: "Falling GCS, fixed/dilated pupil, new hemiparesis, repeated vomiting, seizure, anticoagulated head injury with change or CT midline shift/herniation requires emergency neurosurgical care.",
    examTraps: "Do not require a lucid interval for epidural hematoma and do not dismiss delayed confusion weeks after a fall in an older adult—chronic subdural hematoma can evolve slowly.",
    sourceKeys: ["BTF_SEVERE_TBI_CURRENT", "ACS_TQIP_TBI_CURRENT"],
  }
] as const satisfies readonly UsNpCramLesson[];
