import type { UsNpCramLesson } from "./us-np-cram-types";

export const usNpCramBatch35 = [
  {
    slug: "delayed-puberty",
    title: "Delayed Puberty: Molecular Mechanisms",
    slugAliases: ["delayed-puberty-np"],
    bodySystem: "Reproductive",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PNP", "WHNP"],
    recognize: "Delayed puberty is absence of expected pubertal development beyond the usual age range or failure to progress normally. Constitutional delay is common, but chronic illness, undernutrition, excessive exercise, gonadal failure, pituitary/hypothalamic disease and genetic conditions must be separated using growth and pubertal trajectory.",
    diagnostics: "Confirm Tanner stage and growth velocity, then use morning LH/FSH with estradiol or testosterone, TSH/free T4 and targeted CBC/CMP/inflammatory or celiac testing based on context. High gonadotropins suggest primary gonadal failure; low/inappropriately normal gonadotropins suggest central or functional hypogonadism. Bone age and selective MRI/genetic testing refine the cause.",
    priorities: "Treat the underlying disease, restore adequate nutrition/energy availability when deficient and refer persistent or pathologic delay to pediatric/adolescent endocrinology. Sex-steroid induction can support bone, body composition and psychosocial development when indicated, with gradual dosing designed to mimic normal puberty.",
    medicationSafety: "Testosterone or estrogen induction requires diagnosis, growth/bone-age context and monitoring; supraphysiologic dosing can advance bone age or cause adverse effects. Do not prescribe hormones merely to normalize appearance before excluding endocrine, nutritional and genetic disease.",
    redFlags: "Neurologic symptoms, anosmia with suspected congenital hypogonadotropic hypogonadism, severe weight loss/eating disorder, galactorrhea/visual symptoms, ambiguous genital history or systemic chronic disease requires expedited specialty evaluation.",
    examTraps: "Do not diagnose constitutional delay from one late Tanner stage without family/growth history. Primary and central hypogonadism have opposite gonadotropin patterns, and obesity can complicate visual assessment of pubertal development.",
    sourceKeys: ["ENDOCRINE_PEDIATRIC_PUBERTY_CURRENT"],
  },
  {
    slug: "central-precocious-puberty",
    title: "Precocious Puberty: Molecular Mechanisms",
    slugAliases: ["precocious-puberty-np"],
    bodySystem: "Reproductive",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PNP", "WHNP"],
    recognize: "Central precocious puberty reflects early hypothalamic-pituitary-gonadal activation, traditionally before age 8 in girls and 9 in boys. Rapid progression, growth acceleration and advancing bone age matter; isolated benign variants such as premature thelarche or adrenarche do not require the same workup.",
    diagnostics: "The 2026 Endocrine Society guideline favors an ultrasensitive basal LH as the initial test when evaluation is needed, with GnRH/GnRHa stimulation selectively. Assess bone age and sex steroids; brain MRI is not routine for every asymptomatic girl age 6-8 or boy age 8-9 and should follow age, sex, neurologic findings and progression risk.",
    priorities: "Observe selected older girls with slowly progressive puberty rather than automatically testing/treating all early development. Use long-acting GnRH agonist therapy for children most likely to benefit in adult-height, progression or psychosocial terms, with pediatric endocrine follow-up and clinical growth/puberty monitoring.",
    medicationSafety: "GnRH agonists can cause transient pubertal flare and require adherence to long-acting dosing; routine repeated biochemical suppression testing is not recommended when clinical response is satisfactory. Do not add growth hormone routinely to GnRH agonist therapy.",
    redFlags: "Very young onset, neurologic symptoms, rapid virilization, café-au-lait/fibrous dysplasia clues, marked growth acceleration or discordant peripheral sex-steroid effects requires expedited endocrine/CNS evaluation.",
    examTraps: "Do not order brain MRI and GnRH stimulation for every 7- to 8-year-old girl with slow breast development. The 2026 guideline explicitly supports more selective testing and treatment in lower-risk subgroups.",
    sourceKeys: ["ENDOCRINE_CPP_2026"],
  },
  {
    slug: "primary-dysmenorrhea",
    title: "Dysmenorrhea: COX-2 Pathways",
    slugAliases: ["dysmenorrhea-np"],
    bodySystem: "Reproductive",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "PNP", "WHNP"],
    recognize: "Primary dysmenorrhea causes cyclic cramping pain beginning around menses from endometrial prostaglandin production and uterine hypercontractility/ischemia. Pain beginning years after menarche, progressive severity, dyspareunia, abnormal bleeding, infertility or poor response to therapy raises concern for endometriosis or another secondary cause.",
    diagnostics: "A typical adolescent/young adult presentation can be diagnosed clinically without imaging. Perform pelvic examination and ultrasound when symptoms are atypical, severe, progressive or refractory, and evaluate pregnancy, infection, endometriosis, adenomyosis or structural disease according to the phenotype.",
    priorities: "Use NSAIDs started at symptom onset or shortly before expected menses when predictable, plus heat/exercise and hormonal suppression when contraception is desired or NSAIDs are inadequate. Persistent symptoms after an adequate empiric trial merit gynecologic evaluation for secondary dysmenorrhea/endometriosis.",
    medicationSafety: "NSAIDs carry GI, renal, bleeding and cardiovascular risks and should not be combined indiscriminately. Hormonal methods require standard thrombosis, migraine, smoking and other contraindication screening; continuous regimens can be appropriate for menstrual suppression.",
    redFlags: "Positive pregnancy test with severe pain/bleeding, fever/cervical motion tenderness, acute torsion pattern, hemodynamic bleeding or rapidly progressive pelvic pain requires urgent evaluation.",
    examTraps: "Do not require laparoscopy before treating likely primary dysmenorrhea, but do not repeatedly escalate NSAIDs for years when pain is refractory or accompanied by secondary-cause clues.",
    sourceKeys: ["ACOG_DYSMENORRHEA_ENDOMETRIOSIS_CURRENT"],
  },
  {
    slug: "abnormal-uterine-bleeding-palm-coein",
    title: "Abnormal Uterine Bleeding: PALM-COEIN",
    slugAliases: ["aub-palm-coein-np"],
    bodySystem: "Reproductive",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "WHNP", "ENP"],
    recognize: "PALM-COEIN organizes nongravid reproductive-age AUB into structural causes—polyp, adenomyosis, leiomyoma, malignancy/hyperplasia—and nonstructural causes—coagulopathy, ovulatory dysfunction, endometrial, iatrogenic and not otherwise classified. First determine whether bleeding is acute/hemodynamically important or chronic.",
    diagnostics: "Obtain pregnancy testing and CBC; add TSH/coagulation/iron or endocrine testing when history indicates. Transvaginal ultrasound evaluates structural disease, while endometrial sampling is guided by age and risk for hyperplasia/cancer rather than performed on every younger patient. ACOG reaffirmed the PALM-COEIN diagnostic framework in 2024.",
    priorities: "Stabilize major bleeding, correct iron deficiency and match hormonal/nonhormonal therapy to cause, severity, contraception and fertility goals. Structural lesions or persistent bleeding despite medical therapy may need hysteroscopy, myomectomy, ablation or hysterectomy depending on diagnosis and reproductive plans.",
    medicationSafety: "High-dose estrogen/combined regimens are inappropriate with major thrombotic contraindications; tranexamic acid requires thrombosis-risk review and is not combined casually with estrogen in high-risk patients. Progestin-only options are useful when estrogen is contraindicated.",
    redFlags: "Hemodynamic instability, symptomatic severe anemia, pregnancy-related bleeding, postmenopausal bleeding, suspected malignancy, severe pelvic pain or coagulopathy requires urgent/expedited evaluation.",
    examTraps: "Do not label all heavy bleeding 'dysfunctional uterine bleeding.' PALM-COEIN directs the differential, and chronic anovulation can increase endometrial-hyperplasia risk even in younger patients.",
    sourceKeys: ["ACOG_AUB_PALM_COEIN_REAFFIRMED_2024", "ACOG_AUB_OVULATORY_REAFFIRMED_2025"],
  },
  {
    slug: "pcos-insulin-androgen-pathophysiology",
    title: "PCOS: Insulin-Androgen Cascade",
    slugAliases: ["pcos-molecular-np"],
    bodySystem: "Reproductive",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "WHNP"],
    recognize: "PCOS combines ovulatory dysfunction, clinical/biochemical hyperandrogenism and polycystic ovarian morphology/AMH criteria in appropriate adults. Insulin resistance can amplify ovarian/adrenal androgen production and suppress SHBG, but not every patient with PCOS is obese or insulin resistant.",
    diagnostics: "Apply current international diagnostic criteria after excluding pregnancy, thyroid disease, hyperprolactinemia, nonclassic CAH and other androgen excess. Ultrasound/AMH is not required when irregular cycles and hyperandrogenism already establish two diagnostic features; adolescent criteria are more conservative and avoid overdiagnosis.",
    priorities: "Treat the patient's goals: lifestyle/metabolic risk, combined hormonal contraception for cycle control/hyperandrogenism when appropriate, metformin for metabolic indications, antiandrogens with reliable contraception, and letrozole as first-line pharmacologic ovulation induction for infertility when no other infertility factor changes the plan.",
    medicationSafety: "Spironolactone is teratogenic to a male fetus and requires reliable contraception; metformin causes GI effects/B12 deficiency risk; estrogen-containing contraception requires thrombosis/migraine/smoking risk review. Avoid treating isolated ovarian morphology as disease.",
    redFlags: "Rapid virilization, very high androgens, clitoromegaly, deepening voice, Cushing features or pelvic/adrenal mass symptoms requires urgent evaluation for tumor or another endocrine cause.",
    examTraps: "PCOS is not diagnosed by an ultrasound full of follicles alone. Routine fasting-insulin testing is not required for diagnosis, and adolescents with normal pubertal irregularity should not be prematurely labeled.",
    sourceKeys: ["PCOS_INTERNATIONAL_2023"],
  },
  {
    slug: "pelvic-inflammatory-disease",
    title: "PID: CDC Guidelines",
    slugAliases: ["pid-np"],
    bodySystem: "Reproductive",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "WHNP", "PNP", "ENP"],
    recognize: "PID is ascending upper-genital-tract infection and can be subtle; pelvic/lower abdominal pain with cervical motion, uterine or adnexal tenderness in a sexually active at-risk patient warrants a low threshold for empiric treatment after excluding dangerous alternatives.",
    diagnostics: "Obtain pregnancy test, gonorrhea/chlamydia NAAT and test for HIV/syphilis as appropriate; wet mount can identify concomitant BV/trichomoniasis. Ultrasound is useful when tubo-ovarian abscess, torsion, ectopic pregnancy or diagnostic uncertainty is present, but a normal ultrasound does not exclude uncomplicated PID.",
    priorities: "Start empiric broad treatment promptly rather than waiting for NAAT confirmation; outpatient regimens cover gonorrhea, chlamydia and anaerobes, while pregnancy, severe illness, abscess, surgical emergency or inability to tolerate oral therapy favors hospitalization. Reassess clinical improvement within about 72 hours.",
    medicationSafety: "Current CDC outpatient therapy includes ceftriaxone plus doxycycline and metronidazole; treatment should not be shortened because tests are negative. Doxycycline pregnancy considerations and cephalosporin allergy history require individualized alternatives.",
    redFlags: "Pregnancy, tubo-ovarian abscess, severe systemic illness, peritonitis, hemodynamic instability, inability to exclude surgical emergency or failure to improve within 72 hours requires escalation.",
    examTraps: "Negative gonorrhea/chlamydia tests do not exclude PID, and absence of fever does not make the diagnosis benign. Delaying treatment increases infertility and chronic pelvic pain risk.",
    sourceKeys: ["CDC_STI_CURRENT_PID"],
  },
  {
    slug: "vaginitis-vaginal-microbiome",
    title: "Vaginitis: Vaginal Microbiome",
    slugAliases: ["vaginitis-np"],
    bodySystem: "Reproductive",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "WHNP", "PNP"],
    recognize: "Vaginal symptoms reflect shifts in flora, inflammation or infection. BV usually raises pH with odor/thin discharge, candidiasis causes pruritus/inflammation with normal pH, and trichomoniasis commonly causes inflammatory discharge with elevated pH; symptoms overlap too much for confident diagnosis by history alone.",
    diagnostics: "Use pelvic exam plus pH, microscopy/amine testing or validated molecular assays based on availability. Test STI/cervicitis when risk or exam suggests it and consider dermatologic, foreign-body, genitourinary syndrome or desquamative inflammatory disease when standard infectious tests are negative.",
    priorities: "Treat the identified cause rather than empirically cycling through antifungals and antibiotics. Recurrent or refractory disease warrants confirmation of diagnosis, species/resistance considerations for candidiasis and evaluation for noninfectious vulvovaginal disease.",
    medicationSafety: "Azole, metronidazole and other therapies differ in pregnancy suitability, drug interactions and formulation. Repeated empiric fluconazole can select resistant non-albicans Candida and should not replace culture/speciation in recurrent complicated disease.",
    redFlags: "Fever, pelvic pain, pregnancy complications, ulcerative lesions, severe edema/cellulitis, immunocompromise or toxic appearance requires evaluation beyond routine vaginitis.",
    examTraps: "Discharge appearance is not enough to distinguish BV, Candida and trichomoniasis. A normal pH makes BV/trichomoniasis less likely but does not by itself diagnose yeast.",
    sourceKeys: ["CDC_STI_CURRENT_BV", "CDC_STI_CURRENT_VVC", "CDC_STI_CURRENT_TRICH"],
  },
  {
    slug: "bacterial-vaginosis-microbiome",
    title: "Bacterial Vaginosis: Molecular Microbiome",
    slugAliases: ["bacterial-vaginosis-np"],
    bodySystem: "Reproductive",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "WHNP", "PNP"],
    recognize: "BV is vaginal dysbiosis with loss of Lactobacillus dominance and overgrowth of anaerobic/biofilm-associated organisms. It often produces thin homogeneous discharge and fishy odor with elevated pH but little vulvar inflammation, and many patients are asymptomatic.",
    diagnostics: "Diagnose symptomatic BV with Amsel criteria, Nugent scoring or validated molecular assays. Routine culture of Gardnerella is not useful because it can be present without BV; evaluate STI risk because BV is associated with increased acquisition risk.",
    priorities: "Treat symptomatic BV with recommended oral or intravaginal metronidazole or clindamycin regimens. Recurrent disease may need extended/suppressive strategies after confirming diagnosis; routine treatment of male partners is not standard under current CDC guidance.",
    medicationSafety: "Clindamycin cream can weaken latex condoms/diaphragms temporarily; metronidazole interacts with warfarin and can cause GI effects. Current evidence does not require avoiding alcohol solely because metronidazole is prescribed, although adverse GI effects still warrant counseling.",
    redFlags: "Pregnancy with symptoms, pelvic pain/fever, postoperative pelvic infection or recurrent symptoms not responding to confirmed therapy requires broader evaluation.",
    examTraps: "BV is not simply a sexually transmitted infection and Gardnerella culture does not diagnose it. Do not diagnose BV from odor alone without appropriate clinical/laboratory criteria.",
    sourceKeys: ["CDC_STI_CURRENT_BV"],
  },
  {
    slug: "cervicitis-pathogen-biology",
    title: "Cervicitis: Pathogen Molecular Biology",
    slugAliases: ["cervicitis-np"],
    bodySystem: "Reproductive",
    applicableExams: ["AANP-FNP", "ANCC-FNP", "WHNP", "PNP", "ENP"],
    recognize: "Mucopurulent endocervical discharge and easily induced endocervical bleeding suggest cervicitis. Chlamydia and gonorrhea are key pathogens, but trichomoniasis, HSV and Mycoplasma genitalium can contribute; many cases have no organism identified.",
    diagnostics: "Obtain NAAT for gonorrhea/chlamydia, test trichomoniasis and BV as indicated and assess for PID. Consider M. genitalium NAAT in persistent/recurrent cervicitis rather than repeatedly giving empiric macrolides; routine Ureaplasma testing is not recommended.",
    priorities: "Treat empirically for chlamydia in higher-risk patients or when follow-up/testing cannot be assured, add gonorrhea therapy based on risk/local prevalence, manage partners and abstinence interval, and reassess persistent symptoms for reinfection, M. genitalium or noninfectious cervical disease.",
    medicationSafety: "Current CDC gonorrhea dosing is weight-based ceftriaxone and doxycycline is used for chlamydia when pregnancy is not present; do not routinely combine ceftriaxone+doxycycline for every cervicitis regardless of gonorrhea risk. Pregnancy changes chlamydia treatment.",
    redFlags: "Pelvic pain, fever, cervical motion/adnexal tenderness, pregnancy with pain/bleeding, disseminated infection or severe genital ulcer disease requires urgent expanded evaluation.",
    examTraps: "Cervical ectropion is not cervicitis, and a negative gonorrhea/chlamydia NAAT does not automatically justify repeated broad antibiotics. Persistent cervicitis should trigger diagnostic reconsideration.",
    sourceKeys: ["CDC_STI_CURRENT_CERVICITIS", "CDC_STI_CURRENT_MGEN"],
  }
] as const satisfies readonly UsNpCramLesson[];
